safe-global/safe-wallet-monorepo

- jest.setup.js
- package.json
- yarn.lock
Removes unnecessary dependency
`whatwg-fetch` has been uninstalled.
Observe the tests passing.
> Chore: remove `whatwg-fetch`

- src/components/common/CookieBanner/index.tsx
- src/definitions.d.ts
- src/services/analytics/TagManager.ts
- src/services/analytics/__tests__/TagManager.test.ts
- src/services/analytics/gtm.ts
- src/services/analytics/useGtm.ts
- src/services/analytics/useMetaEvents.ts
We want to make GA more useful by tracking 100% of users. GA4 has a so-called "consent mode" which doesn't set any cookies and doesn't require a cookie consent. This PR enables this mode, and enables GA cookies only if the user opts in.
See https://www.notion.so/safe-global/Client-side-analytics-improvements-152dad5585d6410b8e6cfb20334d6c05
* Open the branch preview site
* Observe that GTM events are fired w/o accepting the Cookie Banner
* Check that the GA script is loaded with `gcs: G100` parameter (which means cookies are disabled).
* Check that no _ga cookies are set
* Press "Accept all" in the cookie banner
* Observe that GA cookies are added
* Observe that GA requests now contain `gcs: G101` param (meaning cookies are enabled)
> Feat: load analytics in cookie-less mode

- src/components/tx-flow/flows/SignMessage/SignMessage.test.tsx
- src/components/tx-flow/flows/SignMessage/SignMessage.tsx
- src/hooks/loadables/useLoadSafeMessages.ts
- src/hooks/messages/useSafeMessage.ts
- src/hooks/messages/useSafeMessages.ts
- src/hooks/messages/useSyncSafeMessageSigner.ts
- src/services/safe-messages/safeMsgNotifications.ts
Resolves #2019 
- Changes text
- Adds a Success Card
- Shows Success Card for 1s when message is fully signed
- immediately re-fetches message after signing
- Open a 2/3 Safe
- Create a message signing request through Wallet connect
- Add the first signature
- Observe that it gets added immediately
- Change the owner
- Add a second signature
- Observe new success card with Continue button
- It should disappear after 1s
> fix: better UX for off-chain message signing

- src/components/common/AddressInput/index.tsx
Resolves #2378
If a valid address is inputted, it should show an identicon instead of a placeholder.
> Fix: AddressInput identicon

- src/components/new-safe/create/steps/StatusStep/StatusMessage.tsx
- src/components/new-safe/create/steps/StatusStep/StatusStepper.tsx
Resolves #2396
Just a few small edits for the Safe Creation statuses.
> Fix: text changes in Safe Creation

- src/components/tx-flow/flows/AddOwner/index.tsx
- src/config/routes.ts
- src/pages/addOwner.tsx
Resolves #2381 
- Adds a new route `/addOwner` that redirects to the `/settings/setup` page
- Opens the txFlow with pre-filled address
1. Open `/addOwner?safe=<your safe address>&address=<the address you want to add as an owner>`
2. Add owner txFlow opens with the address filled in
3. Open `/addOwner?safe=<your safe address>`
4. Redirected to the settings page but no txFlow opening
5. Open `/addOwner?safe=<your safe address>&address=<an invalid address>`
6. Redirected to the settings page and txFlow opens with the address value but an error for invalid value is displayed
> fix: Add addOwner route and open tx flow

- src/hooks/loadables/useLoadSpendingLimits.ts
Reduces `eth_call` requests
The `length` of the `modules` array is checked instead of the array itself when requesting spending limit details in `useLoadSpendingLimits`.
`useAsync` linting [changed the `safe.modules` `length` dependency](https://github.com/safe-global/safe-wallet-web/pull/2291/files#diff-8696548ccdc8dd843d851f0db58d34d722702c7c69eb48549a153b125b8eb640R109) in favour of `safe.modules`. This caused the increase of `eth_call` requests as a new instance of the Safe info is returned every poll [due to the `loading` flag](https://github.com/safe-global/safe-wallet-web/blob/8f92a0d9106ed89f897cae2eb5f58f6b88d4ef4b/src/hooks/useSafeInfo.ts#L24-L25) in `useSafeInfo`.
Open a Safe with spending limits enabled and observe a reduced number of `eth_call`s when compared to prod.
> fix: don't over-poll Spending Limits data

- src/components/privacy/index.tsx
* Added that IP addresses are not stored for EU users.
* Clarifies that the cookie consent is only given for analytics cookies that will not be otherwise set.
> Fix: adjust privacy policy wrt tracking

- src/hooks/wallets/useOnboard.ts
- src/utils/__tests__/wallet.test.ts
- src/utils/wallets.ts
Resolves #2306
The cause of the bug was that
* `window.ethereum.isConnected()` returns true even if MetaMask is locked
* We didn't await the promise from `_metamask.isUnlocked` and it always returning false
I've removed `isConnected` and made it wait for the promise. Also added custom logic for WC v2 and tests for it.
> Fix: re-connecting a locked wallet

- src/components/common/WalletInfo/styles.module.css
- src/styles/onboard.css
Resolves #2374
I've replaced our custom white background on wallet buttons with a semi-transparent white, so that it works for both dark and light icons.
> Fix: wallet icons in dark mode

- src/hooks/__tests__/useSafeTokenAllocation.test.ts
- src/hooks/useSafeTokenAllocation.ts
- src/utils/__tests__/wallets.test.ts
- src/utils/wallets.ts
Reduces `eth_call` requests
The request for `redeemDeadline` in `useSafeTokenAllocation` is now memoized according to the `chainId` and `address` meaning it will only request once per specific address on a chain. `isSmartContractWallet` has been memoized in a similar fashion.
- Switch Mainnet/Goerli and observe one less request for getting the redemption deadline (from `useSafeTokenAllocation` in the call stack). The values should match that as on prod.
- Switch between the option of executing via relayer/wallet by going back/forward in Safe creation and observe one less request for checking the contract code (from `useWalletCanRelay` -> `isSmartContractWallet` in the call stack).
> fix: memoize deadline + smart contract check calls

- src/components/tx-flow/common/TxLayout/index.tsx
- src/components/tx-flow/common/TxStatusWidget/index.tsx
- src/components/tx-flow/flows/SignMessage/index.tsx
Resolves #2384
When signing a message, it will say "Message status" instead of "Transaction status".
> Fix: status widget for 1271 messages

- cypress/e2e/smoke/batch_tx.cy.js
- src/components/batch/BatchSidebar/BatchTxItem.tsx
- src/components/batch/BatchSidebar/BatchTxList.tsx
Add e2e for the batch tx feature
Tests:
Empty state
Add to batch button present in the tx form
Adding 2 tx in a batch
Swapping tx order
Checking the order in the tx form
Delete a tx from the batch
> [e2e Test] WIP e2e batch transactions

- cypress/e2e/smoke/tx_history.cy.js
- src/components/safe-apps/SafeAppIconCard/index.test.ts
- src/components/safe-apps/SafeAppIconCard/index.tsx
Resolves #2419
This PR checks if an icon src is a relative path or comes from one of our own domains, and inserts it as a regular image in that case. Otherwise, it embeds it in a sandboxed iframe like before.
> Fix: do not sandbox safe icon URLs

- src/components/batch/BatchIndicator/index.tsx
- src/components/common/Header/index.tsx
Resolves #2425
Hides the Batch icon if there's no Safe on that URL.
* Go to a page like Welcome and see that there's no Batch button in the header
> Fix: hide Batch icon if not on a Safe route

- src/components/batch/BatchSidebar/BatchTxItem.tsx
- src/components/common/EthHashInfo/index.test.tsx
- src/components/common/EthHashInfo/index.tsx
- src/components/transactions/TxDetails/Summary/TxDataRow/index.tsx
- src/components/transactions/TxDetails/TxData/DecodedData/MethodDetails/index.tsx
- src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx
- src/components/transactions/TxDetails/TxData/DecodedData/ValueArray/index.tsx
- src/components/transactions/TxDetails/TxData/DecodedData/ValueArray/styles.module.css
- src/components/transactions/TxDetails/TxData/DecodedData/index.tsx
- src/components/transactions/TxDetails/TxData/Transfer/index.tsx
- src/components/tx/DecodedTx/index.tsx
Resolves #2422
Displays name and icon for known addresses in decoded tx details and in multisend details.
* Open a 1.1.1 Safe
* Create a tx to upgrade it to 1.3.0
* See that the mastercopy and fallback handler addresses have a name and icon
> Fix: show known addresses in decoded tx data

- src/components/common/TxModalDialog/styles.module.css
Resolves #2429 
Removes the z-index for the close button
1. Scroll down in the tx flow window
2. Try to press elements that are at the top of the screen e.g. nonce form
3. Observe that its possible to interact with them
> fix: TxFlow close button zindex

- src/components/common/NetworkSelector/index.tsx
Resolves #2412
(same as #2433 but this time with updated git config so I can actually sign the CLA 🙂 )
The `<Paper>` component surrounding the `<NetworkSelector>` had `overflow: visible`, which led to network names potentially being displayed outside the network selector box on small resolutions.
Overriding this specific style with `overflow: auto` fixes the issue and makes the network selector scrollable when vertical screen space is insufficient.
1. Open this branch on dev
2. Open the network selector on a normal desktop resolution and see that it still works as before
3. Open the network selector on a small resolution with low vertical pixel size so that the list of chain names is longer than the screen is able to show
4. See that there's now a scrollbar, and the chain names no longer …
> fix: chain names overflow menu on small resolutions

- package.json
- src/hooks/__tests__/useGasPrice.test.ts
- src/hooks/useDecodeTx.ts
- src/hooks/useGasPrice.ts
- yarn.lock
This PR fixes the usage of chain gas configs in general and adds a new fixed gas config.
Resolves #2222 
Enabled fixed gas prices for EIP-1559
**Fixed 1559 gas prices**
We added Optimism with the desired gas price config to staging and enabled 1559 there.
1. Create any tx on optimism staging
2. Go to execute modal
3. Expand the gas price details
4. Observe 0.1 for maxFeePerGas and 0.0001 for maxPriorityFeePerGas
5. Execute
6. Observe same values in i.e. connected metamask
**Bug fix: Use gas price configs**
This PR also fixed our gas estimations in general which never considered the gas price configs from our config service before.
To test this try to create transactions on networks with specific gas price configs:
- Gas price oracles
- Mainnet
- Polygon
- Fixed
- Görli
The screenshot …
> feat: eip-1559 fixed gas prices

- src/services/analytics/gtm.ts
- src/services/analytics/types.ts
- src/services/analytics/useGtm.ts
Sending a device type manually would allow us to disable the "[Granular location & device data](https://support.google.com/analytics/answer/12002752?hl=en&utm_id=ad)" on GA.
* Open the app on desktop – every GTM event should have `deviceType: 'desktop'`
* Open the app on a tablet (or just resize the window to < 900px) – every GTM event should have `deviceType: 'tablet'`
* Open the app on mobile – – every GTM event should have `deviceType: 'mobile'`
> Feat: send deviceType to GTM

- src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx
A follow-up on #2423
In multisend actions, in addition to displaying the contract method, show the contract name if it comes from the backend.
Before:
After:
> Feat: show contract names in multisend summary

- src/components/transactions/TxDetails/TxData/index.tsx
- src/components/transactions/TxDetails/index.tsx
- src/components/transactions/TxInfo/index.tsx
- src/services/contracts/safeContracts.ts
- src/utils/__tests__/transactions.test.ts
- src/utils/transaction-guards.ts
safe-deployments 1.2.6 made Safe 1.4.1 the default. See https://github.com/safe-global/safe-deployments/pull/248
This breaks our code because we were always retrieving multisend contract addresses w/o a version. It worked for 1.3.0 but not for any other version.
1.
* Open a single transaction view for a multisend tx on Safe 1.3.0 on mainnet
* Open a single transaction view for a multisend tx on Safe 1.1.1 on mainnet
* Open a single transaction view for a multisend tx on Safe 1.3.0 on Polygon
* Multisend details should be displayed for all of them
2.
* Create and execute a multisend tx in a 1.3.0 Safe
* Create and execute a multisend tx in a 1.1.1 Safe
> Fix: multisend verification only worked for the latest contract version

- src/components/batch/BatchSidebar/index.tsx
Resolves #2428
If the batch confirmation flow is open, it is now closed when the last draft is removed via the sidebar.
Batch transaction(s) and enter the confirmation flow. Whilst in the flow, remove the last draft from the sidebar and observe the confirmation flow close. It should _not_ close other flows that may be open under the sidebar.
> fix: close batch flow when removing last draft

- jest.setup.js
- package.json
- src/components/licenses/index.tsx
- src/hooks/wallets/consts.ts
- src/hooks/wallets/useOnboard.ts
- src/hooks/wallets/wallets.ts
- yarn.lock
When MetaMask is intalled:
When Taho is installed:
> Fix: rm WalletConnect v1 and Taho; reorder wallets

- src/store/batchSlice.ts
- src/store/settingsSlice.ts
Resolves console warning/unnecessary re-renders
If a selector returns a new reference, it should be memoised either manually or inside `createSelector`, etc. The following changes solved the console warning:
- `selectAllBatches` no longer returns an empty array but the `initialState`.
- `selectHiddenTokensPerChain` now leverages `createSelector` as it can return an empty array.
- Run the project locally and observe no console warnings.
- Batching should work as expected.
- Hiding/showing spam tokens should work as expected.
Console warning in question:
> fix: selector reference warnings

- src/components/batch/BatchSidebar/index.tsx
Resolves #2404
The batch sidebar buttons are now disabled if the user is not connected or not an owner.
As a non-owner open the sidebar and observe the disabled buttons with tooltip when a batch _doesn't_ exists and when one _does_.
As an owner or non-owner open the sidebar and observe the enabled buttons tooltip when a batch _doesn't_ exists and when one _does_.
> fix: disabled batch sidebar buttons when not owner

- cypress/e2e/smoke/address_book.cy.js
- cypress/e2e/smoke/batch_tx.cy.js
The address-book e2e test often fails if the provider call to resolve ENS takes too long. The ENS lookup is already covered by tests for the `AddressInput` and it is not possible to intercept the call via cypress so we can remove it there.
- Removes the ENS lookup from the address book e2e test
> fix: Remove ENS lookup from address book e2e test

- src/components/common/SafeTokenWidget/__tests__/SafeTokenWidget.test.tsx
- src/components/common/SafeTokenWidget/index.tsx
- src/components/common/SafeTokenWidget/styles.module.css
- src/hooks/__tests__/useSafeTokenAllocation.test.ts
- src/hooks/useSafeTokenAllocation.ts
- src/services/analytics/events/overview.ts
Implements claim button in header
The token allocation element in the header now includes a "New allocation" button according to [the designs](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=7969-133988&mode=design&t=6FeK1GEhF8jSaoo7-0). Clicking it will take you to the claiming app and, providing there is nothing to claim, it should not appear.
Open a Safe with an allocation and observe the new button. Claiming should make it dissappear and opening a Safe _without_ an allocation should not show it at all.
Clicking on the button should the following event: "Click on SEP5 allocation button".
> feat: add claim button to header

- src/hooks/useSafeTokenAllocation.ts
Resolves https://github.com/safe-global/safe-wallet-web/pull/2462#issuecomment-1700369218
The balance is first converted to a `BigNumber`. "Empty" balances were returned as `0x` which caused `add` to throw.
Switch from `gno:0xB8d760a90a5ed54D3c2b3EFC231277e99188642A` to `eth:0x8675B754342754A30A2AeF474D114d8460bca19b` and observe no crash. Switching the other way should not either.
> fix: SAFE token balance in header

- src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
- src/hooks/wallets/useInitWeb3.ts
Fixes https://github.com/safe-global/safe-wallet-web/pull/2462#issuecomment-1700332666
Reverts a part of #2418.
> Fix: revert using wallet RPC for readonly RPC

- src/components/tx-flow/index.tsx
- src/hooks/__tests__/useChainId.test.ts
- src/hooks/useChainId.ts
- src/tests/pages/apps.test.tsx
Fixes https://github.com/safe-global/safe-wallet-web/pull/2462#issuecomment-1700761074
In Next 13, we cannot use useRouter from the App component.
> Fix: Next 13 - useRouter() -> usePathName(), useParams()

- src/components/common/Track/index.tsx
Resolves #2405
Elements wrapped in `Track` now check whether the `children` is targetted. If not, it means that the clicked `target` is disabled and, as such, not tracked.
Click the following elements whilst disabled and observe no tracking event for them:
- Adding an owner
- Removing an owner
- Replacing an owner
- Change policies
- Adding a spending limit
- Removing a spending limit
- "Send" button in the assets table
- "Send" from the address book
- "Add to batch" from a tx from
- "New transaction" from the Add to batch section that opens from the topbar
- "Add a new tx" that shows when there are already batched tx in the menu displayed from the top bar
- "Confirm batch" from that same menu
> fix: don't track clicks on disabled elements

- src/components/new-safe/load/index.tsx
Resolves #2438
The `CardStepper` now has the `address` assigned as a `key` to trigger a re-render if an `address` parameter is in the URL as the `query` is not initially available.
Open the load Safe flow with an `address` search parameter and observe the field populated. Changing the address and navigating forwards/backwards should *not* result in the URL `address` repopulating the field.
> fix: populate address from URL in load Safe flow

- src/components/new-safe/create/logic/index.ts
- src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
- src/components/tx/SignOrExecuteForm/SignForm.tsx
- src/services/exceptions/ErrorCodes.ts
We now have almost no uncaught exceptions on Sentry, so we can track more stuff.
Like failed executions, signatures and Safe creations. This might help when debugging support requests.
> Chore: track tx errors on Sentry

- src/config/constants.ts
The `-nest` name in the domain name should not be used anymore and will be removed in the future. This PR updates the respective value to use the new supported URL.
- Updates the default value set for `SAFE_RELAY_SERVICE_URL_STAGING` from `https://safe-client-nest.staging.5afe.dev/v1/relay` to `https://safe-client.staging.5afe.dev/v1/relay`
- Updates the default value set for `SAFE_RELAY_SERVICE_URL_PRODUCTION` from `https://safe-client-nest.safe.global/v1/relay` to `https://safe-client.safe.global/v1/relay`
NA
NA
> Update default value for Relay Service URL

- src/services/pairing/QRModal.tsx
Resolves #2225
After the mobile pairing modal is closed, we reset the body element's overflow style.
> Fix: reset body scroll after mobile pairing

- src/components/welcome/NewSafe.tsx
It changes the order of "welcome to safe{wallet}" component in the welcome screen in mobile view
Resolves #2473 
Using the Row-reverse property of grid, it changes the order of the components on mobile view
In desktop view, The import component will be in left and the welcome component will be in right
In mobile view, The welcome component will be in top and the import component will be in bottom
Desktop:
Mobile:
> style: welcome screen re-ordering enhancement for mobile view

- src/components/dashboard/PendingTxs/PendingTxListItem.tsx
- src/components/dashboard/PendingTxs/styles.module.css
Resolves #2060
Uses flex-box like in the BatchTxItem.
> Fix: [Dashboard] better layout for pending txs

- .github/workflows/cla.yml
- .vscode/settings.json
- cypress/e2e/add_owner.cy.js
- cypress/e2e/pages/address_book.page.js
- cypress/e2e/pages/balances.pages.js
- cypress/e2e/pages/main.page.js
- cypress/e2e/safe-apps/apps_list.cy.js
- cypress/e2e/safe-apps/browser_permissions.cy.js
- cypress/e2e/safe-apps/info_modal.cy.js
- cypress/e2e/safe-apps/permissions_settings.cy.js
- cypress/e2e/safe-apps/preview_drawer.cy.js
- cypress/e2e/safe-apps/safe_permissions.cy.js
- cypress/e2e/safe-apps/tx_modal.cy.js
- cypress/e2e/smoke/address_book.cy.js
- cypress/e2e/smoke/balances.cy.js
- cypress/e2e/smoke/balances_pagination.cy.js
- cypress/e2e/smoke/beamer.cy.js
- cypress/e2e/smoke/create_safe_simple.cy.js
- cypress/e2e/smoke/create_tx.cy.js
- cypress/e2e/smoke/dashboard.cy.js
- cypress/e2e/smoke/load_safe.cy.js
- cypress/e2e/smoke/nfts.cy.js
- cypress/e2e/smoke/pending_actions.cy.js
- cypress/e2e/smoke/tx_history.cy.js
- cypress/e2e/tx_modal.cy.js
- cypress/e2e/tx_simulation.cy.js
- cypress/support/constants.js
- Refactoring Cypress tests: address book and balances tests
Resolves #2501
- Implement PO model
- Move important values outside of tests into constants.js file
> Refactor Cypress tests: address book and balance tests

- src/components/settings/PushNotifications/hooks/__tests__/useNotificationPreferences.test.ts
- src/components/settings/PushNotifications/hooks/__tests__/useNotificationTracking.test.ts
- src/components/settings/PushNotifications/hooks/useNotificationPreferences.ts
- src/components/settings/PushNotifications/hooks/useNotificationTracking.ts
- src/pages/_app.tsx
- src/service-workers/firebase-messaging/firebase-messaging-sw.ts
- src/services/analytics/events/push-notifications.ts
- src/services/analytics/gtm.ts
- src/services/analytics/types.ts
- src/services/exceptions/ErrorCodes.ts
- src/services/push-notifications/tracking.ts
Adds cached tracking to push notifications
Due to technical limitations and a desire to keep the service worker small, every notification that is shown/clicked increments a counter in a new `notifications-tracking-database` IndexedDB database. A tracking event is then dispatched for every count when the UI is next shown.
1. Ensure notifications are subscribed to and trigger one when the Safe is closed.
2. Open the Safe UI and observe a tracking event, labelled correcty.
> feat: add push notification tracking

- src/components/tx-flow/SafeTxProvider.tsx
- src/components/tx-flow/common/TxNonce/index.tsx
- src/components/tx/SignOrExecuteForm/hooks.ts
If the recommended nonce and safe nonce updates while the transaction modal is open, the current nonce is not updated and transactions with too low nonces are created which lead to validation errors when proposed.
Resets nonce to recommended nonce if the currently selected nonce is lower than the Safe nonce.
1. Open a 1/n Safe with nothing in the queue
2. Initiate any transaction, note the used nonce and immediately execute it (without signing it first)
3. While the transaction is executing, initiate another transaction
4. Observe that this new transaction can initially not be executed and the nonce being the same as the pending transaction
5. Do nothing and wait in the transaction modal until the first transaction got executed and indexed.
6. Observe that the new transaction's nonce gets …
> fix: reset nonce if outdated

- src/services/analytics/gtm.ts
- src/services/analytics/useGtm.ts
Sends `safeAddress` to GTM
- Safe address should be set when opening the app
- Safe address should be updated when switching safes within the same network
- Safe address should be updated when switching safes to a different network
> Feat: attach safe address to analytics events

- cypress/e2e/pages/create_tx.pages.js
- cypress/e2e/pages/dashboard.pages.js
- cypress/e2e/smoke/tx_history.cy.js
- jest.config.cjs
- package.json
- src/components/dashboard/PendingTxs/PendingTxListItem.tsx
- src/components/transactions/HumanDescription/index.tsx
- src/components/transactions/HumanDescription/styles.module.css
- src/components/transactions/TxSummary/index.tsx
- src/components/transactions/TxSummary/styles.module.css
- src/components/transactions/TxType/index.tsx
- src/components/transactions/TxType/styles.module.css
- yarn.lock
This is a smaller iteration on #2465 that only adds human-readable transfers to the history/queue but keeps everything else the same.
Resolves #2449 
- Show Human-readable ERC20, Native and NFT Transfers (Send + Receive), Safe Settings transactions in the transaction history and queue
1. Open the transaction history / queue / single tx view / dashboard pending txs
2. Observe Transfers are in a readable format (`Send <amount> to <address>`, `Receive <amount> from <address>`)
3. Observe other transactions are still in the same layout format
> feat: Add human readable transfers to history and queue

- src/components/tx-flow/index.tsx
Resolves #2499
The transaction modal now closes if the Safe changes.
1. Ensure the transaction modal is open.
2. Change Safe.
3. Observe the modal close.
The same should also happen with the a Safe of the _same_ address, but different chain.
> fix: close transaction flow if Safe changes

- cypress/e2e/pages/dashboard.pages.js
- src/components/dashboard/PendingTxs/PendingTxListItem.tsx
- src/components/dashboard/PendingTxs/PendingTxsList.tsx
- src/components/dashboard/PendingTxs/styles.module.css
- src/components/dashboard/index.tsx
- src/components/transactions/BatchExecuteButton/index.tsx
- src/components/transactions/ExecuteTxButton/index.tsx
- src/components/transactions/SignTxButton/index.tsx
Part of #2510
Shows only signable and executable queued txs, not just any queued txs. Also displays a ✔️ or 🚀 button if a tx can be executed or signed.
> Feat: actionable pending txs on the Dashboard

- src/hooks/wallets/mpc/__tests__/useMPC.test.ts
- src/hooks/wallets/mpc/useMPC.ts
- Adds tests for the `useInitMPC` hook
- Connecting wallet after rehydration
- emitting correct events when switching chain
- initialization of MPC Core Kit
- `yarn test useMPC`
> [Seedless-onboarding] - tests for useMPC hook

- src/components/tx-flow/common/TxButton.tsx
Resolves #2506
If the NFT assets page is already open and "Send NFTs" is clicked in the transaction flow modal, the modal closes. The same for the "Contract interaction" button.
1. Open the NFT asset page.
2. Open the transaction modal.
3. Click "Send NFTs".
4. Observe the modal close.
1. Open the Transaction Builder.
2. Open the transaction modal.
3. Click "Contract interaction".
4. Observe the modal close.
> fix: close transaction modal if already on `href`

- src/components/tx-flow/SafeTxProvider.tsx
- src/components/tx-flow/common/TxNonce/index.tsx
- src/components/tx/SignOrExecuteForm/hooks.ts
Part of #2383 
The form mode for the nonce form changed to `onTouched` with #2383 but selecting a nonce now doesn't update the form unless the user blurs the nonce input. This change calls `onBlur()` whenever the user selects something from the nonce replacement dropdown.
1. Open a safe with at least one transaction in queue
3. Go to the review screen
4. Observe seeing the Sign flow
5. Select the existing nonce from the nonce form
6. Observe seeing the Execute flow
> fix: Update tx flow form when selecting a replacement nonce

- .github/workflows/deploy.yml
- src/components/safe-apps/AppFrame/index.tsx
Resolves #2440 
Considers the safe signing settings when signing a message from safe apps.
1. Use the eip1271 test dapp
2. disable off-chain signing
3. sign a message
4. Observe on-chain signature modal
> fix: allow safe apps to disable off-chain signing

- src/components/privacy/index.tsx
Update the Privacy policy page wrt tracking and anonymized tracking.
> Fix: update privacy policy

- src/services/contracts/__tests__/safeContracts.test.ts
- src/services/contracts/safeContracts.ts
Resolves #2498
`MultiSendCallOnly` only exists as of version 1.3.0. Older Safes (<1.3.0) now use `MultiSendCallOnly` 1.3.0 by default.
1. On a <1.3.0 Safe queue multiple transactions.
2. Click bulk execute from the queue.
3. Observe no crash.
1. Simulate a multiSend transaction on a <1.3.0 Safe.
2. Observe no error when simulating (not related to simulation result).
> fix: use MultiSendCallOnly 1.3.0 for older Safes

- cypress/e2e/pages/dashboard.pages.js
- src/components/dashboard/PendingTxs/PendingTxListItem.tsx
- src/components/transactions/TxType/index.tsx
- src/services/analytics/useGtm.ts
Resolves #2011 
- Removes human-readable descriptions from the dashboard widget
1. Open a Safe with queued transactions
2. Navigate to the dashboard
3. Observe the transactions without human-readable description
> fix: Remove human description from dashboard due to lack of space

- src/components/batch/BatchSidebar/BatchTxItem.tsx
Part of #2011 
- Hides the `TxInfo` in the batch view when human-readable descriptions are displayed
1. Open a Safe and create a batch (e.g. with transfers)
2. Observe that if human-readable descriptions are visible, there is no second column
> fix: Hide txInfo when displaying human description in batch tx

- src/components/settings/PushNotifications/hooks/__tests__/useNotificationRegistrations.test.ts
- src/components/settings/PushNotifications/hooks/useNotificationRegistrations.ts
- src/components/settings/PushNotifications/logic.test.ts
- src/components/settings/PushNotifications/logic.ts
- src/utils/wallets.ts
Resolves Ledger notification registration not working
> Ledger produces vrs signatures with a canonical v value of {0,1}, while Ethereum's ecrecover call only accepts a non-standard v value of {27,28}. More on that [here](https://github.com/ethereum/go-ethereum/issues/19751#issuecomment-504900739).
The `v` of Ledger signatures is now adjusted by `27` accordingly.
- Register for notifications with a non-Ledger wallet and observe registration working.
- Register for notifications with a Ledger and observe registration working.
> fix: adjust Ledger signatures for notifications

- src/components/settings/PushNotifications/PushNotificationsBanner/index.tsx
- src/components/settings/PushNotifications/hooks/__tests__/useNotificationRegistrations.test.ts
- src/components/settings/PushNotifications/hooks/useNotificationPreferences.ts
- src/components/settings/PushNotifications/hooks/useNotificationRegistrations.ts
- src/components/settings/PushNotifications/index.tsx
- src/components/settings/PushNotifications/logic.test.ts
- src/components/settings/PushNotifications/logic.ts
1. https://github.com/safe-global/safe-wallet-web/pull/2546#issuecomment-1735593295
2. "Global registration" not enabling "Confirmation requests" checkbox in notification preferences
3. Signing for added Safes across different chains doesn't work on Ledger/Trezor
The `wallet` is now directly used to create a `Web3Provider` within `getRegisterDevicePayload`. (The chain assertion that happens when clicking "Enable all" causes `useWeb3` to return `undefined` for a short period of time.)
Ownership of the Safes being registered is no longer references `useIsSafeOwner`. The registrant is inherently registered and the checkbox should therefore be checked. (If they are not an owner or delegate they won't receive notifications, however.)
Multiple signatures are now requested sequentially instead …
> fix: notification preferences, post-switch registration + sequential signatures

- src/components/settings/PushNotifications/GlobalPushNotifications.tsx
- src/components/settings/PushNotifications/__tests__/GlobalPushNotifications.test.ts
- src/components/settings/PushNotifications/__tests__/logic.test.ts
- src/components/settings/PushNotifications/hooks/__tests__/useNotificationPreferences.test.ts
- src/components/settings/PushNotifications/hooks/__tests__/useNotificationRegistrations.test.ts
- src/components/settings/PushNotifications/hooks/useNotificationPreferences.ts
- src/components/settings/PushNotifications/hooks/useNotificationRegistrations.ts
- src/services/exceptions/ErrorCodes.ts
Resolves https://github.com/safe-global/safe-wallet-web/pull/2546#issuecomment-1736499323
`deleteAllPreferences` is has been replaced with `deleteAllChainPreferences`, which clears preferences according to a provided `chainId` according to the device unregistration (also per `chainId`).
A loading indicator has also been added to the global preferences "Save" button.
During the following registrations, a loading indicator should appear in the "Save" button:
1. Ensure multiple Safes are registered across differing chains.
2. Navigate to the global notification preferences.
3. Unregister a Safe.
4. Observe _only_ the preferences from that Safe removed.
---
1. Ensure multiple Safes are registered across differing chains.
2. Navigate to the global notification preferences.
3. Unregister _all_ …
> fix: only delete all preferences per chain

- src/components/safe-messages/MsgSummary/index.tsx
- src/components/tx/SignOrExecuteForm/hooks.ts
Fixes https://github.com/safe-global/safe-wallet-web/pull/2546#issuecomment-1738335210, https://github.com/safe-global/safe-wallet-web/pull/2546#issuecomment-1738357845
- Checks the `recommendedNonce` for undefined
- Adds correct css class to MsgSummary
1. Create a new transaction in a new safe
2. Observe the nonce form showing 0
3. Go to Messages with existing messages there
4. Observe no overlaps
> fix: Show recommended nonce when nonce is 0, fix msgSummary layout

- src/services/analytics/gtm.ts
Safe Apps track all RPC requests a lot of which are triggered from the Governance App on the Dashboard. Since this doesn't reflect actual Safe App usage, it should be disabled.
* Safe Apps tracking events should not be triggered on the dashboard anymore
* Events on the /apps page, as well as individual Safe App pages should be still emitted like before.
> Fix: prevent Safe Apps tracking on non-Safe App pages

- src/components/settings/PushNotifications/index.tsx
- src/config/constants.ts
Adds help center link to the push notifications settings page.
A new "Learn more about push notifications here" sentence has been added to the end of the description of push notifications in the per-Safe/global notifications settings.
Open the per-Safe/global notifications settings and observe the new sentence/working link.
> feat: help centre article link placeholder

- src/components/settings/PushNotifications/PushNotificationsBanner/index.tsx
Resolves style inconsistency for "Enable all" button height when disabled.
The `CheckWallet` component now wraps the button container element instead of just the "Enable all" button.
Note: this seems to happen only in Chrome.
1. Ensure no wallet is connect.
2. Ensure the Safe has not previously dismissed the push notification banner.
3. Open the Safe.
4. Observe the "Enable all" button (disabled) having the same height as the "Customize" button in the notification banner.
> fix: disabled "Enable all" button height

- src/components/notification-center/NotificationCenter/index.tsx
- src/components/transactions/TxType/styles.module.css
Avoid hiding a single notification behind a collapsible box. It occupies exactly the same space.
Plus, the wording "1 other notification<b>s</b>" is wrong.
1.
* Trigger 5 notitications
* Before: the 5th one was hidden, and it said "1 other notifications"
* After: all 5 are shown
2.
* Trigger 6 or more notitications
* Only 4 are shown and it says "2 other notifications"
> Fix: notifications popup: don't hide just one item

- src/components/settings/PushNotifications/PushNotificationsBanner/PushNotificationsBanner.test.ts
- src/components/settings/PushNotifications/PushNotificationsBanner/index.tsx
Resolves signature requests for Safes that are already registered for notifications.
The logic within the banner has been fixed, as well as more unit test coverage added.
1. Add a Safe on chain A and register for notifications with it.
2. Add a Safe on chain B and register for notifications with it.
3. Observe only one signature request.
> fix: only request new notification signatures

- cypress/e2e/pages/owners.pages.js
- cypress/e2e/smoke/replace_owner.cy.js
- Making tests independent from each other
Resolves #2579 
- Tests structure, redesign
> Tests: Add replace owner tests

- src/components/notification-center/NotificationCenter/index.tsx
- src/components/notification-center/NotificationCenter/styles.module.css
Resolves unclear notification settings navigation
A "Notifications settings" link has been added to the notification centre footer.
Open the notification centre and observe the new, working link in the footer.
Older screenshots showcasing the presence:
> feat: notification settings link

- src/components/settings/PushNotifications/GlobalPushNotifications.tsx
- src/components/settings/PushNotifications/PushNotificationsBanner/PushNotificationsBanner.test.ts
- src/components/settings/PushNotifications/PushNotificationsBanner/index.tsx
- src/components/settings/PushNotifications/__tests__/GlobalPushNotifications.test.ts
- src/services/analytics/events/push-notifications.ts
Multiple signing windows and unsupported added Safes breaking registration.
Enabling "all" notifications via the banner is now per chain. Only one signing window will appear and Safes on that chain will be registered for notifications.
On the global notifications settings page, the notifiable Safes are filtered according to the chains of the config service.
1. Ensure there are added Safes on differing networks and that no notification banner has been previously dismissed.
2. Open a network with added Safes and enable the notifications via the banner.
3. Observe only one signing window appear.
4. Switch to another network with added Safes and repeat.
1. Add an unsupported chain with Safes to the `SAFE_v2__addedSafes` key in the `localStorage`.
2. Navigate to the global notification …
> fix: enable notifications per chain

- src/components/safe-apps/SafeAppIconCard/index.tsx
Resolves cut off logo
The full logo is now shown in the header when connected to a DApp.
Connect to a DApp via native WC and observe no cut off logo.
> fix: don't cut off DApp icon

- src/services/walletconnect/WalletConnectContext.tsx
- src/services/walletconnect/WalletConnectWallet.ts
- src/services/walletconnect/__tests__/WalletConnectContext.test.tsx
- src/services/walletconnect/__tests__/WalletConnectWallet.test.ts
DApp on wrong chain
1. The session is now updated after approval with the chain of the Safe, and updated session returned accordingly.
2. As a precaution, if no active session or matching `chainId` exists, an error is now returned upon "wrong" request.
1. Connect to Uniswap via native WC with a Safe on Gnosis Chain. Observe it immediately requesting chain switch.
2. Connect via native WC to a DApp that doesn't support the current Safe and try to transact, observing the "Unsupported chains." error.
> fix: update session after approval

- src/components/notification-center/NotificationCenter/index.tsx
A fix for #2576, the +1 logic wasn't checked in enough places.
> Fix: collapse notifications if more than max + 1

- src/components/settings/PushNotifications/PushNotificationsBanner/PushNotificationsBanner.test.tsx
- src/components/settings/PushNotifications/PushNotificationsBanner/index.tsx
+ Don't track banner dismissal on enable all/customize.
The banner was previously shown regarless of whether you're connected which clashed with the onboard popup.
> Fix: don't show push notifications banner if wallet not conencted

- src/components/welcome/NewSafe.tsx
Part of #2452 
- Displays the button to open the safe list sidebar if there are owned safes detected
1. Open the welcome page
2. No button should be visible when not connected and there are no added safes
3. Connect with a wallet that owns safes
4. Observe the button appears and displays the number of owned safes + added safes
> [Seedless Onboarding]: Show Safe list sidebar button on welcome page

- src/components/tx-flow/flows/SafeAppsTx/ReviewSafeAppsTx.tsx
- src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
- src/components/tx/SignOrExecuteForm/SignForm.tsx
- src/components/tx/SignOrExecuteForm/index.tsx
- src/services/safe-wallet-provider/index.ts
- src/services/safe-wallet-provider/useSafeWalletProvider.tsx
- src/services/tx/tx-sender/dispatch.ts
- src/services/tx/txEvents.ts
In 1/X Safes with immediate execution, a txHash can be sent to the requesting dapp right away.
> Feat: return txHash if available

- src/components/walletconnect/ConnectionForm/index.tsx
- src/components/walletconnect/Hints/index.tsx
- src/components/walletconnect/Hints/styles.module.css
Resolves missing WC help info
The help regarding connection/interaction with a dApp has been added.
Open the WC modal and observe the help information within the accordions. Hiding and showing them should work accordingly.
> fix: populate help section

- src/components/common/ConnectWallet/AccountCenter.tsx
- src/components/common/NetworkSelector/index.tsx
- src/components/notification-center/NotificationCenter/index.tsx
- src/components/walletconnect/Popup/index.tsx
Resolves non-uniform alignments
All `Popover`s in the header now aligned directly below the header.
Open the notification, WC, account centre and network switcher popovers and observe them aligned below the header.
> fix: align all `Popover`s to header

- src/components/walletconnect/ConnectionForm/index.tsx
- src/components/walletconnect/Hints/index.tsx
- src/components/walletconnect/SessionList/index.tsx
- src/components/walletconnect/SessionManager/Header.tsx
- src/components/walletconnect/WcInput/index.tsx
Addresses initial design implementation feedback
- Only one help accordion can be open at once
- Hiding the accordions is indefinite and then shown only via the info button
- URI input field is no longer disabled after URI entry
- Small text adjustments
Interact with the WC modal and observe the above addressed.
> fix: address WC style feedback

- src/components/transactions/TxDetails/index.tsx
- src/components/transactions/TxListItem/ExpandableTransactionItem.tsx
- src/services/analytics/events/txList.ts
Fix for #2543 
This will significantly reduce the number of events that are tracked due to users opening a single transaction view (which is already tracked by a page view event).
- Removes `Fetch transaction details` event
- Tracks `Expand transaction item` event whenever the user expands a transaction item
1. Open a transaction history
2. Click on a transaction to expand
3. Observe that the event is tracked
4. Close the transaction and open it again
5. Observe that the event is tracked again
6. Open a single transaction view
7. Observe that no event for fetch tx details is tracked
> fix: Track transaction item open events

- src/components/walletconnect/SessionManager/Header.tsx
- src/components/walletconnect/SessionManager/styles.module.css
Resolves incorrect icon on error state
The icon has been changed to the correct colour (blue) and a new badge added instead for the error state.
Cause an errorneous session and observe the new design.
> fix: change colour of icon + add error badge

- cypress/e2e/pages/create_wallet.pages.js
- cypress/e2e/pages/owners.pages.js
- src/components/settings/owner/EditOwnerDialog/index.tsx
- src/components/settings/owner/OwnerList/index.tsx
Resolves console warnings in owner list.
All `Tooltip` children within the owner list have been wrapped in `span` elements.
Open the project locally and navigate to the owner list within the settings:
- Observe working tooltips for replacing, editing and removing owners.
- When clicking each, observe the transaction flow opening as well as correct tracking.
> fix: console warnings in owner list

- cypress/e2e/pages/balances.pages.js
- cypress/e2e/pages/main.page.js
- cypress/e2e/smoke/assets.cy.js
- cypress/e2e/smoke/balances.cy.js
- cypress/support/constants.js
Resolves #2614 
- Add Assets tests
> Tests: Add Assets tests

- src/components/common/ConnectWallet/AccountCenter.tsx
- src/components/common/ConnectWallet/MPCLogin.tsx
- src/components/common/ConnectWallet/__tests__/MPCLogin.test.tsx
- src/components/common/NetworkSelector/index.tsx
- src/components/common/NetworkSelector/styles.module.css
- src/components/common/WalletInfo/index.tsx
- src/components/common/WalletInfo/styles.module.css
- src/components/new-safe/create/index.tsx
- src/components/new-safe/create/steps/ReviewStep/index.test.tsx
- src/components/new-safe/create/steps/ReviewStep/index.tsx
- src/components/new-safe/create/steps/SetNameStep/index.tsx
Resolves #2458 
- Disables Social Login when not on Gnosis Chain and shows an info text
- Skips to the review screen on safe creation when using Social Login
- Displays simplified relay sponsor view in review screen
- Disables network selector when using Social Login
1. Open the welcome page
2. Switch to an unsupported network
3. Observe the Social Login is disabled with an info text
4. Switch to Gnosis chain and log in via Google
5. Observe the Network selector is disabled
6. Enter the safe creation flow
7. Observe jumping right to the review screen
8. No execution method selector is shown and instead a simple message saying Free
9. Disconnect from Google
10. Connect via MM
11. Network Selector should work
12. Enter the safe creation
13. First step of the safe creation should open
> fix: Enable 1-click safe create for social login

- src/components/common/ConnectWallet/AccountCenter.tsx
- src/components/notification-center/NotificationCenter/index.tsx
- src/components/walletconnect/Popup/index.tsx
- src/components/walletconnect/SessionList/index.tsx
- src/components/walletconnect/SessionList/styles.module.css
- src/components/walletconnect/SessionManager/ErrorMessage.tsx
- src/components/walletconnect/SessionManager/index.tsx
- src/components/walletconnect/SessionManager/styles.module.css
Resolves alignment issues
- All popups now only adjust the first `Paper` top spacing.
- The disconnect button in the `SessionManager` no longer overlaps DApp names.
- Adds `gap` between sessions.
- Centralise error message.
1. Open the WC popup _without_ having dismissed the hints. Observe no accordion/checkbox overlap.
2. Dismiss the hints and open them via the icon. Observe no alignment issues above the accordions.
3. Approve a session with a DApp that has a long name, e.g. Aave. Observe no overlap with the disconnect button.
4. Add a second session. Observe spacing between sessions.
5. Connect to an unsupported network. Observe error, centralised.
> fix: WC popup, checkbox, session alignment

- src/components/walletconnect/ProposalForm/ChainWarning.tsx
- src/components/walletconnect/ProposalForm/index.tsx
- src/services/walletconnect/utils.ts
Resolves unsupported session errors
When proposing a session that is not supported by the Safe Account chain, the approval is now disabled and the alert coloured erroneously.
Open a Safe on Gnosis Chain and try to connect to AAVE. Observe the disabled button and red information box.
> fix: disable approval of unsupported sessions

- src/services/safe-wallet-provider/useSafeWalletProvider.tsx
Resolves missing icon in transaction list
The URL of the WC Safe App is sent in the transaction `origin` and the icon of which therefore used.
Execute a transaction via native WC and observe the DApp details in the transaction flow, but now a WC icon in the transaction list.
> fix: show WC details in transaction list

- src/components/walletconnect/HeaderWidget/index.tsx
- src/components/walletconnect/WcInput/index.tsx
- src/services/walletconnect/WalletConnectWallet.ts
- src/utils/clipboard.ts
Resolves stale pairing URIs in input
When rejecting a session proposal, the pairing URI is cleared from the URL/clipboard (state) meaning that the input is not populated with the value.
Copy a pairing URI from a DApp and reject the proposal, observing no value prepopulating the input field.
> fix: clear pairing URI on rejection

- src/components/walletconnect/SessionList/styles.module.css
Resolves overflow of DApp names
The `ListItem`s of `SessionList` now have a `min-height` instead of fixed `height`.
Connect to CoW Swap via WC and observe no overflow of the name.
> fix: WC session list height

- .github/workflows/test.yml
- package.json
- src/components/address-book/ExportDialog/index.test.tsx
- yarn.lock
I've switched our CI to a different Jest action that has a better coverage report and the same annotations as the previous one.
Also, I've deleted the pre-commit hook because it was really slow.
> Chore: enable unit test coverage comment

- src/components/batch/BatchIndicator/index.tsx
- src/components/walletconnect/ConnectionForm/index.tsx
- src/components/walletconnect/HeaderWidget/Icon.tsx
- src/components/walletconnect/HeaderWidget/index.tsx
- src/components/walletconnect/Hints/index.tsx
- src/components/walletconnect/ProposalForm/ChainWarning.tsx
- src/components/walletconnect/WcInput/index.tsx
Resolves various feedback
1. All references to "pairing URI" are now "pairing code".
2. An extra two steps have been added to the "How do I connect to a dApp?" section.
3. The hint dismissal checkbox has been removed, opting in favour of session proposal hiding them instead.
4. The "Ensure the dApp is connected to %%chain%%" info is now always shown if the DApp supports the Safe.
5. Session counts are now displayed numerically in a badge, and the batch indicator badge design has been alignned to match it (solving https://github.com/safe-global/safe-wallet-web/issues/2442).
1. No references of "pairing URI" should be present when testing the following.
2. "Connect a wallet" and "Select WalletConnect as the wallet" should be present in the "How do I connect to a dApp?" hint.
3. No dismissal …
> fix: WC details + header badges

- src/services/walletconnect/useWalletConnectClipboardUri.ts
Resolves stale pairing URIs from the clipboard from being entered on focus
Previous pairing URIs are cached and only new ones returned from `useWalletConnectClipboardUri`.
Pairing with WC in Chrome via clipboard and blur then focus the window again. Observe no stale pairing URI entered/no field error.
> fix: don't paste stale pairing URIs

- src/components/tx-flow/flows/SignMessage/index.tsx
- src/services/safe-wallet-provider/index.ts
- src/services/safe-wallet-provider/useSafeWalletProvider.test.tsx
- src/services/safe-wallet-provider/useSafeWalletProvider.tsx
- src/store/index.ts
- src/utils/__tests__/safe-messages.test.ts
- src/utils/safe-messages.ts
Resolves on-chain signing capibility
Toggling between on-/off-chain signing is now possible via WC, handling the `safe_setSettings` RPC call.
Open the EIP-1271 example dApp and connect via WC (on the `wallet-connect-v2` branch). Observe signing (typed) messages works as expected after toggling between on-/off-chain signing.
> feat: on-chain WC signing

- src/services/walletconnect/WalletConnectWallet.ts
Resolves multiple session disconnects throwing
Session updated are now handled one after each other.
Connect two DApps that support chain A but not chain B. Switch from chain A to chain B and observe no WC-related error.
> fix: multipl session disconnects throwing

- cypress/e2e/safe-apps/apps_list.cy.js
- cypress/e2e/safe-apps/browser_permissions.cy.js
- cypress/e2e/safe-apps/info_modal.cy.js
- cypress/e2e/safe-apps/permissions_settings.cy.js
- cypress/e2e/safe-apps/preview_drawer.cy.js
- cypress/e2e/safe-apps/safe_permissions.cy.js
- cypress/e2e/safe-apps/tx_modal.cy.js
- cypress/e2e/smoke/add_owner.cy.js
- cypress/e2e/smoke/address_book.cy.js
- cypress/e2e/smoke/assets.cy.js
- cypress/e2e/smoke/balances.cy.js
- cypress/e2e/smoke/balances_pagination.cy.js
- cypress/e2e/smoke/batch_tx.cy.js
- cypress/e2e/smoke/beamer.cy.js
- cypress/e2e/smoke/create_safe_simple.cy.js
- cypress/e2e/smoke/create_tx.cy.js
- cypress/e2e/smoke/dashboard.cy.js
- cypress/e2e/smoke/import_export_data.cy.js
- cypress/e2e/smoke/landing.cy.js
- cypress/e2e/smoke/load_safe.cy.js
- cypress/e2e/smoke/nfts.cy.js
- cypress/e2e/smoke/remove_owner.cy.js
- cypress/e2e/smoke/replace_owner.cy.js
- cypress/e2e/smoke/tx_history.cy.js
Resolves #2634 
- Add test IDs and update descriptions
> Tests: map tests to TestRail ids

- jest.config.cjs
- src/components/walletconnect/ConnectionForm/index.tsx
- src/components/walletconnect/ProposalForm/useCompatibilityWarning.ts
- src/services/walletconnect/__tests__/WalletConnectContext.test.tsx
- src/services/walletconnect/__tests__/WalletConnectWallet.test.ts
Resolves help blocks not hiding after session then refresh
Duplicate state leftover from the debounced checkbox has been removed.
Connect a session and observe the help blocks hidden, remaining hidden after refreshing. The info box that toggled the help box should have an explanatory tooltip that works as expected.
> fix: help block not hiding

- src/components/walletconnect/ProposalForm/__tests__/useCompatibilityWarning.test.ts
- src/components/walletconnect/ProposalForm/index.tsx
- src/components/walletconnect/ProposalForm/useCompatibilityWarning.ts
Resolves crashes when `metadata` is empty
The icon is no longer rendered in the `ProposalForm` if none is provided in the `metadata.icons` array, and `this dApp` is used as a fallback for the `metadata.name`.
Connect to [Satellite](https://satellite.money) and observe no error, as well as successful transacting.
> fix: handle empty metadata

- src/services/walletconnect/WalletConnectWallet.ts
- src/services/walletconnect/__tests__/WalletConnectWallet.test.ts
Resolves dApp chain alignment
The `chainChanged` event is not emitted before the `accountsChanged event when updating a session.
Connect to [Aura Finance](https://app.aura.finance) and observe the initial chain matching that of the Safe, as well as changing with Safe switches across chains.
> fix: emit `chainChanged` first

- src/components/walletconnect/HeaderWidget/index.tsx
- src/components/walletconnect/SessionManager/ErrorMessage.tsx
- src/components/walletconnect/SessionManager/styles.module.css
- src/services/walletconnect/WalletConnectContext.tsx
Resolves WC error never clearing
All WC-related errors are closed after viewing them, as well as being truncated if they are too long.
Connect to a dApp in one tab, then in another open the Safe on a chain that the connected-to dApp doesn't support. Refresh the former and observe an error present in the popup, truncated. When closing the popup, it should clear.
> fix: prevent error from blocking WC popup

- src/components/tx-flow/index.tsx
Resolves successful signing requests rejecting in dApps
The `USER_QUIT` event is nly dispatched to the dApp if a warning requirement was set and is accepted when closing the flow, ergo not when a signature request succeeds and closes the flow.
Observe successful swaps on Aave, CoWSwap, Curve and Sushi (on 1/n Safes).
> fix: don't reject when signing

- package.json
- src/components/common/AddressInput/index.test.tsx
- src/components/common/CheckWallet/index.test.tsx
- src/components/new-safe/create/steps/StatusStep/__tests__/useSafeCreation.test.ts
- src/components/tx-flow/flows/SignMessage/SignMessage.test.tsx
- src/hooks/__tests__/useRemainingRelays.test.ts
- src/hooks/useMnemonicName/useMnemonicName.test.ts
- src/tests/Builder.ts
- src/tests/builders/chains.ts
- src/tests/builders/utils.ts
- yarn.lock
Resolves brittle tests
A new `Builder` class has been added that facilitates mock data generation for tests. An example `chainBuilder` has been created and used in a few demonstrative tests where `useCurrentChain` is mocked.
Observe the tests passing.
> chore: mock data builder for tests

- src/hooks/wallets/mpc/__tests__/useMPCWallet.test.ts
- src/hooks/wallets/mpc/useMPCWallet.ts
- src/utils/addresses.ts
Adds the mpc signer address into the addressbook after login.
1. If the google signer address is in the addressbook, delete it.
2. Re-Login with google
3. Observe that the resolved address is added to the addressbook.
> [Seedless-Onboarding] Add signer account to address book on login

- cypress/e2e/pages/nfts.pages.js
- cypress/e2e/pages/safeapps.pages.js
- cypress/e2e/safe-apps/apps_list.cy.js
- cypress/e2e/safe-apps/browser_permissions.cy.js
- cypress/e2e/safe-apps/info_modal.cy.js
- cypress/e2e/safe-apps/permissions_settings.cy.js
- cypress/e2e/safe-apps/preview_drawer.cy.js
- cypress/e2e/safe-apps/safe_permissions.cy.js
- cypress/e2e/safe-apps/tx_modal.cy.js
- cypress/e2e/smoke/dashboard.cy.js
- cypress/e2e/smoke/nfts.cy.js
- cypress/e2e/smoke/tx_history.cy.js
- cypress/support/safe-apps-commands.js
Resolves #2671 
- Migrate safe apps and NFTS tests to Sepolia
> Tests: Migrate safe apps tests to Sepolia

- src/services/exceptions/ErrorCodes.ts
- src/utils/transactions.ts
ABI decoded was throwing in some rare cases.
> Fix: uncaught exception in ApprovalEditor

- src/components/common/TokenExplorerLink/index.tsx
Just a small fix to avoid key prop warnings in the console.
> Fix: use local ExplorerButton component

- public/images/common/bar-chart.svg
- src/components/common/PageHeader/styles.module.css
- src/components/new-safe/create/steps/SetNameStep/index.tsx
- src/components/settings/SecurityLogin/SocialSignerExport/ExportMPCAccountModal.tsx
- src/components/settings/SecurityLogin/SocialSignerMFA/helper.ts
- src/components/settings/SecurityLogin/SocialSignerMFA/index.tsx
- src/components/settings/SecurityLogin/SocialSignerMFA/styles.module.css
- src/services/analytics/events/createLoadSafe.ts
- src/styles/globals.css
Part of #2452 
- Renames `oldPassword` to `currentPassword`
- Renames `Confirm new password` to `Confirm password`
- Displays a submit error inside the form
- Fixes z-index issue on the settings page when scrolling
- Adds an event to track create safe form cancels
- Adds visual default states for `passwordStrength` and `passwordsMatch`
- Closes the accordion on successful form submission
1. Open a Safe and login with google
2. Go to the settings page
3. Compare form design with [Figma](https://www.figma.com/file/WSpulDIM1EoSCI6Ph9QdWq/Seedless-onboarding?node-id=909%3A26336&mode=dev)
> [Seedless Onboarding]: Adjust password form

- src/components/new-safe/create/steps/StatusStep/useSafeCreationEffects.ts
Adds safeAddress to safe creation event
1. Create a new safe
2. Observe that the safe address exists in GTM on the Created Safe event
3. Navigate to that safe
4. Observe that the safe address is still there
> fix: track safeAddress on Safe creation

- src/components/tx-flow/index.tsx
- src/services/safe-wallet-provider/useSafeWalletProvider.tsx
- src/services/tx/txEvents.ts
- src/services/walletconnect/WalletConnectContext.tsx
The on-close callback wasn't correctly handled because of how we were setting state.
This wasn't setting the state to a new function, but was calling this function right away instead as it it was a setter callback.
```
setOnClose(onClose ?? noop)
```
I've changed onClose and shouldWarn to useRef to fix this.
Also removed the global USER_QUIT tx event and replaced with with direct onClose callbacks.
> Fix: on close callback for WalletConnect

- Dockerfile
Resolves #2697
`after-install` needs to be run manually on CI.
> Chore: after-install in Docker

- src/services/analytics/TagManager.ts
- src/services/analytics/__tests__/TagManager.test.ts
- src/services/analytics/gtm.ts
- src/services/analytics/types.ts
- src/services/analytics/useGtm.ts
Track the user's used wallet type as user property.
> feat: track user's wallet type through user properties

- src/components/common/SocialSigner/index.tsx
- src/services/mpc/SocialLoginModule.ts
Part of #2452 
- Rejects the promise from the MPC Provider calls so it can be caught by our components
- Resets the loading state during login if login fails
- Adds a TODO to show an error if login fails (Need to check this with design)
1. Open a Safe
2. Login with Social
3. Execute a transaction but block the network requests to w3a
4. Observe an error is shown in the modal
> [Seedless Onboarding] Catch errors during signing with social login

- src/components/welcome/WelcomeLogin/WalletLogin.tsx
- src/components/welcome/WelcomeLogin/__tests__/WalletLogin.test.tsx
Part of #2452
- Checks for `wallets.length` since onboard returns an empty array if no wallet is connected
1. Open the welcome page
2. Press Connect wallet
3. Close the modal
4. Observe no flashing
> [Seedless Onboarding] Only continue to safe creation if login succeeds

- src/store/__tests__/addressBookSlice.test.ts
- src/store/addressBookSlice.ts
Creating a Safe with social signers lead to empty names in the addressbook.
We ignore addressBook entries with empty names and do not insert those anymore.
1. Create a Safe with social signer
2. Witness that no empty entry is created for that Safe anymore
> fix: ignore empty names in addressbook

- cypress/e2e/pages/balances.pages.js
- cypress/e2e/pages/batches.pages.js
- cypress/e2e/pages/create_wallet.pages.js
- cypress/e2e/pages/main.page.js
- cypress/e2e/pages/owners.pages.js
- cypress/e2e/pages/safeapps.pages.js
- cypress/e2e/safe-apps/apps_list.cy.js
- cypress/e2e/safe-apps/info_modal.cy.js
- cypress/e2e/safe-apps/preview_drawer.cy.js
- cypress/e2e/safe-apps/safe_permissions.cy.js
- cypress/e2e/smoke/add_owner.cy.js
- cypress/e2e/smoke/assets.cy.js
- cypress/e2e/smoke/balances.cy.js
- cypress/e2e/smoke/balances_pagination.cy.js
- cypress/e2e/smoke/batch_tx.cy.js
- cypress/e2e/smoke/create_tx.cy.js
- cypress/e2e/smoke/import_export_data.cy.js
- cypress/e2e/smoke/remove_owner.cy.js
- cypress/e2e/smoke/replace_owner.cy.js
- cypress/e2e/smoke/tx_history.cy.js
Resolves #2705 
Update test data/logic
> Tests: Fix Cypress tests

- cypress/e2e/pages/dashboard.pages.js
- cypress/e2e/pages/nfts.pages.js
- cypress/e2e/pages/safeapps.pages.js
- cypress/e2e/safe-apps/browser_permissions.cy.js
- cypress/e2e/safe-apps/safe_permissions.cy.js
- cypress/e2e/smoke/dashboard.cy.js
- cypress/e2e/smoke/nfts.cy.js
- cypress/e2e/smoke/tx_history.cy.js
Resolves #2722 
- Refactor skipped tests
- Make the tests independent
> Tests: Update skipped tests

- src/pages/_app.tsx
- src/services/pairing/QRModal.tsx
- src/services/pairing/module.ts
- src/services/pairing/styles.module.css
Resolves #2711
The mobile pairing modal was rendered in a completely separate React root which caused a lot of issues.
> Fix: render mobile pairing correctly

- src/components/safe-apps/AppFrame/index.tsx
- src/components/tx-flow/flows/SignMessage/SignMessage.tsx
- src/components/tx-flow/flows/SignMessageOnChain/ReviewSignMessageOnChain.test.tsx
- src/components/tx-flow/flows/SignMessageOnChain/ReviewSignMessageOnChain.tsx
- src/components/walletconnect/WcConnectionForm/index.tsx
- src/components/walletconnect/WcErrorMessage/index.tsx
- src/components/walletconnect/WcErrorMessage/styles.module.css
- src/components/walletconnect/WcHints/index.tsx
- src/components/walletconnect/WcLogoHeader/index.tsx
- src/components/walletconnect/WcLogoHeader/styles.module.css
- src/components/walletconnect/WcSessionList/WcNoSessions.tsx
- src/components/walletconnect/WcSessionList/index.tsx
- src/components/walletconnect/WcSessionMananger/index.tsx
- src/pages/apps/open.tsx
- src/services/analytics/events/walletconnect.ts
- src/services/exceptions/ErrorCodes.ts
- src/services/onboard.ts
- src/services/safe-wallet-provider/index.test.ts
- src/services/safe-wallet-provider/index.ts
- src/services/safe-wallet-provider/useSafeWalletProvider.test.tsx
- src/services/safe-wallet-provider/useSafeWalletProvider.tsx
- src/services/walletconnect/WalletConnectContext.tsx
- src/services/walletconnect/WalletConnectWallet.ts
- src/services/walletconnect/__tests__/WalletConnectContext.test.tsx
- src/services/walletconnect/__tests__/utils.test.ts
- src/services/walletconnect/utils.ts
* Change the "WC show hints" event to trigger on i-icon click + add a "WC hide hints" event - verified
* Add an event for all RPC requests made through WalletConnect – "WC request"
* Don't ignore chain switch errors
* Display errors in two lines: summary and details - changed , the error is displayed in a few lines. The connection code is too long for one line
* Limit the displayed dapp name to 22 characters in the session list - verified
* Reduce the time to show a connect/disconnect message to 1 second (was 2) - verified
* Fix Safe logo for WalletConnect (resolves #2720) - verified
* Show the new WC popup when the old WC Safe App is opened - verified
> Fix: adjust WalletConnect events

- src/components/common/SocialSigner/index.tsx
- src/services/exceptions/ErrorCodes.ts
- src/services/mpc/SocialWalletService.ts
Login errors are caught and ignored.
- Calls logError and throws a new Error.
- Displays the error in the login screens
- Break the local config by configuring a wrong verifier ID or block the network requests
- Try to login
- Witness new errors
> [Seedless-Onboarding] fix: login error handling 

- src/components/new-safe/create/index.tsx
- src/hooks/useMnemonicName/index.ts
- src/hooks/useMnemonicName/useMnemonicName.test.ts
- Uses mnemonic names for Safe creation with Social wallet connected
- Changes mnemonic name to be upper cased and with space instead of dashes
- Create a new Safe using social wallet
- Witness that a safe name is set
> feat: use mnemonic name for Social Safes 

- src/components/common/FileUpload/index.tsx
- src/components/walletconnect/WcSessionMananger/index.tsx
- src/services/walletconnect/WalletConnectContext.tsx
- src/services/walletconnect/tracking.ts
WalletConnect RPC request tracking was added in #2717.
This PR limits the types of requests being tracked to only transaction and signature requests. Otherwise we would track all kinds of "read-only" requests like `eth_getChainid` etc.
Also, track errors only once when they are thrown, not every time they're shown.
> Fix: WalletConnect - track only tx and signature requests

- cypress/e2e/pages/create_wallet.pages.js
- cypress/e2e/pages/owners.pages.js
- cypress/e2e/smoke/create_safe_simple.cy.js
> Tests: Seedless cypress tests(normal flow)

- cypress/e2e/pages/address_book.page.js
- cypress/e2e/pages/batches.pages.js
- cypress/e2e/pages/load_safe.pages.js
- cypress/e2e/safe-apps/info_modal.cy.js
- cypress/e2e/safe-apps/preview_drawer.cy.js
- cypress/e2e/safe-apps/tx_modal.cy.js
- cypress/e2e/smoke/address_book.cy.js
- cypress/e2e/smoke/balances.cy.js
- cypress/e2e/smoke/load_safe.cy.js
- cypress/e2e/smoke/tx_history.cy.js
> Tests: Make tests independent

- cypress/e2e/pages/create_wallet.pages.js
- src/components/common/ConnectWallet/WalletDetails.tsx
- src/components/common/SocialSigner/__tests__/SocialSignerLogin.test.tsx
- src/components/common/SocialSigner/index.tsx
- src/components/settings/SettingsHeader/index.test.tsx
- src/components/settings/SettingsHeader/index.tsx
Part of #2452 
- Hides `Security & Login` on the settings page if not logged in with a social signer
- Enables the Continue with Google button if the user closes the password recovery modal
- Shows part of the supported networks message in a tooltip on the welcome page
- Closes the wallet popover when the recovery modal opens
1. Open the settings page
2. Observe no `Security & Login` navigation item
3. Login with social signer
4. Observe a `Security & Login` navigation item
5. Set a password for the social signer and try to login from a different browser
6. Abort the password recovery modal
7. Observe the Continue with Google button on the welcome page becomes enabled again
> fix: Hide Security&Login from settings if not a social signer

- src/components/settings/SecurityLogin/SocialSignerMFA/index.tsx
- src/components/settings/SecurityLogin/SocialSignerMFA/styles.module.css
Part of #2452
Reloads the app when setting a password so that the state is updated. This is a workaround because there is no observable state for when the password is set or when MFA is enabled. 
2. Login with Google
3. Go to Security & Login settings
4. Set or update the password
5. Observe the page reloads after successful submission
> fix: Reload app when setting password

- src/hooks/wallets/mpc/useSocialWallet.ts
- src/pages/_app.tsx
- src/services/mpc/PasswordRecoveryModal.tsx
- src/services/mpc/SocialLoginModule.ts
Part of #2452 
- Implements the `eth_requestAccounts` for the onboard module
2. Press Connect wallet
3. Select Social Login
4. Observe getting logged in
5. Set a password
6. Log out and login again
7. Observe the password recovery modal opens
8. Submit the modal
9. Observe being logged in
> fix: Add social login option to onboard module

- package.json
- src/hooks/wallets/mpc/useMPC.ts
- yarn.lock
- Updates mpc-core-kit to 1.3.0
- Sets a static hashedFactorKeyNonce to be compatible with Safe{Core}
> chore: update mpc-core-kit

- src/components/settings/SecurityLogin/SocialSignerExport/ExportMPCAccountModal.tsx
- src/components/settings/SecurityLogin/SocialSignerExport/index.tsx
- src/services/analytics/events/mpcWallet.ts
Part of #2452
- Adds new events for the export pk flow
- `Reveal private key` when the user presses the button
- `Export private key successful` when the user successfully types in the password
- `Export private key error` if the password was wrong or the validation failed for another reason
- `Toggle see private key` when the user toggles to see their private key
- `Copy private key` when the user copies their pk
1. Open Safe
2. Login with social
3. Create a password
4. Go through the export pk flow and observe the above mentioned events
> fix: Add events for export pk

- src/hooks/wallets/mpc/useMPC.ts
Disables logs in `useMpc` if in production.
> fix: disable mpcorekit logs in prod

- .dockerignore
- Dockerfile
- Reduce size by using multistage builds
- Run `yarn build` on the build process and not when the docker image starts (it can take a few minutes to complete)
> Optimize docker image

- src/components/common/SocialSigner/index.tsx
- src/components/common/SocialSigner/styles.module.css
Currently the login button only becomes disabled but does not indicate that the login / account creation is in progress.
- Adds a pending state to the social login button
- Login with google on i.e. the Welcome Page
https://github.com/safe-global/safe-wallet-web/assets/2670790/ba56c5da-e6d0-4c08-b5af-aaff29b26b0b
> fix: pending state for social login

- src/components/common/SocialSigner/index.tsx
- src/services/analytics/events/mpcWallet.ts
- src/services/mpc/SocialWalletService.ts
Currently we cannot differentiate between a click on the Google login button in the navigation bar or on our welcome page.
Adds an event label which is either "welcome or 
Click on login with google button in header and welcome page and observe different event labels.
> chore: add event label to google login button

- cypress/e2e/smoke/assets.cy.js
- cypress/e2e/smoke/batch_tx.cy.js
- src/components/balances/AssetsTable/index.tsx
Adds a new screen to the assets page with the Safe QR Code and a link for on-ramping.
> fix: Add ramp view to assets page if there are no assets

- package.json
- src/components/tx/ExecutionMethodSelector/index.tsx
- src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
- src/components/tx/SponsoredBy/index.tsx
- src/hooks/useWalletCanRelay.ts
The relay function disappearing when there are 0 relays is not intutive. It's better to show that the quota is over and that it will reset in an hour.
Plus, I've added a warning that the connected wallet should have enough funds (steps on the toes of #2678, but it's just a quick fix until that PR is merged).
Relay:
Wallet:
> Fix: show relays even when 0 relays left

- src/components/balances/AssetsTable/NoAssets.tsx
- src/components/balances/AssetsTable/index.tsx
Adds a prefix switch for the QR code.
> Fix: prefix switch for receive QR

- src/config/securityHeaders.ts
Signing txs with a social signer is blocked by out CSPs
Allows web assembly through the [CSP directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_webassembly_execution) 'wasm-unsafe-eval'
Set IS_PRODUCTION to true locally and check the social login
> fix: allow execution of web assembly

- cypress/e2e/pages/main.page.js
- cypress/e2e/pages/nfts.pages.js
- cypress/e2e/safe-apps/tx-builder.spec.cy.js
- cypress/e2e/smoke/nfts.cy.js
- src/components/common/ModalDialog/index.tsx
- src/components/nfts/NftGrid/index.tsx
- src/components/nfts/NftSendForm/index.tsx
- src/components/tx-flow/common/TxLayout/index.tsx
- src/components/tx-flow/flows/NftTransfer/SendNftBatch.tsx
- src/components/tx/SignOrExecuteForm/SignForm.tsx
Resolves 
Part of #2776 
- Add test IDs to nft component
- Improve nft tests for reliability
> Tests: Add test IDs and modify NFT tests

- .github/workflows/nextjs_bundle_analysis.yml
- package.json
Resolves #2802
Adds a new action to analyze bundle size changes of the nextjs app
> chore: Analyze NextJS bundle size action

- .github/workflows/nextjs_bundle_analysis.yml
- .gitignore
- src/components/common/ConnectWallet/WalletDetails.tsx
- src/components/common/SocialSigner/index.tsx
- src/components/welcome/WelcomeLogin/index.tsx
- src/hooks/wallets/mpc/__tests__/useMPC.test.ts
- src/hooks/wallets/mpc/useMPC.ts
- src/hooks/wallets/mpc/useRehydrateSocialWallet.ts
- src/hooks/wallets/mpc/useSocialWallet.ts
- src/pages/_app.tsx
- src/services/mpc/SocialLoginModule.ts
Part of #2452 
Lazy loads the mpc core kit to reduce the initial js bundle size
- Converts the `useInitMPC` and `useInitSocialWallet` hooks into functions
- Uses `next/dynamic` to import `SocialSigner`
- Changes the onboard module to lazy import dependencies
1. Open the safe
2. Login with social
3. Observe being logged in
4. Reload the page
5. Observe being logged in with social again
6. Log in with Metamask or any other wallet
7. Observe it still working
> fix: Lazy load mpc core kit

- src/services/recovery/__tests__/recovery-state.test.ts
- src/services/recovery/recovery-state.ts
Querying the recovery state does not work.
- Uses `blockNumber` instead of `blockHash`
- Fixes the endpoint of our tx service
- filters the queueNonces while querying and not afterwards
- Load a Safe that has a recovery tx queued
- Observe the redux state
> fix: fix and optimise fetching the recovery state

- .github/workflows/deploy.yml
In order to be able to test our app with production settings before a release, we'll be building and deploying a production version on staging from the main branch.
With this setup, https://safe-wallet-web.staging.5afe.dev can be used as a close-to-prod environment for pre-release testing.
> Chore: prod build on staging (main)

- package.json
- src/components/tx/SignOrExecuteForm/hooks.ts
- src/services/tx/tx-sender/recommendedNonce.ts
- yarn.lock
Use the new recommended nonce endpoint on the CGW
- The recommended nonce request on tx creation uses the new `/nonces` endpoint
1. Open a Safe
2. Switch to staging CGW
3. Create a new transaction
4. Observe the recommended nonce is loading and correct
CGW ticket - https://github.com/safe-global/safe-client-gateway/issues/681
> fix: Update to new recommended nonce endpoint

- src/components/walletconnect/WcProposalForm/ProposalVerification.tsx
Adjust the warning as per Derek's request.
> :pray:for implementing Verify API - caveat
your language for “mismatch” is a bit strong and also wrong - we do not flag this scenario as “high risk”. Can you pls make the messaging a bit more clear?
> Fix: WC verification wording

- src/components/recovery/SkipRecoveryButton/index.tsx
- src/components/sidebar/SidebarNavigation/index.tsx
- src/components/tx-flow/flows/SkipRecovery/SkipRecoveryFlowReview.tsx
- src/components/tx-flow/flows/SkipRecovery/index.tsx
- src/services/recovery/transaction.ts
Resolves #2763
A new flow for skipping recovery transactions has been added which is opened via the "Skip" buttons in the transaction list.
Note: a hard refresh is required after skipping is executed but this will be fixed in a follow up PR.
1. Propose a recovery attempt.
2. Skip it via the transaction list.
3. Refresh and observe no more recovery attempts listed.
> feat: skip recovery transactions

- src/components/common/EnhancedTable/index.tsx
- src/components/settings/Recovery/index.tsx
Partially resolves #2756
This adds an `EnhancedTable` with all guardians listed, which has placeholder buttons for editing and removing.
Note: the proposal button remains for testing.
Ensure recovery is enabled and observe the styled table in the "Recovery" settings section".
> Recovery settings

- src/services/analytics/types.ts
- src/services/analytics/useGtm.ts
I've added a new user property `walletAddress`.
The Privacy Policy for this has been updated in #2840.
* Open the console
* Connect a wallet
* See that it logs a new GTM user property
> Analytics: track wallet address

- .github/workflows/ondemand.yml
- .github/workflows/regression.yml
- .github/workflows/safe-apps-e2e.yml
- .github/workflows/smoke.yml
- cypress.config.js
Resolves #2825 
Recently it was noticed that some machines started to fail when running Cypress tests in parallel. This was due to different version of Chrome passed by random machines, where Cypress requires all machines pass identical environment. The fix was to use specific version of Chrome and add this step to our test workflows. 
Part of this task also included increasing number of test retries to reduce flaky tests. This will be observed and adjusted as needed.
> Tests: Add Chrome version to smoke tests workflow

- Dockerfile
- Add node-gyp before installing other packages
- Increase yarn timeout
> Fix ARM64 docker image build

- src/hooks/useTxTracking.ts
- src/services/analytics/events/transactions.ts
In #2787, we added a new event `Create transaction`. Since a signature is required for both tx creation and confirmation, we cannot use the existing `Off-chain signature` event to track signatures for existing transactions.
So I've added another event, `Confirm transaction` to track specifically those kind of signatures.
> Analytics: add a Confirm transaction event

- src/components/settings/RecoveryEmail/AddEmailDialog.tsx
- src/components/settings/RecoveryEmail/index.tsx
- src/components/settings/RecoveryEmail/styles.module.css
- src/components/tx-flow/common/OwnerList/index.tsx
- src/pages/settings/notifications.tsx
Partially resolves #2757
This implements a basic setting structure and modal for adding a recovery email.
Open the "Notifications" setting and observe the new template structure, as well as modal that opens when clicking "Add email address".
> feat: recovery email settings structure

- src/components/dashboard/PendingTxs/PendingRecoveryListItem.tsx
- src/components/dashboard/PendingTxs/PendingTxList.test.ts
- src/components/dashboard/PendingTxs/PendingTxListItem.tsx
- src/components/dashboard/PendingTxs/PendingTxsList.tsx
- src/components/dashboard/PendingTxs/styles.module.css
- src/components/recovery/RecoveryInfo/index.tsx
- src/components/recovery/RecoverySummary/index.tsx
- src/components/tx-flow/common/OwnerList/index.tsx
Resolves #2755
Pending recovery attempts are now listed in the pending transaction dashboard widget.
Ensuring recovery is enabled, queue a recovery attempt (as well as a standard transaction) and observe the both in the pending transaction list widget on the dashboard
> feat: pending recoveries in dashboard widget

- .github/workflows/ondemand.yml
Resolves #2856 
- To optimise testing efforts and ensure the timely detection and addressing of potential bugs, we need to enable Cypress tests to run on a daily basis.
> Tests: Add tests schedule

- .github/workflows/e2e-ondemand.yml
Resolves #2859 
- To be able to generate test run reports in TestRail, this integration needs to be added to Cypress on demand tests. By doing this, we will get recorded results and will be able to track them going forward.
> Tests: Add TestRail integration to CI

- .github/workflows/e2e-ondemand.yml
Resolves #2859 
- In order for TestRail to accept JUnit tests reports, we need to generate a single report by merging already generated ones.
> Tests: Add junitparser to TestRail in CI

- src/components/recovery/RecoveryContext/__tests__/useRecoveryDelayModifiers.test.ts
- src/components/recovery/RecoveryContext/index.tsx
- src/components/recovery/RecoveryContext/useRecoveryDelayModifiers.ts
- src/components/settings/Recovery/index.tsx
- src/services/recovery/__tests__/delay-modifier.test.ts
- src/services/recovery/delay-modifier.ts
Resolves Zodiac-deployed Delay Modifiers from showing as recovery guardians
The modules of a Delay Modifier are iterated over checked whether they are other Zodiac contracts. (Zodiac only either deploy the Delay Modifier _without_ modules and/or with [Zodiac contracts as modules](https://github.com/gnosis/zodiac-safe-app/blob/e5d6d3d251d128245104ddc638e26d290689bb14/packages/app/src/views/AddModule/wizards/RealityModule/service/moduleDeployment.ts#L88).) In contrasts, we deploy the Delay Modifier with non-Zodiac contracts added enables as modules.
Enable a Delay Modifier via the Zodiac Safe App directly, or alternatively by enabling the Reality module. Observe that neither appears in the recovery settings of the Safe.
> fix: filter Zodiac-deployed Delay Modifiers

- src/components/common/SocialSigner/PasswordRecovery.tsx
- src/components/common/SocialSigner/__tests__/SocialSignerLogin.test.tsx
- src/components/common/SocialSigner/index.tsx
- src/hooks/wallets/useOnboard.ts
The connect wallet request when connecting from the onboard module got stuck in a promise that never resolved after calling `connectWallet`.
Resolves #2863 
Does not allow two concurrent `connectWallet` requests.
- Ensure that for your social signer MFA is enabled
- Click connect wallet
- Select Social signer
- Login and recover password
- Observe the modal to close
> fix: successfully connect after password recovery

- src/components/common/PageLayout/index.tsx
- src/components/recovery/RecoveryModal/index.test.tsx
- src/components/recovery/RecoveryModal/index.tsx
- src/hooks/useIsSidebarRoute.ts
Resolves recovery-related modals opening when adding a Safe.
The modal displays are now disabled on "non-sidebar" routes.
1. Ensure that recovery is enabled and the guardian wallet is connect.
2. Remove the Safe in question from the added Safes.
3. Remove the `SAFE_v2__dismissedRecoveryProposals` `localStorage` key.
4. Open the add Safe flow and observe no modal opening.
> fix: disable recovery modals on non-sidebar routes

- src/components/common/PaginatedTxns/index.tsx
- src/components/dashboard/PendingTxs/PendingTxsList.tsx
- src/components/recovery/GroupedRecoveryListItems/index.tsx
- src/components/recovery/RecoveryList/index.tsx
- src/components/tx-flow/flows/RecoverAccount/RecoverAccountFlowReview.tsx
- src/utils/__tests__/tx-list.test.ts
- src/utils/transaction-guards.ts
- src/utils/tx-list.ts
Resolves #2763
This groups recovery attempts and their cancellations together as we do with conflicting transactions.
Ensuring recovery is enabled, queue a recovery attempt and cancel it. Observe the grouping at the top of the queue.
> feat: recovery attempt + cancellation grouping

- src/services/analytics/spindl.ts
- src/services/analytics/useGtm.ts
We were planning to allowlist only the prod domain via Spindl's settings, but this setting doesn't seem to work (error 500) on their side, so we'll have to disable it on the client.
> Fix: disable spindl on dev

- src/components/common/ChainIndicator/index.tsx
- src/components/common/Footer/index.tsx
- src/components/common/WalletInfo/index.tsx
- src/components/safe-apps/SafeAppLandingPage/SafeAppDetails.tsx
- src/components/safe-apps/SafeAppPreviewDrawer/index.tsx
The chain indicator in the WalletInfo popup should show the wallet's network, not Safe network.
> Fix: wallet chain in wallet info

- package.json
- yarn.lock
Upgrade to [the latest safe-modules-deployments](https://github.com/safe-global/safe-modules-deployments/releases/tag/v1.2.0) to enable Spending Limits on Sepolia.
> Fix: enable spending limits on Sepolia

- src/components/tx-flow/flows/UpsertRecovery/UpsertRecoveryFlowSettings.tsx
Resolves `ref` warning
The `ref`s within the recovery upsertion flow are now forwarded correctly.
Enable/edit the recovery feature and on the settings page where the delay/expiration period can be edited, observe no `ref` warning:
> fix: ref warning

- src/components/recovery/ExecuteRecoveryButton/index.tsx
- src/components/recovery/RecoverySigners/index.tsx
- src/components/tx-flow/flows/CancelRecovery/CancelRecoveryFlowReview.tsx
- src/hooks/useRecoveryQueue.ts
Resolves [malformed queue](https://www.notion.so/safe-global/Wrong-message-about-expired-recovery-in-the-next-recovery-tx-7a61aef7aa1949f98cfcedad587b6588)
Expired recovery attempts are no longer filtered from the queue.
The Delay Modifier requires the "next" transaction to be executed/cancelled before the [`txNonce` + n transaction can be executed](https://github.com/gnosis/zodiac-modifier-delay/blob/main/contracts/Delay.sol#L195-L198).
Note: missed instances of "skipped" have been changed to "cancelled" as per previous requirements.
1. Ensuring the recovery module is enabled with a low expiration period, queue two recovery attempts.
2. After expiration has passed, observe both attempts remaining in the queue and the first cancellable, the second not.
3. After cancelling the first, the …
> fix: don't filter expired recovery attempts from queue

- src/components/settings/Recovery/index.tsx
Resolves [missing label for cooldown/expiration](https://www.notion.so/safe-global/Never-is-not-displayed-as-Expiry-6e1056ce860d48f4be043025afb19fc6)
If the cooldown or expiration is set to `0`, the periods are labelled as "none"/"never" respectively.
1. Ensure recovery is enabled with a cooldown of `0` and expiration of `0`.
2. Observe a cooldown period of "none" and expiration of "never" in the recovery settings.
> fix: show "none"/"never" for no cooldown/expiration

- src/components/common/PageLayout/index.tsx
- src/components/recovery/RecoveryModal/index.test.tsx
- src/components/recovery/RecoveryModal/index.tsx
- src/pages/_app.tsx
Resolves proposal modal opening for non-Guardians
The recovery proposal now _only_ opens if a Guardian is connected.
Note: the `RecoveryModal` was also refactored be not take `children` for future safety.
1. Ensuring recovery is enabled, open a Safe as a Guardian and observe the proposal modal.
2. Switch to a non-Guardian and observe no proposal modal.
> fix: only display proposal modal to Guardians

- src/utils/__tests__/tx-list.test.ts
- src/utils/tx-list.ts
Resolves [grouping non-recovery cancellations](https://www.notion.so/safe-global/Cancelling-Account-recovery-cc139f5915a04bc19a91b1fd44c1a21c)
Non-recovery related transactions are not grouped in arrays and relevant test coverage has been improved.
1. Propose a recovery attempt.
2. Cancel recovery attempt.
3. Queue a "standard" transaction.
4. Observe only the recovery cancellation grouped with the recovery attempt.
> fix: only group recovery transactions in arrays

- src/components/tx-flow/flows/UpsertRecovery/UpsertRecoveryFlowSettings.tsx
Resolves [missing Guardian info](https://www.notion.so/safe-global/af7bf82ec5a040d3acc20b167bb0656a?v=27045d3b2d0a4c938f627bb5f23bc7f5&p=b6b1ff47552b4d42bfb230cc8b825c65&pm=s)
An `Alerts` with the respective information has been added to the recovery settings section of the upsertion flow.
Enable/edit recovery and observe the new information below the "Trusted Guardian" section.
> Guardian info

- src/components/recovery/CancelRecoveryButton/index.tsx
- src/components/recovery/ExecuteRecoveryButton/index.tsx
- src/components/recovery/RecoveryListItem/RecoveryListItemContext.tsx
- src/components/recovery/RecoveryListItem/index.tsx
- src/components/recovery/RecoverySigners/index.tsx
- src/services/tx/tx-sender/dispatch.ts
Resolves [recovery transaction error handling](https://www.notion.so/safe-global/Error-when-creating-editing-recovery-setup-without-changes-f82ad44386e547c99d2a9444854e4344?d=3775d9c982be43949926b42571b746bb)
A new error-specific context has been added around each `RecoveryListItem` which is rendered when present above the execution buttons. On top of this, errors thrown by the respective recovery transaction dispatchers are now thrown again as they were not being caught correctly.
1. Propose a recovery and reject it, observing the error object showing as we do with "normal" transactions.
2. Execute/reject a recovery proposal (as a Guardian) and observe the new error message showing above the execution buttons, or alternatively opening the respective accordion if done so via the summary …
> fix: handle recovery errors

- src/components/recovery/RecoveryCards/RecoveryInProgressCard.tsx
- src/components/recovery/RecoveryCards/__tests__/RecoveryInProgressCard.test.tsx
Resolves [unclear expired recovery transaction](https://www.notion.so/safe-global/Expired-recovery-process-blocks-start-recovery-from-the-dashboard-c9a79955b4eb4592a70d367445ca958b)
A new message is displayed in the "in-progress" modal/header widget on the dashboard if the "next" recovery transaction expired.
1. Queue a recovery transaction, ensuring that it will expire.
2. Observe the new text within the "in-progress" modal component.
> fix: add expiration state to in-progress modal

- src/components/tx-flow/flows/SuccessScreen/index.tsx
Bug: if you're on an individual transaction page and execute it, the View transaction button on the Success screen doesn't do anything (it navigates to the same page and doesn't close the modal).
Solution: it will now close the modal.
> Fix: close tx flow on "View transaction"

- src/components/recovery/CancelRecoveryButton/index.tsx
- src/components/settings/Recovery/index.tsx
- src/components/tx-flow/flows/UpsertRecovery/UpsertRecoveryFlowReview.tsx
- src/components/tx-flow/flows/UpsertRecovery/UpsertRecoveryFlowSettings.tsx
Resolves ability to [cancel recovery attempts after expiration](https://www.notion.so/safe-global/Cancel-recovery-tx-after-Recovery-delay-f8af1f46751f41a2bb735aec783a388c)
The disable logic has been altered to only take the expiration into account when not connected as an owner, as well as adjusting the information about cancellation throughout the app.
Observe cancellation is _always_ possible as an owner, wheras if not an owner only after expiration.
> fix: allow cancellation after expiration

- src/services/ens/config.ts
- src/services/ens/custom.ts
- src/services/ens/index.test.ts
- src/services/ens/index.ts
Resolves #2687.
Ethers v5.7 unfortunately doesn't support Sepolia out of the box, and upgrading to the latest version is complicated.
So as a temporary fix, I'm adding a custom resolver for Sepolia.
> Feat: custom ENS lookup for Sepolia

- src/components/tx-flow/flows/ExecuteBatch/ReviewBatch.tsx
- src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
Resolves #2896
I've removed the flag that disabled the Execute button whilst polling the validity of the tx execution. The validation error itself doesn't block the Execute button, so why should its loading state do that?
> Fix: don't refresh ExecuteForm on validation polling

- src/components/welcome/WelcomeLogin/index.tsx
The position of the Safe logo on the Welcome page, although perfectly in the middle of the block mathematically, looked unbalanced because of the graphical and textual parts of the logo. I've shifted it a bit to the left and it looks more centered now.
Before:
After:
> Fix: logo centering on welcome page

- src/components/recovery/CancelRecoveryButton/index.tsx
- src/components/recovery/ExecuteRecoveryButton/index.tsx
- src/components/recovery/RecoveryContext/__tests__/useRecoveryPendingTxs.test.ts
- src/components/recovery/RecoveryContext/__tests__/useRecoveryState.test.tsx
- src/components/recovery/RecoveryContext/index.tsx
- src/components/recovery/RecoveryContext/useRecoveryPendingTxs.ts
- src/components/recovery/RecoveryContext/useRecoveryState.ts
- src/components/recovery/RecoveryStatus/index.tsx
- src/components/recovery/RecoverySummary/index.tsx
- src/components/tx-flow/flows/RecoverAccount/RecoverAccountFlowReview.tsx
- src/hooks/__tests__/useRecoveryTxState.test.tsx
- src/hooks/useRecoveryTxState.ts
- src/services/recovery/recovery-sender.ts
- src/services/recovery/recoveryEvents.ts
- src/services/tx/tx-sender/dispatch.ts
Resolves [missing "Processing..." state for recovery transactions](https://www.notion.so/safe-global/Do-we-have-a-processing-relaying-state-instead-of-awaiting-confirmation-for-the-Account-recovery-5a07f9ed7cde429ba976fe7ad16e5f59)
A new recovery-focused event bus has been added that matches that of the one for "standard" transactions and messages. Using that, a new pending map is updated according to the dispatched events and parsed for the current status of a recovery attempt.
1. Queue a recovery attempt.
2. Execute/cancel the attempt and observe the new processing status.
Note: data loading should also be tested - recovery state updates when a proposal is executed, cancelled and/or settings are changed.
> feat: recovery transaction processing state

- src/components/dashboard/index.tsx
Resolves [recovery feature widget not hiding after being enabled](https://www.notion.so/safe-global/Remove-the-Edit-recovery-banner-from-the-Dashboard-after-the-recovery-is-set-up-cc6336c7391f4faf8cf587f5680ca70f)
The dashboard widget featuring recovery is now not only hidden if the chain doesn't support it but also if the feature is enabled on the current Safe.
Switch between Safes that have recovery enabled/disabled and observe the dashboard widget hidden accordingly.
> fix: hide recovery widget if feature enabled

- src/hooks/loadables/useLoadSafeMessages.ts
Resolves #1403
Removes a polling timer and listens to the `messagesTag` from the backend instead.
* Open the Messages tab
* In another browser window, create a new message (e.g. OpenSea login)
* Observe that the new message appeared on the Messages tab within 15 seconds
> Refactor: poll messages based on messagesTag

- src/components/recovery/RecoverySigners/index.tsx
Resolves [incorrect description of failed attempts](https://www.notion.so/safe-global/Expired-recovery-process-blocks-start-recovery-from-the-dashboard-c9a79955b4eb4592a70d367445ca958b)
The description of a failed transaction has been added under the recovery signers.
Queue a recovery transaction with a delay and expiration enabled and observe the following lifecycle description under the signers.
1. "The recovery transaction can be executed after the delay period has passed:"
2. "The recovery transaction can be executed until {{date}}." (without expiration: "The recovery transaction can be executed now.")
3. "The recovery transaction has expired and needs to be cancelled before a new one can be created."
> fix: adjust description of expired transactions

- src/components/recovery/ExecuteRecoveryButton/index.tsx
Resolves [unclear tooltip text](https://www.notion.so/safe-global/Reword-execute-button-tooltip-22e7a21a1ec743a9904246e595c0bb77)
The execution button tooltip (shown when no wallet is connected or a recovery transaction is not executable/pending) now reads:
1. "You can execute the recovery after the specified delay" when the transaction is next and awaiting cooldown to pass
2. "Previous recovery attempts must be executed or cancelled first" when the transaction is queued
Queue a recovery transaction with a delay and observe the new tooltip text on hover.
> fix: adjust recovery execution button tooltip text

- src/components/tx-flow/flows/UpsertRecovery/RecovererSmartContractWarning.tsx
- src/components/tx-flow/flows/UpsertRecovery/UpsertRecoveryFlowSettings.tsx
Resolves [style inconsistencies of smart contract validation](https://www.notion.so/safe-global/Validate-EOA-and-Safes-in-the-guardian-input-f93b1340c71c424ea191dfc5adfb835f)
The style of the smart contract validation has been adjusted to match that of the address add functionality below an address input (see screenshots).
Upsert the recovery Recoverer and enter a non-Safe smart contract, observing the correctly styled message.
> fix: smart contract warning style

- src/components/tx-flow/flows/UpsertRecovery/UpsertRecoveryFlowSettings.tsx
- src/components/tx-flow/flows/UpsertRecovery/index.tsx
Resolves [disabled next button when selecting address from address book](https://www.notion.so/safe-global/Can-not-edit-recovery-set-up-436b288d55784a0c93e0f428b8cf706d)
We manually check the "dirty" status of input fields when upserting recovery.
Note: focus on pasting vs. selecting addresses from the address book dropdown.
- Test each input field as dirty _before_ and _after_ confirming consent
- Test each input field as dirty _before_ and _after_ confirming consent
> fix: manually check dirty status

- src/hooks/__tests__/useRecoveryTxState.test.tsx
- src/services/recovery/__tests__/recovery-state.test.ts
- src/services/recovery/recovery-state.ts
Resolves [recovery of <1.3.0 Safes showing as malicious](https://www.notion.so/safe-global/1-1-1-Recovery-tx-is-displayed-as-Malicious-Transaction-16f6beb12675450cbcd1d75df906d856)
The initial deployment version of the MultiSendCallOnly contract is used as a fallback when checking for maliciousness of a recovery attempt.
Propose a recovery attempt on a <1.3.0 Safe and observe that it is not marked as malicious in the queue.
> fix: fallback MultiSend version for maliciousness

- src/components/common/AddressBookInput/index.tsx
- src/components/tx-flow/flows/UpsertRecovery/UpsertRecoveryFlowSettings.tsx
Resolves [missing prefix validation within recovery flows](https://www.notion.so/safe-global/Guardian-field-prefix-validation-is-missing-089a12f5e6f4482580b697bd83fd183d)
The `shouldValidate` flag has been removed from the `AddressBookInput` `onInputChange` as it was causing too many subsequent validation attempts, roughly the following:
1. Incorrectly prefixed address entered.
2. Validation error occurs but value is also parsed to not have a prefix.
3. Validation occurs again via flag.
4. Value is now valid ad the prefix was removed.
Removing this flag should not affect any other places as the validation inherently occurs within `AddressInput` but we should check other areas that the component is used, namely:
- Transaction filter
- Safe creation flow owner fields
- Add owner flow owner …
> fix: prefix validation within recovery flows

- src/components/dashboard/RecoveryHeader/index.test.tsx
- src/components/dashboard/RecoveryHeader/index.tsx
- src/components/recovery/RecoveryContext/__tests__/useRecoveryPendingTxs.test.ts
- src/components/recovery/RecoveryContext/useRecoveryPendingTxs.ts
- src/hooks/useRecoveryTxNotification.ts
- src/services/recovery/recovery-sender.ts
- src/services/recovery/recoveryEvents.ts
Resolves [smart contract Recoverers not working](https://www.notion.so/safe-global/Safe-as-an-Recoverer-create-recovery-tx-form-is-not-updated-and-manual-closing-is-required-53071d129364467aa1b18bfd2a2a368e)
An unchecked signer is now used when interfacing with the Delay Modifier if the connected provider is a smart contract.
1. Enable a Safe as a Recoverer.
2. Propose a recovery and observe that the proposal modal closes and loads after the proposal is executed.
3. Executing/skipping recovery proposals should work in the same way.
> fix: use unchecked for smart contract recoverers

- src/components/recovery/RecoveryContext/__tests__/useRecoveryPendingTxs.test.ts
- src/components/recovery/RecoveryContext/__tests__/useRecoverySuccessEvents.test.ts
- src/components/recovery/RecoveryContext/index.tsx
- src/components/recovery/RecoveryContext/useRecoveryPendingTxs.ts
- src/components/recovery/RecoveryContext/useRecoverySuccessEvents.ts
- src/components/recovery/RecoveryStatus/index.tsx
- src/hooks/useRecoveryTxNotification.ts
- src/services/recovery/recoveryEvents.ts
Resolves missing `SUCCESS` notifications
A new `useRecoverySuccessEvents` hook has been added to the `RecoveryContext` which dispatches a new `RecoveryEvent.SUCCESS` according to the pending/queue recovery state.
For proposal creations and executions/cancellations _by Recoverers_, observe a new success notification after the transaction is executed/loaded in the interface.
> feat: add `RecoveryEvent.SUCCESS` notifications

- src/components/transactions/TxDetails/index.tsx
Tx details showed a loader every 15 seconds which made the whole tx jump in the History/Queue.
> Fix: tx details - show loader only when no data

- src/components/common/AddressBookInput/index.tsx
- src/components/common/AddressInputReadOnly/index.tsx
Resolves #2931
I've disabled copying address in the AddressBookInput dropdown.
> Fix: disable copying address in AddressBookInput

- src/components/tx-flow/flows/RecoverAccount/RecoverAccountFlowReview.tsx
Resolves [disabled button without feedback](https://www.notion.so/safe-global/Safe-as-an-Recoverer-create-recovery-tx-form-is-not-updated-and-manual-closing-is-required-53071d129364467aa1b18bfd2a2a368e?d=73579f2095094da49aec3e7eb572559f)
When proposing a recovery, the execution button now has a spinner within it instead of just being disabled.
Propose a recovery and observe a spinner within the execution button.
> fix: [Recovery] add spinner to button when proposing

- src/components/tx-flow/flows/UpsertRecovery/useRecoveryPeriods.ts
Reduces delay periods on all networks
The test network periods have been enabled by default.
Open a non-test network and observe the test periods available during recovery upsertion.
> fix: temporarily reduce delay period

- src/components/tx-flow/flows/UpsertRecovery/UpsertRecoveryFlowReview.tsx
- src/components/tx-flow/flows/UpsertRecovery/useRecoveryPeriods.ts
Resolves [expiry time displayed in seconds](https://www.notion.so/Proposal-expire-time-is-in-seconds-instead-of-human-readable-time-format-5e4f039fd65d41ba86ea1adc791a64ef)
The expiry time on the upsertion review screen is now displayed by it's label, e.g. "1 minute" instead of "60".
Note: this also includes a small fix for [the test period of "1 hour" which was incorrectly set to have a value of 1 day](https://www.notion.so/safe-global/Setting-the-recovery-in-1-hour-actually-sets-its-for-1-day-64d8bc3a5f4f4528b40e4bc062901046).
Open the recovery upsertion flow and set an expiration period and delay period of 1 hour. Observe the correctly labelled expiration period and delay period setting to 1 hour.
> fix: recovery expiry label

- src/components/tx-flow/flows/RecoverAccount/RecoverAccountFlowSetup.tsx
Resolves [QR modal not opening in proposal flow](https://www.notion.so/safe-global/The-QR-code-icon-in-the-recovery-form-doesn-t-work-28b73698d4a340b284f9168b448c4158)
The validation `mode` of the proposal flow has been changed from `all` to `onChange` (matching that of the other recovery flows. The modal was otherwise closing immediately due to error focusing.
Open the recovery proposal flow and click the address input QR, observing that it opens.
> fix: (Recovery) change validation `mode` for QR modal

- src/components/tx-flow/flows/CancelRecovery/CancelRecoveryFlowReview.tsx
- src/components/tx-flow/flows/RecoverAccount/RecoverAccountFlowReview.tsx
- src/components/tx-flow/flows/RemoveRecovery/RemoveRecoveryFlowReview.tsx
- src/components/tx-flow/flows/UpsertRecovery/UpsertRecoveryFlowReview.tsx
- src/services/analytics/events/recovery.ts
- src/services/analytics/events/transactions.ts
Part of Recovery EPIC
- Emits custom recovery events instead of using `TX_EVENTS.CREATE` since with #2914 they would be tracked twice in some cases
Create, edit, remove a recovery setup and observe the new events
Create and cancel a recovery attempt and observe the new events
> refactor: Use custom recovery events instead of create tx events

- src/components/batch/BatchSidebar/BatchTxItem.tsx
- src/components/transactions/TxSummary/index.tsx
- src/components/transactions/TxSummary/styles.module.css
The human-readable A/B test was removed in #2900 but some leftovers remained. This PR cleans that up which fixes the missing tx summary.
> Fix: rm human-readable leftovers

- src/components/common/AddressBookInput/index.tsx
- src/components/common/SafeTokenWidget/index.tsx
- src/components/common/TokenAmountInput/index.tsx
- src/components/tx-flow/flows/NewSpendingLimit/CreateSpendingLimit.tsx
- src/components/tx-flow/flows/NftTransfer/SendNftBatch.tsx
- src/components/tx-flow/flows/TokenTransfer/CreateTokenTransfer.tsx
- src/components/tx-flow/flows/TokenTransfer/__tests__/CreateTokenTransfer.test.tsx
- src/components/tx-flow/flows/TokenTransfer/__tests__/utils.test.ts
- src/components/tx-flow/flows/TokenTransfer/utils.ts
- src/components/tx/SpendingLimitRow/index.tsx
- src/components/tx/SpendingLimitRow/styles.module.css
- src/hooks/useIsSafeTokenPaused.ts
Resolves #2880 
- Hides the nonce input field if a non-owner tries to create a spending limit transaction
- Pre-selects the first available token when a non-owner tries to create a spending limit transaction
- Displays the nonce input again if an owner switches from a spending limit token to a non-spending limit token
1. Open a safe with a spending limit as a non-owner
2. Create a transaction and observe the nonce input is hidden
3. Observe a token is pre-selected in the form
---
1. Open a safe as an owner that also has a spending limit
3. Observe the nonce input being visible
5. Select the spending limit token and select spending limit in the radio group
6. Observe the nonce input is hidden
7. Switch to a different token
8. Observe the nonce input is visible
> Fix: Hide nonce input if its a spending limit transaction

- src/utils/transaction-guards.ts
Improves the strictness of the `isRecoveryQueueItem` type guard.
The `eventSignature` uniqueness of the `RecoveryQueueItem` is checked that it is `"TransactionAdded(uint256,bytes32,address,uint256,bytes,uint8)"`.
Queue a recovery proposal and observe that the dashboard and transaction list queues work as expected.
> refactor: improve `isRecoveryQueueItem` strictness

- src/components/common/EnhancedTable/index.tsx
- src/components/settings/owner/OwnerList/index.tsx
Resolves inability to export owner list
This adds an export button below the owner list that, when clicked, creates as CSV file listing the current owners of the Safe Account and their name prioritised by address book then "known address".
Open the owner list and click the new export button. Observe that the downloaded CSV lists all the owners.
> feat: add export button to owner list

- cypress/e2e/pages/create_tx.pages.js
- cypress/e2e/pages/main.page.js
- cypress/e2e/regression/remove_owner.cy.js
- cypress/e2e/regression/tx_history.cy.js
- cypress/e2e/regression/tx_history_2.cy.js
- cypress/e2e/smoke/add_owner.cy.js
- cypress/e2e/smoke/address_book.cy.js
- cypress/fixtures/txhistory_data_data.json
Resolves #2979 
To increase coverage in tx history, tests for the following tx types were added:
- on-chain rejection
- batch 
- add/change/remove owner
- delete module
- change threshold.
> Tests: History tests - part 2

- src/components/batch/BatchSidebar/index.tsx
- src/components/common/ConnectWallet/AccountCenter.tsx
- src/components/notification-center/NotificationCenter/index.tsx
- src/components/walletconnect/WcHeaderWidget/index.tsx
MUI has a default animation when a dropdown or a popup opens. It makes them feel slow.
This PR sets the animation duration to 0 for the dropdowns in the header. It makes the UI much snappier.
> Fix: speed up popups

- src/components/common/ConnectWallet/AccountCenter.tsx
- src/components/common/WalletInfo/index.tsx
The balance doesn't reload anymore whenever the header popup is opened and closed
Pass the balance from the header to the child component instead of using the same hook twice
1. Connect a wallet
2. Open the account center through the header
3. Observe the balance being visible
4. Close the popup and open it again
5. Observe no loading state
> fix: Dont reload balance when popup is closed

- src/components/safe-apps/AppFrame/index.tsx
- src/hooks/useTxQueue.ts
- src/services/analytics/gtm.ts
- src/services/analytics/useGtm.ts
We need to track the query params to pass UTM-params to GA.
> Analytics: include query params in the pageview event

- src/components/common/AddressBookInput/index.tsx
Resolves #2993
The label property wasn't propagated properly to the ReadonlyInput.
> Fix: add/replace owner input label

- cypress.config.js
- cypress/e2e/pages/create_tx.pages.js
- cypress/e2e/pages/create_wallet.pages.js
Resolves #
- Quick fix for data copy tests to clipboard
> Tests: Fix copy tests

- .github/workflows/nextjs-bundle-analysis.yml
- scripts/github/download_bundle_analyser_artifact.sh
Follow up for #2803 
The download-artifact action we use downloads artifacts in chronological order so it always compares with the oldest dev bundle instead of the newest. There is an open issue on the board but no fix so far ([see discussion](https://github.com/dawidd6/action-download-artifact/issues/240)). We switch to a custom bash script that is also linked in the discussion to download and unzip the bundle from dev.
> chore: Download latest bundle analysis artifact from base branch

- src/hooks/wallets/useOnboard.ts
- src/services/onboard.ts
- src/utils/wallets.ts
After #2343, the reconnect behavior with MetaMask became extremely annoying. Every time you open the browser and go to the app, it pops up a locked MetaMask window even if you don't need the wallet at that moment.
This PR limits the auto-connect to only when MetaMask is already password-unlocked. The behavior for other wallets is unchanged.
Unlocked MetaMask:
1. Go to the app
2. Connect MetaMask (unlock it if password-locked)
3. Refresh the page
4. MetaMask should seamlessly reconnect w/o showing the onboard modal
Locked MetaMask:
1. Disconnect MetaMask if connected
2. Completely close the browser
3. Open the browser again and go to the app
4. Make sure MetaMask is password-locked
5. Observe that the app didn't auto-connect to MetaMask
Other wallets:
They should reconnect like before.
> Fix: reconnect MetaMask only if unlocked

- src/components/safe-apps/AppFrame/useAppCommunicator.ts
Resolves https://github.com/safe-global/safe-apps-sdk/issues/480
This will be a fast hotfix for the issue above. Final fix for the bug was detected in https://github.com/safe-global/safe-apps-sdk/pull/530
Because it may take time to reach all the dependencies where the package is used will publish this as an emergency fix while developers update to the recent version with the fix.
Set the normalized empty value when undefined is set for `value` or  `data` for a Safe App `sendTransaction` event.
> fix: Add default values for `value` and `data` in AppCommunicator

- src/utils/wallets.ts
As per @schmanu's comment:
> After rehydrating the Web3Auth session we automatically call connectWallet we have to avoid calling connectWallet on page load as the MPC connection is not ready yet then and the connectWallet call on rehydration get’s blocked somehow.
I've disable auto-reconnect for the social login.
> Fix: don't auto-reconnect social login

- src/hooks/wallets/__tests__/useWalletBalance.test.ts
- src/hooks/wallets/useWalletBalance.ts
Polls wallet balance every 15s.
Resolves [Notion issue](https://www.notion.so/safe-global/04fafddb03ce4ec79611081c819f45a7?v=8b8e36baa6484c8cb1163334d656a89c&p=57d297e101de4401bc312cce59a36ec1&pm=s)
Polls the connected wallet's balance every 15s
- Connect a wallet
- Send native tokens out of that wallet or in to the wallet
- observe that it updates automatically after a while
> fix: poll wallet balance

- package.json
- src/components/sidebar/SidebarNavigation/index.tsx
- src/pages/apps/index.tsx
- src/pages/apps/open.tsx
Resolves #3016
This PR reinstates the feature toggle so that it's possible to remotely disable all Safe Apps.
The feature is currently toggled off on prod.
> Fix: use SAFE_APPS feature toggle

- src/hooks/safe-apps/useSafeAppsFilters.ts
- src/pages/apps/index.tsx
The search input in the Safe Apps list was painfully slow to type. Instead of debouncing using a hook, I've added a debounce directly to the onchange listener and it's much faster. Still far from ideal but much faster.
Type something in the Safe Apps search filter.
> Fix: safe apps search performance

- cypress/e2e/regression/tx_history.cy.js
- cypress/e2e/regression/tx_history_2.cy.js
- cypress/e2e/safe-apps/tx-builder.spec.cy.js
- cypress/e2e/smoke/tx_history.cy.js
Resolves #3019 
- As part of our continuous automation test coverage, we are adding some tx history tests to our smoke tests suite.
- Part of this ticket also includes minor update of tx builder test.
- Run E2E tests and observe outcome.
> Tests: Update tx builder and add tx history tests to smoke suite

- src/components/common/ScanQRModal/ScanQRButton.tsx
- src/services/analytics/events/modals.ts
Adds a new analytics event emitted after a successfull QR code scan.
I've made a [GA exploration](https://analytics.google.com/analytics/web/#/analysis/p308247657/edit/QUA2dWwnRmyWKbKZDz1H8w
) for the "Scan QR" event. It shows an average of 100-150 events a day. I'd like to test the hypothesis that many of those clicks don't result in an actual scan.
> Analytics: track successfull QR scans

- src/components/common/ConnectWallet/AccountCenter.tsx
- src/components/common/WalletInfo/index.tsx
Fetching the wallet balance to display in the header using the "readonly" RPC provider drastically increased the number of RPC requests.
Reverting until we figure out how to get this data w/o extra load.
* Fetch the balance via the connected wallet RPC provider
* Use the balance that web3-onboard provides (has to be parsed from a string)
> Fix: don't show balance in header

- .github/workflows/tag-release.yml
The GitHub Tag & Release job was incorrectly configured to run the last step even if a PR to main is closed w/o merging.
Moved `if: github.event.pull_request.merged == true` to the top to apply to the entire job.
> Chore: create a release only if PR is merged

- src/components/new-safe/create/steps/ReviewStep/index.tsx
- src/components/tx/BalanceInfo/index.tsx
- src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
- src/components/tx/SignOrExecuteForm/__tests__/ExecuteForm.test.tsx
- src/hooks/__tests__/useWalletCanPay.test.ts
- src/hooks/useWalletCanPay.ts
A follow up to #2678 to show an error to the user if their connected wallet balance is too low to execute a transaction or create a safe
- Shows an error in case relaying is not selected and wallet balance is too low
1. Try to execute a transaction with a wallet that doesn't have enough funds
2. Observe an error in the transaction review screen
3. Check that the error is only shown if relaying is not selected
4. Try to create a safe with a wallet that doesn't have enough funds
5. Observe an error in the review screen
> feat: Show error on tx and safe creation if wallet balance is insufficient

- src/components/common/ConnectWallet/AccountCenter.tsx
- src/components/common/SocialLoginInfo/index.tsx
- src/components/common/WalletBalance/index.tsx
- src/components/common/WalletInfo/index.test.tsx
- src/components/common/WalletInfo/index.tsx
- src/components/common/WalletInfo/styles.module.css
- src/components/common/WalletOverview/index.tsx
- src/components/tx/SignOrExecuteForm/__tests__/SignOrExecute.test.tsx
- src/hooks/wallets/__tests__/useOnboard.test.ts
- src/hooks/wallets/useOnboard.ts
- src/hooks/wallets/useWalletBalance.ts
For the header widget, use the balance string returned by web3-onboard as it fetches it from the wallet RPC anyway.
The returned balance always matches the wallet chain, not the Safe chain, so I made it clearer in the header widget:
---
In the tx-flow, it will still get an updated wallet balance directly from the readonly RCP like before:
> Fix: use wallet balance from onboard

- src/components/balances/AssetsTable/NoAssets.tsx
- src/components/common/BuyCryproButton/index.tsx
- src/components/dashboard/Overview/Overview.tsx
- src/config/constants.ts
- src/services/analytics/events/overview.ts
Resolves #3021
Creates a BuyCryptoButton component that finds the Ramp app by a tag and tracks the button clicks.
Also fixes the link: from `/apps` to `/apps/open`.
Event:
Dashboard:
Asset list:
> Analytics: track Buy Crypto button

- cypress/e2e/regression/tx_history_2.cy.js
The regression run on dev is failing because of typeUntrustedToken is undefined
Resolves #
typeUntrustedToken is defined as const 
const typeUntrustedToken = data.type.untrustedReceivedToken
run the regression suite and make sure that the test " 
Verify that sender address of untrusted token will not be copied until agreed in warning popup" is passed
> Add untrustedtoken const to the history_2 test in regression

- src/services/walletconnect/WalletConnectWallet.ts
The wrong error was thrown on user-initiated session rejection.
> Fix: [WalletConnect] - user reject session reason

- src/components/common/CopyTooltip/index.tsx
- src/components/safe-apps/SafeAppActionButtons/index.tsx
The Share button now has a hover effect like the other two buttons and is perfectly aligned to the center.
> Fix: [Safe Apps] align the share button

- package.json
- src/components/safe-apps/AppFrame/useAppCommunicator.ts
- src/components/safe-apps/PermissionsPrompt.tsx
- src/hooks/safe-apps/permissions/useSafePermissions.ts
- yarn.lock
The new safe-apps-sdk exports ESM modules which allows tree-shaking. It reduces the 500-kb Viem dependency significantly.
> Refactor: update safe-apps-sdk to v9 with ESM support

- next.config.mjs
Resolves #3050
Simply adding the Zodiac module to `optimizePackageImports` drastically reduced its size.
It doesn't affect the bundle analyzer report because it's in its own code chunk. But the difference is visible in the `yarn analyze` report.
> Chore: optimize the Zodiac dependency

- src/components/batch/BatchSidebar/BatchReorder.tsx
- src/components/batch/BatchSidebar/BatchTxList.tsx
- src/components/batch/BatchSidebar/index.tsx
- src/components/common/PageLayout/index.tsx
- src/components/safe-apps/SafeAppList/index.tsx
We had two places where `framer-motion` was used:
* Batch sidebar (for reordering)
* Safe Apps list (animation was added in #2699)
I've made the Batch sidebar lazy-loaded, and removed the animation completely from Safe Apps as it was very slow and not particularly better for UX.
> Refactor: lazy-load BatchSidebar + remove animations in Safe Apps list

- src/features/walletconnect/constants.ts
From the Optimism team:
> we recently implemented a code change to block smart contract wallets from using the bridge on [app.optimism.io](http://app.optimism.io/). Can you remove the block on your end for [app.optimism.io](http://app.optimism.io/) that prevents safe wallets from connecting? this will allow safe wallets to be used for the non-bridge features in our app.
I've removed the blocked host accordingly.
> Fix: [WalletConnect] rm app.optimism.io from blocked bridges

- package.json
- yarn.lock
Safe web is using an old version of safe-deployments safe-sdk has already been updated to version 1.28.0
Ref: https://github.com/safe-global/safe-infrastructure/issues/124#issuecomment-1877217611
> up safe-deployments version

- .github/workflows/cla.yml
- src/components/transactions/TxInfo/index.tsx
Resolves #3007
1. Open a transaction where the Token Symbol value is null. Example: https://app.safe.global/transactions/tx?safe=eth:0x220866b1a2219f40e72f5c628b65d54268ca3a9d&id=transfer_0x220866B1A2219f40e72f5c628B65D54268cA3A9D_ed95a5741db35c4a8478b9cad5c196784687106180afb92ab7f0e3157c45f4fd0344
2. Observe that "Unknown NFT" is shown where the token symbol would usually be.
Before: 
After:
> fix: show "Unknown NFT" on transactions when token symbol value is null

- src/components/welcome/WelcomeLogin/WalletLogin.tsx
Resolves #3073
Always show just the address w/o an address book/ENS name.
> Fix: [Welcome page] don't show name in Continue with

- .eslintrc.json
- .github/workflows/cla.yml
- package.json
- src/components/balances/CurrencySelect/__tests__/useCurrencies.test.ts
- src/components/balances/CurrencySelect/useCurrencies.ts
- src/components/tx/SignOrExecuteForm/__tests__/ExecuteForm.test.tsx
- yarn.lock
On the assets page if the user was to change the currency to SATS, LINK or BITS the app would crash. It turns out that we rely on Intl.NumberFormat for currency, but it only works with ISO 4217 - which requires the currency length to be exactly 3 characters. With anything else the call will throw. For now we decided to ignore any non ISO 4217 currencies.
Resolves #3045
@katspaugh and I agreed to remove Currencies that are not 3 characters long (as expected by ISO 4217). The currencies feature is not used much and if it is used it is mainly USD.
The list of currencies will no longer show LINK, BITS or SATS - so running into the crash is no longer possible
> fix: avoid crashing when selecting a 4-letter currency

- package.json
- yarn.lock
Resolves https://www.notion.so/safe-global/Can-not-execute-using-hardwallets-04a665fe2ca74e7c8e03ed8154449067
Tx execution with Ledger wasn't working because of an alias for the `@ethereumjs/common` package.
> Fix: restore Ledger ethereumjs dependency

- src/components/safe-apps/SafeAppsHeader/index.tsx
- src/components/safe-apps/SafeAppsHeader/styles.module.css
Resolves #3075 
This pull request updates the Safe Apps header by dynamically adding the connected network name into the title. The new title format is "Explore the Safe {networkName} ecosystem". Additionally, the subtitle tag length has been adjusted to ensure it fits in a single line.
> feat: Update Safe Apps header

- src/utils/__tests__/validation.test.ts
- src/utils/validation.ts
When adding a custom safe app, if a localhost URL includes subdomains, it will fail the validation. For example `http://localhost:3001/` will be allowed, but `http://foobar.localhost:3000/` will fail.
Resolves #1108 
- allows localhost domains which include subdomains when adding a custom safe app.
- both `http://localhost:3000` and `http://foobar.localhost:3000` will be allowed.
- Open the `Add a custom safe app` modal.
- Enter a localhost URL with subdomains. The example from the ticket is http://bafybeiasatviqudql65qxx66ois3dr7vxmhkk7zawn2vhdeax6q6pn4lsa.ipfs.localhost:8080/  
- To be able to add the url you will need to run the IPFS desktop app: https://docs.ipfs.tech/install/ipfs-desktop/ 
Although this fix is only to do with the form validation so it isn't necessary.
- There should …
> fix: allow localhost URLs with subdomains when adding custom safe apps

- src/services/analytics/events/createLoadSafe.ts
- src/services/analytics/events/overview.ts
- src/services/analytics/events/transactions.ts
- src/services/analytics/events/wallet.ts
- src/services/analytics/gtm.ts
- src/services/analytics/types.ts
* I've formalized the key event types in an enum
* Renamed tx events to past tense to match the existing events
* Added SAFE_CREATED, SAFE_OPENED and WALLET_CONNECTED. They were previously tracked via GTM by eventAction:
When this change is released, we'll need to remove that config on GTM.
* Go to the /welcome page
* Open the console
* Open one of the Safes in the sidebar
* Observe a `[GTM]` event in the console with `eventName: 'safe_opened'`
The same for wallet_connected, safe_created, tx_created, tx_confirmed and tx_executed.
> Analytics: key event types

- src/components/common/Popup/index.tsx
Resolves #3081
Adds `overflow-y: auto` property to the MUI `Popover` element
1. Try to connect to Snapshot.org on Sepolia with a smaller viewport height
2. The full WC screen is not visible
3. Try to scroll down should work
> fix: [WalletConnect] scroll on smaller screens

- cypress/e2e/pages/create_tx.pages.js
- cypress/e2e/pages/load_safe.pages.js
- cypress/e2e/pages/main.page.js
- cypress/e2e/pages/navigation.page.js
- cypress/e2e/pages/spending_limits.pages.js
- cypress/e2e/regression/spending_limits.cy.js
- cypress/e2e/smoke/spending_limits.cy.js
- cypress/support/constants.js
- src/components/common/TokenAmountInput/index.tsx
- src/components/settings/SpendingLimits/SpendingLimitsTable.tsx
- src/components/settings/SpendingLimits/index.tsx
- src/components/sidebar/NewTxButton/index.tsx
- src/components/tx-flow/common/TxButton.tsx
- src/components/tx-flow/common/TxNonce/index.tsx
- src/components/tx-flow/flows/NewSpendingLimit/CreateSpendingLimit.tsx
- src/components/tx-flow/flows/NewSpendingLimit/ReviewSpendingLimit.tsx
- src/components/tx-flow/flows/TokenTransfer/SendAmountBlock.tsx
- src/components/tx-flow/flows/TokenTransfer/SpendingLimitRow/index.tsx
Resolves #3093 
As part of our continuous automation test coverage, we are adding Spending limits tests to our smoke and regression tests:
- Added data-testid for tests
- Added tests
**Tests added**
- Verify when spending limit is selected the nonce field is removed
- Verify spending limit option shows available amount
- Verify Spending limit option is available when selecting the corresponding token
- Verify values and trash icons are displayed in Beneficiary table
- Verify that the Review step shows beneficiary, amount allowed, reset time
- Verify A valid ENS name is resolved successfully
- Verify writing a valid address shows no errors
- Verify Fill by QR code with a valid address
- Verify Amount input cannot be 0
- Verify Amount input cannot be a negative number
- Verify Amount input …
> Tests: add tests for spending limits

- src/hooks/useSpendingLimitGas.ts
Resolves #3086
Estimates the `gasLimit` for spending limit transactions via the `web3ReadOnly` provider instead of through the connected wallet provider which could be on a different chain and thus make the estimation call fail.
1. Create a spending limit transaction
2. Switch wallet to a different network
3. Observe the gasLimit is still estimated
4. Switch wallet to the correct network
5. Observe the gasLimit is still estimated
6. Make sure the transaction executes
> fix: [Spending Limit] estimate gas via readonly provider

- src/components/welcome/WelcomeLogin/WalletLogin.tsx
Copy address on WalletLogin button.
sets `copyAddress` to false.
Hover over the address on the button and observe that it does not copy anymore.
> fix: do not copy address on wallet button

- cypress/e2e/pages/spending_limits.pages.js
- cypress/e2e/regression/spending_limits.cy.js
- cypress/e2e/regression/spending_limits_nonowner.cy.js
- cypress/support/constants.js
- src/components/common/TokenAmountInput/index.tsx
- src/components/settings/SpendingLimits/NoSpendingLimits.tsx
- src/components/tx-flow/flows/NewSpendingLimit/ReviewSpendingLimit.tsx
Resolves #3093 
As part of our continuous automation test coverage, we are adding more Spending limits tests to:
**Added data-testids**
**Tests added:**
- Verify "Max" button value set to be no more than the allowed amount
- Verify selecting a native token from the dropdown in new tx
- Verify that when replacing spending limit for the same owner, previous values are displayed in red
- Verify that where there are no spending limits setup, information images are displayed
- Verify "New spending limit" button only available for owners
> Tests: add more tests for spending limits

- package.json
- yarn.lock
The latest update if @web3-onboard/walletconnect fixes the dynamic import of the walletconnect package which decreases the main bundle size significantly.
> Chore: update @web3-onboard/walletconnect

- src/components/tx-flow/flows/ExecuteBatch/ReviewBatch.tsx
- src/components/tx-flow/flows/RecoverAccount/RecoverAccountFlowReview.tsx
- src/components/tx-flow/flows/SignMessage/SignMessage.tsx
- src/components/tx-flow/flows/TokenTransfer/ReviewSpendingLimitTx.tsx
- src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
- src/components/tx/SignOrExecuteForm/SignForm.tsx
- src/components/tx/SignOrExecuteForm/WalletRejectionError.tsx
- src/features/recovery/hooks/useRecoveryTxNotification.ts
- src/hooks/messages/useSafeMessageNotifications.ts
- src/hooks/useTxNotifications.ts
- src/services/tx/tx-sender/dispatch.ts
Resolves #2701
When a user rejects a transaction through their connected wallet:
- do not log it as an error to sentry.
- do not send the user an error notification.
- Show `The transaction was rejected by the user.` in the tx execution box instead of a generic error message.
- Create a new transaction.
- When you are prompted to accept the transaction in Metamask, click reject.
- There should not be an error logged to sentry.
- There should be no error notification.
- The Execution box should say `The transaction was rejected by the user.`
- This will effect anywhere the user is prompted to accept or reject a transaction, including:
- signing a tx
- executing a tx
- signing a message
- batch txs
- tx with spending limits
- relayed txs
- bulk txs
- account recovery
Before: 
After:
> Fix: don't treat user rejections as errors

- src/components/tx-flow/flows/NewSpendingLimit/ReviewSpendingLimit.tsx
Resolves #2397
`existingSpendingLimit` was set inside a `useEffect` which caused an additional call to `createNewSpendingLimitTx` with an undefined value for `existingSpendingLimit`. This results in a fallback and displays a wrong transaction to the user inside the decoded data field. Depending on which useEffect finishes first this wrong result can stay visible.
This PR moves `existingSpendingLimit` into a `useMemo` to prevent the additional call.
1. Go to Settings > Spending Limits
1. Create a new one-time spending limit
1. Execute a spending limit transaction with that
1. Go to Settings > Spending Limits
1. Reset the spending limit to another one-time spending limit
1. Observe the UI not showing a wrong transaction in the decoded tx view
Before: This is the wrong transaction for …
> fix: [Spending Limit] wrong decoded data shown

- src/components/tx-flow/flows/SignMessage/SignMessage.tsx
- src/components/tx-flow/flows/SignMessageOnChain/ReviewSignMessageOnChain.tsx
- src/components/tx/ApprovalEditor/ApprovalItem.tsx
- src/components/tx/ApprovalEditor/hooks/useApprovalInfos.test.ts
- src/components/tx/ApprovalEditor/hooks/useApprovalInfos.ts
- src/components/tx/ApprovalEditor/index.tsx
- src/services/security/modules/ApprovalModule/index.ts
- src/utils/tokens.ts
Permit2 signature are not highlighted in our UI.
Shows the readonly approval editor for `PermitSingle` and `PermitBatch` Permit2 messages in SignOnchain and Offchain modals
- Request a signature for a PermitSingle or PermitBatch message (I extended the [example drainer app](https://github.com/5afe/eip-1271-dapp/tree/drain-wallet-example-dapp))
- Observe the new Approval Editor
> feat: show approval editor for permit2 messages

- src/hooks/useSpendingLimitGas.ts
https://www.notion.so/safe-global/b2bf1616be274eba8e02dedcfd272d1e?v=a922ede2ebd14ba3b629d2e36d43e3f6&p=4107e875bdc6454587fd61257e87fce1&pm=s
Does not use readOnly provider for gas estimation of spending limit tx.
- Setup a Spending limit and try to use it in a send funds tx
> Fix: spending limit estimation in ethers v6

- src/hooks/wallets/__tests__/useOnboard.test.ts
- src/hooks/wallets/useOnboard.ts
- src/hooks/wallets/wallets.ts
- src/services/onboard.ts
Resolves #3116
Removes the `recommendedInjectedWallets` option in the onboard config. Not sure why it was there in the first place. It seems to work the same sans the annoying warning.
The docs say:
>  if your app only supports injected wallets and when no injected wallets detected, recommend the user to install some
This is clearly not our case.
I've also removed auto-connection ot WalletConnect on mobile because it was briefly flashing the same warning.
> Fix: remove recommended injected wallet in web3-onboard

- src/components/new-safe/create/steps/ReviewStep/index.tsx
- src/components/tx/GasParams/index.tsx
- src/hooks/__tests__/useGasPrice.test.ts
- src/hooks/useGasPrice.ts
The correct formula is `(baseFee + maxPrioFee) * gasLimit` but with the switch to BigInt we did `baseFee + (maxPrioFee * gasLimit)` instead which resulted in the total fee being too low
1. Create a safe on sepolia
2. Observe the total fee not showing something like < 0,000001 ETH
> fix: Show more accurate total fee during safe creation

- src/components/tx/security/redefine/RedefineBalanceChange.tsx
Resolves #3120 
- Add a new owner to a Safe
- Observe that it shows the empty balance change correctly.
> fix: show empty balance change response correctly

- src/components/common/WalletBalance/index.test.tsx
- src/components/common/WalletBalance/index.tsx
Resolves https://www.notion.so/safe-global/Wallet-balance-never-resolves-when-trying-to-submit-bulk-transactions-with-walletconnect-6110e4bcd28444b083315bd21a10100d?d=71a60b3cbfd64773ab148328894330cf
Checks that the balance is undefined instead of coalescing.
Connect a wallet with 0 balance and look at the wallet balance in the send transaction screen.
> fix: show zero wallet balance

- src/features/recovery/services/recovery-sender.ts
- src/services/tx/tx-sender/__tests__/ts-sender.test.ts
- src/services/tx/tx-sender/sdk.ts
- src/utils/providers/UncheckedJsonRpcSigner.ts
If another safe is owner of a safe and we use walletconnect to sign transaction the UI was not updating. It turns out we need to port the  UncheckedJsonRpcSigner from ethers v5.
The UncheckedJsonRpcSigner fakes a transaction receipt without actually having one, and this is needed for transactions that don’t actually end on-chain.
Signing with a safe should close the transaction popup in the child's safe.
Resolves #
Test cases:
1. Create a transaction in C and sign in P
2. Create a transaction in C and immediately execute in P
In both cases the UI flows close and the transaction in C only appears in the queue after the transaction in P has been executed. 
3. Create and immediately execute transaction in C and sign in P
4. Create and immediately execute transaction in C and immediately …
> fix: UI not updating if signing from walletconnect

- src/services/onboard.ts
Switching to some chains threw an error that onboard does not know the chainId.
Resolves https://www.notion.so/safe-global/b2bf1616be274eba8e02dedcfd272d1e?v=a922ede2ebd14ba3b629d2e36d43e3f6&p=ac04ce127afd4987923caa3fb3b483bd&pm=s
When initializing onboard with all chainIds, we do not pad the chainId to bytes.
- Connect a wallet to Sepolia
- Open a Safe on görli
- Try to sign a tx where a chain switch is required first
> Fix: onboard initialization with ethers v6

- src/services/safe-messages/__tests__/safeMsgSender.test.ts
- src/utils/web3.ts
resolves: https://www.notion.so/safe-global/Can-not-sign-message-work-on-prod-70a71bf06be54c3fbf2a0e05cf19d657
Resolves #
ethers v6 converts the chainId to a hex value: https://github.com/ethers-io/ethers.js/blob/50b74b8806ef2064f2764b09f89c7ac75fda3a3c/src.ts/hash/typed-data.ts#L75
Our SDK expects a number, that's why we convert the hex value from ethers v6 to number.
> fix: message signing

- src/hooks/wallets/mpc/useRehydrateSocialWallet.ts
Resolves #3109 
- Open a unsupported Social login chain and observe that it does not try to rehydrate the connection
> fix: only rehydrate if social login is enabled

- src/components/sidebar/Sidebar/styles.module.css
- src/components/sidebar/SidebarList/index.tsx
- src/components/sidebar/SidebarList/styles.module.css
Resolves #3067
**Double border on desktop sidebar**
- Removed the border _only_ on desktop (mobile didn't have the double border issue).
**Transaction badge color**
- Used the _warning_ value for the badge color prop (I assume this is the color you're after, let me know if it needs changing!).
**Transaction badge spacing**
- Updated margin-left to 24px.
- Create some txs to render the pending txs badge.
| Before | After |
| ------ | ----- |
| ![Before](https://github.com/safe-global/safe-wallet-web/assets/12480362/6388dd12-a874-49cb-bebb-f57de175ee04) | ![After](https://github.com/safe-global/safe-wallet-web/assets/12480362/e47d55b6-74e0-47ca-9683-912057de923f) |
> fix: left sidebar ui

- src/hooks/__tests__/useWalletCanPay.test.ts
- src/hooks/useWalletCanPay.ts
Resolves https://www.notion.so/safe-global/Wallet-balance-never-resolves-when-trying-to-submit-bulk-transactions-with-walletconnect-6110e4bcd28444b083315bd21a10100d?d=71a60b3cbfd64773ab148328894330cf
Checks that the wallet balance is undefined.
Connect a wallet with 0 balance and try to execute a tx.
The "not enough funds" warning should appear.
> fix: useWalletCanPay with 0 balance

- README.md
- src/services/analytics/spindl.ts
Reported in #3153 – Spindl is loaded even if its env variable isn't set.
If the env var isn't provided, don't load Spindl.
> Fix: don't load Spindl if no SDK key

- cypress/e2e/pages/create_tx.pages.js
- cypress/e2e/pages/spending_limits.pages.js
- cypress/e2e/smoke/create_tx.cy.js
- cypress/e2e/smoke/spending_limits.cy.js
- src/components/common/NumberField/index.test.ts
- src/components/common/NumberField/index.tsx
We were not automatically replacing comma (,) with a dot (.) when entering numbers in the send tokens interface and this was driving me nuts as I always had to remove the comma and make sure to enter a dot. 
This improves the number input. On German keyboard instead of a dot on the numpad one has a comma (,). With this change a comma will be automatically replaced with a dot.
Resolves #
Try to enter a number with comma. You can start with a comma `,` and you should get `0.` instead.
Commas anywhere in the number will be automatically replaced with dots.
> feat: better number input

- src/components/batch/BatchSidebar/BatchTxItem.tsx
- src/components/batch/BatchSidebar/styles.module.css
- src/components/transactions/TxListItem/ExpandableTransactionItem.tsx
- src/components/transactions/TxSummary/styles.module.css
- src/components/transactions/TxType/index.tsx
- src/components/transactions/TxType/styles.module.css
Resolves #3136
Fixed overlap/overflow for TxType component (used in three different parent components):
- Tx history page
- Home pending txs module
- Batched transactions sidebar
I wasn't sure of the correct styling preference (inline, css module, etc), so I tried to follow the same convention in each component. If you prefer to make this fix another way, feel free to disregard this PR :)
Also, a lot of Cypress tests were failing for me, but they didn't seem to be related to my changes.
| Before | After |
|--------|-------|
| ![Before Feature X](https://github.com/safe-global/safe-wallet-web/assets/12480362/b73d74bb-b245-46db-ab28-7ad5f20f3961) | ![After Feature X](https://github.com/safe-global/safe-wallet-web/assets/12480362/7b4ecda2-3d28-4953-ab38-af4764c51570) |
| ![Before Feature …
> fix: TxType overlap/overflow

- docs/release-procedure.md
When preparing the last release I was not sure how to notify QA about it. And I obviously did it wrong.
Resolves #
Ads the necessary info to the docs about the current process
> docs: improve the “preparing a release” steps

- cypress/e2e/pages/create_tx.pages.js
- cypress/e2e/pages/spending_limits.pages.js
- cypress/e2e/regression/spending_limits.cy.js
- cypress/e2e/safe-apps/drain_account.spec.cy.js
- cypress/e2e/smoke/create_tx.cy.js
- cypress/support/constants.js
Resolves #3172 
As part of our continuous automation tests coverage, the following test were added:
1) As part of this [PR](https://github.com/safe-global/safe-wallet-web/pull/3127/files#diff-6add3851be7cde7f9478820f8e4f8b54f460537db9e093258b173dfe41c0d77c ), part of a test was deleted, see comments in the PR. This task fixes it. 
2) A new test covering the fix for the [bug](https://github.com/safe-global/safe-wallet-web/issues/2397).
Run Cypress tests and observe the outcome.
> Tests: add extra tests to address bug fix and restore a deleted test

- src/features/recovery/components/RecoveryDetails/index.tsx
Resolves https://www.notion.so/safe-global/Recovery-tx-1970-as-expires-date-for-never-expires-3e0fab8db7f94ef9bdfebcdcd9d11151
Checks if `expiresAt` exists before rendering it
1. Open a Safe with recovery where recovery attempts have no expiry
2. Propose a recovery
3. Go to the queue
4. Expand details
5. Observe expiry is not shown
> fix: Only show recovery expiry if its not null

- src/components/common/TokenAmountInput/index.tsx
- src/components/tx-flow/flows/SuccessScreen/StatusMessage.tsx
- src/utils/ethers-utils.ts
- Hides the MAX Button if the value is 0
- Shows a human-readable timeout error during tx execution
- `Number(0n)` resolves to 0 which gets rendered when trying to conditionally renders something with `&&`
1. Open a safe with no assets
2. Create a token transfer
3. Observe no MAX Button is visible
4. Create a transaction and execute with low gas
5. Wait until it times out
6. Observe a readable timeout error
> [Release 1.28.0] Fix max amount button and timeout error

- src/components/swap/CowWidget.tsx
The current version of CoW Swap in prod doesn't work with the PoC in #feat-cow-swap branch. 
This PR changes the environment to `dev` which means, the iframe use https://dev.swap.cow.fi/ instead of https://swap.cow.fi
We just applied a fix in DEV to disable bundling of transactions if CoW Swap doesn't manage to get an instance of the SWAP, this will solve the issue.
We should bring back bundling of transactions, so this will be a temporal fix.
> Point to development

- package.json
- yarn.lock
Update WalletConnect packages (see their [release notes](https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.11.1)), plus add a yarn command to do it easier next time.
> Chore: update WalletConnect packages

- cypress/e2e/pages/assets.pages.js
- cypress/e2e/pages/navigation.page.js
- cypress/e2e/pages/sidebar.pages.js
- cypress/e2e/regression/sidebar_2.cy.js
- cypress/e2e/regression/sidebar_nonowner.cy.js
- cypress/support/constants.js
- cypress/support/localstorage_data.js
- src/components/balances/CurrencySelect/index.tsx
- src/components/sidebar/PendingActions/index.tsx
Resolves #3187 
- Added new tests for sidebar
- Added data-testids to support tests
**New tests:**
- Verify Fiat currency changes when edited in the assets tab
- Verify "wallet" tag counter if the safe has tx ready for execution
- Verify "Wallet" tag counter only shows for owners
- Verify New Transaction button enabled for users with Spending limits allowed
- Verify tag counting queue tx show for owners and non-owners
> Tests: add sidebar tests -p3

- src/hooks/wallets/web3.ts
The ENS resolution stopped working after #3208.
This PR partially reverts the changes and instantiates the `JsonRpcProvider` without a network object.
1. Open a safe on mainnet or sepolia
3. Type an ENS as the recipient
4. Observe the name resolves
> fix: ENS resolution

- src/components/tx-flow/flows/AddOwner/ReviewOwner.tsx
- src/features/counterfactual/hooks/useDeployGasLimit.ts
- src/services/tx/tx-sender/create.ts
Resolves #3191
- Implements `addOwner` and `swapOwner` functions for undeployed safes
1. Create a counterfactual 1/1 safe
2. Navigate to the settings page
3. Add or swap an owner
4. Observe that there are no errors in the transaction flow
5. Observe that the transaction executes, deploys the safe and adds/swaps the owner
> [Counterfactual] Enable addOwner and swapOwner flow for counterfactual safes

- src/components/dashboard/FirstSteps/index.tsx
- src/components/dashboard/FirstSteps/styles.module.css
- src/components/dashboard/index.tsx
- src/features/counterfactual/ActivateAccount.tsx
- src/store/txHistorySlice.ts
- src/utils/transaction-guards.ts
Part of #3207 
- Creates a new widget for the dashboard to show first steps
- Creates `StatusProgress` component that can be reused for other widgets
1. Create a new counterfactual safe
2. Observe first steps card visible on the dashboard
3. Complete first steps or deploy safe immediately
4. Observe cards are not visible anymore
> [Counterfactual] Add first steps widget

- src/components/new-safe/create/logic/index.ts
- src/features/counterfactual/ActivateAccount.tsx
Part of #3156 
- Adds a new optional parameter `safeVersion` to `createNewSafe` and `relaySafeCreation`
- Passes the `safeVersion` to those functions for undeployed safes
1. Create a new counterfactual safe
2. Deploy the safe either via first transaction or separate deployment
3. Observe the safe address is deployed
4. Create a safe normally
5. Observe the predicted safe address is the one that is also deployed
> fix: [Counterfactual] Deploy safe with specific version

- src/services/analytics/__tests__/tx-tracking.test.ts
- src/services/analytics/events/transactions.ts
- src/services/analytics/tx-tracking.ts
Safe Apps tx events will now have the Safe App URL as their label.
1. Make a transaction via any Safe App
2. See in the console that the GTM events tx_created, tx_confirmed and tx_executed have the Safe App's URL as the `eventLabel` property.
> [Analytics] origin as label for safe app txs

- cypress/e2e/pages/address_book.page.js
- cypress/e2e/regression/address_book.cy.js
- cypress/e2e/regression/address_book_2.cy.js
- cypress/e2e/safe-apps/tx-builder.spec.cy.js
- cypress/e2e/smoke/address_book.cy.js
- cypress/support/localstorage_data.js
- src/components/address-book/AddressBookTable/index.tsx
- src/components/address-book/ExportDialog/index.tsx
Resolves #3229 
- Added tests to cover remaining tests in Address Book
- 
Tests added:
- Verify an entry can be added by ENS name
- Verify empty name is not allowed when editing
- Verify clicking on Send button autofills the recipient filed with correct value
- Verify Name and Address columns sorting works
- Verify that edit owners name changes the name in the settings
- Verify that editing an entry from the transaction details updates the name in address book
- Verify copy to clipboard/Etherscan work as expected
> Tests: add more tests for address book

- src/features/counterfactual/utils.ts
Part of #3156
- Uses the existing `tryOffChainSigning` method when signing the bundled transaction
1. Create a counterfactual safe with a hardware wallet
2. Deploy the safe with the first transaction
3. Observe no error when signing
> fix: [Counterfactual] try signing methods when signing

- src/components/transactions/TxSummary/index.tsx
Resolves #3249
Nonce is a number, so 0 wasn't passing the check.
After the fix:
> Fix: don't display 0 nonce for grouped txs

- .github/workflows/cla.yml
- src/components/settings/PushNotifications/styles.module.css
Changed the border color of the info alert component on the _Notifications_ tabs in the _Settings_.
> Fix: change macOsInfo border color

- src/components/welcome/MyAccounts/useAllSafes.ts
Before, undeployed safes were being shown under the watchlist. Show them under owned safes instead.
- create a safe using the option to pay later.
- after safe creation, the safe should be shown in the owned safes section of the sidebar and the /accounts page
> Show undeployed safes under owned safes

- src/components/dashboard/FirstSteps/index.tsx
- src/components/new-safe/create/steps/ReviewStep/styles.module.css
- src/features/counterfactual/ActivateAccountFlow.tsx
Resolves #3156 
The `SUCCESS` event was emitted twice when deploying a safe. Once from the original promise coming from the protocol-kit and then also from the watcher that we start. I removed the `onSuccess` callback in the original promise since the watcher is always running.
This PR also fixes minor UI issues mentioned on the [QA Board](https://www.notion.so/safe-global/c56befc17429427fa47a67fbe5ebc4cb?v=c6cfec4c5b32445bab938f15a76d33e4)
1. Create a counterfactual safe
2. Go to dashboard and activate it now without an additional tx
3. Observe there is only one success screen at the end
> fix: [Counterfactual] Only show success screen once

- src/features/walletconnect/constants.ts
Resolves #3078
I've moved the Linea bridge from the red unsupported bridges to the yellow warned bridges list.
> Fix: move Linea bridge to warned bridges

- src/components/common/ConnectWallet/ConnectWalletButton.tsx
- src/components/welcome/MyAccounts/PaginatedSafeList.tsx
- src/components/welcome/MyAccounts/index.tsx
- src/components/welcome/MyAccounts/styles.module.css
https://www.notion.so/My-accounts-Empty-state-b92fff61cd454471bb9af8cc18c589bd?pvs=4
Adds a state to the owned safes list for when a wallet is not connected. Includes a button for connecting a wallet
> Add connect button to owned safe list when no wallet is connected

- src/components/common/AddressBookInput/index.tsx
Resolves #3252 
Check if the current address input is a valid address. If it is then do not show any suggestions from the address book.
- Create a transaction that transfers any asset
- Enter destination address (something not in the address book)
- Click on the address input
- The autocomplete should not show any suggestions.
> fix: don't show address suggestions after a valid address has been entered

- src/components/dashboard/FeaturedApps/FeaturedApps.tsx
- src/components/dashboard/index.tsx
- src/components/dashboard/styles.module.css
- src/features/recovery/components/RecoveryWidget/index.tsx
- src/features/recovery/components/RecoveryWidget/styles.module.css
Updating the overview widget layout as part of #3207 caused an empty widget slot that was closed from the top and bottom so it looks out of balance.
- Move the recovery widget to the top and spread the walletconnect and tx builder over the whole width
1. Open dashboard
2. See gap at the top
> fix: Adjust dashboard widget positions

- src/components/common/BuyCryptoButton/index.tsx
- src/components/dashboard/Overview/Overview.tsx
- src/features/counterfactual/FirstTxFlow.tsx
- src/features/counterfactual/hooks/usePendingSafeStatuses.ts
- src/features/counterfactual/store/undeployedSafesSlice.ts
- src/features/counterfactual/utils.ts
- src/hooks/coreSDK/__tests__/safeCoreSDK.test.ts
- src/hooks/coreSDK/safeCoreSDK.ts
When switching from an undeployed safe we run a `useEffect` to check `checkDeploymentStatus` which contains the updated `provider` but can still contain the previous safeInfo. In that case it can happen that the undeployed state is wrongfully removed.
Make sure that the `provider` and the `safeInfo` have the same chainId before checking if a contract is deployed on the safeAddress
1. Create a counterfactual safe with address X on network A
2. Deploy that safe
3. Create a counterfactual safe on network B and make sure that the safe ends up with the same address X
4. Switch back to network A
5. Switch back to the network B
6. Observe the counterfactual safe on network B is still accessible
---
1. Create a counterfactual safe on Celo
2. Press on "Create transaction" on the dashboard
3. …
> fix: [RC] issues

- cypress/e2e/regression/create_safe_simple.cy.js
- cypress/e2e/smoke/create_safe_simple.cy.js
- src/components/common/ConnectWallet/ConnectWalletButton.tsx
- src/components/common/ConnectWallet/ConnectionCenter.tsx
- src/components/welcome/MyAccounts/PaginatedSafeList.tsx
- src/components/welcome/MyAccounts/index.tsx
- src/components/welcome/MyAccounts/styles.module.css
- src/components/welcome/MyAccounts/useAllSafes.ts
- src/components/welcome/WelcomeLogin/index.tsx
Redirect from the welcome page depending on wether the user has any safes:
- If the user has either owned or added safes, redirect to the accounts page `/welcome/accounts`
- If the user has no safes to show, redirect them to create a new safe page `/new-safe/create`
On the `/welcome` page:
- Connect an account with owned safes, but with no added safes in the browser (private window)
- should redirect to `/welcome/accounts`
- Connect an account with no owned safes (fresh MM account), but with added safes in the browser
- should redirect to `/welcome/accounts`
- Connect an account with no owned safes, and no added safes
- should redirect to `/new-safe/create`
> Redirect form /welcome page when wallet is connected

- package.json
- src/components/common/AddressBookInput/index.test.tsx
- src/components/common/EthHashInfo/index.test.tsx
- src/components/common/EthHashInfo/index.tsx
- src/components/settings/FallbackHandler/__tests__/index.test.tsx
- src/components/settings/PushNotifications/GlobalPushNotifications.tsx
- src/hooks/useAllAddressBooks.ts
- src/tests/builders/chains.ts
Showing a name for an address via the `EthHashInfo` component uses the `useAddressBook` hook. This works well when on a specific safe view because there is a unique chain to check. However, on non-safe routes like the global notifications this doesn't work and can result in showing the wrong name for an address in case it has the same address on multiple chains.
- Adds a new hook `useAllAddressBooks`
- Uses that hook instead of `useAddressBook` to find a name in `EthHashInfo`
1. Create 2 safes with identical addresses on 2 different chains e.g. with counterfactual
2. Deploy both safes
3. Make sure both safe addresses are in the address book with different names
4. Go to the global notifications page
5. Observe both addresses show up with their correct name
> fix: Check all address books to find name for an address

- cypress/e2e/pages/owners.pages.js
- src/components/dashboard/FirstSteps/index.tsx
- src/components/new-safe/create/steps/OwnerPolicyStep/index.tsx
- src/components/new-safe/create/steps/OwnerPolicyStep/useSafeSetupHints.ts
- src/features/counterfactual/CounterfactualHint.tsx
- src/store/settingsSlice.ts
- Adds a hint to the owner step during safe creation informing the user that pay later is only supported for single owner setups
- Changes the 1/1 warning to an info box to make it less scary
- Adds a toggle option to the QR code in the first steps widget
- Removes the wrong chain warning on the owner step because the user is redirected away if their wallet has a different network so they will never see that warning
1. Go through the safe creation flow
2. Observe in the owner step that the 1/1 warning is now blue
3. Observe there is no pay later hint
4. Add another owner
5. Observe there is a pay later hint
6. Create the safe counterfactually
7. Press Add funds on the dashboard
8. Observe a toggle option under the QR code
> fix: [RC] Add pay later hint to safe creation step

- src/components/welcome/MyAccounts/useAllSafes.ts
Resolves https://www.notion.so/safe-global/570f3459753047f49022d5b63ee1e57e?v=ed82ae2a7e28401086a736f6af1c31ae&p=bc70bcc7233d488e84e2d4dd96c9bcf9&pm=s
Newly created safes take around 5 minutes to show up in responses from the CGW. As a workaround, display newly created safes in the owned safes list by referencing the owners array in localstorage.
> fix: show newly depoyed safes under owned safes

- src/components/welcome/MyAccounts/AccountItem.tsx
- src/components/welcome/MyAccounts/CreateButton.tsx
- src/components/welcome/MyAccounts/index.tsx
- src/services/analytics/events/overview.ts
Add tracking events for:
- `Open Safe`
- labels: login_page | sidebar
- `Create new Safe`
- labels: login_page | sidebar
-  choose a safe from the safe list in both the login page and the sidebar.
-  click the button to create a new safe, both from the login page and the sidebar
-  Check that the events are fired in the console with the appropriate labels
> Add tracking events for adding and selecting safes

- cypress/e2e/pages/sidebar.pages.js
- cypress/e2e/regression/create_safe_google.cy.js
- cypress/e2e/regression/sidebar.cy.js
- cypress/e2e/regression/sidebar_2.cy.js
- src/components/welcome/MyAccounts/PaginatedSafeList.tsx
- Fix breaking sidebar tests
- Removed tests for depreciated functionality
> Tests: fix breaking tests

- src/components/common/EthHashInfo/SrcEthHashInfo/index.tsx
- src/components/common/EthHashInfo/SrcEthHashInfo/styles.module.css
- src/components/transactions/TxDetails/TxData/Transfer/index.tsx
- src/components/welcome/MyAccounts/styles.module.css
Resolves #3197
It truncates text with ellipsis on shrink, adding width 100% to TransferTxInfo container (Box) and hiding overflow on SrcEthHashInfo component (text Box itself).
Open http://localhost:3000/transactions/history?safe=oeth:0x773D7c58941295aF412092efF5Aa3d188525e81a , open accordion of any transaction and check if address shortens with "..." at the end on smaller viewports.
> fix: Add hide address overflow on transaction history

- package.json
- src/features/walletconnect/components/WcSessionMananger/index.tsx
- yarn.lock
Resolves #3284
This is an attempt to fix 2 WC bugs that are plaguing some of our users:
No matching key: session
No matching key: keychain
For the keychain error I haven't figured a way how to reproduce it, but it appears that WC has fix in their latest release. For the session error I could reproduce it when connecting to 1inch, but also very edge case and I doubt that users are encountering it that way. We have a lot of errors in sentry and I can't imagine that users trigger it like this.
For the session error you could try the PR and follow the same steps as in the gif. The problem is that the fix is flaky - sometimes it works, sometimes it doesn't, where without it, it always fails. 
For the keychain issue, no idea. We'll have to monitor sentry for that error.
> fix: wc "no matching key" errors

- .husky/pre-push
- README.md
- package.json
- yarn.lock
Often we push code only to find 10min later that we have a lint or test issue. With the changes here before a push we'll run the linter and tests(if desired).
> feat: add husky pre-push hook

- src/features/recovery/components/RecoveryEmail/RegisterEmail.tsx
- src/features/recovery/components/RecoveryEmail/index.tsx
Resolves #3320
- Adds a form to enter an email address and Cancel and Continue buttons
- On Continue, registers the email
- On Cancel, hides the form and displays the "Sign to view" button again
1. Open a safe with recovery enabled
2. Go to the settings page
3. Observe the "Sign to view" button is disabled if no wallet is connected or wallet is not an owner
4. Press "Sign to view" and sign the message
5. An email form should be visible
6. Press cancel
7. The "Sign to view" button should be visible again
8. Do Step 4 again
9. Enter a valid email and submit
10. The email address should be visible
Note: With the addition of #3321, Step 9 will open a new dialog to verify the email.
> feat: [Recovery] Add register email form

- src/hooks/__tests__/useGasLimit.test.ts
- src/hooks/useGasLimit.ts
- src/hooks/useIsValidExecution.ts
- src/services/tx/__tests__/encodeSignatures.test.ts
- src/services/tx/encodeSignatures.ts
- src/tests/mocks/contractManager.ts
- src/tests/test-utils.tsx
- src/tests/transactions.ts
Resolves #3332 
- Checks if a signature is needed before adding a pre-validated-sig.
- Open a 1/2 Safe where you control both owners
- Sign a transaction with the owner that has a higher address (higher hex number)
- Switch to the other owner with a lower address
- Try to execute the tx
- Observe that the gas estimation now matches
> fix: do not modify signatures for fully signed txs when estimating

- src/features/recovery/components/RecoveryEmail/VerifyEmail.tsx
- src/features/recovery/components/RecoveryEmail/index.tsx
- src/features/recovery/components/RecoveryEmail/useRecoveryEmail.ts
Resolves #3149
- Adds a new function `deleteEmailAddress`
- Shows a delete button with the email
- Shows a notification on successful deletion
1. Register an email address
2. Press "Sign to view"
3. Observe a delete button next to the email
4. Press the button and sign
5. Observe a success message
6. Observe that the form is visible again
> feat: [Recovery] Delete registered email

- jest.config.cjs
Improves our coverage accuracy by excluding some irrelevant folders.
- Excludes generated typechain files
- Excludes our test-utils and mocks
Run `yarn test --coverage`
Observe that there are no more generated files and testutils
> chore: exclude generated & test folders from coverage

- src/components/new-safe/create/steps/ReviewStep/index.tsx
Part of #3270
In some cases it can happen that `gtmSetSafeAddress` is called too late after safe creation so that certain key events like `safe_created` do not contain the `safeAddress`. To solve this we additionally call `gtmSetSafeAddress` when the counterfactual safe creation is submitted.
1. Create a counterfactual safe
2. Observe in the console that all events after pressing Create contain the safe address
> fix: [Analytics] Set safe address during safe creation

- src/components/welcome/WelcomeLogin/index.tsx
Resolves #3357 
Add a button to the welcome page for adding watchlist safes even when there is no wallet connected.
- make sure no wallet is connected
- go to `/welcome`
- see that the button is present and leads to adding a new account to the watchlist.
With social login:
> feat: allow adding safes from the welcome page

- src/components/common/NetworkSelector/index.tsx
- src/components/common/SocialSigner/__tests__/SocialSignerLogin.test.tsx
- src/components/common/SocialSigner/index.tsx
Resolves #3266
- Hides the `More network support coming soon` toolip
1. Connect with social signer on Gnosis chain
2. Open the Network selector
3. Observe other network items are still disabled
4. Observe there is no tooltip
> fix: [Seedless] Hide tooltip when connected with social signer

- cypress/e2e/pages/create_wallet.pages.js
- cypress/e2e/pages/sidebar.pages.js
- cypress/e2e/regression/create_safe_simple_2.cy.js
- Fix failing tests on dev due to changes by the [PR](https://github.com/safe-global/safe-wallet-web/pull/3285)
- Add wait to sidebar open action to enable complete render of 'Show more' button
> Tests: fix cypress tests on dev

- src/components/welcome/MyAccounts/styles.module.css
Since the .listItem had a padding, the <a> tag inside of it was only clickable if you manage to hit it directly. But ListItem actually looks like a clickable button, so you won’t expect that you have to be clicking directly in the center.
Since a picture is worth 1000 words, a gif is worth ????
Resolves #
> fix: not possible to click on a safe in listItem

- src/components/common/CooldownLink/index.tsx
- src/features/recovery/components/RecoveryEmail/RegisterEmail.tsx
- src/features/recovery/components/RecoveryEmail/VerifyEmail.tsx
- src/features/recovery/components/RecoveryEmail/index.tsx
- Rename "Resend" to "Resende code" and remove text underline
- Show an error in case registration fails
- Close the registration form if registration succeeds
- Enable the Sign to view button for spending limit users to get rid of the tooltip. This will be properly fixed in https://github.com/safe-global/safe-wallet-web/issues/3381
> fix: [Recovery] Stabilization

- src/hooks/__tests__/useGasPrice.test.ts
- src/hooks/useGasPrice.ts
The gas estimation on mainnet is sometimes wrong.
Takes `maxPriorityFeePerGas` and `baseFee` from etherscan instead of using ethers `maxPriorityFeePerGas`.
- Try to execute a transaction on mainnet.
- Compare the estimated `maxFeePerGas` and maxPriorityFeePerGas with etherscan's [gas tracker](https://etherscan.io/gastracker)
> fix: mainnet gas price calculation

- src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx
Resolves #3301
Only sets `native transfer` as the method name if the transaction has a non-zero value.
1. Interact with an unknown contract e.g. via tx builder without an ABI
2. Add a native transfer in there as well
3. Observe the decoded view correctly shows native transfer for the second tx and "Unknown contract interaction" for the first
> fix: Don't show native transfer for unknown contract interactions

- src/components/welcome/MyAccounts/PaginatedSafeList.tsx
Users have complained that it is difficult to find the safe they're looking for with the pagination on the safe lists.
Remove the show more button from the safes list. Show all safes in the list by default
> Fix: Remove show more button from safe lists

- src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
- src/hooks/useGasLimit.ts
- src/services/tx/tx-sender/dispatch.ts
Resolves https://github.com/safe-global/safe-wallet-web/issues/3141
Instead of using the safe wallet as "from" for the gas estimation, we use a random EOA address. 
Also, I don't think that we should show an error for when we determine that the connected walelt might not have enough funds. I changed it to info, maybe warning would be even more appropriate, opinions? 
You need a nested safe setup: parent/child. The parent should be owner of the child. Create a tx in the child (e.g. add owner etc) and try to sign in the parent safe. Without this fix the process will fail with an estimation error. With the fix, the transaction should go through.
> Fix: zksync nested safe gas estimation

- src/components/dashboard/FirstSteps/index.tsx
- src/components/welcome/MyAccounts/CreateButton.tsx
Resolves https://www.notion.so/safe-global/GTM-tracking-Create-safe-tracked-twice-af995523863541778b0dcb69726ad157
Resolves https://www.notion.so/safe-global/Create-tx-button-shouldn-t-be-available-for-non-owners-disconnected-users-0dd990edb6bd4cdf9e816423911af51e
The `CreateButton` is already wrapped in a `Track` so I removed the onClick handler
1. Go to the accounts page
2. Press the Create button
3. Observe only one event
4. Create a counterfactual safe
5. Go to the dashboard
6. Disconnect your wallet or switch to a non-owner
7. Observe the Add funds and Create transaction buttons are disabled
> fix: Track Create new Safe click once, disable onboarding buttons for non-owners

- src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.test.tsx
- src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx
Resolves [Notion issue](https://www.notion.so/safe-global/NativeToken-transfer-ETH-is-marked-as-Unknown-contract-interaction-1f5ed836073245cbb9962daf47485c41)
Does not require tx.data to be defined when checking for native transfers.
- Send a multisend with native transfers
- Observe that they are shown correctly
> fix: detect native transfers

- src/components/welcome/MyAccounts/useAllSafes.ts
For users with a lot of safes it is disorienting for the order of their accounts to change after selecting a different safe. Make the list order persistent.
Resolves #
- Remove sorting by current chain, so that the list order does not change after selecting a new safe.
- Now it is ordered primarily by chains you have added safes on, and secondarily by chainId.
> Fix: remove dynamic sorting for safe lists

- src/components/transactions/TxDetails/index.tsx
- src/components/transactions/TxDetails/styles.module.css
Resolves #3386
It adds the flex-wrap property to the button container. I have also moved the styles of the Box container from inline properties to the corresponding css file for better maintenance.
Open http://localhost:3000/transactions/queue?safe=oeth%3A0x773D7c58941295aF412092efF5Aa3d188525e81a , open up the transation modal and check Execute and Replace buttons.
> fix: Add wrap on queue tx button container

- .github/workflows/e2e-hp-ondemand.yml
- Reduce number of machines for execution in recovery tests
> Tests: reduce number of machines for recovery tests

- src/components/welcome/MyAccounts/useAllSafes.ts
Watchlist safes were not showing up when disconnected from wallet. 
Always show watchlist safes wether connected or not.
> fix: show watchlist when disconnected from wallet

- src/features/recovery/services/delay-modifier.ts
Resolves #3413 
- For some safe proxy contracts (e.g. on mainnet), the function `getGnosisProxyMasterCopy` returns `0` since the public masterCopy function is missing ([Example](https://etherscan.io/address/0x651bBd829a7cBD32F35dFC099cBde1E04789393c#code))
- Check `isAddress` for a given `moduleAddress` before running `_getZodiacContract`
1. Open a safe on mainnet that added another safe as the recoverer
2. Navigate to the settings page
3. Observe the Recovery setup is visible
> fix: Recovery not visible on settings page

- src/components/common/WalletInfo/index.tsx
- src/features/walletconnect/components/WcSessionList/WcNoSessions.tsx
note to testers: I can't see this error in production, it seems to only appear with the local dev release, so you'll have to test this locally
fix: Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
In some locations we had <Typography variant=“body1”> nested inside another <Typography> this renders 2 <p> tags inside of each-other and that is not valid. The other way around was having a <Box> that is nested inside of a Typograpühy which also seems to be not valid.
run the website with 'yarn dev' -> open the wallet box on top -> you shouldn't see:
> chore: <p> cannot appear as a descendant of <p>.

- package.json
- src/components/common/PageLayout/index.tsx
- src/components/tx/ErrorMessage/index.tsx
- src/components/tx/ErrorMessage/styles.module.css
- src/config/routes.ts
- src/features/recovery/components/RecoveryEmail/UnsubscribeEmail.tsx
- src/features/recovery/components/RecoveryEmail/useRecoveryEmail.ts
- src/hooks/useIsHeaderRoute.ts
- src/hooks/useIsSidebarRoute.ts
- src/pages/unsubscribe.tsx
- yarn.lock
Resolves #3387 
Adds a new page `/unsubscribe`
Note: The unsubscribe link from received emails doesn't work yet so we need to request the uuid and manually test this.
1. Open the `/unsubscribe` page
2. Observe the design
https://github.com/safe-global/safe-wallet-web/assets/5880855/be9683b7-bed7-4a75-be67-a120841e570a
> feat: [Recovery] Add unsubscribe page

- src/components/common/AddressInputReadOnly/index.tsx
- src/components/common/AddressInputReadOnly/styles.module.css
Resolves #3129 
- Adds ellipsis for long addresses
- Removes unused `endAdornment` in `AddressInputReadOnly`
- Adds the `address` as a title to the element
1. Add some addresses to your address book
3. Assign those addresses as owners
4. Observe the address is cut off at the end with `...` if there is not enough space
5. Hover the address
6. Observe a title showing the whole address
> fix: Address overflow in read-only inputs

- src/components/tx-flow/flows/TokenTransfer/SpendingLimitRow/index.tsx
fixes #3326
If you have a token that has a spending limit, select it, then switch to another token that doesn't have a spending limit set then the "Max" button would update the amount field to 0 instead of the max available.
The whole problem stems from the fact that we watch for the type of the transfer with react-hook-form, but if we just unmount the component that displays those limit controls the watch doesn't know that the type has to be reset back to default.
follow the steps in #3326
> fix: max button not applying correct value

- src/features/walletconnect/constants.ts
Resolves https://github.com/safe-global/safe-wallet-web/issues/3435
Moved scroll.io from BlockedBridges to the WarnedBridges.
1. open WalletConnect widget
2. open https://scroll.io/bridge
3. try to establish a connection from Safe{Wallet} to Scroll Bridge
> fix: move scroll.io from blocked bridges to the warned bridges

- cypress/e2e/pages/create_wallet.pages.js
- src/components/dashboard/CreationDialog/index.tsx
- src/services/analytics/events/counterfactual.ts
Follow up on #3203 
Less than 4% of users who created a counterfactual safe did a backup according to our analytics. Furthermore we received feedback that this option is confusing. As there is currently no strategy to restore those backups this option seems more confusing than it is useful. In case users with an existing backup reach out to us we can still handle those manually.
1. Create a new counterfactual safe
2. Observe no Backup option
> fix: Remove counterfactual backup option

- src/hooks/useTxHistory.ts
- src/utils/__tests__/tx-history-filter.test.ts
- src/utils/tx-history-filter.ts
Resolves #3334
Passes the trusted flag to the filtered history endpoints (although it only works for the incoming tx filter).
* Open https://filter_incoming--walletweb.review-wallet-web.5afe.dev/transactions/history?safe=eth:0x220866b1a2219f40e72f5c628b65d54268ca3a9d&type=Incoming
* Press "Hide unknown transactions"
* The tx list should be filtered
---
Note: this PR is based off of the Tx Deletion PR because it requires an updated Gateway SDK.
> Feat: spam filter for incoming txs

- src/components/settings/ContractVersion/index.tsx
Resolves #3436
It adds an additional check on safe.version before displaying version tag (green mark and label).
Open https://localhost:3000/settings/setup?safe=matic:0x68d231A531BcF34199a825AE568aa79b695f7965 and check there is no "Latest Version" label
> fix: Remove display version on unsupported contract

- src/features/walletconnect/WalletConnectContext.tsx
- src/features/walletconnect/components/WalletConnectProvider/index.tsx
- src/features/walletconnect/components/WcConnectionForm/index.tsx
- src/features/walletconnect/components/WcProposalForm/index.tsx
- src/features/walletconnect/components/WcSessionList/index.tsx
- src/features/walletconnect/components/WcSessionMananger/index.tsx
- src/features/walletconnect/hooks/__tests__/useWalletConnectSessions.test.tsx
- src/features/walletconnect/services/WalletConnectWallet.ts
Resolves #3200
- Adds loading indicators for `disconnect`, `reject` and `approve`
- Moves the `onDisconnect`, `onReject` and `onApprove` handler to the components where they are used instead of prop drilling them
Other changes:
💡 These aim to reduce complexity and improve the UX. We should discuss if we want to keep them or not. 💡 
- Removes the `handleBeforeUnload` call as there is no error and no such handling in the [example app](https://react-wallet.walletconnect.com/pairings). Reloading the page during an approval doesn't show any errors either, just an "Unknown" pairing but no active session. Using the same uri again establishes a session and updates the "Unknown" pairing which is expected.
- Removes `WcConnectionState` and associated logic. Switching back and forth with the dialogs …
> fix: Add loading states to WC

- src/components/dashboard/GovernanceSection/GovernanceSection.tsx
When in dev mode and on a chain different than eth or sepolia every refresh display a “Hydration failed error”. It turns out that the governance module is being rendered on the server, where in the client it return null. This is caused by the use of useChainId hook which returns a default chain on the server, but on the client the actual chain the user is on. With the isLayoutReady check we make sure that this component actually only renders when ran on the client.
Hydration error in dev mode
Prevents rendering of the component on the server
In dev mode switch the chain to something other than mainnet and sepolia. When on the dashboard refresh - you shouldn't see a hydration error.
> fix: hydration error on dashboard

- src/components/common/Header/index.tsx
- src/components/common/Header/styles.module.css
Hamburger icon is not left padded
Resolves #3372
Padding on left of hamburger icon matches that above and below it.
1. Removing edge="start" which uses a negative margin to counteract the padding on one side (this is often helpful for aligning the left or right side of the icon with content above or below, without ruining the border size and shape).
2. Removing unnecessary padding-left provided to MUI IconButton and adding padding 16 px to the Button child element of IconButton.
As it is a ui/css change you can test the issue with the steps mentioned in reproducing it.
> fix: Hamburger-icon

- src/features/walletconnect/services/WalletConnectWallet.ts
- src/features/walletconnect/services/__tests__/WalletConnectWallet.test.ts
If the user is trying to connect with WC to Opensea and the user is on a chain other than mainnet the first connection attempt fails. The second one succeeds. This is because when opensea sees the list of optional chains, after establishing a session it sends a request, but the request is for the optional chain and not for the required one and we end up blocking it. By giving up on the optional namespace Opensea sends the request to the requried chain.
Go to opensea to a collection that is on let's say OP. Try to establish WC connection to your safe that is also on OP. Establishing a connection should work.
> fix: cannot connect with WC to Opensea

- package.json
- src/hooks/wallets/useOnboard.ts
- src/services/tx/tx-sender/sdk.ts
- src/utils/wallets.ts
- yarn.lock
The Zerion Wallet mobile app, when connected via WalletConnect, connects to the wrong chain but onboard thinks it's on the right chain. In addition to that, `onboard.setChain` doesn't work for WalletConnect (probably because onboard thinks there's no need to switch the chain). Not sure on whose side is the bug, but this fixes it for us.
Basically, if we detect WalletConnect, it will always attempt to switch the chain even if it's seemingly already on the right one.
1. Connect Zerion to Safe as a signer
2. Attempt to sign or execute a tx
3. On prod, it would show a "Safe contract not deployed on this network" error
---
Other cases:
1. Switch MetaMask to some chain
2. Connect it to a Safe on another chain
3. Try to sign or execute a tx
4. It should offer to switch the chain in MM and …
> Fix: always switch wallet chain before signing/executing

- src/components/tx/SignOrExecuteForm/hooks.test.ts
- src/components/tx/SignOrExecuteForm/hooks.ts
Resolves #3422
Relaying a transaction first prompts the user to sign and then proposes the signed transaction to the backend which makes it appear in the queue with one signature but in case the call to the relay service fails, the tx dialog is still open and the user can either Execute the transaction again or only sign if the recommended nonce updated fast enough. This is confusing because the same transaction is already in the queue. Instead the transaction should not be queued unless the relay call succeeds.
Propose the unsigned transaction to the backend in case the user tries to relay. That way it doesn't show up in the queue unless executed and the recommended nonce also won't increase in case there is an error from the relay call.
1. Open a Safe on Sepolia
2. Create a transfer to …
> fix: Propose relay transactions without a signature

- src/components/common/SocialSigner/index.tsx
- src/components/welcome/WelcomeLogin/index.tsx
Resolves #3428 
- Passes the `onLogin` handler to `SocialSigner`
1. Open Safe on Gnosis Chain
2. Connect with your Google Account
3. Observe being redirected to the Accounts page
> fix: Redirect user to accounts page on social login

- src/components/theme/darkPalette.ts
- src/styles/vars.css
Resolves #3464
Reverts back to the previous `warning.background` color in dark mode
1. Open a Safe
2. Switch to dark mode
3. Go to the Settings and create a recovery
4. Observe that the warning text is readable
> fix: Revert warning.background color in dark mode

- src/components/tx-flow/common/TxLayout/index.tsx
- src/components/tx-flow/common/TxLayout/styles.module.css
- src/components/tx/SignOrExecuteForm/BatchButton.tsx
- src/components/tx/SignOrExecuteForm/SignForm.tsx
Overlapping buttons when signing a transaction #3403
Resolves #3403
As per the designs provided removed box component and used stack component to achieve the responsive design for different screen widths.  Added media queries for respective screen sizes to render the buttons as asked in the design.
Tested on various devices, screen sizes also by resizing the window.
> fix: Overlapping buttons when signing a transaction

- src/features/walletconnect/components/WalletConnectProvider/index.tsx
- src/features/walletconnect/components/WcInput/index.tsx
- src/features/walletconnect/components/WcProposalForm/index.tsx
- src/features/walletconnect/components/WcSessionMananger/index.tsx
Resolves #3395 
- Stores approvals for verified dApps per chain and auto approves future sessions
1. Open a Safe
2. Open a verified dApp (e.g. CowSwap)
3. Connect CowSwap to your Safe
4. A green message should be visible on the Approve screen
6. Press Approve
7. Disconnect the session and connect to CowSwap again
8. Observe no Approve screen and automatically connecting
9. Switch to a different chain and connect with CowSwap again
10. Observe the session is not auto approved
11. Oberve that the dialog closes on approval 
https://github.com/safe-global/safe-wallet-web/assets/5880855/a302c57d-71d3-4af6-9895-9239014f43e8
> feat: Auto approve verified WC sessions

- src/components/transactions/GroupedTxListItems/styles.module.css
Fixes a CSS bug in Safari that made conflicting tx groups look like this:
> Fix: Safari CSS - conflicting txs line

- src/components/tx-flow/SafeTxProvider.tsx
- src/components/tx/SignOrExecuteForm/hooks.ts
- src/services/tx/tx-sender/recommendedNonce.ts
The protocol-kit estimates the safeTxGas correctly but our SafeTxProvider overrides it with it's own estimation. Therefore this logic is removed with this commit so we only rely on the safeTxGas from the core-sdk.
Resolves #3171 
Remove all safeTxGas logic from our interface and let the protocol-kit handle it in `createTransaction` (except if the user explicitly overrides it)
- Use a 1.1.1 Safe and create a Rejection tx
- Observe that safeTxGas is 0 and it decodes correctly to a rejection
> fix: safeTxGas for rejection txs

- src/components/tx/SignOrExecuteForm/hooks.test.ts
- src/components/tx/SignOrExecuteForm/hooks.ts
Part of #3422 
This is a follow up to #3457 which solved the issue for immediately executed relay transactions but in case a user queued a transaction first and then decided to relay it would fail. We now check for the `txId` when relaying:
- If there is a `txId` it means the transaction has already been created and is queued so we propose the signed transaction
- If there is no `txId` it means it is an immediate execution so we propose the unsigned transaction
1. Open a 1/1 Safe on Sepolia
2. Create a new transaction to your own Safe (so that relaying fails)
3. Upon execution there should be an error message visible
4. There should not be a transaction in the queue
---
1. Switch to a 2/n Safe on Sepolia
2. Create a new transaction to your own Safe (so that relaying fails)
3. Sign that …
> fix: Propose signed transaction when relaying from the queue

- src/components/transactions/GroupedTxListItems/styles.module.css
Resolves [Notion](https://www.notion.so/safe-global/63420452940c454b809f3b5872e678ef?v=7044dcf36cdb4656b7b00878ede3974a&p=bbe5b688230e45cb8aaadd291fa2d573&pm=s)
- Removes the static color
1. Open a Safe
2. Queue two transactions with the same nonce
3. Check that the Conflicting transactions message is readable in both light and dark mode
> fix: Conflicting transaction color in dark mode

- src/components/tx-flow/SafeTxProvider.tsx
- src/components/tx/SignOrExecuteForm/hooks.ts
- src/services/tx/tx-sender/recommendedNonce.ts
This reverts commit 1dc5e3ea1aa0e37b2126b4c270b5e8be9f82323a.
The commit caused `safeTxGas is NaN` errors for transactions from SafeApps.
> Revert "fix: safeTxGas for rejection txs (#3452)"

- src/features/walletconnect/components/WcProposalForm/__tests__/useCompatibilityWarning.test.ts
- src/features/walletconnect/components/WcProposalForm/useCompatibilityWarning.ts
Make the warning more specifically refer to bridging as opposed to using a dapp.
> Fix: adjust bridge warning wording

- src/components/notification-center/NotificationCenter/index.tsx
Resolves #3465
The popup should be closed _after_ a navigation happens, not before. An MUI quirk. So I just added a simple timeout on link click.
> Fix: close Notifications popup after navigation

- src/utils/wallets.ts
Resolves #3508
Rabby and Zerion expose the same `window.ethereum._metamask` API as MetaMask itself, so it's possible to check if they are unlocked. If they are, we won't show a reconnect modal.
> Fix: don't show onboard popup on reconnect for MetaMask, Rabby and Zerion

- src/utils/__tests__/web3.test.ts
- src/utils/gateway.ts
- src/utils/safe-messages.ts
- src/utils/web3.ts
In Ethers v6, the signTypedData method unconditionally calls `eth_signTypedData_v4` that Ledger (and probably also Trezor) doesn't support. So I've added a fallback that calls `eth_signTypedData` if `eth_signTypedData_v4` fails.
Case 1:
* Propose a transaction with Ledger
* Delete that transaction with Ledger
Case 2:
* Sign a message with one of the signers being a Ledger
> Fix: [Tx Deletion] signTypedData fallback for Ledger

- src/components/transactions/TxStatusLabel/index.tsx
- src/components/transactions/TxSummary/index.test.tsx
- src/components/transactions/TxSummary/index.tsx
Resolves [Issue in QA Board](https://www.notion.so/safe-global/Tx-status-is-displayed-as-a-text-in-addition-to-n-of-M-5202a7c1373c4f5cb30fa42e2882cc30)
- Adds previous condition back to only render `TxStatusLabel` if the transaction is either not in the queue or if it is pending
1. Queue a transaction
2. Observe no status label in the queue
3. Execute the transaction
4. Observe a processing status label
5. Go to the history after execution
6. Observe a Success status label
> fix: Only show status label in queue if transaction is pending

- src/components/transactions/TxSummary/QueueActions.tsx
- src/components/transactions/TxSummary/index.tsx
- src/components/transactions/TxSummary/styles.module.css
Resolves #
Have a look at a pending transaction in the queue - both execute and speed up should have enough space from the elements above them.
> fix: status|speed up button too cramped up

- cypress/e2e/happypath/sendfunds_queue_1.cy.js
Resolves #3541 
- Adjust env variables in tests
> tests: adjust env variables in tests

- src/components/welcome/MyAccounts/CreateButton.tsx
- src/components/welcome/MyAccounts/index.tsx
The Connect wallet button was previously a textual button, and now it's a contained button:
Before:
After:
> Fix: make Connect wallet primary CTA on the Accounts page

- src/components/common/AddressBookInput/index.tsx
Resolves #3531 
It adds a memo function value (isInAddressBook) to find address in address book (returns true if found) and adds this check before displaying the message (if not isInAddressBook then display message).
1. Go to a safe you own
2. Add an address to the address book
3. Start a send funds tx
4. Copy/paste that address in the input
5. Check that "add to address book" is not showing anymore.
> fix: Hide "add to address book" when address already in the address book

- src/features/swap/components/OrderId/index.stories.tsx
- src/features/swap/components/OrderId/index.tsx
Adds an `OrderId` component for `SwapOrder`
1. Open the Storybook link
2. Compare the OrderId component with the specs
> feat: Add OrderId component for swaps

- src/components/tx-flow/flows/ReplaceTx/index.tsx
Resolves #3551
Only the last transaction in the queue and transactions with a duplicate nonce are allowed to be deleted.
I used `useRecommendedNonce() - 1` to calculate the last transaction nonce.
If a tx is in principle deletable but isn't the last one or a duplicate, we show a tooltip.
> Fix: allow deleting only last tx and duplicates

- .eslintrc.json
- src/components/dashboard/FirstSteps/index.tsx
- src/components/dashboard/FirstSteps/styles.module.css
Follow up on #3495 
- Adds back the `static.main` color to the badge
1. Create a counterfactual Safe
2. Go to the dashboard
3. Switch to dark mode
4. Observe the badges are readable
> fix: Dashboard widget color in dark mode

- src/services/tx/tx-sender/sdk.ts
Resolves #3515
If `wallet_switchEthereumChain` throughs an "Unrecognized chain" error, we'll attempt to add that chain to the wallet.
> Fix: use wallet_addEthereumChain if cannot switch chain

- src/features/swap/components/OrderId/index.tsx
the truncated orderId for cowswap orders should not contain 0x (it is also shown without it in the cowswap interface)
> Fix: truncated orderId should not contain 0x

- src/components/common/EthHashInfo/SrcEthHashInfo/index.stories.tsx
- src/components/common/EthHashInfo/SrcEthHashInfo/index.tsx
- src/components/common/EthHashInfo/SrcEthHashInfo/styles.module.css
- src/components/transactions/TxDetails/TxData/index.tsx
- src/features/swap/components/SwapTxInfo/index.tsx
We want to display a reduced `TxData` section for `SwapOrders` according to the [design specs](https://www.figma.com/file/VyA38zUPbJ2zflzCIYR6Nu/Swap?node-id=5807%3A29679&mode=dev)
- Extends `EthHashInfo` with a new prop `onlyName`
- Adds `SwapTxInfo` component
1. Execute a swap
2. Observe the new "Interact with" block
> feat: Add SwapTxInfo, extend EthHashInfo

- src/components/safe-apps/AppFrame/index.tsx
- src/hooks/safe-apps/useCustomAppCommunicator.tsx
We extracted the app communicator handlers into a new hook called `useCustomAppCommunicator`. It also uses the `useSafePermissions` hook but now this hooks is used in two places but the data is only updated in one. This results in the `AppFrame` not having the data for e.g. `permissionsRequest` so safe apps won't see a dialog when requesting permissions for the address book.
Uses `overrideHandlers` to keep the handlers in `AppFrame`
1.
> fix: Override handlers in new app communicator

- src/features/swap/components/SwapProgress/index.stories.tsx
- src/features/swap/components/SwapProgress/index.tsx
Adds `SwapProgress` component to be used in `SellOrder` according to the [Design](https://www.figma.com/file/VyA38zUPbJ2zflzCIYR6Nu/Swap?node-id=5974%3A14487&mode=dev)
1. Check the component in Storybook
> feat: Add SwapProgress component

- src/components/common/Table/DataTable.tsx
- src/features/swap/components/SwapOrder/index.tsx
- src/hooks/useMnemonicName/index.ts
Show different labels and a different order of swaps when its a sell or buy order.
- Adds a small gap for the `DataTable`
- Uses `TokenIcon` component so there is a fallback image
1. Create a buy and sell order
2. Observe the different orders and labels
> fix: Show different label for sell orders

- src/services/tx/__tests__/extractTxInfo.test.ts
- src/services/tx/extractTxInfo.ts
Inability to execute queued CoW Swap orders.
The `to` and `value` of `SwapOrder`-typed transactions were not being mapped correctly for the SDK. New mapping cases have been added to cover them accordingly, as well as test coverage.
Associated error prevention has also been included, should other transaction types be added in the future.
1. Queue a CoW Swap order.
2. Observe ability to successfully execute the order.
> fix: map `to` and `value` of `SwapOrder` type transactions

- cypress/e2e/pages/create_tx.pages.js
- cypress/e2e/pages/dashboard.pages.js
- cypress/e2e/pages/sidebar.pages.js
- Add wait time before adding value to clipboard
> Tests: add wait time

- src/components/dashboard/ActivityRewardsSection/index.tsx
The Learn more button in the Safe Pass banner did not open in a new tab.
- Sets `target` to `_blank`
- Click on Learn more
> fix: open info page in new tab

- src/components/transactions/ExecuteTxButton/index.tsx
- src/components/transactions/TxDetails/index.tsx
- src/components/transactions/TxDetails/styles.module.css
- src/components/transactions/TxStatusLabel/index.tsx
- src/components/transactions/TxSummary/index.tsx
- src/hooks/useTransactionStatus.ts
- src/utils/transaction-guards.ts
Resolves [Notion issue](https://www.notion.so/safe-global/View-pending-expired-swap-in-Queue-00dd0e0e820f4040aab6dea6995f4d73)
- Disables the Execute button if a swap order is expired
- Shows a red Cancelled label for cancelled swaps
1. Create a cow swap and queue it
2. Wait until its expired
3. Observe the Execute button is disabled and a message is shown
> fix: Disable Execute button for expired swaps

- src/features/swap/index.tsx
Renders better notifications about the swap status
https://www.notion.so/safe-global/8f5927d10d3643f3a0d2ebc02c8eb425?v=1ddb11e4f9454c5d85bc9b50cde32640&p=e3f19e8ddcaf4263ab4164a4eb95e333&pm=s
Changed the notification title and text to the agreed ones.
Create a cow swap and watch the notifications that are output. (You need to be on the swap page to see all of them)
> feat: implement better swap notifications

- src/features/swap/index.tsx
- src/features/swap/styles.module.css
- src/pages/swap.tsx
- src/styles/globals.css
Sets the swap widget page to full height so that the widget is not cut off
1. Open the Swap page
2. Click "My orders"
3. Observe the overlay taking up the available space
> fix: Set swap widget to full height

- src/components/common/Header/index.tsx
The logo has been historically linking to the Index or Welcome page which is now not so useful anymore.
It will now link to the Home page if on a different Safe page, or to the Accounts page (`/welcome/accounts`) if on Home already.
> Fix: link to the accounts page from the logo

- src/components/common/EthHashInfo/index.stories.tsx
- src/stories/storeDecorator.tsx
If you were trying to create a story for a component that uses redux state storybook was throwing an error
Ads a decorator that can wrap a story if testing a component that requires state.
> feat: add a redux store decorator for stories

- src/components/transactions/TxDetails/index.tsx
- src/utils/transaction-guards.ts
Resolves [Notion issue](https://www.notion.so/safe-global/Poll-order-status-2442e20147024c3bb69cf49263d1e69c)
- Polls `txDetails` every 15 seconds if its a swap order and the status of the swap is `open`
1. Create a Swap
2. Execute the transaction
3. Open the transaction in the history
4. Observe the status switching from `open` to `fulfilled`
> fix: Poll swap order details

- src/components/balances/AssetsTable/index.tsx
- src/components/common/BuyCryptoButton/index.tsx
- src/components/dashboard/Overview/Overview.tsx
- src/components/sidebar/SidebarNavigation/index.tsx
- src/utils/chains.ts
Adds a new feature flag for Swaps called `NATIVE_SWAPS` and hides UI elements if its not enabled.
- Hide the Swap button on the dashboard if feature is disabled
- Hide the Swap button in the assets table if feature is disabled
- Hide the Sidebar navigation item for Swaps if feature is disabled
- Use `formatUnits` in the assets table when passing the value for a swap
- Adjust the button layout on the dashboard for mobile view (3 columns, larger buttons)
For now the Swap feature is only enabled on Sepolia
1. Open a Safe on Mainnet
2. There should be no swap button on the dashboard
3. There should be no swap button in the sidebar navigation
4. There should be no swap button in the assets table
5. Open a Safe on Sepolia
6. Switch to a mobile view on the dashboard
7. Observe a three column …
> feat: Add Swap feature flag

- src/features/swap/components/SwapOrder/index.stories.tsx
- src/features/swap/components/SwapOrder/index.tsx
- src/features/swap/helpers/swapOrderBuilder.ts
- src/features/swap/helpers/utils.ts
The cowswap API was returning an unexpected value for the orderClass:
context:
Trust the appData.metadata.orderClass.orderClass to match the form used (Swap->market, Limit->limit, Twap->twap). More context:
The the order class in the API is what the order was considered during placement. Before, there was a difference between SWAP and LIMIT. Basically SWAP had a fee, LIMIT did not.
When we moved all orders to not have a pre-defined fee, everything became a LIMIT order from the protocol point of view.
> fix: wrong orderClass used

- src/components/tx-flow/common/TxNonce/index.tsx
Resolves #3159 
Show an error when user inputs a non integer number
- On the execute transaction screen, try to change the nonce to a number with a decimal point.
- It should show an error.
- Changing to an integer should work as before.
> fix: show input error if chosen nonce is not an integer

- cypress/e2e/happypath/sendfunds_relay.cy.js
- cypress/e2e/pages/dashboard.pages.js
- cypress/e2e/regression/address_book_2.cy.js
- cypress/e2e/regression/sidebar.cy.js
- cypress/e2e/regression/spending_limits.cy.js
- cypress/e2e/regression/tx_history.cy.js
- cypress/e2e/safe-apps/apps_list.cy.js
- cypress/e2e/smoke/dashboard.cy.js
- cypress/support/constants.js
- Skip unreliable clipboard operation tests
- Update balance for e2e test
- Update expected app name and app count in a test
> Tests: fix failing tests

- src/components/tx-flow/flows/SignMessage/SignMessage.tsx
Resolves https://www.notion.so/safe-global/a9aab340d6544cecb2c9be2c654a2c62?v=fe4919f55fb34c82afc07f08552c7967&p=f2a55e3ae651421ba8d673dbc8fcdd4a&pm=s
- Adds query parameter to settings link
- Receive a blind signing request
- Click on the settings link
- When asked to cancel the flow, cancel and witness no more crash
> fix: add query param to settings link

- src/features/swap/components/SwapOrder/index.tsx
Resolves: https://www.notion.so/safe-global/Show-swap-recipient-in-history-ad9368d5f2ee4de191e49315e9cb4251?pvs=4
- adds a new row for custom recipient orders showing the recipient address
- Example tx: `/transactions/tx?safe=sep:0xC62CBc9d49ba64EC27a1c27fAA9c7f2ce5D583C8&id=multisig_0xC62CBc9d49ba64EC27a1c27fAA9c7f2ce5D583C8_0xf32095000c4cbb67f0b24b45533422fc7f9ed009b92ed2e60348b3ba49baf42e`
> Feat: for swap orders with custom recipient, display recipient address in order details

- src/features/counterfactual/FirstTxFlow.tsx
Resolves: https://www.notion.so/safe-global/Create-your-first-transaction-8eb9359fcfd943fcaf1a401500458e43?pvs=4
- Link now leads to the native swap feature instead of the safe apps page.
> Feat: Make swap link in CF first transaction modal lead to native swap feature

- src/features/swap/helpers/__tests__/utils.test.ts
- src/features/swap/helpers/utils.ts
Resolves: https://www.notion.so/safe-global/Check-surplus-calculation-31c4ea517ab74a2a8c8f1555a6447fb1?pvs=4
- use the correct values to calculate surplus depending on the order type
- for buy orders: (executed sell amount) - (order sell amount)
- for sell orders: (order buy amount) - (executed sell amount)
- Compare the surplus value in the safe tx to the surplus value given in the cowswap order, and ensure the values are the same. For both transaction types: `buy` and `sell`
- example buy order
- https://fix_surplus_calc--walletweb.review-wallet-web.5afe.dev/transactions/tx?safe=sep:0x8FAb71C0d4272698A3B2d1F3Ed5FC3c1B9b3E531&id=multisig_0x8FAb71C0d4272698A3B2d1F3Ed5FC3c1B9b3E531_0x3e84f6c60d81a710328ab141f595ea0fb4275ca5da4b7d019a7a0cc98cf67f7d
- …
> Fix: use correct values for swap order surplus calculation

- src/features/swap/index.tsx
- src/pages/swap.tsx
Shows the user a message instead of the native swaps widget in case they try to open the swaps route on an unsupported chain.
- Removes hard-coded supported chains for swaps and uses the feature flag instead
1. Open the `/swaps` route on an unsupported chain
2. Observe the message showing instead of the widget
> fix: Use feature flag for swaps widget

- src/components/tx-flow/flows/SuccessScreen/index.tsx
- src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
This is an attempt to make the swap a bit less confusing after performing a swap. We incentivise the user to go to "view transaction" instead of staying on the swap page. This way he won't be on the swap page that just displays "order submitted" with no further information about the order itself. 
Resolves
https://www.notion.so/safe-global/Submit-order-redirect-5e826c01903249fdb3cfc116811fa472?pvs=4
Hides the "Finish" button on the Success screen
Perform a swap. On the success screen you should only see "view transaction"
> feat: hide finish button on success screen for swaps

- src/features/counterfactual/FirstTxFlow.tsx
Resolves: https://www.notion.so/safe-global/Create-your-first-transaction-8eb9359fcfd943fcaf1a401500458e43?pvs=4
- On the first transaction modal on counterfactual safes:
- Links to native swap feature for supported chains
- Otherwise keeps current functionality (links to filtered safe apps)
> Fix: CF first transaction swap link goes to safe apps page if native swaps is not enabled

- src/components/transactions/TxDetails/index.tsx
Follow up on [Notion issue](https://www.notion.so/safe-global/Poll-order-status-2442e20147024c3bb69cf49263d1e69c)
- Always fetches the transaction details for a swap order instead of relying on an existing value
1. Create and execute a swap order
2. Go to the transaction details view or history
3. Expand to see the transaction details
4. Observe the status updating from open to fulfilled after a while
> fix: Always poll swap info

- src/components/transactions/ExecuteTxButton/index.tsx
- src/components/transactions/SignTxButton/index.tsx
- src/components/transactions/TxSummary/index.tsx
- src/features/swap/hooks/useIsExpiredSwap.ts
- src/hooks/__tests__/useInterval.test.ts
- src/hooks/useInterval.ts
Resolves [Notion issue](https://www.notion.so/safe-global/Disable-Confirm-for-expired-orders-a9a31d79065e4b63976a40a4cadc8d3c)
Checks the expiry date of a swap order every 10s and disables the Confirm/Execute button if it expired
- Adds a new hook `useInterval`
- Adds a new hook `useIsExpiredSwap`
This should be tested in a 1/n and n/m safe
1. Create a limit swap with an expiry of 5 minutes and an unfillable order
2. Queue the transaction but don't execute it
3. Observe that after 5 minutes the status automatically changes to expired and the button becomes disabled
> fix: Check expiry status of swaps at a given interval

- src/components/balances/AssetsTable/index.tsx
- src/hooks/safe-apps/useCustomAppCommunicator.tsx
- src/services/analytics/events/safeApps.ts
- src/services/analytics/events/transactions.ts
- src/services/analytics/tx-tracking.ts
- Adds event for opening safe apps modals with app name as label
- Adds token address as label to event for the Swap button in the assets table
- adds native_swap as tx type for swap transactions
- Create a Swap through our modal and observe the new /adjusted events
> Analytics: swap analytics

- src/features/swap/index.tsx
- the app communicator was not correctly initialized when the disclaimer is displayed
Resolves #
- Adds the consent flag to the dependencies of the useEffect that sets the iframeRef.
- Delete the disclaimer consent from local storage
- Open the CoW widget
- Witness that the connection succeeds
> Fix: cow swap disclaimer communication

- src/features/swap/components/SwapOrderConfirmationView/index.tsx
Resolves [Notion issue](https://www.notion.so/safe-global/Slippage-is-displayed-for-the-Limit-Orders-on-Confirmation-page-during-tx-creation-a2d2a8a3bdb74964950b3611b85ae498)
- Hides the Slippage if the `orderClass` is `limit`
1. Create a limit order
2. Submit the order in the widget
3. Observe no Slippage in the order details
> fix: Hide slippage for swap limit orders

- src/components/transactions/ExecuteTxButton/index.tsx
Resolves #3644 
Disables the execute button if transaction is pending
1. Create and queue a transaction
2. Execute the transaction
3. The transaction should be pending
4. Open the transaction details
5. Observe the Execute button is disabled
> fix: Disable execute button for pending transactions

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-production.yml
As requested by @luarx, an update for our deployment actions:
* New action version
* A more secure AWS auth method w/o using keys.
> Chore: update AWS action

- package.json
- src/components/common/NamedAddress/index.tsx
- src/components/common/NamedAddressInfo/index.test.tsx
- src/components/common/NamedAddressInfo/index.tsx
- src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx
- src/components/transactions/TxDetails/TxData/DecodedData/index.tsx
- src/features/swap/components/SwapOrderConfirmationView/index.tsx
- yarn.lock
Contract interactions where not decoded using known addresses.
- Fetches contract info from known addresses for every `to` address during tx decoding.
- Initiate txs and observe the correct contract names being shown.
> feat: fetch contract info for contract interactions

- src/components/transactions/TxDetails/index.tsx
- src/components/transactions/TxSummary/index.tsx
- src/features/swap/hooks/useIsExpiredSwap.ts
- src/utils/transaction-guards.ts
Resolves [Notion issue](https://www.notion.so/safe-global/Issue-Expired-status-is-displayed-for-the-orders-with-filled-status-in-the-history-3b1c5384735c405d8ba91a7fd47772b8)
- Checks `isQueue` before rendering the status label and expiry message
- Removes the previously added `isExpiredSwapInfo` check
1. Create and queue a limit swap order
2. Wait for it to expire
3. The buttons should become disabled in the queue and the message should be visible
4. Execute a swap order that can be fulfilled
5. Wait for the execution time to pass
6. Observe the status label saying Success in the tx history and no message visible
7. Execute a limit order that can't be fulfilled
8. Observe the status label saying Success in the tx history and no message visible
Queue expired:
History expired:
History …
> fix: Hide Expired status in tx history

- src/components/common/TokenIcon/index.tsx
- src/components/common/TokenIcon/styles.module.css
- src/components/transactions/TxInfo/index.tsx
Resolves: https://www.notion.so/safe-global/Display-token-icons-in-the-tx-list-12098c01ba6743b7a3669e6262c9800c?pvs=4
- display the sell token symbol and then the buy token symbol in the transaction info 
- Excecute a swap
- View the swap tx in transaction history.
> Feat: Add token symbols to swap transaction summary

- src/components/new-safe/create/index.tsx
- src/components/new-safe/create/steps/OwnerPolicyStep/index.tsx
Resolves #3571
- Moves the defaultOwner logic from the parent component to the owner step so that it updates if the wallet was changed during one of the steps
1. Go to safe creation with wallet 1
2. Switch to wallet 2 in the first step
3. Go to the owner step
4. Observe wallet 2 is the default owner
5. Switch back to wallet 1
6. Observe wallet 2 is still the default owner
7. Go back one step and forth again
8. Observe wallet 2 is still the default owner
> fix: Set default owner on safe creation when entering step

- package.json
- src/components/theme/safeTheme.ts
- src/components/tx/ApprovalEditor/ApprovalEditor.test.tsx
- src/components/tx/ApprovalEditor/ApprovalEditorForm.test.tsx
- src/components/tx/ApprovalEditor/ApprovalEditorForm.tsx
- src/components/tx/ApprovalEditor/ApprovalItem.tsx
- src/components/tx/ApprovalEditor/ApprovalValueField.tsx
- src/components/tx/ApprovalEditor/Approvals.tsx
- src/components/tx/ApprovalEditor/EditableApprovalItem.tsx
- src/components/tx/ApprovalEditor/SpenderField.tsx
- src/components/tx/ApprovalEditor/hooks/useApprovalInfos.test.ts
- src/components/tx/ApprovalEditor/hooks/useApprovalInfos.ts
- src/components/tx/ApprovalEditor/index.tsx
- src/components/tx/ApprovalEditor/styles.module.css
- src/components/tx/ApprovalEditor/utils/approvals.ts
- src/services/security/modules/ApprovalModule/index.ts
- yarn.lock
Resolves #3607 
- Changes layout / design of approval editor
- Groups approvals by spender address
- Fetches and displays contract name for spender address
- Use any app that requires approvals OR transaction builder to craft specific approval payloads
- Observe the approval editor
* [] I've written a unit/e2e test for it (if applicable) 🧑‍💻
> feat: redesign approval editor

- src/components/transactions/TxSummary/index.tsx
- src/components/transactions/TxSummary/styles.module.css
Resolves:https://www.notion.so/safe-global/Loader-icon-on-top-of-the-expired-tag-4ddba4d2f2564ab0b1481b92ca6451a7?pvs=4
- If a pending swap transaction takes longer than the allotted time to execute
- show the transaction as expired only. 
- Do not give the option to speed up the transaction.
> Fix: do not show pending status if swap order is expired

- src/hooks/useTransactionType.ts
Resolves:  https://www.notion.so/safe-global/Issue-Add-new-icon-for-the-txs-from-the-Native-swap-diff-from-Cowswap-history-and-queued-lists-aab4b65e0f7e495f934f0b76bd2c317a?pvs=4
- Use the new icon for native swaps but keep the cow icon for swaps done via the cowswap safe app.
> fix: Use native swap icon for native swap transactions in the queue

- src/components/transactions/TxInfo/index.tsx
- src/components/transactions/TxSummary/styles.module.css
- execute tx button is hidden for some widths [1]
- the tx info overlaps with the tx date for some widths in swap transactions [2]
Resolves #3664 
Resolves: https://www.notion.so/safe-global/07996126a3c041db90e36e01eb4ce46c?v=03b2eaffc9af4b48b1bf57e50546ac3d&p=12098c01ba6743b7a3669e6262c9800c&pm=s (thread)
- Increases the breakpoint for splitting the summary over two lines, so the execute button does not become hidden
- Increases the width of the tx info section to accomodate the longer swap transaction info
- Add a max with with `nowrap` for longer token names  in the tx summary
- View a swap transaction in the queue.
- see that the execute/speed up button is visible for all screen widths
- see that there is no overlap between the tx info and the date, including when the token names are …
> Fix: text overlaps and hidden execute button in the transaction summary

- src/components/sidebar/SidebarHeader/index.tsx
If a Safe doesn't have a name in the Address Book, do a reverse ENS lookup in the Sidebar.
Can be tested with the Safe from the PR preview link.
> Feat: resolve Safe address ENS in sidebar

- src/features/swap/helpers/utils.ts
Resolves: https://www.notion.so/safe-global/Look-at-our-appData-usage-714b0f9b7639465ab39b5d13d2d102b0
According to the cowswap team, fullAppData can not be assumed to always be defined, so we must include default values for when it isn't.
> Fix: Account for when fullAppData is undefined on swap orders 

- src/components/transactions/TxSummary/index.tsx
- src/components/transactions/TxSummary/styles.module.css
- Queue switches to mobile/tablet view on too large screens
- grouped transactions are not aligned
resolves: https://www.notion.so/safe-global/Issue-dancing-view-for-the-Queued-because-of-expired-state-f81f11c9114d4e8e9975708b3fe899db [SWT-69]
> Fix: queue changes to mobile layout on desktop resolutions

- src/features/counterfactual/CounterfactualForm.tsx
We didn't call the `onSubmit` handler in `CounterfactualForm` so safe apps didn't receive a `safeTxHash` when submitting transactions.
- Call `onSubmit` when submitting in `CounterfactualForm`
1. Create a counterfactual safe
2. Send some WETH to it
3. Open the CowSwap safe app
4. Create a TWAP order
5. Submit the transaction in the tx-flow
6. Observe that CowSwap shows a success message and is not stuck
> fix: [Counterfactual] Call onSubmit handler when submitting a transaction

- src/components/dashboard/Overview/Overview.tsx
- src/services/analytics/events/swaps.ts
- adds an extra click event for entering the native swaps feature from the dashbaord.
> Feat: Add click event for dashboard swap button

- src/components/tx-flow/flows/SafeAppsTx/ReviewSafeAppsTx.tsx
Resolves [Notion issue](https://www.notion.so/safe-global/Remove-the-option-of-Add-to-batch-ff5ce2a525c1406d90b5db92445ab0e3) [SWT-72]
- Disables the Add to Batch button if the transaction comes from the native swap widget
1. Create a swap order
2. Try to sign it
3. Observe the Add to Batch button is disabled
> fix: Disable batching for native swaps

- src/components/tx/SignOrExecuteForm/index.tsx
- src/features/speedup/components/SpeedUpModal.tsx
- src/hooks/useTxTracking.ts
- src/services/analytics/__tests__/tx-tracking.test.ts
- src/services/analytics/gtm.ts
- src/services/analytics/tx-tracking.ts
- src/services/analytics/types.ts
Resolves [Notion issue](https://www.notion.so/safe-global/Send-order-status-to-GA-740c268ea08f4c929adc3d6c4b3fb041)
- Sends the `orderUid` as a predefined dimension called `transaction_id` with certain events such as `tx_created`, `tx_confirmed`, `tx_executed`, `on-chain interaction`
1. Create a swap order
2. Press submit in the modal
3. Observe the GTM event containing `transaction_id` with the `orderUid` as the value
> fix: Send orderUid with analytics events

- src/components/balances/AssetsTable/index.tsx
- src/components/sidebar/SidebarNavigation/index.tsx
- src/features/counterfactual/FirstTxFlow.tsx
Resolves #
Due to a bug, the swap widget is not picking up the creation of a counterfactual safe. 
Until this is resolved, we’ll disable the swap feature for counterfactual safes
Create a counterfactual safe. The swap button should be missing from the dashboard, assets and navigation. For the first transaction modal there is a swap button, but it should lead to the safe apps page and not the native integration.
> fix: remove swap from counterfactual safes [SWAP-66]

- src/components/dashboard/Overview/Overview.tsx
- src/components/sidebar/SidebarNavigation/index.tsx
- src/features/swap/components/SwapButton/index.tsx
- src/services/analytics/events/swaps.ts
- Adds tracking event for the sidebar.
- Renames the open swap event action.
- Removes token ID from asset page event.
> Feat: add tracking event for the sidebar swaps link

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-production.yml
- .github/workflows/e2e-hp-ondemand.yml
- .github/workflows/e2e-ondemand.yml
- .github/workflows/e2e-regression.yml
- .github/workflows/e2e-safe-apps.yml
- .github/workflows/e2e-smoke.yml
- .github/workflows/lint.yml
- .github/workflows/nextjs-bundle-analysis.yml
- .github/workflows/tag-release.yml
- .github/workflows/unit-tests.yml
`actions/upload-release-asset@v1` is [failing](https://github.com/safe-global/safe-wallet-web/actions/runs/9063027490/job/24898450610) with `Error: Resource not accessible by integration` so I moved it down to let the S3 upload step to run before the entire action fails.
I also updated the checkout action to v4 in all the workflows.
> Chore: move checksum upload step

- src/features/swap/index.tsx
The title says it all.
Create a swap and observe the fees section.
> fix: feeTooltip text was wrong

- .github/workflows/deploy-production.yml
- scripts/github/s3_upload.sh
The checksum `if` was wrong, it should check for file existence with `-f`.
> Chore: fix checksum upload

- Dockerfile
When playing around with the Safe web interface I noticed that the Docker image that it produces is **over 6GB in size**! This is very large for a docker image that just hosts static files.
This PR slims down the docker image significantly by using a multistage build where the first stage builds the static website, and the actual image just hosts the static webside (here using BusyBox `httpd` which is nice and lightweight).
This gets the image down to around 72MB, around 1% of the original image size _(sizes computed from Docker images built on amd64 Linux)_.
Note that there is one weird detail is that static HTTP servers typically don't have support for automatically adding `.html` endings to URL paths. It was worked around here with symlinks. See comment in the Dockerfile for more …
> Slim Down Docker Image

- Dockerfile
PR #3707 changed the docker file to produce smaller artifacts, however, this started causing [CI errors](https://github.com/safe-global/safe-wallet-web/actions/runs/9083918124/job/24963680879).
This reverts PR #3707 in the meantime. I will investigate and try to make a follow up PR that fixes the issue.
> Revert "Slim Down Docker Image"

- src/components/transactions/TxList/index.tsx
- src/hooks/__tests__/usePendingTxs.test.ts
- src/hooks/usePendingTxs.ts
Resolves #3215
- Only shows unsigned transactions in the untrusted pending queue
- Changes the first label of the queue to always show "Pending" when a transaction is pending
A few variations in 1/n and n/m safes should be tests
1. Queue 2 transactions and execute the first one
2. Queue 2 transactions and bulk execute
3. Queue 1 transaction, create another one and immediately execute that one to replace the first
> fix: Hide signed transaction from untrusted pending queue

- src/features/walletconnect/constants.ts
Resolves #3738
It will now only show a bridge warning for rhino.fi.
> Fix: move rhino.fi to warned bridges

- .github/workflows/deploy-production.yml
The action `actions/upload-release-asset@v1` stopped working and it's not maintained, so I replaced it with `Shopify/upload-to-release@v1`. See https://github.com/marketplace/actions/upload-to-release-action
> Chore: update release action

- src/features/walletconnect/services/WalletConnectWallet.ts
- src/features/walletconnect/services/__tests__/WalletConnectWallet.test.ts
Sometimes the chainChanged event is ignored if the connected dapp did not acknowledge the new session yet.
Then the dapp is stuck with a wrong chain on which the Safe is not deployed.
- Only uses our workaround if the Safe is not present in the requiredNamespace
- Connect to uniswap with a polygon Safe
- observe that the Safe is correctly recognized on Polygon
> fix: (WC) do not return Safe as available on all optional Namespaces

- src/components/welcome/MyAccounts/useSafeOverviews.ts
Balances and pending actions in the Safe List are now cached until the new data arrives or the page is reloaded, so that there's less jumping every time you open the sidebar.
* Connect a wallet with many Safes
* Open the Sidebar
* Disconnect or switch to another wallet
* The list should be updated accordingly
* Close the sidebar and open it again
* Balances and pending actions should be visible immediately
> Fix: memoize Safe List data

- src/components/transactions/TxFilterForm/TxFilterForm.test.tsx
- src/components/transactions/TxFilterForm/index.tsx
Resolves #3759 
- Add component tests for TxFilterForm
- Run tests and observe outcome
> Tests: add component tests for tx history filter

- src/components/sidebar/SidebarNavigation/config.tsx
- src/components/sidebar/SidebarNavigation/index.tsx
- src/components/theme/darkPalette.ts
- src/components/theme/safeTheme.ts
Displays a "new" label next to the swap navitem
Open a safe and in the menu on the right Swap should have a "new" badge/label.
> feat: add new label to swaps button [SWAP-86]

- next-env.d.ts
- src/components/common/BuyCryptoButton/index.tsx
- src/components/common/SafeTokenWidget/index.tsx
- src/components/tx-flow/index.tsx
- src/hooks/useIsSidebarRoute.ts
- src/services/tx/tx-sender/sdk.ts
- tsconfig.json
Part of #3745
In Rabby, the error when trying to switch to a network that is not yet added is nested and doesn't pass our condition. It now checks for a nested `code` in the error that is thrown.
1. Remove Sepolia network from Rabby
2. Connect to a Sepolia Safe
3. Create / Execute a transaction or sign a message
4. Observe there is no error and instead Rabby pops up to add Sepolia as a new network
> fix: Add network to Rabby if unknown

- src/components/tx-flow/flows/ExecuteBatch/ReviewBatch.tsx
- src/services/analytics/events/transactions.ts
Add a new tx type for bulk executions to differentiate them from batches.
> Analytics: differentiate bulk executions from batches

- src/components/welcome/MyAccounts/useTrackedSafesCount.ts
Resolves https://www.notion.so/safe-global/1f1df3f06ead4378ab1c9c3de24951b1?v=6ad2667b868d4c0f8cf18e129f762583&p=cf2a606d10e94de49050d87973a54621&pm=s
- Does not track owned Safes if no wallet is connected
- Add a counterfactual Safe
- observe that nothing is logged without owner connected
- Observe that with owner connected the counts are correct
> fix: counterfactual safe tracking

- src/features/recovery/components/RecoverySettings/index.tsx
The Recovery feature is not "new" anymore so this label should be removed.
> Fix: remove the New chip from Recovery settings

- src/hooks/coreSDK/useInitSafeCoreSDK.ts
- src/services/exceptions/ErrorCodes.ts
Resolves #3587
Judging by the Sentry logs, this error is happening when an RCP responds with an error.
There's nothing we can do about this from the frontend, but the error message should be clearer.
> Fix: Error initializing the Safe Core SDK -> Error connecting to the blockchain

- src/components/tx-flow/common/TxButton.tsx
- src/components/tx-flow/flows/NewTx/index.tsx
- src/services/analytics/events/modals.ts
Added a swap tokens there and slightly updated the visual presentation according to the figma: https://www.figma.com/design/VyA38zUPbJ2zflzCIYR6Nu/Swap?node-id=6588-48609&t=LhvUJl76y7PuTnIS-4
Hit the "New Transaction" button and enjoy!
> feat: slight UI improvements to the new tx flow [SWAP-89]

- src/components/balances/AssetsTable/index.tsx
SWAP-83
- Sets amount to 0
Click on swap button on assets list
> fix: use zero swap amount from assets table [SWAP-83]

- next-env.d.ts
- src/features/swap/index.tsx
When switching betwenn Swap/Limit forms, selected tokens are reset. On CoW Swap they  are synced between all forms.
We were re-rendering the widget when the user switches between swap and a limit swap and this was causing the sellToken to reset. Now, we no longer do this
1. Navigate to swaps
2. Select a different token
3. switch to limit order
> fix: switch between swap & limit loses token [SWAP-97]

- src/components/welcome/MyAccounts/PaginatedSafeList.tsx
Resolves #3794
`chainId` wasn't taken into account when looking up Safes in the balances list.
> Fix: same addresses showing same balance

- src/components/common/EthHashInfo/SrcEthHashInfo/index.tsx
- src/components/common/EthHashInfo/index.tsx
Show an indicator when displaying a name of an address from the Address Book.
> Feat: address book indicator

- src/components/common/NetworkSelector/index.tsx
After we removed the automatic redirect from `/welcome` to `/welcome/accounts` if wallet is connected, the Network Selector started requiring an extra click to see the list of your Safes. This PR fixes that.
The Network Select will now take you straight to `/welcome/accounts` if wallet is connected.
> Fix: improve chain switch redirect

- src/features/swap/index.tsx
CoW was not written properly in the fee tooltip:
https://prnt.sc/LHMI8U0QvfQa
Look at the fee tooltip.
> fix: typo in feeTooltipMarkdown [SWAP-93]

- src/components/welcome/MyAccounts/__tests__/useSafeOverviews.test.ts
- src/components/welcome/MyAccounts/useSafeOverviews.ts
I'm not sure what the root cause of undefined addresses is, they seem to be already [filtered by Boolean](https://github.com/safe-global/safe-wallet-web/blob/dev/src/components/welcome/MyAccounts/useAllSafes.ts#L55) before being passed to `useSafeOverviews`. But here's a fix that just filters out bad values before sending a request to CGW.
> Fix: filter out undefined address in useSafeOverviews

- src/services/analytics/gtm.ts
- src/services/analytics/useGtm.ts
Like we do with Safe addresses, signer addresses must be trimmed so that GA/BigQuery doesn't try to convert them to integers.
> Analytics: remove 0x from signer address

- src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
- src/hooks/__tests__/useRemainingRelays.test.ts
- src/hooks/useRemainingRelays.ts
- src/utils/chains.ts
Resolves SWAP-100
New feature flag to offer relaying for native swaps only.
- On staging gnosis chain swaps are temporily only available for native swaps to test this PR
- Test a tx from the native swaps
- Test a tx from other sources / Safe apps
> feat: relaying for native swaps only [SWAP-100]

- src/features/swap/components/SwapOrder/index.tsx
- src/features/swap/helpers/__tests__/utils.test.ts
- src/features/swap/helpers/utils.ts
Resolves: https://www.notion.so/safe-global/Better-Surplus-calculation-2e3bf20feeed46938c6efa6728c5ea94?pvs=4
- Calculate surplus for partially filled orders instead of only for fully fulfilled orders, like CoW Swap are doing.
- Create a partially fillable limit order.
- When the order is partially filled, check that the surplus price is displayed. Check that it is the same as the order on cowswap.
- You can set the sell amount to more than your current balance to make sure that it will be partially filled
> Feat: calculate surplus for partially filled orders

- src/components/transactions/TxSummary/index.tsx
- src/features/recovery/components/ExecuteRecoveryButton/index.tsx
- src/features/recovery/components/RecoverySummary/index.tsx
Resolves: https://www.notion.so/safe-global/Reposition-execute-button-for-the-recovery-transaction-ba6c3968a2c44d2f93f9f9e848bda873
- puts the recovery transactions execute button in the 'actions' column.
- uses the same styles as the normal recovery button to make sure they are aligned.
- removes unused css class (unrelated)
> Fix: move the execute button on recovery transactions to the correct column [SWAP-75]

- src/components/tx-flow/flows/SuccessScreen/index.tsx
- src/hooks/useTxNotifications.ts
- src/store/swapOrderSlice.ts
- src/utils/tx-link.ts
We don’t always have the txId in the order information, but when we do we add a link to the notification.
It’s highly likely that order created events won’t ever have a txId as this event is created before submitting the tx to the blockchain.
I had to extract getTxLink to a separate file as having it in useTxNotifications was causing a circular dependency error in our tests.
Resolves #
This PR cannot guarantee that the push notification displayed will have a "view transaction" link. It all depends in what order the updates to the order will come through (whether they will be triggered through the widget or through the transaction service). If the user leaves the widget page after submitting a tx, then updates will most probably come from the tx service and there will be "view transaction" …
> feat: add link to tx for order notifications [SWAP-61]

- cypress/fixtures/txhistory_data_data.json
- src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.test.tsx
- src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx
Lowercase "native transfer" was capitalized in #3760 but it's not consistent with other tx types in decoded multisends.
Restores it to how it was.
> Fix: restore lowercase "native transfer"

- src/components/tx-flow/flows/SafeAppsTx/index.tsx
- src/components/tx-flow/flows/SignMessage/index.tsx
- src/features/swap/index.tsx
Resolves SWAP-81
- Decodes transactions and adds a label containing:
- Wrap txs
- approvals
- Swaps orders
> feat: decode txs in swap modal [SWAP-81]

- src/components/balances/AssetsTable/index.tsx
- src/components/common/EnhancedTable/index.tsx
- src/components/common/FiatValue/index.tsx
- src/components/common/TokenAmount/index.test.tsx
- src/components/dashboard/Assets/index.tsx
- src/components/dashboard/Overview/Overview.tsx
- src/components/welcome/MyAccounts/AccountItem.tsx
- src/utils/__tests__/formatNumber.test.ts
- src/utils/formatNumber.ts
A revised fiat and token amount formatting rules as outlined [here](https://www.notion.so/safe-global/Revised-number-formatting-cd2f32bcd9174626851c27bb34cb163a).
This PR simplifies the formatting logic quite a lot, and relies on browser's default formatting plus some tweaks.
Additionally, it right-aligns fiat values in Asset tables.
> Feat: better fiat and token amount formatting

- src/components/tx-flow/flows/ExecuteBatch/ReviewBatch.tsx
- src/components/tx/security/tenderly/__tests__/utils.test.ts
- src/components/tx/security/tenderly/utils.ts
- src/features/recovery/services/__tests__/recovery-state.test.ts
- src/features/recovery/services/__tests__/transaction-list.test.ts
- src/features/recovery/services/recovery-state.ts
- src/services/contracts/__tests__/deployments.test.ts
- src/services/contracts/__tests__/safeContracts.test.ts
- src/services/contracts/deployments.ts
- src/services/contracts/safeContracts.ts
- src/services/security/modules/DelegateCallModule/index.test.ts
- src/services/security/modules/DelegateCallModule/index.ts
Refactoring to generally use the latest version of the MultiSendCallOnly available for the given network. This simplification enables removing some logic for determining the MultiSendCallOnly version from the codebase.
There is no dependency between the Safe version and the multisend version, meaning any Safe can use any multisend version. Assuming that the latest MultiSendCallOnly contract version is most optimized, it doesn't make sense to use legacy versions with older Safes.
A consistent multisend address also makes the configuration of the Roles Modifier more straightforward. (Users of the Roles mod need to explicitly enable all allowed multisend addresses.)
Make some multisend transactions on different versions of Safe (1.3.0, 1.1.1, 1.4.1)
> Refactor: Consistently use latest MultiSendCallOnly address 

- src/components/common/FiatValue/index.tsx
- src/utils/formatNumber.ts
Firefox doesn't play nicely with `undefined` as a locale parameter.
> Fix: explicitly pass a locale to NumberFormat

- src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx
- src/components/transactions/TxDetails/TxData/DecodedData/index.tsx
- src/components/tx/DecodedTx/index.tsx
- src/components/tx/FieldsGrid/index.tsx
- src/components/tx/SendToBlock/index.tsx
On some resolutions the value of a transaction is cut off and not visible in the transaction review screen.
Show value of transaction separately to the to address.
Create a tx with value > 0 via. e.g. transaction builder.
> fix: always show tx value

- src/components/tx/SignOrExecuteForm/PermissionsCheck/__test__/PermissionsCheck.test.tsx
- src/components/tx/SignOrExecuteForm/PermissionsCheck/hooks.ts
- src/features/recovery/components/RecoveryContext/__tests__/useRecoveryState.test.tsx
- src/utils/chains.ts
- Adds a feature toggle `ZODIAC_ROLES` to the roles integration
- Turn off the feature toggle and observe that roles execution is not offered
> feat: add feature toggle for zodiac roles integration

- src/components/dashboard/index.tsx
- src/components/welcome/MyAccounts/AccountItem.tsx
* Show skeletons while fiat totals are loading in the Account List
* Stretch the Swaps banner to full width if there's no SAP banner
> Fix: add skeletons in Account List + stretch Swaps banner

- src/features/walletconnect/__tests__/WalletConnectContext.test.tsx
- src/features/walletconnect/components/WalletConnectProvider/index.tsx
- src/services/safe-wallet-provider/index.ts
Resolves https://www.notion.so/safe-global/Signing-message-shows-a-too_small-error-8d4a815756e142e194e56fb57638b211
- Does not pass -1 as appId but undefined instead
- Sign a message
- Sign a tx
> fix: do not pass negative app id

- src/services/private-key-module/index.ts
- src/tests/e2e-wallet.ts
Onboard cannot subscribe to the chainChanged event if it's emitted synchronously right after connecting.
Giving it a small delay allows onboard to subscribe to this event and fetch an ENS name and account balance of the connected address.
> Fix: delay chainChanged event in test wallet

- src/components/dashboard/ActivityRewardsSection/index.tsx
- src/components/welcome/MyAccounts/PaginatedSafeList.tsx
- src/components/welcome/MyAccounts/index.tsx
* Add a simple loading indicator in the safe list.
* Adjust the CSS of the SAP banner
> Fix: add loading indicator for safe list

- next-env.d.ts
- src/components/settings/SecurityLogin/index.tsx
- src/hooks/useAdjustUrl.ts
- src/pages/apps/open.tsx
Resolves #3843
* I've added a static list of routes that require a `safe` query param
* I've added this logic to an existing `useAdjustUrl` hook that has somewhat related functionality
* For `/apps/open` without `?safe`, there's a special redirect to the Safe App share route
> Fix: redirect routes w/o ?safe

- src/components/tx/ApprovalEditor/ApprovalEditorForm.tsx
- src/components/tx/ApprovalEditor/EditableApprovalItem.tsx
- src/components/tx/ApprovalEditor/index.tsx
- src/components/tx/DecodedTx/index.tsx
- src/components/tx/SignOrExecuteForm/index.tsx
- src/features/swap/components/SwapOrderConfirmationView/index.tsx
- src/hooks/useDecodeTx.ts
A few UI adjustments for the Approval Editor in swap transactions.
* The approval editor is now shown below Swap details
* The entire Unlimited amount block is clickable (becomes editable)
* The tracking event on click is now differentiated by label: `edit` or `save`.
Internal discussion: https://5afe.slack.com/archives/C06GBBW39QU/p1718885834196179
> Fix: adjust approval editor with swaps

- package.json
- src/components/common/Table/EmptyRow.tsx
- src/components/common/Table/styles.module.css
- src/components/transactions/TxDetails/TxData/index.tsx
- src/components/transactions/TxDetails/index.tsx
- src/components/transactions/TxInfo/index.tsx
- src/components/transactions/TxStatusLabel/index.tsx
- src/components/tx-flow/flows/ConfirmTx/index.tsx
- src/features/swap/components/SwapOrder/index.tsx
- src/features/swap/components/SwapOrder/swap.stories.tsx
- src/features/swap/components/SwapOrder/twap.stories.tsx
- src/features/swap/components/SwapProgress/index.tsx
- src/features/swap/components/SwapTxInfo/SwapTx.tsx
- src/features/swap/components/SwapTxInfo/interactWith.tsx
- src/features/swap/helpers/swapOrderBuilder.ts
- src/features/swap/helpers/utils.ts
- src/features/swap/hooks/useIsExpiredSwap.ts
- src/features/swap/index.tsx
- src/features/swap/store/swapParamsSlice.ts
- src/hooks/useTransactionStatus.ts
- src/hooks/useTransactionType.ts
- src/services/analytics/tx-tracking.ts
- src/store/swapOrderSlice.ts
- src/tests/mocks/chains.ts
- src/tests/mocks/transactions.ts
- src/utils/transaction-guards.ts
- yarn.lock
Resolves #
https://www.notion.so/safe-global/76f265123c0a4ad680947ce489804342?v=17c30f9503cd4d48a622209408de56d6&p=0f273a0f06f2465589628c7299f44e05&pm=s
Create a twap order throw the native swap feature.
> Feat: TWAP order decoding in tx history/queue [SW-1]

- src/components/tx/SignOrExecuteForm/hooks.test.ts
- src/components/tx/SignOrExecuteForm/hooks.ts
Updates `useRecommendedNonce` for 1/1 Safes that execute a transaction directly. 
Fetched the recommended nonce when the safe's `txHistoryTag` changes.
Reason being that 1/1 Safe transactions that get executed immediately never hit the queue and thus do not update the `txQueuedTag`.
Adds a unit test for `useRecommendedNonce`
- Open a 1/1 Safe with an empty queue
- Create a transaction and execute it immediately
- Quicky create a second transaction and wait in the tx modal for the first one to finish
- The nonce should automatically get updated to the next one once the first tx gets indexed if the nonce has not been changed manually
> fix: update recommendedNonce when history tag changes

- src/components/safe-messages/MsgListItem/ExpandableMsgItem.tsx
It will remove the border from the transactions in Messages tab.
Issue #3871
Resolves # 3871
The `sx` prop is part of the MUI system, which allows you to apply styles to components directly I have put the border to none there.
I have put code I below the `Accordion` element, which will remove the border and ensure that the pseudo-element is also removed.
```
sx={{ border: 'none', '&:before': { display: 'none' } }}
```
you can visit `https://app.safe.global/transactions/messages?safe=eth:0xA77DE01e157f9f57C7c4A326eeE9C4874D0598b6` URL where you will use list of transaction without border.
* [Done] I've tested the branch on mobile 📱
* [No] I've documented how it affects the analytics (if at all) 📊
* [No(Not applicable)] I've written a unit/e2e test for it (if applicable) 🧑‍💻
> removed border from messages txs

- src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx
- src/utils/formatNumber.ts
The wrong number formatting function was called in SingleTxDecoded. It resulted in double formatting which failed in locales where the decimal separator is a comma (e.g. pt-PT).
* Set your browser language to Portuguese (Portugal)
* Go to tx history and expand a multisend transaction containing fractional amount transfers
* In prod: they would be displayed as NaN
* On this branch: they are displayed correctly
> Fix: wrong number formatting in SingleTxDecoded

- package.json
- src/components/transactions/BulkTxListGroup/index.tsx
- src/components/transactions/TxDetails/index.tsx
- src/components/transactions/TxDetails/styles.module.css
- src/features/swap/components/SwapOrder/index.tsx
- src/hooks/useTransactionType.ts
- src/utils/transaction-guards.ts
- yarn.lock
Displays swap info on sent/receive events
sent/receive events that are created in response to a swap order should display additional info about the swap
> Display swap info on sent/receive events [SW-3]

- src/components/settings/FallbackHandler/index.tsx
- src/features/swap/helpers/utils.ts
Resolves [SW-33](https://www.notion.so/safe-global/CoW-s-fallback-handler-99044779a28d46cfb69552103bee6e68)
- Checks if the fallback handler is cows fallback handler for TWAPs and displays a message instead of the unofficial fallback handler warning
- Removes the check icon and adjusts the spacing according to Figma design
1. Open a Safe that has TWAP enabled
2. Go to Settings -> Modules
3. Observe a green message above the fallback handler address
> fix: Display cow fallback handler message [SW-33]

- src/features/swap/components/SwapTxInfo/SwapTx.tsx
We were displaying wrong amount in the queue and history when the user was making a buy order.
1. Create a buy order
2. in queue and history you should see "{sell token icon} to {buy token icon} {amount buy token}"
> Fix buy order [SW-50]

- src/components/safe-apps/SafeAppList/index.tsx
Resolves #3887
- Hides the native swaps card in the custom apps list
1. Open the custom apps list
2. Observe no native swaps card
> fix: Hide native swaps card from custom apps list

- src/components/tx/SignOrExecuteForm/index.tsx
- src/features/swap/components/TwapFallbackHandlerWarning/index.tsx
- src/features/swap/helpers/__tests__/utils.test.ts
- src/features/swap/helpers/utils.ts
If the user is submitting a TWAP order for the first time he would most probably need to change his safe's fallback handler. Whenever we detect this we now show a warning:
Resolves #
Try to create a TWAP order on a safe that has the standard fallback handler. The first tx should display the warning in the screenshot.
> feat: add a warning if changing the fallback handler [SW-53]

- src/components/transactions/TxDetails/TxData/Transfer/index.test.tsx
- src/components/transactions/TxDetails/TxData/Transfer/index.tsx
We currently do not show the "Before you copy" confirmation modal for transactions using real tokens to perform address poisoning.
Show the Copy modal warning for transactions that are detected as imitations but use trusted tokens.
Open a Safe with an address poisoning attempt using a real token (e.g. USDC)
> fix: address poison copy confirmation modal

- cypress/e2e/happypath/sendfunds_relay.cy.js
- cypress/e2e/pages/main.page.js
- cypress/support/constants.js
- Add check for remaining relay attempts in tests
> Tests: Add relay check

- src/features/swap/components/SwapOrderConfirmationView/OrderFeeConfirmationView.tsx
- src/features/swap/components/SwapOrderConfirmationView/index.tsx
Don't display a widget fee on the confirmation screen if it the feature is the order doesn't have any widget fee applied
You would need access to config server. Disable widget fee. Make a swap, on the confirmation view you shouldn't see a fee.
> fix: don’t display widget fee, if it is not on [SW-64]

- src/features/swap/index.tsx
Adds a title to the execute transaction screen when cancelling a limit order
> Fix: Add title for limit order cancellations [SW-68]

- src/components/transactions/TxSummary/index.tsx
Our previous address poisoning and spam protection made transactions slightly opaque in the history to help users quickly distinguish them.
The new address poisoning flagging does not make them opaque at the moment.
- Makes txs opaque for imitations as well
Find a Safe with transactions that only get flagged through our new detection: Address poisoning attempts which actually transfer legit tokens.
Before:
After:
> fix: mark imitation txs opaque

- package.json
- yarn.lock
The CoW widget was not properly updating AppData in some situations. This widget release includes the fix for this:
https://github.com/cowprotocol/cowswap/pull/4670
click the link in the fee tooltip
it opens inside of the iframe, hit back. Make your swap tx and proceed to the confirm transaction screen - with this PR the tx should now be decoded.
> chore: update cowprotocol/widget-react

- src/features/swap/components/SwapOrder/rows/SurplusFee.tsx
For buy orders the fee was being displayed in the wrong token.
- For both buy and sell orders, the fee is displayed in the sell token.
- Also fixes some formatting in the fee tooltip text.
- Go to a buy order with fees, [example](https://release--walletweb.review.5afe.dev/transactions/tx?safe=sep:0x8f4A19C85b39032A37f7a6dCc65234f966F72551&id=multisig_0x8f4A19C85b39032A37f7a6dCc65234f966F72551_0x7175d1355f355353403449f68b14229cbf9ecc8291baa431753ac0a5efdb36e6)
- See that the fee is displayed with the correct token and amount. It should match the cowswap order.
> Fix: display swap fees using the correct token [SW-67]

- src/features/swap/components/LegalDisclaimer/index.tsx
Second usage of terms in the disclaimer had to also be a link to the terms page.
> Fix terms [SW-43]

- src/features/swap/components/SwapTxInfo/SwapTx.tsx
For buy orders we were only showing the sell token icon, but not the sell token name
Resolves #
Make a buy order and you should now in the queue/history see the sell token name.
> fix: sell tooken was not being shown [SW-76]

- src/components/balances/AssetsTable/index.tsx
- src/components/sidebar/SidebarNavigation/index.tsx
- src/features/counterfactual/CounterfactualForm.tsx
- src/features/counterfactual/FirstTxFlow.tsx
- src/features/counterfactual/hooks/usePendingSafeStatuses.ts
- src/features/counterfactual/utils.ts
Cow was not being able to work with counterfactual safes - it was showing the widget as not connected. 
Resolves #
Now the widget is connected to the safe and one can submit an order.
1. Create counterfactual safe
2. Fund it with money
3. Try to make a swap
1. Create a safe and deploy it right away
2. Create counterfactual safe and activate it without a transaction
> fix: re-enable swaps for counterfactual safes [SW-23]

- src/features/swap/components/SwapOrderConfirmationView/OrderFeeConfirmationView.tsx
Adjusts the tooltip in the order confirmation view to match the widget one.
> Fix: swap tooltip

- src/features/swap/helpers/data/stablecoins.ts
USDT is missing from the stablecoins array on arbiturm and because of this we apply wrong fee for stablecoin swaps
1. Open the swaps widget with an arbitrum safe - try to swap USDT for another stable -> you should get the stable rates for the swap.
> fix: usdt missing from stablecoins array on arbitrum

- src/components/notification-center/NotificationCenter/index.tsx
Resolves #3810 
- I don't think this fixes the root of the problem which has something to do with having an `onClick` handler in a nested `NextLink` but it rerenders the `Popover` whenever the `open` state changes which also solves the issue
1. Create a transaction
2. Open the transaction detail page
3. Open the notification center
4. Press "View transaction"
5. Observe that the UI is still clickable
> fix: Close notification center when a notification is opened

- src/components/common/Header/index.tsx
- src/components/common/Header/styles.module.css
Resolves #3251 
- Only displays the burger menu if `onMenuToggle` is passed to `Header`
1. Open the welcome page or any other route where there is no sidebar
2. Decrease the viewport width
3. Observe no burger menu appearing in the header
> fix: Hide burger menu on non-sidebar routes

- src/components/common/AddressBookInput/index.tsx
Resolves #3826 
- Hides the Add to address book icon in the address input field if an address already exists in the address book
1. Open a Safe
3. Select a recipient from the address book
4. Observe there is no icon button next to the address
5. Type in an address thats not in the address book yet
6. Either press the icon next to the address or the link below the input field
7. Observe that the address is pre-populated in the form
> fix: Hide add to address book button if address already in address book

- package.json
- yarn.lock
Bump [`safe-deployments`](https://github.com/safe-global/safe-deployments) from `v1.36.0` to `v1.37.1` so teams that recently deployed Safe{Core} on their new chain can run safe-wallet-web properly.
Resolves # N/A
N/A
Make sure that recent network deployments are included in the package `node_modules/@safe-global/safe-deployments/dist/assets/v1.x.x/xxxxxx.json` (e.g L3X testnet | ChainID: `12325`)
N/A
> Bump safe-deployments from 1.36.0 to 1.37.1

- src/components/tx/SignOrExecuteForm/index.tsx
- src/features/swap/helpers/utils.ts
When valueDecoded isn't an array, it crashes the whole page. Our types apparently are wrong for this object.
Sentry: https://safe-global-eu.sentry.io/issues/2398958/?project=4507215200256080&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=5
> Fix: valueDecoded must be an array

- src/services/safe-wallet-provider/useSafeWalletProvider.test.tsx
- src/services/safe-wallet-provider/useSafeWalletProvider.tsx
We were showing the wrong type of the native confirmation popup.
> Fix: prompt -> confirm

- src/services/private-key-module/index.ts
This fixes the Private Key signer wallet in e2e tests, specifically transaction deletion.
JSON parse wasn't necessary.
> Tests: fix tx deletion

- src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx
- src/components/transactions/TxDetails/TxData/DecodedData/index.tsx
- src/components/tx-flow/flows/NewSpendingLimit/ReviewSpendingLimit.tsx
- src/components/tx-flow/flows/RemoveSpendingLimit/RemoveSpendingLimit.tsx
- src/components/tx-flow/flows/TokenTransfer/ReviewSpendingLimitTx.tsx
- src/components/tx-flow/flows/TokenTransfer/ReviewTokenTransfer.tsx
- src/components/tx-flow/flows/TokenTransfer/SendAmountBlock.tsx
- src/components/tx/DecodedTx/index.tsx
- src/utils/__tests__/formatters.test.ts
- src/utils/formatters.ts
On some locales native values are displayed as NaN.
Always uses `safeFormatUnits` instead of `formatVisualAmount` before passing the value to `SendAmountBlock`
1. On firefox open the tx builder Safe app
2. Enter any EOA address as `to` address
3. Enter a big amount (e.g. 123456789 - your Safe does not need to actually hold this amount as we just want to see the decoding)
4. Witness `NaN` on prod but now the correct amount in this PR deployment
> fix: correctly format native transfer amounts

- src/components/tx/ErrorMessage/index.tsx
Resolves #3935
Ethers adds `could not coalesce error` in the beginning of error messages which isn't useful to the user. This PR simply cuts it off.
> Fix: remove "could not coalesce error" prefix from error messages

- cypress/fixtures/txhistory_data_data.json
- src/components/transactions/TxInfo/index.tsx
Resolves #3198
I removed the redundant part from the tx summary.
> Fix: avoid duplication in Safe creation tx summary

- src/components/tx/SignOrExecuteForm/PermissionsCheck/__test__/PermissionsCheck.test.tsx
- src/services/safe-wallet-provider/useSafeWalletProvider.test.tsx
- src/tests/mocks/chains.ts
The PermissionsCheck tests were doing actual fetch requests to a gas oracle which sometimes failed on CI. Fetch is now mocked to return an empty object.
> Tests: mock fetch in PermissionsCheck tests

- src/features/counterfactual/hooks/usePendingSafeStatuses.ts
- src/features/counterfactual/services/safeCreationEvents.ts
- src/features/counterfactual/utils.ts
- src/services/safe-wallet-provider/useSafeWalletProvider.test.tsx
This fixes a regression that was introduced in #3778
#3778 consolidated the logic of counterfactual and normal safe deployment and as such removed existing hooks like `useSafeCreationEffects`. This hook contained the logic to emit a `CREATED_SAFE` event on successful creation.
This PR adds this back for normal safe deployments. For counterfactual safe deployments this event is emitted immediately which is as expected.
1. Create a safe and choose pay now
2. Observe a `CREATED_SAFE` event after successful deployment
> fix: Add CREATED_SAFE event back for normal safe creation

- src/components/common/Table/styles.module.css
Resolves #2682 
- Adds `overflow-x: auto` property to `DataRow` component
1. Create a swap on Curve
2. Observe the tx details in the review screen can be fully viewed by scrolling
3. The `TxDataRow` / `DataRow` component is also used for Swaps, TxSummary, MsgDetails, RecoveryDetails. Make sure these places still work as expected
https://github.com/safe-global/safe-wallet-web/assets/5880855/d19435a6-8df8-4f34-b07f-e136b8f1ef0d
> fix: Make transaction details scrollable during creation

- src/components/common/TxModalDialog/index.tsx
- src/services/safe-wallet-provider/useSafeWalletProvider.test.tsx
Cannot use keyboard scroll in the tx modal.
Resolves #2690
- Wrap the dialog contents in the DialogContent and DialogContentText components to get the default MUI modal behaviour.
- Create a transaction with many steps (https://github.com/safe-global/safe-wallet-web/issues/2690#issuecomment-1945821479)
- Open the tx modal. Focus on the modal (click or tab).
- Scroll using the arrow buttons should work. Scrolling to the end of the page using `CMD`+`down` or `end` should also work.
> Fix: allow keyboard scrolling for in Dialog

- src/components/common/OnboardingTooltip/index.tsx
Resolves #3798 
- Adds `disablePortal` to the Tooltip element so that it is not rendered at the top of the DOM anymore
- Adds a `minWidth` to its text to make the tooltip a bit wider again
1. Open a Safe with a clean local storage
2. Go to Assets
3. Observe the tooltip showing
4. Press Create transaction
5. Observe the tooltip is not visible anymore
> fix: Hide onboarding tooltip behind transaction modal

- .github/workflows/deploy-dev.yml
- .github/workflows/e2e-regression.yml
- .github/workflows/e2e-safe-apps.yml
- .github/workflows/e2e-smoke.yml
- .github/workflows/nextjs-bundle-analysis.yml
- .github/workflows/unit-tests.yml
Github actions on forks fail, because they require secrets that are not available. By relying on pull_request_target maintainers will be able to start those action workflows and they shouldn’t fail.
From the [github docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target):
This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the pull_request event does. This prevents execution of unsafe code from the head of the pull request that could alter your repository or steal any secrets you use in your workflow. This event allows your workflow to do things like label or comment on pull requests from forks.
With this we should be able to manually run actions on github PR from forks. This …
> Chore: switch to pull_request_target

- .github/workflows/deploy-dev.yml
- .github/workflows/e2e-regression.yml
- .github/workflows/e2e-safe-apps.yml
- .github/workflows/e2e-smoke.yml
- .github/workflows/nextjs-bundle-analysis.yml
- .github/workflows/unit-tests.yml
Reverts safe-global/safe-wallet-web#3966
We didn't achieve the expected outcome. It turned out that code from the PR was completely ignored and instead the base branch was used for the deployment.
> Revert "Chore: switch to pull_request_target"

- src/components/transactions/TxType/index.tsx
- src/hooks/useTransactionType.tsx
In the transaction summary, the swap icon is black in dark mode.
- Use MUI SvgIcon to render the swap icon so that it changes color according to the theme.
- Find or create a swap transaction in the tx history.
- See the the icon is the correct color in both light and dark mode. Make sure the other tx icons are unaffected.
> Fix: make swap icon white in dark mode [SW-81]

- src/components/balances/AssetsTable/index.tsx
- src/components/common/EnhancedTable/index.tsx
- src/components/transactions/TxDetails/styles.module.css
Visually align columns and headers in the assets table.
Before:
After:
> Fix: align assets table

- src/components/transactions/HexEncodedData/index.tsx
Makes small adjustments to HexEncodedData:
- Tooltip explaining why first 10 chars are highlighted
- Uses the FieldGrid component for the title
Before:
After:
> feat: redesign HexEncodedData

- src/pages/terms.tsx
- src/store/cookiesAndTermsSlice.ts
Section 18 had repeated content.
Also fixes reference mistakes.
Requested by legal
> Fix: add correct contents to section 18 of terms page

- src/hooks/loadables/useLoadSpendingLimits.ts
Part of #2414 
- `getSpendingLimits` was called twice because the condition only checked for the existence of `tokenInfoFromBalances` but the initial value is an empty array so it should check the length of the array instead
1. Open a Safe with a spending limit
2. It should still be visible under settings and when trying to create a transaction
> fix: Harden condition for loading spending limits

- src/components/common/TxModalDialog/index.tsx
Resolves #3985 
- Changes the dialog element to a `div` to resolve react errors
- Explicitely adds `text.primary` as color for this element so that child elements inherit it
1. Open a Safe
3. Observe the title and network name are readable
> fix: Use text color for tx dialog content element

- src/components/common/FiatValue/index.tsx
- src/components/common/TokenAmount/index.tsx
- src/components/transactions/TxInfo/index.tsx
- src/features/swap/components/SwapOrder/index.tsx
- src/features/swap/components/SwapTxInfo/SwapTx.tsx
- src/utils/formatNumber.ts
Resolves #3978
Show precise full token and fiat amounts on hover.
> Feat: full amount tooltip

- src/components/tx-flow/flows/RemoveSpendingLimit/RemoveSpendingLimit.tsx
Resolves #3992
- The amount when removing a spending limit is already in wei so no need to parse it
1. Open a safe with a spending limit
2. Remove the spending limit
3. Observe the amount is shown correctly
> fix: Don't parse amount when removing spending limit

- src/components/transactions/TxDetails/index.tsx
Resolves #4000
Fixes a regression introduced in #3893 
- Adds back the `swapOrder` class to the wrapper element
1. Open a Safe with a TWAP order in the history or queue
2. Observe there is padding in the tx details
> fix: Add padding to swap tx details

- src/features/swap/components/SwapButton/index.tsx
- src/features/swap/index.tsx
Tokens can end up having the same token abbreviation, but they always have different token addresses. If the user select a token that has the same abbreviation as another token in the list the widget starts flickering between the selected tokens and resets to WETH for input token and no selected output token. By opting to use addresses instead the problem seems to be resolved.
Go to the swaps page.
For source token select: USDC
for target token select: APE
Without this commit the token selection will flicker and would reset to WETH for source token and nothing for output token. With this PR source token would be USDC and target token would be the APE token selected.
> fix: swap token selection flickers

- package.json
- src/features/counterfactual/store/undeployedSafesSlice.ts
- src/hooks/useDraftBatch.ts
- src/hooks/usePendingTxs.ts
- src/services/safe-wallet-provider/useSafeWalletProvider.test.tsx
- src/store/__tests__/swapOrderSlice.test.ts
- src/store/batchSlice.ts
- src/store/broadcast.ts
- src/store/common.ts
- src/store/index.ts
- src/store/pendingTxsSlice.ts
- src/store/persistStore.ts
- yarn.lock
While I was tracking why a component re-renders I found out that it is due to a reducer always returning a new array. Those kind of errors should actually be reported in dev mode, but our version of redux-tookit was not doing that. After I quickly looked at the changelog it seemed that the relevant code for this was added in redux tookit version 5, but we were on 4. 
I had to bite the bullet and do the update. I did try to do this in the past, but back then didn't want to deal with the type problems this update was bringing with it... Now I no longer had a choice. :)
> Refactor: update react-redux and redux-toolkit to latest versions

- src/components/welcome/MyAccounts/styles.module.css
Resolves #3970
- Stack the balance underneath the address for smaller screens
- open the safe list in the sidebar or the accounts page
- resize the screen to be < 500px
- See that the address and balance are displayed on top of one another.
> fix: account list address and balance are misaligned for smaller screens

- src/components/common/TokenAmount/index.tsx
Resolves [RC comment](https://github.com/safe-global/safe-wallet-web/pull/4012#issuecomment-2259523123)
- Adds the same decimals check for computing the `fullAmount` as is present for `amount`
1. Create a new Safe
2. Observe no formatting units error in the console after creation
> fix: format value in sidebar only if decimals exist

- .github/workflows/cypress/action.yml
- .github/workflows/e2e-hp-ondemand.yml
- .github/workflows/e2e-ondemand.yml
- .github/workflows/e2e-regression.yml
- .github/workflows/e2e-safe-apps.yml
- .github/workflows/e2e-smoke.yml
- Add tags to test types in workflows.
> Tests: Add tags to test types

- package.json
- src/hooks/coreSDK/__tests__/safeCoreSDK.test.ts
- src/hooks/coreSDK/safeCoreSDK.ts
- yarn.lock
Safe deployments 1.37.2 adds canonical deployment addresses.
Those are used when i.e. replaying a 1.3.0 L1 Safe on a L2 chain and on some networks such as Optimism they are not detected currently.
- Updates safe-deployments
- Also accepts the canonical L1 master copy address
- Open a replayed 1.3.0 L1 Safe on e.g. Optimism
> fix: accept canonical mastercopy

- src/features/swap/hooks/useIsExpiredSwap.ts
The Hook was using IntervalCounter and despite the state of the hook not changing, the interval counter was being updated, which in turn caused every component using this hook to rerender.
Since this hook is used in TXSummary it meant that the whole TX History or TX Queue were rerendered every 10s degrading the performance.
No unnecessary rerenders every 10s
Easiest way to see the improvement is to use the react devtools extension and make sure that "highlight updates when component render" is turned on. Without the fixes in this PR you will see the History page constantly rerenering
> fix: useIsExpiredSwap causing too many rerenders

- .github/workflows/cypress/action.yml
- .github/workflows/e2e-ondemand.yml
- .github/workflows/e2e-smoke.yml
- Update to Cypress v.13.13.1
- Add timeouts to test runs to avoid pending tests for a long time
> Tests: Set specific cypress version

- src/components/tx-flow/flows/RecoverAccount/RecoverAccountFlowReview.tsx
- src/components/tx/SignOrExecuteForm/TxChecks.tsx
- src/components/tx/SignOrExecuteForm/index.tsx
Resolves #3584
- Hides the Transaction checks block if both redefine and simulation flags are disabled
1. Open a safe on a network without stransaction checks like zksync era
3. Observe no Transaction checks block
> fix: Hide transaction checks block if features are disabled

- cypress/e2e/regression/swaps.cy.js
- cypress/e2e/safe-apps/apps_list.cy.js
- cypress/e2e/safe-apps/drain_account.spec.cy.js
- cypress/e2e/safe-apps/preview_drawer.cy.js
- cypress/e2e/safe-apps/safe_permissions.cy.js
- cypress/e2e/safe-apps/tx-builder.spec.cy.js
- cypress/e2e/safe-apps/tx_modal.cy.js
- cypress/support/safe-apps-commands.js
- Add cookie acceptance via local storage
- Increase swap value to avoid insufficient balance when swapping 
> Tests: Update cookies acceptance in safe apps

- src/components/transactions/TxDetails/index.tsx
- src/components/tx/FieldsGrid/index.tsx
A follow-up on #3967.
Moved multisend to the very bottom (like it was before) and fixed the "To" field wrapping on small screens.
> Fix: multisend position in tx details; "to" field wrapping on small screens; 

- src/components/common/FiatValue/FiatValue.test.tsx
- src/components/common/FiatValue/index.tsx
- src/components/dashboard/Overview/Overview.tsx
- src/utils/__tests__/formatNumber.test.ts
- src/utils/formatNumber.ts
A bit of extra precision in the total asset value.
> Feat: total asset value cents in grey

- src/hooks/wallets/web3.ts
Issues with Scroll network due to a too high RPC batch size
Reduces the RPC batch size from 10 to 3.
- Use scroll network
> fix: reduce rpc batch size

- cypress/e2e/prodhealthcheck/add_owner.cy.js
- cypress/e2e/prodhealthcheck/create_tx.cy.js
- cypress/e2e/prodhealthcheck/load_safe.cy.js
- cypress/e2e/prodhealthcheck/messages_onchain.cy.js
- cypress/e2e/prodhealthcheck/nfts.cy.js
- cypress/e2e/prodhealthcheck/remove_owner.cy.js
- cypress/e2e/prodhealthcheck/sidebar.cy.js
- cypress/e2e/prodhealthcheck/sidebar_3.cy.js
- cypress/e2e/prodhealthcheck/spending_limits.cy.js
- cypress/e2e/prodhealthcheck/swaps_history_2.cy.js
- cypress/e2e/prodhealthcheck/swaps_tokens.cy.js
- cypress/e2e/prodhealthcheck/tokens.cy.js
- cypress/e2e/prodhealthcheck/tx_history.cy.js
- cypress/e2e/prodhealthcheck/tx_history_2.cy.js
- cypress/e2e/regression/add_owner.cy.js
- cypress/e2e/regression/messages_onchain.cy.js
- cypress/e2e/regression/replace_owner.cy.js
- cypress/e2e/regression/sidebar_3.cy.js
- cypress/e2e/regression/spending_limits.cy.js
- cypress/e2e/regression/swaps_history_2.cy.js
- cypress/e2e/regression/tokens.cy.js
- Add Cypress tests for production health check runs
- Skip one of the tests in replace owner suite, relevant [task](https://www.notion.so/safe-global/Regression-suite-Maintenance-for-the-skipped-replace-owner-tests-c49be23086884cad8479402702502df2?pvs=4)
> Tests: Add production tests

- cypress/e2e/prodhealthcheck/swaps_tokens.cy.js
- There is some flakiness in a test showing unexpected number. Skipping this for now. Will be solved later. 
> Tests: Skip failing test

- src/hooks/wallets/wallets.ts
We now run [scheduled tests in production](https://github.com/safe-global/safe-wallet-web/pull/4049), and these tests require the Private Key wallet module that's been only available on dev so far.
I've removed the `IS_PROD` check so that we can control this wallet via the config service like other wallets, and enable this module on prod Sepolia.
> Tests: enable PK module for tests in prod

- src/features/walletconnect/__tests__/WalletConnectContext.test.tsx
- src/features/walletconnect/components/WalletConnectProvider/index.tsx
Resolves #4043
To the app, it doesn't matter what URL is being sent in the `origin` of WC-initialted tx proposals. The old WC Safe App doesn't exist anymore, so CGW won't match these txs to anything.
But it matters for data analysis on the backend, so we're restoring the behavior unintentionally altered in #3760.
* Create any transaction via WalletConnect
* Filter the Network Requests in devtools by "propose"
* Observe that the `origin` field in the propose request is set to `https://apps-portal.safe.global/wallet-connect`
> Analytcs: restore WalletConnect tx origin

- src/components/tx-flow/flows/TokenTransfer/ReviewSpendingLimitTx.tsx
- src/components/tx/SignOrExecuteForm/ExecuteThroughRoleForm/index.tsx
- src/components/tx/SignOrExecuteForm/index.tsx
- src/services/analytics/events/transactions.ts
- src/services/analytics/types.ts
Role-based executions were previously tracked as separate events preceding a `tx_executed` event but it's more inline with our existing events to track them as `tx_executed` with a custom `eventAction`.
Edit: extended the same to spending limit transactions.
* Make a token transfer using Spending Limits
* In the console, the `tx_created` and `tx_executed` events should have a `Created/Executed via spending limit` action
* Create a Roles-based tx and execute it
* In the console, the `tx_created` and `tx_executed` events should have a `Created/Executed via role` action
> Analytcs: execution via role event

- src/components/tx/DecodedTx/index.tsx
- src/components/tx/FieldsGrid/index.tsx
1. Restore "native transfer" in the Advanced details title:
2. Wrap "Interacted with" to the next line if it doesn't fit:
> Fix: restore "native transfer"; wrap "Interacted with"

- src/components/tx/DecodedTx/index.tsx
- src/components/tx/FieldsGrid/index.tsx
- src/components/tx/SignOrExecuteForm/index.tsx
Fixes for the issues reported [on notion](https://www.notion.so/safe-global/Tx-details-redesign-issues-ef226c9c47f04e4d8c7c891886a66985).
1. The method call details are moved to the Advanced details for approvals:
2. Restore "native transfer" in the Advanced details title:
3. Wrap "Interacted with" to the next line if it doesn't fit:
> Fix: tx-details redesign fixes

- src/components/new-safe/create/AdvancedCreateSafe.tsx
- src/components/new-safe/create/index.tsx
- src/components/new-safe/create/steps/StatusStep/index.tsx
- src/utils/chains.ts
Safe creation was broken for chains without 1.4.1 deployed.
- Removes `LATEST_SAFE_VERSION` usage and replaces it with `getLatestSafeVersion`
- Create a Safe on e.g. zkSyncEra (Pay later suffices)
> fix: safe creation for chains without 1.4.1 deployed

- src/components/welcome/MyAccounts/AccountItem.tsx
- src/components/welcome/MyAccounts/styles.module.css
A small fix for long Safe names that weren't truncated.
> Fix: ellipsis for Safe names

- cypress/support/utils/wallet.js
Smoke tests were failing because the connect wallet action was finding more than one Connect button.
> Tests: fix create_safe_simple

- package.json
- yarn.lock
Resolves #4061 
Upgrades Zodiac to 4.0.3
- Enable Recovery on Base (Feature flag)
- Test recovery
> feat: upgrade zodiac to enable recovery on Base

- src/components/new-safe/create/logic/index.test.ts
- src/components/new-safe/create/logic/index.ts
- src/components/new-safe/create/steps/StatusStep/index.tsx
Limits redirects to known URLs.
The redirect was introduced here: #519 – to allow creating a Safe from a Safe App share URL and then going back to that Safe App.
* Open a share link of any Safe App, e.g. https://app.safe.global/share/safe-app?appUrl=https%3A%2F%2Fsafe-eth.everstake.one%2F&chain=eth
* Connect a wallet that doesn't have Safes on that chain
* Click on Create new Safe Account
* Complete a Safe creation
* You'll be redirected back to that Safe App
> Fix: limit safeViewRedirectURL redirects to Safe App URLs

- src/config/securityHeaders.ts
Resolves #4079
The previously used syntax doesn't work for URLs with a port specified.
Try to open a localhost URL as a Safe App.
> Fix: allow Safe Apps from localhost:<port>

- src/features/walletconnect/components/WcProposalForm/ProposalVerification.tsx
As requested by WalletConnect, we should not show `has been verified by WalletConnect` as it's not 100% bullet-proof. See https://docs.walletconnect.com/walletkit/web/verify#disclaimer
So from now on, we'll be showing only if a dApp is a known scam or there's a domain mismatch.
> Fix: don't show "verified by WalletConnect"

- public/images/sidebar/multichain-account.svg
- src/components/common/SafeIcon/index.tsx
- src/components/welcome/MyAccounts/AccountItem.tsx
- src/components/welcome/MyAccounts/MultiAccountItem.tsx
- src/components/welcome/MyAccounts/PaginatedSafeList.tsx
- src/components/welcome/MyAccounts/SubAccountItem.tsx
- src/components/welcome/MyAccounts/index.tsx
- src/components/welcome/MyAccounts/styles.module.css
- src/components/welcome/MyAccounts/useAllSafesGrouped.ts
- src/components/welcome/MyAccounts/useGetHref.ts
- src/components/welcome/MyAccounts/useTrackedSafesCount.ts
- src/components/welcome/MyAccounts/utils/multiChainSafe.test.ts
- src/components/welcome/MyAccounts/utils/multiChainSafe.ts
- src/features/counterfactual/store/undeployedSafesSlice.ts
- src/services/analytics/events/overview.ts
- src/store/common.ts
Groups Safes with the same address in the sidebar.
- Create Safes with the same address on some networks.
- Check and observe the sidebar:
- Multichain Safes should appear first
- The "add network" button has no function yet. It will be added in the PR that implements the action!
> feat: show multichain accounts in sidebar

- src/components/transactions/Warning/index.tsx
The contents of the delegate call warning weren't center-aligned which drove me crazy.
> Fix: (css) center-align delegate warning

- .github/workflows/cla.yml
- src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
Resolves #
https://github.com/safe-global/safe-wallet-web/issues/4142
It adds correct sizes for the MUI screen variations (sm, xs, md, lg and xl)
1) Go to a safe you own 1/1
2) Create a tx and go to the "Confirm transaction" modal screen
> fix: put execute button to be full width on mobile display

- src/features/swap/index.tsx
- src/pages/swap.tsx
Resolves #4144
The sell token query parameter wasn't properly pass to the Swaps widget. It will now update the widget params when the URL query becomes available.
> Fix: (Swaps) sell token reactivity

- src/components/transactions/HexEncodedData/HexEncodedData.test.tsx
- src/components/transactions/HexEncodedData/__snapshots__/HexEncodedData.test.tsx.snap
- src/components/transactions/HexEncodedData/index.tsx
- src/components/transactions/TxDetails/Summary/TxDataRow/index.tsx
- src/components/transactions/TxDetails/TxData/DecodedData/ValueArray/index.tsx
Resolves #4136
A new property called `highlightFirstBytes` was added in to the `<HexEncodedData />`component, where we can explicitly say where we wish to have the highlight or not. I've added it as default `true` because the default behaviour of this component was supposed to be highlighted and also we do not need to go across the entire application and set the highlight as true. 
Create any raw undecoded data transaction, and you'll see the highlight still exists, and for any type of hex-bytes it is not highlighted.
> Highlight raw data transactions

- src/hooks/safe-apps/useAppsSearch.ts
Resolves #4088
It adds the tags property from the apps array into the fusion constructor parameters.
Type the category you want to search in the safe apps search bar and you'll have the apps filtered not only by the name or description but also category.
> fix: Consider app category in the searchbar query filter

- src/components/tx/SignOrExecuteForm/index.tsx
- src/hooks/useDecodeTx.ts
Resolves #4119
This problem was happening because the call to get the `decodedData` is an asynchronous call which uses the `useAsync` hook. This `useAsync` hook was clearing the data everytime the component re-renders, what was making the component who presents the decoded transaction details (`<DecodedTx />`) to be unmounted. Diving in the three of this component and its dependencies, I found we have a parameter in the `useAsync` hook, which was added specially to avoiding cleaning the data after the consumer is re-rendered, and the default behaviour of it is to clear the data. 
The solution was to simply provide this parameter in the execution of `useAsync` hook inside the `useDecodeTx` hook, and also just show the `<DecodedTx />` component once the `decodedData` exists.
1) Go to the …
> fix: avoid blinking screen in the confirmation modal view

- cypress/e2e/prodhealthcheck/tx_history.cy.js
- cypress/e2e/prodhealthcheck/tx_history_2.cy.js
- cypress/e2e/regression/tx_history.cy.js
- cypress/e2e/regression/tx_history_2.cy.js
- cypress/support/utils/txquery.js
- package.json
- src/services/transactions/index.tests.ts
- src/services/transactions/index.ts
- src/utils/__tests__/tx-history-filter.test.ts
- src/utils/tx-history-filter.ts
- yarn.lock
Removes deprecated timezone_offset, Adds `timezone` as a replacement.
Resolves
https://github.com/safe-global/safe-client-gateway/issues/1024
A new query parameter, timezone, has been introduced. This parameter accepts only valid timezone strings (e.g., Europe/Berlin) and supersedes the deprecated timezone_offset, which previously accepted a numeric timezone difference.
- Review the transaction history list.
- Make sure the transactions are listed with the correct time and date, and verify that they are grouped by day properly.
- Ensure that transactions occurring around midnight are not mistakenly assigned to the following day.
For more info please visit https://github.com/safe-global/safe-client-gateway/issues/1024
> Refactor: replace deprecated timezone_offset parameter with timezone

- src/components/transactions/MaliciousTxWarning/index.tsx
- src/components/transactions/TxDetails/TxData/Transfer/index.test.tsx
Make the unverified token tooltip a little bit clear that it's based on 3rd-party token lists.
> Fix: update unverified token warning

- src/components/common/Chip/index.tsx
A CSS regression from #4154. The New chip shouldn't be `position: absolute`.
> Fix: "New" chip positioning

- package.json
- src/components/transactions/TxDetails/TxData/index.tsx
- src/components/transactions/TxInfo/index.tsx
- src/features/stake/components/StakingConfirmationTx/Withdraw.tsx
- src/features/stake/components/StakingConfirmationTx/index.tsx
- src/features/stake/components/StakingTxDepositInfo/index.tsx
- src/features/stake/components/StakingTxWithdrawDetails/index.tsx
- src/features/stake/components/StakingTxWithdrawInfo/index.tsx
- src/features/stake/components/StakingWidget/index.tsx
- src/features/stake/helpers/utils.ts
- src/hooks/useTransactionType.tsx
- src/services/tx/extractTxInfo.ts
- src/utils/transaction-guards.ts
- yarn.lock
Ads decoding views for stake claim txs
Resolves #
> Feat: staking claim [SW-160]

- src/components/tx-flow/common/TxLayout/index.tsx
- src/components/tx-flow/common/TxLayout/styles.module.css
Resolves 
release blocker: https://github.com/safe-global/safe-wallet-web/pull/4162#issuecomment-2349136056
It decreases the breakpoint of the backButton css and removes a magic number from the txLayout component. Now the `isDesktop` variable is getting it value based on the `lg` measure.
1) Go to any transaction screen where the back button appears
2) Resize the screen 
3) The back button should break only in the 1199 resolution
Video: https://www.awesomescreenshot.com/video/31567985?key=75c8d42a80cec6163ca9679d129950cf
> Fix: back button breakpoint in tx flow

- src/components/transactions/ExecuteTxButton/index.tsx
- src/components/transactions/SignTxButton/index.tsx
If an owner is connected to the wrong chain the confirm and execute button is disabled.
Removes network check  for those buttons.
- Open a Safe with a queued and signable tx
- Connect with an owner wallet on a wrong chain
> fix: do not check network for confirm / execute buttons in the queue

- src/components/common/CookieAndTermBanner/index.tsx
- src/pages/terms.tsx
- src/store/cookiesAndTermsSlice.ts
A few minor edits on the Terms page.
> Legal: update the terms page [SW-185]

- src/features/counterfactual/ActivateAccountFlow.tsx
Allows activating Safe accounts as non owner and for multisig counterfactual Safes.
Adds `allowNonOwner` to `CheckWallet` within the `ActivateAccountFlow`
- Create a m/n counterfactual Safe
- Activate it
> [Multichain] fix: allow activating Safes as non-owner

- src/components/common/NetworkSelector/NetworkMultiSelector.tsx
- src/components/common/NetworkSelector/index.tsx
- src/components/common/NetworkSelector/styles.module.css
Resolves SW-184 and fixes a regression introduced in #4075 for `getNetworkLink`
- Checks for `safeAddress` inside `getNetworkLink` and simplifies the pathname
1. Open a Safe that is deployed on multiple networks
2. Switch to a different network
3. Observe the same route is still open for the new network
4. Observe no visual issue in dark mode when pressing "Show all networks"
> [Multichain] fix: Network selector links and visual style [SW-184]

- src/features/speedup/components/SpeedUpModal.tsx
- src/features/speedup/utils/__tests__/IsSpeedableTx.test.ts
- src/hooks/__tests__/useTxPendingStatus.test.ts
- src/hooks/__tests__/useTxTracking.test.ts
- src/hooks/useDraftBatch.ts
- src/hooks/useTxPendingStatuses.ts
- src/services/tx/__tests__/txEvents.test.ts
- src/services/tx/__tests__/txMonitor.test.ts
- src/services/tx/tx-sender/__tests__/ts-sender.test.ts
- src/services/tx/tx-sender/dispatch.ts
- src/services/tx/txEvents.ts
- src/services/tx/txMonitor.ts
- src/store/__tests__/pendingTxsSlice.test.ts
- src/store/__tests__/txHistorySlice.test.ts
- src/store/__tests__/txQueueSlice.test.ts
- src/store/pendingTxsSlice.ts
- src/store/txHistorySlice.ts
- src/tests/builders/pendingTx.ts
- src/utils/transaction-guards.ts
Follow up to #4025
This is needed in order for #4069 to work since migration transactions are always replaced and their pending state is stuck indefinitely which bricks the safe.
- Stores the `nonce` for each pending transaction
- Extends the pending tx cleanup logic in the tx history middleware by not just checking if there is a matchin txId but also if there is a matching nonce and in case there is and txIds don't match it means the pending transaction got replaced so it is safe to clear it
1. Open the same safe in two different browsers
2. Execute a transaction with the same nonce at the same time from each browser
3. Observe both pending states to be cleared as soon as one of the transactions is executed
> fix: Cleanup pending txs if nonce already executed

- src/components/common/NetworkInput/index.tsx
- src/features/multichain/components/CreateSafeOnNewChain/index.tsx
Legacy Safes could be replayed through the sidebar context menu.
Marks unavailable chains as disabled
- Try to add a network to a 1.1.1 Safe
> [Multichain] Fix: Disable legacy safe replaying

- src/components/common/NetworkSelector/NetworkMultiSelector.tsx
- src/services/contracts/deployments.ts
Fixes the check for canonical deployments in the `NetworkMultiSelector` 
- Create a new Safe and start with any chain except zkSync.
- Observe that now zkSync is not offered (greyed out)
> [Multichain] fix: check for canonical deployments

- src/features/swap/helpers/data/stablecoins.ts
Some user were complaining that our swaps was applying a too high fee on stables. It turned out that we didn't have sdai, eure and usdc.e tokens in the list of stables.
Resolves #
Try to swap 100 between the tokens and your swap should have a 0.1% fee applied instead of 0.35%
> Feat: add sdai, usdc.e, EURE to the list of stables

- src/components/common/BlockedAddress/index.tsx
- src/features/stake/components/StakePage/index.tsx
- src/features/swap/index.tsx
- src/store/ofac.ts
Checks whether the currently connected wallet or safe is on the OFAC list and blocks access to the stake feature.
You can use impersonator.xyz with any of the addresses on the https://github.com/ultrasoundmoney/ofac-ethereum-addresses/blob/main/data.csv list and it should display a block letting you know that the address is blocked.
> Feat stake OFAC

- src/features/stake/components/InfoTooltip/index.tsx
- src/features/stake/components/StakingConfirmationTx/Deposit.tsx
- src/features/stake/components/StakingConfirmationTx/Exit.tsx
The fee label for deposit was missing the Info tooltip. This PR ads it.
Try to create a deposit, the fee tooltip should be next to the fee.
> Fix(Staking): add tooltip to widget fee

- src/components/new-safe/create/steps/ReviewStep/index.tsx
- src/features/counterfactual/ActivateAccountFlow.tsx
When activating a CF safe, the network is not shown as it was before.
Show the network in `ActivateAccountFlow` when activating a safe
- Create a CF safe and then activate it.
- On the confirmation screen, the network of the safe should be shown in the `Network` section
> Fix(Multichain): No network is visible in activate account flow. [SW-192]

- src/components/common/NetworkSelector/NetworkMultiSelector.tsx
- src/components/new-safe/create/logic/index.test.ts
- src/components/new-safe/create/logic/index.ts
- src/components/new-safe/create/steps/ReviewStep/index.tsx
- src/components/welcome/MyAccounts/utils/multiChainSafe.ts
- src/utils/chains.ts
Adds feature toggle for Multichain creation
- On Prod: only single chain creation should be available
- On Staging: For multi chain Safes only Sepolia, Polygon and Ethereum support multichain deployments
> [Multichain] Feat: multichain feature toggle

- src/components/common/CheckWallet/index.test.tsx
- src/components/common/CheckWallet/index.tsx
- src/features/counterfactual/ActivateAccountButton.tsx
- src/features/counterfactual/ActivateAccountFlow.tsx
- new `allowUndeployedSafe` prop in `CheckWallet`
- If false the buttons get disabled for undeployed Safes
- Unit tests
- Create a new CF multichain Safe
- Go to e.g. Settings and observe the "Add owner" button to be disabled
> [Multichain] Fix: multichain disable cf creation

- src/components/new-safe/create/logic/index.test.ts
- src/components/new-safe/create/logic/index.ts
For Safe versions `< 1.4.1` no `setupToL2` call is used when creating the Safe.
- Checks the safe version and only migrates if the safe version is >= 1.4.1
- Create a Safe on a  network that does not support 1.4.1.
> Fix(Multichain): no setupTol2 for legacy versions
