safe-global/safe-wallet-monorepo

src/components/common/ConnectWallet/styles.module.css
src/services/onboard.ts
src/styles/onboard.css

Ledger and Trezor can now successfully connect.
The problem was the `publicRpcUrl` property in the chain configs. Somehow it works fine with MetaMask (when you add a chain to MetaMask, it uses this URL in MetaMask), but breaks Ledger/Trezor.
Also fixed the z-index for Ledger and Keystone modals.

Fix: Ledger and Trezor now work

---

src/components/create-safe/useEstimateSafeCreationGas.test.ts
src/hooks/__tests__/useAsync.test.ts
src/hooks/__tests__/useGasPrice.test.ts
src/hooks/__tests__/useLoadChains.test.ts
src/hooks/useAsync.ts
src/hooks/useTxHistory.ts
src/hooks/useTxQueue.ts
src/store/txHistorySlice.ts
src/store/txQueueSlice.ts

Debounce the loading state with a 10 ms timeout so that immediately resolving promises don't cause an unnecessary re-rendering.
A typical example from our code:
```
const [data, error, loading] = useAsync(() => {
if (!provider) return
return loadData()
}, [provider])
```

Fix: avoid flashing loading state in useAsync

---

src/components/transactions/ExecuteTxButton/index.tsx

Small fix for the `ExecuteTxButton`. It was staying disabled for txs with nonce 0 i.e. the first transaction in a newly created safe.

fix: Fix 0 nonce tx execution button

---

src/components/common/CustomTooltip/index.tsx
src/components/common/PaginatedTxns/index.tsx
src/components/create-safe/status/useSafeCreation.test.ts
src/components/transactions/BatchExecuteButton/BatchExecuteHoverProvider.tsx
src/components/transactions/BatchExecuteButton/__tests__/BatchExecute.test.tsx
src/components/transactions/BatchExecuteButton/index.tsx
src/components/transactions/BatchExecuteButton/styles.module.css
src/components/transactions/TxList/index.tsx
src/components/transactions/TxListItem/ExpandableTransactionItem.tsx
src/components/transactions/TxListItem/styles.module.css
src/components/transactions/Warning/index.tsx
src/hooks/__tests__/useBatchedTxs.test.ts
src/hooks/useBatchedTxs.ts

- Adds _Execute Batch_ Button to Queue
- Highlights batchable transactions when hovering the button

feat: Add batch execute button and tx highlighting

---

.env.example

The environment value is read as a string, and any non-empty string will be treated as a truthy value

Remove value from `NEXT_PUBLIC_IS_PRODUCTION`

---

src/components/common/AddressInput/useNameResolver.ts
src/components/create-safe/useEstimateSafeCreationGas.ts
src/components/load-safe/steps/SafeOwnersStep.tsx
src/components/safe-apps/AddCustomAppModal.tsx
src/components/settings/ContractVersion/UpdateSafeDialog.tsx
src/components/settings/SafeModules/RemoveModule/steps/ReviewRemoveModule.tsx
src/components/settings/SpendingLimits/NewSpendingLimit/steps/ReviewSpendingLimit.tsx
src/components/settings/SpendingLimits/RemoveSpendingLimit/index.tsx
src/components/settings/owner/ChangeThresholdDialog/index.tsx
src/components/tx/DecodedTx/index.tsx
src/components/tx/modals/NftTransferModal/ReviewNftTx.tsx
src/components/tx/modals/RejectTxModal/RejectTx.tsx
src/components/tx/modals/TokenTransferModal/ReviewTokenTx.tsx
src/hooks/__tests__/useAsync.test.ts
src/hooks/loadables/useLoadBalances.ts
src/hooks/loadables/useLoadSafeInfo.ts
src/hooks/loadables/useLoadSpendingLimits.ts
src/hooks/loadables/useLoadTxHistory.ts
src/hooks/loadables/useLoadTxQueue.ts
src/hooks/useAddressResolver.ts
src/hooks/useAsync.ts
src/hooks/useCollectibles.ts
src/hooks/useGasLimit.ts
src/hooks/useGasPrice.ts
src/hooks/useOwnedSafes.ts
src/hooks/useTxHistory.ts
src/hooks/useTxQueue.ts
src/services/__tests__/domains.test.ts
src/services/domains.ts

`useAsync` often has to check for missing dependencies from other hooks, and we've been doing it from inside an async function. This can cause an unnecessary re-rendering of the `loading` state.
This PR allows returning `undefined` from the `useAsync` callback (not `Promise<undefined>`!), in which case it bypasses the whole loading routine, and `setLoading` will never be set to true in that case.
I also fixed `useLoadBalances` which weren't polling because of the safe hook memoization.
Unit tests + check places that have a loader:
* name/address-resolving inputs
* tx queue/history

Refactor: undefined in useAsync

---

src/components/transactions/ExecuteTxButton/index.tsx
src/components/transactions/RejectTxButton/index.tsx
src/components/transactions/SignTxButton/index.tsx

Small fix for the Mui warning in console that `Tooltip` shouldn't be used with a disabled child element

fix: Add span wrapper for disabled tooltip buttons

---

.github/workflows/e2e.yml
.github/workflows/lint.yml

Adds a build command to quickly fail the more lengthy CI jobs (CloudFlare and e2e tests) if the build isn't working.

Chore: add build to the lint job

---

src/components/load-safe/steps/SafeReviewStep.tsx

Fallback names being added to address book.
Before adding owners of a Safe to the address book, they are first checked against the `fallbackName`.
Create/load a Safe but do not enter names for the owner(s). After successful creation/load, observe that the owners will not be present in the address book.

fix: don't add fallback names to address book

---

src/components/address-book/AddressBookTable/index.tsx

Enabling export button providing there is at least one address book entry stored locally.
Instead of referencing the `length` of the address book of the current chain, 'all' address books are checked instead.
Note: we do not remove the `chainId` key from the address book if all entries are removed from said chain, hence `values` are checked.
Ensure an entry exists on one chain then switch to another chain that has no address book entries. Observe the export button is now enabled.

fix: enable export with any address book entry

---

src/components/common/PaginatedTxns/index.tsx

Incorrect error text.
The `<PaginatedTxns>` component is shared between historical and queues transactions. It's now has a generic error message.

fix: tx loading error text

---

src/components/common/Header/index.tsx
src/components/common/Track/index.tsx

Logo link in header.
`passHref` was not functioning correctly as it wasn't wrapped in an anchor.
Hover over the logo in the header and observe the cursor change. Clicking it should navigate you to `/`.

fix: wrap header logo in anchor

---

src/components/transactions/BatchExecuteButton/index.tsx

Batch execution tooltip console error.
The `children` of the `CustomTooltip` is now wrapped in a `<span>`.
Open the queue list and observe no console error about tooltips.

fix: batch execution tooltip error

---

src/components/common/TokenAmount/index.tsx
src/components/common/TokenAmount/styles.module.css
src/components/tx/modals/TokenTransferModal/ReviewTokenTx.tsx
src/components/tx/modals/TokenTransferModal/styles.module.css
src/hooks/useDarkMode.ts
src/pages/_app.tsx
src/pages/safe/settings/appearance.tsx
src/store/settingsSlice.ts

Fixes the dark mode switch and default value in store + adds a light background for token icons in dark mode.

Fix: dark mode toggle + asset icons in dark mode

---

.github/workflows/e2e.yml
src/components/address-book/ImportDialog/__tests__/validation.test.ts
src/components/address-book/ImportDialog/index.tsx
src/components/address-book/ImportDialog/validation.ts
src/utils/__tests__/validation.test.ts
src/utils/validation.ts
yarn.lock

Address book import validation.
Entries are first validated, displaying an error/disabling the import button if they are invalid. Entries that contain empty fields are ignored. `chainId`s in address books that have whitespace are sanitised.
- Import must be `.csv` file
- It cannot be > 1MB in size
- CSV file must contain data
- CSV file must have the correct headers
- Entries must exist
- All addresses must be valid
- All `chainId`s must be valid
Manipulate an address book CSV to flout one of the above validation rules and observe the shown that prevents submission.

feat: validate address book import

---

src/components/common/LoadMoreButton/index.tsx
src/components/common/PaginatedTxns/index.tsx
src/hooks/useTxHistory.ts
src/hooks/useTxQueue.ts
src/pages/safe/balances/nfts.tsx
src/store/index.ts
src/store/txQueueSlice.ts

There were duplicate tx items in the history when a new tx was successfully indexed. This was due to the allResults continuously  accumulating loaded results.
Now, we display each page separately with its own loader hook. So that if a page is updated, it will re-render itself seamlessly.

Fix: duplicate results in paginated txns

---

src/components/common/Footer/index.tsx
src/components/common/Header/styles.module.css
src/components/common/PageLayout/index.tsx
src/components/common/PageLayout/styles.module.css
src/components/sidebar/Sidebar/index.tsx
src/components/sidebar/Sidebar/styles.module.css

When navigating between long pages with scroll, the scroll position wasn't resetting. This was because we have a custom scrollable container (.main) instead of the body.
This PR changes the page layout so that the whole page scrolls, and the header and sidebar are sticky.
I had to remove the owned safes on the welcome page for now. They break all the beautiful CSS logic. Hopefully we'll restore it in a new design.

Fix page scroll

---

src/components/transactions/BatchExecuteButton/styles.module.css
src/components/transactions/GroupedTxListItems/styles.module.css

- Moves the Batch Execute button down to not overlap with the tabs on smaller screens
- Scaffolds grouped tx description on smaller screens

style: Align batch execute button on smaller screens

---

src/components/address-book/ImportDialog/__tests__/validation.test.ts
src/components/address-book/ImportDialog/index.tsx
src/components/address-book/ImportDialog/validation.ts

Clearer error messages and entry count.
1. Rejected uploads (wrong filetype or >1MB csv files) now display their error message.
2. Chain IDs padded with whitespace that match other chain IDs in an address book are counted as the same when displaying the chain count, i.e. `"100"` is the same as `"  100    "`
3. Validation messages are row-specific.
1. Drag a non-csv file or attempt to upload a >1MB csv file. Observe the related error message.
2. Upload an address book that contains two entries on the same chain, but modifying one `chainId` to have whitespace at the beginning or end. Observe the row-specific error message.
3. Upload an address book with an invalid address, then name. Observe each time a row-specific error message. Invalid chain IDs match testing method 2.

fix: row-specific validation

---

src/components/settings/RequiredConfirmations/index.tsx
src/components/tx/SignOrExecuteForm/index.tsx

Nonce not displaying when changing nonce.
1. When no `tx` exists in `<SignOrExecuteForm>`, `<GasParams>` is hidden. `<ChangeThresholdDialog>` does not create a transaction unless a new threshold is selected:
2. On top of this, the "Change" button to alter a Safe threshold is hidden on 1/1 Safes.
1. Open a 1/2 Safe and attempt to change the threshold. Observe no gas parameters in the dialog, as well as the submit button being disabled until choosing a new threshold.
2. Open a 1/1 Safe and observe no threshold "Change" button in the settings.
1. 
2.

fix: hide gas params if no tx + threshold when 1/1

---

src/components/common/Notifications/index.tsx
src/components/common/Notifications/styles.module.css
src/components/notification-center/NotificationCenterItem/index.tsx
src/components/notification-center/NotificationCenterItem/styles.module.css
src/components/notification-center/NotificationCenterList/index.tsx
src/hooks/useSafeNotifications.ts
src/hooks/useTxNotifications.ts
src/store/notificationsSlice.ts

Rendering of notification links.
The `link` in a notification is now rendered when one is present. A deeplink to transactions was also included.
- Access a Safe that requires an update and observe the link in the notification.
- Create and/or execute a proposed transaction and observe the link in the notification.

feat: show link in notifications

---

src/services/tx/txSender.ts

Small fix for Spending Limits (and potentially other places) when the multisend call only has 1 tx, the core-sdk already sets `operation: 0` so we should reuse that
1. Create a new spending limit, it has more than 1 tx and is encoded as a multisend call
2. Change the same spending limit, owner and token need to be the same
3. Observe that there is no error message
4. Observe that the tx can be executed

fix: Use operation from core-sdk for multisend tx call

---

src/components/common/Notifications/styles.module.css
src/components/settings/owner/ChangeThresholdDialog/index.tsx
src/components/tx/AdvancedParamsForm/index.tsx
src/components/tx/ErrorMessage/index.tsx
src/components/tx/ErrorMessage/styles.module.css
src/components/tx/ExecuteCheckbox/index.tsx
src/components/tx/GasParams/index.tsx
src/components/tx/SignOrExecuteForm/index.tsx

If safeTxGas isn't zero, it will display it in the advanced params + in the form.
Safe Core SDK takes care of setting it to 0 for 1.3.0 safes.

Feat: display/edit safeTxGas when not 0

---

src/components/transactions/Warning/index.tsx

Styling of threshold changes/(unexpected) delegate call warnings.
`<Alert>`s are now styled in a similar fashion to notifications:
- Observe the correctly styled threshold warning here
`rin:0x501E66bF7a8F742FA40509588eE751e93fA354Df/transactions/tx?id=multisig_0x501E66bF7a8F742FA40509588eE751e93fA354Df_0xb8badb9506ca147386d9980fb4ba78a04fa61298ee3a13c368ec5f685b3c87e8` in light/dark mode.
- Observe the correctly styled unexpected threshold warning here
`rin:0x73a7AA145338587f7aB7f63c06d187C85dF4727e/transactions/tx?id=multisig_0x73a7AA145338587f7aB7f63c06d187C85dF4727e_0xba28109747222d6cfb7f0fb75f03d49957e343674bc116162b038e244dbcc6d6`.

fix: threshold change/delegate call warning styles

---

src/components/create-safe/index.tsx
src/components/settings/SafeModules/RemoveModule/index.tsx
src/components/settings/SpendingLimits/NoSpendingLimits.tsx
src/components/settings/SpendingLimits/SpendingLimitsTable.tsx
src/components/settings/SpendingLimits/index.tsx
src/components/settings/owner/RemoveOwnerDialog/index.tsx
src/components/sidebar/SidebarNavigation/config.tsx

Spending limit token icons didn't have a fallback, fixed by using `<TokenIcon>`.
Also removed capital initial letters in titles.

Fix: token icon in spending limits; decapitalize labels

---

public/images/network-error.svg
public/third-party-cookies-check/index.html
src/components/safe-apps/AppCard.tsx
src/components/safe-apps/AppFrame/ThirdPartyCookiesWarning.tsx
src/components/safe-apps/AppFrame/index.tsx
src/components/safe-apps/AppFrame/styles.module.css
src/components/safe-apps/AppFrame/useAppIsLoading.ts
src/components/safe-apps/AppFrame/useThirdPartyCookies.ts
src/components/safe-apps/AppList.tsx
src/components/safe-apps/SafeAppsErrorBoundary/SafeAppsLoadError.tsx
src/components/safe-apps/SafeAppsErrorBoundary/index.tsx
src/components/safe-apps/SafeAppsErrorBoundary/styles.module.css
src/config/constants.ts
src/hooks/safe-apps/useSafeAppFromManifest.ts
src/pages/safe/apps.tsx
src/services/exceptions/ErrorCodes.ts
src/services/safe-apps/track-app-usage-count.ts
src/utils/url.ts

Resolves https://github.com/safe-global/web-core/issues/364
This PR includes the basic iframe loading components for Safe Apps. The SDK communication is not included in order to  maintain the PR small. Another branch will be created from this one to include SDK communication. It means that apps using the Provider are not going to load as the initial communication should be set. Use something like `CowSwap` to test that properly load
1) Open an app and see it can load properly
2) Open BrokenApp for checking the slow loading messages and error boundaries
3) Check Third party cookies banner working properly
4) Check correct tracking of opened apps in local storage

feat(safe-apps):  Safe App iframe view

---

src/services/analytics/analytics.ts
src/services/beamer/index.ts

Loggin events on prod.
Events are now logged as `info` when `!IS_PRODUCTION`,
Note: is is possible to turn off `info` logs in the console and they therefore won't interfere with debugging.
Navigate the Safe and observe the events loggin as `info` instead of a normal `log`.
Console logging only occurs outside of prod.

fix: log events as `info` outside of prod.

---

src/hooks/useTransactionStatus.ts

Signer specific `AWAITING_CONFIRMATIONS` statuses.
If the currently connected wallet exists in the `missingSigners` array, the status is "Needs your confirmation" as opposed to "Needs confirmations" when it isn't.
Create a transaction on a 2+/n Safe. Observe how the status differs between the creator and the other required signers.

fix: wallet-dependent awaiting confirmation status

---

src/components/tx/SpendingLimitRow/index.tsx
src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx
src/hooks/useSpendingLimit.ts
src/utils/__tests__/validation.test.ts
src/utils/validation.ts

- When sending funds and selecting a token for which a spending limit exists we show a radio group selection
- Selecting the Max amount changes depending on what is selected
1. Create a new transaction and select a token for which a spending limit exists for the connected wallet address
2. Observe 2 options showing up (Multisend, Spending Limit)

feat: Add Spending limit tx type selection when sending funds

---

.github/workflows/e2e.yml
.github/workflows/lint.yml
.github/workflows/test.yml
src/components/tx/AdvancedParamsForm/index.tsx
src/components/tx/ExecuteCheckbox/index.tsx
src/components/tx/GasParams/index.tsx
src/components/tx/SignOrExecuteForm/index.tsx
src/components/tx/TxStepper/index.tsx
src/components/tx/modals/ConfirmTxModal/ConfirmProposedTx.tsx
src/components/tx/modals/RejectTxModal/RejectTx.tsx

A help link in the Advanced params:
An info icon + tooltip for the Execute checkbox:
The text in the Execution modal:
The signing text in the rejectio
n modal:

Fix: small text/UI adjustments in tx modals

---

src/components/settings/SpendingLimits/NewSpendingLimit/steps/ReviewSpendingLimit.tsx
src/components/settings/SpendingLimits/NewSpendingLimit/steps/SpendingLimitForm.tsx
src/components/transactions/TxDetails/TxData/SpendingLimits/index.tsx

Adding test spending limit periods for Rinkeby.
The spending limit periods depending on the current `chainId`. Rinkeby now has shorter spending limit periods.
- Add a new spending limit on Rinkeby. Observe the periods of 5 minutes, 30 minutes and 1 hours.
- Add a new spending limit on a non-Rinkeby chain. Observe the periods of 1 day, 1 week and 1 month.
Rinkeby:
Polygon:

fix: use diff. reset for Rinkeby spending limits

---

src/components/settings/SpendingLimits/NewSpendingLimit/steps/SpendingLimitForm.tsx

Immediate validation of spending limit amounts
The spending limits form not validates fields `onChange`.
Open the modal to add a new spending limit and select an asset then attempt to enter a negative amount. When the input loses focus, observe the validation error message.

fix: validate spending limits `onChange`

---

src/hooks/loadables/useLoadSpendingLimits.ts

Spending limit not resetting
When changing from a Safe that has a spending limit to another that has none, the `spendingLimits` slice is reset to an empty array.
Open a Safe with a spending limit and observe it set in the settings. Switch to a Safe that has none set and observe none in the settings.

fix: reset spending limit module if none is set

---

src/components/settings/owner/AddOwnerDialog/DialogSteps/ChooseOwnerStep.tsx

Unclear owner replacement
A "New owner" label has been added above the relevant fields.
Open the owner replacement modal and observe the new label.

fix: add "New owner" label to owner replacement

---

src/components/settings/SpendingLimits/RemoveSpendingLimit/index.tsx

Token not displayed in spending limit removal modal
The formatted amount of, as well as token logo, is now displayed in the spending limit removal modal.
Remove a spending limit and observe the token at the top of the modal.

fix: add token to remove spending limit modal

---

src/components/common/Notifications/index.tsx
src/components/notification-center/NotificationCenter/index.tsx

Closing notifications toggling unread badge.
Notification center only shows the unread badge if a notification is `!isRead`. When manually closing a notification, it reads a it.
-Open a Safe that requires an update. When the notification opens, observe the unread badge on the notification centre badge. Either opening the notification center or manually closing the notification directly removes the badge.
-Dispatch an autohiding notification (via a transaction) and observe the badge persisting when the notification autohides. Manually closing it removes the badge.

fix: unread badge

---

src/components/settings/SafeModules/index.tsx

Unnamed modules
When a known module is added, i.e. spending limit module, they are listed without a name. This means that the module could theoretically be removed, removing set spending limits in turn. This adds either "Spending limit module", or "Unknown module" in the module list (if there is no address book entry for said address).
Enable a spending limit and navigate to the modules settings of the Safe. Observe the "Spending limit module" name now shown.

fix: display module names

---

src/components/tx/GasParams/index.tsx

Gas params editor not opening.
The edit button is now replaced with a skeleton when gas estimations are loading. Proposed transactions show the edit button immediately.
Create/create and execute transactions on 1/1 Safes and observe that gas params are editable. The same for 1+/n Safes.
The Safe in question that showcased these issues was `rin:0x9913B9180C20C6b0F21B6480c84422F6ebc4B808`.

fix: don't allow immediate edit of gas params

---

src/components/settings/SpendingLimits/NewSpendingLimit/steps/SpendingLimitForm.tsx
src/components/transactions/TxDetails/TxData/SpendingLimits/index.tsx
src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx
src/utils/__tests__/validation.test.ts
src/utils/validation.ts

Limited spending limits.
There is now no upper limit to the token amount when adding a spending limit.
Add a spending limit, select a token and enter an amount higher than that that currently is in the Safe. Observe no error.

fix: remove upper limit for spending limit tokens

---

src/components/transactions/HexEncodedData/index.tsx

Expanding hex data submitting transactions.
The `onClick` handler for showing/hiding hex data calls `preventDefault` before toggling.
Open the spending limit creation modal and on the review step open the "Transaction details" accodion, clicking on "Show more"/"Show less" won't submit the form.

fix: prevent "Show more" from submitting form

---

src/components/common/SafeTokenWidget/index.tsx
src/components/common/TokenAmount/index.tsx
src/components/create-safe/steps/ReviewStep.tsx
src/components/settings/SpendingLimits/NewSpendingLimit/steps/ReviewSpendingLimit.tsx
src/components/settings/SpendingLimits/NewSpendingLimit/steps/SpendingLimitForm.tsx
src/components/settings/SpendingLimits/SpendingLimitsTable.tsx
src/components/transactions/TxDetails/TxData/DecodedData/Multisend/index.tsx
src/components/transactions/TxDetails/TxData/SpendingLimits/index.tsx
src/components/transactions/TxDetails/TxData/Transfer/TransferActions.tsx
src/components/tx/GasParams/index.tsx
src/components/tx/SendFromBlock/index.tsx
src/components/tx/SpendingLimitRow/index.tsx
src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx
src/services/tx/tokenTransferParams.ts
src/store/addedSafesSlice.ts
src/utils/__tests__/formatters.test.ts
src/utils/formatters.ts
src/utils/validation.ts

Number formatting and "Max" spending limit.
The number formatters have been updated to use `ethers`' `formatUnits` instead of `toDecimals` and the "Max" token amount has been removed from the `<SpendingLimitForm>` field as it's possible to set higher amounts than that which is in the Safe.
1. Observe all numbers formatted correctly across the Safe, i.e. in the assets list, in high and low amount transactions and in modals. Choosing the "Max" amount when the current transaction has high or low amounts, formatted with `>` or `<` should not copy these symbols into their respective amount fields.
2. The "Max" button should no longer exist in the spending limits form.

fix: adjust number formatters + "Max" spending limit

---

src/components/tx/AdvancedParams/AdvancedParamsForm.tsx

A tiny fix to the help link in Advanced params.

Fix: target blank for help link

---

src/styles/theme.ts

Unselectable tokens
Long `<Select>` `<MenuItem>`s now show a scrollbar.
Open a Safe with a large amount of asset types. Open the currency selector and observe the scrollbar. Attempt to send assets and observe the scrollbar in the asset list. The same with the asset list when creating a spending limit.

fix: add scroll to long select lists

---

src/hooks/useTxPendingStatuses.ts
src/pages/_app.tsx

Both hooks are basically initializing pending txns, so no need to call them separately.

Refactor: call useTxMonitor from usePendingTxs

---

src/components/common/EthHashInfo/index.tsx
src/components/create-safe/status/useSafeCreation.ts
src/components/create-safe/steps/OwnerPolicyStep.tsx
src/components/create-safe/steps/OwnerRow.tsx
src/components/create-safe/steps/ReviewStep.tsx
src/components/create-safe/types.d.ts
src/components/load-safe/steps/SafeOwnersStep.tsx
src/components/load-safe/steps/SafeReviewStep.tsx
src/components/load-safe/steps/SetAddressStep.tsx
src/components/settings/owner/AddOwnerDialog/DialogSteps/ChooseOwnerStep.tsx
src/hooks/__tests__/useAddressResolver.test.ts
src/hooks/useAddressResolver.ts

Empty entries in address book
- `NamedAddress['fallbackName']` has been changed to `NamedAddress['ens']` and the create/load Safe flow updated accordingly. `placeholder`s are heirachically:
1. Address book name
2. ENS domain
3. Random mnemonic (only when loading a Safe or adding an owner)
- The above are used as sequential fallbacks when loading Safes or adding owners to existing Safes.
- `useAddressResolver` has been adjusted to not return fallbacks from `useMnemonicName` as it is not required everywhere. The hook now returns:
```ts
{
name: string, // Current address book name
ens?: string, // Resolved ENS domain, if no address book entry found
resolving: boolean // Resolving status
}
```
1. Create a Safe, define/don't define a name. Observe that it is added to the address book with a …

fix: empty named entries added to address book

---

src/components/common/Header/index.tsx

The logo had a leftover height from the previous logo.

Fix: logo size

---

src/pages/safe/settings/appearance.tsx

Resolves #459
(Un-)checking the prefix copy preference checkbox now toggles the setting.
Open the apperance settings and toggle the prefix copying setting. Observe the checkbox (un-)checks and copying the address from the sidebar prepends the prefix accodingly.

fix: copy prefix checkbox

---

src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx

Resolves #457
When setting the "Max" amount of assets to send, it selects either the highest amount (if it is within the spending limit) or spending limit (if it is less than the amount).
Create a spending limit that is higher than the asset amount in the Safe. Create a transaction, selecting the "Max" amount. Observe that it selects the max amount of the asset, not the spending limit.

fix: limit max to balance

---

package.json
src/components/settings/SafeModules/RemoveModule/steps/ReviewRemoveModule.tsx
src/components/settings/SpendingLimits/NewSpendingLimit/steps/ReviewSpendingLimit.tsx
src/services/tx/__tests__/spendingLimitParams.test.ts
src/services/tx/__tests__/txSender.test.ts
src/services/tx/txSender.ts
src/utils/transactions.ts
yarn.lock

- Updates `safe-core-sdk` packages dependencies
- Renames methods
- Removes `TransactionOptions` casting
Notes: Will update the `nonce` type in `TransactionOptions` i nthe next Core SDK release to `number | string` instead of just `number`

Update `safe-core-sdk` to v3.0.0

---

src/components/common/PaginatedTxns/index.tsx

When triggering the infinite scroll pagination on the tx list it keeps the old urls even when applying a new filter. Now we reset `pages` when applying the filter.
1. Open the safe
2. Navigate to the tx history
3. Scroll down so more transactions are loaded
4. Scroll up and apply a filter
5. Observe the filter being applied and only relevant txs are being displayed

fix: Reset pages when applying tx filter

---

src/components/tx/DecodedTx/index.tsx
src/components/tx/GasParams/index.tsx

Unnecessary use of state.
The second `expanded` argument of `<Accordion>` `onChange` handlers is used for tracking events.
Create a transaction and in the flow open/close the gas parameters/tansaction details. Observe the event tracking "Open"/"Close" correctly.
The `MODALS_EVENTS.TX_DETAILS` and `MODALS_EVENTS.ESTIMATION` events should track as before.

refactor: use `onChange` to track events directly

---

src/utils/__tests__/tx-history-filter.test.ts
src/utils/tx-history-filter.ts

#475 
Transaction filter dates no longer contain the time, instead formatting in `"yyyy-MM-dd"`.
Filter transactions by date. Observe that the results are from start of day to end of day of the chosen dates.

fix: remove time from date filters

---

src/components/settings/ContractVersion/UpdateSafeDialog.tsx
src/components/settings/SpendingLimits/NewSpendingLimit/steps/ReviewSpendingLimit.tsx
src/services/tx/__tests__/spendingLimitParams.test.ts
src/services/tx/txSender.ts

Replaces the use of MultiSend contract with the use of the MultiSendCallOnly contract using the Safe Core SDK

Use MultiSendCallOnly

---

src/components/settings/SafeModules/index.tsx
src/hooks/useTransactionType.ts
src/utils/transaction-guards.ts

Unnecessary side effect and inconsistent default module names
Unknown modules are now shown under the same name ("Unknown module") in the settings and transaction list.
`useTransactionType` has also been simplified to not rely on state/effects, abstracting the transaction `type` parsing into `getTxType`.
The transaction list `type`s (in the summary headers) should appear the same as before.

fix: standardise unknown module names  + simplify `useTransactionType`

---

src/components/tx/SignOrExecuteForm/SignOrExecuteForm.test.tsx
src/components/tx/SignOrExecuteForm/index.tsx

- Adds tests for `SignOrExecuteForm`

fix: Add tests for SignOrExecuteForm

---

src/components/create-safe/sender.ts
src/components/create-safe/status/usePendingSafeCreation.ts
src/components/create-safe/status/useSafeCreation.test.ts
src/components/create-safe/useEstimateSafeCreationGas.test.ts
src/components/create-safe/useEstimateSafeCreationGas.ts
src/components/tx/TxSimulation/utils.ts
src/components/tx/modals/BatchExecuteModal/ReviewBatchExecute.tsx
src/hooks/coreSDK/safeCoreSDK.ts
src/services/contracts/safeContracts.ts
src/services/contracts/spendingLimitContracts.ts
src/services/tx/__tests__/safeUpdateParams.test.ts
src/services/tx/safeUpdateParams.ts
src/services/tx/txSender.ts
src/utils/transactions.ts

Using the Core SDK to get contract instances.
All (possible) contract instance retrievals are now done via the Core SDK so that we rely less on TypeChain.
- Safe creation and associated gas estimation works as expected.
- Interrupted Safe creation transactions succeed.
- Batch execution works as expected.
- Safe updating works as expected.

refactor: instantiate contracts via Core SDK

---

src/components/sidebar/Sidebar/styles.module.css

The Mobile `Sidebar` is covered by the `Header` for some viewport widths
The Sidebar media query is adjusted to apply `padding-top` to the Mobile Sidebar
1. Adjust the viewport width to 700px
2. Click the Menu button
3. The Sidebar is no longer under the Header bar
_before_
_after_

style: adjust Sidebar media query

---

src/components/common/ConnectWallet/AccountCenter.tsx

The `<AccountCenter />` displays the selected network instead of the connected wallet network.
`<AccountCenter />` component now displays the connected wallet chain information. This change aligns the UI with showing the `<ChainSwitcher />` component.
1. Connect to the app with a wallet that doesn't disconnect on switching chains (p.ex. MetaMask)
2. In the Network Selector change network.
3. The connected wallet should remain aligned with MM
_before_
_after_

fix: show connected wallet chain info

---

src/hooks/coreSDK/__tests__/safeCoreSDK.test.ts
src/services/__tests__/safeContracts.test.ts
src/services/contracts/safeContracts.ts

Resolves #508
Metadata is stripped from version number.
When getting contract instances via the Core SDK, it only accepts versions `1.1.1`, `1.2.0` or `1.3.0`. The `version` of L2 Safes includes `+L2` metadata. This is now stripped before getting contract instances from the Core SDK.

fix: do not pass version metadata to Core SDK

---

src/components/common/EthHashInfo/index.tsx

Hashes being prefixed
`EthHashInfo` only adds prefixes to `props.address` lengths of `42`. Hashes are therefore no longer prefixed.
Open transaction details and observe the "Transaction hash" and "safeTxHash" having no prefix.

fix: only prefix addresses

---

src/components/common/CopyAddressButton/index.tsx
src/components/common/EthHashInfo/index.test.tsx
src/components/common/EthHashInfo/index.tsx

Untested `EthHashInfo`
- `<EthHashInfo>` is now fully covered by unit tests.
- `props.copyPrefix` has been removed as `<CopyAddressButton>` determines this based on settings.
- The prefix is not retrieved from `useCurrentChain`. It is instead selected via props.chainId`/`useChainId`.
- In accordance with this, `<CopyAddressButton>` is passed a specific `prefix` to match the selected chain instead of using `useCurrentChain`.
- Addresses/hashes should appear the same in the UI depending on the prefix settings. Copying the address/prefix should also prepend the prefix according to the settings.
- `src/components/common/EthHashInfo/index.test.tsx` should pass.

fix: cleanup `EthHashInfo` + add tests

---

src/components/common/Header/index.tsx
src/components/create-safe/index.tsx
src/components/load-safe/index.tsx
src/components/tx/GasParams/index.tsx
src/components/tx/TxStepper/useTxStepper.ts
src/services/analytics/events/createLoadSafe.ts
src/services/analytics/events/modals.ts
src/services/analytics/events/overview.ts

Resolves #471 
1. Clicking the logo no longer dispatches the "Go to Welcome page" event.
2. Editing the advanced parameters of a transaction only dispatches "Edit advanced params". ("Edit estimation" has been removed).
3. Navigating forward/backwards in the Safe load/creation flow dispatches the following: (Before it dispatched under the `'modals'` category).
```ts
{ eventCategory: 'load-safe'/'create-safe', eventAction: 'Next'/'Submit'/'Cancel'/'Back' }
```
1. Clicking the logo should dispatch no event.
2. Opening the advanced parameters modal should only dispatch one event.
3. Going forward/backward in Safe load/creation flows should be categorised correctly. Forward/backward navigation in modals should be categorised under `'modals'`.

fix: remove unnecessary/categorise stepper events

---

src/components/tx/SignOrExecuteForm/index.tsx
src/hooks/wallets/wallets.ts
src/services/pairing/module.ts
src/services/tx/__tests__/txSender.test.ts
src/services/tx/txSender.ts

Resolves https://github.com/safe-global/web-core/issues/485
- Signing transactions now work: `personal_sign` event is emmitted by mobile app, signed with WC's `signMessage` (`eth_sign`).
- Sending transactions now work: an empty `value` is added to the `ITXData` payload of `sendTransaction` (`eth_sendTransaction`)
- Create and sign a transaction. Observe that it is added to the queue.
- Execute a transaction. Observe that it successfully executes.

fix: use `eth_sign` + always send tx `value` when paired

---

src/components/common/SafeTokenWidget/index.tsx
src/services/analytics/events/overview.ts

Adds tracking & tooltip to safe token widget.
Hover over widget.
Click on widget => new event gets tracked
New Event: Click on Safe Claiming App Widget

add tracking and tooltip to token widget

---

src/components/common/PairingDetails/index.tsx
src/services/pairing/connector.ts
src/services/pairing/hooks.ts
src/services/pairing/module.ts

Resolves #488 
The changes to the `connector` from inside the pairing module are not being picked up by the `useInitPairing` hook. This results in event listeners not updating and thus not creating a new session / generating a new uri.
This PR adds the same workaround as we had in the old codebase to display a manual refresh button instead of the QR Code if the session was rejected or the uri is faulty (no `handshakeTopic` being present)
2. Scan the Mobile Pairing QR code
3. Confirm on phone
4. Observe being connected
5. Disconnect via Desktop
6. Observe seeing a QR Code or the manual refresh button
7. Scan the QR Code
8. Reject on phone
9. Observe seein the manual refresh button

fix: Add manual refresh to mobile pairing qr code

---

src/components/common/PaginatedTxns/index.tsx
src/components/transactions/TxList/index.tsx

Resolves #514
The `<BatchExecuteHoverProvider>` has been hoisted to surround all pages.
Queue >1 transactions and hover over the "Execute batch" button. Observe that the transaction-to-batch are highlighted accordingly.

fix: batch execution hover highlighting

---

src/components/common/PaginatedTxns/index.tsx
src/hooks/useTxHistory.ts
src/hooks/useTxQueue.ts
src/utils/__tests__/tx-history-filter.test.ts
src/utils/transactions.ts

Resolves broken transaction grouping
Date label timezone adjustment was inadventedly added to the transaction queue. The queue doesn't return date labels and it has therefore been removed.
Open `rin:0xFfDC1BcdeC18b1196e7FA04246295DE3A17972Ac` and observe that no date labels are present and that nonce 395/396 transactions are correctly grouped with no date label separation.

fix: remove date label timezone adjustment from queue

---

src/components/common/CopyAddressButton/index.tsx
src/components/common/EthHashInfo/index.test.tsx
src/components/common/EthHashInfo/index.tsx

Resolves address prefixes not copying
`showPrefix`/`copyPrefix` props have been added as per `safe-react` and the `<PrefixedEthHashInfo>` references settings to enable these accordingly.
Disable rendering of prefixes. Observe that the prefix is, however, copied.

fix: copy prefix when showing it is disabled

---

src/components/tx/GasParams/index.tsx

Resolves #532 
Since 0 is a falsy value it will not render if evaluated with `&&` so we check if its `undefined` instead
1. Open a newly created safe
3. Observe the nonce is being displayed in the review screen

fix: Handle 0 nonce in GasParams

---

src/utils/__tests__/formatNumber.test.ts
src/utils/formatNumber.ts
src/utils/formatters.ts

Unit tests for number formatting -> https://github.com/5afe/safe/wiki/How-to-format-amounts
_Note:_ I've used underscore as numeric separator for readability.
Run `yarn test formatNumber`

test: unit test formatNumber

---

src/services/analytics/TagManager.ts
src/services/analytics/__tests__/TagManager.test.ts
src/services/analytics/gtm.ts

Resolves #502
We no longer load GTM via a package. The syntax remains the same for initialization, wheras `TagManager.dataLayer` no longer requires nesting the event inside a `dataLayer` property.
- Open the Safe with Analytics cookies enabled. Observe that GTM loads as normal and events are tracked correctly.
GTM is loaded directly.

fix: load/interface with GTM directly

---

src/components/common/PaginatedTxns/index.tsx
src/utils/__tests__/tx-history-filter.test.ts
src/utils/transactions.ts

Removes unnecessary logic from client-side.
Manual additon of date labels to filter results/adjustment for timezones has been removed.
Open transaction history, ensure timezone is set to non-UTC, observe that date labels span transactions of different days.
Filter transactions. Observe that there are no date labels.

fix: remove filter date labels + timezone offset

---

src/services/analytics/TagManager.ts
src/services/analytics/__tests__/TagManager.test.ts

Resolves https://github.com/safe-global/web-core/pull/517#discussion_r967757713
GTM's `noscript` injection has been used as the Safe doesn't work without JS.
Observe no `<noscript>` injected in the DOM.

fix: remove GTM `noscript`

---

src/components/tx/SignOrExecuteForm/index.tsx
src/hooks/wallets/wallets.ts

Resolves https://github.com/safe-global/web-core/pull/505#discussion_r967760009
`isPaired` has been renamed to `isSafeMobileWallet`.

fix: rename `isPaired` to `isSafeMobileWallet`

---

README.md

As per https://gitpoap.notion.site/Maximizing-your-GitPOAP-s-impact-fafb53a83c754c2588e90c57b18ee898

Chore: add gitpoap badge to the readme

---

src/components/tx/modals/RejectTxModal/RejectTx.tsx

Part of #532
https://github.com/safe-global/web-core/issues/532#issuecomment-1243090996
Submit button is disabled for Reject transactions with nonce 0
One can create a Reject transaction with `txNonce` 0
see https://github.com/safe-global/web-core/issues/532#issuecomment-1243090996

fix: pass txNonce 0 on RejectTx

---

src/hooks/wallets/useOnboard.ts
src/services/pairing/hooks.ts
src/store/txQueueSlice.ts

Resolves queue/wallet events over tracking.
1. Transaction queue is now compared for equality before being tracked. Only actual transactions are tracked, now not including `DATE_LABEL`s or `CONFLICT_HEADER`s.
2. Connected wallet/WalletConnect peer labels are cached/compared before tracking.
1. Open the dashboard/transaction queue. Observe that only one event is tracked for the queue length, unless a queued transaction is added or executed.
2. Connect a wallet/WalletConnect peer and observe that only one event is tracked.
1. Queue length is tracked once for current queue data.
2. Wallet connection events are tracked once upon connection.

fix: queue/wallet events over tracking

---

src/components/common/ConnectWallet/WalletDetails.tsx
src/hooks/wallets/useOnboard.ts

Resolves https://github.com/safe-global/web-core/pull/543#issuecomment-1248684913
The connection call when manually connecting is now wrapped in the tracking function.
Connect to a wallet via the header and observe the tracking event.
Connecting to a wallet via the header tracks the "Connect wallet" event

fix: add missing wallet tracking

---

src/utils/date.ts

Removes redudant TODO
Comment has been removed:
- `@date-io/date-fns` is needed for the MUI date picker. It doesn't expose `date-fns`.
- `date-fns` is used extensively, not just for relevant times.
- Our `formatTimeInWords` uses hours, days, weeks, months, years, whereas `Intl.RelativeTimeFormat` is restricted to just one.

fix: remove redundant TODO

---

package.json
src/components/transactions/TxDetails/Summary/index.tsx
src/components/transactions/TxDetails/TxData/index.tsx
src/components/transactions/TxSigners/index.tsx
src/hooks/__tests__/useBatchedTxs.test.ts
src/hooks/useTransactionType.ts
src/services/tx/extractTxInfo.ts
src/utils/transaction-guards.ts
src/utils/transactions.ts
yarn.lock

Updates to CGW SDK latest version using the added types:
- ConflictType
- DetailedExecutionInfoType
- TransactionInfoType
- TransactionListItemType
History and Queue transaction lists should work as before
Expanding any transaction type details should work as before

refactor: use CGW SDK enums

---

src/components/sidebar/SidebarHeader/index.tsx
src/utils/__tests__/formatNumber.test.ts
src/utils/formatNumber.ts

Resolves currency style
The `Intl.NumberFormat` logic for amounts been refactored so that currency/amounts adhere to the same style.
Currency formatting now displays the currency code at the end of the amount which matches our desired design.
Observe no differences in amounts across the Safe, apart from the sidebar header showing currencies appended with the relevant currency code.
The currencies should be rounded to the country-specific precision, e.g. JPY has no decimals, EUR has two, IQD has three.

refactor: currency formatting

---

src/components/common/AppStoreButton/index.tsx
src/components/common/Footer/index.tsx
src/components/common/Footer/styles.module.css

Resolves no App Store button in footer
The App Store button has been added to the footer, responding to light/dark mode
Open the settings and observe the App Store button present in the footer, opening the App Store correctly when clicking. Changing the theme should also change the colour of the button
Clicking the button should dispatch the "appstore-button-click" action with a `label` of "footer".

fix: add App Store button to footer

---

src/components/common/SafeTokenWidget/__tests__/SafeTokenWidget.test.tsx
src/components/common/SafeTokenWidget/index.tsx

Fetches the claiming app url for the `SafeTokenWidget` from the config service / apps list.
Witness the updated URL on the safe token widget.
None

Token widget url

---

src/hooks/loadables/useLoadTxQueue.ts

Remove unnecessary queue loading dependency.
Queue polling does not rely on the `txHistoryTag` anymore.
Both the `txQueueTag` and `txHistoryTag` are [updated at the same time by the gateway](https://github.com/safe-global/safe-client-gateway/blob/main/src/routes/safes/handlers/safes.rs#L29-L33), using the [latest transaction timestamps](https://github.com/safe-global/safe-client-gateway/blob/main/src/routes/safes/handlers/safes.rs#L80-L143).
Queue a transaction then execute it. Observe that the transaction moves to the history as before.

fix: remove unnecessary queue dependency

---

src/services/tx/__tests__/txSender.test.ts

Some missing coverage for dispatchTxExecution + assertions for tx events in existing txSender tests.

Chore: add txSender tests

---

src/utils/__tests__/formatters.test.ts
src/utils/formatters.ts

Resolves `safeFormatUnits` FIXMEs
Trailing zero removal logic has been abstracted into its own function and tests added.
The unit tests should pass and all token amount display, i.e. Safe token amount, spending limit amount/spent and assets to send should display as before.

fix: abstract trailing zero removal logic

---

src/components/common/ContextMenu/index.tsx
src/components/common/ContextMenu/styles.module.css
src/components/sidebar/SafeListContextMenu/index.tsx
src/components/transactions/TxDetails/TxData/Transfer/TransferActions.tsx
src/components/transactions/TxDetails/TxData/Transfer/index.tsx

Resolves TODO/duplicate code
The context menus from the transaction list and sidebar Safe list have been abstracted into one `ContextMenu` component.
- Expand a transaction and observe that the context menu is as before.
- Observe that the context menu in the sidebar Safe list is as before.

refactor: abstract context menu

---

src/components/load-safe/steps/SafeReviewStep.tsx

Resolves a regression after #570. It goes to the dashboard after adding a Safe.

Fix: go to dashboard after adding a safe

---

src/utils/__tests__/formatNumber.test.ts
src/utils/formatNumber.ts

Resolves formatting 0 amounts
Instead of comparing against the minimum denominator of a currency, the current 'part' of the formatted currency is compared against `0` as that could be the value.
The minimum denominator of a currency is now derived from `1` as well.
All currencies should display as before, especially when no amount is present in a Safe and the `formatNumber` test should pass.

fix: formatting no currency

---

src/components/common/PaginatedTxns/index.tsx

Small fix for the tx list displaying "0" when there are no results.
1. Open the Queue on a safe with no transactions
2. Observe no "0" visible in content area
Before:
After:

fix: Hide result length from tx list when there are no results

---

public/_redirects

Resolves #592
[CloudFlare Pages' redirects](https://developers.cloudflare.com/pages/platform/redirects/) don't preserve query params, so I had to remove transaction history and apps from the redirect patterns. It also fixes the single tx view.
This app will still work, it will just return a 404 when loading those pages before loading the right page.
Tx history:
* Filter tx history, reload the page
* Observe that the filter is still the same
Single tx:
* Open a single tx page
* Reload the page
Safe Apps:
* Open a Safe App
* Reload the page

Fix: CloudFlare redirects cut off query params

---

src/components/common/AddressInput/index.test.tsx
src/components/common/AddressInput/index.tsx
src/components/common/AddressInput/useNameResolver.ts
src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx

Suppress validation errors when an ENS domain is entered and is being resolved.
If ENS failed to resolve, display that specific error.
Adds a debounce for regular validation errors, but there's no delay when the input becomes valid or an ENS name has been entered and is resolving.
**Case 1:**
* Open the Send Funds form
* Enter a valid ENS domain (type quickly!)
* Observe that the field remains green the whole time
If you type slowly, it will still show a validation error eventually.
**Case 2:**
* Open the Send Funds form
* Enter a bogus ENS domain
* Observe that the field remains green while the ENS is resolving but becomes red and shows an ENS error after a couple seconds
None

Fix: delay validation error in AddressInput

---

src/components/common/PageLayout/styles.module.css
src/components/common/PagePlaceholder/styles.module.css
src/components/dashboard/PendingTxs/PendingTxsList.tsx

Resolves #593
Makes the main content wrapper flex box so that the error container can stretch 100% of its height.

Fix: Safe not found alignment

---

src/components/create-safe/status/CreationStatus.tsx
src/components/create-safe/status/usePendingSafeCreation.ts
src/components/create-safe/status/useSafeCreation.test.ts
src/components/create-safe/status/useSafeCreation.ts
src/components/tx/modals/TokenTransferModal/ReviewSpendingLimitTx.tsx
src/hooks/useTransactionStatus.ts
src/hooks/useTxNotifications.ts
src/hooks/useTxPendingStatuses.ts
src/hooks/useTxTracking.ts
src/services/tx/__tests__/txEvents.test.ts
src/services/tx/__tests__/txMonitor.test.ts
src/services/tx/__tests__/txSender.test.ts
src/services/tx/txEvents.ts
src/services/tx/txMonitor.ts
src/services/tx/txSender.ts
src/store/pendingTxsSlice.ts

Accomodating statuses for PoS
All instances of mining/mined have been changed to processing/processed in order to accomodate for PoS.
- Create and execute a transaction. Observe the notification regards it as "processing" the transaction and the status is now also "Processing".
- Adding a spending limit now says "Spending limit transactions only appear in the interface once they are successfully processed and indexed." in the modal.
- Transactions that timeout (by underpricing the gas) should throw "Transaction not processed in 6.5 minutes. Be aware that it might still be processed."

fix: use processing instead of mining

---

src/components/tx/TxSimulation/__tests__/utils.test.ts
src/components/tx/TxSimulation/utils.ts

-(partially) signed transactions, which are not at the top of the queue. Could not be simulated successfully. They would run into an GS026 error.
Resolves #597 
- If a transaction has signatures we add those to the simulated transactions signatures
- We check if the simulated txs nonce is higher than the safe's nonce.
If this is true, we overwrite the nonce for the simulation.
- Queue 2 or more transactions and sign them.
- now try to simulate the transaction with the higher nonce
None

fix: simulation of queued transactions

---

.vscode/settings.json
package.json
tsconfig.json
yarn.lock

Currently if non existing css class is being used from a css module import we do not get any error / warning about it.
Adds `typescript-css-module-plugin` to enable compile errors if non-existing css classes are being referenced from css modules.
- install the new package
- restart vs code and choose the workspace version of typescript as the used typescript version
- change a imported css module class name to something invalid and wait for the compilation error

chore: add typescript-css-module-plugin

---

public/_redirects
scripts/generate-routes.js
src/config/routes.ts
src/hooks/__tests__/usePathRewrite.test.ts
src/hooks/usePathRewrite.ts
src/pages/404.tsx
src/services/analytics/useGtm.ts

Resolves #604 
It was a regression after I added _redirects. The `/` should remain in the URL.

Fix: redirect from a bare safe address URL

---

src/components/tx/modals/NewTxModal/index.tsx

Fix: NFT icon

---

package.json
public/third-party-cookies-check/index.html
src/components/settings/SafeModules/RemoveModule/steps/ReviewRemoveModule.tsx
src/components/settings/TransactionGuards/RemoveGuard/index.tsx
src/components/settings/TransactionGuards/RemoveGuard/steps/ReviewRemoveGuard.tsx
src/components/settings/TransactionGuards/index.tsx
src/components/settings/TransactionGuards/styles.module.css
src/components/transactions/TxDetails/TxData/DecodedData/ValueArray/index.tsx
src/services/analytics/events/settings.ts
src/services/tx/txSender.ts
tsconfig.json
yarn.lock

Resolves transaction guard removal
The option to remove transaction guards via a removal modal has now been implemented into the settings.
Enable a transaction guard (DenyListGuard: `0x885dCFA4A720dBAEa1Dd3AB1bB7c31Ed5f04B1c6`) then remove it via the settings. The removal should succeed after execution and the guard no longer be active/visible in the settings.
Removal tracks a new "Remove transaction guard" event.

feat: transaction guard removal

---

src/components/tx/SignOrExecuteForm/SignOrExecuteForm.test.tsx
src/components/tx/SignOrExecuteForm/index.tsx
src/hooks/wallets/wallets.test.ts
src/hooks/wallets/wallets.ts

Resolves #503 
Uses `eth_sign` when signing a transaction via WalletConnect
2. Connect to the safe via mobile MM app
3. Create/Sign a transaction
4. Observe no error
5. Observe a window popping up on the mobile MM app

fix: Use eth_sign when connected via WC

---

src/components/common/Notifications/index.tsx
src/hooks/__tests__/useSafeNotifications.test.ts
src/hooks/useSafeNotifications.ts
src/services/__tests__/safeContracts.test.ts
src/services/contracts/safeContracts.ts
src/utils/url.ts

Notifying users of invalid mastercopies
When switching Safes, the mastercopy is verified for validity and a notification dispatched if it is invalid.
Open a Safe with an invalid mastercopy (`matic:0x5B7e9a88237Ca67591e751186b10623Db5653045`) and observe the invalid mastercopy notification. Switching between Safes should trigger this only when the master copy is invalid. The CLI link should open in a new window.
Any currently present links, i.e. to update the Safe, should open in the current tab.

feat: invalid mastercopy notification

---

src/components/transactions/SingleTx/SingleTx.test.tsx
src/components/transactions/SingleTx/index.tsx
src/components/transactions/TxListItem/ExpandableTransactionItem.tsx

<SingleTx /> tests (part of https://github.com/safe-global/web-core/pull/609)
Test cases:
1. Safe contains transaction (happy path)
2. Url is wrong
3. txId is wrong
4. Safe does not contain the transaction

test: add tests to `<SingleTx />`

---

src/config/securityHeaders.ts

Resolves #629 
Opening the QR file upload spawns a worker that tries to access a `blob`.
Allows `blob` in the CSP
2. Create a new Safe
3. Open the QR Modal when adding a new owner
4. Observe app not crashing

fix: Allow blobs in CSP

---

src/components/tx/modals/NftTransferModal/SendNftForm.tsx

Resolves #639 & #640
The `imageUri || logoUri` or fallback image of an NFT are now showing in the select fields for sending an NFT.
Token ID is now truncated when too long.
Open `rin:0x1230B3d59858296A31053C1b8562Ecf89A2f888b` and send attempt to send an NFT (using impersonator.xyz if necessary). Observe the (fallback) images shown accordingly.

fix: display NFT images in send form + truncate ID

---

src/components/nfts/NftGrid/index.tsx
src/pages/balances/nfts.tsx

Resolves #638
A new `NFTApps` component, which displays apps tagged with `'nfts'`, has been added to the top of the NFTs page. If no tagged apps were found, it does not show.
Open the NFTs page and observe the NFT apps.

feat: add NFT apps to assets page

---

src/components/nfts/NftGrid/index.tsx

Resolves #634 
The collection `logoUri` is now displayed next to the title of an NFT collection.
Open `eth:0x8675B754342754A30A2AeF474D114d8460bca19b/balances/nfts` and observe the "Flowers" logo next to the collection title.

fix: display collection image

---

src/components/dashboard/Overview/Overview.tsx
src/components/tx/SendFromBlock/index.tsx
src/components/tx/SendFromBlock/styles.module.css
src/components/tx/modals/NftTransferModal/ReviewNftTx.tsx
src/components/tx/modals/NftTransferModal/SendNftForm.tsx
src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx

Resolves #642
Adds an NFT preview, in a similar style as the token transfer.
I also restored the NFT count on the Dashboard, using Aaron's Invention™️. 
Send some NFT.

Fix: sent NFT preview

---

src/components/dashboard/PendingTxs/PendingTxsList.tsx
src/utils/__tests__/transactions.test.ts
src/utils/transactions.ts

Resolves #624
The queue count is calculated based on differing nonces.
Queue a transaction and create a rejection for it. Observe that the dashboard does not count two, but one.

fix: show total of queued transactions by nonce

---

src/styles/colors-dark.ts
src/styles/vars.css

Resolves #618 
Changes the color of disabled text from #303033 to #636669 in dark mode for better visibility
2. Enable dark mode
3. Execute a queued transaction
4. Edit gas parameters
5. Observe the disabled field(s) text being more visible

style: Adjust disabled text color in dark mode palette

---

src/components/settings/SpendingLimits/NoSpendingLimits.tsx

Resolves #619 
Removes top margin for the text elements. This was a leftover from when we had a different layout.
1. Open a Safe without spending limits
2. Navigate to Settings / Spending limits
3. Observe Icons are aligned with their text

style: Align spending limit icons with their text

---

src/components/tx/GasParams/index.tsx
src/components/tx/SignOrExecuteForm/index.tsx
src/components/tx/TxSimulation/index.tsx
src/components/tx/TxSimulation/styles.module.css

- do not display nonce `0` while waiting for the estimations endpoint
- renders a Skeleton while waiting for the Simulation parameters
1. Go to a Safe and create a transaction
2. On the review modal, while the nonce is being retrieved, a Skeleton is displayed
3. In the same modal, a Skeleton component displays before the Simulation's accordion

fix: jumpy review tx modal

---

cypress/e2e/smoke/address_book.cy.js
cypress/e2e/smoke/dashboard.cy.js

Resolves dashboard/address book smoke tests
- A legacy dashboard test was removed.
- The address book selectors were improved.
Observe the E2E tests pass on the CI, or that `address_book.cy.js` and `dashboard.cy.js` pass locally

fix: dashboard + address book smoke tests

---

src/components/address-book/AddressBookTable/index.tsx
src/components/tx/modals/NewTxModal/index.tsx
src/components/tx/modals/NftTransferModal/SendNftForm.tsx

Resolves #677
The `NewTxModal` is now opened when clicking "Send" in the address book. The `recipient` is passed to either the `TokenTransferModal` or `NftTransferModal` respectively.
Open the address book and click "Send". Observe the modal allowing either token or NFT transfer. Clicking either of them assigns the recipient as the chosen contact.

fix: open `NewTxModal` from address book

---

src/components/tx/GasParams/index.tsx

Resolves #653
When signing a transaction, the wallet nonce is no longer shown.
- Create a transaction on a 1+/n Safe and observe that the wallet nonce is no longer shown/is editable in the advanced parameters.
- Create an executable transaction and observe that the wallet nonce remains and is editable.

fix: don't show wallet nonce when signing

---

src/components/dashboard/FeaturedApps/FeaturedApps.tsx

Resolves #654
The links to the features apps on the dashboard have been updated to use the `next/link` component, appending the `app.url` to the `query` object.
Open the Safe and observe the WalletConnect and Transaction Builder apps successfully open from the dashboard.

fix: links to featured apps

---

src/components/tx/AdvancedParams/AdvancedParamsForm.tsx

Resolves #661
Relevant form labels have been added to the advanced parameeters form.
Create a new transaction and observe the new form labels.

fix: add labels to advanced parameters form

---

src/components/create-safe/status/usePendingSafeCreation.ts
src/components/create-safe/status/useSafeCreation.test.ts
src/services/tx/__tests__/txSender.test.ts
src/services/tx/txSender.ts
src/utils/ethers-utils.ts

Do not dispatch a replacement transaction as an error
Partially resolves #620 
`ethers` throws an error upon speeding up a transaction. The error is handled now and does not dispatch a FAILED event.

fix: replacement tx error

---

src/components/common/ConnectWallet/AccountCenter.tsx
src/components/common/ConnectWallet/styles.module.css

Fix: overflowing address name

---

src/components/common/PageHeader/index.tsx
src/components/common/PageHeader/styles.module.css

Adds the same fixed offset when sticky as is added to the height.

Fix: page headers w/o Safe name

---

src/components/transactions/GroupLabel/index.test.ts
src/components/transactions/GroupLabel/index.tsx

Resolves #655 
" - transaction with nonce {{nonce}} needs to be executed first" has been added to "Queued" labels.
Queue two transactions. Observe the extra text on the second `LABEL`.

fix: add nonce of transaction to execute to label

---

jest.setup.js
src/components/common/SafeTokenWidget/index.tsx
src/definitions.d.ts
src/hooks/wallets/useOnboard.ts
src/hooks/wallets/wallets.ts
src/services/pairing/connector.ts
src/utils/wallets.ts

Resolves #615
Avoid attempting to reconnect if the wallet is not verifiably unlocked.
MetaMask:
* Connect to MM
* Refresh the page – it should auto-connect again
* Lock MM
* Refresh the page
* It should _not_ reconnect
WalletConnect/Safe mobile pairing:
* Connect
* Refresh the page – it should auto-connect again
* Initiate a disconnect from the WC side (not via our app!)
* Refresh the page
* It should _not_ reconnect
None.

Fix: reconnect wallet only if unlocked

---

src/components/common/PagePlaceholder/styles.module.css
src/components/dashboard/PendingTxs/PendingTxsList.tsx

We lost the image size after the illustrations were updated.

Fix: page placeholder style

---

package.json
src/components/common/AddressInput/index.test.tsx
src/components/common/AddressInput/index.tsx
yarn.lock

Resolves #686
Some sort of bug in RHF caches the error state somewhere. I blamed our code at first, but it doesn't cache the error anywhere. It's not the debounce or anything else on our side. `trigger` seems to help.

Fix: reset error after ENS resolution

---

src/components/common/DateTime/index.test.tsx
src/components/common/DateTime/index.tsx
src/components/transactions/SingleTx/SingleTx.test.tsx

Resolves #657 & #673
- The `timestamp` of a transaction is formatted as is.
- The exact time is shown on the history list.
Open `rin:0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD/transactions/queue` and observe that the queued transaction have valid "n days ago" labels. The exact time will, however, been shown on the history list.

fix: don't adjust timestamps + show exact time on history

---

src/components/sidebar/SidebarHeader/index.tsx

Resolves #671 
The QR code, copy and block explorer buttons all now use the `Tootip` component, resulting in uniform tooltip styling.
Hover over the QR code, copy or block explorer buttons in the sidebar and observe the same style.

fix: standardise sidebar toolbar styles

---

src/styles/globals.css
src/styles/theme.ts

Resolves #668
Sets a global style for `button` in order to keep the agent stylesheet from overwriting the font property
1. Go to the Tx Signers in the history list.
2. The "Hide All" button shall have `DM Sans,sans-serif` font-family

style: make `button` element inherit parent font globally

---

src/services/beamer/index.ts
src/styles/globals.css

Resolves #730
Changes the tooltip to "right" in Beamer's config
Offsets the tooltip past the Sidebar
1. Unselect Beamer's cookies
2. Accept Beamer's cookies
3. Observe the tooltip is rightfully placed
N/A

style: place Beamer tooltip to the right after Sidebar

---

src/components/tx/modals/NftTransferModal/SendNftForm.tsx
src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx

Resolves #678
if the selected tx recipient is know show it in a `<EthHashInfo />` component
Clicking on the `<EthHashInfo />` resets the recipient value.
1. Go to "Send funds"
2. Select a recipient address from the list
3. Observe <EthHashInfo /> component with the know address
1. Go to "Send NFT"
2. Select a recipient address from the list
3. Observe <EthHashInfo /> component with the know address

fix: show <EthHashInfo /> for known tx recipients

---

src/components/settings/TransactionGuards/RemoveGuard/steps/ReviewRemoveGuard.tsx

Resolves #754
The transaction removal modal title colour is now `primary.light`.
Open the transaction guard removal modal and observe the correct title colour.

fix: change colour of tx  guard modal title

---

src/components/settings/owner/AddOwnerDialog/DialogSteps/ChooseOwnerStep.tsx
src/components/settings/owner/AddOwnerDialog/DialogSteps/ReviewOwnerTxStep.tsx
src/components/settings/owner/RemoveOwnerDialog/DialogSteps/ReviewRemoveOwnerTxStep.tsx

Resolves #741
The explorer link is shown next to the address when replacing an owner.
Open the owner replacement modal and observe the explorer link.

fix: show explorer icon when replacing owner

---

src/pages/settings/setup.tsx

Resolves #736
Adds a tooltip to the Safe nonce in settings.

Fix: add safe nonce tooltip

---

src/pages/_app.tsx
src/pages/_document.tsx
src/utils/createEmotionCache.ts

Resolves #680
I've copied this example: https://github.com/mui/material-ui/tree/master/examples/nextjs-with-typescript
Basically restoring what @yagopv already did once.
The MUI theme CSS is now embedded into the pre-built HTML files.

Fix: MUI CSS cache for SSG

---

src/components/transactions/TxDetails/TxData/Rejection/index.tsx

Resolves #663
Assigns some margin right to the copy
1. Expand a "On-chain rejection" transaction
2. Observe the copy that goes like "_This is an on-chain rejection that didn't send any funds. (...)_" to never stay under the Share button in different viewport widths
None

Style share btn overlapping text

---

src/hooks/safe-apps/permissions/useBrowserPermissions.ts
src/hooks/safe-apps/permissions/useSafePermissions.ts

Resolves https://github.com/safe-global/safe-react-apps/issues/500
We removed the trailingSlash from the comparisons between origins

fix(safe-apps): Remove trailing slash from permissions appUrl comparisons

---

public/images/apps/network-error.svg
src/components/safe-apps/SafeAppsErrorBoundary/SafeAppsLoadError.tsx
src/components/safe-apps/SafeAppsErrorBoundary/styles.module.css

Resolves https://github.com/safe-global/web-core/issues/707
Use classes for dark mode instead same image for both

fix(safe-apps): Use classes for dark mode in network error icon

---

src/components/common/NetworkSelector/index.tsx
src/components/safe-apps/SafeAppLandingPage/AppActions.tsx

Resolves #696 
Switching chain using the network selector keeps the Safe App link in the URL.
In the `NetworkSelector` component:
```
[....]
return router.push({
pathname: shouldKeepPath ? router.pathname : '/',
query: {
chain: newShortName,
safeViewRedirectURL: router.query?.safeViewRedirectURL,
},
})
```
1. open a share a safe app link
2. Connect your wallet (with an address that is not an owner of a safes to make sure that the Crate Safe Button is present)
3. Use the network selector
4. Complete the Safe Creation
5. You are redirected to the Safe App with your new Safe! 😃

fix: fixed redirection to the safe app on safe creation

---

src/components/transactions/TxFilterForm/index.tsx

Resolves #501
The outgoing amount filter now shows "Acount (only {{nativeCurrency}})" as a label.
Open the outgoing transaction filter and observe the new label. It should not show on the incoming filter.

fix: add native currency to filter label

---

src/components/settings/SafeModules/index.tsx
src/components/transactions/TxInfo/index.tsx
src/hooks/useTransactionType.ts

Resolves #749, #775 & #755
- 749/775: We no longer hardcode any module names, including "Unknown module".
- 755: Contract interactions in the transaction list return the address book entry name if it is present as their type.
- 749/775: Ensure the spending limit or other module is enabled on your Safe and observe that they have no name.
- 755: Interact with a contract then add it's address to your address book. Observe the transaction list type now returns the address book name

fix: only use address book/known names

---

src/components/common/SafeLoadingError/index.tsx

Merely adds a margin to fix this:
https://fix-not-found.web-core.pages.dev/0xA77DE01e157f9f57C7c4A326eeE9C4874D0598b6/home

Fix: safe not found style

---

src/services/tx/__tests__/txSender.test.ts
src/services/tx/txSender.ts

Resolves #644
The SafeTx gas estimation call is now inside of a `try..catch`. Because the estimation failed with the initial param, both `recommendedNonce` and `safeTxGas` were not fetched.
If the estimation fails with the initial params, a second request with '0x' data is issued to be able to retrieve the recommendedNonce for the "Review Modal"
See steps of #644 
The Review Modal is expected to be operable now.

fix: handle gas estimation error in createTx

---

src/components/safe-apps/AppCard/index.tsx
src/components/safe-apps/AppCard/styles.module.css

Resolves #779
Added new styles to fix the small issues in our Safe Apps Cards (Logo + Description)
```
.truncateDescription {
display: -webkit-box;
-webkit-line-clamp: 3;
-webkit-box-orient: vertical;
overflow: hidden;
}
```

fix: fixed small visual issues in our Safe Apps Cards (logo + descriptions)

---

src/components/common/ModalDialog/index.tsx

Resolves #744
Adds scoll=body to the MUI Dialog.
Open a Safe with many owners and try to add a new one.
The whole page should now scroll.

Fix: scroll body when modal is too big

---

src/components/sidebar/DebugToggle/index.tsx

Dark mode debug toggle
Another debug toggle in the sidebar for dark mode has been added.
Switch the new toggle and observe the theme change.

fix: add debug toggle for dark mode

---

src/components/tx/AdvancedParams/AdvancedParamsForm.tsx
src/components/tx/AdvancedParams/index.tsx
src/components/tx/GasParams/index.tsx
src/hooks/__tests__/useGasPrice.test.ts
src/hooks/useGasPrice.ts

Resolves #811
Gas price estimation was relying on EIP-1559 params.
I've added fallbacks for non-EIP-1559 chains + hiding the new gas params if on such a network.
Try to execute a tx on Optimism.

Fix: support non-EIP-1559 chains

---

src/pages/index.tsx

Co-authored-by: katspaugh <381895+katspaugh@users.noreply.github.com>
Resolves https://github.com/safe-global/web-core/issues/793
It removes the intermediate route between the starting and final route, so the back button takes you to the starting route and not the intermediate one
1. Go on any non-homepage route (safe view, apps, etc)
2. Switch the network, it should take you to the home page
3. Click back button in the browser, it should take you to the previous route

Use replace to overwrite current path in `pages/index.tsx`

---

src/components/common/SafeTokenWidget/__tests__/SafeTokenWidget.test.tsx
src/components/transactions/TxDetails/TxData/SpendingLimits/index.tsx
src/config/constants.ts
src/hooks/__tests__/useChainId.test.ts
src/hooks/useChainId.ts
src/services/tx/__tests__/tokenTransferParams.test.ts
src/services/tx/tokenTransferParams.ts

Rinkeby is deprecated, so we'll use Görli as our default chain on dev.

Fix: set default testnet to Goerli

---

src/components/common/AddressInput/useNameResolver.ts
src/components/create-safe/steps/ConnectWalletStep.tsx
src/components/create-safe/steps/OwnerPolicyStep.tsx
src/components/create-safe/steps/OwnerRow.tsx
src/components/create-safe/steps/ReviewStep.tsx
src/components/create-safe/steps/SetNameStep.tsx
src/components/load-safe/steps/SafeOwnersStep.tsx
src/components/load-safe/steps/SafeReviewStep.tsx
src/components/load-safe/steps/SelectNetworkStep.tsx
src/components/load-safe/steps/SetAddressStep.tsx
src/components/tx/TxStepper/index.tsx
src/components/tx/TxStepper/useTxStepper.ts

Resolves #768 
- Extends `useTxStepper` to optionally update step data when going back
- Updates data in create/load safe forms when going back
- Fixes an issue where owner AddressBook names would overwrite a newly typed name in create/load safe forms
2. Create a new Safe
3. Input data in every screen and press back and continue
4. Observe that the data is persisted
5. Load an existing Safe
6. Change data in every screen and press back and continue
7. Observe that the data is persisted
8. Change the name of an existing owner that has an AB entry and press back/continue
9. Observe that the newly typed name is shown instead of the AB name

fix: Persist stepper data when going back in create/load safe

---

.github/workflows/deploy-staging.yml
.github/workflows/lint.yml
docs/release-procedure.md
package.json
src/hooks/__tests__/usePathRewrite.test.ts
src/hooks/usePathRewrite.ts
src/pages/404.tsx

Copies HTML files to S3 w/o an extension but with the right content-type, so that URLs like `/welcome` work along with `/welcome.html`.
Also I moved the 404 redirect code to the 404 page itself, I think it makes more sense than a common hook.

Chore: deploy HTML files w/o extension

---

src/styles/globals.css

Resolves #812
The `padding-top` which Beamer adds to the `body` has been removed. As such, the content does not move down the page when the top bar is present.
Open a Safe on Rinkeby and observe the top bar from Beamer (if it is not there, open the PR deployment in an Icognito/Private Window or set an announcement in the Beamer admin panel). Observe no content shift downwards.

fix: remove Beamer top padding

---

scripts/generate-routes.js
src/components/settings/SafeAppsPermissions/index.tsx
src/components/sidebar/SidebarNavigation/config.tsx
src/config/routes.ts
src/pages/settings/safe-apps/index.tsx

Adjusting the Safe Apps settings route
The Safe Apps settings router has been renamed to `/settings/safe-apps` and the title adjusted to match our lowercase styling.
Open the Safe Apps permissions settings and observe the title be "Safe Apps permissions" and route `/settings/safe-apps`

fix: rename Safe Apps settings route

---

src/components/tx/SignOrExecuteForm/index.tsx
src/services/tx/__tests__/txSender.test.ts
src/services/tx/txSender.ts

Resolves #658 
An unchecked signer is used when executing a transaction. This resolves the promise as soon as the tx is submitted in the wallet both for smart-contract wallet owners and EOA owners.
The main difference is that `transactionResponse` now returns [mocked values](https://docs.ethers.io/v5/api/providers/jsonrpc-provider/#UncheckedJsonRpcSigner) (except for txHash). Since we only call `.wait()` on it and are not accessing any other properties I implemented this as a general solution instead of only doing it for executions done with smart-contract wallet owner.
- Follow the steps described in #658 
- Test tx executions with EOA and hardware wallets
- Observe that in all cases, the tx modal closes as soon as the tx is submitted in the wallet
Left: `transactionResponse` of a tx …

fix: Use unchecked signer when executing transactions

---

src/components/balances/AssetsTable/index.tsx

Resolves #832
An information icon, with tooltip, is shown when there is no value of an asset.
Open a Safe with assets of no value, e.g. `eth:0x8675B754342754A30A2AeF474D114d8460bca19b` and observe the new icon with tooltip.

feat: show information when no asset value

---

src/components/common/PageHeader/styles.module.css
src/services/tx/txSender.ts

Resolves #849 
Since we are using `box-sizing: content-box` we have to subtract the padding from the total width.
2. Navigate to Tx history, AB and any other page with a page header
3. Observe that the page header content is visible

fix: Adjust page header width

---

src/components/safe-apps/SafeAppsModalLabel/index.tsx

Resolves #838 
Some safe app manifests have a broken `iconUrl`, e.g. the protocol prefix is missing. In that case we display the default safe app icon within the tx modal.
1. Open a safe app with a broken `iconUrl` e.g. ENS safe app
3. Observe the default safe app icon being displayed

fix: Use fallback image for safe app icons in tx modal

---

src/components/transactions/SingleTx/SingleTx.test.tsx
src/components/transactions/SingleTx/index.tsx

Resolves #851
`query.id` is undefined at first because the router is client-side only. So the page is pre-generated with an error message.
I removed the handling of a missing query.id. It will just show an infinite loader if you open a page w/o the query param. I think it's fine because why would you open it like this?

Fix: prevent error flashing in SingleTx

---

src/config/securityHeaders.ts

Resolves #827 
Adds `https://*.ingest.sentry.io` to our CSP allowed src so the Core SDK error is handled without crashing the app.
1. Try to update a 1.0.0 Safe (which will throw an uncatched error)
2. The app should handle the error elegantly and not crash (i.e display our ErrorBoundary component)
None
N/A

fix: add Sentry to the CSP allowed domains

---

src/config/securityHeaders.ts

Resolves #827 
Adds `https://*.ingest.sentry.io` and `https://sentry.io`  to our CSP allowed src so the Core SDK error is handled without crashing the app.
1. Try to update a 1.0.0 Safe (which will throw an uncatched error)
2. The app should handle the error elegantly and not crash (i.e display our ErrorBoundary component)
None
N/A

chore: extend CSP domains

---

src/components/tx/SignOrExecuteForm/SignOrExecuteForm.test.tsx
src/components/tx/SignOrExecuteForm/index.tsx

This PR displays a specific error message in the transaction modal if the connected wallet is connected to the wrong chain or if it is not an owner of the wallet. 
Resolves #769, #722
If the connected wallet is connected to the wrong chain or is not an owner, an explicit error message that explains the problem is displayed above the generic `This transaction will most likely fail.` message. Additionally, it disables the submit button in these cases. I used the error messages from #769 and #722.
1. Create a transaction in the transaction builder
2. Switch the connected wallet to a different chain or connect an unrelated address
3. Open the transaction overlay via the `Send Batch` button

fix: display specific error message for wrong chain and non-owner wallets

---

src/components/address-book/AddressBookHeader/index.tsx
src/components/balances/AssetsHeader/index.tsx
src/components/common/NavTabs/styles.module.css
src/components/common/PageHeader/index.tsx
src/components/common/PageHeader/styles.module.css
src/components/safe-apps/SafeAppsHeader/index.tsx
src/components/settings/SettingsHeader/index.tsx
src/components/sidebar/Sidebar/index.tsx
src/components/sidebar/Sidebar/styles.module.css
src/components/sidebar/SidebarHeader/index.tsx
src/components/sidebar/SidebarHeader/styles.module.css
src/components/sidebar/SidebarNavigation/index.tsx
src/components/transactions/TxHeader/index.tsx
src/pages/transactions/history.tsx
src/pages/transactions/queue.tsx
src/styles/theme.ts

Smaller page headers.
The page header height has been reduced in accordance with [the designs](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=1137%3A50534). The sidebar "header" was also tweaked to incorporate the new design.
It follows [this visual rule as described by @liliiaorlenko](https://5afe.slack.com/archives/C03DAGWJCR5/p1665138752632389):
Note: the address book search is not included in this PR. An issue exists for it [here](https://github.com/safe-global/web-core/issues/835).
Open the Safe and navigate between sections. Observe the correct page header designs.

fix: reduce page header height

---

src/components/safe-apps/AppFrame/useAppIsLoading.ts
src/config/constants.ts

Resolves a thing from the discussion [here](https://github.com/safe-global/web-core/pull/808#discussion_r987615060)
It gives a better name to a constant that defines the number of seconds to elapse before we show a warning that the app takes a long time to load

refactor: slow loading warning timeout constant name

---

src/components/transactions/TxSigners/index.tsx

Resolves transaction stepper colours
The step labels of the transaction stepper now match that of the [Figma designs](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=508%3A15613).
Open the transaction details and observe the correct colours in the stepper.

style: transaction stepper colours

---

src/store/__tests__/txHistorySlice.test.ts

A Jest unit test for the tx history middleware which dispatched `SUCCESS` events if a pending tx was added to the history.
`yarn test txHistory`
None

test: add test for txHistorySlice middleware

---

src/components/tx/GasParams/index.tsx
src/hooks/__tests__/useGasPrice.test.ts
src/hooks/useGasPrice.ts

Resolves #855
Adds a check in GasParams and AdvancedParamsForm to show the old `gas price` if the chain is configured as not supporting EIP-1559.
* Make a tx on Arbitrum (no EIP-1559) – the gas price should be around 0.1 Gwei.
* Make a tx on Mainnet – it should have max priority fee set to 1.5 Gwei.

Fix: don't display EIP-1559 params for non-EIP-1559 chains

---

src/hooks/safe-apps/usePinnedSafeApps.ts
src/hooks/safe-apps/useSafeApps.ts
src/store/index.ts
src/store/safeAppsSlice.ts

Resolves #814 
The pinned ids are still "global" across chains, because apps also exist on multiple chains.
However, `useDeadPinnedSafeAppsRemover` was removing them if they the app doesn't exist on the current chain.
I've removed that hook. The consequence is that pinned ids might potentially linger even if the app was removed, but they shouldn't do harm?
* Pin a few apps
* Switch to another chain, switch back
* The pinned apps should be intact

Fix: don't auto-remove pinned apps

---

src/components/common/SafeTokenWidget/__tests__/SafeTokenWidget.test.tsx
src/components/common/SafeTokenWidget/index.tsx
src/config/constants.ts
src/hooks/safe-apps/useRankedSafeApps.ts

Resolves #829
The Claiming App is now positioned first in the dashboard featured apps.
Note: the Claiming App now has a `"safe-claiming-app"` tag and is instead found by this instead of it's `id` (which changes depending on environment).
Open the dashboard on a network that supports the Claiming App and observe it in first position. If necessary, add the `"safe-claiming-app"` to a network temporarily.

fix: rank Claiming App first on dashboard

---

src/components/safe-apps/SafeAppList.tsx
src/components/safe-apps/SafeAppsSearchPlaceholder.tsx
src/config/constants.ts
src/tests/pages/apps.test.tsx

Resolves #836
Adds placeholder when no searchs apps are found.
Open Safe and search for apps that don't exist. Observe the placeholder with working WalletConnect button (across networks).

fix: placeholder when no apps found

---

src/components/common/ConnectWallet/AccountCenter.tsx
src/components/common/ConnectWallet/WalletDetails.tsx
src/components/common/ConnectWallet/styles.module.css
src/hooks/wallets/useOnboard.ts
src/utils/wallets.ts

Resolves #871
When the user presses "Connect wallet" on mobile, it automatically pops up the WalletConnect modal instead the onboard modal.

Fix: auto-choose to WalletConnect on mobile

---

src/components/common/ScanQRModal/index.tsx

@francovenica:
> For mobile. When you try to use the QR code feature the system will turn on your frontal camera and there is no way to change it to the back camera, making it really hard to read a QR code that way. I'd like to discuss it here first since idk if there is anything we can do about it
I've removed `facingMode: user` so that it choses whichever camera is the default.

Fix: rm QR camera facing mode

---

src/components/tx/TxSimulation/__tests__/utils.test.ts
src/hooks/useGasLimit.ts

Resolves #886
The problem was that we were adding the executing wallet's address as a "fake" signature.
It should only add the "fake" signature if the wallet is an owner and their signature is still missing.
Try to execute a tx as a non-owner – gas estimation should work

Fix: encode executor sig only if owner

---

src/components/common/Notifications/index.tsx
src/components/common/Notifications/styles.module.css
src/components/tx/ErrorMessage/index.tsx
src/hooks/safe-apps/permissions/index.ts
src/hooks/useTxNotifications.ts
src/store/notificationsSlice.ts
src/utils/formatters.ts

Fix: hide error details in notifications

---

src/components/address-book/ImportDialog/index.tsx
src/components/address-book/ImportDialog/styles.module.css

Resolves #889
Internal CSV errors are actual Error objects, not just strings. Our own validation functions return strings, however.
I decided not to change our validation functions, and adjusted the error handling instead. It now supports both errors and strings. Before that it was crashing the app because it couldn't render an error.
Also adjusted the styles a bit.
Upload some non-CSV file. It should show an error and not crash the app.

Fix: AB errors can be Error

---

src/components/transactions/SignTxButton/index.tsx
src/components/transactions/TxSigners/index.tsx
src/components/transactions/TxSummary/index.tsx
src/hooks/useTransactionStatus.ts
src/hooks/useTxPendingStatuses.ts
src/services/tx/__tests__/txSender.test.ts
src/services/tx/txEvents.ts
src/services/tx/txSender.ts
src/store/__tests__/txQueueSlice.test.ts
src/store/pendingTxsSlice.ts
src/store/txQueueSlice.ts

There is a delay of a few seconds between signing a queued tx and receiving the new signature from the tx services. 
Currently the pending signature is only reflected by the signing button and not reflected in the redux store causing the loading spinner to disappear when switching views.
Resolves #872 
Adds a new `PendingStatus.SIGNING` which receives the pending `signerAddress` as payload.
The `txQueueSlice` middleware will update the pending status once the pending signature is returned by the tx service queue.
1. Queue any tx is a 2/n safe
2. add the second signature without executing the tx
3. witness the new "Signing" status which is persisted when switching to the history tab and back
None

fix: add signing to pending tx states

---

src/components/common/Header/index.tsx
src/components/sidebar/NewTxButton/index.tsx

Resolves #897
If the connected wallet is in a different chain that the opened Safe, the "Switch to ..." button is displayed instead of the "New transaction" button.
1. Connect your wallet on Goerli
2. Open a Ethereum Safe
3. The "New transaction" button is replaced by the "Switch to ..." button
4. "Switch to ..." button is removed from the Header
_Mobile resolution_
_Web_

fix: replace "New transaction" button for "Switch to ..." button if on wrong chain

---

.github/workflows/e2e.yml
.github/workflows/safe-apps-e2e.yml
cypress/e2e/smoke/dashboard.cy.js
cypress/e2e/smoke/load_safe.cy.js
cypress/e2e/smoke/tx_history.cy.js
next.config.mjs
src/components/common/NetworkSelector/index.tsx
src/hooks/__tests__/useChainId.test.ts
src/hooks/useChainId.ts
src/hooks/useInitSession.ts
src/pages/404.tsx
src/utils/validation.ts

Resolves #915
Next.js router's dynamic query params are only available in an effect, so useChainId was always falling back to the default/stored chainId.
I've added a fallback to window.location as a workaround. It causes hydration errors tho. We should have probably made `useChainId()` nullable, but now it would mean too many changes.
Also fixes the storing of the last chainId that was self-referential and thus not working properly.
Load the app and see that it doesn't log two page views.

Fix: read chainId directly from location

---

cypress/e2e/smoke/load_safe.cy.js

This flag isn't necessary, only Dashboard and Tx History tests rely on the prod CGW.

Chore: rm prod flag in load_safe.cy.js

---

src/components/transactions/TxSummary/styles.module.css

Resolves #887
The TxSummary mobile styles are reorganized to display one element per line.
1. Go to any transaction history or queue and observe the collapsed TxSummary not cramping
2. If you reduce a lot the viewport width, you will observe the TxSummary is scrollable

style: adjust tx summary grid on mobile viewport

---

src/components/common/NetworkSelector/index.tsx

A small CSS fix: the NetworkSelector wasn't centered vertically.

Fix: center network selector

---

src/components/safe-apps/AppCard/index.tsx

Resolves https://github.com/safe-global/web-core/issues/567
- It extracts buttons used in different versions of the app card component into separate components
- Check if the looks are identical to the production app and make sure buttons still work

refactor: extract reused buttons to separate components

---

src/components/common/NavTabs/styles.module.css
src/components/common/PageHeader/styles.module.css

Makes the tabs a bit bigger and easier to click on.
As per @liliiaorlenko:
> Yes maybe we can widen the area for 5pm and lower the tabs 15px, may this can visually improve it

Fix: space out page header tabs

---

cypress/e2e/smoke/dashboard.cy.js
cypress/e2e/smoke/tx_history.cy.js

Removes the Local Storage workaround after creating Goerli pending transactions in `staging`
1. Delete `SAFE_v2__debugProdCgw` from your local storage
2. Run `dashboard` and `tx_history` tests on Cypress

test: remove LS workaround

---

src/components/dashboard/PendingTxs/PendingTxListItem.tsx
src/components/dashboard/PendingTxs/styles.module.css
src/components/dashboard/index.tsx
src/components/transactions/TxSummary/styles.module.css

Resolves #914
Uses grid templates to style the Transaction queue items in the Dashboard
1. Open a Safe with existing pending transactions
2. Go to Dashboard
3. Reduce the viewport width and observe the pending transactions do not get cramped.
4. Toggle mobile viewport observe the pending transactions do not get cramped.
N/A

style: use grid template for dashboard pending txs

---

src/utils/transactions.ts

Resolves #930 
This was a general issue and not related to smart contract wallets.
When building the tx object for the single tx view, `missingSigners` is only added if the transaction still needs confirmations.
1. Open an m/n safe
2. Create and sign a tx
4. Switch to a different owner
5. Open the tx in the detail view
6. If the tx needs more signatures it should display the checkbox
7. If the tx is already fully signed it should hide the checkbox

fix: Hide execute checkbox if tx has enough confirmations

---

src/components/address-book/ImportDialog/__tests__/validation.test.ts
src/components/address-book/ImportDialog/index.tsx
src/components/address-book/ImportDialog/validation.ts
src/services/exceptions/ErrorCodes.ts

Resolves #889
Removes the extraneous content type validation.
Adds a `papaparse` error type.
Follow #[889](https://github.com/safe-global/web-core/issues/889) steps

fix: better AB import error

---

src/components/create-safe/steps/OwnerPolicyStep.tsx
src/components/create-safe/steps/SetNameStep.tsx
src/components/load-safe/steps/SafeOwnersStep.tsx
src/components/load-safe/steps/SetAddressStep.tsx

Resolves #947 
As a result of #842 we were validating the form data via the RHF `handleSubmit` call when navigating back. Now, we just get the latest form values and pass them to the `onBack` handler without using RHF `handleSubmit`. This has the side-effect, that default values can now be invalid so we need to trigger the RHF validation on mount for the steps that have required fields.
2. Load an existing safe
3. Change the safe address so the field becomes invalid
4. Observe being able to click Back
5. Observe a validation error when going back to the set address step
6. Create a new safe
7. Change the owner address so it becomes invalid
8. Observe being able to click Back
9. Observe a validation error when going back to the owner step

fix: Dont validate create/add safe form data when going back

---

src/components/address-book/AddressBookHeader/index.tsx
src/components/address-book/AddressBookTable/index.tsx

Resolves #949
The length of chain-specific address books are checked to ensure exporting is possible as they can be an empty object.
The "No entries found" placeholder has been updated to include the chain name as well, e.g. "No entries found on Polygon".
1. Remove the `SAFE_v2__addressBook` `localStorage` entry.
2. Add an address book entry on chain X, and another on a chain Y.
3. Observe the export button enabled when on chain Y, even after deleting the entry (as well as "No entries found on Polygon" shown).
4. Switch to chain Y and observe that the address book is still exportable. Deleting the entry disables the button.

fix: disable address book export when no entries exist on all chains

---

src/components/tx/NonceForm/index.tsx
src/services/tx/txSender.ts

Removes use of `>=` in warnings
- `Nonce must be >= ${safeNonce}` ->`Nonce can't be lower than ${safeNonce}`
- `The Safe SDK could not be initialized. Please be aware that we only support >= v1.1.1 Safes.` -> `The Safe SDK could not be initialized. Please be aware that we only support v1.1.1 Safes and up.`
- Create a transaction and edit the nonce to be below that of the Safe nonce. Observe the new warning.
- Open a v1.0.0 Safe and try to create a transaction. Observe the new warning.

fix: use declarative warnings instead of symbols

---

src/components/create-safe/index.tsx
src/components/create-safe/sender.ts
src/components/create-safe/status/hooks/useWatchSafeCreation.test.ts
src/components/create-safe/status/hooks/useWatchSafeCreation.ts
src/components/create-safe/status/usePendingSafeCreation.ts
src/components/create-safe/status/useSafeCreation.test.ts
src/components/create-safe/status/useSafeCreation.ts
src/components/create-safe/steps/ReviewStep.tsx
src/components/create-safe/useEstimateSafeCreationGas.test.ts
src/components/create-safe/useEstimateSafeCreationGas.ts
src/utils/wallets.ts

Resolves #917 
- Caches relevant info of the safe creation tx for the `_waitForTransaction` call to detect a replacement tx
- Only watches an ongoing tx if the original promise is lost (after a page reload)
- Adds the fallback handler address to the safe creation call, not sure about the impact but we forgot to port it from safe-react
- Safe creation on different chains should work as before and there are no instant timeout errors anymore

fix: Cache transaction info on safe creation

---

src/hooks/useSafeNotifications.ts
src/services/contracts/safeContracts.ts

We don't support making transactions with <=1.0.0 Safes, so I've added a notification suggesting using the legacy desktop app for these Safes.
Can be tested on https://legacy-notif.web-core.pages.dev/eth:0xcd2E72aEBe2A203b84f46DEEC948E6465dB51c75

Feat: notify about unsupported Safe versions

---

src/services/pairing/module.ts

Resolves #990
I've copied the chain switching code from safe-react and put it in the pairing module.
* Connect to the Safe mobile app
* Change the web-app network
* Press the "Switch to chain X" button

Fix: switch chain with mobile pairing

---

src/components/new-safe/CreateSafe/index.tsx
src/components/new-safe/StepCard/index.tsx
src/components/new-safe/steps/Step2/index.tsx
src/components/new-safe/steps/Step3/index.tsx
src/components/new-safe/steps/Step3/styles.module.css

Resolves partially #864
Implements the create Safe flow "Review" step according to [Figma](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=192%3A8146) 
Navigate to `/demo` and observe the review step.
The received creation values will be fully functional once https://github.com/safe-global/web-core/issues/931 is resolved.

Review step redesign

---

cypress/e2e/smoke/create_tx.cy.js

After investigation on the failing E2E tests
What's happening is that a transaction was already queued with the same data, thus it won't be duplicated and consequently it won't appear in the Dashboard as the most recent transaction with that nonce. (That's why it start failing out of the sudden - we are only randomizing 20 possible values in the test)
We stop queuing transactions with the same nonce and instead queue transactions with the recommended nonce and verify the transaction is queued in the Single Tx details page instead of the Dashboard.
After signing the transaction, we follow to the SingleTx page by clicking the notification where we can see the newly queued transaction.

test: queue transaction with recommended nonce

---

src/components/tx/ExecuteCheckbox/index.tsx
src/components/tx/SignOrExecuteForm/SignOrExecuteForm.test.tsx
src/components/tx/SignOrExecuteForm/index.tsx

A small UX improvement.
When executing a transaction, a checked Execute checkbox signals that it's an execution, not a signature.
In the "Execute" modal, the checkbox was completely hidden because it's the only option, but with this, we're losing this UI signal. So I made it a disabled checkbox instead of completely hiding it.

Fix: show a disabled Execute checkbox in the Execute modal

---

src/hooks/__tests__/useSafeNotifications.test.ts
src/hooks/useSafeNotifications.ts

The warning was previously showing a link to the desktop app (see #978), but the desktop app itself is now defunct due to a changed Infura key and possible deprecation of the old Gnosis URLs.
So I changed the link to point to the CLI instead.

Fix: 1.0.0 warning - link to the CLI

---

src/services/ExternalStore.ts
src/services/local-storage/__tests__/useLocalStorage.test.ts
src/services/local-storage/useLocalStorage.ts

Caches the localStorage in a globally shared in-memory store (ExternalStore).
This will make `useLocalStorage` slightly faster if the cache is already initialized.
Important for use-cases like the A/B test hook which we'll initialize on app start but it can be read later on another route.

Refactor: external store in useLocalStorage

---

src/hooks/useSafeTokenAllocation.ts

Resolves #1004
All allocation `amount`s are added together.
Open an [investor Safe](https://github.com/safe-global/claiming-app-data/blob/main/vestings/assets/1/investor_vestings.csv), e.g. `eth:0xfB2aD9007F2D62a973f71Af206242eE4bD790b2C` and observe the amount shown in the header now includes their vested amounts as well.

fix: add investor allocation to total

---

src/components/common/Header/index.tsx

Resolves empty widget container in header.
If no Safe address exists, the widget is not rendered.
Open Safe creation and observe no empty widget container:

fix: hide widget when no Safe address exists

---

package.json
src/components/common/Footer/index.tsx

Broken footer link
The `homepage` in `package.json` has been updated to the correct repository, as well as the link corrected to match our release naming format.
Click the version number in the footer and observe the latest release opens.

fix: footer release link

---

src/services/analytics/useGtm.ts

Resolves initial pageviews not being tracked.
The cookie policy is checked before attempting to dispatch a pageview (which ensures GTM is enabled).
Open the Safe in GTM debug view and refresh. Observe the intial pageview being tracked.
Intial pageview is now successfully tracked.

fix: initial pageview event

---

src/hooks/useChainId.ts
src/services/analytics/gtm.ts
src/services/analytics/useGtm.ts
src/utils/url.ts

Resolves #1034 
Sets anonymized path and location in dataLayer when initializing GTM
1. Open the Safe with DebugView
2. Reload the page
3. Scroll around
4. Observe a `user_engagement` event with anonymized path and location values

fix: Anonymize safe address on gtm init

---

src/components/safe-apps/SafeAppsTxModal/ReviewSafeAppsTx.tsx
src/components/tx/SignOrExecuteForm/index.tsx
src/services/exceptions/ErrorCodes.ts
src/services/tx/__tests__/txSender.test.ts
src/services/tx/proposeTransaction.ts
src/services/tx/txSender.ts
src/utils/transactions.ts

Resolves #1035 
The `origin` is now proposed with transactions when created via a Safe App.
Create a transaction via the Transaction Builder and observe the logo/name in the transaction list.

fix: propose transaction with `origin`

---

src/components/tx/SignOrExecuteForm/index.tsx
src/hooks/__tests__/useIsValidExecution.test.ts
src/hooks/useIsValidExecution.ts

Fixes the validation error when executing txs from non-owner wallets.
Resolves #1057
Does not add signature of executing wallet if it is not an owner
Execute a queued txs that is fully signed from a non-owner connected wallet. 
None

fix: execution from non-owner wallets

---

src/components/load-safe/steps/SafeReviewStep.tsx

Resolves #1056
The copy and explorer buttons are now shown next to addresses of the Safe-to-be-added on the review step of the add Safe flow.
Add a Safe and on the review step, observe the copy and explorer buttons next to the Safe/owners.

feat: show copy/explorer buttons on load review

---

src/components/settings/TransactionGuards/index.tsx

Replaces the word "modules" with "transaction guards" in the transaction guards description:

fix: Reword transaction guards description

---

src/components/notification-center/NotificationCenter/styles.module.css

Resolves dark mode colour.
The `stroke` colour of the notification centre bell in dark mode is now set to that of `"text.primary"`. It has to be done via CSS as `stroke` does not seem to play well with `SvgIcon`.
Open the Safe and switch between light/dark mode. Observe the notification centre bell icon change accordingly.
Before:
After:

fix: dark mode notification bell colour

---

src/components/transactions/RejectTxButton/index.tsx
src/components/tx/modals/NewTxModal/index.tsx
src/components/tx/modals/NftTransferModal/ReviewNftTx.tsx
src/components/tx/modals/NftTransferModal/index.tsx
src/components/tx/modals/RejectTxModal/RejectTx.tsx
src/components/tx/modals/RejectTxModal/index.tsx
src/components/tx/modals/TokenTransferModal/ReviewMultisigTx.tsx
src/components/tx/modals/TokenTransferModal/ReviewSpendingLimitTx.tsx
src/components/tx/modals/TokenTransferModal/ReviewTokenTx.tsx
src/components/tx/modals/TokenTransferModal/index.tsx
src/services/analytics/events/modals.ts

Resolves #972
Clicking "Replace" now opens the transaction creation modal in "replacement mode". It is possible to create an asset/NFT transfer with the nonce of the chosen transaction, or alternatively a rejection transaction.
Queue a transaction then click "Replace". Observe that the transaction-to-be-created will be of the same nonce as that which will be replaced.
Clicking "Rejection transaction" in the creation modal emits:
```ts
{
event: "customClick",
chainId: "",
eventCategory: "modals",
eventAction: "Reject transaction"
}
```
Note: the button style has changed since recording this GIF.
New variant:

feat: replace specific transactions

---

src/components/dashboard/PendingTxs/PendingTxsList.tsx
src/components/tx/NonceForm/index.tsx
src/hooks/useTransactionType.ts
src/utils/tx-list.ts

Resolves #973
When creating a transaction, the Safe nonce field now shows autocomplete options with the transaction type which sets the associated nonce on click. Conflicting transactions show the type of the most recently queued one (as we do in the dashboard).
Note: the transaction "info", e.g "withdraw", "n action(s)" is not implemented as it would require a big refactor of `TxInfo` to extract component logic into functions. Should we want to include this, we should include it in a separate PR. After discussion with the team, we think the current implementation is a sufficient MVP.
Ensure transactions are already queued and create a new transaction. When editing the nonce an autocomplete dropdown should allow selection of previous nonces, as well as allowing manual entry. All …

feat: add autocomplete to `NonceForm` nonce

---

src/components/tx/modals/NewTxModal/index.tsx

Resolves #1069 
We [set the `initialData` of `TokenTransferModal` and `NftTransferModal`](https://github.com/safe-global/web-core/blob/dev/src/components/tx/modals/NewTxModal/index.tsx#L88-L91) when [sending to a contact from the address book](https://github.com/safe-global/web-core/blob/dev/src/components/address-book/AddressBookTable/index.tsx#L163). 
We weren't setting a default `recipient` value [for our `formData`](https://github.com/safe-global/web-core/blob/dev/src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx#L72). An empty string is now used by default.
Unable to replicate.

fix: set default `recipient`

---

src/components/common/Header/styles.module.css
src/components/common/NetworkSelector/styles.module.css
src/components/new-safe/CardStepper/styles.module.css
src/components/new-safe/CreateSafe/styles.module.css
src/components/new-safe/steps/Step0/index.tsx
src/components/new-safe/steps/Step1/index.tsx
src/components/new-safe/steps/Step1/styles.module.css
src/components/new-safe/steps/Step2/index.tsx
src/components/new-safe/steps/Step2/styles.module.css
src/components/new-safe/steps/Step3/index.tsx
src/components/new-safe/steps/Step4/StatusMessage.tsx
src/components/new-safe/steps/Step4/index.tsx

- Adjust button layout for safe creation steps
- Remove padding from Stepper and instead handle row spacing of each view with a single css class and optimize it for smaller screens
- Remove negative margins from `Divider` elements
- Improve `NetworkSelector` clickable area
- Adjust Threshold select size and color
- Click through each create safe step on `/new-safe/create` and compare with Design

[Safe Creation] Layout adjustments

---

next.config.mjs

Upload sourcemaps along with the code, so that we can see better traces on Sentry and in the console on prod.

Chore: enable sourcemaps on prod

---

src/services/ls-migration/addressBook.ts
src/services/ls-migration/tests.test.ts

Resolves invalid address book entry migration
The validity of migrated a migrated address/name is checked prior to entry insertion.
Add an invalid address and/or empty name on the old deployment. Clear the migration flag and observe the invalid entries not migrate to the new deployment.

fix: validate migrated address book

---

src/utils/__tests__/formatters.test.ts
src/utils/formatters.ts

Resolves [ongoing Sentry errors](https://sentry.io/organizations/gnosis/issues/3725083966/?project=6769196&query=is%3Aunresolved&referrer=issue-stream&sort=date&statsPeriod=14d)
An empty string fallback has been added to `shortenAddress` if passed a falsy value.
It is covered by tests.

fix: fallback to empty string when shortening address

---

src/hooks/__tests__/useSafeNotifications.test.ts
src/hooks/useSafeNotifications.ts
src/services/contracts/safeContracts.ts

Notification link for legacy Safes
Instead of linking to the CLI, we link to the upgrade page of the `safe-react` deployment for older Safes not supported by `web-core`.
Open a <1.1.1 Safe and observe the new link in the notification.
Note: redirection on `safe-react` will still happen until we merge [this](https://github.com/safe-global/safe-react/pull/4113).

fix: redirect to old deployment for legacy Safes

---

src/pages/index.tsx

Resolves #1112
As we don't want to interact with the DOM, `useLayoutEffect` removed the error (which was caused by calling `router.replace` too many times).
Open `/` and observe no error in the console. Navigating to the following should work as before:
- Previously used Safe: `?safe=xyz:0x123`
- Currently selected network: `?chain=xyz` (no added Safe)
- Otherwise: `/welcome`

fix: "Aborting fetching component for router"

---

src/components/common/MetaTags/index.tsx

Resolves truncated `meta` description on Twitter.
The description has been shortened [as per agreed](https://5afe.slack.com/archives/C03FNGQ1LTU/p1667921041810869?thread_ts=1667840653.495219&cid=C03FNGQ1LTU):
```
Safe (prev. Gnosis Safe) is the most trusted platform to manage digital assets on Ethereum and multiple EVMs. Over $40B secured.
```
Draft a Tweet with the PR link and observe the above description.

fix: shorten `meta` description

---

src/components/transactions/TxDetails/index.tsx
src/components/transactions/Warning/index.tsx

Resolves #898
A new warning is shown when a proposed transaction has no signatures.
Open `/gor:0xF3E977e7Eea1A91ce5B2d5077e5A7195Ae18b722/transactions/tx?id=multisig_0xF3E977e7Eea1A91ce5B2d5077e5A7195Ae18b722_0xc0c5380e113ecff6054c69d02fe7d5ee753db29635548c80794bd028cf614bb5` and observe the warning.

feat: unsigned warning

---

src/components/common/SafeTokenWidget/styles.module.css
src/components/dashboard/SafeAppsDashboardSection/SafeAppsDashboardSection.tsx
src/components/dashboard/styled.tsx
src/components/safe-apps/AppCard/index.tsx
src/components/safe-apps/AppCard/styles.module.css
src/components/safe-apps/SafeAppLandingPage/SafeAppDetails.tsx
src/components/safe-apps/SafeAppsInfoModal/index.tsx
src/components/safe-apps/SafeAppsSection/CollapsibleSection.tsx
src/components/safe-apps/SafeAppsSection/DefaultSection.tsx
src/components/settings/SafeAppsPermissions/index.tsx
src/components/sidebar/NewTxButton/styles.module.css
src/components/sidebar/SafeList/index.tsx
src/components/sidebar/SafeList/styles.module.css
src/styles/theme.ts

Resolves styling issues mainly affecting the Safe Apps list.
It also includes tweaks to some generic rules as the border radius for buttons and container elements.
Update styles on Safe Apps list to follow design guidelines
https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=1%3A7
Update generic styles to follow design guidelines
https://www.figma.com/file/HKW5iarMST9rL7Kxkf59qY/MUI-for-Figma?node-id=10838%3A66318
Before
After

fix: Safe Apps list styles issues

---

src/components/common/Notifications/index.tsx
src/components/tx/SignOrExecuteForm/index.tsx
src/hooks/useTxNotifications.ts
src/services/exceptions/ErrorCodes.ts
src/services/tx/__tests__/generateSafeTxHash.test.ts
src/services/tx/generateSafeTxHash.ts
src/services/tx/txEvents.ts
src/services/tx/txSender.ts

Resolves #704
- A new `TxEvent.SIGNING` event is now dispatched before signing a transaction (mirroring `safe-react`).
- The `generateSafeTxHash` function allows for hash generation from transaction data. It is passed to `TxEvent.SIGNING`/`TxEvent.EXECUTING` events and displayed in notification `"Details"` (if present).
- Notifications with `"Details"` now persist
Observe that when signing/executing a transaction, `"Details"` now exist in the dispatched notifications with the `safeTxHash`. Both notifications persist.

feat: add `SIGNING` event + `safeTxHash` details

---

cypress/e2e/smoke/balances.cy.js
cypress/e2e/smoke/create_tx.cy.js

Broken `create_tx` E2E test in the CI
Spy and wait for the `/estimations` network request
Stub the second `/estimations` request
Spy and wait for the `/propose` network request

test: spy and wait for slow network requests

---

src/components/safe-apps/AppFrame/TransactionQueueBar/index.tsx
src/components/transactions/TxListItem/ExpandableTransactionItem.tsx

For some reason we had the `unmountOnExit` prop set for the accordions which made the animation look choppy.
Before:
https://user-images.githubusercontent.com/5880855/200006728-112dabed-4663-4dbb-bb0f-1648907e4a18.mov
After:
https://user-images.githubusercontent.com/5880855/200006743-fe18f28c-eeaf-40df-b1cd-afb1e331725e.mov

fix: Keep accordion details mounted for transition

---

src/components/dashboard/GovernanceSection/GovernanceSection.tsx
src/components/dashboard/GovernanceSection/styles.module.css

Gives a frame to display the Governance components inside a collapsible section
Part of #974 
1. Go to dashboard and observe the new section

[Governance Visibility] Dashboard section

---

src/components/create-safe/status/useSafeCreationEffects.ts
src/components/create-safe/types.d.ts

Resolves #1121 
We were using `pendingSafe.address` instead of `pendingSafe.safeAddress`. I opted against refactoring the types to keep this PR small but added a TODO.
1. Create a new safe
2. Observe that it is being added to the added safes list

fix: Store newly created safe

---

src/components/common/EthHashInfo/index.tsx
src/components/common/EthHashInfo/styles.module.css
src/components/common/ModalDialog/index.tsx
src/components/common/ModalDialog/styles.module.css

Resolves #1046
Sets min-width in the `TxModal` and reduces the addresses font-size to always have addresses and buttons visible inside the Modal.
2. Open create a new transaction modal.
3. All legit addresses (40 chars) represented in the modal shall not push the buttons out of visible area.
N/A

fix: adjust modals to hug long addresses

---

.github/workflows/e2e.yml
.github/workflows/lint.yml
.github/workflows/safe-apps-e2e.yml
.github/workflows/test.yml

Updates some actions to use the latest version, to remove Node 12 deprecation warning in Github actions

Update actions to latest version

---

src/components/new-safe/steps/Step3/index.tsx
src/components/new-safe/steps/Step4/logic/index.ts
src/components/new-safe/steps/Step4/useSafeCreation.ts
src/components/welcome/index.tsx
src/hooks/useTxNotifications.ts
src/store/notificationsSlice.ts

Part of #864 
- Shows a notification with more detailed errors
- Closes the notification when the user presses Retry
- Extends the notification slice to support closing all notifications
- Temporarily links to new safe creation on welcome page to make testing easier
3. Reject the tx
4. Observe a notification being shown
5. Cancel a tx
6. Observe a notification being shown
7. Press Retry
8. Observe the notification disappearing

fix: Show error notifications in safe creation

---

src/components/tx/modals/NewTxModal/index.tsx
src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx

Resolves #1111
The `SendAssetsForm` now has `defaultValues`. Before, the `address` could've been `undefined` and was being passed down to `EthHashInfo`.
Open the send assets modal and observe no errors in the console. We should also see no further Sentry logs regarding this issue either.

fix: set `defaultValues` of `SendAssetsForm`

---

src/utils/wallets.ts

Resolves #1134 
- Checks that the method exists before calling it
This error most likely happens with older versions of the metamask extension. It was implemented [in 2018](https://github.com/MetaMask/metamask-extension/commit/84874a639d217da36926869fa3cb235c05725cf5)
- Connect to the safe via MM
- Lock the Account from MM
- Observe the wallet disconnecting in the safe

fix: Check that isUnlocked exists before calling

---

src/components/common/PsaBanner/index.module.css
src/components/common/PsaBanner/index.tsx

Resolves #1146
The banner text/link has been updated to:
"app.safe.global is Safe's new official URL. Export your data from the old app here"
"here" links to either the settings of the open Safe (`/app/{{safe}}/settings/details`) or `/export`.
Open the Safe and observe the banner, with link to relevant route. On smaller resolutions, the close button should move below the text.

fix: update banner text + mobile layout

---

src/components/tx/ExecuteCheckbox/index.tsx
src/components/tx/modals/NewTxModal/CreationModal.tsx
src/components/tx/modals/NewTxModal/ReplacementModal.tsx
src/components/tx/modals/NewTxModal/TxButton.tsx
src/components/tx/modals/NewTxModal/index.tsx
src/components/tx/modals/NewTxModal/styles.module.css

Resolves #718 
The new create/replace transaction modals have been separated, with the latter including a stepper according to [this design](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=2104%3A59002).
- Queue a transaction, then click replace. Observe the new modal, with the buttons working as intended.
- The create modal should function as before, displaying the Transaction Builder.

feat: replacement modal

---

src/components/common/PageLayout/SideDrawer.tsx
src/components/common/PageLayout/index.tsx
src/components/common/PageLayout/styles.module.css
src/components/sidebar/Sidebar/index.tsx
src/components/sidebar/Sidebar/styles.module.css
src/styles/globals.css

A small refactoring based on #1169.
Extracts the collapsible drawer logic into a SideDrawer component. PageLayout only lifts the state.
The Sidebar component is untouched, it's the same as on dev.

Refactor: extract sidebar drawer

---

cypress/e2e/safe-apps/apps_list.cy.js
cypress/e2e/smoke/create_tx.cy.js

Unreliable transaction creation test.
- The timeout for E2E wallet connection has been increased
- Tests relevant to the estimation/proposal/safe-apps endpoint incerceptions have been moved inside [the `intercept` callback](https://docs.cypress.io/api/commands/intercept#Using-the-yielded-object)
Observe the test passes in the E2E job.

fix: improve reliability of E2E tests

---

src/components/new-safe/steps/Step0/index.tsx

Resolves #1173 
- Disables auto navigation from Step 0 if there is a pending safe
3. Reject the transaction in your wallet
4. Click the Safe logo
5. Go to /welcome and click create new safe
6. Observe being navigated to the status screen
7. Observe the app not crashing

fix: check for pending safe creation in first step

---

src/styles/theme.ts

Based on user feedback, we're making the toggle color green when checked. Only affects the light mode.
Color approved by the designers.

Fix: MUI Switch default color

---

src/hooks/__tests__/useChainId.test.ts
src/hooks/__tests__/usePathRewrite.test.ts
src/hooks/useChainId.ts
src/hooks/usePathRewrite.ts
src/services/exceptions/ErrorCodes.ts

Resolves #1154 
- Instead of throwing an error, we navigate the user to the `/welcome` page if there is an invalid shortname in the URL. This is the same behaviour as in safe-react.
- Error is being logged to the console and sentry instead
1. Open a safe
2. Change the URL shortname to an invalid shortname e.g. "test" or "undefined"
3. Observe being navigated to the welcome page
4. Change the URL shortname to a valid shortname for which the safe doesn't exist
5. Observe a Safe couldn't be loaded error

fix: handle invalid shortname in url

---

src/components/tx/modals/NewTxModal/index.tsx
src/styles/colors-dark.ts
src/styles/colors.ts
src/styles/onboard.css
src/styles/theme.ts
src/styles/vars.css

@liliiaorlenko provided a new, more contrastive, backdrop color. It's the same in both dark and light modes.

Fix: backdrop color

---

src/components/common/ScanQRModal/index.tsx
src/styles/theme.ts

Resolves #1171 
Resolves #1185 
- Uses `useRef` instead of `createRef` and fixes side effect dependencies to prevent rerenders
3. Navigate to the add owner screen
4. Press the QR Button with camera allowed
5. Press the Upload an Image button
6. Observe the app not crashing

fix: QR reader crashes app

---

src/components/new-safe/CreateSafe/index.tsx
src/components/new-safe/OverviewWidget/index.tsx

Resolves #1209 
- Displays the overview widget in step 1 with a message 
1. Open the new safe creation flow
2. Disconnect wallet
3. The overview widget is visible

fix: Add overview widget to step 1 in safe creation

---

src/components/create-safe/InfoWidget/index.tsx
src/components/create-safe/status/useSafeCreation.ts
src/components/new-safe/steps/Step1/index.tsx
src/components/new-safe/steps/Step2/index.tsx
src/components/new-safe/steps/Step4/useSafeCreation.ts
src/services/analytics/events/createLoadSafe.ts

Part of #864 
- Emits missing safe creation events
- Adds new events for opening hints
1. Go through the new safe creation flow
2. Check that the safe name is sent when submitting step 2
3. Check that the number of owners and the threshold are sent when submitting step 3
4. Check that an event is sent once the transaction is confirmed in the wallet (this existed in safe-react but not in web-core)
5. Check that an event is sent when opening a hint
- Adds `CREATE_SAFE_EVENTS.OPEN_HINT` event

fix: Add missing safe creation events

---

src/components/create-safe/status/__tests__/useSafeCreation.test.ts
src/components/create-safe/status/useSafeCreation.ts
src/components/new-safe/steps/Step4/useSafeCreation.ts

Resolves #1214 
- Uses the `web3ReadOnly` provider to watch an existing tx
1. Navigate to the new safe creation flow
2. Create a new safe and confirm the transaction
3. Disconnect your wallet
4. Reload the page
5. Observe the UI showing `Transaction is being executed.`
6. Observe the UI watching the tx and updating the status once the tx has been executed or canceled

fix: Watch safe creation tx even without a connected wallet

---

cypress/e2e/smoke/create_tx.cy.js

Changes how we wait for intercepted requests. 
The propose request timed out a lot of times.

e2e: improve reliability of create_tx cypress test

---

src/pages/index.tsx

Resolves #1172
If an address is present in the URL, it will redirect to the `/home` of that Safe.
Open `/{{shortName}}:{{address}}` with no session cache (e.g. in Incognito) and observe that it directs to `/{{shortName}}:{{address}}/home`. When opening the Safe with a `lastSafe` cached, it should open to that one.
All Safe-specific routes should function as before, e.g. opening `/{{shortName}}:{{address}}/settings/setup` should not direct to `/{{shortName}}:{{address}}/home`.

fix: redirect to `/home` of Safe present in URL

---

package.json
src/components/transactions/TxDetails/index.tsx
src/components/transactions/Warning/index.tsx
yarn.lock

Resolves default warning when no signatures exist.
A warning should no longer shown by default when no signatures are present, e.g. when queuing an approval of a nested Safe. Instead, they are shown when the `trusted` flag is `false`.
Note: no warning will be shown [until the flag is implemented](https://github.com/safe-global/safe-client-gateway/issues/1005).
Open an "untrusted" transaction and observe the warning

fix: show warning based on `trusted` flag

---

src/components/dashboard/GovernanceSection/GovernanceSection.tsx
src/components/dashboard/index.tsx
src/components/safe-apps/AppFrame/index.tsx

Mini Safe apps iframes are displayed in the dashboard
Resolves #974

feat: Dashboard governance widgets

---

src/components/dashboard/CreationDialog/index.tsx
src/components/new-safe/CreateSafe/index.tsx
src/components/new-safe/steps/Step2/useSafeSetupHints.ts
src/components/new-safe/steps/Step4/StatusMessage.tsx

Part of #864 
- Fixes a typo in the safe creation modal
- Removes uppercase from hint tags
- Adjusts threshold hint title to include "policy"
- Adjusts the message shown once the safe is successfully indexed

fix: Safe cration text changes

---

src/components/dashboard/GovernanceSection/GovernanceSection.tsx

Part of https://github.com/safe-global/web-core/issues/1221
Allows passing a dark mode flag in the url to the governance widgets
Reads app dark setting and passes it in the `appUrl`
Needs https://github.com/safe-global/safe-react-apps/pull/580 to be merged or it will break parsing the widgets ID
N/A
Nothing changes

feat: pass dark mode in the widgets url

---

src/components/tx/modals/NftTransferModal/SendNftForm.tsx

Resolves #1227
The select is now using InfiniteScroll to load more NFTs as you scroll the popup.
- Open a Safe with tons of NFTs
- Open the New transaction -> Send NFT modal
- Try to select some NFT beyond the first page

Refactor: paginated NFT select

---

src/components/dashboard/GovernanceSection/GovernanceSection.tsx

_Note:_ I've branched from `one-governance-widget` but it will be merged into `epic-governance`
Part of https://github.com/safe-global/web-core/issues/1221
The theme is passed to the `<AppFrame>` together with the widget ID as `#<widget_id>+<theme>`
Can be tested against the https://github.com/safe-global/safe-react-apps/pull/588 PR deployment

feat: pass dark theme flag in url hash

---

src/components/new-safe/CardStepper/useCardStepper.ts
src/components/tx/TxStepper/useTxStepper.ts

Resolves #1248 
- Adds the current step as label to the tracked event
1. Open the safe creation
2. Click Next
3. Observe that the GTM event in the console contains the current step as label

fix: Send current step with tracking event

---

src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx
src/components/tx/modals/TokenTransferModal/useIsSafeTokenPaused.ts
src/components/tx/modals/TokenTransferModal/useSafeTokenWarning.ts
src/services/tx/safeUpdateParams.ts

Resolves #1244 
- Checks the `unpaused` property of the safe token contract
- Displays an error message and disables the next button if the safe token is selected in the transfer modal
1. Open a Safe on Mainnet that has Safe Tokens
2. Try to transfer them
3. Observe an error message and the next button being disabled
4. Select a different token
5. Observe the Next button becoming enabled again

fix: Dislay an error when trying to transfer safe token

---

src/components/create-safe/InfoWidget/styles.module.css
src/components/transactions/TxDetails/index.tsx

Temporarily comment out the Untrusted tx badge from #1220.
To be restored after #1261 is closed.

Fix: comment out the untrusted badge

---

src/components/safe-apps/AppFrame/index.tsx

Resolves #1246 
Added a [`sandbox`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) attribute to the Safe Apps iframe in the past
We discussed in [this Problem Statement](https://www.notion.so/gnosis-safe/Alternative-to-iframes-e6f93ee4cd834fa99f57b5f420cf7b5a) the possibility of adding the sandbox attribute in the iframe.
```
const IFRAME_SANDBOX_ALLOWED_FEATURES = 'allow-scripts allow-same-origin allow-popups allow-forms allow-downloads allow-orientation-lock'
```
- `allow-scripts` : Lets the resource run scripts (needed for all the Safe Apps)
- `allow-same-origin` : Needed to the [same-origin policy](https://developer.mozilla.org/en-US/docs/Glossary/Same-origin_policy) (Most of Safe App access to [data …

Added sandbox attribute to Safe App iframe

---

src/config/constants.ts

Shows the token badget with the allocated tokens.
Resolves #1272
- adds the goerli safe token address
Open a safe with allocation on goerli (i.e. `gor:0xAecDFD3A19f777F0c03e6bf99AAfB59937d6467b`)

add safe token address to goerli

---

src/components/safe-apps/AppFrame/TransactionQueueBar/styles.module.css
src/styles/theme.ts

The Tx queue is shown in front of the transaction modal, making interaction a little bit tricky:
Adjusted the z-index value for the transaction queue bat to `z-index: 1200`:
```
.barWrapper {
position: absolute;
bottom: 0;
right: 0;
width: 100%;
/* MUI Drawer z-index default value see: https://mui.com/material-ui/customization/default-theme/?expand-path=$.zIndex */
z-index: 1200;
/*this rule is needed to prevent the bar from being expanded outside the screen without scrolling on mobile devices*/
max-height: 90vh;
}
```
1. Connect walletconnect with a safe with pending transactions.
2. click on the transaction queue.
3. Connect to Cow Swap Dapp.
4. Disconnect your wallet.
5. Click on connect wallet to see the onBoard Modal.
6. Create a eth-WETH swap transaction.
7. see the transaction …

fix: updated tx queue bar zIndex to avoid overlaps

---

package.json
src/services/onboard.ts
yarn.lock

Resolves #1233 
Opened a bug ticket in the onboard repo: https://github.com/blocknative/web3-onboard/issues/1385
- Downgrades `@web3-onboard/core` to v2.8.5
This can be tested either with WC or Mobile Pairing
2. Connect via mobile app that has 2 owner keys
3. Switch to the other owner via mobile app
4. Observe the address updating on web
5. Switch the chain via mobile app
6. Observe the chain changing on web

fix: Account switching with mobile pairing and WC

---

.github/workflows/cla.yml

Resolves #1257
Copies the action from safe-react. The only difference is it's now linking directly to the website instead of an .md file in the repo.

Chore: add a CLA checking action

---

src/components/transactions/RejectTxButton/index.tsx
src/components/tx/NonceForm/index.tsx
src/components/tx/modals/NewTxModal/ReplacementModal.tsx
src/components/tx/modals/NewTxModal/index.tsx
src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx
src/components/tx/modals/TokenTransferModal/index.tsx
src/store/safeInfoSlice.ts

Resolves isses found [here](https://github.com/safe-global/web-core/pull/1079#issuecomment-1333132981).
1. Spending limit transactions are not shown creating a transaction via the replacement flow.
2. The backdrop no longer flickers whent the autocomplete dropdown is open.
3. Transactions with nonce 0 now open the replacement modal.
4. Disable duplicate rejection transactions.
1. Attempt to replace a transaction. Observe that spending limit options are not displayed.
2. Open the nonce autocomplete limit and observe no backdrop flicker.
3. Attempt to replace a transaction with nonce 0. Clicking "Replace transaction" in the modal should open the next step.
4. The replacement button is now always shown. Attempting to replace a transaction that already has a rejection transaction will render …

fix: replace nonce 0, flicker, no spending limit + disable duplite rejections

---

.github/workflows/cla.yml
src/components/settings/DataManagement/index.tsx
src/components/settings/ImportAllDialog/index.tsx
src/pages/import.tsx

* Add a link to the old app on the import page
* Make the tooltip text inline
* Show the "Overwrite data?" alert only after dropping a file

Fix: link to old app from the import page

---

.github/workflows/cla.yml

The action we've been using has stopped working for external contributors. I've replaced it with a simple comment for non-org members, urging to sign the CLA.

Chore: replace the CLA action with a simple comment

---

src/components/create-safe/logic/index.ts
src/components/create-safe/status/__tests__/useSafeCreation.test.ts
src/components/create-safe/steps/ReviewStep.tsx
src/components/new-safe/steps/Step3/index.tsx
src/services/contracts/safeContracts.ts
src/services/tx/safeUpdateParams.ts

Resolves #1236
The Compatibility Fallback Handler is now retrieved via `safe-core-sdk`.
Safe creation should function as normal.

fix: get Compatibility Fallback Handler from SDK

---

src/components/tx/modals/TokenTransferModal/ReviewTokenTx.tsx
src/utils/__tests__/formatNumber.test.ts
src/utils/formatNumber.ts

Resolves #705
Implements a new formatter `formatAmountPrecise` to format a number with a passed precision without adhering to our style guide notation.
Uses the app `formatAmountPrecise` formatter for review modal header's amounts.
1. Click to create a transaction with thousands and decimals
2. Observe the review modal displays the amount formatted as per locale
N/A

Fix format amount review modal

---

src/components/tx/TxStepper/vertical.tsx

Related to #968 
- The vertical tx stepper passes the category parameter so that the creation flow uses the same `eventCategory` as the new safe creation flow
1. Open the safe with the AB test set to false
2. Navigate to `/welcome`
3. Create a new safe
4. Observe that the GTM events include `eventCategory: create-safe` instead of `modal`
- This will track all safe creation events under the same `eventCategory`

fix: Track safe creation events under the same category

---

src/components/transactions/TxDetails/TxData/SettingsChange/index.tsx
src/components/transactions/Warning/index.tsx

Resolves #1328
The transaction details of threshold altering transactions has been changed from "Increase/decrease confirmation policy to:" to "Required confirmations for new transactions:". The associated tooltip from "This transaction potentially alters the number of confirmations required to execute a transaction." to "This transaction potentially alters the number of confirmations required to execute a transaction. Please verify before signing."
Create a transaction that alters the threshold of the Safe and observe the new details/tooltip.

fix: alter threshold change warning text

---

src/components/tx/NonceForm/index.tsx

Resolves #1311
The `typeof  recommendedNonce` is checked that it is a `'number'` instead of whether it is truthy.
1. Create a new Safe and create a new transaction.
2. Edit the nonce to >0 and reset the nonce to the recommended value.
3. Observe that it sets to 0.

fix: allow resetting to recommended nonce of 0

---

src/components/new-safe/steps/Step4/StatusMessage.tsx

Resolves #1299 
- Error color on the status screen is now red instead of green
- Every other status is now colored blue instead of orange
1. Open the new safe creation flow
2. Submit the form
3. Observe a blue status message
4. Reject the transaction
5. Observe a red status message

fix: Change status colors in safe creation

---

src/components/tx/modals/NewTxModal/ReplacementModal.tsx
src/components/tx/modals/NewTxModal/TxButton.tsx

Mixture of nouns and verbs in the transfer modal.
The "Contract interaction" text has been changed to "Build transaction" and the title of the replacement button area to "Select how you would like to replace this transaction" in order to match the semantics of the buttons that are all now titled with verbs ("Rejection transaction" is now "Reject transaction").
1. Open the new transaction modal either by the sidebar or transaction replacement.
2. Observe the new text.

fix: adjust text of buttons in transfer modal

---

src/components/common/SafeTokenWidget/__tests__/SafeTokenWidget.test.tsx
src/components/common/SafeTokenWidget/index.tsx
src/hooks/__tests__/useSafeTokenAllocation.test.ts
src/hooks/useSafeTokenAllocation.ts

The token widget did not take token balance and the redeem deadline into account.
Resolves #1208 
Adjusts the formula to `totalAllocation - tokensClaimed + balance`
When computing the total allocation after the `redeemDeadline` has passed we ignore unredeemed allocations.
- On görli the redeem deadline was on 30th of November, meaning unredeemed allocations should not be counted anymore:
- Safe with only user airdrop but not ecosystem airdrop redeemed `gor:0x5f310dc66F4ecDE9a1769f1B7D75224dA592201e`
- On mainnet this date is on the 27th of Dec
None

Adjust safe token widget allocation formula

---

package.json
src/components/settings/ContractVersion/index.tsx
src/components/settings/TransactionGuards/index.tsx
src/components/tx/TxSimulation/utils.ts
src/components/tx/modals/BatchExecuteModal/ReviewBatchExecute.tsx
src/hooks/coreSDK/safeCoreSDK.ts
src/hooks/coreSDK/useInitSafeCoreSDK.ts
src/services/contracts/safeContracts.ts
src/services/tx/safeUpdateParams.ts
src/utils/helpers.ts
yarn.lock

NOTE: This cannot be merged until https://github.com/safe-global/safe-gateway-typescript-sdk/pull/108 is merged/released and a new lock is generated.
Resolves #1327
The nullable `SafeInfo['version']` for unsupported base contracts is now handled.
Open `matic:0xF3aa45696f8Bc702D41d11b365C067f26f79fcaA` and open the module settings. Observe no error/app crash.

fix: handle nullable `SafeInfo['version']`

---

src/components/tx/modals/NewTxModal/ReplacementModal.tsx
src/components/tx/modals/NewTxModal/styles.module.css

Resolves #1357 
- Aligns the replacement modal buttons on smaller screens to fit the viewport
2. Replace an existing transaction
3. Observe that the buttons are aligned
4. Reduce the screen width
5. Observe that all buttons are still visible

fix: Replacement modal button alignment on mobile

---

src/hooks/useTransactionType.ts

Resolves #1354 
change custom tx fallback icon
Open `eth:0x0DA0C3e52C977Ed3cBc641fF02DD271c3ED55aFe/transactions/tx?id=module_0x0DA0C3e52C977Ed3cBc641fF02DD271c3ED55aFe_0xe14278097fc7d0f462d2913d36185505ee09f8476ac899620c409eb0afaa812a_0xa65aaf534f1a4620` on production and observe the type be "Contract interaction".

fix: change custom tx fallback icon

---

package.json

Updates `safe-core-sdk` version to `v3.2.1`.
This fixes this issue: https://github.com/safe-global/web-core/issues/1343

Update safe-core-sdk to v3.2.1

---

.github/workflows/deploy.yml

A small tweak of the branch name sanitizer. Replace non-alphanumeric symbols with underscores instead of nothing.

Chore: replace non-alpha chars with _ in PR deployment

---

.eslintrc.json

Enables `no-constant-condition` eslint rule which detects constant conditions such as
```ts
if ("constant" {
doSomething()
}
```
Add constant conditions in some code and see a warning appear.

chore: enable no-constant-condition eslint rule

---

src/components/common/EthHashInfo/index.tsx
src/components/safe-apps/SafeAppsTxModal/ReviewSafeAppsTx.tsx
src/components/settings/SafeModules/RemoveModule/steps/ReviewRemoveModule.tsx
src/components/tx/SendFromBlock/index.tsx
src/components/tx/SendToBlock/index.tsx
src/components/tx/modals/BatchExecuteModal/ReviewBatchExecute.tsx
src/components/tx/modals/NftTransferModal/ReviewNftTx.tsx
src/components/tx/modals/NftTransferModal/SendNftForm.tsx
src/components/tx/modals/TokenTransferModal/ReviewMultisigTx.tsx
src/components/tx/modals/TokenTransferModal/ReviewSpendingLimitTx.tsx
src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx

Resolves #1242 
- Changes the font-size of `EthHashInfo` addresses to `inherit` (16px)
- (refactor): Extracts the recipient area from tx modals into `SendToBlock` to keep the smaller font-size of 14px for all addresses displayed inside tx modals. Also addresses some inconsistencies across different tx modals where captions had different colors and font-weights.
1. Open a safe
2. Go to History
3. Open a transaction
4. Observe all addresses and hashes have the same font-size
5. Open a tx modal
6. Observe that all addresses have a smaller font-size of 14px

fix: Increase font-size for EthHashInfo

---

src/components/tx/SpendingLimitRow/index.tsx
src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx

Resolves #1310 
- Displays the available spending limit amount (amount-spent) with more precision
1. Open a safe with a spending limit in place
3. Select the token that has a spending limit
4. Observe the amount is displayed with enough precision
5. Press Max
6. Observe the same amount in the input field

fix: Display available spending limit amount

---

cypress/e2e/safe-apps/tx_modal.cy.js

Flakiness in transaction modal e2e test

fix(safe-apps-e2e): Add timeout for avoid flakiness when transaction modal is showed

---

src/components/safe-apps/AppFrame/TransactionQueueBar/index.tsx
src/components/transactions/TxListItem/ExpandableTransactionItem.tsx

Resolves #1303
The `Accordion`s now only mount on enter, not unmounting when closing.
Open/close the transaction accordions/Safe Apps queue bar and observe that there is only one network request. Subsequent opens/closes are then smooth.

fix: accordion mounting

---

src/components/tx/AdvancedParams/AdvancedParamsForm.tsx
src/components/tx/GasParams/index.tsx

Resolves #1345 
- Doesn't disable the gas fee accordion even if the nonce is undefined
2. Create a new spending limit transaction
3. Observe that the "Estimated Fee" Accordion is clickable and opens
4. Observe being able to edit gas fee params

fix: Allow editing gas fees for spending limit transactions

---

.dockerignore
Dockerfile

Added `Dockerfile` to Resolve safe-global/safe-infrastructure#58
based in [this template](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile) recommended in [the nextjs docs](https://nextjs.org/docs/deployment#docker-image)
Added a `Dockerfile` file
To test the image run:
- Create the docker image: `docker build -t web-core .`
- Run the docker image: `docker run -p 3000:3000  web-core`
- Open your browser on `http://127.0.0.1:3000`

chore: added Dockerfile

---

src/services/pairing/__tests__/utils.test.ts
src/services/pairing/connector.ts
src/services/pairing/utils.ts
src/services/pairing/utils/utils.test.ts
src/utils/wallets.ts

Resolves #701
Previously cached pairing sessions (if last connected >24h) are no longer automatically connected to/are cleared.
Connect to the Safe UI via pairing. Increase system time by 24h (+1m) and observe that reconnection does not automatically happen. The `SAFE_v2__pairingConnector` `localStorage` item should also no longer be present.
When returning to the Safe UI within a 24h window, the pairing session should connect as before.

fix: expire/clear pairing session after 24h

---

src/components/common/Header/styles.module.css
src/components/common/PageHeader/styles.module.css
src/components/common/PageLayout/index.tsx
src/components/common/PageLayout/styles.module.css
src/components/common/PsaBanner/index.module.css
src/components/common/PsaBanner/index.tsx
src/pages/_app.tsx
src/styles/globals.css

Resolves #1202
The banner is now statically positioned on top of the header. When it's opened, the global header-height variable is set to 104px. When it's closed, it's set back to 52px.

Fix: psa banner fixed on top

---

src/components/common/SafeIcon/styles.module.css
src/components/dashboard/Overview/Overview.tsx

Resolves #1240
The `SafeIcon` `container` now matches that of the `Identicon` size and the `Threshold` is position based on the top right of it.
Open a Safe dashboard and observe the position matching in the sidebar and the overview widget.

fix: threshold position

---

src/components/safe-apps/AppFrame/index.tsx
src/components/safe-messages/Msg/index.tsx
src/components/safe-messages/Msg/styles.module.css
src/components/safe-messages/MsgModal/index.tsx

Resolves #1392 & #1393
- The signing modal now shows the Safe app icon/name from the manifest, falling back to "Sign message off-chain".
- The font size of the message, SafeMessage and hash has been reduced.
Note: the modal colour has not been adjusted as it matches the others/uses the global theme. Truncation of the message is an open question that can be later adjusted if necessary.
- When signing a message, observe that the copy buttons are now visible.
- When signing an EIP-712 message, observe the width now fitting within the modal.
- The signed message in the messages list should now display it under the "Message" title.
Note: the show/hide button will be at the top when compared to this screenshot

fix: modal header text + smaller message font

---

src/hooks/loadables/useLoadSafeMessages.ts
src/hooks/useSafeMessagePendingStatuses.ts

Resolves #1394
Safe messages are always polled for on the `POLLING_INTERVAL`.
1. Open a 2+/n Safe and sign a message with owner 1.
2. Reload the Safe and switch to owner 2.
3. Confirm the message and observe that the pending status clears on next poll.

fix: poll for messages

---

src/components/safe-apps/AppFrame/index.tsx
src/utils/__tests__/safe-messages.test.ts
src/utils/__tests__/validation.test.ts
src/utils/safe-messages.ts
src/utils/validation.ts

Does not run into an error if the compatibility handler is not set.
Resolves #1413 
- Handles the case when the fallback handler is `null`
- Adds jest test for the supportsEip1271 function
- Connect using our test dapp with this PR deployment using the patched wallet connect version
- Using a safe without compatiblity fallback handler
- Observe warning in log when pressing "enable off-chain signing"

fix: check for compatibility handler

---

src/components/common/ConnectWallet/WalletDetails.tsx
src/components/common/ConnectWallet/useConnectWallet.ts
src/styles/onboard.css

Resolves #1367
The popover was still open after clicking on Connect, covering the WC popup and blocking input clicks.

Fix: close connect popup on button click

---

cypress/e2e/create_tx.cy.js
src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx

Resolves #1441 
- Removes the spending limit check from the early return statement
1. Open a safe
3. Select a token that doesn't have a spending limit
4. Press "Max"
5. Observe the max amount in the input field
6. Select a token that has a spending limit
7. Press "Max"
8. Observe the max spending limit amount in the input field

fix: Max amount button when sending tokens

---

src/components/common/ErrorBoundary/index.tsx

Resolves https://github.com/safe-global/safe-react-apps/issues/631
I noticed that there was one more error on development thrown by the SvgIcon component. After debugging I noticed that we pass the JSX markup to the `CircularIcon` component instead of the function itself
1. Visit production:
https://app.safe.global/gor:0x4127839cdf4F73d9fC9a2C2861d8d1799e9DF40C/apps?appUrl=appUrl%3Djavascript%3AstartHack%28%29
2. Copy pathname from the link above and use it with the preview deployment:
https://bug_xss_infite_loading--webcore.review-web-core.5afe.dev/gor:0x4127839cdf4F73d9fC9a2C2861d8d1799e9DF40C/apps?appUrl=appUrl%3Djavascript%3AstartHack%28%29

Fix infinite loading at error boundary screen

---

src/components/sidebar/SidebarList/styles.module.css

Resolves #1264 
- Uses the correct palette colors for hover/selected state in the sidebar
2. Hover and select sidebar items in light and dark mode
3. Observe it is the same color as in the design

fix: Sidebar hover and selected color

---

src/hooks/wallets/wallets.test.ts
src/hooks/wallets/wallets.ts

Resolves #1362 
Reverts changes done in #613 because of https://github.com/safe-global/web-core/issues/1362#issuecomment-1348525567
1. Open a safe
2. Connect via MM mobile app
3. Create and sign a transaction
4. Observe a MM popup showing signed data in a readable format

fix: Use eth_signTypedData with WC

---

src/components/tx/SignOrExecuteForm/index.tsx

Resolves #1364
As per @schmanu's suggestion, we check if a tx is already proposed (txId is there), and if so we don't allow editing the nonce.
* Create a tx either with MMI or a smart contract wallet
* Start signing it from another wallet – the nonce should **not** be editable

Fix: disallow editing nonce for existing txs

---

LICENSE.md
package.json

Per @rmeissner's comment:
> we do not expect unconditional forking (that is why we have lgpl as a license and not mit)
This PR changes the project's license to [LGPL v3](https://www.gnu.org/licenses/lgpl-3.0.en.html).

Change license from MIT to LGPL

---

src/components/common/ExternalLink/index.tsx
src/components/common/Footer/index.tsx

refactor: rename ExternalLink prop

---

src/components/safe-messages/Msg/index.tsx
src/components/safe-messages/Msg/styles.module.css
src/components/safe-messages/MsgDetails/index.tsx

Changes the Msg component according to the designs
Resolves #1438 
- Instead of completely hiding the message it shows the first 3 lines
- in the sign message modal the message is initially truncated
- Show all / hide button is below the message
- Off-chain sign a typed data message
- Look at a typed data message in the messages list
None

fix: make message expandable

---

src/components/transactions/SignTxButton/index.tsx

The label for the SignTxButton was accidentally changed.
Resolves #1435 
Changes the label / tooltip to "Confirm"
- Queue a tx and observe the Confirm button
None

[Eip-1271] fix sign tx label

---

src/components/safe-messages/MsgModal/index.test.tsx
src/services/safe-messages/__tests__/safeMsgSender.test.ts
src/utils/__tests__/safe-messages.test.ts
src/utils/safe-messages.ts

For Safes `<1.3.0` a wrong Safe message hash is computed when signing off-chain messages.
Resolves #1432 
- Does not add the `chainId` into the `domain` part of the Safe message's typed data if Safe version < 1.3.0
- Testing is blocked by the tx service also computing a wrong Safe message hash when creating off-chain messages.

[EIP-1271] support Safe's < 1.3.0

---

src/components/safe-apps/SafeAppsInfoModal/useSafeAppsInfoModal.ts
src/hooks/safe-apps/useSafeApps.ts
src/pages/apps.tsx

Resolves https://github.com/safe-global/web-core/issues/1326 and https://github.com/safe-global/safe-react-apps/issues/619
By checking that the remote app list was loaded before checking if the app exists there
Refresh a non-custom app and confirm the warning isn't there

Bug: Custom app warning flash

---

docs/environments.md
src/components/new-safe/CreateSafe/index.tsx

Resolves #1231 
Rewrites the remaining links to `safe.global`
- One link during SafeCreation (What Safe Setup should I use?)
- links in the developer markdown docs
- Check the links in the developer docs
- Check the link in SafeCreation

fix: use new app deployment url

---

src/components/tx/SignOrExecuteForm/index.tsx

Resolves #1294 
- Uses the updated `tx` object for simulations
1. Open a 1.1.1 safe
3. Simulate
4. Observe that Tenderly receives the initially estimated safeTxGas
5. Change the safeTxGas
6. Simulate
7. Observe that Tenderly receives the custom safeTxGas

fix: Use custom safeTxGas for simulations

---

src/components/common/Footer/index.tsx

Calculates the year displayed in the footer instead of hardcoding it.
Open a page with the footer (p.e, `Settings`)
Observe the year in the footer is different than in production

fix: compute copyright dates range in footer

---

package.json
public/fallback-f8QgO8lFjdpyu62z5u9i5.js
yarn.lock

The latest onboard has a [bug with account switching](https://github.com/blocknative/web3-onboard/issues/1385), so we're rolling it back.

Chore: roll back onboard-core

---

src/styles/onboard.css

Resolves #1352
The `onboard-danger-500` CSS variable has been altered to `--color-error-main`.
Scan for a Ledger account but cancel it. Observe the more visible error text.

fix: adjust error colour

---

src/components/common/AddressInput/index.test.tsx
src/components/common/AddressInput/index.tsx

Fixes async validation for AddressInput
Resolves #1203 
Shows a loading spinner while the form is validating.
- Find a address input with slow validation or add a way of throttling the validation (Slow resolving promise, network throttling)

fix: async validation loader in AddressInput

---

src/components/balances/AssetsTable/index.tsx
src/components/common/EnhancedTable/index.tsx

**Note: I based this branch off `spam-tokens-manually-hide` as  the EnhancedTable is refactored there in a way necessary to fix this!**
Render problems when sorting assets.
Resolves #1482 
- Adds a meaningful key to each asset row instead of the index.
- Sort the assets and witness the logos to be updated.
None

Fix asset table rerender

---

src/components/safe-messages/Msg/index.tsx

Resolves #1393
Extensive messages are now shown below the link that shows/hides them.
- Sign an EIP-712 message and observe that the show/hide link is above it, as well as no overflowing outside of the modal.
- Observe that no overflow appears in the message details in the transaction list.

fix: move message below link

---

src/components/new-safe/OwnerRow/index.tsx
src/components/new-safe/create/steps/Step2/index.tsx

Resolves https://github.com/safe-global/web-core/issues/1350
Triggers a form validation after an owners array change
In the creation flow, add a repeated owner.
Remove the repeated owner.
The form should have no errors.

fix: trigger validation upon owner removal

---

package.json
yarn.lock

The recent update to RHF >= 7.41.2 broke the form validation on the safe creation screen (and potentially other places).
Downgrades RHF to the last working version 7.41.1
3. Create a new safe and navigate to the owner policy screen
4. Observe that the Next button is not disabled
[Slack thread with more info](https://5afe.slack.com/archives/C03DAGWJCR5/p1672932360224469)

fix: Downgrade RHF version to 7.41.1

---

src/components/common/PageLayout/SideDrawer.tsx
src/components/common/PageLayout/index.tsx

Fixes a regression introduced in #1471 
- Keeps the sidebar mounted but hidden
1. Open the welcome/create safe/load safe page on mobile
2. Press the Burger menu icon
3. Observe the sidebar opening

fix: Show sidebar on mobile when pressing the burger menu icon

---

src/components/new-safe/create/NetworkWarning/index.tsx

I was trying to create a Safe and was really confused why the submit button was disabled.

Feat: add a chain switch button in Safe creation

---

src/components/common/OnboardingTooltip/index.tsx
src/styles/theme.ts

In dark mode the green text button on white background is hard to read. Changed it to black.
Look at the tooltip for the new hide tokens in dark mode

fix: button color for OnboardingTooltip

---

src/components/common/Notifications/index.tsx
src/components/notification-center/NotificationCenterItem/index.tsx

The `div inside p` warning strikes again.

Fix: div in p warning

---

src/store/__tests__/settingsSlice.test.ts
src/store/settingsSlice.ts

Resolves #1513 
Does not overwrite hidden tokens on other chains when the state is modified.
1. Hide tokens on mainnet
2. Hide tokens on goerli
3. go back to the Safe in mainnet and witness the tokens to still be hidden

fix: overwritten state of hidden tokens

---

src/components/sidebar/SidebarHeader/index.tsx
src/hooks/useVisibleBalances.ts

A small regression from the spam tokens feature. While balances are loading, we were briefly displaying 0.00 USD instead of a skeleton in the sidebar.

Fix: fiat total skeleton

---

src/components/common/ConnectWallet/AccountCenter.tsx
src/hooks/coreSDK/__tests__/useInitSafeCoreSDK.test.ts
src/hooks/coreSDK/useInitSafeCoreSDK.ts
src/hooks/wallets/useOnboard.ts
src/hooks/wallets/useWallet.ts

Resolves #1519
The root cause was that if you dismiss the HW account selection popup, the account is seemingly still connected but the Core SDK fails to init.
And the second part of the problem was that the SDK wouldn't even re-init when that popup is dismissed because the provider object doesn't refresh in that case.
I fixed the problem by
1. making the entire wallet object a dependency of the SDK hook (as opposed to just the provider)
2. the wallet will be disconnected if the SDK fails to init.
* Connect to Ledger
* Attempt to connect to Ledger again, but dismiss the account selection modal w/o selecting an account
* Attempt to execute a tx or a batch

Fix: disconnect wallet if SDK fails to init

---

src/components/common/AddressInput/index.tsx

Resolves #1520 
Creates a local isValidating instead of using the `isValidating` returned by the `useFormContext`.
See https://github.com/safe-global/web-core/issues/1520
https://user-images.githubusercontent.com/32431609/211860699-491ad7ad-7d9b-4d3e-99ee-81ffb4eeb5df.mov

fix: show input loading state when "Add Safe" from the sidebar

---

src/services/tx/tx-sender/dispatch.ts
src/services/tx/tx-sender/index.test.ts

Resolves https://github.com/safe-global/web-core/issues/1489
Waits for a successful SDK interaction to dispatch the tx PENDING state
1. Open a fully signed tx
2. Press Execute
3. Do not approve or reject in the wallet
4. Refresh the page
5. There is no "Submitting" transaction yet
N/A
https://user-images.githubusercontent.com/32431609/212056935-3965af77-002d-48cc-95cd-1eea1adea614.mov

fix: wait until successful SDK call to set pending state

---

cypress/e2e/smoke/create_safe_simple.cy.js
src/components/new-safe/OwnerRow/index.tsx
src/components/new-safe/create/steps/SetNameStep/index.tsx

Follow up on #1500
Tests more cases during safe creation flow:
- Changing network
- Removing an owner
- Saving data even when going back

fix: Extend create safe e2e test

---

src/services/safe-messages/__tests__/safeMsgSender.test.ts
src/services/safe-messages/safeMsgSender.ts
src/utils/web3.ts

Before submitting EIP 712 messages to our tx service we normalize the message.
Normalizing a message does:
- Infers the EIP712Domain type
- Infers the primaryType
Resolves #1517 
Uses the `TypedDataEncoder.getPayload` function to normalize and verify a message before submitting it.
Sign a EIP 712 message without primaryType or without EIP712Domain type.
None

[Eip-1271] normalize EIP-712 messages

---

src/components/safe-messages/Msg/index.tsx
src/components/safe-messages/Msg/styles.module.css
src/components/safe-messages/MsgDetails/index.tsx
src/components/transactions/TxDetails/styles.module.css

Resolves #1393
The message details `display` has been altered to `flex` and the `SafeMessage` positioning has been aligned with [the design](https://www.figma.com/file/x1uuIJsOZkyv5cwNlDdVC1/EIP-1271?node-id=253%3A4454&t=62fpDRvXgYksVegG-0).
Open an EIP-712 message and observe the new layout, not overlapping onto the signers column.

fix: message positioning

---

src/components/dashboard/SafeAppsDashboardSection/SafeAppsDashboardSection.tsx
src/components/new-safe-apps/SafeAppCard/SafeAppCard.tsx
src/components/new-safe-apps/SafeAppList/SafeAppList.tsx
src/hooks/safe-apps/useSafeAppPreviewDrawer.ts

Resolves https://github.com/safe-global/web-core/issues/1414

feat(safe-apps): Open drawer in dashboard

---

src/components/safe-messages/Msg/index.tsx
src/components/safe-messages/Msg/styles.module.css
src/components/safe-messages/MsgDetails/index.tsx
src/components/safe-messages/MsgModal/index.tsx

Resolves #1393
The message is now display inside a `textarea` according to [the design](1393).
Open the messages list and observe the new formatting of the messages, as well as in the signing modal.

fix: adjust message display style

---

src/hooks/wallets/useOnboard.ts
src/services/analytics/gtm.ts

- Fixes overtracking introduced with #1496 
- Sends the meta event type as a custom dimension to GA for making it easier to filter
- Resets `eventLabel` for events that don't use it to prevent pollution
2. Connect with MM
3. Observe only one meta event for connecting the wallet
4. Observe a new field `eventType` in GTM that is only set with meta events
5. Go to Assets and hide a token
6. Observe `eventLabel` with an undefined value in GTM
A new optional attribute `eventType` was added to the data layer

fix: GA tracking wrong eventLabels, missing event type, overtracking wallet connect event

---

src/components/common/ConnectWallet/AccountCenter.tsx
src/hooks/wallets/useOnboard.ts

Removes the last used wallet when disconnecting.
2. Connect with a wallet
3. Reload the page
4. Observe it reconnecting to the wallet
5. Disconnect the wallet
6. Reload the page
7. Observe it not reconnecting to the wallet

fix: Remove last used wallet when disconnecting

---

src/components/safe-apps/SafeAppIcon/index.tsx

Resolves #1564
The `overflow` of the `SafeAppIcon` is not `hidden`.
Open the Safe Apps page and observe no scrollbars on icons.

fix: prevent scrollbars on Safe App icons

---

src/components/transactions/TxDetails/styles.module.css
src/components/transactions/TxSigners/index.tsx
src/components/transactions/TxSigners/styles.module.css

Resolves incorrect placement of executor in transaction stepper:
The stepper "line" (`::before`) length is relevant to the display of executor/hint about execution.
- Queue a transaction and observe the hint regarding execution positioned correctly.
- Execute a transaction and observe the executor positions correctly.
- Observe no line that spreads beyond the final step.

fix: position executor in transaction stepper

---

src/components/tx/modals/NewTxModal/CreationModal.tsx

Resolves console error.
The Transaction Builder link in the transaction creation modal was not forwarding a ref correctly. An interim anchor tag is used to wrap the button instead of forwarding the ref to the button.
Open the transaction creation modal and observe that there is no console error and that the styling/functionality of "Contract interaction" button is still the same.

fix: ref forwarding

---

public/safe.webmanifest
src/components/common/ChainIndicator/index.tsx
src/components/common/NetworkSelector/index.tsx
src/components/dashboard/Overview/Overview.tsx

Reduces CLS caused by elements in the header and sidebar
- Adds padding to the `NetworkSelector` in the header
- Adds a skeleton for the `ChainIndicator`
- Removes a redundant loading state for the overview widget on the dashboard
Before:
[before.webm](https://user-images.githubusercontent.com/5880855/214008107-3df65843-3638-4395-9b8e-c01cad9bad88.webm)
After:
[after.webm](https://user-images.githubusercontent.com/5880855/214008217-78b685ec-965b-4e48-ba3c-b59d82d7ba6c.webm)

fix: Reduce cummulative layout shift (CLS)

---

src/components/address-book/EntryDialog/index.tsx
src/components/common/AddressInput/index.tsx
src/components/new-safe/OwnerRow/index.tsx
src/components/new-safe/load/steps/SetAddressStep/index.tsx
src/components/settings/owner/AddOwnerDialog/DialogSteps/ChooseOwnerStep.tsx
src/components/transactions/TxFilterForm/index.tsx
src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx

This PR makes it clearer that you can enter either an address or an ENS name in the recipient field.
All the places where we have address inputs – the recipient field in tx modals, address book entry modal, owner management etc – will have "or ENS" added in the label.

fix: "Recipient" -> "Recipient address or ENS"

---

src/components/tx/SendFromBlock/index.tsx

Resolves console error regarding DOM nesting
The wrapper `Typography` uses specifies the `component` instead.
Open the transaction creation modal and observe no visual change regarding the "Sending from" block, as well as no console errors regarding DOM nesting.
Before:
After:

fix: DOM nesting error

---

src/components/transactions/TxDetails/Summary/TxDataRow/index.tsx
src/components/transactions/TxDetails/Summary/TxDataRow/styles.module.css

Resolves #1523 
changed css, used `text.secondary` as color property.

fix: transaction info styling

---

src/store/__tests__/index.test.ts
src/store/index.ts
src/store/settingsSlice.ts

Resolves #1551
Hydrated state is now merged with the initial state.
1. Run the project locally.
2. Add a new key to a slice's `initialState`.
3. Reload the app and observe the new key present in the state in Redux DevTools.

fix: `merge` hydration of persisted state

---

src/components/common/WalletInfo/index.tsx
src/components/new-safe/OwnerRow/index.tsx
src/components/tx/SendToBlock/index.tsx

Resolves invalid DOM nested, on top of https://github.com/safe-global/web-core/pull/1585
All instances of `EthHashInfo` found inside `Typography` have been changed to use `div` elements as they shouldn't be nested inside `p` elements.
1. Open the account centre when connected to a wallet without an ENS and observe no console error.
2. Load a Safe and observe no console errors on the owner overview step.
3. Review a transaction to be created and observe console errors.

fix: `EthHashInfo` nesting

---

src/components/new-safe/create/logic/index.test.ts
src/components/new-safe/create/logic/index.ts

Resolves #1558 
Note: I couldn't reproduce ethers returning an error but the transaction still being executed/being in the mempool.
Uses the generic `ERROR` instead of `TIMEOUT` as a fall-through when creating a safe. This makes more sense since ethers returns a specific error code for timeouts but not for other possible errors like the one reported.
1. Create a new safe
2. Select 21000 gas limit in your wallet
3. Submit transaction
4. Observe a generic error in the UI instead of a timeout error
5. Create a new safe
6. Select extremely low gas and maxPrioFee
7. Reload the page
8. Wait for 6.5 minutes
9. Observe a timeout error

fix: Handle safe creation errors

---

src/hooks/__tests__/useChainId.test.ts
src/hooks/__tests__/useVisibleBalances.test.ts
src/hooks/useChainId.ts

Resolves #1554
`useChainId` returns the `chainId` of the connected wallet if no `chainId` is present in the URL or cached from the last session.
1. Open a "non-`chainId`" URL in an Incognito window (e.g. `/welcome`).
2. Ensure the wallet is connected to a chain that is present in the environment chain configuration and connect the wallet.
3. Observe the chain in the top right matches that of the wallet.
---
1. Open a "non-`chainId`" URL in an Incognito window (e.g. `/welcome`).
2. Ensure the wallet is connected to a chain that is NOT present in the environment chain configuration and connect the wallet.
3. Observe the chain in the top right is the default fallback, Mainnet on prod. or Goerli on dev.

fix: fallback to `chainId` of `wallet`

---

src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx

Resolves #1545
The `tokenAddress` field in the `SendAssetsForm` has been converted to use RHF's `Controller` component.
Note: this partially resolves #1501 and demonstrates the importance of controlled MUI components with RHF (#1369).
Open the transaction creation modal and observe that the field is no longer erroneous after selecting a token. Selecting a token when a value is set should clear the value field as well.

fix: asset selection validation

---

.github/workflows/cla.yml
src/hooks/useGasLimit.ts

Resolves gas limit is not high enough for transactions in Gnosis Chain when the safeTxGas is set.
Due to a problem on Nethermind it's returning a lower gas estimation for those transactions having a `safeTxGas` set. 
`safeTxGas`is used as a mechanism so developers can suggest a gasLimit of the inner transaction. So whenever an app suggests a gasLimit it's set as safeTxGas.
Add an increment of 30% to the estimated `gasLimit`.
The fix is not ideal, but there is no other way to workaround this until a proper fix is added to Nethermind. Fix will be applied only specifically for Gnosis Chain and when the `safeTxGas` is set to a different value than 0.
Use `CowSwap` with latest version of WalletConnect Safe app and try to execute an `approve`
In this PR it should have enough gas limit, not the …

Add increment for failing estimations in Gnosis Chain

---

src/components/settings/ContractVersion/UpdateSafeDialog.tsx
src/components/settings/SafeModules/RemoveModule/steps/ReviewRemoveModule.tsx
src/components/settings/SpendingLimits/NewSpendingLimit/steps/ReviewSpendingLimit.tsx
src/components/settings/SpendingLimits/RemoveSpendingLimit/index.tsx
src/components/settings/TransactionGuards/RemoveGuard/steps/ReviewRemoveGuard.tsx
src/components/settings/owner/AddOwnerDialog/DialogSteps/ReviewOwnerTxStep.tsx
src/components/settings/owner/ChangeThresholdDialog/index.tsx
src/components/settings/owner/RemoveOwnerDialog/DialogSteps/ReviewRemoveOwnerTxStep.tsx
src/components/transactions/TxDetails/index.tsx
src/components/tx/SignOrExecuteForm/index.tsx
src/components/tx/TxStepper/useTxStepper.ts
src/components/tx/modals/ConfirmTxModal/ConfirmProposedTx.tsx
src/components/tx/modals/NftTransferModal/ReviewNftTx.tsx
src/components/tx/modals/RejectTxModal/RejectTx.tsx
src/components/tx/modals/TokenTransferModal/ReviewSpendingLimitTx.tsx
src/components/tx/modals/TokenTransferModal/index.tsx
src/services/tx/tx-sender/dispatch.ts
src/services/tx/tx-sender/index.test.ts

Resolves #1563
It restores the previous logic which proposes before an immediate execution.
I've also added a condition not to show the Untrusted Tx warning when executing a tx.
* Create a tx in the Drain app
* Immediately execute
* Click on "View transaction" in the notification
* Observe that the tx doesn't have an Untrusted warning
* Once in the history, the tx will have the Drain app logo
34 is before the fix, 35 – after.

Fix: propose immediately executed txs

---

src/components/notification-center/NotificationCenter/styles.module.css

Resolves unreadable unread notification number:
The colour of the text inside the unread notification badge has been changed to `static.main`.
Open a Safe that needs upgrading, then the Notification Centre. Observe that the unread badge numbes is legible in light/dark mode.

fix: unread badge colour in dark mode

---

src/hooks/wallets/wallets.ts

Resolves #1596
When all wallets are disabled, we pass an empty array to onboard, but it needs at least one wallet. So I made it return the "injected" wallet as a default.
Cello has currently 0 wallets enabled in the staging config.

Fix: default wallet when none are enabled

---

src/services/ls-migration/addedSafes.ts
src/services/ls-migration/index.ts
src/services/ls-migration/tests.test.ts
src/store/__tests__/addedSafesSlice.test.ts
src/store/addedSafesSlice.ts

Resolves #1603 
Legacy added Safe owner formats (from the original address book) are now migrated correctly and sanitised post-corrupt migration.
The original address book format alteration can be found [here](https://github.com/safe-global/safe-react/pull/2296/files#diff-bd2bbcb55c5dde038dc34315180a7f921a4df36bd925a72a39c8ffd33676392a):
1. Modify added Safe `localStorage` on `safe-react` to have `owners` as `Array<{ address: string, name: string }>` and reattempt migration. Observe no crashing when opening the sidebar in `web-core`.
2. Modify added Safe `localStorage` on `web-core` to have `owners` as `Array<{value: { address: string, name: string }}>` and refresh. Observe no crashing when opening the sidebar.

fix: migrate/sanitise legacy owner format

---

src/components/dashboard/Overview/Overview.tsx
src/hooks/useBalances.ts
src/store/balancesSlice.ts

Resolves #1607
The balances `loading` flag now checks the reference equality of the initial state.
1. Open a Safe with multiple tokens and observe that the "Tokens" amount on the dashboard switches from the loading skeleton to the number of tokens owned.
2. Navigate to the assets page and hide all tokens then back to the dashboard and refresh. Observe that the "Tokens" amount changes from the loading skeleton to 0.
3. Switch to a Safe that has fewer tokens (hidden token amount is higher). Observe that the the loading skeleton switches from loading skeleton to 0.
Varing amounts of hidden tokens should no make the loading skeleton change to 0 to n. It should always change from the skeleton to the amount of tokens not hidden.

fix: balances loading flag

---

cypress/e2e/non_owner_spending_limit.cy.js

Adds a test for non-owner spending limit beneficiaries (https://github.com/safe-global/web-core/pull/1572).
An E2E test has been added that checks whether the "New transaction" button is enabled and the transaction creation modal flow is accessible/submittable for non-owner spending limit beneficiaries.
Run Cypress locally and execute the `non_owner_spending_limit.cy.js` test.

test: non-owner spending limit beneficiary

---

src/components/safe-apps/SafeAppsTxModal/ReviewSafeAppsTx.tsx

Resolves #1536 
Note: Somehow the Tenderly simulation shows success but I think its a general issue with 1.1.1 Safe contracts that the simulation doesn't propagate if the call was reverted so Tenderly still returns "Success". I think its unrelated to this issue and would fix it seperately.
Checks the number of transactions that are submitted through safe apps and calls `createMultiSendCallOnlyTx` or `createTx`. Previously it would try to call `createMultiSendCallOnlyTx` but without passing any `safeTxGas` which caused it to fail because the logic inside `safe-core-sdk` falls back to creating a single safe transaction if the array only contains one transaction so we should also handle that case on our side.
1. Open a 1.1.1 Safe
2. Open the TxBuilder safe app
3. Create and batch **one** …

fix: Only use multisend call if its more than 1 transaction

---

src/components/nfts/NftGrid/index.tsx
src/components/nfts/NftSendForm/index.tsx
src/pages/balances/nfts.tsx

A few small fixes for the NFT page layout on mobile and tablet.
This is how it was:
Now:

Fix: nft page mobile layout

---

src/components/common/PsaBanner/index.tsx

Fixes the link in the blue banner. The old app will redirect to the new app, except for the export path, so we shouldn't link to settings.

Fix: old app export link

---

src/components/nfts/NftCollections/index.tsx
src/components/nfts/NftSendForm/index.tsx

The Send button was tracked even if disabled.
See [this comment](https://github.com/safe-global/web-core/pull/1616#issuecomment-1411965500).

Fix: track nft send only when enabled

---

src/components/common/InfiniteScroll/index.tsx
src/components/sidebar/SafeListItem/index.tsx
src/hooks/__tests__/usePendingActions.test.ts
src/hooks/useIntersectionObserver.ts
src/hooks/usePendingActions.ts

Resolves https://github.com/safe-global/web-core/issues/1610
Uses `IntersectionObserver` to assert that the SafeListItem is in the viewport before sending a API request
On adjusting the application viewport, the `transactions/queued` network requests should equal the number of Safes visible in the Safe list sidebar

fix: fetch queue when Safe list item is visible

---

src/components/common/ConnectWallet/AccountCenter.tsx
src/components/common/Header/index.tsx
src/components/common/PageLayout/SideDrawer.tsx
src/components/common/PageLayout/index.tsx
src/components/common/PageLayout/styles.module.css

The sidebar is initially rendered in an uncollapsed state because that's how it will stay on the desktop.
Then we detect if it's a small screen via JS and collapse the sidebar. This causes the sidebar to flash on the initial page load on mobile.
This PR hides the sidebar via CSS on mobile until it's collapsed.
* The sidebar should not be initially visible on mobile (compare to prod)
* On desktop, when going from Safe Creation to an individual Safe, the sidebar should appear instantly (it's animated on on prod)
* In individual Safe Apps, the sidebar should still be animated when collapsing/expanding it.

Fix: avoid flashing the sidebar on mobile and desktop

---

src/components/settings/EnvironmentVariables/index.tsx

A small fix for settings inputs as per @JagoFigueroa's [suggestion](https://github.com/safe-global/web-core/pull/1648#issuecomment-1422263256).

Fix: type=url for env var inputs

---

src/components/safe-apps/SafeAppsSDKLink/styles.module.css
src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx

Resolves https://github.com/safe-global/web-core/pull/1648#issuecomment-1423715767
Filtered balance `items` were defined but not used for rendering the menu.

Fix: limit spending limit tokens in menu

---

src/components/balances/AssetsTable/index.tsx
src/components/balances/TokenMenu/index.tsx
src/components/balances/TokenMenu/styles.module.css
src/components/common/Sticky/index.tsx
src/components/nfts/NftSendForm/index.tsx

Resolves https://github.com/safe-global/web-core/issues/1636
Reuse `<Sticky/>` in `TokenMenu`
1. Go to This safe that has a bunch of tokens in ETH eth:0x8675B754342754A30A2AeF474D114d8460bca19b
2. Open the menu to hide tokens
3. Scroll down a bit so the save button overlaps a checkbox
4. Click the Save button where the checkbox in the row behind it would be

fix: Sticky z-index in assets and NFTs

---

src/components/safe-apps/SafeAppsHeader/index.tsx

Resolves #1666
1. The Safe Apps title has been changed to "Explore the Safe Apps ecosystem"
2. The Safe Apps subtitle has been changed to  "Connect to your favourite web3 applications with your Safe wallet, securely and efficiently"
Open the Safe Apps section of the Safe and observe the new text.

fix: change Safe Apps text

---

src/components/nfts/config.ts

Blur links for assets aren't working, there's leading to empty asset pages:
This is because blur expects contract addresses to be lowercase
Resolves #
Transform blur asset links to lowercase
1. Go to assets > nfts > click on the blur link for an nft

fix blur nft links

---

package.json
yarn.lock

`typescript-plugin-css-modules` changed their third party dependencies and thus got rid of multiple vulnerabilities. See https://github.com/mrmckeb/typescript-plugin-css-modules/issues/151
Updates the `typescript-plugin-css-modules` to 4.2.2
**This PR does not require QA as it is only a dev dependency**

chore: update vulnerable dependency

---

src/hooks/__tests__/useSafeTokenAllocation.test.ts

Unit tests are failing in the CI without related changes
Mock fetch implementation in the failing test
Run `yarn test useSafeTokenAlocation`

fix: useSafeTokenAlocation unit test

---

src/services/analytics/events/wallet.ts

The name of the event is broader than it is.

Docs: add a comment on wallet events

---

src/components/safe-apps/SafeAppIconCard/index.tsx

This will defer the loading of the icon iframes until they're in the viewport.

Fix: lazy load app icon iframes

---

src/components/common/Header/index.tsx
src/components/common/Header/styles.module.css

Resolves #1695 
* Adds style class to hide the menu in mobile mode.
* Adjusts margin to maintain the original arrangement.
Open the Welcome page in mobile or adjust resolution to mobile mode in Chrome.
NA
---
I have read the CLA Document and I hereby sign the CLA
---
recheck

[Fix][Mobile] Hamburger menu not working on welcome page

---

scripts/github/prepare_production_deployment.sh
scripts/github/s3_upload.sh

The build is uploaded to S3 to a new folder every time we deploy a release, so it makes no sense trying to keep old files while uploading the new ones.
Only the dev and staging buckets use the same folder across deployments, but we don't care about downtime there.

Chore: remove an unnecessary deployment step

---

src/components/common/PageLayout/index.tsx
src/components/sidebar/Sidebar/index.tsx
src/components/sidebar/SidebarHeader/index.tsx

Partly #1714
The sidebar was previously rendered conditionally in two variants: for `?safe` routes and for non-safe routes.
Since we now don't show the sidebar for pages like Welcome, Safe Creation etc, there's no need for this variance, and we can always render the nav sidebar for a better static site performance.
Disable JS and load the Balances page of any Safe. The sidebar should appear much faster.

Fix: pre-render the nav sidebar

---

src/components/nfts/config.ts

I've added OpenSea links on the NFT page for all the chains that it supports.
Also fixed the Polygon link, it was wrong.
I've tested the links in these safes:
Polygon: matic:0xbf4C4b9Cf903a540dF752c10912de377A55e4FA6
Optimism: oeth:0xf9D445a46D65427550174ec2A49FceFA3dae7f8D
Arbitrum: arb1:0x2EBA2F2F1D599E9E2920ce4B70b1B881e76db82E
Avalanche: avax:0xbD99AB5EbD2a68e4Ad4b21dF73f5f393fe223411
Binance: bnb:0xe83FA375a2a7c383B1fB6a6ed6bB22F6A123a980

Fix: OpenSea links for l2 chains

---

src/hooks/__tests__/useRemoteSafeApps.test.ts
src/hooks/safe-apps/useRemoteSafeApps.ts
src/hooks/safe-apps/useSafeApps.ts

Resolves #1713
`useRemoteSafeApps` sorts the remote apps alphabetically.
1. Open the Safe Apps list and observe it alphabetically sorted (before filter).
2. Open the NFT list and observe the NFT Safe Apps sorted alphabetically.

fix: alphabetically sort remote apps

---

cypress/e2e/smoke/dashboard.cy.js
src/components/dashboard/PendingTxs/PendingTxListItem.tsx
src/components/dashboard/PendingTxs/PendingTxsList.tsx
src/components/transactions/SingleTx/index.tsx
src/components/transactions/TxListItem/ExpandableTransactionItem.tsx

Resolves #1671
The final piece of #1671 – a skeleton for the single tx page.
I've replaced the circular loader with a skeleton in an expanded accordion.
Also changed the links from the dashboard queue widget to open individual txs instead of the entire queue. "View all" still links to the queue.

Fix: single transaction skeleton

---

src/components/settings/SpendingLimits/NewSpendingLimit/steps/SpendingLimitForm.tsx

Resolves #1654 
- Adds decimal validation to the amount input in `SpendingLimitForm`
1. Open a Safe
2. Create a new Spending Limit
5. Amount can't have too little or too many decimals

fix: Reuse amount validation for spending limits

---

src/components/safe-apps/utils.ts
src/config/constants.ts

Hiding "safe-governance-app" tags from Safe App card.
The "safe-governance-app" tag is now filtered.
Open the Safe Apps list and observe no tag on the Governance App card.

fix: filter governance app tag

---

src/components/safe-apps/SafeAppsSDKLink/index.tsx
src/components/safe-apps/SafeAppsSDKLink/styles.module.css
src/config/constants.ts

Resolves #1665
* I made it open on hover as per design
* Initially, it will show "How to build on Safe"
* If scrolled down a bit, it will minimize itself to not overlap with the page content

Fix: apps sdk widget design

---

src/hooks/safe-apps/useSafeAppFromManifest.ts
src/pages/apps/open.tsx

Reverts a change from #1674
A regression was introduced in #1674 which prevented Safe Apps with an unreachable manifest.json from being loaded.
Load the InsurAce app, it should load w/o problem, but on prod it won't.

Fix: revert regression in useSafeAppFromManifest

---

src/components/settings/owner/AddOwnerDialog/DialogSteps/ReviewOwnerTxStep.tsx

Resolves #1613
The new name of the owner-to-be-added is shown in the review modal instead of that from the address book.
1. Add an address that is NOT AN OWNER of the current Safe to the address book.
2. Attempt to add the aformentioned address as an owner of the Safe, specifying a new name.
3. Observe the new name shown in the review modal under which the address will be stored under

fix: show new name in review modal

---

src/components/tx/AdvancedParams/AdvancedParamsForm.tsx
src/components/tx/AdvancedParams/index.tsx
src/components/tx/ExecutionMethod/index.tsx
src/components/tx/ExecutionMethod/styles.module.css

Partially resolves https://github.com/safe-global/web-core/issues/1700
- Styles the `RelayingChip` as per Figma if the hourly relay limit is reached
- Disables advanced params fields other than `Gas limit`
1. The Chip can be tested when reaching the relay limit (5 hourly relay txs)
2. To test the disable edit fields:
- Create a transaction that can be relayed
- Open the "Estimated fee" dropdown and click "Edit". All fields but "Gas limit" should be disabled.

feat: relay modal adv params

---

src/components/tx/GasParams/index.tsx

Resolves [regression](https://github.com/safe-global/web-core/pull/1744#issuecomment-1461047693).
The `safeTxGas` is only show if present, meaning that it won't display for 1.3.0 Safes.
Create a transaction on a 1.3.0 Safe and observe that the `safeTxGas` is not shown in the advanced gas parameters.

fix: only show `safeTxGas` when present

---

cypress/e2e/smoke/balances.cy.js

Adds E2E test for manually hiding tokens
Run cypress

test: e2e manually hide tokens

---

public/.well-known/apple-app-site-association

Resolves https://github.com/safe-global/safe-ios/issues/2480
When this file is deployed and available at  https://safe-web-core.staging.5afe.dev/.well-known/apple-app-site-association the ios mobile app will be able to open staging deep link
- Deploy to staging
- Create ios app with matching applink entitlements

apple-app-site-association file also needed in staging environment.

---

src/hooks/useOwnedSafes.ts

Resolves #1759 
- Awaits the fetch of owned safes before setting the cache to avoid setting it for a stale state
1. Go to Safe
2. Clear the ownedSafes local storage
3. Connect a wallet that owns safes on different networks
4. Open the safe list sidebar
5. Observe owned safes are fetched and saved in the local storage
6. Switch to a safe on a different network
7. Observe the safe list sidebar closes
8. Observe the `ownedSafes` local storage doesn't update
9. Open the safe list sidebar again
10. Observe that the `ownedSafes` local storage gets overriden with the correct entries

fix: Only store owned safes for their given chainId

---

.github/workflows/deploy.yml

`set-output` will be deprecated in May this year, so we need to migrate it as per https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
If the PR deployment in this PR works, then it's all bueno.

Chore: replace deprecated set-output in the deploy workflow

---

src/components/transactions/TxSummary/styles.module.css

Randomly noticed this on prod:
Breaking words like this seems to be unnecessary on desktop (and even on mobile, because we break the summary into several lines).
After the fix:

Fix: tx-summary word-break only on mobile

---

src/services/sentry.ts

Removes sensitive data such as the Safe address and tx ids from Sentry events.
So far they haven't been needed for debugging anyway.

Fix: strip query params from Sentry events

---

src/components/safe-apps/SafeAppCard/index.tsx
src/components/safe-apps/SafeAppCard/styles.module.css
src/components/safe-apps/SafeAppList/index.tsx
src/components/safe-apps/SafeAppsFilters/index.tsx
src/components/safe-apps/SafeAppsListHeader/index.tsx
src/components/safe-apps/utils.ts
src/services/analytics/events/safeApps.ts

Resolves #1788
Sorts the tags alphabetically.
Check that the categories select is sorted.
Unrelated to tags, I've also added tracking on the grid/list view toggle. There should be a new event when you click on one of these: 
These buttons will now also remember the last view choice.

Fix: sort Safe App tags

---

src/components/tx/modals/TokenTransferModal/ReviewMultisigTx.tsx
src/utils/__tests__/validation.test.ts
src/utils/validation.ts

Resolves https://github.com/5afe/safe-support/issues/158
Tokens with `0` decimals are now successfully created. Token amount validation also works, e.g.: negative, 0 and above the supported amount.
1. Impersonate `eth:0x98329910449586BA244d9edEa97496f8ccf1C6Be`.
2. Create a new transaction with the "Smooth Love Potion" token and observe that all valid amounts can be entered and all invalid amounts error.
3. When a valid amount was entered, the transaction successfully loads on the review screen.

fix: support tokens with no decimals

---

src/components/dashboard/Relaying/index.tsx
src/components/tx/SignOrExecuteForm/index.tsx
src/services/analytics/events/modals.ts
src/services/analytics/events/overview.ts

Adds GA tracking to relaying related events
Tracks the following events:
- Open the help article in dashboard
- Submit transaction via relayer
- Submit transaction via connected wallet
Execute the above described actions and observe GA logging the events

feat: track relaying events

---

src/components/transactions/TxDetails/TxData/DecodedData/Multisend/index.tsx
src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx

Resolves #1687
Multisend transactions now have a header that includes "Expand all" and "Collapse all" buttons that open/close all actions in the transaction.
Open a multisend transaction and observe that each action can be individually expanded/collapse, but now also all at once. When some are open and globally expanded/collapsed, no bugs should exist.

feat: buttons to expand/collapse all actions

---

src/components/common/DateTime/index.test.tsx

DateTime jest test failed during switch to daylight savings time.
Resolves #1803 
The test now mocks the system time to a fixed date time.
`yarn test`

fix: DateTime jest test

---

src/components/settings/FallbackHandler/__tests__/index.test.tsx
src/components/settings/FallbackHandler/index.tsx
src/components/tx/modals/NewTxModal/CreationModal.tsx
src/hooks/safe-apps/useTxBuilderApp.ts
src/pages/settings/modules.tsx

Resolves #1781
This adds a new block to the "Modules" settings pane that displays the currently set Fallback Handler (if present), as well as a warning if an unofficial one is set.
Open the "Modules" settings pane and observe the new block. It should display the according details as mentioned above.

feat: display Fallback Handler address

---

src/components/settings/ContractVersion/UpdateSafeDialog.tsx
src/components/settings/ContractVersion/index.tsx
src/pages/settings/setup.tsx

Resolves #1786
This adds a clearer overview of newer Safe versions in the settings.
Note: "Update" was used instead of "Upgrade" as we use that term throughout the app and the `Alert` style matches that of the others in the app, which is why it differs slightly from [the design](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=501-11610&t=9g8AQ8txlqQ6WCF4-0).
- Open a Safe that is up-to-date and observe the standard checkmark.
- Open an outdated Safe and obsert the new information.

feat: show alert for new versions in settings

---

src/components/new-safe/create/logic/index.test.ts
src/components/new-safe/create/logic/index.ts
src/components/new-safe/create/steps/StatusStep/__tests__/useSafeCreation.test.ts
src/components/new-safe/create/steps/StatusStep/index.tsx
src/components/new-safe/create/steps/StatusStep/useSafeCreation.ts

Resolves https://github.com/safe-global/web-core/pull/1815#discussion_r1153032221
Splits the logic inside `useSafeCreation`
Create safe should work as expected with relay and without

refactor: split create safe callbacks

---

src/components/dashboard/SafeAppsDashboardSection/SafeAppsDashboardSection.tsx
src/components/dashboard/SafeAppsDashboardSection/styles.module.css
src/components/safe-apps/SafeAppCard/index.tsx

Inconsistent height of card on dashboard
The height of the "Explore Safe Apps" card is now 100%, matching that of the other cards on the dashboard.
Open the dashboard and observe that the "Explore Safe Apps" card matches the same height as the tallest card in that row. The Safe Apps list should also appear as before.
Before:
After:

fix: height of "Explore Safe Apps" card

---

src/components/dashboard/Relaying/index.tsx

Resolves missing help article link
Click "Read more" in the relaying widget of the dashboard and observe that the link works.

fix: add help centre article

---

src/components/sidebar/DebugToggle/index.tsx
src/hooks/useRelayingDebugger.ts
src/hooks/useRemainingRelays.ts
src/services/local-storage/useLocalStorage.ts

Aiding in testing of non-relay relay related features.
A new debug toggle allows enabling/disabling relaying has been added to the sidebar.
Open the Safe and observe the new debug switch which, when toggles, enables/disables relaying in the UI.

feat: add relay debug toggle

---

src/components/safe-apps/AppFrame/useFromAppAnalytics.ts

This PR adds the new Safe Apps domain to the `useFromAppAnalytics()` hook.
You can send custom analytics from Safe Apps. As we are migrating the production address to `https://apps-portal.safe.global` it is necessary to allow the domain explicitly
Use the Wallet Connect with `https://safe-client.safe.global` for connect to any dApp.
Check the connection analytics are being sent
```
{
"event": "safeApp",
"chainId": "1",
"eventCategory": "safe-apps-analytics",
"eventAction": "New session",
"safeAppName": "Walletconnect-v1",
"safeAppEthMethod": "",
"safeAppMethod": "",
"safeAppSDKVersion": "",
"eventLabel": "https://app.uniswap.org",
"gtm.uniqueEventId": 15
}
```

fix(safe-apps): Add new Safe apps domain

---

src/components/settings/SpendingLimits/SpendingLimitsTable.tsx

This solves the issue where Table header is displayed even when there are no records
Resolves #1703
I have added a conditonal statement which renders table only when data is avilable.
table is displayed only when it's not empty
Go to the spending limits page in the safe without the spending limits module enabled or to the Base network ( no support for spending limits). Now the table would not be rendered if there is no data in table.

fix: Spending limits: Table header is displayed when no records #1703

---

src/components/safe-apps/AddCustomAppModal/index.tsx
src/components/safe-apps/SafeAppActionButtons/index.tsx
src/components/safe-apps/hooks/useShareSafeAppUrl.ts
src/pages/index.tsx

Resolves #1644
Creation of the Safe App share URL now happens inside a `useEffect`.
- Ensure Safe Apps share URL is created correctly.
- Ensure the share page of the Safe App opens and does not redirect away.

fix: create Safe App share URL in `useEffect`

---

package.json
src/components/transactions/TxShareLink/index.tsx
src/pages/404.tsx
src/tests/pages/404.test.tsx

Resolves #1869
I've added a condition to rewrite paths containing `/transactions/(something-that-is not-in-the-static-routes)` to `/transactions/tx?id=...`.
Open a link like this:
https://fix_tx_url--webcore.review-web-core.5afe.dev/eth:0xA77DE01e157f9f57C7c4A326eeE9C4874D0598b6/transactions/multisig_0xA77DE01e157f9f57C7c4A326eeE9C4874D0598b6_0x102f72ce18d977a144ddef78c1f35a3102d04e94cc39e3e59d874874f22a7ec2
It should redirect to the new format.

Fix: redirect old tx id URLs

---

src/components/common/CopyButton/index.tsx
src/components/transactions/TxShareLink/index.tsx

In some browser environments, navigator.clipboard.writeText  function isn't allowed (e.g. in a web view on Android). So it was throwing **NotAllowedError: Write permission denied**. errors on Sentry.
Resolves #1782
added a try-catch block that handles any errors. When error occurs the button is disabled and title is changed showing copying is disabled in your browser.
Open in webview on android and try to copy the text.

fix: Unhandled exception in the Copy button #1782

---

src/components/transactions/GroupedTxListItems/index.tsx

Resolves #1829 
This issue was really hard to reproduce. I was able to reproduce it in a 2/n safe with multiple transactions in the queue that were missing signatures. When signing a transaction, it becomes pending which we then fetch the untrusted queue for. When signing a transaction that is not next in queue (e.g. with nonce 32), that fetch sometimes returns an array consisting only of the label and a conflict header i.e.
```
[{
"type": "LABEL",
"label": "Pending"
},
{
"type": "CONFLICT_HEADER",
"nonce": 31
}]
```
I suspect its either the CGW or the service worker returning cached data. In any case, we should not proceed to `TxGroup` if there is an empty array passed.
- Makes sure that `groupedListItems` is not empty before rendering 
1. Open a 2/n safe
2. Queue 2 transactions
3. Sign …

fix: Unhandled error for pending txs in queue

---

src/hooks/__tests__/useRemainingRelays.test.ts
src/hooks/useRemainingRelays.ts

Resolves #1879
Both `useRemainingRelaysBySafe` and `useLeastRemainingRelays` now refetch if the polled-for `safe.txHistoryTag` updates, meaning that any successful relays cause a refresh of the remaining relays possible.
1. Relay a transaction whilst on the dashboard and do not navigate away.
2. Observe the relay widget reducing after the transaction was successful.

fix: refresh remaining relays after relay

---

src/hooks/wallets/useOnboard.ts

Note: I do not have access to an iOS device and have only tested this on Android. Faking the UA on desktop shows it working on iOS, but it should still be tested on a physical device.
Resolves #1878
The presence of `window.ethereum` is also checked before automatically connecting to WalletConnect on mobile. If it _is_ present (an inject wallet exists), no autoconnection occurs.
1. Open the Safe on mobile _without_ an injected wallet installed: on Safari (on iPhone) or on Chrome/Firefox with no extensions (on Android).
2. Click connect and observe the WalletConnect QR immediately shown.
1. Open the Safe on mobile _with_ an injected wallet installed: on Chrome/Firefox with the Coinbase/MetaMask extension installed (on Android).
2. Click connect and observe the standard wallet modal shown.

fix: allow using the injected wallet on mobile

---

cypress/e2e/smoke/create_safe_simple.cy.js
cypress/e2e/smoke/load_safe.cy.js
cypress/e2e/smoke/pending_actions.cy.js
src/components/sidebar/SafeListItemSecondaryAction/index.tsx
src/components/welcome/NewSafe.tsx
src/services/pairing/module.ts

Resolves a few inconsistencies in the UI after renaming from "Safe" to "Safe Account" or "Safe{Wallet}".
- The name of the pairing wallet is now "Safe{Wallet}" in the onboard modal, not "Safe{Wallet} mobile}".
- The sidebar button to add a specific Safe Account is now just "Add" instead of "Add Safe Account".
- The title on the welcome page (on desktop/mobile) is now "Safe{Wallet}", not "SafeWallet".
- The wording below the create/add blocks on the welcome page do not repeat "Safe Account" frequently.
Observe the above changes are present in the UI.

fix: tweak wording of Safe Account/{Wallet}

---

package.json

Resolves #1900
Replaces http-server with the serve package from Vercel. It's much faster and doesn't add trailing slashes to directory URLs.
Run `year static-serve`.

Chore: repace http-server with serve

---

src/components/common/AppStoreButton/index.tsx
src/components/common/AppStoreButton/styles.module.css

A tiny part of PR #1389 
Replaced `<img>` tag with `<Image>` component by `next/image`
Visible on Connect wallet dropdown and in the footer of settings page
**Note -** I think PR #1389 is quite big and can be converted into either a milestone or smaller issues. For example, an issue which will target the images, other issue can target npm modules which can be optimized, and so on.

app store button - replaced with next image

---

.github/workflows/cla.yml
CONTRIBUTING.md

Resolves [linking to a 404 page](https://github.com/safe-global/web-core/pull/1906#issuecomment-1521650541)
All instances of links to our CLA have had the trailing forward slash removed.
Click the CLA link in the PR comments/`CONTRIBUTING.md` file and observe a working link to our CLA agreement.

fix: remove slash from end of CLA links

---

cypress/e2e/smoke/balances.cy.js
cypress/e2e/smoke/nfts.cy.js
src/components/safe-apps/SafeAppsTxModal/ReviewSafeAppsTx.tsx
src/components/transactions/HexEncodedData/index.tsx
src/components/transactions/TxDetails/TxData/DecodedData/Multisend/index.tsx
src/components/transactions/TxDetails/TxData/DecodedData/Multisend/styles.module.css
src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx
src/components/tx/DecodedTx/index.test.tsx
src/components/tx/DecodedTx/index.tsx
src/components/tx/SignOrExecuteForm/SignOrExecuteForm.test.tsx
src/components/tx/modals/NftBatchModal/ReviewNftBatch.tsx
src/components/tx/modals/NftBatchModal/index.tsx
src/services/tx/tokenTransferParams.ts

Enhances the "Transaction details" block in SignOrExecuteForm:
* Show decoded native token transfers (previously we didn't show them at all)
* Show multisend actions (previously it showed only the raw data)
I've removed <Multisend> from custom Review modals, and it's now shown in Transaction details instead.
Test native token transfers, NFT batches, Safe App batches.

Feat: decode native transfers + show Multisend in the tx info block

---

cypress.config.js
src/components/common/TokenIcon/styles.module.css
src/components/tx/ApprovalEditor/ApprovalEditor.test.tsx
src/components/tx/ApprovalEditor/ApprovalEditorForm.tsx
src/components/tx/ApprovalEditor/index.tsx
src/components/tx/ApprovalEditor/styles.module.css
src/components/tx/ApprovalEditor/utils/approvals.ts

The approved amount input is now editable right away and you just need to press the ✔️ button to save it.
Plus some minor visual tweaks.

Fix: improve ApprovalEditorForm

---

src/components/dashboard/FeaturedApps/FeaturedApps.tsx
src/components/dashboard/index.tsx

Part of #1867 
The featured apps dashboard widget took up the whole space if relaying was disabled.
- Adjusts the layout of `FeaturedApps` depending on whether the relaying widget is visible or not
1. Open the Dashboard on a network without relaying
2. Observe the FeaturedApps taking up half the width
3. Open the Dashboard on a network with relaying
4. Observe the FeaturedApps taking up the whole available space
With no Relaying widget:
With Relaying widget:

fix: Dashboard layout with relaying widget

---

src/components/tx/SignOrExecuteForm/hooks.test.ts
src/components/tx/SignOrExecuteForm/hooks.ts
src/components/tx/SignOrExecuteForm/index.tsx

Resolves #1925
We didn't notice the bug, because there's a global variable `window.origin` which was masking the undefined `origin`.
`executeTx` and `signTx` now take an `origin` parameter.

Fix: useTxActions should accept origin

---

src/components/transactions/TxDetails/TxData/DecodedData/Multisend/index.tsx

Resolves #1914
The scroll wrapper is not added in the transaction list.
- Open the transaction mentioned in the issue of the PR and observe no scrollbar next to the decoded transaction.
- Batch an NFT transfer and observe that the scrollbar _is_ present next to the decoded transactions in the modal.

fix: don't scroll wrap in transaction list

---

cypress/e2e/smoke/balances.cy.js

A timeout before the Goerli Ether assertion to allow the balances to load.

Chore: fix e2e tests

---

src/components/safe-apps/AppFrame/index.tsx

Resolves #1927 
`getBalance` additionally checks if the feature toggle is active for the current chain.
- On a supported chain: Set the token list to default.
- Open the Safe on Gnosis Chain and use the Safe Test app 'getBalance' button.

fix: fetch all balances if chain does not support default tokens

---

cypress/e2e/smoke/create_tx.cy.js
src/components/dashboard/Relaying/index.tsx
src/components/new-safe/create/steps/ReviewStep/index.tsx
src/components/tx/ExecutionMethodSelector/index.tsx
src/components/tx/ExecutionMethodSelector/styles.module.css
src/components/tx/SignOrExecuteForm/index.tsx
src/components/tx/SponsoredBy/index.tsx
src/components/tx/SponsoredBy/styles.module.css
src/components/tx/modals/BatchExecuteModal/ReviewBatchExecute.tsx
src/utils/relaying.ts

Resolves #1894 (Safe creation and batch transactions)
The execution method selector has been added to the review step of the Safe creation flow, as well as the batch transaction modal.
- Create a Safe and observe the execution method in the review step:
- Relaying a Safe creation should work.
- Executing a Safe creation should work when relaying is possible.
- Executing a Safe creation should work when relaying is _not_ possible.
- Create a batch and observe the execution method in the modal:
- Relaying a batch should work.
- Executing a batch should work when relaying is possible.
- Executing a batch should work when relaying is _not_ possible.
Note: standard transactions should work as before: relay and standard executions.

feat: execution method for creation + batches

---

src/components/tx/DecodedTx/index.test.tsx
src/components/tx/DecodedTx/index.tsx

Transactions that call functions without parameters, for instance wrapping a native token. 
Lead to uncaught errors in our DecodeTx component.
Checks if the first parameter is `undefined`.
Try to wrap xdai to wxdai on gnosis chain by doing a `deposit()` call (e.g. by using cowswap or tx builder)

fix: decoding txs without parameters

---

cypress/e2e/smoke/pending_actions.cy.js
src/components/common/ScanQRModal/ScanQRButton.tsx
src/services/analytics/events/modals.ts

I'd like to re-evaluate the usefulness of a QR scanner on desktop. Adding a tracker to see how many users click on it.

Fix: track QR button in address inputs

---

package.json
src/components/imprint/index.tsx
src/hooks/useOwnedSafes.ts
src/hooks/useTxPendingStatuses.ts
src/services/sentry.ts

@fmrsabino noticed some instances where web-core wasn't replaced.

Chore: replace remaining web-core instances

---

src/components/common/Header/styles.module.css

Resolves small logo after rebrand reversion.
The logo `height` has been removed.
Open the app and observe the correctly sized logo.
PR:
Prod:

fix: remove logo height

---

cypress/e2e/smoke/address_book.cy.js
cypress/e2e/smoke/balances.cy.js
cypress/e2e/smoke/beamer.cy.js
cypress/e2e/smoke/create_safe_simple.cy.js
cypress/e2e/smoke/create_tx.cy.js
cypress/e2e/smoke/dashboard.cy.js
cypress/e2e/smoke/nfts.cy.js
cypress/e2e/smoke/pending_actions.cy.js
cypress/e2e/smoke/tx_history.cy.js

This pending actions test is constantly failing, and I think it's because it clicks on `Accept all`, whereas most other tests click on `Accept selection`. Beamer is then enabled, and it loads very slowly which might block other things on the page.

Chore: "Accept selection" in e2e tests

---

src/hooks/usePendingTxs.ts

Resolves #1956
Adds a useAsync flag to not clear the previous poll result.
* Make a 1/1 execution
* Go to the queue and wait for 15 seconds
* The pending tx should not blink
* Switch to another Safe
* The queue should be immediately replaced with the new Safe's queue

Fix: don't clear pending queue when polling

---

src/components/common/WalletIcon/index.tsx
src/components/common/WalletInfo/index.tsx
src/components/sidebar/PendingActions/index.tsx
src/components/tx/ExecutionMethodSelector/index.tsx
src/definitions.d.ts
src/hooks/wallets/useOnboard.test.ts
src/hooks/wallets/useOnboard.ts
src/utils/wallets.ts

Injected wallets can have a custom icon, which we were ignoring. I've added it as a prop, so it's now displayed.
Before:
After:
* Connect with a custom wallet like Rabby or Zerion
* Check the wallet info in the header
* Check the Pending Actions in the Safe List
* Check the icon in the Relaying vs Wallet select

Fix: support injected wallet icons

---

src/components/balances/AssetsTable/index.test.tsx
src/components/balances/HiddenTokenButton/index.test.tsx
src/components/safe-apps/AppFrame/index.tsx
src/components/safe-apps/AppFrame/useAppCommunicator.ts
src/components/settings/SafeAppsSigningMethod/index.test.tsx
src/components/settings/SafeAppsSigningMethod/index.tsx
src/components/sidebar/SidebarNavigation/config.tsx
src/pages/settings/safe-apps/index.tsx
src/services/analytics/events/settings.ts
src/store/settingsSlice.ts
src/utils/__tests__/safe-messages.test.ts
src/utils/safe-messages.ts

Resolves #1943 
New analytics event:
- Change "Use on-chain signatures" setting
- Add the new Wallet Connect [PR deployment](https://pr657--safereactapps.review-react-hr.5afe.dev/wallet-connect/) as custom app
- Open a dapp that requires signatures (e.g. opensea login)
- Witness that by default it uses off-chain signing
- Change the setting to on-chain signing
- Witness that it now uses on-chain signing

Eip 1271 backward compatibility

---

src/pages/balances/nfts.tsx

Resolves #1959
Reload `<NftCollections>` component when changing `safeAddress` or `chainId`
1. Go to the NFTs page of a Safe containing NFTs
2. Change to another loaded Safe in the Sidebar
3. The table should display only the current Safe NFTs

fix: re-render `<NftCollections>` component when loading other Safe

---

src/components/transactions/TxDetails/TxData/DecodedData/MethodDetails/index.tsx
src/components/transactions/TxDetails/TxData/DecodedData/Multisend/index.tsx
src/components/transactions/TxDetails/TxData/DecodedData/Multisend/styles.module.css
src/components/tx/DecodedTx/index.tsx
src/utils/formatters.ts

We got user feedback that the multisend inside the Transaction details was hard to view, as opposed to the tx details in the history/queue.
I've made it look like the details in the history.
* moved it out of the accordion
* removed inner scroll
* showed the expand/collapse all buttons
This basically reverts the design to how it was in v1.8.1 (see #1899).

Feat: tx details - full multisend view

---

src/components/safe-apps/SafeAppsTxModal/ReviewSafeAppsTx.tsx

Fixes a regression introduced in #1899. The hex data was missing in the Safe App tx modal.
Restores the hex data component.
Make a Transaction Builder tx.

Fix: restore copiable hex data in the safe app review modal

---

src/services/safe-messages/safeMsgSender.ts
src/services/tx/tx-sender/__tests__/sdk.test.ts
src/services/tx/tx-sender/dispatch.ts
src/services/tx/tx-sender/sdk.ts
src/utils/safe-messages.ts

Resolves https://github.com/5afe/safe-support/issues/191
If `eth_signTypedData` is not supported by the current wallet (e.g. Ledger), `eth_sign` is used instead to sign off-chain messages (if supported by the Safe version).
Try to sign an EIP-712 message off-chain with a Ledger and observe a successful message creation.

fix: fallback to `eth_sign`

---

src/utils/__tests__/formatters.test.ts
src/utils/formatters.ts

`camelCaseToSpaces` was working incorrectly when there were multiple capital letters in a row.
Make or find a transaction that has an acronym in the method name. E.g. depostERC20Token or something similar.
The decoded method should look like `DEPOSIT ERC20 TOKEN`.

Fix: acronyms in camelCaseToSpaces

---

src/components/transactions/TxDetails/TxData/DecodedData/ValueArray/ValueArray.test.tsx
src/components/transactions/TxDetails/TxData/DecodedData/ValueArray/index.tsx

Resolves #1920
The `ValueArray` component now uses `isArray` as a type guard to prevent stringified arrays, labelled as array, e.g. "string[]" from being mapped.
1. Connect a Safe via WalletConnect to Snapshot.
2. Create a proposal with multiple choices.
3. Observe the `choices` rendered correctly in an array (above each other).
Signing other typed data should also not crash the interface.

fix: improve array decoding

---

src/pages/transactions/messages.tsx

Resolves #1972
When navigating _from_ the "Messages" tab of a Safe that supports/has Messages (e.g. Goerli Safes on staging) _to_ a Safe that doesn't (e.g. other network on staging), the Safe now redirect to the "History" tab.
1. Open the "Messages" tab of a Safe on Goerli (on staging).
2. Switch to a Safe on mainnet.
3. Observe the redirection.

fix: redirect non-existing "Messages" tab

---

.github/workflows/deploy-dockerhub.yml

The Dockerhub project was renamed to safe-wallet-web to match the new name of this repo, so the deploy action must be updated. To make it more flexible, let's make it a GitHub secret along with the Dockerhub username/password.

Chore: pass dockerhub project id from github secrets

---

src/components/common/AddressInput/index.test.tsx
src/components/common/AddressInput/index.tsx
src/utils/addresses.ts

Resolves #1631 
- Adds a cleanup function `cleanInputValue` which finds a valid address in the input and removes the rest
2. Click on the `New transaction` button on the sidebar
3. Click on the `Send tokens` button
4. Paste a string including a valid Ethereum address
(Eg. - `Here's my address: 0x0000000000000000000000000000000000000000`)
5. It should resolve this string to just the address.

feat: Make it easier to paste eth addresses

---

src/components/transactions/ExecuteTxButton/index.tsx
src/components/transactions/RejectTxButton/index.tsx
src/components/transactions/SignTxButton/index.tsx
src/components/transactions/__tests__/utils.test.ts
src/components/transactions/utils.ts

Resolves #1932
Includes the `coreSDK` initialization in the condition to disable the `<TxSummary>` buttons (`ExecuteTxButton`, `RejectTxButton` and `SignTxbutton`)
Improve tooltip description as per the disable condition
1. Go to a Tx queue where a queued tx is fully signed but not the "Next" in the queue
2. Observe the execution icons is disabled and show a tooltip "Transaction {nonce} must be executed first"
~1. Go to a Tx queue and have 2 transactions ready to be executed
2. Execute the first one
3. Observe the execution icons in the second one is disabled and show a tooltip "Pending transaction must first succeed"~
1. Go to a Tx queue where there is a tx queued in the "next" nonce
2. Refresh the page
3. Try to hover the Execute/Reject/Sign buttons immediately
4. Observe they are …

fix: improve disable condition and tooltip tile on `TxSummary` buttons

---

src/components/settings/DataManagement/index.tsx

Resolves excessibe padding in "Data import" settings pane.
The `margin-top` of the pane has been removed.
Open the "Data" settings and observe a similar style between the import/export panes.
Before:
After:

fix: remove margin from data import pane

---

src/hooks/loadables/useLoadBalances.ts
src/hooks/useAsync.ts

#1974 
The `useAsync` hook with a third param set to false currently caches data even if the callback does an early exit.
It should only cache data between reloads, not when the callback returns (doesn't matter a promise or not).
If the callback returns no promise, it should be treated as if it returns a promise that resolves to undefined, just w/o the async part.
`useAsync` with `false` as a third param is used in places where we poll info but don't want to clear the data between polls:
* Single tx page (because we poll the tx details when the queue/history tags update)
* Expanded tx details in the tx list (for the same reason)
* Approval editor (polls balances)
* Gas price
* Pending txs queue
* Regular queue
* Messages queue
* History
* Assets

Fix: useAsync should clear data if no promise

---

src/hooks/loadables/useLoadBalances.ts
src/hooks/loadables/useLoadTxHistory.ts
src/hooks/loadables/useLoadTxQueue.ts
src/hooks/useAsync.ts
src/hooks/useChangedValue.ts
src/pages/_app.tsx

Resolves #1980
This was a regression from #1968.
The `router.query` is initially empty. This is to avoid hydration issues with the static build which doesn't have any query params by definition.
On safe-specific routes, `router.query.safe` then gets populated with the value from the URL, thus going from undefined to a string. This causes the main page component to re-render due to the `key` prop.
I've added a hook that only changes the key if the previous value was set.

Fix: don't refresh main component on first page load

---

cypress/e2e/smoke/balances.cy.js
cypress/e2e/smoke/nfts.cy.js

Removes a leftover E2E test after removing the NFT links tooltip
- Removes a the tooltip test
- ~Comments out a fiat currency selector test relying on a failing CGW endpoint.~

test: E2E remove NFT tooltip assertion

---

src/components/settings/EnvironmentVariables/EnvHintButton/index.tsx
src/components/settings/EnvironmentVariables/index.tsx
src/store/__tests__/settingsSlice.test.ts
src/store/settingsSlice.ts

Resolves #1978
Setting custom env. vars. no longer fully overwrite the `EnvState`. RPC/Tenderly settings now have their own actions:
- `setRpc` only sets the current chain
- `setTenderly` only sets the Tenderly settings
The sidebar hint is now only shown when there is either a custom RPC for the current chain or custom Tenderly settings.
1. Set a custom RPC on Goerli and observe the warning in the sidebar.
2. Switch to another network and observe no warning.
1. Set custom Tenderlys ettings and observe the warning in the sidebar.
2. Switch to another network and observe the warning.

fix: merge custom env vars per chain

---

src/components/sidebar/SafeList/index.tsx

Fixes a regression from #1937 
SafeList should always show added safes regardless of the connected wallet.

Fix: show added safes with or w/o a wallet

---

.github/workflows/deploy-release.yml
.github/workflows/deploy.yml
.github/workflows/e2e.yml
.github/workflows/lint.yml
.github/workflows/safe-apps-e2e.yml
.github/workflows/test.yml
README.md

Part of #2009
Replaces `cancel-workflow-action` with a native concurrency setting as per the suggestion in cancel-workflow-action's repo.

Chore: rm cancel-workflow-action

---

src/components/transactions/TxDetails/TxData/DecodedData/Multisend/index.tsx
src/components/transactions/TxDetails/TxData/DecodedData/Multisend/styles.module.css

Resolves #2002
Replace the `AccordionSummary` by a styled `<div>` element.
1. Queue any multiSend tx
2. Open the tx queue
3. Click on the "rocket" or "check" icon to sign / execute directly from the list
4. Click on Expand all
https://github.com/safe-global/safe-wallet-web/assets/32431609/9f43a994-3bcd-4e90-8d55-1df68c8f8c9b

fix: keep expand/collapse buttons from rotating

---

src/components/tx/DecodedTx/index.tsx

Avoids rerenders of approval editor, when the queue gets polled
Resolves #2003 
Memoize prop for approval editor
1.    Queue a transaction containing approval(s)
2.    Wait ~10-15s
3.    Witness the approval editor rerendering

fix: Do not rerender approval editor in confirmation modal

---

src/components/safe-messages/Msg/styles.module.css

Solve unexpected duplicate style properties
Resolves #
Remove the oldest line of `white-space` property
Fixed a warning duplicated style
Run SonarQube to verify

chore: remove duplicated white-space

---

src/components/tx/TxSecurityWarnings/index.tsx
src/components/tx/TxSecurityWarnings/useDelegateCallModule.ts
src/services/security/modules/DelegateCallModule/index.test.ts
src/services/security/modules/DelegateCallModule/index.ts

Resolves #2016
This adds the `DelegateCallModule`, as well as associated hook and demo implementation in the transaction modal.
The implementation checks and warns whether the given transaction is a non-MultiSend `DelegateCall`.
Create a `DelegateCall` transaction and observe the warning.
Please note that this is a demo implementation.

feat: unexpected delegate call security module

---

cypress/e2e/smoke/balances.cy.js

The Terms banner was removed in #2041, but the OK button in the balances test remained.

Tests: fix balances - rm Ok button

---

next.config.mjs

Next was showing a warning about unrecognized `modularizeImports`.

Chore: fix modularized exports config

---

src/components/safe-apps/SafeAppsSignMessageModal/ReviewSafeAppsSignMessage.tsx
src/components/safe-apps/SafeAppsTxModal/ReviewSafeAppsTx.tsx
src/components/settings/ContractVersion/UpdateSafeDialog.tsx
src/components/settings/SafeModules/RemoveModule/steps/ReviewRemoveModule.tsx
src/components/settings/SpendingLimits/NewSpendingLimit/steps/ReviewSpendingLimit.tsx
src/components/settings/SpendingLimits/RemoveSpendingLimit/index.tsx
src/components/settings/TransactionGuards/RemoveGuard/steps/ReviewRemoveGuard.tsx
src/components/settings/owner/AddOwnerDialog/DialogSteps/ReviewOwnerTxStep.tsx
src/components/settings/owner/ChangeThresholdDialog/index.tsx
src/components/settings/owner/RemoveOwnerDialog/DialogSteps/ReviewRemoveOwnerTxStep.tsx
src/components/tx/modals/NftBatchModal/ReviewNftBatch.tsx
src/components/tx/modals/RejectTxModal/RejectTx.tsx
src/components/tx/modals/TokenTransferModal/ReviewMultisigTx.tsx
src/components/tx/modals/TokenTransferModal/ReviewSpendingLimitTx.tsx

Fixes linting and adds TODOs where to update `SignOrExecuteForm`

Fix linting errors, add TODOs for failing tx flows

---

src/components/tx-flow/common/TxLayout.tsx
src/components/tx-flow/flows/NftTransfer/ReviewNftBatch.tsx
src/components/tx-flow/flows/NftTransfer/index.tsx
src/components/tx-flow/flows/TokenTransfer/CreateTokenTransfer.tsx
src/components/tx-flow/flows/TokenTransfer/ReviewTokenTransfer.tsx
src/components/tx-flow/flows/TokenTransfer/index.tsx
src/components/tx-flow/useTxStepper.tsx
src/components/tx/SignOrExecuteForm/SignForm.tsx

This updates the `nextStep` function to require the entire data structure to be set on submission.
- Only renders current step
- Adds back button (yet to be styled)
- Closes modal when signing
Open the transaction creation flow and click next, observing the data present in the second step. Clicking back should also retain the values on the first step.

refactor: save entire data structure on submission

---

package.json

Resolves #2056
The `npm run serve` command now accepts an optional env var for the port number.

Chore: use REVERSE_PROXY_UI_PORT env var in the serve command

---

src/components/common/NewModalDialog/index.tsx
src/components/safe-apps/AppFrame/index.tsx
src/components/tx-flow/index.tsx

If the user closes the tx modal by clicking on the X button, or navigating to another route, the current Safe Apps transaction should be cancelled.

Onclose callback

---

src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
src/components/tx/SignOrExecuteForm/SignForm.tsx
src/components/tx/SignOrExecuteForm/index.tsx

AdvancedParams are only used for execution, so they are now in the ExecuteForm.

Refactor: move AdvancedParams to ExecuteForm

---

src/components/tx-flow/flows/TokenTransfer/CreateTokenTransfer.tsx
src/components/tx/SpendingLimitRow/index.tsx
src/components/tx/SpendingLimitRow/styles.module.css

Resolves #2100
This updates the spending limit selector to match that of the [new designs](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=5230-264187&t=B0OQUDy2kbDKsMnU-0).
Create a transaction and observe the new styled spending limit selector.

feat: spending limit selector

---

src/hooks/useGasLimit.ts

Resolves gas etimations failing when `baseGas` is set.
The set `baseGas` is used instead of a default `0` when estimating gas.
- Create a transaction with a `refundReceiver`, `baseGas` (and potentially `gasPrice`) set and observe no failing estimation.
- [This](https://app.safe.global/transactions/tx?safe=matic:0x7FAE0c531719A2ae946f098a177F90040910B2aa&id=multisig_0x7FAE0c531719A2ae946f098a177F90040910B2aa_0xd0a128883e01dd78ab6dc1bbc90527ae00170a248cef07c5b4fad6757aabc94e) transaction should successfully estimated if impersonating an owner and attempting to execute it.

fix: use `baseGas` in estimation

---

src/components/tx/ExecuteCheckbox/index.tsx
src/components/tx/ExecuteCheckbox/styles.module.css

Partially resolves #2026
This redesigns the execution checkbox in accordance with [the design](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=5188-172291&t=mADPGUm7uT4huNpO-0).
Note: the placement of the component is incorrect but will be moved as we progress with this issue.
Create a transaction and observe the option to switch between execution/signing, working as intended.

feat: execute/sign `RadioGroup`

---

src/components/tx-flow/common/TxCard/index.tsx
src/components/tx-flow/common/styles.module.css
src/components/tx/SignOrExecuteForm/ConfirmationTitle.tsx
src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
src/components/tx/SignOrExecuteForm/SignForm.tsx
src/components/tx/SignOrExecuteForm/index.tsx
src/components/tx/SignOrExecuteForm/styles.module.css

Implements a component for the Confirm/Execute titles
1. Get to the review state of different transaction flows and observe the component changing states depending if you're going to execute / sign / create&execute the transaction

[TX flow] feat: confirm/execute title component

---

src/components/transactions/TxNavigation/index.tsx

Resolves #2101
The messages tab is now _always_ shown if a chain supports EIP-1271, no longer taking into account if signed messages exist.
1. Open a Safe on a chain that supports EIP-1271 with no signed messages and observe the tab present.
2. Switch to a Safe on a chain that _doesn't_ support EIP-1271 and observe no tab present.

fix: show messages tab if chain supports EIP-1271

---

src/components/tx-flow/flows/TokenTransfer/CreateTokenTransfer.tsx
src/components/tx-flow/flows/TokenTransfer/styles.module.css
src/components/tx/SpendingLimitRow/index.tsx

Implementation of the updated amount field style.
The amount input field has been updated according to [the designs](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=5230-264187&t=xZ8Pv94K8PF5BdpI-0).
Create a transaction and observe the new design of the input field.

fix: update amount field style

---

src/tests/pages/apps-share.test.tsx

Unit tests were failing because of the updated Tx Builder URL. Looks like we aren't mocking the Safe App list request properly.

Chore: fix tx builder unit tests

---

src/components/tx-flow/common/TxCard/index.tsx
src/components/tx-flow/common/TxLayout/index.tsx
src/components/tx-flow/common/TxLayout/styles.module.css
src/components/tx-flow/common/styles.module.css
src/components/tx-flow/flows/TokenTransfer/CreateTokenTransfer.tsx
src/components/tx/SignOrExecuteForm/index.tsx

Harmonizes the styles in the Send Token flow that were unnecessary present after merging the last PRs into the epic branch.
Check https://epic_tx_flow--walletweb.review-wallet-web.5afe.dev/ vs this PR deployment for the Send Tokens create and review steps

[TX flow] styles: fix send token styles

---

next.config.mjs

Moves the `modularizeImports` config back to `experimental` in the next config. This was changed as part of https://github.com/safe-global/safe-wallet-web/pull/2049 to remove the warnings but `modularizeImports` seem to be an `experimental` feature of next and stopped working altogether after.
The change resulted in more than twice the number of modules being loaded on local dev (17k+ instead of ~6k).
1. Run the local dev environment
2. Observe significantly fewer modules being loaded

chore: Fix modularized imports

---

src/components/tx/security/redefine/RedefineBalanceChange/styles.module.css

Adds a one-pixel gap between balance changes so that they aren't butt-to-butt.

Fix: a tiny fix for balance changes CSS

---

src/components/tx/DecodedTx/index.tsx

Resolves unclear advanced details.
This adds a tooltip next to the advanced details in the transaction flow.
Create a transaction and open the details. Observe the new tooltip.

feat: add tooltip to advanced details

---

src/components/tx-flow/flows/TokenTransfer/CreateTokenTransfer.tsx
src/components/tx-flow/flows/TokenTransfer/styles.module.css

- Displays the token balance in the amount input field
- Slightly decreases the spacing of the amount input as discussed [here](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF?node-id=5230:264187#476048952)
3. Observe the token balance is visible

[TX flow] Display Token balance

---

src/components/address-book/EntryDialog/index.tsx
src/components/common/AddressBookInput/index.tsx
src/components/common/AddressBookInput/styles.module.css
src/components/common/AddressInput/index.tsx

The AB entry dialog had a bug, if you press Enter it would submit the parent form (e.g. the Send tokens form).
I also added a button link to the Unknown address text to make it more actionable.

Fix: address book entry dialog

---

src/components/tx-flow/common/TxLayout/styles.module.css
src/components/tx-flow/common/TxNonce/index.tsx
src/components/tx-flow/common/styles.module.css
src/components/tx-flow/flows/NewTx/index.tsx
src/components/tx-flow/flows/TokenTransfer/SendAmountBlock.tsx
src/components/tx-flow/flows/TokenTransfer/SendToBlock.tsx
src/components/tx/DecodedTx/index.tsx
src/components/tx/ExecuteCheckbox/styles.module.css
src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
src/components/tx/SignOrExecuteForm/SignForm.tsx
src/components/tx/SignOrExecuteForm/TxChecks.tsx
src/components/tx/SignOrExecuteForm/index.tsx
src/components/tx/SignOrExecuteForm/styles.module.css
src/components/tx/TxSimulation/index.tsx
src/components/tx/TxSimulation/styles.module.css
src/components/tx/security/shared/SecurityWarnings/styles.module.css

Part of #2067 
- Adjusts the layout for reviewing send token txs according to the design
- Moves Redefine block up to tx checks
- Adds the contract interaction link in new tx menu
- Fixes the NFT Transfer link in new tx menu
1. Try sending nfts and contract interaction via the new tx menu
2. Observe the send tokens review screen

[TX flow] Design adjustments

---

src/components/common/CheckWallet/index.tsx

Allows non-owners with spending limit to execute transaction
Resolves #2073
- Create safe 2of2
- add owners Owner1Addr and Owner2Addr
- add spending limit of 1 ETH for NonOwnerAddr
- Create send 2 ETH transaction
- sign with Owner1Addr and Owner2Addr but do not execute
- Attempt to execute transaction with NonOwnerAddr

fix: Allow non-owners with spending limit to execute transaction

---

src/components/dashboard/CreationDialog/index.tsx
src/components/dashboard/index.tsx
src/components/new-safe/create/logic/index.ts

Resolves #2088
The `showCreationModal` query param is now removed when closing the creation modal when closing.
After creating a Safe and opening it, close the creation modal and observe that the param is removed from the URL.

fix: remove creation modal query param on close

---

cypress/e2e/smoke/dashboard.cy.js

The safe has received a spam token, increasing the token counter in the dashboard. For now I just updated the number so the test passes since there isn't much we can do about spam tokens

[e2e] - fix dashboard - change token counter

---

src/components/common/PaginatedTxns/index.tsx
src/components/safe-messages/PaginatedMsgs/index.tsx

Resolves #1974
"Manually" resets the state of the loaded page URLs in PaginatedTxns.
I'm worried that this might be not the only such place where we might be having stale state after #1756.
* Make your browser zoom really small (press Ctrl+- a few times)
* Open a Safe with lots of hsitorical txs, go to Transactions
* Observe that it loaded two initial pages of history
* Switch to another Safe

Fix: reset tx list pages when Safe is changed

---

src/styles/onboard.css

Resolves #1358
Adds a line of CSS to remove extra padding.

Fix: keystone modal scroll

---

src/components/tx-flow/common/TxButton.tsx
src/components/tx-flow/flows/NewTx/index.tsx

I've restored the tracking of the following tx modal events:
* `Send tokens`
* `Send NFTs`
* `Contract interaction`
They are now tracked again when clicking on the corresponding buttons.

Fix: restore tracking of send modals

---

src/components/tx/security/redefine/RedefineBalanceChange.tsx
src/components/tx/security/redefine/index.tsx
src/components/tx/security/redefine/styles.module.css
src/components/tx/security/tenderly/index.tsx

Resolves size of balance change element
The balance change element has been made more compact according to the designs ([singular](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&mode=design&t=lFWis1kfT0aTJf9j-0), [multutiple](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=7389-146659&mode=design&t=6NrjQvf4sXjRStAP-0)).
Create a transaction sending one/multipl assets and observe the new design.

fix: make balance change more compact

---

src/components/common/TxModalDialog/index.tsx

Resolves workaround to hide modal backdrop
This replaces the `TransitionComponent` and `slot.backdrop` with a `Fragment`, removing the open transition and backdrop from `TxModalDialog`.
Create a transaction and observe no transition when opening the modal, as well as no `MuiDialog-backdrop` in the DOM:
Previous error:
Now:

fix: disable transition + backdrop of modals

---

src/components/common/PageLayout/index.tsx
src/components/common/TxModalDialog/index.tsx
src/components/common/TxModalDialog/styles.module.css
src/components/tx-flow/index.tsx

When a Safe App is open with a collapsed sidebar, the TxModal should be full page width.

Fix: tx modal with collapsed sidebar

---

src/hooks/wallets/wallets.ts
src/utils/wallets.ts

Resolves WC v1 session caching interfering with v2.
The local session of WC v1 is no longer checked when trying to auto-connect to v2.
Create a session with WC v1 and refresh the Safe. Observe that WC v2 does not try to auto-connect.

fix: don't check WC v1 session for v2 reconnection

---

src/components/safe-apps/AppFrame/index.tsx
src/components/safe-messages/SignMsgButton/index.tsx
src/components/tx-flow/common/TxFlowExitWarning/index.tsx
src/components/tx-flow/flows/SignMessage/SignMessage.test.tsx
src/components/tx-flow/flows/SignMessage/SignMessage.tsx
src/components/tx-flow/index.tsx

Resolves direct exit of new transaction flow
A confirmation dialog is now shown when exiting or navigating away from the new transaction flow which needs to first be accepted.
Create a transaction, attempt to close the flow/navigate away with back button and observe the new confirmation dialog.

feat: show alert before closing transaction flow

---

package.json
yarn.lock

Resolves #2137
`@web3-onboard/core` has been updated, which includes the latest versions of all WC packages and [the fix](https://github.com/WalletConnect/walletconnect-monorepo/pull/2684) for the reported issue.
1. Open two Safes in separate windows.
2. Connect to one from the other via WC.
3. Observe no errors in either console.

fix: upgrade `@web3-onboard/core`

---

src/components/common/CookieBanner/styles.module.css

Resolves #2198
Overrides the MUI colors in CSS.

Fix: checked box color in CookieBanner

---

src/components/transactions/TxInfo/index.tsx
src/components/tx-flow/flows/ConfirmTx/index.tsx

Resolves missing subtitle in confirmation flow.
The summary type and info has been added as the subtitle to the transaction confirmation flow.
Execute a queued transaction and observe the correct subtitle in the transaction flow.

feat: add subtitle to confirmation flow

---

src/components/tx-flow/common/TxLayout/index.tsx
src/components/tx-flow/common/TxLayout/styles.module.css

Resolves positioning of security check widgets
The messages from Redefine/Tenderly are now `sticky` when scrolling down the transaction flow step.
Open a Safe on a chain that supports Redefine and create a transaction, then simulate with Tenderly. Ensure the returned messages are higher than the window height and scroll down the step. Observe the `sticky` messages.

fix: make tx check widgets `sticky`

---

src/components/tx-flow/flows/AddOwner/index.tsx
src/components/tx-flow/flows/ChangeThreshold/ChooseThreshold.tsx
src/components/tx-flow/flows/ChangeThreshold/ReviewChangeThreshold.tsx
src/components/tx-flow/flows/ChangeThreshold/index.tsx
src/components/tx-flow/flows/NftTransfer/index.tsx
src/components/tx-flow/flows/TokenTransfer/index.tsx

Resolves incorrect styling of change threshold flow and wrong flow titles.
The change threshold flow has been updated to align with [the designs](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=1-5&mode=design&t=GSwvc7AZCbfsRX19-0).
A few incorrect titles were adjusted to switch between "New transaction" and "Confirm transaction" accordingly.
- Change the threshold via the settings and observe the new styling, correctly validated.
- Create an add owner, NFT or token transfer transaction and observe the initial title is "New transaction" and when going to the second step it is "Confirm transaction".

fix: change threshold flow style + titles

---

package.json
src/config/securityHeaders.ts
src/hooks/wallets/wallets.ts
src/services/pairing/module.ts
src/styles/onboard.css
yarn.lock

Direct Ledger connection
The `@web3-onboard/ledger` module has been reverted to no longer rely on Ledger Live, supporting more chains and custom derivation paths.
Open the Safe on a chain that supports Ledger devices and connect and transact successfully.

fix: revert Ledger module

---

src/components/tx-flow/common/TxNonce/index.tsx
src/components/tx-flow/common/TxNonce/styles.module.css

Part of #2067
- Hides the reset nonce button instead of disabling it
- Shows the value as the title when hovering
1. Open a Safe
3. Observe the input field being smaller
4. Observe the reset nonce button not visible
5. Change the nonce
6. Observe the reset nonce button is visible

fix: Hide reset nonce button

---

src/components/new-safe/create/steps/StatusStep/LoadingSpinner/styles.module.css
src/components/tx-flow/flows/SuccessScreen/StatusMessage.tsx
src/components/tx-flow/flows/SuccessScreen/StatusStepper.tsx
src/components/tx-flow/flows/SuccessScreen/index.tsx

Resolves #2023 
- Handles Relayed transactions in Status screen
- Listens to the `TxEvent.FAILED` event in order to show an error state and message
1. Open a Safe
2. Queue a transaction that would fail
3. Execute the transaction via relayer (or any other method that will result in a TxEvent.FAILED event)
4. Observe the Status screen changing

fix: Handle relayed txs and errors in status screen

---

src/components/tx-flow/common/TxLayout/styles.module.css
src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
src/components/tx/SignOrExecuteForm/SignForm.tsx
src/components/tx/SignOrExecuteForm/styles.module.css

Part of #2067 
- Aligns the submit button to the right at all times
- Adds spacing above error messages
1. Open a Safe
2. Confirm an existing transaction
3. Switch to a wallet thats not an owner
4. Observe the Submit button still aligned to the right
5. Create a transaction that will fail
6. Observe enough space above the error message

fix: TxFlow submit button alignment, error message spacing

---

src/components/sidebar/NewTxButton/index.tsx
src/components/tx-flow/common/TxNonce/index.tsx
src/components/tx-flow/flows/NewTx/index.tsx
src/components/tx-flow/index.tsx
src/components/tx/SignOrExecuteForm/ExecuteForm.tsx

Part of #2067 
- Uses the browser native confirmation dialog
- Prevents navigation if user cancels
- Adds another option to `setTxFlow` to bypass confirmation dialog
1. Open a Safe
2. Create new transaction
3. Navigate away
4. Observe no confirmation dialog
5. Click on Send tokens
6. Try to navigate away or close the window
7. Observe a confirmation dialog

fix: Hide confirmation dialog if set via setTxFlow

---

src/components/tx/SignOrExecuteForm/TxChecks.tsx
src/components/tx/SignOrExecuteForm/styles.module.css

- adds RedefineMessage to TxChecks for small screens
- changes order of Redefine scan results and Tenderly Simulation
- Open app in mobile or in a small window
- create transaction
- observe redefine results under the "Scan for risks" box

feat: show redefine warnings on mobile

---

.github/workflows/tag-release.yml

The release action pastes the contents of the RC pull request into a bash variable using an echo command, but if the PR description contains a quote it breaks the bash syntax.
E.g.
```
Remove "What's new"
```

Chore: escape quotes in release action

---

.github/workflows/tag-release.yml

* fix: revert Ledger module (#2215) – restoring previous Ledger connection UI
* fix: Allow non-owners with spending limit to execute transaction (#2121) by @elgatovital 
* Fix: checked box color in CookieBanner (#2199)
* fix: remove "Where's my wallet?" info (#2171)
* fix: don't check WC v1 session for v2 reconnection (#2178)
* Fix: /apps/open redirect (#2177)
* Fix: keystone modal scroll (#2170)
* Fix: reset tx list pages when Safe is changed (#2168)
* fix: remove creation modal query param on close (#2167)
* chore: update deployment-related packages (#2217)
* fix: upgrade `@web3-onboard/core` (#2195)
* Tests: change token counter (#2179)
* Docs: fix readme formatting (#2159)

Release 1.14.0 (fixed release workflow)

---

src/components/transactions/TxDetails/TxData/DecodedData/Multisend/index.tsx
src/components/transactions/TxDetails/TxData/DecodedData/Multisend/styles.module.css
src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx
src/components/tx-flow/common/TxStatusWidget/index.tsx
src/components/tx-flow/common/TxStatusWidget/styles.module.css
src/components/tx/DecodedTx/index.test.tsx

Part of #2067 
- Uses the `compact` prop to display DecodedTxs with the alternative design
1. Open a Safe
2. Create a multisend transaction
3. Observe the new design
4. Navigate to the history and expand a multisend transaction
5. Observe that it still looks like it used to

fix: Adjust decoded tx ui

---

README.md
src/hooks/wallets/wallets.ts

Marks `NEXT_PUBLIC_WC_PROJECT_ID` as required
If `NEXT_PUBLIC_WC_PROJECT_ID` is not present, the WC v2 module throws.
The module is now not instantiated if one is not present and the README has been updated accordingly.

fix: only initiate WC v2 module if project id provided

---

src/components/tx-flow/flows/TokenTransfer/SendToBlock.tsx

Resolves title misalignment
The `Grid` within the `SendToBlock` has been adjusted, allowing the address to "decide" the alignment.
1. Create a standard transaction and observe the correct alignment of the "To" title and address.
2. Create a Safe Apps transaction and observe the correct alignment of the "Interact with (and send n ETH to):" title and address.
Standard transaction:
Safe Apps transaction:

fix: recipient title alignment

---

src/components/tx-flow/index.tsx

Part of #2067 
- Changes the dependency from `router.events` to `router`
1. Open a Safe
2. Press Connect wallet > Connect
3. Select Safe Wallet
4. Observe no error

fix: router is undefined when using onboard modal

---

src/components/common/PageLayout/styles.module.css
src/components/common/TxModalDialog/styles.module.css

Part of #2067 
1. Open safe apps list
2. Press New transaction
3. There are no overlays from the list
4. Open a Safe app
5. Press New transaction
6. The sidebar expand button is visible

fix: Adjust z-index of new flow

---

src/hooks/wallets/useOnboard.ts
src/utils/wallets.ts

Prevents auto-connection to WC v1 on mobile
On mobile, we autoconnect to WC if there is no injected wallet present. However, this was not updated to be WC v2. This adjusts the `connectWallet` logic accordingly.
1. Open the PR deployment on mobile and attempt to connect a wallet with no injected wallet present. Observe the WC v2 modal.
2. Open the PR deployment on mobile and attempt to connect a wallet with an injected wallet present, e.g. Firefox w/ MetaMask. Observe the onboard modal.

fix: autoconnect to WC v2 on mobile

---

src/components/tx-flow/flows/AddOwner/ChooseOwner.tsx
src/components/tx-flow/flows/AddOwner/index.tsx
src/components/tx-flow/flows/ReplaceOwner/index.tsx

It is not possible to change the threshold when swapping owners.
Removes nonce input from `ReplaceOwner` flow.
- Replace an owner
- Observe that there is no input for the nonce anymore

fix: remove threshold from swap owner modal

---

src/components/tx-flow/common/TxButton.tsx
src/components/tx-flow/common/TxNonce/index.tsx
src/components/tx-flow/flows/NewTx/index.tsx
src/components/tx-flow/flows/TokenTransfer/styles.module.css

Part of #2067 
- Shows the recommended nonce as an item in the autocomplete list
- Converts `nonce` and `recommendedNonce` to strings for the form component
- Fixes a ref error resulting from `TxButton`
1. Open a Safe
3. Click into the nonce field
4. You should see the recommended nonce
5. The recommended nonce value should be highlighted in the list
6. Type in a different value
7. You should see the reset to recommended nonce button
8. Select the recommended nonce from the list
9. The reset button should disappear

fix: Show recommended nonce in list

---

src/components/transactions/ExecuteTxButton/index.tsx
src/components/transactions/SignTxButton/index.tsx
src/components/tx-flow/flows/RejectTx/index.tsx
src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
src/components/tx/SignOrExecuteForm/NonOwnerError.tsx
src/components/tx/SignOrExecuteForm/SignForm.tsx
src/components/tx/SignOrExecuteForm/styles.module.css

Part of #2067 
- Adds the non-owner check back when executing a tx
1. Open a Safe
3. Swich to a non-owner wallet
4. Observe the Submit button is disabled and an error is shown
5. Switch to signing
6. Observe the Submit button is disabled and an error is shown
7. Go to a fully signed tx in the queue as a non-owner
8. Press the execute button
9. Observe the Submit button is enabled

fix: Disable submit button for non-owners

---

src/components/tx-flow/flows/NftTransfer/ReviewNftBatch.tsx

Part of #2067 
- Changes the NFT view to take up the available space
1. Open a Safe
2. Create an NFT transfer
3. Observe the NFT list taking up the whole space

fix: Review send NFT view full width

---

src/components/new-safe/create/steps/ReviewStep/index.tsx
src/components/new-safe/create/steps/StatusStep/__tests__/useSafeCreation.test.ts
src/components/new-safe/create/steps/StatusStep/useSafeCreation.ts
src/components/tx/AdvancedParams/useAdvancedParams.ts
src/components/tx/modals/BatchExecuteModal/ReviewBatchExecute.tsx
src/hooks/__tests__/useGasPrice.test.ts
src/hooks/useGasPrice.ts
src/services/tx/tx-sender/dispatch.ts
src/utils/transactions.ts

Resolves #2221
We were not estimating the gas for Safe creation/batch execution transactions. This adds the relevant gas parameters to each transaction accordingly.
1. Connect a Ledger to Polygon
2. Observe the Safe creation flow estimating the network fee in the UI correctly, as well as successfully creating a Safe.
3. Observe batch execution working as expected.
Note: this should not affect other wallets and, as such, they need also be tested accordingly.

fix: Safe creation/batch execution gas estimation

---

package.json
yarn.lock

Updates `protobufjs`
- Test if trezor wallet still works

fix: update protobufjs transitive dependency

---

cypress/e2e/smoke/create_safe_simple.cy.js
cypress/e2e/smoke/nfts.cy.js

Resolves failing E2Es
After aligning the names of "Goerli" on our chain config. our smoke tests stopped working as it was selecting "Görli".
This updates the smokes to match the both.
Run the `create_safe_simple.cy.js` and `nfts.cy.js` smokes and observe them passing.

chore: fix network name selection in E2E

---

src/components/tx-flow/common/TxStatusWidget/index.tsx
src/components/tx-flow/common/TxStatusWidget/styles.module.css

Resolves unnecessary hook
The `TxStatusWidget` no longer requires `useDarkMode` to set the colour of the badge. Instead it now uses the `data-theme` attribute.
Create a transaction and switch between the light and dark mode. Observe the badge colour changing correctly.

fix: remove unnecessary hook

---

src/components/settings/SafeAppsSigningMethod/index.tsx

Resolves https://github.com/5afe/safe-support/issues/229
- Updates the link in settings
1. Open the settings page
2. Go to Safe Apps
3. Press the sign message link
4. Help center article should open

fix: Update message signing link in settings

---

src/components/tx-flow/common/TxNonce/index.tsx

Increase `min-width` of nonce field
The "base" `min-width` of the nonce field has been increased to 4 characters as per design request.
Create a transaction and observe the increased `min-width` of the nonce field.

fix: increase `min-width` of nonce field

---

src/components/transactions/BatchExecuteButton/index.tsx
src/components/transactions/TxDetails/TxData/DecodedData/Multisend/index.tsx
src/components/transactions/TxDetails/TxData/DecodedData/Multisend/styles.module.css
src/components/tx-flow/flows/ExecuteBatch/DecodedTxs.tsx
src/components/tx-flow/flows/ExecuteBatch/ReviewBatch.tsx
src/components/tx-flow/flows/NewSpendingLimit/ReviewSpendingLimit.tsx
src/components/tx-flow/flows/RemoveSpendingLimit/RemoveSpendingLimit.tsx
src/components/tx-flow/flows/TokenTransfer/SendAmountBlock.tsx

Part of #2067 
- Adds Expand/Collapse all buttons to batch execute
- Renames Batch execute submit button to "Submit"
- Doesn't show the confirm dialog when batch executing
- Updates the spending limit components to use `SendAmountBlock` instead of `AmountBlock` since it supports a custom title now and is more in line with the rest of the layout
1. Open a Safe
2. Queue and confirm at least 2 transactions
3. Press Execute Batch
4. Observe the decoded tx ui with buttons

fix: Align decoded tx ui for batch execute

---

src/components/common/TokenAmountInput/index.tsx
src/components/tx-flow/flows/NewSpendingLimit/CreateSpendingLimit.tsx
src/components/tx-flow/flows/NewSpendingLimit/ReviewSpendingLimit.tsx
src/components/tx-flow/flows/RemoveGuard/index.tsx

Part of #2067 
- Pass in validation to `TokenAmountInput` and make the Max field optional
- Remove amount validation for spending limits
- Adjust spending limit replacement UI when values don't change
- Update Remove Guard title text
- Resets the amount to an empty string instead of 0 when switching tokens
1. Open a Safe
2. Overwrite an existing spending limit but don't change any values
3. Observe no Max button visible
4. It should be possible to type in a larger amount than is available for a given token
5. Observe no strike-through values on screen
6. Change the reset time
7. Observe the old reset time is striked through and has its original value and not the relative time

fix: Validation for spending limits

---

src/components/tx-flow/SafeTxProvider.tsx
src/components/tx-flow/common/TxLayout/index.tsx
src/components/tx-flow/common/TxStatusWidget/index.tsx
src/components/tx-flow/flows/TokenTransfer/ReviewSpendingLimitTx.tsx
src/components/tx/SpendingLimitRow/index.tsx

Part of #2067 
- Adds an additional field `nonceNeeded` to the `SafeTxContext` so the nonce can be hidden from inside flow components
- Closes the flow when submitting a spending limit tx
1. Open a Safe with a spending limit
3. Switch between spending limit and normal transaction
4. Observe the nonce field is disappearing
5. Observe the status widget is changing text
6. Submit the transaction
7. Observe the modal is closing

fix: Hide nonce for spending limit txs

---

package.json
src/components/transactions/TxSigners/index.tsx
src/components/tx-flow/common/TxStatusWidget/index.tsx
src/utils/transaction-guards.ts

Resolves confirmed status incorrectly highlighted
The transaction status "Confirmed" step is now only highlighted if the user will confirm the transaction with their signature.
1. Create a transaction on a 1/n Safe and observe the "Confirmed" status highlighted.
2. Create a transaction with an 1+/n Safe and observe the "Confirmed" status highlighted when the threshold - 1 user confirms/executes the transaction.

fix: highlight confirmed status when signer confirms

---

src/components/privacy/index.tsx

Resolves outdated privacy policy
This adds Web3Auth and MoonPay to the privacy policy in accordance with the forthcoming mobile release.
Open the privcay policy and observe that it matches the [requested updates](https://docs.google.com/document/d/1xMboad_kb_qRwwu_kZOjgGpdXMfPgXlZ-hzblnAcOAY/edit).

fix: update privacy policy for mobile onboarding

---

src/components/common/NumberField/index.test.ts
src/components/common/NumberField/index.tsx
src/components/common/TokenAmountInput/index.tsx

Resolves #2281
The value of the `NumberField` component now trims and removes leading zeros.
The aforementioned component is used in:
- Token amount field
- `safeTxGas` field
- Transaction filter: amount, nonce fields
- Advanced params: wallet nonce, max prio fee, max fee/gas price fields
- Approval editor: value field
- Transaction nonce field

fix: trim/remove leading zeros from values

---

src/components/transactions/TxDetails/TxData/DecodedData/Multisend/styles.module.css
src/components/tx-flow/TxInfoProvider.tsx
src/components/tx/security/tenderly/__tests__/useSimulation.test.ts
src/components/tx/security/tenderly/index.tsx
src/components/tx/security/tenderly/useSimulation.ts

Fixes for #2067 
- Checks if there is a call trace error for the tenderly message
- Adds back the padding for decoded txs if its not compact
1. Open a Safe and simulate a transaction that has a call trace error
2. Observe the button showing Fail instead of Success

fix: Show Tenderly fail if there is a call trace error

---

src/components/common/NumberField/index.tsx

Resolves unformatted nonce
The transaction nonce field did not inherit the formatting added in https://github.com/safe-global/safe-wallet-web/pull/2284 (trimming/removing leading zeros). This fixes the issue.
Edit the transaction nonce and observe that it's not possible to enter spaces or leading zeros.

fix: also format `inputProps['onChange']`

---

src/components/settings/FallbackHandler/__tests__/index.test.tsx
src/components/settings/FallbackHandler/index.tsx
src/hooks/coreSDK/safeCoreSDK.ts
src/services/security/modules/DelegateCallModule/index.ts

Fallback handler/unsupported mastercopy warnings on non-default addressed chains
The deployment address of the current chain is no longer assumed to be ["default"](https://github.com/safe-global/safe-deployments/blob/main/src/assets/v1.3.0/gnosis_safe.json#L2), but is instead [referenced by `chainId`](https://github.com/safe-global/safe-deployments/blob/main/src/assets/v1.3.0/gnosis_safe.json#L7).
All instances of `defaultAddress` have been chanced to `networkAddresses[chainId]`.
- Open a non-supported mastercopy and observe the warning, as well as no warning on official deployments.
- Open a Safe with a fallback handler (of non-default address) set and observe no warning in the settings that it is unofficial. When an unofficial on is set, however, it should still warn.

fix: use the deployment by `chainId`

---

src/components/tx-flow/flows/SuccessScreen/index.tsx

Reverted transactions looked like successful transactions.
- Subscribes to the `TxEvent.REVERTED` event and displays an error on revert.
- Create any tx
- reduce the gas limit by a bit
- Execute the tx
- Wait for it to revert

fix: show error for reverted txs

---

src/components/tx/security/tenderly/index.tsx

Tenderly status for unsuccessful txs
Resolves #2301 
If a simulation finishes without being successful we show an Error state in the simulation component.
- Create a transaction that will revert (for instance send Safe token or add a duplicate owner, etc.)
- Simulate it
- Observe overall error state of the simulation

fix: show unsuccessful simulations correctly

---

src/components/common/TxModalDialog/styles.module.css
src/components/tx-flow/common/TxLayout/index.tsx
src/components/tx-flow/common/TxLayout/styles.module.css
src/components/tx-flow/common/TxStatusWidget/index.tsx
src/components/tx-flow/common/TxStatusWidget/styles.module.css
src/components/tx-flow/flows/NewTx/index.tsx
src/components/tx-flow/flows/SuccessScreen/index.tsx

Resolves [design inconsistencies](https://www.notion.so/safe-global/New-Transaction-flow-b15e2dc487ca406c908d0e4fb8271704#6c3f7beb913f40ea9cda25ad177f4478)
- Transaction status widget has been made more compact
- The close button now has a background colour]
- Success screen width has been reduced
- All transaction flow modals are centred (new transaction, flow and success screen)
Use the transaction creation flow, executing a transaction and observe the above.
---

fix: centralise flow + reduce success screen width

---

src/components/common/MetaTags/index.tsx

A small adjustment for #2307 – avoid loading the new analytics script in non-prod envs and in forked UIs.

Fix: load plausible analytics only on prod and official domain

---

src/components/common/MetaTags/index.tsx
src/config/securityHeaders.ts

A small adjustment for https://github.com/safe-global/safe-wallet-web/pull/2307.
* Avoid loading the new analytics script in non-prod envs and in forked UIs
* Add the plausible host to the allowed script hosts in the CSP.

Fix: load plausible analytics only on prod and official domain + add to CSP

---

src/components/common/TxModalDialog/styles.module.css

When you confirm a tx from the Apps Drawer, the Tx Modal should be on a higher layer.

Fix: make tx modal higher than queue drawer

---

package.json
src/components/common/TxModalDialog/styles.module.css
src/components/safe-apps/AppFrame/useTransactionQueueBarState.ts

Setting a high z-index on the modal was a mistake because ot was covering the Safe List.
Instead, it will now collapse the bottom drawer when a tx modal is opened.

Fix: minimize queue drawer when tx modal is opened

---

src/components/tx-flow/SafeTxProvider.tsx
src/components/tx-flow/flows/ConfirmTx/ConfirmProposedTx.tsx

Solves a bug with delegated txs:
* A delegate address creates a tx with nonce N
* An actual owner address signs it
* Instead of signing the tx N, it creates another tx with a nonce N + 1
The tx confirmation flow will now always use the original transaction nonce and won't update it to the recommended nonce.
* Create an unsigned tx using MetaMask institutional or a delegate address.
* Sign it with an owner key
* Observe that it signed the original tx and not created a new tx

Fix: always keep the nonce of existing txs

---

src/services/pairing/__tests__/utils.test.ts
src/services/pairing/utils.ts

Resolves #2316
The disabled wallets list can be empty, and it doesn't mean the pairing module is disabled...
* Go to the config-service admin on staging
* Enable ALL wallets for some chain
* Go to that chain and observe that mobile pairing is visible in the connection popup

Fix: mobile pairing check

---

src/components/tx-flow/flows/SuccessScreen/index.tsx
src/hooks/useTxNotifications.ts
src/services/pairing/__tests__/utils.test.ts
src/services/pairing/utils.ts

Resolves differing/duplicate link
Our notification links to the transaction in our URI, whereas the button to "View transaction" linked to the block explorer. As there is already a link to the explorer in the `EthHashInfo`, the button has now been changed to align with the notification instead.
Create an execute a transaction and observe that button/notification transaction links navigate to the Safe UI, whereas the `EthHashInfo` to the block explorer.
Note: links are marked in the screenshot below.

fix: align transaction links

---

src/components/tx-flow/common/TxNonce/index.tsx
src/components/tx-flow/common/TxNonce/styles.module.css

Resolves #2304
The design of the replacement nonce dropdown has been aligned with [the designs](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=1-5&mode=design&t=WbShkKUISF7wNfbP-0).
Opent the transaction flow on a Safe and observe the recommended nonce in the dropdown list (as well as other queued transactions, if they exist).

fix: replacement nonce dropdown style

---

src/components/safe-apps/AppFrame/index.tsx

Resolves #2286
The Safe App transaction flow is no longer closed via the communicator.
Observe that the Safe App transaction flow closes in the following instances:
- Queuing a transaction
- Successfully preparing an off-chain signature
Observe that the Safe App transaction flow _doesn't_ close in the following instance:
- Executing a transaction

fix: don't close flow in Safe Apps

---

src/components/tx/SignOrExecuteForm/styles.module.css

Resolves incorrect colour
The colour of the "Execute" icon on the transaction flow is now green in dark mode.
Observe the correct colour on the transaction flow in dark mode.

fix: execute icon colour in dark mode

---

cypress/e2e/smoke/create_tx.cy.js
cypress/e2e/smoke/nfts.cy.js
src/components/tx-flow/common/TxLayout/index.tsx
src/components/tx-flow/common/TxLayout/styles.module.css
src/components/tx-flow/flows/NewTx/styles.module.css
src/components/tx-flow/flows/SuccessScreen/index.tsx
src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
src/components/tx/SignOrExecuteForm/SignForm.tsx
src/components/tx/SignOrExecuteForm/hooks.test.ts
src/components/tx/SignOrExecuteForm/hooks.ts
src/components/tx/security/SecurityWarnings.tsx
src/hooks/useTxNotifications.ts
src/services/pairing/__tests__/utils.test.ts
src/services/pairing/utils.ts

Resolves #2321
Technically, nothing bad will happen if you sign a tx with the same owner twice. It will just overwrite the first signature.
But still good to warn about that.
However, I would keep the Sign button enabled because there can be a situation when a tx is signed locally, but sending it to the backend failed. In this case signing again is helpful.
In addition to that, some small stylistic adjustments in the tx flow.
Shows a warning is the tx has already been signed by the connect wallet.

Fix: warn if tx was already signed by connected wallet

---

package.json
src/components/settings/DelegatesList/index.tsx
src/config/constants.ts
src/pages/settings/setup.tsx
yarn.lock

It's currently not possible to see from the UI if a Safe Account has delegates attached (addresses that can only create transactions).
This PR just shows the list of delegates if they are enabled.

Feat: show delegates

---

.gitignore
public/fallback-_BhnCpEzQvANEPPDjEZ18.js
src/components/balances/AssetsTable/index.test.tsx
src/components/balances/HiddenTokenButton/index.test.tsx
src/components/batch/BatchSidebar/styles.module.css
src/components/common/ConnectWallet/AccountCenter.tsx
src/components/common/ConnectWallet/styles.module.css
src/components/common/EthHashInfo/AddressEmoji.tsx
src/components/common/EthHashInfo/index.test.tsx
src/components/common/EthHashInfo/index.tsx
src/components/common/EthHashInfo/styles.module.css
src/components/common/SafeIcon/index.tsx
src/components/common/SafeIcon/styles.module.css
src/components/settings/EmojiPreview/index.tsx
src/components/transactions/TxDetails/TxData/Transfer/index.tsx
src/components/tx/SignOrExecuteForm/BatchButton.tsx
src/pages/settings/appearance.tsx
src/services/analytics/events/settings.ts
src/store/settingsSlice.ts

Experimental feature: deterministic emojis for Ethereum addresses.
For each displayed address, an emoji is derived based on the address. This helps identify addresses more easily and helps memorize which is which.
This PR adds an experimental toggle in the Appearance Settings that enables address emojis (off by default).

Feat: emoji identicons

---

src/components/safe-apps/SafeAppCard/index.tsx
src/components/safe-apps/SafeAppList/index.tsx

Resolves #2349 
- Moves the check if a safe app was previously open further up the call tree into `handleSafeAppClick`
1. Open the custom safe apps tab
2. Add a custom safe app
3. Click on it
4. Observe that it directly opens
5. Navigate to the safe apps list
6. Click on a safe app
7. Observe that the drawer opens
8. Open that safe app
9. Navigate back to the safe apps list
10. Click on the same safe app again
11. Observe that it opens directly without a drawer

fix: Open custom safe apps on click

---

src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
src/components/tx/SignOrExecuteForm/SignForm.tsx
src/components/tx/SignOrExecuteForm/index.tsx

Delegate txs can be unsigned but still be in the queue, so the definition of `isCreation` should be the absence of a tx id.
* Create a transaction as a delegate
* Confirm the transaction as an owner
* Observe that it no longer says "Create" anywhere in the confirmation tx flow like it did before

Fix: tx can have been created w/o signatures

---

src/components/common/CookieBanner/index.tsx
src/components/common/CookieBanner/styles.module.css
src/components/common/EthHashInfo/SrcEthHashInfo/index.tsx
src/components/common/ExplorerButton/index.tsx
src/components/common/Footer/index.tsx
src/config/constants.ts

Resolves #2344
Light mode:
Dark mode:
The color of checked checkboxes should be applied differently depending on the inverted color scheme of the cookie banner.

Fix: cookie prefs checked checkbox color

---

src/pages/share/safe-app.tsx

Resolves #2320
It should wait for the client-side router to kick in before attempting a redirect.
Open this link:
https://fix_app_share--walletweb.review-wallet-web.5afe.dev/share/safe-app?appUrl=https%3A%2F%2Fsafe-apps.dev.5afe.dev%2Fdrain-safe&chain=gor
It should not redirect to the Dashboard.

Fix: prevent an early redirect on the Safe Apps share page

---

src/components/new-safe/create/__tests__/useSyncSafeCreationStep.test.ts
src/components/new-safe/create/steps/ConnectWalletStep/index.tsx
src/components/new-safe/create/steps/ReviewStep/index.tsx
src/components/new-safe/create/steps/StatusStep/StatusStepper.tsx
src/components/new-safe/create/steps/StatusStep/__tests__/index.test.tsx
src/components/new-safe/create/steps/StatusStep/__tests__/usePendingSafe.test.ts
src/components/new-safe/create/steps/StatusStep/__tests__/useSafeCreation.test.ts
src/components/new-safe/create/steps/StatusStep/__tests__/useSafeCreationEffects.test.ts
src/components/new-safe/create/steps/StatusStep/index.tsx
src/components/new-safe/create/steps/StatusStep/usePendingSafe.ts
src/components/new-safe/create/steps/StatusStep/useSafeCreation.ts
src/components/new-safe/create/steps/StatusStep/useSafeCreationEffects.ts
src/components/new-safe/create/types.d.ts
src/components/new-safe/create/useSyncSafeCreationStep.ts

Resolves #2292 
- Stores pending Safe per chainId
- Create a Safe on Görli but do not wait for the tx to process
- Switch to Polygon 
- Create a Safe on polygon in parallel

feat: pending safes per chainId

---

src/components/common/AddressEmoji/AddressEmoji.test.tsx
src/components/common/AddressEmoji/index.tsx
src/components/common/AddressEmoji/styles.module.css
src/components/common/EthHashInfo/index.tsx
src/components/common/WalletInfo/styles.module.css
src/store/addedSafesSlice.ts

Another iteration on emoji avatars:
* Limit them only to owned/added Safes
* Clean up the emoji ranges
As agreed with @johannesmoormann, we're limiting the scope of this feature to make it safer.

Fix: limit emoji avatars to owned Safes

---

cypress/fixtures/safe-app.html
src/components/safe-apps/AppFrame/__tests__/AppFrame.test.tsx
src/components/safe-apps/AppFrame/index.tsx
src/pages/apps/open.tsx

Fixes the tx-modal e2e test
- The safe app fixture immediately sent a transaction to the communicator which sometimes made the test fail because the manifest wasn't fully fetched yet. This adds a small delay there
- Also removes the `useSafeAppFromManifest` hook inside `AppFrame` since we already use the hook in the parent so we can pass it as a prop instead
- Safe apps should still work
- The tx-modal e2e test should not fail anymore

Tests: fix tx modal e2e test

---

src/components/batch/BatchSidebar/index.tsx
src/hooks/useDraftBatch.ts

When a batch is confirmed, it should be removed. It didn't work because I was passing the wrong id.
* Create a batch
* Confirm it
* It should be proposed to the queue (or executed)
* It should disappear from the batch sidebar

Fix: clear batch on confirm

---

src/components/common/ConnectWallet/ConnectionCenter.tsx
src/components/common/ConnectWallet/styles.module.css

Resolves #2380
Not connected:
Connected:

Fix: [mobile] CSS for not connected state in header
