safe-global/safe-wallet-monorepo

.env.example
README.md
src/config/constants.ts

I've not run the interface for a while and needed to get the dev env working again. I had to search the source code for used env variables to get it done.
Creates an env example file

Add env example file

---

src/components/common/ConnectWallet/ConnectButton.tsx
src/components/common/ConnectWallet/styles.module.css
src/components/common/Header/index.tsx
src/components/common/Header/styles.module.css
src/components/sidebar/Sidebar/styles.module.css

The header CSS still had some problems. I've adjusted some paddings.
Also fixed the sidebar being wider than the screen on mobile.

Fix: header CSS

---

CONTRIBUTING.md
docs/code-style.md
src/services/ls-migration/README.md

Adds fancier contributing guidelines and moves the code style to a separate doc.

Chore: contributing.md + code of conduct

---

src/components/transactions/TxDetails/Summary/index.tsx
src/components/transactions/TxSummary/index.tsx
src/components/tx/DecodedTx/index.tsx
src/components/tx/SignOrExecuteForm/index.tsx

Adds transaction details when signing/executing an existing tx.

Feat: transaction details in tx modal

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md

Adds a Feature request and a Bug report templates.
I've copied them from safe-react and adjusted the text a bit.

Chore: add issue templates

---

src/components/create-safe/steps/SetNameStep.tsx
src/components/load-safe/steps/SetAddressStep.tsx
src/components/safe-apps/AddCustomAppModal.tsx
src/components/settings/owner/OwnerList/index.tsx
src/tests/pages/apps.test.tsx

There were a couple places in the app where Gnosis the company was mentioned. I reworded them.

Fix: rm Gnosis from app text

---

package.json
src/components/common/ConnectWallet/styles.module.css
src/components/common/TokenAmount/styles.module.css
src/components/safe-apps/AppCard/styles.module.css
src/components/safe-apps/SafeAppsSection/styles.module.css

CSS formatting problem found by @katspaugh in one of my previous PRS.
Trying to fix that, I discovered that the prettier command was faulty. It parsed globs incorrectly and would throw an error if it couldn't find a file matching the glob. This PR also fixes that https://github.com/prettier/prettier/issues/7861#issuecomment-603363046

Fix prettier command and run prettier

---

src/components/tx/modals/BatchExecuteModal/ReviewBatchExecute.tsx
src/hooks/useTxNotifications.ts
src/hooks/useTxPendingStatuses.ts
src/services/tx/txEvents.ts
src/services/tx/txSender.ts
src/store/pendingTxsSlice.ts
src/store/txHistorySlice.ts

- Shows notifications when executing a spending limit tx
- Removes `tx` from `TxEvent` types as it is currently not utilized
- Adds an optional `message` prop to `TxEvents`

feat: Add notifications for spending limit txs

---

package.json

Chore: add prettier to pre-commit

---

src/tests/pages/apps.test.tsx

Remove unused debug variable in safe apps page tests

---

.github/workflows/test.yml
README.md
src/components/common/TokenIcon/styles.module.css

Add build badges + run unit tests on main.

Chore: add badges in the readme + run tests on main

---

src/styles/theme.ts

Incorrect theme shadows
Strings have been adjusted to be template literals.
No visual changes should be noticeable to shadows in the app.

fix: theme template literals

---

public/favicons/site.webmanifest
src/pages/_app.tsx

A small fix: remove the theme colors because they make the app look weird on the mobile phone.
Also added a meta description like in safe-react.

Fix: remove theme color from manifest

---

package.json
yarn.lock

Adds ts-prune to find unused code. Plus a command that runs lint, prune and prettier:
```
yarn fix
```

Chore: add ts-prune

---

src/components/common/DatePickerInput/index.tsx
src/components/transactions/TxFilterForm/index.tsx

Resolves #476
"From" and "To" dates now validate against each other and are validation dependent on each other.
Enter conflicting dates above/below the other accordingly and observe the validation error.

fix: validate dates

---

src/components/settings/SafeModules/RemoveModule/index.tsx
src/components/settings/owner/RemoveOwnerDialog/index.tsx

Resolves #460 
- Makes the icon and button larger
1. Open the safe app
2. Navigate to module settings
3. Observe delete button has the same size as other delete buttons

style: Use same size for delete icons

---

src/components/address-book/ImportDialog/index.tsx
src/components/common/Footer/index.tsx
src/components/sidebar/SafeListContextMenu/index.tsx
src/components/tx/TxStepper/useTxStepper.ts
src/components/tx/modals/TokenTransferModal/ReviewSpendingLimitTx.tsx
src/services/analytics/events/modals.ts
src/services/analytics/events/settings.ts
src/services/analytics/gtm.ts
src/services/onboard.ts

Resolves #471
Adds missing events and removes wrong/unused events.

Fix: analytics events

---

src/components/settings/SpendingLimits/NewSpendingLimit/steps/SpendingLimitForm.tsx

Resolves "value out-of-bounds" error
The [upper limit of a spending limit amount (`uint96`)](https://github.com/safe-global/safe-modules/blob/master/allowances/contracts/AlowanceModule.sol#L52) is now validated against.
Attempt to create a spending limit with a value > 2^96 - 1 and observe the new validation error that prevents you from submitting.

fix: validate upper amount of spending limit

---

src/utils/date.ts
src/utils/transactions.ts
src/utils/tx-history-filter.ts

Some of the TODOs have been already fixed but the comments remained.

Chore: update obsolete todos

---

src/components/common/PairingDetails/index.tsx
src/services/pairing/hooks.ts

Removes TODOs
TODOs have been moved to an issue https://github.com/safe-global/web-core/issues/563 instead as we intend to improve this in the future.

fix: remove pairing TODOs

---

src/services/contracts/safeContracts.ts
src/services/contracts/spendingLimitContracts.ts

Removes TODOs
TODOs have been moved to Core SDK issues: https://github.com/safe-global/safe-core-sdk/issues/261, https://github.com/safe-global/safe-core-sdk/issues/262, https://github.com/safe-global/safe-core-sdk/issues/263 instead.

fix: remove Core SDK TODOs

---

cypress/e2e/smoke/balances.cy.js
cypress/e2e/smoke/load_safe.cy.js

~Changing the test of the "Receive" modal test (no more Receive button in the assets tab)~

test: e2e balances

---

docs/environments.md
docs/release-procedure.md
src/hooks/useTxQueue.ts

Copied the docs from safe-react. Need to update the environment URLs once we have a new deployment.

Docs: copy docs from safe-react

---

src/components/safe-apps/SafeAppList.tsx

A small fix for the "loading" message that was too close to the edge of the page.

Fix: Safe Apps loading message style

---

src/components/common/Header/index.tsx

Resolves #580
Checks if we're on Dashboard, and links directly to Welcome then.

Fix: logo links to welcome if on dashboard

---

src/components/tx/AdvancedParams/AdvancedParamsForm.tsx
src/components/tx/AdvancedParams/index.tsx
src/components/tx/SignOrExecuteForm/index.tsx

Resolves #584
Apparently we lost the right gas limit param at some point. I'm now passing it explicitly to the form.

Fix: recommended gas limit

---

src/components/common/ErrorBoundary/index.tsx
src/components/common/ErrorBoundary/styles.module.css

The error message had the wrong !IS_PRODUCTION flag, and also it was black-on-black in the dark mode.

Fix: error boundary bugs

---

cypress/e2e/smoke/tx_history.cy.js

Editing selectors.
I didn't need to change the test at all
NOTE: I had to change my timezone for these test to work, because they expect specific dates that don't show up if you are not in GMT +2. 
This could be related to this issue https://github.com/safe-global/web-core/issues/539
I don't know what timezone the CI uses

test: E2E Transaction history 

---

src/components/tx/SignOrExecuteForm/SignOrExecuteForm.test.tsx

Related to #503 
Tests signing, on-chain signing, executing branches in `SignOrExecuteForm`

fix: Add more tests for SignOrExecuteForm

---

src/config/securityHeaders.ts
src/pages/_app.tsx

- add ContentSecurityPolicy
- add Strict-Transport-Security

security: add CSP headers

---

src/hooks/safe-apps/useRemoteSafeApps.ts

Resolves #698
Multiple components were requesting remote Safe Apps almost simultaneously. Probably assuming they come from a centralized local state.
E.g. the two Dashboard widgets (Featured Apps and Safe Apps), and the SAFE token widget in the header.
I've added some primitive request caching to avoid this. We should probably consider storing apps in Redux.

Fix: avoid multiple safe-apps requests

---

.github/workflows/build.yml
.github/workflows/deploy-staging.yml
.github/workflows/e2e.yml
.github/workflows/lint.yml
.github/workflows/test.yml

Adds a GitHub action to deploy the build to staging. Needs to be merged to main for the workflow dependencies to work.

Chore: action to deploy to staging

---

src/config/constants.ts

Chore: update staging CGW URL

---

src/components/nfts/NftGrid/index.tsx
src/components/sidebar/Sidebar/index.tsx
src/components/sidebar/SidebarHeader/index.tsx

Resolves #771 and #800.
Just two small CSS fixes.

Style: NFT collection icon & Safe icon

---

src/styles/theme.ts

A small fix for the tooltip colors that I accidentally broke in #807.

Fix: tooltip colors

---

src/hooks/loadables/useLoadChains.ts
src/hooks/useMasterCopies.ts
src/services/exceptions/ErrorCodes.ts

Simply fixed an inconsistent error code choice.

Fix: wrong error code for load chains

---

public/images/apps/apps-icon.svg
src/components/safe-apps/AddCustomAppModal.tsx
src/tests/pages/apps.test.tsx

Fix wrong merge to `main` in this PR -> https://github.com/safe-global/web-core/pull/778/files

fix(safe-apps):  Wrong merge into main

---

src/components/dashboard/FeaturedApps/FeaturedApps.tsx
src/components/tx/modals/NewTxModal/index.tsx
src/config/constants.ts
src/services/analytics/events/modals.ts

Resolves #876 
Adds a Contract interaction button with the TxBuilder icon and link.

Feat: contract interaction (TxBuilder)

---

public/images/address-book/address-book.svg
src/components/address-book/AddressBookHeader/index.tsx
src/components/address-book/AddressBookHeader/styles.module.css
src/components/address-book/AddressBookTable/index.tsx
src/components/safe-apps/SafeAppsHeader/index.tsx
src/pages/transactions/tx.tsx

Resolves #835
A search bar has been added to the `AddressBookHeader` which filters the results shown in the `AddressBookTable`. Said search bar, as well as the `action` buttons are responsive.
Open the address book, ensuring entries exist. Enter a search query and observe the entries filter depending it. When none are found, observe the `PagePlaceholder`.

feat: address book search

---

src/components/common/ConnectWallet/styles.module.css
src/components/common/ModalDialog/index.tsx
src/components/notification-center/NotificationCenterItem/styles.module.css
src/components/transactions/TxList/styles.module.css
src/styles/theme.ts

There are some warnings in the console because of this selector.

Fix: first-child -> first-of-type

---

.github/workflows/deploy-staging.yml
.github/workflows/e2e.yml
src/config/constants.ts

Fix: update the WC bridge URL

---

src/components/create-safe/status/usePendingSafeCreation.ts

Resolves #905
Pending Safe creation was failing early because of a poorly handled error.
I've added a condition that falls back to a timeout when that unexpected error happens.
Create a Safe on Aurora.

Fix: timeout in safe creation

---

cypress/e2e/smoke/address_book.cy.js
src/components/common/SafeTokenWidget/__tests__/SafeTokenWidget.test.tsx
src/components/common/SafeTokenWidget/index.tsx
src/hooks/useSafeTokenAllocation.ts
src/utils/formatNumber.ts
src/utils/formatters.ts

Displays SAFE token allocation properly.
Ported from https://github.com/safe-global/safe-react/pull/4081.

Fix: display allocated SAFE amount

---

cypress/e2e/smoke/tx_history.cy.js

Fixes `tx_history` test by correcting the Tx History iterator

test: fix tx list iterator

---

cypress/e2e/safe-apps/constants.js
cypress/support/safe-apps-commands.js
src/components/dashboard/SafeAppsDashboardSection/__tests__/SafeAppsDashboardSection.test.tsx
src/components/safe-apps/SafeAppsInfoModal/useSafeAppsInfoModal.ts
src/hooks/safe-apps/permissions/useBrowserPermissions.ts
src/hooks/safe-apps/permissions/useSafePermissions.ts
src/services/safe-apps/track-app-usage-count.ts

Renaming storage keys to camelcase for matching the project code style

feat(safe-apps): Rename storage keys for Safe Apps to camelcase

---

cypress.config.js
cypress/e2e/safe-apps/permissions_settings.cy.js
src/components/settings/SafeAppsPermissions/index.tsx

- Adds e2e test for the Permissions settings section
- Adds global configuration for [Test Retries](https://docs.cypress.io/guides/guides/test-retries)

feat(safe-app-e2e): Add tests for permissions settings section

---

package.json
src/config/constants.ts

Fix: update CGW URL

---

src/components/common/NameInput/index.tsx
src/components/create-safe/steps/OwnerRow.tsx
src/components/new-safe/CreateSafe/index.tsx
src/components/new-safe/steps/Step2/OwnerRow.tsx
src/components/new-safe/steps/Step2/index.tsx
src/components/new-safe/steps/Step2/styles.module.css

Redesign of owner step.
Resolves #962 
Adds New owner and threshold step with redesigned elements.
Navigate to `/demo` and observe the example owner step.
The safe creation and the owner step will be fully functional once #931 is resolved.
None

[Safe Creation] Owner step

---

src/components/common/NetworkSelector/index.tsx
src/components/common/PageLayout/index.tsx
src/components/new-safe/CardStepper/index.tsx
src/components/new-safe/CreateSafe/index.tsx
src/components/new-safe/steps/Step1/index.tsx

Resolves #995
- Hides sidebar on create-safe page
- Stays on create-safe page when switching network
- Centers create-safe form and uses a fixed width container

fix: Create safe layout adjustments

---

src/components/common/CopyButton/index.tsx
src/components/common/EthHashInfo/styles.module.css
src/components/common/TokenExplorerLink/index.tsx
src/components/transactions/TxDetails/TxData/Transfer/index.tsx

Fix: tiny icons in tx-list

---

.github/workflows/release.yml
package.json
yarn.lock

There was a YML syntax mistake in the release action.
Also updated the Gateway SDK version.

Chore: release action syntax

---

src/services/ls-migration/addedSafes.ts
src/services/ls-migration/tests.test.ts

Rinkeby was deleted, so no need to migrate it.

Fix: rm Rinkeby from the migration script

---

src/components/common/PairingDetails/PairingDescription.tsx
src/components/new-safe/CreateSafe/index.tsx
src/components/new-safe/steps/Step4/StatusMessage.tsx
src/components/new-safe/steps/Step4/StatusStepper.tsx

Textual inconsistencies
A few grammatical/punctuation mistakes have been rectified, as well as styles adjusted to be uniform.
A missing hint from the design was also added.
n/a

fix: textual inconsistencies + add hint

---

package.json
src/components/safe-apps/SafeAppsSignMessageModal/ReviewSafeAppsSignMessage.tsx
src/components/safe-apps/utils.ts

Mergeback v1.0.7 to dev

---

package.json
public/images/settings/data/file.svg
src/components/common/AddressInput/index.test.tsx
src/components/common/AddressInput/index.tsx
src/components/settings/DataManagement/index.tsx
src/components/settings/ImportAllDialog/__tests__/useGlobalImportFileParser.test.ts
src/components/settings/ImportAllDialog/index.tsx
src/components/settings/ImportAllDialog/styles.module.css
src/components/settings/ImportAllDialog/useGlobalImportFileParser.ts
src/components/sidebar/SidebarNavigation/config.tsx
src/config/routes.ts
src/pages/import.tsx
src/pages/settings/data.tsx
src/services/analytics/events/settings.ts
src/services/exceptions/ErrorCodes.ts
src/services/ls-migration/addressBook.ts
src/services/ls-migration/tests.test.ts
src/store/addedSafesSlice.ts
src/utils/__tests__/addresses.test.ts
src/utils/addresses.ts
src/utils/validation.ts
yarn.lock

Have to backmerge because we cherry-picked commits for v1.0.8

Backmerge main to dev

---

package.json

So we dont have to backmerge from main

chore: Bump version to 1.0.9

---

src/components/settings/ImportAllDialog/documentation.md

Adds documentation of our v1 export / import.

add: docs for import all feature

---

src/components/common/ConnectWallet/WalletDetails.tsx
src/components/common/ConnectWallet/useConnectWallet.ts
src/components/dashboard/CreationDialog/index.tsx
src/components/new-safe/CreateSafe/index.tsx
src/components/new-safe/steps/Step0/index.tsx
src/components/new-safe/steps/Step2/index.tsx
src/components/new-safe/steps/Step2/useSafeSetupHints.ts
src/components/new-safe/steps/Step3/index.tsx
src/components/new-safe/steps/Step4/StatusMessage.tsx

Part of #864 
- Updates the text for each safe creation step
- Updates the text for each hint
- Updates the text for the creation modal
- Adds copy and explorer icons to addresses on the review screen as [mentioned here](https://github.com/safe-global/web-core/issues/864#issuecomment-1317934120)
- Updates layout of the connect wallet step
1. Open the Safe creation flow
2. Compare content to the design files

Safe creation text updates

---

.github/workflows/deploy.yml
.github/workflows/release.yml
scripts/github/s3_upload.sh

Resolves #1195
Ports the PR deployment action we had in safe-react.
We'll see if it works in this very PR. :)

Chore: PR deployment action

---

.github/workflows/deploy.yml

Make the deploy link stand out more.

Chore: use branch name for PR deployments + prettify the comment

---

.github/workflows/cla.yml
CLA.md

The CLA action doesn't seem to be able to post a comment in external contributors' PRs.
It says
```
Error occured when creating or editing the comments of the pull request: Resource not accessible by integration
```
Trying to figure out why.

Chore: tune the CLA action

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/cla.yml
CONTRIBUTING.md

Copies the action from https://github.com/safe-global/safe-ios/pull/2806

Chore: try a different CLA config

---

README.md

A table of required and optional env vars.

Docs: list env vars in the readme

---

cypress/e2e/tx_modal.cy.js
src/components/tx/SendFromBlock/index.tsx
src/components/tx/SendFromBlock/styles.module.css

Fix: rm balance in review modal

---

.github/workflows/build/action.yml
cypress/e2e/smoke/tx_history.cy.js
src/hooks/safe-apps/useRemoteSafeApps.ts

Resolves #1422
The fetch call wasn't caught in one place.

Fix: catch uncaught network error

---

.github/workflows/deploy-dockerhub.yml
.github/workflows/deploy.yml
scripts/github/deploy_docker.sh

Resolves safe-global/safe-infrastructure#58
Added github action to deploy web-core image to our `safeglobal` dockerhub.
Tasks:
[see this action.](https://github.com/safe-global/web-core/actions/runs/3759650670/jobs/6389471041)

chore: Added github action to deploy web-core image to our `safeglobal` dockerhub

---

src/config/chains.ts

adds 2 more chains
Venidium Testnet: https://chainlist.org/chain/4918
Venidium Mainnet: https://chainlist.org/chain/4919

add Venidium testnet and mainnet networks

---

package.json
yarn.lock

update @gnosis.pm/safe-deployments from v1.17.0 to v1.18.0

update @gnosis.pm/safe-deployments to v1.18.0

---

cypress/e2e/safe-apps/apps_list.cy.js
cypress/e2e/safe-apps/info_modal.cy.js
cypress/e2e/safe-apps/preview_drawer.cy.js

Fix e2e with the new changes and adds spec for the drawer

New safe apps design e2e

---

src/components/common/Notifications/index.tsx
src/hooks/useTxNotifications.ts

Resolves #1541
Adds an explorer link by hash.
Create and immediately execute a tx.

Feat: explorer link for unproposed txs

---

package.json
src/components/safe-apps/AppFrame/index.tsx
src/components/transactions/TxNavigation/index.tsx
src/pages/transactions/history.tsx
src/pages/transactions/messages.tsx
src/pages/transactions/navigation.tsx
src/pages/transactions/queue.tsx
yarn.lock

Uses new Feature toggle for EIP-1271 off chain messages.
Resolves #1532 
On Staging:
Check a Safe on görli => It shows messages
Check a Safe on mainnet => it shows no messages.
Currently the feature is only available on görli
None

feat: use EIP1271 feature toggle per chain

---

src/hooks/wallets/useOnboard.ts

Resolves #1600
A re-entrant lock has been added to our `connectWallet` wrapper.
When pairing via connect/switch wallet buttons and then scanning the QR code, `connectWallet` will have been called and then called again by the WalletConnect `connect` event. We cannot remove the `connectWallet` from the `connect` event callback because that is responsible for the reconnection of previously cached pairing sessions.
1. Connect to MetaMask and switch to Safe Mobile. Observe one tracking event for each wallet.
2. Switching back to MetaMask and then back to Safe Mobile should also only track each wallet once.
3. Refresh whilst connected to Safe Mobile. Observe the cached session reconnecting and one event being tracked.

fix: prevent multiple pairing tracking calls

---

src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx
src/hooks/coreSDK/useInitSafeCoreSDK.ts

Resolves #1656
The validation function only checked if the amount is <= than the allowance, but didn't check it against the total amount of the token.

Fix: spending limit max amount

---

package.json
src/components/tx/SpendingLimitRow/index.tsx
src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx

A hotfix for send amount validation (#1681)

Release 1.5.1

---

src/config/chains.ts

* Hotfix: add base-gor to the chain id dictionary

Fix: add base-gor to the chainlist

---

package.json
yarn.lock

Just a minor update of the MUI version, see https://github.com/mui/material-ui/blob/master/CHANGELOG.md

Chore: update MUI

---

package.json
src/components/balances/HiddenTokenButton/index.tsx
src/components/balances/TokenListSelect/index.tsx
src/components/common/OnboardingTooltip/index.tsx

A couple small visual tweaks for the token list filter.

v1.6.1 – adjust the text in the token list select

---

.github/PULL_REQUEST_TEMPLATE.md

@iamacook you vigilantly caught an issue on mobile in one of my PRs, so I think it would be nice to make it part of the PR checklist.

Docs: add a checklist to the PR template

---

package.json

Hotfix v1.6.2

---

cypress/e2e/smoke/balances.cy.js
package.json
public/.well-known/apple-app-site-association
src/components/common/PaginatedTxns/index.tsx
src/components/terms/index.tsx
src/components/tx/GasParams/index.tsx
src/hooks/useTxPendingStatuses.ts

backmarge `main` into `dev`

---

src/components/settings/owner/ChangeThresholdDialog/index.tsx
src/hooks/useGasPrice.ts
src/services/analytics/TagManager.ts
src/services/pairing/hooks.ts

just found some typos when browsing the codebase.

chore: fix typo

---

package.json
yarn.lock

Resolves #1796
safe-react-components has the actual fix, so we just need to update the package.

Fix: update safe-react-components

---

.github/workflows/build/action.yml

Missing env. vars. in workflow.
All env. vars. mentioned in the readme are now added in the build workflow (gateway URLs and Safe version).

fix: add missing env. var. secrets

---

src/components/dashboard/Relaying/index.tsx
src/components/sidebar/DebugToggle/index.tsx
src/hooks/useRelayingDebugger.ts
src/hooks/useRemainingRelays.ts
src/services/local-storage/useLocalStorage.ts

Backmerges main into dev after 1.8.0 release

Backmerge main > dev

---

src/hooks/wallets/useOnboard.test.ts
src/hooks/wallets/useOnboard.ts
src/services/exceptions/ErrorCodes.ts

This PR fixes #1783. Unhandled exception in useOnboard
In this PR i have added a try catch block that handles any error thrown by the getAddress() function inside the try block. If getAddress() function throws an error, the catch block will be executed and the error will be caught and logged to the console. Then, null will be returned as the value of getConnectedWallet() function.

fix: Unhandled exception in useOnboard

---

src/components/new-safe/create/steps/StatusStep/useSafeCreation.ts

Resolves #1881 
In #1815, we split up the code of `createSafe` into `createSafeViaRelayer` and `handleCreateSafe` for better readability and moved some of the conditions into the inner function calls as well. Unfortunately, this doesn't work well with how React states update and thus results in multiple inner function calls.
Reverts the abstraction we built as part of #1815 and moves all conditions back into the main function call.
1. Open the Safe app
3. Reject in Wallet
4. Retry
5. Observe there is only one transaction in the wallet
6. Reject
7. Reload the page
8. Observe the wallet prompting only one transaction
Creating a safe through relaying should still work

fix: Multiple transactions when creating a safe

---

.github/workflows/deploy.yml
docs/environments.md

@luarx will update the PR deployment to have host/S3 folder match the repo name.

Chore: rename PR deployment folder

---

src/components/common/Footer/index.tsx

Updates the Copyright text in the Footer as discussed [here](https://5afe.slack.com/archives/C03FNGQ1LTU/p1683205024311169)
1. Open the Safe Settings or Welcome page
2. Observe the new Copyright text in the Footer

fix: Update copyright text in footer

---

src/components/tx/SignOrExecuteForm/hooks.ts

A small refactor/fix for the executeTx function.
Before, it was always first proposing the tx if there's no txId. Now, it first does a signature for relayed txs which might create an id, then proposes.
Basically, this avoids two proposals in a row for "immediately relayed" transactions.
Case 1:
* Relay a transaction in a 1/1 Safe
* The "Transaction proposed successfully" notification should pop-up only once, after signing the tx (before it twice – was before and after signing)
Case 2:
* Execute a transaction in a 1/1 Safe
* The "Transaction proposed successfully" notification should pop-up before executing in the wallet (like before)

Refactor: executeTx hook

---

cypress/e2e/smoke/import_export_data.cy.js
cypress/fixtures/data_import.json
cypress/support/commands.js
src/components/settings/DataManagement/FileListCard.tsx

Resolves #2008
Test Import export of Data files in web browser
Checks imported data
Access to a safe
Checks the address book, settings, pinned apps and Data for export

test: e2e Import Export data

---

src/components/privacy/index.tsx
src/components/terms/index.tsx

* `March -> May`
* `the -> a` and `Account -> Accounts` in some instances

Text: minor edits in the Termsn and Privacy (Safe -> Safe Account)

---

src/components/transactions/ExecuteTxButton/index.tsx
src/components/transactions/SignTxButton/index.tsx
src/components/tx-flow/SafeTxProvider.tsx
src/components/tx-flow/common/TxNonce.tsx
src/components/tx-flow/flows/ConfirmTx/ConfirmProposedTx.tsx
src/components/tx-flow/flows/ConfirmTx/index.tsx
src/components/tx-flow/flows/NftTransfer/ReviewNftBatch.tsx
src/components/tx-flow/flows/NftTransfer/SendNftBatch.tsx
src/components/tx-flow/flows/NftTransfer/index.tsx
src/components/tx-flow/flows/RejectTx/RejectTx.tsx
src/components/tx-flow/flows/RejectTx/index.tsx
src/components/tx-flow/flows/TokenTransfer/CreateTokenTransfer.tsx
src/components/tx-flow/flows/TokenTransfer/ReviewTokenTransfer.tsx
src/components/tx-flow/flows/TokenTransfer/index.tsx
src/components/tx/SignOrExecuteForm/index.tsx
src/components/tx/modals/ExecuteTxModal/index.tsx

The nonce wasn't passed to the context in the right place.

Fix: pass nonce correctly

---

src/components/balances/AssetsTable/index.tsx
src/components/tx-flow/common/TxNonce/index.tsx
src/components/tx-flow/flows/TokenTransfer/index.tsx

The Send button in the AssetsTable will now open the new token transfer flow.

Send button in Assets

---

src/components/tx-flow/common/TxLayout/index.tsx
src/components/tx-flow/common/TxLayout/styles.module.css
src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
src/components/tx/SignOrExecuteForm/SignForm.tsx

The buttons are now aligned nicely.

Fix: align Next and Back buttons

---

src/components/tx-flow/common/TxLayout/index.tsx
src/components/tx-flow/common/TxLayout/styles.module.css
src/components/tx-flow/flows/NewTx/index.tsx
src/components/tx-flow/flows/NftTransfer/index.tsx
src/components/tx-flow/flows/SafeAppsTx/index.tsx
src/components/tx-flow/flows/TokenTransfer/index.tsx

TxLayout now accepts an icon for the title.

Modal title and icon

---

src/components/tx-flow/flows/TokenTransfer/CreateTokenTransfer.tsx
src/components/tx-flow/flows/TokenTransfer/index.tsx
src/components/tx-flow/flows/TokenTransfer/styles.module.css

Resolves #2096
This updates the amount selector to match that of the [new designs](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=5230-264187&t=kyq2PL3CaJr48Epo-0).
Create a transaction and observe the new styled amount selector with correct validation.

feat: amount selector

---

src/components/tx/ExecutionMethodSelector/index.tsx
src/components/tx/ExecutionMethodSelector/styles.module.css
src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
src/components/tx/SignOrExecuteForm/styles.module.css
src/components/tx/SponsoredBy/index.tsx

Tweaks execution method component style.
This slightly adjusts the style of the execution method component to match that of the [new design](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=6903-162691&t=CQl06jnWgxedwquU-0).
Create a transaction on a chain that supports relaying and observe the updated design for relaying execution.
Note: the component is also used in Safe creation and on the dashboard. No differences should be seen there.

fix: execution method style

---

src/components/tx-flow/common/TxCard/index.tsx
src/components/tx-flow/common/TxLayout/index.tsx
src/components/tx-flow/common/TxLayout/styles.module.css
src/components/tx-flow/common/styles.module.css
src/components/tx-flow/flows/TokenTransfer/ReviewTokenTransfer.tsx
src/components/tx-flow/flows/TokenTransfer/SendAmountBlock.tsx
src/components/tx-flow/flows/TokenTransfer/SendToBlock.tsx
src/components/tx-flow/flows/TokenTransfer/styles.module.css

Resolves #2027 
Implements the Figma design
- Also adjusts the TxLayout header design and spacing of TxCard
1. Create a new token transfer
2. Observe the overview screen

[TX flow] Send tokens overview

---

public/images/common/minus.svg
public/images/settings/setup/rectangle.svg
src/components/tx-flow/flows/AddOwner/ReviewOwner.tsx
src/components/tx-flow/flows/RemoveOwner/ReviewRemoveOwner.tsx
src/components/tx-flow/flows/RemoveOwner/styles.module.css

Resolves outdated design
This updates the style of the owner displays for add, remove and owner replacement transaction flows.
Add, remove or replace an owner and observe the new designs.

fix: update owner management styles

---

src/pages/apps/index.tsx

Resolves #2176
The `router.push` call was wrong.

Fix: /apps/open redirect

---

src/components/tx-flow/flows/RemoveModule/ReviewRemoveModule.tsx
src/components/tx-flow/flows/RemoveModule/index.tsx

Part of #2067 
- Adjusts the UI for remove module flow
1. Open a Safe with a module
2. Remove module
- Add icon for the "Remove module" title

[TX flow] Adjust Remove module ui

---

cypress/e2e/smoke/create_tx.cy.js
cypress/e2e/smoke/nfts.cy.js
src/components/common/TokenAmountInput/index.tsx
src/components/common/TokenAmountInput/styles.module.css
src/components/common/TxModalDialog/index.tsx
src/components/tx-flow/common/TxNonce/index.tsx
src/components/tx-flow/flows/NftTransfer/ReviewNftBatch.tsx
src/components/tx-flow/flows/NftTransfer/SendNftBatch.tsx
src/components/tx-flow/flows/TokenTransfer/CreateTokenTransfer.tsx

Send Tokens: auto-focus on the recipient field unless a recipient address is passed as a prop.

Fix: autofocus recipient if not set

---

src/components/tx/security/tenderly/index.tsx

Resolves incorrect simulation results
Extra flags are now referenced when determining a simulation failure, in a similar manner to https://github.com/safe-global/safe-wallet-web/pull/1861.
Open the Balancer Safe App and request, then simulate a double drip on the same day. Observe the simulation failure.

fix: don't rely only on fetch status for error

---

src/components/tx-flow/common/styles.module.css
src/components/tx-flow/flows/ExecuteBatch/ReviewBatch.tsx
src/components/tx-flow/flows/ExecuteBatch/index.tsx
src/components/tx-flow/flows/TokenTransfer/SendAmountBlock.tsx
src/components/tx-flow/flows/TokenTransfer/SendToBlock.tsx
src/components/tx/ErrorMessage/index.tsx
src/components/tx/security/redefine/index.tsx

Part of #2067 
- Adjusts the Batch Execute UI for the new flow
1. Open a Safe
2. Queue at least 2 transactions
3. Batch execute
4. Observe that the layout is aligned

[TX flow] Adjust batch execute ui

---

src/components/tx-flow/common/constants.ts
src/components/tx-flow/flows/AddOwner/ChooseOwner.tsx
src/components/tx-flow/flows/ChangeThreshold/ChooseThreshold.tsx
src/components/tx-flow/flows/RemoveOwner/SetThreshold.tsx
src/components/tx/SpendingLimitRow/index.tsx
src/components/tx/security/redefine/RedefineBalanceChange.tsx
src/components/tx/security/redefine/index.tsx
src/components/tx/security/tenderly/index.tsx
src/config/constants.ts

Missing tooltips
This adds the missing tooltips for:
- Threshold (add/remove/replace owner)
- Spending limit transaction type
- Balance changes
- Simulation
- Security risk
Interaction with each of the above in the transaction flow and observe the tooltips.

feat: add missing tooltips

---

src/components/tx/ApprovalEditor/ApprovalEditor.test.tsx
src/components/tx/ApprovalEditor/ApprovalEditorForm.test.tsx
src/components/tx/ApprovalEditor/hooks/useApprovalInfos.test.ts
src/components/tx/ApprovalEditor/hooks/useApprovalInfos.ts
src/components/tx/ApprovalEditor/index.tsx
src/services/security/modules/ApprovalModule/index.ts

Part of #2067
- Write tests for `ApprovalEditor`, `ApprovalEditorForm` and `useApprovalInfos`

fix: Write tests for ApprovalEditor

---

src/components/tx/security/tenderly/index.tsx

Resolves suggestion
This updates the simulation block title from "Simulate transaction" to "Run a transaction" as per suggestion.
Create a new transaction on a chain that supports simulation and observer the new title.

fix: change simulation title

---

src/components/tx-flow/common/TxLayout/styles.module.css
src/components/tx-flow/flows/NewTx/styles.module.css

Resolves misaligned progress bar
This adjusts the new transaction/transaction flow positioning so that the progress bar aligns with the "New transaction" button in the sidebar, as per design review.
Create a new transaction and observe the modal correctly aligned in both the first and further modals.

fix: align progress bar with new tx button

---

src/components/safe-apps/AddCustomAppModal/index.tsx
src/components/settings/SafeModules/index.tsx
src/config/constants.ts

Fixes some broken links pointing to the Safe docs
Replaces the links with new ones
Check the new are links are the right ones and they work properly

Update links pointing to the Safe documentation

---

src/components/common/MetaTags/index.tsx

Testing Plausible Analytics as a possible alternative of GA. For some context, here the Notion page is [here]([Link](https://www.notion.so/safe-global/Track-Safe-Wallet-OKRs-d365b10467e94f53be29a06b269ebb93) for context of Plausible Analytics)
Resolves
We want to have a better overview of the people using our interface. PA enables this with its privacy-focus approach.
As soon as data is injected in PA, we will have the first data insights and evaluate the tool.

Add Plausible Analytics script

---

package.json
src/components/tx-flow/SafeTxProvider.tsx
src/components/tx-flow/flows/ConfirmTx/ConfirmProposedTx.tsx

* Fix: delegate-created txs should have a fixed nonce (#2323)

Release 1.15.2

---

src/components/tx-flow/flows/SuccessScreen/StatusStepper.tsx

Resolves #2300 
A new "Transaction is executed" step has been added to the success screen of the new transaciton flow according to [the desings](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=5510-153193&mode=design&t=ZLyiyeogK4BFuwU0-0).
Create and execute a transaction, observing the new step.

feat: add "Transaction is executed" to stepper

---

src/components/privacy/index.tsx

Resolves #2335
This adds a new `5.15.` section for Plausible Analytics as well as updating the last updated date.
Open the privacy policy and observe the new section and updated date.

feat: add Plausible Analytics to privacy policy

---

src/components/common/MetaTags/index.tsx
src/components/privacy/index.tsx
src/config/securityHeaders.ts

Plausible Analytics was added in #2307 as an experiment.

Chore: rm Plausible Analytics script

---

cypress/e2e/smoke/balances.cy.js
cypress/e2e/smoke/create_tx.cy.js
cypress/e2e/smoke/dashboard.cy.js
cypress/e2e/smoke/pending_actions.cy.js
cypress/e2e/smoke/tx_history.cy.js
cypress/support/commands.js

Some of the smoke tests were running with a production gateway URL because staging was not indexed properly at some point. I've adjust them to only run on staging.

Tests: run e2e tests only on staging

---

src/components/common/EthHashInfo/SrcEthHashInfo/index.tsx
src/components/common/EthHashInfo/SrcEthHashInfo/styles.module.css
src/components/common/EthHashInfo/index.tsx
src/components/transactions/TxListItem/ExpandableTransactionItem.tsx
src/components/transactions/TxListItem/styles.module.css

Fix: emoji offset in tx details

---

src/components/safe-apps/types.ts
src/components/tx-flow/flows/SignMessageOnChain/ReviewSignMessageOnChain.tsx
src/hooks/loadables/useLoadSpendingLimits.ts
src/services/pairing/module.ts

Resolves #2389
Don't reset spending limits on each poll.

Fix: keep prev spending limits when polling

---

src/components/privacy/index.tsx
src/hooks/loadables/useLoadSpendingLimits.ts

Two additional changes for #2390.
* Fix: don't over-poll Spending Limits data (#2407)
* FIx: adjust privacy policy wrt cookieless tracking (#2402)

Release 1.17.0 addendum

---

package.json
yarn.lock

* fix: predicted Safe address on ZK chains (#2416)

Release 1.17.1

---

docs/release-procedure.md

Update some outdated info in the release docs.

Docs: update release-procedure.md

---

.github/workflows/cla.yml

Adds user `fmrsabino` to the CLA allowlist
NA
NA
NA

Add fmrsabino to CLA allowlist

---

cypress/e2e/pages/batches.pages.js
cypress/e2e/pages/create_tx.pages.js
cypress/e2e/pages/create_wallet.pages.js
cypress/e2e/pages/dashboard.pages.js
cypress/e2e/pages/import_export.pages.js
cypress/e2e/pages/load_safe.pages.js
cypress/e2e/pages/main.page.js
cypress/e2e/pages/nfts.pages.js
cypress/e2e/smoke/batch_tx.cy.js
cypress/e2e/smoke/create_safe_simple.cy.js
cypress/e2e/smoke/create_tx.cy.js
cypress/e2e/smoke/dashboard.cy.js
cypress/e2e/smoke/import_export_data.cy.js
cypress/e2e/smoke/landing.cy.js
cypress/e2e/smoke/load_safe.cy.js
cypress/e2e/smoke/nfts.cy.js
cypress/e2e/smoke/pending_actions.cy.js
cypress/support/constants.js

- Refactoring of existing Cypress tests
Resolves #2511 
- Implement PO Model
- General refactoring

Refactoring of existing Cypress tests (P2)

---

cypress/e2e/pages/batches.pages.js
cypress/e2e/pages/create_tx.pages.js
cypress/e2e/smoke/create_tx.cy.js

#2383 broke the create_tx test wrt the nonce editing.

Tests: fix nonce editing in create_tx

---

src/components/common/PageLayout/index.tsx
src/components/welcome/NewSafe.tsx
src/components/welcome/WelcomeLogin/styles.module.css
src/components/welcome/styles.module.css

Adds design for Welcome page sidebar
Got to welcome page and show the sidebar

feat: add sidebar design to welcome page

---

cypress/e2e/pages/create_wallet.pages.js
cypress/e2e/pages/main.page.js
cypress/e2e/pages/owners.pages.js
cypress/e2e/smoke/create_safe_simple.cy.js
cypress/e2e/smoke/remove_owner.cy.js
cypress/support/constants.js

Resolves #2603 
- Add Create Safe tests

Add create safe tests

---

src/components/dashboard/FeaturedApps/FeaturedApps.tsx
src/components/walletconnect/HeaderWidget/index.tsx
src/services/walletconnect/WalletConnectContext.tsx
src/services/walletconnect/__tests__/useWalletConnectSessions.test.tsx

The WC dashboard widget will no longer go to the app, but will open the native WC popup instead.

Feat: open WC popup on dashboard widget click

---

src/components/common/NetworkSelector/index.tsx
src/components/sidebar/SafeListItem/index.tsx
src/components/sidebar/SafeListItem/styles.module.css
src/components/walletconnect/WcInput/index.tsx
src/components/walletconnect/WcProposalForm/CompatibilityWarning.tsx
src/components/walletconnect/WcProposalForm/__tests__/useCompatibilityWarning.test.ts
src/components/walletconnect/WcProposalForm/index.tsx
src/components/walletconnect/WcSessionMananger/index.tsx
src/services/analytics/events/overview.ts
src/services/analytics/events/walletconnect.ts

Added a bunch of extra events requested by Alice.

[WalletConnect] Feat: add extra tracking events

---

src/components/transactions/HumanDescription/index.tsx

A tiny fix to avoid key prop warnings in the HumanDescription.

Fix: key prop in HumanDescription

---

cypress/e2e/pages/create_wallet.pages.js
cypress/e2e/smoke/create_safe_simple.cy.js
src/components/new-safe/create/__tests__/useSyncSafeCreationStep.test.ts
src/components/new-safe/create/useSyncSafeCreationStep.ts
src/components/welcome/WelcomeLogin/index.tsx

With seedless onboarding, the safe creation flow slightly changes so we need to adjust the e2e test for it.
Part of #2542

fix: Safe creation e2e test for seedless onboarding

---

.github/workflows/e2e.yml
.github/workflows/safe-apps-e2e.yml

Resolves #2738 
- Enable Cypress tests run in parallel

Tests: Update workflow to enable tests run in parallel

---

src/components/welcome/NewSafeSocial.tsx

Part of #2452
- Updates text and link on the social login welcome page

fix: Update welcome screen text

---

package.json
src/components/tx/ExecutionMethodSelector/index.tsx
src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
src/components/tx/SponsoredBy/index.tsx
src/hooks/useWalletCanRelay.ts

Fix: show relays even when 0 relays left

---

package.json
src/components/tx/ExecutionMethodSelector/index.tsx
src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
src/components/tx/SponsoredBy/index.tsx
src/hooks/useWalletCanRelay.ts

Resolves the disabled Execute button.

Fix: revert relaying message

---

.github/workflows/e2e-ondemand.yml

Resolves #2859 
- Update TestRail instance url

Tests: Update TestRail url

---

cypress/e2e/pages/create_tx.pages.js
cypress/e2e/regression/tx_history.cy.js
src/components/transactions/TxSigners/index.tsx
src/components/transactions/TxSummary/index.tsx

Resolves #
- Update test to run independently

Tests: Fix tx expand test

---

src/components/dashboard/PendingTxs/PendingRecoveryListItem.tsx
src/components/dashboard/PendingTxs/PendingTxListItem.tsx
src/components/dashboard/PendingTxs/styles.module.css
src/components/recovery/RecoveryCards/RecoveryInProgressCard.tsx
src/components/recovery/RecoveryCards/RecoveryProposalCard.tsx
src/components/recovery/RecoveryCards/styles.module.css
src/components/tx-flow/common/TxLayout/styles.module.css
src/components/tx-flow/flows/CancelRecovery/CancelRecoveryOverview.tsx
src/components/tx-flow/flows/CancelRecovery/styles.module.css

Resolves Mobile issues for recovery
Adjusts the mobile view of the `InProgressCard`, `ProposalCard` and cancel tx flow

Recovery mobile

---

src/components/recovery/RecoveryCards/RecoveryInProgressCard.tsx
src/components/recovery/RecoveryCards/RecoveryProposalCard.tsx
src/components/recovery/RecoveryCards/styles.module.css
src/components/settings/Recovery/ChooseRecoveryMethodModal.tsx

Resolves [Mobile issues](https://www.notion.so/safe-global/0fa7da35cc494c9ab0ec643634cacc24?v=6746502232bc4464b7ce8ced9fa3873d&p=521136a0e375498db1e8fa1d08a4daab&pm=s) and [Tracking issue](https://www.notion.so/safe-global/0fa7da35cc494c9ab0ec643634cacc24?v=6746502232bc4464b7ce8ced9fa3873d&p=521136a0e375498db1e8fa1d08a4daab&pm=s)
- Sets the RHF value when selecting a card
- Updates css to align icons on mobile

fix: Update card mobile view, set recovery method correctly

---

src/components/settings/Recovery/ChooseRecoveryMethodModal.tsx

Resolves text inconsistencies
The intro. text about each recovery method has been adjusted accordingly.
Setup recovery and observe the new texts.

fix: update recovery method texts

---

src/components/settings/Recovery/ChooseRecoveryMethodModal.tsx

Text update for recovery method according to [this](https://5afe.slack.com/archives/C060WD5UJTT/p1701706692709319?thread_ts=1701692216.878579&cid=C060WD5UJTT)

fix: Update text for recovery method

---

cypress/e2e/pages/create_tx.pages.js
cypress/e2e/regression/tx_history.cy.js
cypress/e2e/regression/tx_history_2.cy.js
cypress/fixtures/txhistory_data_data.json

Resolves #N/A
- Update test indexes

Tests: Fix test index

---

.github/workflows/cypress/action.yml
.github/workflows/e2e-smoke.yml

Resolves # N/A
- Install latest stable Chrome version to be used in all jobs

Tests: Use latest stable Chrome version in tests

---

package.json
yarn.lock

Just a patch version update for Next.js.

Chore: update Next.js to 13.5.6

---

.github/workflows/yarn/action.yml
src/components/common/ChainIndicator/styles.module.css
src/components/common/CopyTooltip/index.tsx
src/components/common/NetworkSelector/index.tsx
src/components/dashboard/PendingTxs/styles.module.css
src/components/safe-apps/SafeAppActionButtons/index.tsx
src/hooks/wallets/useOnboard.ts

Resolves #3034
* Changed the selected Network font to 14px
* Removed border from pending txs on the Dashboard
I've also aligned the Safe Apps icons (the Share icon was previously sticking out):

Fix: minor design tweaks

---

cypress/e2e/smoke/load_safe.cy.js

Just removing variables that are not used in the load_safe e2e test

Tests: Removing unused variables

---

package.json
src/components/welcome/WelcomeLogin/WalletLogin.tsx

fix: do not copy address on wallet button (#3098)

Hotfix Release 1.26.2

---

README.md

added yarn postinstall command in the readme.md file

Generate Type command instruction added in the readme.md

---

cypress/e2e/safe-apps/drain_account.spec.cy.js

Update was required to run the tests on Sepolia. 
- Updated chain to Sepolia
- Updated safes to use in these tests
Run Cypress tests and observe outcome.

Tests: fix drain account tests

---

cypress/e2e/pages/main.page.js
cypress/e2e/pages/modals.page.js
cypress/e2e/pages/sidebar.pages.js
cypress/e2e/regression/sidebar_2.cy.js
cypress/e2e/smoke/create_tx.cy.js
cypress/support/constants.js
cypress/support/localstorage_data.js
src/components/address-book/EntryDialog/index.tsx
src/components/sidebar/SafeList/index.tsx
src/components/sidebar/SafeListContextMenu/index.tsx
src/components/sidebar/SafeListItem/index.tsx
src/components/sidebar/SafeListItemSecondaryAction/index.tsx
src/components/sidebar/SafeListRemoveDialog/index.tsx
src/components/sidebar/SidebarHeader/index.tsx

Resolves #3187 
- Added new tests for sidebar
- Added data-testids to support tests
- Refactoring: need to skip create tx test due to issues in safe data - wip
**New tests:**
- Verify the safe added are listed in the sidebar
- Verify Safes are separated by networks
- Verify a safe can be renamed
- Verify a safe can be removed
- Verify the "Read only" tag if the connected user is not an owner of a safe

Tests: add sidebar tests -p2

---

src/components/safe-apps/SafeAppsHeader/index.tsx

Wording as per @lukasschor's request.

Fix: edit Safe Apps heading

---

src/components/safe-apps/AddCustomAppModal/index.tsx
src/config/constants.ts

The old link was giving a 403.

Fix: update the Safe Apps SDK link

---

cypress/e2e/pages/dashboard.pages.js
src/components/dashboard/Overview/Overview.tsx
src/components/dashboard/index.tsx
src/components/sidebar/SidebarHeader/index.tsx

Part of #3207
- Updates the design for the overview widget
- Adds tracking for the Receive button and extends it by a label to differentiate between the same button in the sidebar
1. Open the dashboard
2. Compare the new design ([Figma](https://www.figma.com/file/fUOaMHVOhsIylBjxiL5uEn/Counterfactual-deployment?node-id=3220%3A26989&mode=dev))
3. Make sure to also check Buy Crypto on a supported chain

[Counterfactual] Implement the dashboard overview widget design

---

src/components/sidebar/Sidebar/index.tsx
src/components/sidebar/Sidebar/styles.module.css

Resolves #3194 
the issue is coming from the MUI <IconButton /> component i decided to remove the component and updated with the normal <button /> element now the issue is resolved and tested in the both chrome and safary.
https://github.com/safe-global/safe-wallet-web/assets/43741383/7a9b294c-a0c4-407a-8629-52ecfc1c189c

[Safari] Sidebar CSS is broken fix

---

src/components/common/ChainIndicator/index.tsx
src/components/common/ChainIndicator/styles.module.css
src/components/sidebar/Sidebar/index.tsx
src/components/welcome/MyAccounts/AccountItem.tsx
src/components/welcome/MyAccounts/index.tsx
src/components/welcome/MyAccounts/styles.module.css

Add the simplified safe list created in #3233 to the sidebar
- go to any safe dashboard and open the sidebar from there.

Display simplified safelist in the sidebar

---

src/components/common/BuyCryproButton/index.tsx
src/components/dashboard/Overview/Overview.tsx

Resolves #3068
Added styles
Check styles
It is my first PR for your repository. Please let me know if I have made any mistakes related to your coding style guidelines

fix: edit styles for assets in Overview widget

---

cypress/e2e/pages/create_wallet.pages.js
cypress/e2e/pages/load_safe.pages.js
cypress/e2e/pages/sidebar.pages.js
cypress/e2e/smoke/create_safe_simple.cy.js
cypress/e2e/smoke/load_safe.cy.js
src/components/new-safe/OwnerRow/index.tsx
src/components/new-safe/load/steps/SetAddressStep/index.tsx

Resolves #3294 
- Add more tests for adding safes

Tests: add load safe tests

---

cypress/e2e/pages/load_safe.pages.js
cypress/e2e/pages/main.page.js
cypress/e2e/regression/load_safe_2.cy.js
cypress/e2e/smoke/load_safe.cy.js
cypress/support/constants.js
cypress/support/localstorage_data.js

Resolves #3294 
- Add more tests for adding safes

Tests: add more load safe tests

---

src/components/common/MetaTags/index.tsx

Resolves #3297 3297
added <meta name="robots" content="noindex" /> in the MetaTags

Add noindex meta tag to prevent search engine indexing

---

src/hooks/useGasLimit.ts

Resolves #3183 
`getEncodedSafeTx` can throw for invalid values like uneven byteslike lengths and since it didn't catch those errors it would crash the app.
Moves the `getEncodedSafeTx` and `operationType` calls into the `useAsync` so errors are caught and displayed to the user instead. We also need to make the callback async to achieve this. Since both variables are only used within the `useAsync`, having the memoized isn't necessary.
1. Open the tx-builder safe app
2. Create a transaction with custom data and choose `0x0` as the data
3. Send the transaction
4. Observe the app not crashing
5. Observe an error shown in the tx-flow modal instead

fix: Catch errors during gas limit estimation

---

src/components/welcome/MyAccounts/AccountItem.tsx

Resolves #3341
- Restores the `getHref` function that was previously in the `SafeList` component
1. Open a safe
2. Navigate to any route
3. Switch to a different safe
4. Observe being on the same route
5. Open the single tx view
6. Switch to a different safe
7. Observe being navigated to the tx history
8. Go to the welcome page
9. Select a safe there
10. Observe being navigated to the dashboard

fix: Stay on the same route when switching safes

---

cypress/e2e/pages/create_wallet.pages.js
cypress/e2e/pages/load_safe.pages.js
cypress/e2e/pages/owners.pages.js
cypress/e2e/regression/create_safe_simple_2.cy.js
cypress/e2e/regression/load_safe_2.cy.js
cypress/e2e/smoke/load_safe.cy.js
src/components/new-safe/OwnerRow/index.tsx
src/components/new-safe/create/steps/OwnerPolicyStep/index.tsx

Resolves #3347 
- Add more safe creation tests

Tests: add safe creation tests

---

src/components/common/CodeInput/__tests__/index.test.tsx
src/components/common/CodeInput/index.tsx
src/components/common/CodeInput/styles.module.css
src/components/common/CooldownLink/index.test.tsx
src/components/common/CooldownLink/index.tsx
src/components/tx/ErrorMessage/index.tsx
src/components/tx/ErrorMessage/styles.module.css
src/features/recovery/components/RecoveryEmail/RegisterEmail.tsx
src/features/recovery/components/RecoveryEmail/VerifyEmail.tsx
src/features/recovery/components/RecoveryEmail/index.tsx
src/features/recovery/components/RecoveryEmail/useRecoveryEmail.ts
src/tests/test-utils.tsx

Resolves #3321
- Adds a new component `CodeInput` and updates `CooldownLink` (Copied from #2968)
- Adds a new component `VerifyEmail`
1. Register an email address
2. Observe the verify dialog opens
3. Close the dialog and reload the page
4. Press Sign to view
5. Observe an unverified email info showing
6. Press "Verify"
7. Observe the verify dialog opens
8. Type in the verification code and submit
9. Observe the verify dialog closes
10. Observe a success notification
11. Observe the unverified email info disappears
- The Verify button should be disabled until all digits are entered
- Pressing Verify and Resend should already do the correct network requests

feat: [Recovery] Verify email

---

src/features/recovery/components/RecoveryEmail/RegisterEmail.tsx
src/features/recovery/components/RecoveryEmail/index.tsx
src/features/recovery/components/RecoveryEmail/useRecoveryEmail.ts

Resolves #3146 
- Adds a new function `editEmailAddress`
1. Add an email (either verified or not verified)
2. Press Sign to view
3. Observe an edit button next to the email address
4. Press the edit button
5. Observe the register form opens with the email address pre-filled
6. Change the email address
7. Observe a signature request
8. Sign
9. Observe the verify email dialog opens
10. Verify the email
11. Observe the register form closes
12. Observe the new email address is visible

feat: [Recovery] Edit email

---

cypress/e2e/pages/create_wallet.pages.js
cypress/e2e/regression/create_safe_google.cy.js
cypress/e2e/regression/create_safe_simple.cy.js
cypress/e2e/smoke/create_safe_simple.cy.js
src/components/welcome/WelcomeLogin/WalletLogin.tsx
src/components/welcome/WelcomeLogin/index.tsx
src/pages/index.tsx

The redirect fron '/` to the last opened Safe hasn't been working reliably recently, but also it conceptually complicates the user flow.
We want the Welcome page to be the starting point of the app, w/o a hidden redirect logic.

Fix: remove broken index redirect

---

src/components/tx-flow/flows/ReplaceTx/index.tsx
src/utils/chains.ts

A feature toggle for the Delete Transaction feature.

Feat: feature toggle for tx deletion

---

package.json
src/features/walletconnect/services/WalletConnectWallet.ts
src/features/walletconnect/services/__tests__/WalletConnectWallet.test.ts

* Revert "fix: cannot connect with WC to Opensea (#3437)

Release 1.32.1

---

.eslintrc.json
.gitignore
.storybook/main.ts
.storybook/preview.ts
package.json
src/components/common/CopyButton/index.stories.tsx
src/components/common/CopyButton/index.tsx
src/components/common/DateTime/DateTime.stories.tsx
src/components/common/DateTime/DateTime.tsx
src/components/common/DateTime/DateTimeContainer.tsx
src/components/common/DateTime/index.tsx
src/stories/Configure.mdx
yarn.lock

This commit ads Storybook support: https://storybook.js.org
Files ending with .stories.tsx will appear inside of the storybook UI where we get preview for those UI components.
Currently it is very hard to figure out which component can be reused when we build a new feature. We have a lot of designs in figma, but it is hard to find out if we have implemented reusable components that could be used to speed up the development of a new feature. With storyboard we get a place where we can display those reusable components. In addition to this storyboard forces us to think in "composable components" starting from the smallest UI elements and composing up. One first things about the props a component should receive, builds the UI around it with the different possible stats and later just feeds …

chore: storybook

---

src/features/speedup/components/SpeedUpMonitor.tsx
src/utils/chains.ts

Adds a feature toggle to the speed up tx feature.
- Currently the feature is only enabled on Sepolia on staging.

feat: add feature toggle for speed-up tx

---

cypress.config.js
cypress/e2e/happypath/sendfunds_queue_1.cy.js
cypress/e2e/pages/assets.pages.js
cypress/e2e/pages/main.page.js
cypress/e2e/pages/transactions.page.js
cypress/support/api/utils_ether.js
cypress/support/api/utils_protocolkit.js
cypress/support/constants.js

Resolves #3541 
- Add integration of Protocol Kit into Cypress tests to better manage test data

Tests: add protocolkit integration in cypress project

---

cypress/e2e/happypath/recovery_hp_1.cy.js
cypress/e2e/pages/recovery.pages.js

- Handle deletion of multiple recoverers to avoid tests to fail.

Tests: handle deletion of multiple recoverers

---

src/components/common/SafeTokenWidget/index.tsx
src/config/constants.ts
src/hooks/__tests__/useSafeTokenAllocation.test.ts
src/hooks/useSafeTokenAllocation.ts

Resolves https://www.notion.so/safe-global/Change-voting-power-computation-08023afef09e4676b7a9020d0d7ba7f3?pvs=4
Changes voting power calculation to include SAFE tokens that are in the locking contract. This includes locked tokens and unlocked but not yet withdrawn tokens.
- Open a safe with some SAFE tokens allocated.
- Check that the number shown in the header is correct according to the formula: `(allocation - claimed) + token balance + locking balance`

Feat: update voting power calculation to include locking contract tokens

---

.github/workflows/build-storybook/action.yml
.github/workflows/deploy-dev.yml

This PR ads a github action that builds our storybook together with the site and publishes it.
The URL to the storybook can be viewed in the comment.

feat: add a build of storybook to PRs

---

src/components/common/SocialSigner/index.tsx

Feat: add a warning about Google login

---

src/features/swap/components/StatusLabel/index.stories.tsx
src/features/swap/components/StatusLabel/index.tsx
src/features/swap/components/SwapOrder/index.stories.tsx
src/features/swap/components/SwapOrder/index.tsx

This PR implements the different Sell Orders https://www.figma.com/file/VyA38zUPbJ2zflzCIYR6Nu/Swap?type=design&node-id=1-3&mode=design&t=fZkl3tqjIWoYsB9C-0
Resolves #

WIP: Feat cow swap sell order storybook

---

.github/workflows/cypress/action.yml

- Update Cypress workflow to add wallet credentials

Tests: update workflow to add wallet credentials

---

package.json
yarn.lock

The swap page was suffering from High CPU usage. With the latest cowswap react-widget update this is fixed.

fix: CowSwap high CPU usage

---

package.json
src/components/common/SafeTokenWidget/index.tsx

* Update the URL of the Governance Safe App link in the header

Fix: governance -> community

---

src/features/swap/index.tsx

Resolves [Notion issue](https://www.notion.so/safe-global/Remove-fee-1bf529eb594d488ab28f68791c9926e5)
Removes the fee from the widget config
1. Create a swap
2. Observe no swap fee in the widget

fix: Remove swap fee

---

src/components/tx/SignOrExecuteForm/index.tsx
src/features/speedup/components/SpeedUpModal.tsx
src/hooks/useTxTracking.ts
src/services/analytics/__tests__/tx-tracking.test.ts
src/services/analytics/gtm.ts
src/services/analytics/tx-tracking.ts
src/services/analytics/types.ts

fix: Revert orderUid tracking

---

package.json
src/features/swap/index.tsx
yarn.lock

We need to show a custom fee label in the swap widget.
Create a new swap through the widget - you should see the custom fee label & tooltip

feature: custom swap fee label [SWAP-76]

---

package.json
src/features/swap/index.tsx
yarn.lock

- custom swap fee label (#3692)

Release 1.36.1

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-production.yml
.github/workflows/e2e-hp-ondemand.yml
.github/workflows/e2e-ondemand.yml
.github/workflows/e2e-regression.yml
.github/workflows/e2e-safe-apps.yml
.github/workflows/e2e-smoke.yml
.github/workflows/lint.yml
.github/workflows/nextjs-bundle-analysis.yml
.github/workflows/tag-release.yml
.github/workflows/unit-tests.yml
package.json
src/features/swap/index.tsx

* fix: feeTooltip text was wrong (#3697)
* Chore: move checksum upload step (#3694)

Release 1.36.2

---

cypress/e2e/happypath/sendfunds_connected_wallet.cy.js
cypress/e2e/smoke/create_tx.cy.js

- Fix failing tests due to change in a safe
- Update safe balance to correct value

Tests: fix failing tests

---

cypress/e2e/pages/safeapps.pages.js
cypress/e2e/regression/messages_popup.cy.js
cypress/e2e/safe-apps/info_modal.cy.js
src/components/safe-apps/SafeAppPreviewDrawer/index.tsx

- Add action to open safe app in tests

Tests: fix open safe app test

---

src/components/dashboard/ActivityRewardsSection/index.tsx

feat: activate points step

---

src/components/common/SocialLoginDeprecation/index.tsx
src/components/common/SocialSigner/index.tsx
src/components/welcome/MyAccounts/styles.module.css

Resolves #3732
End of life support is extended till July.

Fix: update social login disclaimer

---

cypress/e2e/happypath/tx_history_filter_hp_1.cy.js
cypress/e2e/happypath/tx_history_filter_hp_2.cy.js
cypress/e2e/pages/create_tx.pages.js
cypress/e2e/pages/owners.pages.js
cypress/e2e/smoke/tx_history_filter.cy.js
cypress/support/utils/txquery.js
src/components/transactions/TxFilterForm/index.tsx

- Add more tests for tx history filter: API and UI tests
- Fix bug on dev which occurred due to overlay when clicking on 'body'

Tests: add tx filter tests

---

.github/workflows/deploy-dev.yml
next-env.d.ts

The condition to check the PR branch was wrong.

Chore: fix branch conditionals

---

cypress/support/commands.js
cypress/support/e2e.js

Tests: Update cypress headers

---

cypress.config.js
cypress/e2e/happypath/sendfunds_connected_wallet.cy.js
cypress/e2e/pages/create_tx.pages.js
cypress/e2e/pages/spending_limits.pages.js
cypress/e2e/regression/spending_limits.cy.js
cypress/e2e/safe-apps/permissions_settings.cy.js
cypress/e2e/smoke/messages_offchain.cy.js
cypress/fixtures/txmessages_data.json
cypress/support/commands.js

- Move offline messages tests to Smoke suite
- Fix failing tests on dev
- Skip permissions tests 
- Increase test retries
- Refactor/add spending limit tests

Tests: Fix-refactor tests

---

cypress.config.js
cypress/e2e/pages/assets.pages.js
cypress/e2e/regression/balances_pagination.cy.js
cypress/e2e/regression/sidebar_2.cy.js
cypress/e2e/regression/tokens.cy.js
cypress/support/constants.js

Tests: Fix regression tests

---

src/components/sidebar/SidebarNavigation/config.tsx

Fix: Chip warnings about nested tags

---

next-env.d.ts
src/services/private-key-module/index.ts
src/tests/e2e-wallet.ts

`eth_signTypedData` was incorrectly mapped for the test Private Key wallet module.

Fix: signTypedData for the test wallet

---

src/components/new-safe/create/steps/OwnerPolicyStep/index.tsx

Resolves #3824
Removes the block from the code.

Fix: remove mobile signer promo

---

src/components/tx/security/redefine/useRedefine.ts

Tx nonce is updated in real-time when creating a new transaction. At first it takes the Safe nonce, then a recommended nonce is fetched and the safeTx object is updated with that.
This triggers two risk scanning requests where the only difference is the nonce.
Since the risk API doesn't seem to care about nonces, I made it always send 0, as well as memoizing the payload as JSON.
On prod (so without this fix):
* Go to Swaps
* Create a swap of any two tokens
* Open the console and filter Network Requests by `risk`
* Confirm the swap to see the Safe Tx confirmation modal
* Observe two `/messages` requests
On this branch:
* Only one `/messages` request

Fix: ignore nonce for risk scanning requests

---

package.json
src/components/tx/security/redefine/useRedefine.ts

* Fix: ignore nonce for risk scanning requests (#3854)

Release 1.38.1

---

src/pages/privacy.tsx

* Removal of Web3Auth
* Section about data analysis

Chore: update privacy policy

---

src/components/dashboard/ActivityRewardsSection/index.tsx
src/components/dashboard/GovernanceSection/GovernanceSection.tsx
src/components/dashboard/GovernanceSection/styles.module.css
src/components/dashboard/index.tsx
src/hooks/useOnceVisible.ts

Part of #3323
The governance widget makes a few requests to CGW from below the fold. This PR defers the rendering of this widget until the user scrolls to it.

Refactor: lazy-load governance widget

---

src/components/common/MetaTags/index.tsx

The old text was outdated. New text approved by Ani.

Fix: update meta description

---

cypress/e2e/pages/assets.pages.js
cypress/e2e/regression/create_safe_simple.cy.js
cypress/e2e/regression/nfts.cy.js

Tests: Fix tests

---

cypress/e2e/pages/swaps.pages.js
cypress/e2e/regression/swaps.cy.js
cypress/e2e/regression/swaps_history.cy.js
cypress/e2e/regression/swaps_history_2.cy.js
cypress/fixtures/swaps_data.json

Tests: Add swap tests

---

cypress/e2e/regression/swaps.cy.js

Tests: Increase waiters in swap tests

---

src/components/settings/FallbackHandler/index.tsx

Part of #3882 
Forgot to remove a console-log

fix: Remove console-log

---

cypress/e2e/pages/main.page.js
cypress/e2e/pages/sidebar.pages.js
cypress/e2e/pages/swaps.pages.js
cypress/e2e/regression/sidebar_2.cy.js
cypress/e2e/regression/sidebar_3.cy.js
cypress/e2e/regression/swaps_history_2.cy.js
cypress/support/localstorage_data.js

Tests: Add sidebar tests

---

src/pages/terms.tsx

Updates terms and conditions based on the changes made here: https://docs.google.com/document/d/1mfHZAo8GLzwkUUPROD_9p-Dpwh45oNlxfo-zyZHgiRQ/edit#heading=h.spy5u325ndtz

Feat: update terms and conditions page [SW-58]

---

cypress/e2e/happypath/sendfunds_connected_wallet.cy.js
cypress/e2e/happypath/sendfunds_relay.cy.js

Tests: Update hp tests

---

cypress/e2e/pages/swaps.pages.js
cypress/e2e/regression/swaps.cy.js
cypress/fixtures/swaps_data.json
src/features/swap/components/SwapOrderConfirmationView/OrderFeeConfirmationView.tsx
src/features/swap/components/SwapOrderConfirmationView/index.tsx

- Add tests to check order details in Swap confirmation window

Tests: Order details tests

---

src/pages/terms.tsx

Updates last edited date and adds some missing commas

chore: update terms page with corrections

---

src/components/common/CookieAndTermBanner/index.tsx
src/features/swap/components/LegalDisclaimer/index.tsx
src/features/swap/index.tsx

- show last update in t&c
- adjust fee tooltip
- replace "Legal disclaimer" with "Note"

Fix: wording changes

---

package.json

chore: bump package.json

---

cypress/e2e/happypath/sendfunds_connected_wallet.cy.js
cypress/e2e/happypath/sendfunds_relay.cy.js
cypress/e2e/regression/sidebar_3.cy.js
cypress/e2e/regression/swaps.cy.js
cypress/e2e/regression/tx_history.cy.js
cypress/e2e/regression/tx_history_2.cy.js
cypress/fixtures/history.json

- Fix failing happy path and regression tests

Tests: Fix regression and hp tests

---

package.json
src/components/tx/SignOrExecuteForm/index.tsx
src/features/swap/helpers/utils.ts
src/services/safe-wallet-provider/useSafeWalletProvider.test.tsx
src/services/safe-wallet-provider/useSafeWalletProvider.tsx

* Fix: valueDecoded must be an array (#3940)
* Fix: prompt -> confirm (#3939)

Release 1.39.2

---

cypress/e2e/pages/batches.pages.js
cypress/e2e/regression/batch_tx.cy.js
cypress/e2e/smoke/batch_tx.cy.js
cypress/support/constants.js
cypress/support/localstorage_data.js

Tests: Add more batch tests

---

.github/workflows/cypress/action.yml
.github/workflows/e2e-prod-ondemand.yml
cypress/e2e/prodhealthcheck/recovery.cy.js

Tests: Add health check tests to prod

---

.github/workflows/cypress/action.yml

- Update Cypress action to latest version (v6)

Tests: Update cypress action to latest version

---

cypress/e2e/regression/messages_onchain.cy.js
cypress/e2e/regression/tx_history.cy.js
cypress/e2e/regression/tx_history_2.cy.js
cypress/fixtures/txhistory_data_data.json

Fixing the e2e tests that were broken in #3967.

Tests: fix tx destails tests

---

cypress/e2e/pages/create_tx.pages.js
src/components/transactions/BatchExecuteButton/index.tsx
src/components/tx-flow/flows/ExecuteBatch/ReviewBatch.tsx

Resolves #3217
I've removed "light green" from the text.

Fix: bulk tx tooltip wording

---

src/components/welcome/MyAccounts/AccountItem.tsx

Resolves #4039
Don't show a loader for CF safes.

Fix: no balance skeleton for counterfactual safes

---

src/components/tx-flow/flows/RejectTx/RejectTx.tsx
src/components/tx/DecodedTx/index.tsx
src/components/tx/SignOrExecuteForm/index.tsx

Resolves https://www.notion.so/safe-global/Rejection-has-advanced-details-and-it-shouldn-t-f7c7ae2514354c34860d9c3565c20b58
The value check was incorrect as value is a string.

Fix: native transfer only if value > 0

---

src/components/new-safe/create/steps/SetNameStep/index.tsx

If a user switches the network during Safe creation the latest Safe version of the first chain was still being used.
- Updates the latest Safe version when the network changes.
Currently on Prod 1.4.1 is only used on Sepolia.
- Switch network to Sepolia
- Start Safe creation flow
- Go to owner Step
- Now switch network to e.g. Base Sepolia
- Continue Safe creation on Base Sepolia and witness that 1.3.0 is correctly used instead of Sepolia's 1.4.1 version

fix: update latest Safe version when switching chains during creation

---

package.json
src/components/common/Table/styles.module.css
src/components/transactions/TxDetails/TxData/DecodedData/MethodDetails/index.tsx
src/components/transactions/TxDetails/TxData/DecodedData/index.tsx

A hot fix for tx details: contract method parameters must be always displayed.

Release 1.41.3

---

.github/dependabot.yml

Dependabot config for automated package updates. It works even w/o this config but it allows customizing the default behavior of Dependabot, e.g. set an interval, what packages to ignore etc.

Chore: create dependabot.yml

---

src/utils/__tests__/formatNumber.test.ts

test: add formatNumber test case

---

package.json
src/services/tx/tx-sender/create.ts
yarn.lock

An upgrade of the protocol-kit that has static network enabled for the JSON RPC provider to reduce the number of RPC calls.

Chore: upgrade protocol-kit

---

cypress/e2e/regression/create_tx.cy.js
cypress/e2e/regression/swaps_history_2.cy.js
cypress/e2e/regression/tokens.cy.js

- Use ls to accept user consent
- Adjust history tests
- Remove propose request in create tx tests

Tests: Fix regression cy 2

---

cypress/e2e/prodhealthcheck/load_safe.cy.js

- Remove duplicate test suites titles to allow TestRail to parse the results correctly

Tests: Remove duplicate tests

---

.github/workflows/unit-tests.yml
src/components/address-book/ImportDialog/__tests__/validation.test.ts

Trying to find a more modern, maintained and flexible action that would work in external PRs too.

Chore: update jest action

---

src/pages/imprint.tsx

Update the imprint as per legal's request.

Legal: update imprint

---

src/components/common/ModalDialog/index.tsx
src/components/common/ModalDialog/styles.module.css
src/components/common/NetworkSelector/index.tsx
src/components/common/NetworkSelector/styles.module.css
src/components/dashboard/FirstSteps/index.tsx
src/components/welcome/MyAccounts/AccountItem.tsx
src/components/welcome/MyAccounts/MultiAccountItem.tsx
src/components/welcome/MyAccounts/styles.module.css
src/features/multichain/components/CreateSafeOnNewChain/index.tsx
src/features/multichain/components/NetworkLogosList/index.tsx
src/features/multichain/components/NetworkLogosList/styles.module.css

Resolves [SW-244](https://www.notion.so/safe-global/Small-design-tweaks-1118180fe57380e08ee4f1f3477f5c6b)
Addresses feedback from this document: https://www.notion.so/safe-global/Insights-Feedback-on-Multichain-10c8180fe57380eba5efded223e0aa70
- Reuses `NetworkLogosList` inside the SafeList
- Adjusts `NetworkLogosList` to optionally only display the first 4 networks
Compare screenshots to Figma design

[Multichain] fix: Adjust multichain design [SW-244]

---

src/components/tx-flow/flows/EnableSafenet/ReviewEnableSafenet.tsx
src/hooks/__tests__/useLoadBalances.test.ts
src/hooks/loadables/useLoadBalances.ts
src/pages/settings/safenet.tsx
src/store/safenet.ts
src/utils/safenet.ts
yarn.lock

This pull request introduces several updates to the SafeNet integration, including new utility functions, API changes, and updates to various components to support these changes. 
Implements https://github.com/safe-global/safenet/issues/44
The most important changes are grouped by theme as follows:
* [`src/hooks/loadables/useLoadBalances.ts`](diffhunk://#diff-719a07107449842c596d71bdde56928c6ea1844db785ed06f58b814ab62bc8e8R14-R16): Added logic to fetch and merge balances from SafeNet and the existing balance source, including new utility functions for balance conversion and chain support checks. [[1]](diffhunk://#diff-719a07107449842c596d71bdde56928c6ea1844db785ed06f58b814ab62bc8e8R14-R16) [[2]](diffhunk://#diff-719a07107449842c596d71bdde56928c6ea1844db785ed06f58b814ab62bc8e8R30-L53) …

Feature: Safenet balance in the assets tab

---

cypress/e2e/pages/create_tx.pages.js
cypress/e2e/pages/safeapps.pages.js
cypress/e2e/prodhealthcheck/add_owner.cy.js
cypress/e2e/prodhealthcheck/create_tx.cy.js
cypress/e2e/prodhealthcheck/load_safe.cy.js
cypress/e2e/prodhealthcheck/messages_onchain.cy.js
cypress/e2e/prodhealthcheck/remove_owner.cy.js
cypress/e2e/prodhealthcheck/sidebar.cy.js
cypress/e2e/prodhealthcheck/spending_limits.cy.js
cypress/e2e/prodhealthcheck/swaps_history_2.cy.js
cypress/e2e/prodhealthcheck/swaps_tokens.cy.js
cypress/e2e/prodhealthcheck/tokens.cy.js
cypress/e2e/prodhealthcheck/tx_history.cy.js
cypress/e2e/regression/swaps_history_2.cy.js
cypress/e2e/safe-apps/tx-builder.spec.cy.js
cypress/fixtures/swaps_data.json

- Prod test suite cleanup
- Add additional tests for advanced details for tx builder tests

Tests: Cleanup prod tests

---

.github/workflows/e2e-ondemand.yml
cypress/e2e/pages/create_wallet.pages.js
cypress/e2e/pages/owners.pages.js
cypress/e2e/regression/create_safe_cf.cy.js
cypress/e2e/regression/create_safe_simple.cy.js
cypress/e2e/smoke/import_export_data.cy.js
src/components/common/NetworkSelector/NetworkMultiSelector.tsx
src/components/new-safe/create/steps/OwnerPolicyStep/index.tsx
src/components/tx-flow/flows/RemoveOwner/SetThreshold.tsx

- Update automation tests to respect new multi chain flow
- Remove happy path tests from regression run workflow

Tests: Update automation tests

---

cypress/e2e/pages/create_tx.pages.js
cypress/e2e/prodhealthcheck/swaps_tokens.cy.js
cypress/e2e/regression/add_owner.cy.js
cypress/e2e/regression/swaps.cy.js

- Add owner and swap tokens tests were flaky. To fix it, conditional logic and waiters were added.

Tests: Fix flaky tests

---

package.json
src/features/counterfactual/CounterfactualSuccessScreen.tsx

Backmerge of `main` to `dev` after 1.45.0 release.

chore: Backmerge main -> dev

---

package.json
src/components/common/NetworkSelector/NetworkMultiSelector.tsx
src/components/new-safe/create/logic/index.ts
src/components/safe-apps/AppFrame/TransactionQueueBar/index.tsx
src/components/transactions/TxDetails/TxData/MigrationToL2TxData/index.tsx
src/features/multichain/hooks/__tests__/useCompatibleNetworks.test.ts
src/features/multichain/hooks/useCompatibleNetworks.ts
yarn.lock

* fix: check deployments of migration contracts, upgrade safe-deployments (#4407)
* Chore(deps): Bump @mui/material from 5.15.1 to 5.16.7 (#4315)

Release 1.45.2

---

package.json

Merged `main` into `dev` after release.

Backmerge release 1.45.2

---

src/components/transactions/TxDetails/Summary/index.tsx
src/components/tx/SignOrExecuteForm/SafenetTxChecks.tsx
src/components/tx/SignOrExecuteForm/index.tsx
src/components/tx/security/safenet/index.tsx
src/store/safenet.ts

Resolves [#70](https://github.com/safe-global/safenet/issues/70)

Recipient signature verification

---

cypress/e2e/regression/add_owner.cy.js

- Add step to clear all txs before test

Tests: Fix add owner test

---

src/components/tx/security/safenet/index.tsx
src/hooks/loadables/useLoadBalances.ts
src/utils/safenet.ts

- Put `no_contract_recipient` with `no_delegatecall` to avoid overriding the `recipient_signature`'s status
- Manage balance merge between Safenet and CGW (icons URI, decimals, fiat conversion and total)
Resolves #

Safenet token balance fix

---

src/components/common/GradientBoxSafenet/index.tsx
src/components/sidebar/Sidebar/styles.module.css
src/components/sidebar/SidebarHeader/index.tsx
src/components/sidebar/SidebarHeader/styles.module.css
src/components/transactions/TxDetails/Summary/styles.module.css
src/components/welcome/MyAccounts/styles.module.css

This PR refactors the sidebar to also use a gradient border. It pushes the drawer button down to not cover Safe information.

Refactor Sidebar Gradient Box

---

package.json

Release 1.46.0

---

package.json
src/components/tx-flow/common/TxStatusWidget/index.tsx
src/features/proposers/components/DeleteProposerDialog.tsx

Backmerges main -> dev and resolves merge conflicts

Backmerge main -> dev

---

src/hooks/loadables/useLoadBalances.ts
src/store/safenet.ts

Related to [#90](https://github.com/safe-global/safenet/issues/90) - Revisit Safenet API

Related to #90 - Revisit the API

---

cypress/e2e/pages/create_wallet.pages.js
cypress/e2e/regression/create_tx.cy.js
cypress/e2e/regression/multichain_create_safe.cy.js
cypress/e2e/regression/multichain_create_safe_flow.cy.js
cypress/support/constants.js
src/components/new-safe/create/steps/ReviewStep/index.tsx
src/features/counterfactual/CounterfactualSuccessScreen.tsx

- Add tests for multichain safe creation flow

Tests: Add multichain safe creation flow tests

---

package.json
src/components/safe-messages/DecodedMsg/index.tsx
src/components/safe-messages/MsgDetails/index.tsx
src/components/safe-messages/MsgListItem/ExpandableMsgItem.tsx

* A fix for a crash on the Messages page

Release 1.47.1

---

src/hooks/__tests__/usePendingTxs.test.ts
src/hooks/usePendingTxs.ts

Resolves [duplicate "Queue" section](https://www.notion.so/safe-global/Nested-safe-v1-Mess-in-the-queue-with-pending-section-2-queued-sections-and-next-in-between-1378180fe57380cb868be95e7a4f46a2)
The "Pending" section of the queue contains immediately executed (untrusted) transactions.
Our `usePendingTxsQueue` [assumes there is only one pending transaction](https://github.com/safe-global/safe-wallet-web/blob/only-next-pending/src/hooks/usePendingTxs.ts#L58). However, if multiple untrusted transactions are proposed (particularly via nested signing), there can be >1 pending transactions, e.g. next label, transaction, queue label, transaction.
The current implementation therefore returns the "Pending" ("Next") section and "Queue" - duplicating the "Queue" section:
This returns only the …

fix: only return "next" transactions as pending

---

cypress/e2e/regression/balances_pagination.cy.js

- A step updated to navigate to the correct URL

Test: Update steps

---

cypress/e2e/pages/sidebar.pages.js
cypress/e2e/prodhealthcheck/add_owner.cy.js
cypress/e2e/prodhealthcheck/create_tx.cy.js
cypress/e2e/prodhealthcheck/load_safe.cy.js
cypress/e2e/prodhealthcheck/messages_onchain.cy.js
cypress/e2e/prodhealthcheck/multichain_network.cy.js
cypress/e2e/prodhealthcheck/nfts.cy.js
cypress/e2e/prodhealthcheck/remove_owner.cy.js
cypress/e2e/prodhealthcheck/sidebar.cy.js
cypress/e2e/prodhealthcheck/sidebar_3.cy.js
cypress/e2e/prodhealthcheck/spending_limits.cy.js
cypress/e2e/prodhealthcheck/swaps_history_2.cy.js
cypress/e2e/prodhealthcheck/swaps_tokens.cy.js
cypress/e2e/prodhealthcheck/tokens.cy.js
cypress/e2e/prodhealthcheck/tx_history.cy.js
cypress/e2e/prodhealthcheck/tx_history_2.cy.js
cypress/support/utils/wallet.js

- Update prod tests to include accept cookies step where required.
- Update connect wallet method

Tests: Update prod tests

---

src/markdown/privacy/privacy.md

Resolves [SW-357](https://www.notion.so/safe-global/Update-privacy-policy-1228180fe57380ae9e5dd04da9e084f9)
- Adds a section for Fingerprint to the privacy policy
1. Open the privacy policy page
2. Observe a new section regarding Fingerprint

fix: Update privacy policy to include Fingerprint usage [SW-357]

---

package.json
src/components/common/SafeTokenWidget/index.tsx
src/hooks/useSafeTokenAllocation.ts
src/markdown/privacy/privacy.md
src/services/safe-wallet-provider/index.test.ts

- feat: Update header safe token widget for SAP [SW-586] (#4565)
- fix: Update privacy policy to include Fingerprint usage [SW-357] (#4605)
- fix: Exclude SAP allocation from voting power (#4610)
- Tests: fix safe-wallet-provider unit tests (#4606)

Release 1.47.4

---

package.json
yarn.lock

Updates the protocol-kit to support a new network
Resolves #
Bumping the protocol-kit version

Chore: Update protocol kit to add new network

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/PULL_REQUEST_TEMPLATE.md
.lintstagedrc.json
.prettierignore
apps/web/.storybook/main.ts
apps/web/README.md
apps/web/cypress/fixtures/test-working-batch.json
apps/web/docs/code-style.md
apps/web/docs/environments.md
apps/web/tsconfig.json

Soem of our files were not correctly formatted. I ran "yarn prettier:fix" on the whole codebase.

fix: run prettier over the codebase

---

.github/workflows/web-deploy-dockerhub.yml
.github/workflows/web-e2e-full-ondemand.yml
.github/workflows/web-e2e-hp-ondemand.yml
.github/workflows/web-e2e-ondemand.yml
.github/workflows/web-e2e-prod-ondemand.yml

The Docker job was broken after the monorepo migration.

Chore: fix docker and on-demand e2e jobs

---

.github/workflows/web-deploy-dockerhub.yml
Dockerfile
apps/web/Dockerfile

The yarn.lock file is in the root of the monorepo, so the Dockerfile should also be there.

Chore: fix docker build

---

apps/web/src/features/walletconnect/components/WcProposalForm/CompatibilityWarning.tsx
apps/web/src/services/analytics/events/walletconnect.ts

Fix: remove network selector from WC proposal warning

---

apps/web/src/components/transactions/TxSummary/index.tsx
apps/web/src/components/transactions/TxSummary/styles.module.css

Just a mechanical refactoring of TxSummary to use less inline styles.

Refactor: less css in tx summary

---

apps/web/package.json
apps/web/src/components/tx/SignOrExecuteForm/SignOrExecuteForm.tsx
apps/web/src/features/tx-notes/TxNoteForm.tsx
apps/web/src/features/tx-notes/TxNoteInput.tsx
apps/web/src/features/tx-notes/encodeTxNote.ts
apps/web/src/features/tx-notes/index.tsx
apps/web/src/services/analytics/events/modals.ts

* Fix(Tx notes): fire analytics on tx submit + adjust design (#4771)

Release 1.49.2

---

apps/web/cypress/e2e/pages/create_tx.pages.js
apps/web/cypress/e2e/pages/create_wallet.pages.js
apps/web/cypress/e2e/pages/sidebar.pages.js

This PR introduces updates to improve the test coverage and reliability for functionalities related to bulk transactions, signer address selection, and address verification:
**1. Bulk Transactions Test Update:**
Enhanced the verifyBulkTxHistoryBlock function to confirm the visibility and structure of bulk transaction elements.
**2. Signer Selection Enhancement:**
Improved the selectSignerOnAutocomplete function by adding a wait to ensure the elements are ready for interaction before clicking the desired autocomplete option.
**3. Address Verification Improvement:**
Updated the verifyEtherscanLinkExists function to include a check for the minimum count of Explorer buttons before verifying the sidebar content.

Tests: Update cy tests

---

apps/web/package.json
apps/web/src/features/tx-notes/TxNoteForm.tsx

Fix(Tx notes): hide for 1/X safes (#4785)

Release 1.49.3

---

apps/web/src/components/sidebar/IndexingStatus/index.tsx

Resolves #4784
The indexing status was simply not polled at all. 😅

Fix(Indexing status): poll every minute

---

.github/ISSUE_TEMPLATE/tech-debt.md

A template for technical debt tickets.

Docs: create tech-debt.md

---

.github/ISSUE_TEMPLATE/task.md

For some structure and linking to Notion.

Docs: add a template for tasks

---

apps/web/cypress/e2e/pages/create_tx.pages.js
apps/web/cypress/e2e/pages/swaps.pages.js
apps/web/cypress/e2e/prodhealthcheck/swaps_history_2.cy.js
apps/web/cypress/e2e/regression/swaps_history_2.cy.js
apps/web/cypress/e2e/regression/twaps_history.cy.js

Resolves #
This PR refines tests to address decoding and enhance validations for transaction history. The following changes were made:
- Added timeouts where necessary to better handle test waits 
- Improved validations for token input/output values by adding timeouts and checks for none-zero conditions value conditions
- Updated test descriptions and relevant test data
- Enhanced validations to ensure decoding data is correctly displayed for transactions
- Enabled a previously skipped test in twaps_history.cy.js to verify order details, as the UI bug blocking it has been resolved

Tests: Update Cypress tests

---

apps/mobile/src/tests/mocks.ts
apps/mobile/src/utils/transaction-guards.ts
packages/store/README.md
packages/store/package.json
packages/store/scripts/api-schema/schema.json
packages/store/scripts/fetch-schema.ts
packages/store/src/gateway/AUTO_GENERATED/balances.ts
packages/store/src/gateway/AUTO_GENERATED/owners.ts
packages/store/src/gateway/AUTO_GENERATED/safe-apps.ts
packages/store/src/gateway/AUTO_GENERATED/transactions.ts
packages/store/src/gateway/types.ts

Automate the fetching of the CGW API schema.
The new command to fetch and generate RTK queries is `yarn build`.

Chore: automatically fetch CGW schema

---

apps/web/cypress/e2e/happypath_2/proposers.cy.js

- Added reload action to retrieve added proposer on UI
- Added verification for added proposer by value

Tests: Update proposer tests

---

apps/web/cypress/e2e/pages/create_tx.pages.js
apps/web/cypress/e2e/pages/dashboard.pages.js
apps/web/cypress/e2e/pages/proposers.pages.js
apps/web/cypress/e2e/regression/tx_share_block.cy.js
apps/web/cypress/e2e/smoke/dashboard.cy.js
apps/web/cypress/support/utils/gtag.js
apps/web/src/components/transactions/TxShareLink/TxShareBlock.tsx
yarn.lock

- Added automation tests for tx share block
- Added data-testids for `TxSharedBlock` component
- Minor refactoring in proper/dashboard tests and getEvents() function

Tests: Add share block tests

---

yarn.lock

Chore: Update yarn.lock file

---

.github/workflows/web-e2e-prod-ondemand.yml

- Update prod workflow to run form main branch
- Run the workflow and check the results

Tests: Update branch

---

apps/web/src/hooks/__tests__/useGasPrice.test.ts
apps/web/src/hooks/useGasPrice.ts

Release 1.50.2

---

.github/workflows/web-e2e-prod-ondemand.yml
apps/web/cypress/e2e/pages/create_tx.pages.js
apps/web/cypress/e2e/pages/staking.page.js
apps/web/cypress/e2e/pages/swaps.pages.js
apps/web/cypress/e2e/prodhealthcheck/tx_history.cy.js
apps/web/cypress/e2e/regression/staking_history.cy.js
apps/web/cypress/e2e/regression/tx_history.cy.js
apps/web/cypress/fixtures/txhistory_data_data.json
apps/web/src/components/transactions/TxDetails/Summary/AdvancedTxDetails/ViewToggleButtonGroup.tsx
apps/web/src/components/transactions/TxDetails/Summary/AdvancedTxDetails/index.tsx

- Added tests for advanced details and minor refactoring
- Updated production tests workflow to revert runs to dev branch
- Added tests for advanced details
- Added data-tested where required
- Updated value expectations for staking history tx and swaps history tests
- Added new test data

Tests: Add advanced details tests

---

apps/web/src/components/balances/AssetsTable/index.test.tsx
apps/web/src/components/dashboard/Overview/Overview.tsx
apps/web/src/components/tx/ApprovalEditor/ApprovalEditor.test.tsx
apps/web/src/features/counterfactual/__tests__/utils.test.ts
apps/web/src/features/counterfactual/useCounterfactualBalances.ts
apps/web/src/features/counterfactual/utils.ts
apps/web/src/hooks/__tests__/useLoadBalances.test.ts
apps/web/src/hooks/loadables/useLoadBalances.ts
apps/web/src/hooks/useBalances.ts
apps/web/src/store/balancesSlice.ts

A follow up for #4770. Counterfactual balances weren't correctly loaded unless a wallet was connected.

Fix(Balances): regression after useLoadBalances refactoring

---

apps/web/src/features/organizations/components/OrgsCreationModal/index.tsx

Resolves #4886
Creates the modal component for creating an org.

feat: add org creation modal

---

apps/web/src/features/organizations/components/OrgsCard/index.tsx
apps/web/src/features/organizations/components/OrgsCard/styles.module.css

Part of #4938 
- Creates a new `OrgsCard` component
Compare with the design

Feat(Orgs): Add org card

---

apps/web/cypress/e2e/pages/batches.pages.js
apps/web/cypress/e2e/pages/create_tx.pages.js
apps/web/cypress/e2e/pages/swaps.pages.js
apps/web/cypress/e2e/regression/spending_limits.cy.js
apps/web/cypress/e2e/regression/twaps_2.cy.js
apps/web/cypress/e2e/regression/tx_queue_delete_btn.cy.js
apps/web/cypress/e2e/regression/tx_queue_reject_btn.cy.js
apps/web/cypress/e2e/regression/tx_queue_replace_btn.cy.js
apps/web/cypress/support/commands.js

To increase automation coverage, new tests were added.
- Added new tests for Reject, Replace, Delete tx options
- Fix “Too many requests” error resulting from rate limit
- Minor refactoring

Tests: Add tx tests

---

apps/mobile/src/tests/mocks.ts
apps/web/src/features/organizations/components/OrgsCreationModal/index.tsx
apps/web/src/features/organizations/components/OrgsList/index.tsx
packages/store/scripts/api-schema/schema.json
packages/store/scripts/openapi-config.ts
packages/store/src/gateway/AUTO_GENERATED/balances.ts
packages/store/src/gateway/AUTO_GENERATED/organizations.ts
packages/store/src/gateway/AUTO_GENERATED/transactions.ts
packages/store/src/gateway/AUTO_GENERATED/users.ts

Resolves #4977
- Calls the endpoint to create an org when submitting the org creation form
- Navigates user to the org dashboard
1. Create an org either from the dashboard or from the org list page
2. Observe being navigated to the org dashboard

feat: Create org when submitting the form

---

apps/web/src/features/organizations/components/AddAccounts/index.tsx
packages/store/scripts/api-schema/schema.json
packages/store/scripts/openapi-config.ts
packages/store/src/gateway/AUTO_GENERATED/auth.ts
packages/store/src/gateway/AUTO_GENERATED/organizations.ts
packages/store/src/gateway/AUTO_GENERATED/users.ts

Resolves #5049
- Generates new hooks from the CGW
- Sends a request to add safe accounts to a given org when submitting the form
1. Open an org
2. Add safe accounts
3. Submit the form
4. Observe the request succeeding
5. Observe the add accounts form closing

Feat(Orgs): Send request to CGW when adding safe accounts to an org

---

apps/web/src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
apps/web/src/components/tx/SignOrExecuteForm/SignForm.tsx
apps/web/src/components/tx/SignOrExecuteForm/__tests__/ExecuteForm.test.tsx
apps/web/src/components/tx/SignOrExecuteForm/__tests__/SignForm.test.tsx
apps/web/src/components/tx/SignOrExecuteForm/__tests__/SignOrExecute.test.tsx
apps/web/src/hooks/useValidateTxData.ts
apps/web/src/services/exceptions/ErrorCodes.ts

- checks that safeTxHash matches the txData

feat(web): validate against mitm

---

apps/web/src/features/tx-notes/encodeTxNote.test.ts
apps/web/src/features/tx-notes/encodeTxNote.ts

Add client-side tx note sanitization in addition to the backend sanitizer.

fix(Notes): additional sanitization

---

.github/workflows/web-deploy-production.yml

Use an action as the curl upload was failing.

Chore(ci): fix release artifact upload step

---

.github/workflows/web-deploy-production.yml

Move the upload actions higher in the workflow.

Chore(CI): reorder upload artifact actions

---

.github/workflows/web-deploy-production.yml
apps/web/package.json
apps/web/src/services/security/modules/BlockaidModule/index.ts

* Fix(Blockaid): non_dapp: true (#5129)
* Chore(CI): reorder upload artifact actions (#5132)
* chore(ci): generate artifact attestation (#5133)

Release 1.51.2

---

apps/web/package.json
yarn.lock

Pin higher version of @web3-onboard/coinbase
- Make sure wallet connection + signing + executing with a Coinbase wallet still works

Chore(web): Update @web3-onboard/coinbase

---

apps/web/src/components/common/PageLayout/index.tsx
apps/web/src/components/common/PageLayout/styles.module.css
apps/web/src/components/common/TemporaryDialog/index.tsx

Popup and banner with a security notice.

feat(web): add temporary popup dialog and banner

---

.github/workflows/web-deploy-production.yml
apps/web/package.json
apps/web/src/components/common/PageLayout/index.tsx
apps/web/src/components/common/PageLayout/styles.module.css
apps/web/src/components/common/TemporaryDialog/index.tsx
apps/web/src/services/security/modules/BlockaidModule/index.ts
yarn.lock

* Fix(Blockaid): non_dapp: true (#5129)
* Chore(CI): reorder upload artifact actions (#5132)
* chore(ci): generate artifact attestation (#5133)
* Chore(web): Update @web3-onboard/coinbase (#5131)
* feat(web): add temporary popup dialog and banner (#5134)

Release 1.51.3

---

apps/web/src/components/tx/SignOrExecuteForm/TxChecks.tsx
apps/web/src/components/tx/SignOrExecuteForm/__tests__/__snapshots__/SignOrExecute.test.tsx.snap
apps/web/src/services/analytics/events/modals.ts

This adjusts the the third party hash tool displayed in the interface.

fix(Web): adjust hash tool link

---

apps/web/package.json
apps/web/src/components/tx/SignOrExecuteForm/TxChecks.tsx
apps/web/src/components/tx/SignOrExecuteForm/__tests__/__snapshots__/SignOrExecute.test.tsx.snap
apps/web/src/services/analytics/events/modals.ts

* fix(Web): adjust hash tool link (#5174)

Release 1.51.5

---

apps/web/cypress/e2e/pages/bridge.pages.js
apps/web/cypress/e2e/pages/spending_limits.pages.js
apps/web/cypress/e2e/pages/swaps.pages.js
apps/web/cypress/e2e/pages/walletconnect.page.js
apps/web/cypress/e2e/regression/sidebar_9.cy.js
apps/web/cypress/e2e/regression/walletconnect.cy.js
apps/web/cypress/support/constants.js
apps/web/src/components/common/CookieAndTermBanner/index.tsx

- Add UI bridging tests for multiple views
- Add minor fixes to failing tests
- Add data-testids where required

Tests: Update tests

---

apps/web/cypress/e2e/pages/assets.pages.js
apps/web/cypress/e2e/pages/safeapps.pages.js
apps/web/cypress/e2e/prodhealthcheck/tokens.cy.js
apps/web/cypress/e2e/regression/tokens.cy.js
apps/web/cypress/e2e/safe-apps/browser_permissions.cy.js

- Enable browser permissions tests
- Update balance checkin non-native tokens

Tests: Add safe apps and permissions tests

---

apps/web/src/features/organizations/components/AddAccounts/index.tsx
packages/store/scripts/api-schema/schema.json
packages/store/src/gateway/AUTO_GENERATED/organizations.ts
packages/store/src/gateway/AUTO_GENERATED/transactions.ts

There was a type mismatch between the expected payload in the CGW and the generated types.
Updates the RTK query endpoints for the CGW to the latest version.
- Open the accounts list for an org
- see that the list of accounts is fetched from the CGW

Fix(Orgs): typescript error when fetching accounts list

---

apps/mobile/src/app/(import-accounts)/_layout.tsx
apps/mobile/src/app/(import-accounts)/form.tsx
apps/mobile/src/app/(import-accounts)/signers.tsx
apps/mobile/src/app/import-signers/private-key.tsx
apps/mobile/src/app/signers/index.tsx
apps/mobile/src/components/Identicon/Identicon.test.tsx
apps/mobile/src/components/Identicon/Identicon.tsx
apps/mobile/src/components/SafeInput/SafeInput.tsx
apps/mobile/src/components/SafeListItem/SafeListItem.tsx
apps/mobile/src/components/SafeListItem/theme.ts
apps/mobile/src/components/transactions-list/Card/SignersCard/SignersCard.tsx
apps/mobile/src/features/Assets/components/Navbar/Navbar.tsx
apps/mobile/src/features/ImportPrivateKey/ImportPrivateKey.container.tsx
apps/mobile/src/features/ImportReadOnly/components/AddSignersFormView.tsx
apps/mobile/src/features/ImportReadOnly/components/ImportAccountFormView.tsx
apps/mobile/src/features/Settings/components/IdenticonWithBadge/IdenticonWithBadge.tsx
apps/mobile/src/features/Share/components/ShareView.tsx
apps/mobile/src/features/Signers/Signers.container.tsx
apps/mobile/src/features/Signers/components/SignersList/SignersList.tsx
apps/mobile/src/features/Signers/components/SignersList/SignersListItem.tsx
apps/mobile/src/navigation/hooks/useModalStyle.ts
apps/mobile/src/theme/tamagui.config.ts

- the identicon was rendered as a square and not a circle
- the continue button was off screen
- incorrect horizontal margins in the signers screens.
Resolves #

fix(mobile): multiple UI inconsistencies

---

apps/web/src/markdown/privacy/privacy.md
apps/web/src/markdown/terms/terms.md
apps/web/src/pages/cookie.tsx
apps/web/src/pages/imprint.tsx

Fix(Legal): update CC address

---

apps/web/src/components/transactions/HexEncodedData/__snapshots__/HexEncodedData.test.tsx.snap
apps/web/src/components/transactions/TxDetails/TxData/DecodedData/MethodDetails/index.tsx
apps/web/src/components/tx-flow/common/TxButton.tsx
apps/web/src/components/tx-flow/flows/NftTransfer/ReviewNftBatch.tsx
apps/web/src/components/tx-flow/flows/NftTransfer/SendNftBatch.tsx
apps/web/src/components/tx/ConfirmTxDetails/index.tsx
apps/web/src/components/tx/DecodedTx/index.test.tsx
apps/web/src/components/tx/FieldsGrid/index.tsx
apps/web/src/components/tx/ReviewTransaction/__tests__/__snapshots__/index.test.tsx.snap
apps/web/src/components/tx/SendToBlock/index.tsx
apps/web/src/components/tx/SignOrExecuteForm/__tests__/__snapshots__/SignOrExecute.test.tsx.snap
apps/web/src/components/tx/confirmation-views/BatchTransactions/__snapshots__/BatchTransactions.test.tsx.snap
apps/web/src/services/analytics/events/modals.ts

There were some design inconsistencies on NFT review screen and in Advanced details.
Also I removed an unused component.

Fix(Signing UX): adjust tx data parameter design

---

apps/web/package.json

* Feat(Tx flow): Signing UX improvements (#5285)
* feat(Signing UX): color coded transaction details (#5406)
* Fix(web): remove warning banner

Release 1.54.0

---

apps/mobile/src/components/Badge/theme.ts
apps/mobile/src/components/SafeBottomSheet/SafeBottomSheet.tsx
apps/mobile/src/components/StatusBanners/PendingTransactions/PendingTransactions.test.tsx
apps/mobile/src/components/StatusBanners/PendingTransactions/PendingTransactions.tsx
apps/mobile/src/components/StatusBanners/PendingTransactions/__snapshots__/PendingTransactions.test.tsx.snap
apps/mobile/src/components/transactions-list/Card/SignersCard/SignersCard.tsx
apps/mobile/src/features/Assets/components/Navbar/Navbar.tsx
apps/mobile/src/features/ConfirmTx/components/SignForm/SignForm.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/TokenTransfer/TokenTransfer.tsx
apps/mobile/src/features/ConfirmationsSheet/ConfirmationsSheet.container.tsx
apps/mobile/src/features/PendingTx/components/PendingTxList/PendingTxList.container.tsx
apps/mobile/src/theme/palettes/darkPalette.ts
apps/mobile/src/theme/palettes/lightPalette.ts
apps/mobile/src/theme/tamagui.config.ts

Fix various small UI issues between what was designed against implemented on confirmation screen.
Resolves #
1 - Open wallet
2 - Trigger a transaction
3 - Perform the Pending tx flow.

fix(mobile): Confirmation UI and flow

---

apps/web/src/features/targetedFeatures/constants.ts
apps/web/src/features/targetedFeatures/hooks/__tests__/useIsTargetedFeature.test.ts
apps/web/src/features/targetedFeatures/hooks/useIsTargetedFeature.ts

Clears the TARGETED_FEATURES array and fixes the targeted feature logic for an empty array.

fix: targeted feature logic for empty feature array

---

apps/web/src/components/common/TokenAmountInput/index.tsx

When a user enters a token amount with a large number of decimal places, the form validation fails. As a result, clicking the **MAX** button incorrectly triggers the "Insufficient balance" alert, even when the user should have sufficient funds.  
The `validateAmount` function calculates the total sum of all defined amounts for a given token by converting input strings into numbers. However, for values with many decimal places, JavaScript rounds the number, leading to inaccurate calculations and an incorrect validation outcome.  
Instead of converting input strings to floating-point numbers, this fix ensures that values are transformed into **BigInt** representations without decimals before summing. This approach eliminates rounding errors and ensures accurate balance validation.

fix(Mass payouts): sum calculation for token amounts with large number of decimals

---

.github/workflows/web-tag-release.yml

Add a link to a corresponding IPFS release on top of main release notes.

Chore(web): insert a link to IPFS release in release notes

---

apps/mobile/src/features/ConfirmTx/components/SignTransaction/SignSuccess.tsx

The signing success message needed updating
Sign a tx and observe the updated screen.

fix(mobile): signing success message was wrong

---

apps/web/src/markdown/terms/terms.md
apps/web/src/markdown/terms/version.js

Resolves #5064 
- Updates the terms page

Fix(Orgs): Update terms and conditions

---

apps/mobile/src/services/key-storage/key-storage.service.ts

The android implementation of the device-crypto library diverges from the iOS implementation. On Android, the encrypt function expects a symmetric key, while on iOS it expects an asymmetric key.
Resolves https://github.com/safe-global/wallet-private-tasks/issues/80
Generate symmetric key in keystore
On Android phone, make sure to first enable a PIN/Pattern/biometric, then try to import a key. It should work.

fix(mobile): can’t encrypt key on android

---

.github/workflows/web-e2e-full-ondemand.yml
.github/workflows/web-e2e-hp-ondemand.yml
.github/workflows/web-e2e-prod-ondemand.yml
.github/workflows/web-e2e-smoke.yml

- Use latest runner version in Cypress workflows
- Update time for scheduled runs

Tests: Update test workflows

---

apps/web/src/components/settings/SafeModules/index.tsx

Resolves #5578 
Replaces hardcoded link to Repo with the module docs

fix(web): fix the link to module docs

---

apps/mobile/src/config/constants.ts
apps/mobile/src/features/Settings/components/AppSettings/AppSettings.container.tsx
apps/mobile/src/features/Settings/components/AppSettings/AppSettings.tsx

- fixes the scroll in the Settings page
- the feedback url is now correct
Navigate to app settings, scroll should work fine. Feedback url should point to the google form.

feat(mobile): feedback form points to correct url

---

apps/mobile/app.config.js

we don’t support iPad right now

fix(mobile): disable tablet support

---

apps/web/cypress/e2e/happypath_2/swaps.cy.js
apps/web/cypress/e2e/pages/create_tx.pages.js
apps/web/cypress/e2e/pages/swaps.pages.js
apps/web/cypress/e2e/regression/swaps.cy.js
apps/web/cypress/e2e/regression/swaps_2.cy.js
apps/web/cypress/e2e/regression/tx_share_block.cy.js
apps/web/cypress/fixtures/swaps/quoteresponse1.json
apps/web/cypress/fixtures/swaps/quoteresponse2.json
apps/web/cypress/fixtures/swaps_data.json

- Add a test for share block
- Add mock response for twap/swap tests to increase stability

Tests: Add tests

---

apps/web/src/components/common/SplitMenuButton/index.tsx

A loading state for the split menu button.

Feat(Signing UX): split menu loading state

---

apps/web/src/components/common/TokenAmount/index.tsx
apps/web/src/components/tx/confirmation-views/BatchTransactions/__snapshots__/BatchTransactions.test.tsx.snap

There was some empty space and lint was complaining

fix(web): lint issue

---

.github/workflows/web-deploy-production.yml
apps/web/scripts/github/s3_upload.sh

Testing if the updated s3 upload script from #5633 still works.

Chore(web): fix prod deployment workflow

---

apps/mobile/package.json
apps/mobile/src/features/TxHistory/TxHistory.container.tsx
packages/store/src/gateway/index.ts
packages/store/src/gateway/transactions.ts
yarn.lock

We had some weird bugs in our history. When switching between the safes we were not displaying the correct data. Now RTK handles this for us.
Uses the latest RTK infinite API
Load a safe, scroll down and you should see that all entries are loading. Switch to a different safe - it should display the correct history items.

feat(mobile): Use RTK infinite queries API

---

apps/mobile/src/app/biometrics-opt-in.tsx
apps/mobile/src/app/notifications-opt-in.tsx
apps/mobile/src/components/OptIn/OptIn.tsx
apps/mobile/src/navigation/hooks/useModalStyle.ts
apps/mobile/src/theme/tokens.ts

fix(mobile): notification screen proper alignment

---

apps/web/package.json

* Fix(Notifications): add a workaround firebase sw file

Release 1.56.2

---

apps/web/src/services/siwe/utils/index.ts

Renames signing message in SiWE
1. Open `/welcome/spaces`
2. Sign in with your wallet
3. Observe the signing message saying safe infrastructure

Fix(Spaces): Rename signing message

---

apps/mobile/src/components/Camera/QrCamera.tsx
apps/mobile/src/features/ImportReadOnly/ScanQrAccount.container.tsx
apps/mobile/src/features/ImportReadOnly/components/ScanQrAccountView.tsx

This PR removes some unused code from the camera flow that is not used.

Chore(mobile): remove unused code from camera flow

---

apps/web/package.json
apps/web/src/components/transactions/TxDetails/index.tsx
apps/web/src/components/transactions/TxSigners/index.tsx
yarn.lock

Resolves #5680
Update the SDK and use the new property.

Refactor(Proposers): use proposedByDelegate

---

apps/web/src/features/swap/components/RedirectToSwapApp/index.tsx

Add URL params to the Swap app fallback so that a token can be preselected.

Feat(Swaps): swap parameters for KyberSwap

---

apps/web/src/components/tx-flow/flows/TokenTransfer/RecipientRow/index.tsx

Resolves #5685 
- Clears up the dependencies avoiding triggering fields that were removed.
- Create a transfer with multiple recipients / tokens / amounts
- Remove the first transfer
- Witness that the total used amount is considered correctly and that the next button works.

fix(web): simplify multi token transfer dependencies

---

apps/web/src/components/tx-flow/flows/RemoveOwner/SetThreshold.tsx
apps/web/src/components/tx-flow/flows/RemoveOwner/index.tsx

Refactor(Tx flow): migrate RemoveOwner flow

---

apps/web/src/components/tx-flow/TxFlow.tsx
apps/web/src/components/tx-flow/TxFlowProvider.tsx
apps/web/src/components/tx-flow/flows/MigrateSafeL2/MigrateSafeL2Review.tsx
apps/web/src/components/tx-flow/flows/MigrateSafeL2/index.tsx
apps/web/src/components/tx-flow/flows/NewSpendingLimit/CreateSpendingLimit.tsx
apps/web/src/components/tx-flow/flows/NewSpendingLimit/ReviewSpendingLimit.tsx
apps/web/src/components/tx-flow/flows/NewSpendingLimit/index.tsx
apps/web/src/components/tx-flow/flows/NftTransfer/ReviewNftBatch.tsx
apps/web/src/components/tx-flow/flows/NftTransfer/SendNftBatch.tsx
apps/web/src/components/tx-flow/flows/NftTransfer/index.tsx
apps/web/src/components/tx-flow/flows/RejectTx/RejectTx.tsx
apps/web/src/components/tx-flow/flows/RejectTx/index.tsx

Migrates multiple flows to the new TxFlow logic:
* RejectTxFlow #5809 
* NftTransferFlow #5807 
* NewSpendingLimitFlow #5806 
* MigrateSafeL2Flow #5821

refactor(TxFlow): migrate RejectTx, NftTransfer, NewSpendingLimit + MigrateSafeL2 flows

---

apps/mobile/src/components/SelectSigner/SelectSigner.tsx
apps/mobile/src/components/SelectSigner/index.ts
apps/mobile/src/features/ConfirmTx/ConfirmTx.container.tsx
apps/mobile/src/features/ConfirmTx/components/CanNotSign/CanNotSign.tsx
apps/mobile/src/features/ConfirmTx/components/CanNotSign/index.ts
apps/mobile/src/features/ConfirmTx/components/ConfirmTxForm/ConfirmTxForm.tsx
apps/mobile/src/features/ConfirmTx/components/SignForm/SignForm.tsx
apps/mobile/src/features/ConfirmTx/hooks/useTxSigner/useTxSigner.ts

It fixes signing issues in the confirm transaction flow.
Resolves https://github.com/safe-global/wallet-private-tasks/issues/15

fix(mobile): improvements to the ready to execute view

---

apps/web/src/components/tx-flow/flows/AddOwner/ReviewOwner.tsx
apps/web/src/components/tx-flow/flows/AddOwner/index.tsx
apps/web/src/components/tx-flow/flows/ChangeThreshold/ReviewChangeThreshold.tsx
apps/web/src/components/tx-flow/flows/ChangeThreshold/index.tsx

Migrate AddOwner and ChangeThreshold to use ReviewTransactionV2 and pass down children.

fix(TxFlow): use ReviewTransactionV2 + pass down children

---

apps/mobile/src/platform/__tests__/fetch.test.ts
apps/mobile/src/platform/fetch.ts

The signers list on Android was empty, where it was properly populated on ios. After debugging for a lot of time it turned out that this is caused by the fetch override we had. 
We were creating a new headers object using:
```
options.headers = {
...options.headers,
// your commented out headers
}
```
This was effectively creating a plain JavaScript object instead of a proper Headers object, which can cause issues on Android. 
The Headers class maintains internal state and has methods like set, append, and get that handle the complexities of HTTP headers correctly, including case-insensitivity.
It seems that because of that the eth_getBalance call was sending some "magic headers" and when we were creating a custom object this was causing havoc. 
Resolves …

fix(mobile): signer select list empty on android

---

apps/web/src/components/tx-flow/flows/RemoveRecovery/RemoveRecoveryFlowOverview.tsx
apps/web/src/components/tx-flow/flows/RemoveRecovery/RemoveRecoveryFlowReview.tsx
apps/web/src/components/tx-flow/flows/RemoveRecovery/index.tsx

Resolves #5813 
Migrates the RemoveRecovery flow to use the new TxFlow logic

refactor(RemoveRecovery): migrate flow to use new TxFlow logic

---

apps/web/src/components/tx-flow/flows/UpsertRecovery/UpsertRecoveryFlowIntro.tsx
apps/web/src/components/tx-flow/flows/UpsertRecovery/UpsertRecoveryFlowReview.tsx
apps/web/src/components/tx-flow/flows/UpsertRecovery/UpsertRecoveryFlowSettings.tsx
apps/web/src/components/tx-flow/flows/UpsertRecovery/index.tsx

Resolves #5819 
- Migrates `UpsertRecoveryFlow` to new `TxFlow`
- Add or Update the recovery settings of a Safe.

Refactor(web): upsert recovery flow

---

apps/web/src/components/common/PaperViewToggle/index.tsx
apps/web/src/components/tx/ReviewTransaction/__tests__/__snapshots__/index.test.tsx.snap
apps/web/src/components/tx/ReviewTransactionV2/__tests__/__snapshots__/ReviewTransactionContent.test.tsx.snap
apps/web/src/components/tx/ReviewTransactionV2/__tests__/__snapshots__/index.test.tsx.snap
apps/web/src/components/tx/SignOrExecuteForm/__tests__/__snapshots__/SignOrExecute.test.tsx.snap

The initial height of the receipt was set to 0.

Fix(Receipt): initial height

---

apps/web/package.json
apps/web/src/features/earn/components/VaultDepositConfirmation/index.tsx
apps/web/src/features/earn/components/VaultRedeemConfirmation/index.tsx

Backmerge `main` -> `dev`

---

apps/web/src/components/tx/ReviewTransaction/__tests__/__snapshots__/index.test.tsx.snap

Two tests were failing after backmerging main into dev

Fix(Tests): Update ReviewTransaction snapshot

---

apps/mobile/src/store/__tests__/activeSafeSlice.test.ts

adds unit tests for activeSafeSlice
---

tests(mobile): add unit tests for activeSafeSlice

---

apps/mobile/src/store/__tests__/addressBookSlice.test.ts
apps/mobile/src/store/addressBookSlice.ts

adds tests for addressBookSlice
---

tests(mobile): add tests for addressBookSlice

---

apps/mobile/docs/push-notifications.md
expo-plugins/notification-service-ios/dist/ios-notification-service-files/NotificationService.swift
expo-plugins/notification-service-ios/dist/ios-notification-service-files/NotificationServiceExtension-Info.plist
expo-plugins/notification-service-ios/dist/ios-notification-service-files/Utils/BoolString.swift
expo-plugins/notification-service-ios/dist/ios-notification-service-files/Utils/CharacterSet+Hex.swift
expo-plugins/notification-service-ios/dist/ios-notification-service-files/Utils/ConfigurationKey.swift
expo-plugins/notification-service-ios/dist/ios-notification-service-files/Utils/Data+MultisigExtension.swift
expo-plugins/notification-service-ios/dist/ios-notification-service-files/Utils/DataString.swift
expo-plugins/notification-service-ios/dist/ios-notification-service-files/Utils/UInt256.swift
expo-plugins/notification-service-ios/dist/ios-notification-service-files/Utils/UInt256String.swift
expo-plugins/notification-service-ios/dist/plugin/config.d.ts
expo-plugins/notification-service-ios/dist/plugin/config.js
expo-plugins/notification-service-ios/dist/plugin/ios.d.ts
expo-plugins/notification-service-ios/dist/plugin/ios.js
expo-plugins/notification-service-ios/dist/plugin/types.d.ts
expo-plugins/notification-service-ios/dist/plugin/types.js
expo-plugins/notification-service-ios/dist/plugin/utils.d.ts
expo-plugins/notification-service-ios/dist/plugin/utils.js
expo-plugins/notification-service-ios/dist/plugin/withNotifee.d.ts
expo-plugins/notification-service-ios/dist/plugin/withNotifee.js

docs(mobile): add push notification docs

---

.cursor/rules/safe-monorepo.mdc

Cursor ignored the wish to create pure functions with the const syntax. With the updated prompt it seems to behave better.
---

chore: small update to cursor rules

---

apps/mobile/package.json
apps/web/package.json
yarn.lock

Push @safe-global/protocol-kit to add compatibility for PEAQ

chore: bump @safe-global/protocol-kit to latest version

---

apps/mobile/src/features/DataImport/HelpImport.container.tsx
packages/utils/src/config/constants.ts

Update the link to the import data help article
Resolves https://linear.app/safe-global/issue/MOB-77/help-desk-article-for-bulk-import
---

fix(mobile): link to correct help article on import

---

packages/utils/src/features/swap/helpers/__tests__/utils.test.ts
packages/utils/src/features/swap/helpers/fee.ts

We had apparent type safety, but it was a lie. 
fullAppData -> metadata -> partnerFee all of those can be undefined. Not handling undefined threw an error and we displayed "error decoding"
Now we properly check for undefined and return 0 as fee for those transactions.
Open a safe with old cowswap tx - they should render now.
---

fix: cowswap fees were not shown for old txs

---

apps/mobile/src/app/_layout.tsx
apps/mobile/src/app/review-and-confirm.tsx
apps/mobile/src/features/ConfirmTx/components/ReviewAndConfirm/ReviewAndConfirmContainer.tsx
apps/mobile/src/features/ConfirmTx/components/ReviewAndConfirm/ReviewAndConfirmView.tsx
apps/mobile/src/features/ConfirmTx/components/ReviewAndConfirm/ReviewFooter.tsx
apps/mobile/src/features/ConfirmTx/components/ReviewAndConfirm/ReviewHeader.tsx
apps/mobile/src/features/ConfirmTx/components/ReviewAndConfirm/index.ts
apps/mobile/src/features/ConfirmTx/components/ReviewAndConfirm/tabs/DataTab.tsx
apps/mobile/src/features/ConfirmTx/components/ReviewAndConfirm/tabs/JSONTab.tsx
apps/mobile/src/features/ConfirmTx/components/SignForm/SignForm.tsx
apps/mobile/src/features/ConfirmTx/components/SignTransaction/SignSuccess.tsx

Resolves https://linear.app/safe-global/issue/COR-158/
Implements a new "Review and Confirm" screen in the mobile app that allows users to thoroughly review transaction details before signing, matching the web app's functionality and improving the transaction confirmation flow.
New Review and Confirm Screen
- Route: /review-and-confirm with proper header configuration
- Tab Structure: Collapsible tab view with Data and JSON tabs for comprehensive transaction review
- Header: Instructional text guiding users through the review process
- Footer: Fixed footer with signer selection and "Confirm transaction" button
Updated Transaction Flow
- Modified SignForm: Changed "Confirm and sign" button to "Continue" and routes to review screen
- Preserved Security: Maintains existing biometrics and …

feat(mobile): add receipt screens

---

apps/web/src/components/common/CookieAndTermBanner/index.tsx

Changes text of Cookie Banner to be more accurate and consistent.
---

Feat(Analytics) change text of cookie banner

---

apps/web/src/features/swap/helpers/__tests__/fee.test.ts
apps/web/src/features/swap/helpers/fee.ts
apps/web/src/features/swap/index.tsx

Changes Swap Fee on Base as an experimental feature for growth.
---

Feat(Web) Edit Swap Fee on Base

---

apps/mobile/app.config.js

Bumps mobile app version to 1.0.2 for iOS store submission

chore: Bump mobile version to 1.0.2

---

apps/web/src/features/multichain/components/UnsupportedMastercopyWarning/UnsupportedMasterCopyWarning.tsx

It solves Issue: https://github.com/safe-global/safe-wallet-monorepo/issues/5875
"underline" css was implement as part of style.modules.css for error message buttons. added style={{ textDecoration: 'none' }} to overwrite the css for this button. fix can be revisited in case standard styling without "underline" needs to be implemented for all error message buttons
recreate 1.3.0L1 safe on L2 network
check base contract warning
---
Devanshu Wadhwani

fix(web): remove underline from migrate button in banner

---

apps/web/src/features/positions/components/PositionsEmpty/__tests__/index.test.tsx
apps/web/src/features/positions/components/PositionsEmpty/index.tsx
apps/web/src/features/positions/components/PositionsWidget/index.tsx
apps/web/src/features/positions/index.tsx

Adds tracking to EmptyPositions Widget.
---

feat(analytics): Add tracking event to empty positions widget

---

apps/web/scripts/release-notes.sh

Add a mobile category in the release notes script.

Chore(web): add a mobile category in the release notes script

---

packages/store/scripts/api-schema/schema.json

There was a git conflict which I resolved unskillfully 😅

Fix: rm leftover git merge tags

---

apps/web/src/components/transactions/TxSigners/index.tsx

Resolves the ens address at the transaction screen.
---

feat(ens): enable ENS resolution for transaction addresses

---

apps/web/src/components/sidebar/SidebarNavigation/index.tsx
apps/web/src/components/tx-flow/common/TxButton.tsx
apps/web/src/features/swap/components/SwapButton/index.tsx
apps/web/src/services/analytics/__tests__/ga-mixpanel-mapping.test.ts
apps/web/src/services/analytics/__tests__/mixpanel-events.test.ts
apps/web/src/services/analytics/events/__tests__/swaps.test.ts
apps/web/src/services/analytics/events/swaps.ts
apps/web/src/services/analytics/ga-mixpanel-mapping.ts
apps/web/src/services/analytics/mixpanel-events.ts

Resolves https://linear.app/safe-global/issue/GRO-14/add-native-swap-viewed-event
Add Swap Viewed event.
---

Feature(Analytics): Add Native Swap Viewed Event

---

apps/web/cypress/e2e/pages/assets.pages.js
apps/web/cypress/e2e/prodhealthcheck/tokens.cy.js
apps/web/cypress/e2e/regression/assets.cy.js
apps/web/cypress/e2e/regression/tokens.cy.js

Resolves https://linear.app/safe-global/issue/GRO-66/improve-e2e-tests
Resolves 3 of 4 failing token e2e tests.
Adds minor refactoring to test files.
---

fix(tests): token e2e tests

---

apps/web/cypress/e2e/happypath_2/multichain_create_safe.cy.js
apps/web/cypress/e2e/pages/create_wallet.pages.js
apps/web/cypress/e2e/regression/batch_tx.cy.js
apps/web/cypress/e2e/regression/create_safe_simple.cy.js
apps/web/cypress/e2e/regression/dashboard.cy.js
apps/web/src/components/dashboard/PendingTxs/PendingTxsList.tsx

Resolves [QA-29](https://linear.app/safe-global/issue/QA-29/e2e-tests-stabilisation)
add small fixes/updates to the failing e2e tests
---

Tests(web): small fixes for e2e tests
