src/components/tx-flow/flows/ChangeThreshold/ReviewChangeThreshold.tsx
src/components/tx-flow/flows/ChangeThreshold/context.tsx
src/components/tx/confirmation-views/ChangeThreshold/ChangeThreshold.stories.tsx
src/components/tx/confirmation-views/ChangeThreshold/ChangeThreshold.test.tsx
src/components/tx/confirmation-views/ChangeThreshold/__snapshots__/ChangeThreshold.test.tsx.snap
src/components/tx/confirmation-views/ChangeThreshold/index.tsx
src/components/tx/confirmation-views/index.tsx

This PR is part of the unify confirmations screen refactor in the transactions flow (https://github.com/safe-global/safe-wallet-web/pull/4177). 
In this PR we're moving the ChangeThresholdReview component to be inside the `tx/confirmation-view` folder.
1) Open a 1/x safe wallet
2) Try to change the threshold of it
3) The change threshold confirmation screen should look the same as production app.

Refactor: Unify changeThresholdReview screen

---

src/features/swap/helpers/data/stablecoins.ts

https://www.coingecko.com/en/coins/sky-dollar
DAI has rebranded to SKY and that new token is most probably going to be used quite a lot in the future. We need to have the token address in the stablecoints array otherwise the swap widget will apply the wrong fee.

Feat(swaps): add usds stable coin

---

src/services/analytics/tx-tracking.ts
src/utils/transaction-guards.ts

With the changes in this pr we will be able to distinguish between deposit, exit and withdraw tx initiated through the stake widget.
This PR introduces logic to differentiate between various staking transaction types, such as deposit, exit, and withdraw, by adding the isAnyStakingTxInfo utility. The getTransactionTrackingType function is updated to recognize these transaction types, ensuring that the correct transaction type is logged when a staking-related transaction is processed.
Submit deposit, exit and withdraw txs. In the browser terminal you should see the GTM tag sent.

Analytics(stake): add tx type tracking

---

src/features/stake/components/StakingConfirmationTx/Withdraw.tsx

Display correct value to withdraw. The Kiln API was not returning the correct value for the amount the user was going to withdraw. They've correct this and the fix was implemented on CGW, so had to update our UI as well.
Resolves #
The rewards prop was removed from the cgw endpoint. `value` now returns the correct net(minus any fees) reward
Withdraw a reward(claim) -> you should see the same value as displayed in the kiln widget.

fix(Staking): display correct value for withdrawal

---

docs/update-terms.md

Since we changed how we update the terms & Conditions file I thought it would be good to also have it written somewhere how to update them from now on.

docs: how to update terms.md

---

src/features/multichain/components/SignerSetupWarning/InconsistentSignerSetupWarning.tsx

Fixes issue that caused the Safe overviews to be fetched on every render on the dashboard.
- Open a multichain Safe and go to the dashboard
- Observe only one request to the safe overview endpoint

fix(Multichain): memoize data for InconsistentSignerSetupWarning

---

src/features/multichain/components/CreateSafeOnNewChain/index.tsx

Resolves [SW-173](https://www.notion.so/safe-global/Close-networks-selector-in-the-header-after-choosing-network-8300245b7058465ea6de4a9e9171f094)
- Adds a `isSubmitDisabled` state
1. Open a replayable safe
2. Add another network
3. Observe the submit button becoming disabled when clicked
4. Observe the submit button becoming enabled when finished

[Multichain] fix: Disable submit button while replaying safe [SW-173]

---

src/components/common/NetworkSelector/NetworkMultiSelector.tsx

In the network multi select for safe creation, if the selected network does not have the multichain feature enabled, then the network is disabled after selection, so you cannot deselect it.
If the feature is not enabled on the currently selected network, all other networks are disabled, but the currently selected one is not.
- In the safe creation flow, use the network selector to select a chain without multichain enabled (eg. Mantle, Holesky on dev)
- The selected option should not become disabled.
Before:
After:

fix(Multichain): do not disable currently selected network in the network selector

---

src/features/multichain/hooks/__tests__/useCompatibleNetworks.test.ts
src/features/multichain/hooks/__tests__/useSafeCreationData.test.ts
src/features/multichain/hooks/useCompatibleNetworks.ts
src/features/multichain/hooks/useSafeCreationData.ts
src/services/contracts/deployments.ts

Disables adding networks for:
- Safes using reimbursement on creation
- Safes with unknown fallback handler
- Try to add a network to a Safe that used reimbursements (`payment > 0`)
- Try to add a network to a Safe with a custom fallback handler

fix(Multichain): add more unsupported Safe cases

---

src/components/new-safe/create/logic/index.ts
src/components/new-safe/create/steps/ReviewStep/index.tsx
src/features/counterfactual/ActivateAccountFlow.tsx
src/features/counterfactual/utils.ts

Resolves SW-199
- Passes `options` to `createNewSafe`
- Adds the `saltNonce` to `newSafeProps` to avoid spreading which causes a lot of requests
- Removes unused code

[Multichain] fix: Pass options for safe creation [SW-199]

---

src/components/common/NameInput/index.tsx

When typing some letters in the name input within the replay safe modal, the focus is moved away from the input.
Related: https://github.com/mui/material-ui/issues/19116
Stops keyboard events in the text input.
- Open a multichain safe.
- In the network selector, open the modal to replay the safe on another chain
- In the text input for setting the name, highlight the existing text and start typing. No matter what letter you start with, it should type as expected. (problematic letters were s, e, and p)

Fix(Multichain): Keep focus within text input when typing name in replay modal [SW-205]

---

src/components/welcome/MyAccounts/useSafeOverviews.ts

Does not fetch safe overview for empty list of Safes.
Open a non-multichain Safe's dashboard. There should be no attempt to load the Safe overview

fix(Multichain): overview of non multichain Safe

---

src/components/welcome/MyAccounts/PaginatedSafeList.tsx

Resolves [SW-223](https://www.notion.so/safe-global/Error-Minified-React-error-418-on-My-accounts-page-reloading-10b8180fe5738049b266f92d66dead3a)
- Changes a Typography element to be a div instead of a p
1. Go to the My Accounts page
2. Reload the page
3. Observe no error showing in the console

[Multichain] fix: Minified react error because of DOM nesting [SW-223]

---

src/components/common/NetworkSelector/NetworkMultiSelector.tsx
src/components/new-safe/create/steps/SetNameStep/index.tsx

Resolves: https://www.notion.so/safe-global/Default-selected-network-for-safe-creation-is-confusing-after-hiding-Network-switcher-10a8180fe57380869a80eca157865b6c?pvs=4
- Uses wallet network as default for safe creation multiselect input.
- Syncs wallet network and current network to prevent a network switch prompt in the wallet info modal
- When beginning the safe creation flow, the default network shown in the multiselect input should always match the connected wallet network.

Fix(Multichain): use wallet network as default for safe creation [SW-215]

---

src/features/multichain/components/CreateSafeOnNewChain/index.tsx

Resolves [SW-173](https://www.notion.so/safe-global/Close-networks-selector-in-the-header-after-choosing-network-8300245b7058465ea6de4a9e9171f094)
- Adds a loading spinner to the new network form
- Removes double divider
1. Open a safe
2. Press add another network and choose a network
3. Press submit and observe the button being disabled and a loading spinner appearing

[Multichain] fix: Add loading spinner to add new network form when submitting [SW-173]

---

src/components/address-book/EntryDialog/index.tsx
src/components/address-book/ImportDialog/index.tsx
src/components/new-safe/create/logic/address-book.ts
src/components/new-safe/load/steps/SafeReviewStep/index.tsx
src/components/settings/owner/EditOwnerDialog/index.tsx
src/components/sidebar/SafeListContextMenu/index.tsx
src/components/sidebar/SafeListRemoveDialog/index.tsx
src/components/tx-flow/flows/AddOwner/ReviewOwner.tsx
src/components/welcome/MyAccounts/AccountItem.tsx
src/components/welcome/MyAccounts/SubAccountItem.tsx
src/features/counterfactual/utils.ts
src/features/multichain/components/CreateSafeOnNewChain/index.tsx
src/store/__tests__/addressBookSlice.test.ts
src/store/addressBookSlice.ts

Resolves:
- [SW-187](https://www.notion.so/safe-global/Display-multichain-safe-name-in-sidebar-depending-on-visible-safes-only-1048180fe57380b4a3fedca4a9aa4e24?pvs=4)
- [SW-221](https://www.notion.so/safe-global/Wrong-chain-is-displayed-in-rename-safe-window-af620157d9bb455480c455c50b6a3bc5?pvs=4)
- [SW-211](https://www.notion.so/safe-global/Disable-rename-option-for-individual-safes-in-the-safe-list-10a8180fe5738063b029da12d8dd57ef?pvs=4)
- Removes the ability to rename multichain safes from the safe list
- Removes the chain indicator from the modal when renaming a multichain safe
- Removes the name input from the modal when replaying a safe on a new network.
1.
- Replay a safe from the sidebar or the network menu in the navbar.
- You should not be able to choose the name of the safe. …

Feat(Multichain): simplify multichain naming options [SW-187] [SW-221] [SW-211]

---

src/components/new-safe/create/steps/ReviewStep/index.tsx
src/features/counterfactual/CounterfactualSuccessScreen.tsx

Resolves [SW-224](https://www.notion.so/safe-global/Network-logo-is-missing-after-safe-activation-10b8180fe57380daa4a9efb8c81f39da)
- Falls back to the current chain for the safe creation success screen in case there are none available through the dispatched event
- Awaits safe creation before showing the success screen
1. Go to safe creation and submit a new counterfactual safe
2. Observe the success screen appears only after navigating to the dashboard
3. Reload the page and activate the safe
4. Observe the current network logo is visible in the success screen

[Multichain] fix: Display current chain network logo in success screen as a fallback [SW-224]

---

src/components/sidebar/SidebarNavigation/index.tsx

Tracks a click on the stake route.
I had to refactor the code a bit to make it easier to add those custom track events.
- Defined a new object customSidebarEvents to handle events and labels for both swap and stake routes.
- Refactored the handleNavigationClick function to dynamically track events for both swap and stake routes by using the new customSidebarEvents mapping.
1. Navigate to the sidebar and click on the swap and stake routes.
2. Verify that the correct events (OPEN_SWAPS for swap, OPEN_STAKE for stake) are tracked and logged with appropriate labels.

fix: click in sidebar was not triggering GTM event

---

src/components/new-safe/create/steps/ReviewStep/index.tsx
src/features/counterfactual/utils.ts
src/features/multichain/components/CreateSafeOnNewChain/index.tsx

Resolves [SW-227](https://www.notion.so/safe-global/Sometimes-the-user-is-not-navigated-to-the-dashboard-after-safe-creation-10c8180fe57380f1afd7c3bdd6e7b930)
- Sets `payMethod` instead of hard-coding it to `PayLater` so that the `useUndeployedSafe` works again
1. Create a safe and pay now
2. Observe being navigated to the dashboard after success

[Multichain] fix: Redirect user to dashboard after safe creation [SW-227]

---

src/components/new-safe/create/steps/ReviewStep/index.tsx
src/features/counterfactual/PayNowPayLater.tsx

Resolves [SW-225](https://www.notion.so/safe-global/Safe-creation-Update-review-safe-creation-screen-according-to-the-design-10b8180fe5738051b666d3385e418d7c)
- Changes the title for the info block to `Before we continue...`
- Changes the info  bullet points for multichain safe creation
- Adds text to the blue info alert.
- Updates create button text

Feat(Multichain): update text on safe creation review step [SW-225]

---

src/features/multichain/hooks/__tests__/useSafeCreationData.test.ts
src/features/multichain/hooks/useSafeCreationData.ts

The transaction service returns "0x" as `setupData` for some Safes in case of indexing issues.
Shows a custom error in case the `setupData` is `0x` instead of running into an ethers error.
- Use impersonator to impersonate an owner of this Safe: `bnb:0xEAce5e6aC77210af7B26f315925DF83A3f8477c0`
- Try to add a new network in the sidebar

fix(Multichain): empty setup data

---

src/components/settings/PushNotifications/hooks/useNotificationRegistrations.ts

Resolves #4253 
- https://github.com/safe-global/safe-gateway-typescript-sdk/pull/189 changed the response from being undefined to be an empty object so we check for `isEmpty` instead of `null`. 
1. Open a Safe
2. Go to Notification settings
3. Turn on notifications
4. Sign the message
5. Observe the Toggle turns on

fix: Push notifications toggle

---

package.json
src/components/common/Table/DataRow.tsx
src/components/transactions/HexEncodedData/__snapshots__/HexEncodedData.test.tsx.snap
src/components/transactions/TxDetails/TxData/index.tsx
src/components/tx/FieldsGrid/index.tsx
src/features/stake/components/StakingConfirmationTx/Deposit.tsx
src/features/stake/components/StakingConfirmationTx/Exit.tsx
src/features/stake/components/StakingStatus/index.tsx
src/features/stake/components/StakingTxDepositInfo/index.tsx
src/features/stake/components/StakingTxExitDetails/index.tsx
src/features/stake/components/StakingTxExitInfo/index.tsx
src/features/stake/components/StakingTxWithdrawInfo/index.tsx
src/features/stake/constants.ts
src/utils/formatters.ts
yarn.lock

- Incorrect Withdrawal Request Status
- Mismatch in Deposit Validator Status 
- Incorrect Claim Transaction Value in History
- Time Formatting Errors: Updated time formatting functions to correctly handle milliseconds, as the gateway now returns time in milliseconds instead of seconds.
- Validator Exit Details Enhancement: Improved the display of validator exit information by showing validator amounts and adding links to beacon chain explorers for better user visibility.
- Status Display Corrections:
Updated the StakingStatus component to correctly map staking statuses to their corresponding display texts and icons.
Modified status labels in the Deposit and Exit components to accurately reflect the validator’s status.
- Time Formatting Updates:
Changed time formatting functions from …

Fix(staking): display stake statuses & exit & claim "values" 

---

src/components/settings/TransactionGuards/index.tsx

Resolves #4256 
- Adds the `hasExplorer` flag to transaction guards
1. Open a safe with a transaction guard
2. Navigate to the settings page
3. Observe a block explorer button

fix: Show block explorer link for transaction guards

---

.github/workflows/unit-tests.yml

Checking if we can downgrade the contents permission.

Chore: contents read permission for unit tests

---

src/features/stake/components/StakingConfirmationTx/Deposit.tsx

The displayed fee was wrong.
the fee is returned by the API in decimal format, so we have to multiply by 100 to get the percentage
Make a deposit and check that the values in the widget match the values in the deocding

fix(staking): fee displayed in wrong format [SW-242]

---

src/components/common/EthHashInfo/SrcEthHashInfo/index.tsx
src/components/common/EthHashInfo/SrcEthHashInfo/styles.module.css

The spacing inside EthHashInfo was inconsistent.
Before:
After:

Fix: icon spacing in EthHashInfo

---

package.json
src/components/new-safe/create/logic/index.test.ts
src/components/new-safe/create/logic/index.ts
src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx
src/config/constants.ts
src/features/counterfactual/ActivateAccountFlow.tsx
src/utils/__tests__/transactions.test.ts
src/utils/transaction-guards.ts
src/utils/transactions.ts
yarn.lock

Resolves: https://www.notion.so/safe-global/Use-officially-deployed-lib-contracts-ee4ff0091ae946799c37dde88531a070
- Replaces hardcoded temporary contract addresses with the proper addresses from `safe-deployments`
- Ensure safe creation works as before.
- Ensure migration of invalid mastercopy safes works as before.
- It should work on all the chains where the new contracts are deployed.
- Creation and migration transactions should not be flagged by blockaid.

Feat(Multichain): use contract addresses from safe-deployments [SW-169]

---

src/components/transactions/TxDetails/Summary/index.tsx
src/components/tx/DecodedTx/index.tsx

when you had a queued TX and you tried to execute it the "call method on contract" was shown twice.
Resolves #
DecodedTx was rendering a decodedData block, which was also rendered by the Summary component.
Right now I’m hiding the decodedData block in the summary based on a prop that is passed by the parent component.
This will be refactored and tested over here:
https://github.com/safe-global/safe-wallet-web/issues/4091
Create a new tx, sign it. Then go in the queue and try to execute it. Now the "call x method on y contract" should be shown just once.

fix: duplicated advanced data

---

src/components/transactions/HexEncodedData/__snapshots__/HexEncodedData.test.tsx.snap
src/components/transactions/TxDetails/Summary/index.tsx
src/components/tx/DecodedTx/index.tsx
src/components/tx/FieldsGrid/index.tsx

Resolves #
https://safe-wallet-web.dev.5afe.dev/transactions/tx?safe=eth:0x2F41E38fcACF402d2abcf567D924e138BE963bDF&id=multisig_0x2F41E38fcACF402d2abcf567D924e138BE963bDF_0x0390584d687540241abe1529e8e50c44f6ec0efe8b897dac8d0cdebfbe669d4b
The content inside of the label was continuous and since we were only forcing min-width it was spanning as much as possible. I opted for "width" instead. On smaller devices we do just min-width this way the column can stretch to the max available space
before
https://safe-wallet-web.dev.5afe.dev/transactions/tx?safe=eth:0x2F41E38fcACF402d2abcf567D924e138BE963bDF&id=multisig_0x2F41E38fcACF402d2abcf567D924e138BE963bDF_0x0390584d687540241abe1529e8e50c44f6ec0efe8b897dac8d0cdebfbe669d4b
after:
https://fix_too_wide_label--walletweb.review.5afe.dev/transactions/t …

Fix: too wide label

---

src/components/common/NetworkSelector/index.tsx
src/store/__tests__/safeOverviews.test.ts
src/store/api/gateway/safeOverviews.ts

We use `""` as fallback value for `useSafeAddress`. This caused empty requests to be triggered for the safe overview endpoint.
This fixes it by checking the safeAddress parameter before loading the safe overviews.
- Observe no more empty requests while the safe information is loading

Fix(Multichain): ignore empty safe address when loading safeOverviews

---

src/components/welcome/MyAccounts/SubAccountItem.tsx
src/components/welcome/MyAccounts/styles.module.css

Part of SW-244
- Fixes the balance alignment of sub items in the safe list
1. Open the sidebar or safe list
2. Expand a multichain safe
3. Observe the balances are aligned to the right
Before:
After:

[Multichain] fix: Adjust balance alignment in safe list [SW-244]

---

src/components/transactions/TxDetails/TxData/MigrationToL2TxData/index.tsx

Fixes the decoding of transactions that migrate from L1 to L2.
- Open the tx history of a Safe that was migrated from L1 to L2 and check the tx details of the migration tx.

Fix: multichain decode migration

---

src/components/common/NetworkSelector/index.tsx

Explains why no network can be added to a Safe when trying to add a new network from the Network selector.
- Open a Safe that can not add another network (e.g. 1.1.1 Safe)
- Open the network selector
- Check the tooltip of the info icon

Feat(Multichain): explain impossible network addition

---

src/components/tx-flow/flows/ExecuteBatch/ReviewBatch.tsx
src/services/tx/tx-sender/dispatch.ts

Resolves [RC issue](https://github.com/safe-global/safe-wallet-web/pull/4290#issuecomment-2387667536)
Fixes a regression introduced in #4158 
- Sets `nonce` when emitting tx events from the batch execution
1. Queue and sign at least 2 transactions
2. Bulk execute them
3. Observe the Execute button changing to a processing state

fix: Set pending state for batched transactions

---

src/hooks/__tests__/useSafeNotifications.test.ts
src/services/contracts/__tests__/safeContracts.test.ts
src/services/contracts/safeContracts.ts
src/utils/__tests__/transactions.test.ts
src/utils/transactions.ts

On e.g. Gnosis Chiado no migration libs are deployed. We still tried to migrate from L1 to L2 though.
- Does not prepend a migration call if the chain does not have the migration contracts deployed.
- Create a L1 1.3.0 Mainnet Safe
- Add Gnosis Chiado to it
- Activate and do any tx
- It should not try to migrate

Fix(Multichain): do not migrate to L2 if no lib contract is available

---

src/components/sidebar/NewTxButton/index.tsx
src/features/counterfactual/ActivateAccountButton.tsx

Resolves [SW-259](https://www.notion.so/safe-global/Show-Activate-Safe-button-in-sidebar-1138180fe57380968e26c6b987d7c090)
- Displays the `Activate now` button in the sidebar in case it is a counterfactual safe
1. Create a counterfactual safe
2. Observe there is an Activate now button in the sidebar

[Multichain] fix: Display Activate now button in sidebar for counterfactual safes [SW-259]

---

src/utils/__tests__/addresses.test.ts
src/utils/addresses.ts

Noticed that the `AddressInput` unit test randomly fails sometimes. This happens when faker generates a shortName with a hyphen or other special characters in it so I adjusted our cleanup function to handle such characters.
- Updates `cleanInputValue` to not only handle `a-z0-9` characters in the prefix but any character that is not a `:`
- Adds unit tests for `cleanInputValue`
1. Create a send transaction
2. Input `test-prefix:<some address>` into the recipient field
3. Observe that the value is not changed
4. Input a real chain prefix like `eth:<some address>`
5. Observe that it is the same behaviour as previously
On prod when typing `test-hyphen:<some address>`
With the change when typing `test-hyphen:<some address>`

fix: Handle special characters for prefix in address input

---

src/features/counterfactual/CounterfactualSuccessScreen.tsx
src/features/counterfactual/hooks/usePendingSafeStatuses.ts
src/features/counterfactual/services/safeCreationEvents.ts
src/features/counterfactual/utils.ts

Resolves #4293
- Emits the `chainId` with the SUCCESS and INDEXED safe creation event
- Uses that chainId inside the success modal instead of the current chain id
1. Create a safe on network A
2. Switch to a safe on network B
3. Observe the success screen showing network A info correctly once the safe has been deployed

fix: Poll safe creation info even when switching networks

---

src/components/new-safe/create/logic/index.ts

Resolves [SW-261](https://www.notion.so/safe-global/Creating-counterfactual-safe-on-zkSync-era-fails-when-pay-later-is-selected-1138180fe5738048ba74eb19dd9eb226)
- Uses chain-specific addresses for safeFactory, safeL1 and safeL2
1. Create a safe on zkSync
2. Observe no error

[Multichain] fix: Use chain-specific addresses for safe creation [SW-261]

---

src/features/multichain/hooks/__tests__/useSafeCreationData.test.ts
src/features/multichain/hooks/useSafeCreationData.ts

Validates the `safeAccountConfig` of counterfactual Safes as well.
- Try to replay a counterfactual Safe that uses a `payment` or unknown `to` address.

Fix(Multichain): validate account data

---

src/components/new-safe/create/logic/address-book.ts
src/components/new-safe/create/steps/ReviewStep/index.tsx
src/components/new-safe/create/steps/StatusStep/index.tsx
src/features/counterfactual/utils.ts

Owner names were not added to the address book for counterfactual Safe creation.
- Uses the `updateAddressBook` action regardless of the Safe creation method.
- Removes dispatching Address book actions from other methods than `updateAddressBook`
- Create a Safe on multiple chains
- Observe the owner and SAfe name being added to all selected networks.

fix(Multichain): store owner and Safe name in addressBook on all chosen networks

---

src/components/common/NetworkSelector/index.tsx
src/components/welcome/MyAccounts/SubAccountItem.tsx
src/features/multichain/components/CreateSafeOnNewChain/index.tsx

Resolves [SW-165](https://www.notion.so/safe-global/Check-analytics-7f1cdc962c6f45e1a1a79dc79055e948)
- Adds the missing events as described in the ticket
Check that the events described in SW-165 are emitted correctly

[Multichain] fix: Add more analytics events for multichain [SW-165]

---

src/components/new-safe/create/OverviewWidget/styles.module.css
src/components/new-safe/create/steps/ReviewStep/index.tsx
src/features/multichain/components/NetworkLogosList/styles.module.css

Resolves [SW-264](https://www.notion.so/safe-global/Show-condensed-view-of-networks-on-creation-review-1158180fe573804099ecf5463ab2531b)
- Uses `NetworkLogosList` with a Tooltip in Review step
- Adds a slight gap to the overview widget network list
1. Create a Safe with multiple networks selected
2. Go to the review step
3. Observe the condensed network view

[Multichain] fix: Add condensed network list to safe creation review [SW-264]

---

src/components/sidebar/SidebarNavigation/index.tsx

Counterfactual Safes cannot batch txs with the deployment anymore.
This PR disables swaps, staking and Safe apps for counterfactual Safes.
- Create a new Safe on multiple networks
- Observe Apps / Staking and swaps being disabled with a tooltip

Fix(Multichain): disable apps for counterfactual Safes

---

src/components/new-safe/create/steps/ReviewStep/index.tsx

Resolves [SW-265](https://www.notion.so/safe-global/Use-readOnly-provider-during-safe-creation-1188180fe57380c0b7fec106b609314b)
Uses the readonly provider for address prediction during safe creation
1. Create a Safe and select a network thats different from the connected wallet network
2. Go to the review step and submit
3. Observe no error

[Multichain] fix: Use readonly provider for predicting address during safe creation [SW-265]

---

src/components/sidebar/SidebarNavigation/index.tsx

Resolves [SW-266](https://www.notion.so/safe-global/Wrong-categories-are-blocked-for-the-CF-safe-1188180fe57380b8aed4e878ae8ebaeb)
- Inverts the condition so that the correct nav items are disabled
1. Open a counterfactual safe
2. Observe Swaps, Apps and Staking are disabled in the sidebar

[Multichain] fix: Invert condition to disable correct nav items [SW-266]

---

src/features/stake/constants.ts

When navigating to the earn page the user was directly sent to the earn tab. With this change the user will be one the overview page.
Changes the default url for the widget
Go to staking and observe that the user is on the overview tab.

feat: start the stake widget on the overview screen SW-233

---

src/components/tx/SignOrExecuteForm/index.tsx
src/features/stake/components/StakingConfirmationTx/Withdraw.tsx

I was originally fixing a bug with staking decoding being displayed twice:
But actually it turned out to be also the same for swaps:
Resolves #
We introduced this bug with the redesign of the tx-details: https://github.com/safe-global/safe-wallet-web/commit/fced30195d512e991afa29f9c77008b8654ddefc . We moved the TxData block higher up in the tree, but failed to account that we display the same info with the ConfirmationOrder view. So this block should be hidden if we are dealing with a stake or swap txs.
If we have any kind of StakingTxInfo or OrderTxInfo tx we hide the TxData block.
Create a swap or stake tx. Sign it. Now in the tx queue hit execute. In production right now we display nearly the same data twice, with this fix only the appropriate confirmation view data is displayed.

fix: swap & stake decoding was displayed twice

---

src/components/new-safe/create/logic/index.test.ts
src/components/new-safe/create/logic/index.ts
src/components/new-safe/create/logic/utils.ts
src/components/new-safe/create/steps/ReviewStep/index.tsx

Fixes address prediction on zkSync and therefore safe creation
- Reverts to using the core sdk for address prediction on zk sync.
- Create a CF Safe on zkSync
- Activate it and observe that the predicted address matches again

Fix(Multichain): zk sync creation

---

src/components/common/NetworkSelector/index.tsx
src/components/welcome/MyAccounts/MultiAccountItem.tsx
src/features/multichain/components/CreateSafeOnNewChain/index.tsx
src/services/analytics/events/overview.ts

Follow-up on [SW-165](https://www.notion.so/safe-global/Check-analytics-7f1cdc962c6f45e1a1a79dc79055e948)
- Only emits expand event if expanded not collapsed
- Adds an event for expanding "Show all networks"
- Sets the chainId when creating a new safe
1. Open the sidebar and expand a multichain safe
2. Observe an expand event
3. Collapse the multichain safe
4. Observe no expand event
5. Click on on "Show all networks" in the header
6. Observe an event when expanding but not collapsing
7. Add a safe on another network
8. Observe the GA events contain the chainId of the new safe

[Multichain] fix: Adjust multichain analytics events [SW-165]

---

cypress/e2e/pages/safeapps.pages.js

- Add more timeout to info modal test as sometimes it is not enough time to retrieve values from local storage

Tests: Add timeout for infomodal test

---

src/components/transactions/TxDetails/TxData/DecodedData/index.tsx
src/components/transactions/TxDetails/TxData/index.tsx
src/utils/transaction-guards.ts

The MultiSends of migrations are not flagged as trusted because they contain delegateCalls.
Adds a workaround that detects that the tx only contains a trusted migration delegateCall and nothing else.
Open e.g. this Safe:
`aurora:0x51b49d7812478A2eaa25fA1d5F7352600d3ABfD2`

fix(Multichain): detect migration txs and mark them as trusted

---

src/features/multichain/hooks/__tests__/useSafeCreationData.test.ts
src/features/multichain/hooks/useSafeCreationData.ts

Replaying counterfactual Safes without paymentToken set lead to a wrong error.
Corrects the check for reimbursements
- Create a new counterfactual Safe
- Try to add a network without activating first

fix(Multichain): allow missing paymentToken when adding networks

---

src/features/multichain/components/CreateSafeOnNewChain/index.tsx

Resolves [SW-270](https://www.notion.so/safe-global/Adding-new-network-does-not-update-address-book-1198180fe5738025b835d3aeb84d5162)
- Calls `updateAddressBook` when replaying a safe from the sidebar or network selector
1. Create a safe
2. Open the sidebar and replay the safe on another network
3. Go to the address book
4. Observe an entry for this safe

[Multichain] fix: Update address book for replayed safe [SW-270]

---

src/hooks/__tests__/useLoadChains.test.ts
src/hooks/loadables/__tests__/useLoadChains.test.ts
src/hooks/loadables/helpers/__tests__/config.test.ts
src/hooks/loadables/helpers/config.ts
src/hooks/loadables/useLoadChains.ts
src/pages/_app.tsx

We are not able to load more than 20 networks in the UI
Resolves #
https://github.com/safe-global/safe-wallet-web/issues/4336
The getConfigs function was using the client gateway sdk to fetch the chains. This call is limited to 20 items and we never try to fetch more. The config service now has more than 20 networks and we are missing them in the url. It turned out however that it is very difficult to provide the {offset, limit} arguments to the getChainInfo on the sdk. Something seems wrong and generated next url is wrong.
That’s why I opted out of using the sdk for this call and instead directly fetch the results and follow the next prop on the returned object until there is nothing more.
If using the production gateway the chiado network should be visible.

fix: useLoadChains should follow the next url

---

src/components/common/Chip/index.tsx
src/components/sidebar/SidebarNavigation/config.tsx

Resolves #4259 
- Adjusts the `Chip` component to receive an `sx` prop to have more granular control over colors
1. Open a Safe
2. Observe the New chip in the sidebar is green
3. Observe the Chip for the SAP on the dashboard still looks the same

fix: Change color of New chip in sidebar

---

src/components/tx/SignOrExecuteForm/DelegateForm.tsx
src/components/tx/SignOrExecuteForm/index.tsx
src/services/analytics/events/transactions.ts

Resolves #4206
- Extends `trackTxEvents` to handle delegate form submissions
1. Open a Safe that has a delegate
2. Create a transaction as a delegate
3. Observe a GA event being emitted once the user submits the tx in their wallet

fix: Track number of delegate transactions

---

cypress/e2e/happypath/sendfunds_relay.cy.js
cypress/e2e/pages/create_tx.pages.js
src/components/tx/RemainingRelays/index.tsx
src/hooks/useRemainingRelays.ts
src/services/exceptions/ErrorCodes.ts

Reflect increased relay window in UI.
All references to "per hour" for the relay limit window have been changed to daily to reflect the forthcoming increase.
Relay a transaction and observe all limit references be daily.

fix: increase relay limit window to daily

---

src/components/new-safe/create/steps/ReviewStep/index.tsx
src/features/multichain/components/CreateSafeOnNewChain/index.tsx

Resolves [SW-270](https://www.notion.so/safe-global/Adding-new-network-does-not-update-address-book-1198180fe5738025b835d3aeb84d5162)
- Looks up the owner entry in the address book when replaying a safe and copies it over if it exists
1. Create a Safe and add owner names
2. Observe them in the address book
3. Replay the safe on another chain
4. Observe them still being in the address book on the new chain

[Multichain] fix: Copy owners to address book when replaying safe [SW-270]

---

src/hooks/useTransactionType.tsx

The icon in dark mode for stake txs was barely visible
Resolves #
The image was not loaded as SVG. Now we load it as SVG and that solves the issue.
check this safe in dark mode: transactions/history?safe=holesky:0x00780312A5F6c561328566Ed01C77fc7596141a6

fix(staking): stake icon was not rendred properly in dark mode

---

package.json
src/hooks/useTransactionType.tsx

* fix(staking): stake icon was not rendred properly in dark mode (#4357)

Release 1.44.3

---

src/components/safe-apps/AppFrame/useAppCommunicator.ts
src/services/safe-apps/AppCommunicator.ts

Resolves https://github.com/safe-global/safe-react-apps/issues/824
It adds the getCurrentTheme method into the app communicator in order to share the darkMode information with the transaction builder or any other safe app.
- Take the transaction builder dark mode deployed PR link and add it on your safe
- Open the custom tx-builder app which you just added
- change the dark mode toggle on the sidebar
- **the transaction builder theme should change according to safe wallet theme** 
[txbuilder.webm](https://github.com/user-attachments/assets/94ef42c4-815d-4717-9dfc-f62ae71adba7)

feat(tx-builder-mode): share dark mode information with safe apps

---

src/store/gateway.ts

Resolves #4359
Our `gatewayApi` has been refactored to use the `fakeBaseQuery` of RTK Query. It accepts a generic, with which we can specify the error type we expect - an `Error` instance in our case. A builder for the `queryFn` within `endpoints` then wraps all Client Gateway calls, returning such instances.
There should be no noticeable difference in the UI. Usage of the above can, however, be checked as such:

refactor: simplify RTK Query `endpoints`

---

src/features/counterfactual/CounterfactualSuccessScreen.tsx

Resolves [SW-287](https://www.notion.so/safe-global/all-added-networks-are-displayed-instead-one-network-where-the-safe-was-activated-11c8180fe573802bb404e5e6bff339a6)
- Narrows down `networks` when receiving an INDEXED event
1. Create a multichain safe on at least 2 networks
2. Observe all the network logos on the success screen
3. Activate one of them
4. Observe only the activated network logo on the success screen
5. Reload the page
6. Activate another safe
7. Observe the correct network logo on the success screen

[Multichain] fix: Only show network logo of activated safe [SW-287]

---

src/components/common/CheckWallet/index.test.tsx
src/components/common/CheckWallet/index.tsx

`allowSpendingLimits` in `CheckWallet` did not work anymore.
Fixes the conditions in `CheckWallet` and the unit test that did not pick up the error
- Connect with a wallet that only has a spending limit
- Observe the "New transaction" button to be available

fix: allowSpendingLimit in CheckWallet

---

src/components/common/NetworkInput/index.tsx
src/components/common/NetworkInput/styles.module.css

Add badge to unavailable networks in add network modal.
- Add a network to a Safe
- Observe that e.g. zkSync is marked as unavailable

Feat: add badge to unavaible chains

---

src/utils/__tests__/tokens.test.ts
src/utils/tokens.ts

Resolves #4376 
- Tries to parse erc20 symbols with `parseBytes32String` in case it throws
- Adds fallbacks for symbol and decimals
1. Open a safe with MKR as a spending limit
2. Observe it showing up in the table

fix: Add fallbacks when parsing erc20 symbol and decimals

---

src/features/counterfactual/CounterfactualSuccessScreen.tsx

Resolves #4383 
- If there is a `chainId` we assume it is not a counterfactual deployment and show a different message
1. Create a single safe and deploy immediately
2. Observe the success screen is saying "Your Account is all set"
3. Create a single safe and pay later
4. Observe the success screen is saying "Your account is almost set"
5. Create a multichain safe
6. Observe the success screen is saying "Your account is almost set"
7. Deploy one of the accounts
8. Observe the success screen is saying "Your account is all set"

fix: Show different message in success screen when safe is deployed

---

.github/workflows/e2e-prod-ondemand.yml
cypress/e2e/prodhealthcheck/swaps_tokens.cy.js
cypress/e2e/regression/swaps_tokens.cy.js

- Sometimes tests failed due to incorrect amount of assets shown on dashboard. This was specifically noted in automation flow. Manual flow works as expected. To overcome this issue, SAFE_v2__settings was added to local storage to retrieve correct number of assets in dashboard. 
- Adjust prod tests workflow to avoid TestRail step failing in pipeline

Tests: Fix prod tests

---

src/components/tx-flow/flows/ConfirmBatch/index.tsx
src/components/tx/confirmation-views/BatchTransactions/BatchTransactions.stories.tsx
src/components/tx/confirmation-views/BatchTransactions/BatchTransactions.test.tsx
src/components/tx/confirmation-views/BatchTransactions/__snapshots__/BatchTransactions.test.tsx.snap
src/components/tx/confirmation-views/BatchTransactions/index.tsx
src/components/tx/confirmation-views/BatchTransactions/mockData.ts
src/components/tx/confirmation-views/index.tsx
src/components/tx/confirmation-views/utils.ts

This PR is part of the unify confirmations screen refactor in the transactions flow (https://github.com/safe-global/safe-wallet-web/pull/4177). 
In this PR we're moving the `BatchList`  from `ConfirmBatch` component to be inside the `tx/confirmation-view/BatchTransactions` component. Please noticed we still have logic inside the `ConfirmBatch` component because the `SignOrExecuteForm/index` depends on the SafeTx in order to get the transactionDetails, and the place where we create the SafeTx for the Batch screen is inside the `ConfirmBatch` component.
1) Go to the top bar of the application and try to send a batch transaction
2) The confirm batch transaction screen should look the same as production app.

Refactor: unify confirmBatch screen

---

package.json
src/components/common/NetworkSelector/NetworkMultiSelector.tsx
src/components/new-safe/create/logic/index.ts
src/components/transactions/TxDetails/TxData/MigrationToL2TxData/index.tsx
src/features/multichain/hooks/__tests__/useCompatibleNetworks.test.ts
src/features/multichain/hooks/useCompatibleNetworks.ts
yarn.lock

If only worldchain is selected as network during Safe creation the SetupToL2 call was missing during deployment.
- Upgrade `safe-deployments` to latest version
- Check for all network options that they have a SetupToL2 deployment available if multiple networks are selected
- Check that target network has MigrateToL2 deployment when adding networks to existing Safes
- Create a Safe on only Worldchain
- Observe that it has the correct masterCopy
- Add Worldchain to a legacy L1 Safe
- Observe that it can be migrated

fix: check deployments of migration contracts, upgrade safe-deployments

---

src/components/common/NetworkSelector/NetworkMultiSelector.tsx

Resolves #4382 
Triggers validation when removing a network.
- select some chains in the create Safe modal
- Remove all selected chains
- Observe the next button being disabled

fix: revalidate input when removing networks

---

src/hooks/loadables/useLoadBalances.ts

This pull request includes a significant change to the `mergeBalances` function in the `src/hooks/loadables/useLoadBalances.ts` file. The update focuses on improving how balances are merged by ensuring unique token addresses and giving precedence to SafeNet items.
Key changes:
* [`src/hooks/loadables/useLoadBalances.ts`](diffhunk://#diff-719a07107449842c596d71bdde56928c6ea1844db785ed06f58b814ab62bc8e8L30-R39): Modified the `mergeBalances` function to use a `Map` for merging balances, ensuring that token addresses are unique and SafeNet items take precedence.

Remove duplicates when merging balances

---

cypress/e2e/regression/swaps.cy.js

The cypress test was failing because we had to execute some transactions in the safe that we use for testing.
Updates the nonce (in theory the nonce should not change again and that's why we don't need to automate it).
Run the cypress test and it should succeed.

fix: cypress test fails due to incorrect nonce

---

src/components/transactions/TxDetails/index.tsx
src/components/transactions/TxSigners/index.tsx

Resolves [SW-297](https://www.notion.so/safe-global/Delete-proposed-transaction-as-an-owner-that-created-the-delegate-11f8180fe573807a9689ff9713940d97)
- Shows the signer block if its an unsigned but trusted tranaction
- Allows to reject delegated transactions
There are a few limitations that need to be tested
1. Only the owner who created the delegate that proposed a transaction can delete their transactions
2. Owners and delegates can replace transactions
3. Only the last transaction or duplicate transactions can be deleted
4. Signed transactions should still offer a Reject option like before

feat: Allow deletion of delegate transactions from the queue [SW-297]

---

cypress/e2e/pages/create_tx.pages.js
cypress/e2e/smoke/tx_history.cy.js
src/hooks/loadables/useLoadTxHistory.ts
src/hooks/useTxHistory.ts
src/store/settingsSlice.ts

Hiding suspicious transactions by default
The default preference to hide suspicious transactions is now set to `true`.
Ensuring no preferences are set, observe the "Hide suspicious" switch to be on by default in the transaction history.

fix: hide suspicious transactions by default

---

src/components/common/NetworkSelector/__tests__/NetworkMultiSelector.test.tsx

Adds a test for the `NetworkMultiSelector` component as it contains a lot of logic and had some issues in the past.

test: add unit test for NetworkMultiSelector

---

src/components/common/CheckWallet/index.test.tsx
src/components/common/CheckWallet/index.tsx
src/components/settings/ProposersList/index.tsx

Resolves [SW-400](https://www.notion.so/safe-global/As-a-proposer-I-can-go-throught-the-add-proposer-12a8180fe57380b4810cec062aaaa98c)
Resolves [SW-396](https://www.notion.so/safe-global/Only-owner-who-created-delegate-can-delete-them-12a8180fe57380ca84e9c8fb60e35004)
- Disables the `Add proposer` button for proposers
- Only enables the Delete proposer button if any of these conditions meet:
- - Connected wallet is the proposer itself
- - Connected wallet is the owner who created the proposer
1. Open a safe with proposers
2. Connect with one of the proposers
3. Observe you can't add new proposers
4. Observe you can only delete yourself
5. Connect with an owner that didn't create any proposers
6. Observe you can't delete them
7. Connect with an owner that created a proposer
8. Observe you …

fix: Disable add proposer and delete proposer [SW-400] [SW-396]

---

.env.example
cypress/e2e/regression/bulk_execution.cy.js
cypress/support/e2e.js

- Fix regression test where hide suspicious token is used
- Add logic to enable e2e tests to still run without valid BEAMER_DATA_E2E
- Update .env.example file: added optional to BEAMER_DATA_E2E

Tests: Update e2e tests

---

src/components/tx/SignOrExecuteForm/index.tsx

This pull request introduces a new feature to check if Safenet is enabled and adjusts the execution button display logic accordingly in the `SignOrExecuteForm` component. The most significant changes include importing the `useIsSafenetEnabled` hook, initializing the `isSafenetEnabled` variable, and modifying the `canExecute` condition to incorporate the new feature.
Feature addition:
* [`src/components/tx/SignOrExecuteForm/index.tsx`](diffhunk://#diff-70addbd231a36637989f9e3732bed07149598277eee9498f69fb69dc12463ffcR46): Imported the `useIsSafenetEnabled` hook.
* [`src/components/tx/SignOrExecuteForm/index.tsx`](diffhunk://#diff-70addbd231a36637989f9e3732bed07149598277eee9498f69fb69dc12463ffcR128): Initialized the `isSafenetEnabled` variable using the `useIsSafenetEnabled` hook.
Execution …

feat: disable execute button for Safenet transactions

---

src/components/tx/SignOrExecuteForm/ConfirmationTitle.tsx
src/components/tx/SignOrExecuteForm/ProposerForm.tsx
src/components/tx/SignOrExecuteForm/index.tsx

Resolves [SW-381](https://www.notion.so/safe-global/Update-message-when-proposing-tx-1298180fe573806bbc3cf615a75febad)
- Adjusts the message shown to proposers when creating a tranaction
- Changes the confirmation title to `Propose`
1. Open a safe as a proposer
3. Observe the new message when confirming

fix: Adjust message when proposing transaction [SW-381]

---

src/components/sidebar/Sidebar/index.tsx
src/components/welcome/MyAccounts/AccountItem.tsx
src/components/welcome/MyAccounts/CreateButton.tsx
src/components/welcome/MyAccounts/MultiAccountItem.tsx
src/components/welcome/MyAccounts/PaginatedSafeList.tsx
src/components/welcome/MyAccounts/QueueActions.tsx
src/components/welcome/MyAccounts/SafesList.tsx
src/components/welcome/MyAccounts/SubAccountItem.tsx
src/components/welcome/MyAccounts/index.tsx
src/components/welcome/MyAccounts/styles.module.css
src/components/welcome/MyAccounts/useAllSafes.ts
src/components/welcome/MyAccounts/useAllSafesGrouped.ts
src/features/multichain/utils/utils.test.ts
src/store/__tests__/safeOverviews.test.ts
src/store/addedSafesSlice.ts

Resolves: https://www.notion.so/safe-global/Create-pinned-accounts-list-in-sidebar-and-accounts-page-11f8180fe573806da36dc2327ce063ad?pvs=4
Replaces the existing safe lists in the sidebar with `Accounts`, containing all owned and read only accounts, and `Pinned` containing safes that have been manually added to the list.
- Adds a pinned flag to the added safes slice
- When you pin a safe, it adds it to the added safes list (if not already added) and sets this flag to true.
- Pinned safes appear in both the pinned list and also in the full list below.
On the accounts page or the sidebar:
- Make sure you can pin and unpin safes (single chain and multichain should behave the same)
- Pinned safes should persist, even when connecting with a different wallet, or in the disconnected state.
- …

Feat(Sidebar): Add pinned safes list to sidebar and accounts page [SW-304]

---

package.json
src/components/settings/ProposersList/index.tsx
src/components/transactions/TxDetails/index.tsx
src/components/transactions/TxSigners/index.tsx
yarn.lock

Resolves SW-309
- Updates the CGW SDK to the newest version
- Uses the new `proposedByDelegate` field to display the address in the queue for proposed transactions
1. Propose a transaction
2. Go to the queue
3. Open the transaction details
4. Observe the proposer address

feat: Show proposer address in queue [SW-309] [SW-426]

---

src/components/transactions/SignTxButton/index.tsx

Resolves SW-431
- Restricts the Tooltip in `SignTxButton` to only show for owners
1. Propose a transaction
2. Go to the queue
3. Hover the Confirm button as a proposer
4. Observe no tooltip
5. Switch to an owner
6. The buttons should be enabled as before

fix: Hide tooltip on confirm button for proposers [SW-431]

---

src/components/tx/security/tenderly/index.tsx

Resolves SW-429
- Uses the first safe owner address as the executor in case a proposer runs a tenderly simulation
1. Create a transaction as a proposer
2. Press simulate
3. Observe that the simulation does not fail

fix: Use safe owner address for tenderly simulation with proposer [SW-429]

---

src/components/transactions/TxSummary/index.tsx

Resolves SW-434
Immediately executed transaction showed the `Proposal` chip in the tx summary even if it wasn't a proposal because in both cases there is no signature returned.
- If a transaction is pending in the queue we don't show the `Proposal` chip in the summary
1. Create and execute a transaction in a 1/n safe
2. Observe that the pending transaction in the queue doesn't show the `Proposal` chip
3. Create a proposal
4. Execute the proposal with an owner
5. Observe the pending transaction doesn't show the `Proposal` chip

fix: Only show proposal chip if transaction is not pending [SW-434]

---

src/components/common/AddressInput/styles.module.css
src/components/tx/SignOrExecuteForm/index.tsx
src/features/proposers/components/UpsertProposer.tsx

Resolves SW-407
Resolves SW-428
- Removes the owner validation from the `UpsertProposer` form
- Removes the horizontal scrollbar when adding proposers
1. Add a new proposer and choose an address from your address book
2. Observe there is no horizontal scrollbar visible
3. Add an owner as a proposer
4. Observe no validation errors
5. Create a transaction as that owner
6. Observe no messages about being a proposer

fix: Allow owners to be added as proposers [SW-407] [SW-428] [SW-381]

---

src/features/targetedOutreach/components/OutreachPopup/index.tsx
src/features/targetedOutreach/constants.ts

Replaces the test URL with the final version of the outreach survey banner. Also changes the banner message to only use the first name.
- Open a targeted safe showing the outreach banner
- click on the CTA and ensure it leads to the correct link (opinionX)

Feat: Update outreach survey URL

---

src/features/proposers/components/DeleteProposerDialog.tsx
src/features/proposers/components/UpsertProposer.tsx
src/features/proposers/utils/utils.ts
src/store/api/gateway/proposers.ts

Resolves SW-407
- Uses the v1 endpoints for adding and deleting a proposer when a hardware wallet is detected
1. Connect with a hardware wallet (Alternatively hard-code the `isHardwareWallet` to be true)
2. Go to the settings page and add a proposer
3. Observe the message to be signed is not typed data
4. Observe a success message
5. Delete a proposer
6. Observe the message to be signed is not typed data
7. Observe a success message

feat: Support hardware wallets for adding and removing proposers [SW-407]

---

src/components/settings/ProposersList/index.tsx
src/features/proposers/components/DeleteProposerDialog.tsx
src/store/api/gateway/proposers.ts

Resolves SW-408
Resolves SW-470
- Tightens validation when doing optimistic updates to the proposer list
- Displays the creator address in the proposer list
1. Open the settings and create a proposer
2. Observe the creator address is shown next to them
3. Add the same proposer twice with 2 different owners
4. Delete one of them
5. Observe the other proposer is still visible in the list
6. Add the same proposer twice with 2 different owners
7. Update the name of one of them
8. Observe the correct entry is updated

feat: Display creator in the proposer list [SW-408] [SW-470]

---

src/components/sidebar/IndexingStatus/index.tsx
src/components/sidebar/Sidebar/index.tsx
yarn.lock

Resolves https://www.notion.so/safe-global/Show-Indexer-Status-57f83175f045417591f9e8f82e2419bd
The endpoint types have been added here: https://github.com/safe-global/safe-gateway-typescript-sdk/pull/201
The endpoint is currently returning a 500, @iamacook will investigate.

Feat: indexing status (SWS-134)

---

src/components/common/GradientBoxSafenet/index.tsx
src/components/transactions/TxDetails/Summary/index.tsx
src/components/tx/SignOrExecuteForm/SafenetTxChecks.tsx
src/components/tx/SignOrExecuteForm/styles.module.css
src/components/tx/security/safenet/index.tsx
src/components/tx/security/safenet/styles.module.css

Designs for the Safenet UI included changes to the security check UI elements; this PR implements those styling changes.
A new `GradientBoxSafenet` UI element was created that wraps an inner element in a box. This was done because implementing gradients on borders is kind of annoying, and so having a component to abstract this away was nice.
UI was changed in both the TX details view in the queue, but also for the signing and execution flow.

Polish Safenet UI for Security Checks

---

src/components/common/GradientBoxSafenet/index.tsx
src/components/sidebar/Sidebar/styles.module.css
src/components/sidebar/SidebarHeader/index.tsx
src/components/sidebar/SidebarHeader/styles.module.css
src/components/transactions/TxDetails/Summary/index.tsx
src/components/transactions/TxDetails/Summary/styles.module.css
src/components/tx/SignOrExecuteForm/SafenetTxChecks.tsx
src/components/tx/SignOrExecuteForm/styles.module.css
src/components/tx/security/safenet/index.tsx
src/components/welcome/MyAccounts/MultiAccountItem.tsx
src/components/welcome/MyAccounts/styles.module.css

This PR changes the account item list to use the `GradientBoxSafenet` component so that the appearance is consistent:
- Icon size/colors are guaranteed to be the same
- uses gradient border
Additionally, https://github.com/safe-global/safe-wallet-web/pull/4487/commits/74b5325c1616ecc0d38592296e68d3ce74474e57 was meant to be included with #4486 but was accidentally omitted and included in this PR instead.

Refactor Account Items to use Gradient Box

---

docs/release-procedure.md

A draft release is created automatically but a final release needs to be created manually from the draft. Adds in this extra step.

Docs: update release docs with missing step for creating final release

---

cypress/e2e/pages/sidebar.pages.js
src/components/welcome/MyAccounts/OrderByButton.tsx
src/components/welcome/MyAccounts/SafesList.tsx
src/components/welcome/MyAccounts/index.tsx
src/components/welcome/MyAccounts/useSafesSearch.ts
src/services/analytics/events/overview.ts

Resolves: https://www.notion.so/safe-global/Add-search-to-safes-list-11f8180fe573800b952bd3189dca3b67?pvs=4
- When the user types in the search bar, renders a filtered list of all safes based on the search term.
- On the accounts page or sidebar, start typing in the search bar.
- Only safes with names matching the search query should be shown. It uses a fuzzy search, like the safe apps search.
- It should also match chain name and address

Feat(sidebar): filter safes by search query [SW-305]

---

README.md
src/components/transactions/TxDetails/Summary/index.tsx
src/components/tx/SignOrExecuteForm/index.tsx

Small fixes for the Safenet demo:
- Wording in transaction details
- Disable Blockaid for Safenet (as it doesn't seem to work because of the guard)

Small Fixes for Safenet Demo

---

src/components/tx-flow/common/TxStatusWidget/index.tsx
src/features/proposers/components/DeleteProposerDialog.tsx

- Passes the correct delegator address when deleting a proposer
- Adjusts `canSign` and `canConfirm` conditions to account for proposers in `TxStatusWidget`
1. Add a proposer
2. Switch to the proposer address
3. Delete yourself as proposer
4. Observe no network error
5. Create a transaction as a proposer
6. Observe the status widget shows confirmations greyed out

fix: Delete proposer as proposer, adjust status widget

---

src/components/welcome/MyAccounts/AccountItem.tsx
src/components/welcome/MyAccounts/MultiAccountItem.tsx
src/components/welcome/MyAccounts/OrderByButton.tsx
src/components/welcome/MyAccounts/index.tsx
src/components/welcome/MyAccounts/useSafesSearch.ts
src/components/welcome/MyAccounts/useTrackedSafesCount.ts
src/services/analytics/events/overview.ts

Resolves [SW-308]
- Adds events for new interactions added in the epic
- Open the accounts page. Observe that the number of owned safes and watchlist safes are tracked as before (once on the first load).
- In addition, the number of pinned safes should now be tracked also.
- Use the search bar to filter safes. An event should be emmitted for each search.
- Use the sort by button. Whenever the sort by value changes, an event should be emitted with the new sort by value.
- Pin or unpin a safe. An event should be emitted specifying which action took place.

Feat(sidebar): Add tracking events for search, sorting, and pinning/unpinning safes [SW-308]

---

src/components/settings/ProposersList/index.tsx
src/config/constants.ts

Resolves [SW-301](https://www.notion.so/safe-global/Update-the-help-article-11f8180fe573806aa5d1db609745dff5)
- Updates the help article link for proposers
1. Go to settings
2. Press "Learn more" under Proposers section
3. Observe the new link opening

fix: Update proposers help article link [SW-301]

---

src/features/myAccounts/components/DataWidget/index.tsx
src/features/myAccounts/index.tsx

Resolves SW-507
See that the accounts page and sidebar matches the designs for:
- when no wallet is connected
- when there are no safes in the list. 
- the datawidget when no data is available.
No safes:
Not connected:
Sidebar data widget:

fix(sidebar):  fix designs for data widget and empty/disconnected state [SW-507]

---

src/hooks/useTransactionType.tsx

Resolves #4384 
- Uses `SvgIcon` to insert batch icon in transactions list
1. Open a safe with batched transactions
2. Go to the history
3. Observe the batch icon is visible in dark and light mode

fix: Batch icon in dark mode

---

src/components/tx-flow/flows/ChangeThreshold/context.tsx
src/components/tx/confirmation-views/ChangeThreshold/ChangeThreshold.stories.tsx
src/components/tx/confirmation-views/ChangeThreshold/index.tsx
src/components/tx/confirmation-views/index.tsx
src/components/tx/confirmation-views/utils.ts

Confirm threshold screen is showing 0 of (n) when user comes from the transaction list.
Before we were grabbing the threshold information from the changeThreshold screen flow, but this information is not available when user comes from the transactions list (for eg, in order to confirm a `change threshold` transaction)
- Change the threshold of your account
- sign but do not execute it
- go to the transaction list and try to confirm or execute it from there.
- The amount of required signers now should be working as expected instead of showing "0 out (n)"

[ SW-467 ] fix(threshold-info): Display right info in the change threshold confirmation screen

---

src/features/myAccounts/components/AccountInfoChips/index.tsx
src/features/myAccounts/components/AccountItems/styles.module.css
src/features/myAccounts/hooks/useSafesSearch.ts

Resolves: https://www.notion.so/safe-global/Feedback-QA-1378180fe57380ef8c58c80deea0deea
https://www.notion.so/safe-global/Feedback-QA-1378180fe57380ef8c58c80deea0deea
- Searches multichain sub safes in when searching.
- Fixes undeployed safe chip color in dark mode
- Fixes issue with pending/ to confirm chips being cut off at a certain screen width
- For a multichain safe, edit the names of the sub safes in the address book, giving different names.
- Make sure all sub safe names are matched when searching

Fix(Sidebar): Include sub safe in search results [SW-305]

---

src/features/counterfactual/utils.ts

The app might crash when coming back after a 6-week vacation with an old localStorage.
* Check out an old version of the app (from September 2024)
* Connect a wallet
* Add a few Safes to the watchlist
* Then check out the latest production code
* Connect wallet
* Open the Safe List sidebar
* App crashes

Fix: add a guard for a possibly undefined safeAccountConfig

---

cypress/e2e/pages/safeapps.pages.js
cypress/e2e/safe-apps/apps_list.cy.js

- Safe apps tests needed to be updated as we added Featured apps section.

Tests: Cy release tests

---

cypress/e2e/happypath_2/proposers.cy.js
cypress/e2e/pages/proposers.pages.js
cypress/e2e/pages/safeapps.pages.js
cypress/e2e/pages/sidebar.pages.js
cypress/e2e/safe-apps/apps_list.cy.js

With introduction of the Featured apps section, there is a need to add additional tests. The following were added:
- Verify the featured apps list
- Verify that pinned app can be in pinned section and in featured at the same time
Part of this PR also includes minor refactoring: delete unused imports, adding extra verification to a test.

Tests: Add safe apps tests

---

src/markdown/terms/terms.md

As small fix for the Terms page as requested by legal – section 13 heading wasn't properly linked.

Fix: section heading in terms

---

cypress/e2e/pages/sidebar.pages.js
cypress/e2e/smoke/import_export_data.cy.js
cypress/e2e/smoke/import_export_data_2.cy.js

- Refactoring: removed extra signer connection to avoid issues with safe loading

Tests: Update import export tests

---

src/features/walletconnect/__tests__/WalletConnectContext.test.tsx

Tests were failing due to a new npm module not working in Jest.

Fix: WC unit tests

---

src/store/__tests__/safeOverviews.test.ts
src/store/api/gateway/safeOverviews.ts

Resolves #4479
Requests `fiatTotal` in `SafeOverviews` using `trusted=false` as we otherwise receive 0 balances for Safes on networks without Default tokenlists.
- Open a Safe with ERC20 tokens on a network without default token list.
- Compare the balance in the sidebar / network selector with the one in e.g. the dashboard

fix: fetch safe overviews including untrusted token fiatTotal

---

src/components/new-safe/create/steps/ReviewStep/index.tsx
src/components/new-safe/load/index.tsx
src/components/sidebar/SafeListContextMenu/index.tsx
src/components/sidebar/SafeListRemoveDialog/index.tsx
src/components/sidebar/WatchlistAddButton/index.tsx
src/features/multichain/utils/utils.test.ts
src/features/myAccounts/components/AccountInfoChips/index.tsx
src/features/myAccounts/components/AccountItems/MultiAccountItem.tsx
src/features/myAccounts/components/AccountItems/SingleAccountItem.tsx
src/features/myAccounts/components/AccountItems/SubAccountItem.tsx
src/features/myAccounts/hooks/useAllSafes.ts
src/features/myAccounts/hooks/useTrackedSafesCount.ts
src/store/__tests__/safeOverviews.test.ts
src/store/addedSafesSlice.ts

Simplify the code and the UI by treating all Added Safes as pinned.
There's now no distinction between "watchlist" Safes and "pinned" Safes. Watchlist Safes are simply pinned read-only Safes.
Counterfactual Safes will be now always displayed under Accounts because they are added to the `useAllSafes` hook.

Refactor: pinned = added safes [SW-304]

---

src/components/safe-messages/DecodedMsg/index.tsx
src/components/safe-messages/MsgDetails/index.tsx
src/components/safe-messages/MsgListItem/ExpandableMsgItem.tsx

Resolves #4561
I've added a catch-all error boundary around message details but also smaller localized try-catches for a couple places where it was failing in a specific safe.

Fix: catch erros in message decoding

---

cypress/e2e/pages/sidebar.pages.js
cypress/e2e/pages/staking.page.js
cypress/e2e/regression/sidebar_2.cy.js
cypress/e2e/regression/staking_history.cy.js
cypress/fixtures/staking_data.json
src/features/myAccounts/components/AccountItems/MultiAccountItem.tsx
src/features/myAccounts/components/AccountItems/SingleAccountItem.tsx
src/features/myAccounts/index.tsx

- The way safes are removed now has changed. Instead of remove button, removing of safes is done via a bookmark button. To address this change, some tests were updated. 
- A staking test failed due to changed activation time value. Instead of checking the hardcoded value, regex was added to make it flexible and reliable check. 

Tests: Fix sidebar and staking tests

---

src/features/multichain/hooks/useSafeCreationData.ts

Removes a debug log.
A leftover log from debugging is removed.
Observe no `creationData` log when opening the app.

fix: remove debug log

---

src/hooks/coreSDK/safeCoreSDK.ts

Follow-up on #4404 
The local storage structure of undeployed safes changed with multichain but during SDK initialization we only checked for the old structure instead of also the new one. This results in the Activate now button always being disabled for new counterfactual safes.
- Init the Safe SDK if undeployed safe `isReplayedSafeProps` or `isPredictedSafeProps`
1. Create a new counterfactual safe
2. Observe that the Activate now button is enabled

fix: Init Safe SDK for replayed safes

---

cypress/e2e/pages/create_wallet.pages.js
cypress/e2e/pages/sidebar.pages.js
cypress/e2e/prodhealthcheck/sidebar_3.cy.js
cypress/e2e/regression/sidebar_3.cy.js
cypress/e2e/regression/sidebar_4.cy.js
cypress/e2e/regression/sidebar_5.cy.js
src/features/myAccounts/index.tsx

- To provide automation coverage, some sidebar safe pin/unpin tests were added.
- This task also includes fixes for existing sidebar tests changed due to introduction of pin/unpin functionality.

Tests: Add safe pin tests

---

cypress.config.js
cypress/e2e/pages/sidebar.pages.js
cypress/e2e/prodhealthcheck/sidebar_3.cy.js

- To handle string variations in Accounts/My accounts section, the regex was added.

Tests: Add regex to handle my accounts

---

package.json
src/components/transactions/TxDetails/Summary/index.tsx
src/components/tx/DecodedTx/index.tsx

* Fix: catch error in hash calculation

Release 1.47.2

---

src/services/safe-wallet-provider/index.test.ts
src/services/safe-wallet-provider/index.ts
src/utils/hex.ts

Resolves incorrect `wallet_getCallsStatus` implementation
Our [EIP-5792](https://eips.ethereum.org/EIPS/eip-5792) implementation adhers to an outdated spec. In particular, the `wallet_getCallsStatus` method returns an incorrect response.
This updates the return type according to the latest spec. (similar to the [Safe Apps SDK update](wallet_getCallsStatus)):
```ts
async wallet_getCallsStatus(safeTxHash: string): Promise<{
status: BundleStatus
receipts?: Array<{
logs: TransactionReceipt['logs']
status: `0x${string}` // Hex 1 or 0 for success or failure, respectively
chainId: `0x${string}`
blockHash: `0x${string}`
blockNumber: `0x${string}`
gasUsed: `0x${string}`
transactionHash: `0x${string}`
}>
}>
```
Connect an EIP-5792 capable DApp via WalletConnect and observe status requests returning …

fix: update `wallet_getCallsStatus` spec.

---

cypress/e2e/pages/sidebar.pages.js
cypress/e2e/regression/sidebar_3.cy.js
cypress/e2e/regression/sidebar_5.cy.js
cypress/e2e/regression/sidebar_6.cy.js
cypress/support/constants.js
cypress/support/localstorage_data.js
src/features/myAccounts/components/OrderByButton/index.tsx
src/features/myAccounts/index.tsx

- Add tests for safe search and sorting in sidebar.

Tests: Add sidebar tests

---

cypress/e2e/safe-apps/drain_account.spec.cy.js

- Sometimes there is a longer wait period for safe with the message "Waiting for Safe". The wait time in tests to be increased a bit to handle this wait. 

Tests: Add timeout for drain account app

---

docs/update-terms.md
mocks/terms.md.js
src/components/common/CookieAndTermBanner/index.tsx
src/markdown/terms/terms.md
src/markdown/terms/terms.md.d.ts
src/markdown/terms/version.ts
src/store/cookiesAndTermsSlice.ts
src/store/index.ts

The entire `terms.md` (100kb+) was bundled with the main app chunk just to read the version. So I extracted it into a separate file instead.

Chore: extract terms version into a separate file for a smaller build

---

src/components/dashboard/SafeAppsDashboardSection/SafeAppsDashboardSection.tsx
src/components/safe-apps/AppFrame/index.tsx
src/components/safe-apps/SafeAppCard/index.tsx
src/components/safe-apps/SafeAppList/index.tsx
src/components/safe-apps/SafeAppPreviewDrawer/index.tsx
src/hooks/safe-apps/useSafeApps.ts
src/pages/apps/custom.tsx
src/pages/apps/index.tsx
src/services/analytics/events/safeApps.ts
src/services/analytics/gtm.ts

Resolves [tracking of featured Safe Apps](https://www.notion.so/safe-global/Add-tracking-events-for-featured-Safe-Apps-1468180fe57380dc9c12e898861574bb)
Featured Safe App interactions are currently not tracked.
This adds tracking to featured Safe Apps, as well as propagating the improvements to existing events: opening and (un-)pinning of Safe Apps (from their respective sections) now includes a `label`:
- `dashboard`
- `apps_pinned`
- `apps_featured`
- `apps_all`
- `apps_custom`
- `apps_sidebar`
Open and/or (un-pin) a Safe App from one of the label-specific locations, observing the new `label` in the tracked event:
- Dashboard
- Apps sections
- Pinned
- Featured
- All
- Custom
- Apps preview drawer
Important: when opening a Safe App for the first time, the "opened" event should _only_ …

fix: add event labels to opening and (un-)pinning of Safe Apps

---

cypress/e2e/pages/swaps.pages.js
cypress/e2e/regression/twaps.cy.js
cypress/e2e/regression/twaps_2.cy.js

- Some TWAP tests were previously failing due to inconsistent behavior, as detailed [here](https://www.notion.so/safe-global/76f265123c0a4ad680947ce489804342?v=f9f164524ec4464286fdc38f31589d0c&p=12e8180fe5738037bd0cd74af080c6dd&pm=s). Upon revisiting the issue, it became evident that the app's state had improved, and the bug was no longer reproducible. However, updates to the tests were necessary to restore functionality, including adjustments to the steps and UI locators.

Tests: Update twap tests

---

next.config.mjs

Caching ethers and protocol-kit in a separate chunk avoids building them on each page compilation.

Chore: speed up dev build

---

src/services/safe-wallet-provider/index.test.ts
src/services/safe-wallet-provider/index.ts

Resolves duplicate hex prefixes in `wallet_getCallsStatus` receipts
In https://github.com/safe-global/safe-wallet-web/pull/4569, the types of `blockNumber`/`gasUsed` were explicitly referenced for the receipts of `wallet_getCallsStatus`.
After further testing, the types of aforementioned values are incorrect. They are hex, not `number`/`bigint`. This adds a check to ensure that they are of type `number` (as we do [in the SDK](https://github.com/safe-global/safe-apps-sdk/blob/main/packages/safe-apps-provider/src/provider.ts#L262-L264)).
Test coverage for both the correct (in case the types are fixed) and incorrect types have also been added.
Request the receipts of an EIP-5792 batch via `wallet_getCallsStatus`, and observe the `blockNumber`/`gasUsed` are hex, without a repeated `0x` …

fix: do not duplicate hex prefixes in `wallet_getCallsStatus` receipts

---

.github/workflows/e2e-full-ondemand.yml
.github/workflows/e2e-ondemand.yml

- With continuous development of new automation tests, we need to increase job timeouts. 

Tests: Increase timeout

---

src/components/common/SafeTokenWidget/index.tsx
src/hooks/useSafeTokenAllocation.ts

Resolves [SW-586](https://www.notion.so/safe-global/Update-safe-token-header-widget-14a8180fe57380e9a399cad809b8dc16)
- Adds an `UnreadBadge` to the safe token header widget in case there is an allocation
- Shows a different tooltip text in case there is an allocation
1. Open the app with a safe that has a SAP allocation on staging
2. Observe the updated header widget for safe tokens
3. Open the app on prod or with a safe without an allocation
4. Observe the header widget looks as before

feat: Update header safe token widget for SAP [SW-586]

---

src/services/safe-wallet-provider/index.test.ts

This test was passing locally but not on CI, likely because of the fuzzy output from faker. If a hex string doesn't contain alphabetical characters, it passes.

Tests: fix safe-wallet-provider unit tests

---

src/hooks/useSafeTokenAllocation.ts

Follow-up on #4565
This changes the logic that calculates the total voting power for the safe header widget.
Our snapshot strategy includes all vesting contracts into the total voting power. This also includes contracts that haven't started yet so users would be able to vote with the SAP airdrop allocation. However since some users will not be able to claim their full allocation through the app it is safe to exclude this allocation.
1. Open the app with a Safe that has an SAP allocation that hasn't been claimed yet (but redeemed)
2. Observe not seeing that number in the header widget

fix: Exclude SAP allocation from voting power

---

src/features/myAccounts/hooks/useAllOwnedSafes.ts

Resolves unnecessary cache updates
We cache the owned Safes for a given address. This is used as an initial value for the sidebar, before the list of owned Safes is returned.
Currently, we are updating the cache if the aforementioned list is returned, as well as when the request address changes and **when the cache updates**. This results in an endless update to the cache, broadcasting across browser tabs.
This removes the unnecessary deps.: `address` and `cache`.
1. Open the same Safe in two different browser tabs, ensuring wallet connection with the same owner.
2. Create a new Safe, owned by the same owner.
3. Refresh both tabs and observe no `storage` event warning in the console.

fix: remove unnecessary deps. from `useAllOwnedSafes` cache

---

src/components/tx/SignOrExecuteForm/SignForm.tsx
src/components/tx/SignOrExecuteForm/__tests__/SignForm.test.tsx

Resolves [SW-363](https://www.notion.so/safe-global/Disable-add-to-batch-button-for-Dapps-1238180fe57380ac935aec33de026aef)
- Disables the `BatchButton` if there is an `origin` passed (it is a safe app or walletconnect)
1. Create a transaction through a safe app
2. Choose Sign
3. Observe Add to batch button is disabled
4. Create a transaction through the native UI
5. Observe there is an Add to batch button when signing and it is enabled

fix: Disable Add to Batch button for safe apps [SW-363]

---

src/services/tx/__tests__/safeUpdateParams.test.ts
src/services/tx/safeUpdateParams.ts

Upgrade transactions for 1.0.0 Safes included an empty transaction instead of the `setFallbackHandler` call.
Uses the Safe contract interface of the upgraded Safe's version instead of the current Safe's version.
This is correct as we first upgrade and change the masterCopy and then set the FallbackHandler.
- Create a 1.0.0 Safe on e.g. Gnosis Chain
- Upgrade it to 1.4.1 through our interface

fix: upgrade transactions for 1.0.0 Safes

---

src/components/common/ModalDialog/index.tsx
src/components/sidebar/SafeListRemoveDialog/index.tsx

Resolves #4379 
Allows passing `chainId` to `ModalDialog` such that we can pass the correct `chainId` in the `SafeListRemoveDialog`
- Open any multichain Safe that is deployed on at least 2 chains where one of the Safes is still counterfactual (not activated)
- Remove the counterfactual Safe while you have a Safe on another chain opened

fix: allow passing custom chainId to ModalDialog

---

src/components/common/AddressInput/index.test.tsx
src/components/common/AddressInput/index.tsx

Resolves #4378
Does not clear `AddressInput` on click when disabled.
- Rename a Safe in the Sidebar that has a Name in the current chain's addresbook.
- Click on the Address field
- Nothing should happen

fix: do not clear AddressInput when disabled

---

src/components/transactions/TxDetails/Summary/SafeTxHashDataRow/index.test.ts
src/components/transactions/TxDetails/Summary/SafeTxHashDataRow/index.tsx

Resolves #4613
For Safe versions <= 1.2.0, the domain separator typehash of the Safe contracts [does not include a `chainId`](https://github.com/safe-global/safe-smart-account/blob/v1.2.0/contracts/GnosisSafe.sol#L26):
```sol
bytes32 private constant DOMAIN_SEPARATOR_TYPEHASH = 0x035aff83d86937d35b32e04f0ddc6ff469290eef2f1b692d8a815c89404d4749;
```
For versions >= 1.3.0, [a `chainId` is included](https://github.com/safe-global/safe-smart-account/blob/v1.3.0/contracts/GnosisSafe.sol#L38):
```sol
bytes32 private constant DOMAIN_SEPARATOR_TYPEHASH = 0x47e79534a245952e8b16893a336b85a3d9ea9fa8c573f3d803afb92a79469218;
```
When calculating the domain hash, we do not take the contract version into account, calculating based on the newer domain separator typehash.
This conditionally includes the …

fix: don't use `chainId` when calculating domain hash of <=1.2.0

---

src/components/settings/DataManagement/FileListCard.tsx
src/components/settings/DataManagement/ImportDialog.tsx
src/components/settings/DataManagement/index.tsx
src/components/settings/DataManagement/useGlobalImportFileParser.ts
src/features/myAccounts/hooks/useAllOwnedSafes.ts
src/services/analytics/events/settings.ts
src/store/api/gateway/index.ts
src/store/visitedSafesSlice.ts

Resolves: https://www.notion.so/safe-global/Sidebar-pinned-safes-add-last-visited-to-the-export-data-14a8180fe573801bb256c388061a2305?pvs=4
Resolves: #4612
- Creates a new `Export Version` (v3) which includes the data the visitedSafes store
- also fixes a bug where the account list is not cleared when disconnecting a wallet.
- make sure the visitedSafes has been populated (by opening several safes).
- Export safe data using the data widget.
- Import the exported file into a private window. 
- See that the visitedSafes store has been populated. Choose to order the safes list by recently opened. See that the order is as expected.

Feat: include recently visited safes in import and export data [SW-594]

---

src/components/common/Mui/index.test.tsx
src/components/common/Mui/index.tsx
src/components/new-safe/create/steps/StatusStep/StatusStep.tsx

The `sx` prop wasn't passed down to MUI Box and Typography because it was overwritten by individual props.

Fix: pass sx prop to Box and Typography

---

src/features/myAccounts/hooks/__tests__/useAllSafesGrouped.ts
src/features/myAccounts/hooks/useAllSafesGrouped.ts
src/tests/builders/safeItem.ts

Resolves [SW-647](https://www.notion.so/safe-global/Refactor-Sidebar-components-1548180fe57380d08e77d05a3a121aec)
- Extracts the logic from `useAllSafesGrouped` into a function and tests it

refactor: Extract useAllSafesGrouped logic and write tests [SW-647]

---

src/features/myAccounts/hooks/__tests__/useAllSafes.test.ts
src/features/myAccounts/hooks/useAllSafes.ts

We should return safes sorted from `useAllSafes` after all otherwise there is a jump when pinning a safe while there are other safes in the same network
- Adds back the sorting of safes that was removed in #4641
1. Open the safe list
2. Pin a safe thats not the first one from its chain
3. Observe no jump

fix: Add sorting back to useAllSafes hook

---

src/components/sidebar/SafeListRemoveDialog/index.tsx

Resolves #4611
- Removes the counterfactual safe from the `undeployedSafes` store as well as from the `addedSafes` store.
- If the safe being removed is the currently opened safe, redirect to the accounts page.
- Create a counterfactual safe
- it should be possible to remove the safe from the context menu of the CF safe in the sidebar.
- If the CF safe being removed is currently opened, redirect to the accounts page.

Fix: allow removing counterfactual safes from safe list

---

src/components/transactions/TxDetails/TxData/DecodedData/MethodDetails/index.tsx
src/components/transactions/TxDetails/TxData/DecodedData/index.test.tsx
src/components/transactions/TxDetails/TxData/DecodedData/index.tsx

Resolves [SW-435](https://www.notion.so/safe-global/Display-raw-fallback-data-12f8180fe57380fc941cd73042bb0837)
- Removes the `isFallback` condition and instead shows `HexEncodedData` additionally when there are no parameters
- Case from https://github.com/safe-global/safe-wallet-web/pull/4260 is still covered
1. Open a transaction where the method name is there but no parameters
2. Observe it displays Hex encoded data instead of nothing

fix: Show raw data if decodedData doesn't contain any parameters [SW-435]

---

src/components/common/CheckWallet/index.test.tsx
src/components/common/CheckWallet/index.tsx

Resolves #4636 
- Also checks for `safeLoaded` when evaluating if the sdk exists or not in `CheckWallet` since the sdk won't exist if there is no safe opened
This should not break existing behaviour for transaction related buttons
1. Go to the global preferences page
2. Activate notifications
3. Observe the Save button is enabled

fix: CheckWallet sdk only if safe is also loaded

---

next-env.d.ts
src/components/sidebar/WatchlistAddButton/index.tsx

Reverts change introduced in https://github.com/safe-global/safe-wallet-web/pull/4657
- Reverts the naming of the read-only button in the sidebar to "Add read-only" instead of "Add as Read-only"
1. Open a Safe without a wallet connected
2. Observe the button in the sidebar says "Add read-only"

fix: Revert add read-only button naming

---

src/components/dashboard/SafeAppsDashboardSection/__tests__/SafeAppsDashboardSection.test.tsx
src/hooks/__tests__/useRankedSafeApps.test.ts
src/hooks/safe-apps/useRankedSafeApps.ts

Resolves [inconsistent display of featured Safe Apps on dashboard](https://5afe.slack.com/archives/C03CQ5ABLQM/p1733926283956939)
We display Safe Apps on the dashboard by ranking (the amount of times an App is opened) and whether they are pinned. This does not take into account whether they are featured.
This updates the ranking of Safe Apps to put any which are featured in the initial position(s). Thereafter are only (ranked|) pinned Apps, and the "Explore" card.
Open the dashboard on a network which has featured Safe Apps and observe featured Apps at the beginning of the list on the dashboard.

fix: rank featured Safe Apps first on dashboard

---

src/components/common/Mui/index.tsx

Border color wasn't properly passed to a Box because of the prop order.
I've also added omitBy to exclude unnecessary undefined properties passed to sx.

Fix: box border color in tx details

---

src/features/counterfactual/hooks/usePendingSafeNotifications.ts

Fixes [issue found in the release](https://github.com/safe-global/safe-wallet-web/pull/4667#issuecomment-2545810281)
- Calls `refetch` on the RTK query for all owned safes when receiving a `SafeCreationEvent.INDEXED`
1. Create a safe with the pay later option
2. Activate the Safe
3. Open the Sidebar
4. Observe there is no "read-only" chip next to the safe item

fix: Refetch owned safes after deployment

---

src/components/settings/RequiredConfirmations/index.tsx
src/components/tx-flow/flows/RemoveOwner/ReviewRemoveOwner.tsx
src/components/tx/confirmation-views/SettingsChange/__snapshots__/SettingsChange.test.tsx.snap
src/components/tx/confirmation-views/SettingsChange/index.tsx
src/components/tx/confirmation-views/__snapshots__/ConfirmationView.test.tsx.snap

Resolves  a comment by Franco:
```
minor issue
There is a ticket where we changed signer/signers depending on if there was more than 1 signer.
There is the situation where if a user is removed from a safe with 2 owners, the ending result should say "1 out of 1 signer" but it still says signers:
- Have a safe with 2 owners
- Remove one
- In the review step, just before executing, see the wording
```

Fix: signer vs plural signers

---

src/features/swap/hooks/__tests__/useIsExpiredSwap.test.ts
src/features/swap/hooks/useIsExpiredSwap.ts

Resolves #4650
- If the `validUntil` value is too far in the future (larger than a custom MAX_TIMEOUT value) we use MAX_TIMEOUT instead for the setTimeout value
1. Create a limit order swap that expires far in the future (25 days+)
2. Observe no expired label
3. Create a limit order that expires not so far in the future (< 25 days)
4. Observe no expired label
5. Create a limit order that expires short in the future
6. Observe the expired label shows up after it is expired

fix: Cap max expiry for setTimeout in useIsExpiredSwap

---

src/features/swap/helpers/data/stablecoins.ts

Resolves #4649.
Top stable coins on Base, data from https://basescan.org/tokens

Fix: add Base stablecoins for swaps

---

src/components/new-safe/create/logic/index.test.ts
src/components/new-safe/create/logic/index.ts
src/components/new-safe/create/steps/ReviewStep/index.tsx
src/features/counterfactual/ActivateAccountFlow.tsx
src/services/tx/__tests__/relaying.test.ts
src/services/tx/relaying.ts
src/services/tx/tx-sender/__tests__/ts-sender.test.ts
src/services/tx/tx-sender/dispatch.ts

Resolves inconsistent relays on Arbitrum
When relaying, a `gasLimit` can be optionally provided in the request. If provided, [a 150k buffer is added to it](https://github.com/safe-global/safe-client-gateway/blob/b7640ed4bd7416ecb7696d21ba105fcb5af52a10/src/datasources/relay-api/gelato-api.service.ts#L62-L75) for the Gelato execution overhead. If none is provided, Gelato estimates this on our behalf and no buffer is added.
This explicitly provides the `gasLimit` to relay requests (if present), otherwise manually estimates it if none is provided.
Ensure relay attempts do not fail (particularly on Arbitrum) for the following cases, and that the `gasLimit` is present in each `POST` request to the `/v1/chains/:chainId/relay`:
1. Safe creation/activation - uses estimation from UI
2. Bulk …

fix: always estimate relay `gasLimit`

---

Dockerfile

With the change to yarn v4 we need to slightly adjust the Dockerfile as the deploying an image to docker.hub was failng.
Resolves #
- network-timeout is now httpTimeout
- there is no need for global node-gyp as yarn uses whatever is specified in the package
sidenote: `yarn global` no longer works. It's not something yarn wants to do. https://yarnpkg.com/migration/guide#use-yarn-dlx-instead-of-yarn-global

Chore: generating docker image was failing

---

.github/workflows/code-review-gpt.yml

Chore: fine-tune AI review prompt

---

src/hooks/useTransactionType.tsx

We weren't displaying Safe App info in the queue/history due to a regression. Safe App txs had default icons and names.
Before this PR:
After:

Fix: display Safe App icon and name in history

---

.gitignore
apps/web/.gitignore
apps/web/src/components/transactions/TxDetails/TxData/MigrationToL2TxData/index.tsx

Upgrading a Safe from 1.3.0 to 1.4.1 breaks the Migration decoding
Less strict by ignoring the to address when decoding `migrateToL2` transactions.
Open e.g. [this transaction](https://app.safe.global/transactions/tx?safe=aurora:0x72a4dCE2C0d068541A3890fC0B968D68A00F877e&id=multisig_0x72a4dCE2C0d068541A3890fC0B968D68A00F877e_0x6602b8ef9bc393b229bfd50033ce4f71581013979d37d56e0d707b8bd8df8a52)

fix: decoding of migrateToL2

---

apps/web/src/components/common/TokenIcon/index.tsx
apps/web/src/components/tx/confirmation-views/__snapshots__/ConfirmationView.test.tsx.snap

* Token icons from Coingecko are now `referrerPolicy="no-referrer"`
* I also made them larger (50x50) because they were too low-res (25x25)

Fix: larger coingecko icons

---

apps/web/src/features/myAccounts/components/AccountListFilters/index.tsx

It is not clear that the search bar can be used for filtering safe names, addresses, and chains all using the same input
Changes the placeholder text to explain what the search can be used for.

Feat(sidebar): change safe search placeholder text

---

package.json
src/components/common/Mui/index.tsx
src/components/tx/SignOrExecuteForm/SignForm.tsx
src/components/tx/SignOrExecuteForm/__tests__/SignForm.test.tsx
src/hooks/useTransactionType.tsx

* Restore the Batch button for Safe Apps (revert #4623)
* Fix: display Safe App icon and name in history (#4694)
* Fix: typography and box sx

Release 1.48.2

---

apps/web/src/components/tx/SignOrExecuteForm/SignerForm/index.tsx

Clicking directly on the address in the `SignerForm` copied the address instead of chosing the signer.
Disables copying the address in the `SignerForm`
- Create a nested Safe tx
- Try to choose a signer which is not in the address book and click on the address

fix(Nested signing): do not copy addresses in SignerForm

---

apps/web/src/services/push-notifications/firebase.ts

Fixes error message when Firebase is initialized:
> FirebaseError: Installations: Missing App configuration value: "projectId" (installations/missing-app-config-values).
[`apps/web/src/services/push-notifications/firebase.ts`](diffhunk://#diff-3be0086de4433400ec5c7c60f44c1230c7bc6da197c50edb0b8acbd480181378L22-R28): Added the `isFirebaseOptions` type guard function to ensure that the `FIREBASE_OPTIONS` object contains a `projectId`.
1. Clear `NEXT_PUBLIC_FIREBASE_OPTIONS_STAGING` in .env file
2. Load app while monitoring the dev console
3. Observe that the error message (see above) is not logged

fix: initialize Firebase only if `projectId` is present in options

---

apps/web/src/components/settings/ContractVersion/index.tsx
apps/web/src/features/multichain/utils/utils.ts
apps/web/src/services/tx/safeUpdateParams.ts
apps/web/src/utils/__tests__/chains.test.ts
apps/web/src/utils/chains.ts

We want to decouple the default Safe version when creating a Safe and when upgrading a Safe:
* for creation – from an env variable `NEXT_PUBLIC_SAFE_VERSION`
* for upgrades – from `chain.recommendedMasterCopyVersion`
Once we decide to set `recommendedMasterCopyVersion` to the same version as `NEXT_PUBLIC_SAFE_VERSION` (i.e. 1.4.1), we can remove this logic.

Fix: use recommendedMasterCopyVersion only for Safe upgrades

---

CONTRIBUTING.md

Add a tl;dr section with a disclaimer about airdrop farming.

Docs: update CONTRIBUTING.md

---

apps/web/src/components/common/MetaTags/index.tsx
apps/web/src/components/common/PageLayout/styles.module.css

Resolves #4434 
- Adds the `viewport-fit=cover` directive to the meta tags -> This moves the whole app up into the "Dynamic island" on iOS
- Adds a padding (for PWA only) to the header and main element to move them down again and adds a background so the content is not visible when scrolling
1. Open the app on mobile (iOS and Android and iOS with a device without the notch), add it as a PWA to your Home Screen and open it again
2. Scroll up and down
3. Observe nothing is visible above the header
4. Open the app on web
5. Scroll up and down
6. Observe the header is at the very top
7. Make sure it works both in landscape and portrait mode on mobile

fix: Adjust meta tag to fix PWA header position

---

.github/workflows/web-deploy-dev.yml
.github/workflows/web-deploy-production.yml
.github/workflows/web-tag-release.yml

The tag-release and prod-deployment jobs were running in the wrong folder after the move to a monorepo.

Chore: fix release jobs

---

apps/web/cypress/e2e/pages/batches.pages.js
apps/web/cypress/e2e/pages/create_tx.pages.js
apps/web/cypress/e2e/pages/sidebar.pages.js
apps/web/cypress/e2e/prodhealthcheck/swaps_history_2.cy.js
apps/web/cypress/e2e/regression/sidebar_5.cy.js
apps/web/cypress/e2e/regression/swaps_history_2.cy.js
apps/web/cypress/fixtures/txhistory_data_data.json
apps/web/cypress/support/e2e.js

Fix failing regression tests:
- Set en-US locale globally to keep consistency with CI/CD when running tests locally
- Update date formats in tx history tests
- Update expanded/collapsed element class and its relative method logic
- Update sign button element with data-testid
- Update tests steps

Tests: Fix regression tests

---

packages/store/package.json

Inconsistency with README
The `@safe-global/store` package's README states that the generation command is `generate-api`. This changes the command to match instead of `api-generate`.
Run `generate-api` command in `@safe-global/store` package and observe no error.

chore: rename API generation command

---

apps/web/package.json
apps/web/src/components/safe-apps/SafeAppSocialLinksCard/SafeAppSocialLinksCard.test.tsx
apps/web/src/components/safe-apps/SafeAppSocialLinksCard/index.tsx
yarn.lock

Resolves the lack of support for Telegram as a social media option for Safe Apps.
This PR adds an option for Safe Apps to include their Telegram ID in the social media section.
1. Navigate to the config service where social media options of Safe Apps are managed.
2. Check for the new option to add a Telegram ID.
3. Add a Telegram ID and verify that it is saved.
4. Navigate to the web app and check that the ID is displayed correctly.
5. Ensure there are no UI or functional issues with the existing social media options.
- [-] I've tested the branch on mobile 📱
- [-] I've documented how it affects the analytics (if at all) 📊
- [+] I've written a unit/e2e test for it (if applicable) 🧑‍💻

feat(Safe Apps): Add option for Safe Apps to include Telegram ID as a social media link

---

apps/web/src/components/tx/SignOrExecuteForm/SignOrExecuteForm.tsx
apps/web/src/features/tx-notes/TxNoteForm.tsx
apps/web/src/features/tx-notes/TxNoteInput.tsx
apps/web/src/features/tx-notes/encodeTxNote.ts
apps/web/src/features/tx-notes/index.tsx
apps/web/src/services/analytics/events/modals.ts

A follow-up on #4693.
Triggering the `Add tx note` on input change is firing too many times, so I'm changing it to fire only when you submit a tx with a note.
Also, we've adjusted the design as per internal feedback:
* GA event is moved to tx modal submit callback
* GA event is renamed to `Submit tx note` to differentiate it from the previous, incorrectly tracked, event
* I also renamed the `onSubmit` prop name to `onChange` for clarity
* Slight adjustments to the design
* Character limit is reduced to 60 to fit in the `origin` limit better + align with the size of the input.

Fix(Tx notes): fire analytics on tx submit + adjust design

---

apps/web/src/features/speedup/components/SpeedUpModal.tsx
apps/web/src/services/tx/tx-sender/dispatch.ts

Just a tiny lint fix – the `safeAddress` param wasn't used in `dispatchCustomTxSpeedUp`.

Refactor(Tx speed up): rm unused argument

---

apps/web/src/features/tx-notes/TxNoteForm.tsx

Resolves #4779.
* Disable tx notes for 1/X Safes
Notes cannot be added when doing an immediate execution in 1/X Safes because we propose the tx before a note is added and then it's impossible to overwrite it unless the tx is signed.
So for now, we're disabling notes for all 1/X Safes. A better solution will be done later in #4783.

Fix(Tx notes): hide for 1/X safes

---

apps/web/src/components/common/OnlyOwner/index.tsx
apps/web/src/components/settings/ProposersList/index.tsx

Resolves #4743 
- Adds a new HoC called `OnlyOwner` and uses it for the Add proposer button instead of the `CheckWallet` component
1. Open a Safe
2. Go to the Settings page
3. Connect with an owner
4. The Add proposer button is enabled
5. Connect with a different wallet e.g. spending limit beneficiary, proposer, nested safe owner, recoverer
6. Observe that the add proposer button is disabled

fix: Enable Add proposer button for owners only

---

apps/web/src/components/tx/confirmation-views/index.tsx

Resolves #4802
TWAP confirmation view is the same as the Swap one so it just needed an extra mapping.

Fix(Swaps): TWAP order decoding

---

apps/web/src/features/swap/components/SwapOrder/rows/SurplusFee.tsx

`executedFee` can be undefined and it was crashing the entire TWAP preview component.

Fix(TWAP): executedFee can be undefined

---

apps/web/src/services/security/modules/BlockaidModule/index.ts

We noticed that Blockaid wasn't working on Blast because we were limiting supported chains to a hardcoded list.
Since we already have a per-chain feature toggle for this, we don't need that list. This enables Blockaid on Blast.
Create a tx on Blast and check that Blockaid now works
Do the same on some other chain where tx scanning is enabled

Fix(Blockaid): pass chain id instead of chain name for Blast and others

---

apps/web/scripts/github/s3_upload.sh

Identical to https://github.com/safe-global/safe-docs/pull/680 and https://github.com/safe-global/safe-homepage/pull/541, this fix aims to drastically reduce deployment times to AWS.
The issue is solved by uploading files in parallel using the `&` operator. A limit of 20 threads has been added for more safety.

fix: upload build output to AWS using up to 20 parallel threads

---

apps/web/src/components/transactions/TxDetails/TxData/NestedTransaction/ExecTransaction/index.tsx
apps/web/src/components/tx/SignOrExecuteForm/__tests__/__snapshots__/SignOrExecute.test.tsx.snap
apps/web/src/components/tx/confirmation-views/useTxPreview.ts

Resolves #4840
It was a regression after #4783 (not live yet).
The `operation` field in a nested tx was BigInt and it wasn't working well with the tx preview endpoint. So I converted it to a number.
Also optimized the dependencies of useAsync in useTxPreview to avoid an infinite loop if a passed tx object is re-created.

Fix: nested tx preview

---

apps/mobile/src/components/SafeInput/SafeInput.stories.tsx
apps/mobile/src/components/SafeInput/SafeInput.test.tsx
apps/mobile/src/components/SafeInput/SafeInput.tsx
apps/mobile/src/components/SafeInput/styled.ts
apps/mobile/src/components/SafeInput/theme.ts
apps/mobile/src/components/SafeInput/utils.ts
apps/mobile/src/theme/tamagui.config.ts

It creates reusable SafeInput component.

feat: Create SafeInput component

---

.github/workflows/web-e2e-full-ondemand.yml
apps/web/cypress/e2e/pages/create_wallet.pages.js
apps/web/cypress/e2e/pages/sidebar.pages.js
apps/web/cypress/e2e/regression/multichain_network.cy.js
apps/web/cypress/e2e/regression/multichain_networkswitch.cy.js
apps/web/cypress/e2e/regression/multichain_setup.cy.js

Resolves #4850 
- Updated and enabled Polygon tests
- Increased timeouts where necessary
- Increased containers from 5 to 8 in speedup tests 
- Decreased full regression workflow timeout to 40 minutes

Tests: Update polygon tests

---

apps/web/package.json
yarn.lock

Ensures safe-deployments version used is the expected one
Set a explicit version for @safe-global/safe-deployments

chore(dependencies): set explicit version for @safe-global/safe-deployments

---

apps/web/src/components/tx-flow/flows/TokenTransfer/CreateTokenTransfer.tsx
apps/web/src/components/tx-flow/flows/TokenTransfer/__tests__/CreateTokenTransfer.test.tsx
apps/web/src/permissions/config.ts
apps/web/src/permissions/hooks/usePermission.ts

Resolves this bug report by @liliya-soroka:
> 1. The bug with defining the spending limits amount -
Steps;
> 2. add spending limits in a new safe
> 3. start the send funds and select spending limits
https://github.com/user-attachments/assets/28c115b8-c79e-4229-a6d0-80de589e61ba
> Current result: The amount is 0 undefined

Fix(Spending limits): check selected token

---

apps/web/src/components/transactions/TxDetails/index.tsx

Transactions proposed by delegates were previously not deletable because the proposer value was wrong.
* Create a tx as a proposer
* Delete that tx as a proposer

Fix(Proposers): allow deleting tx proposals

---

apps/web/cypress/e2e/happypath/recovery_hp_1.cy.js
apps/web/cypress/e2e/pages/create_tx.pages.js
apps/web/cypress/e2e/pages/messages.pages.js
apps/web/cypress/e2e/pages/spending_limits.pages.js
apps/web/cypress/e2e/prodhealthcheck/sidebar.cy.js
apps/web/cypress/e2e/regression/messages_offchain.cy.js
apps/web/cypress/e2e/regression/spending_limits_nonowner.cy.js
apps/web/cypress/e2e/regression/tx_notes.cy.js
apps/web/src/features/tx-notes/TxNote.tsx
apps/web/src/features/tx-notes/TxNoteInput.tsx

To increase our automation coverage, new Cypress tests were added for tx notes functionality.
- Added automation tests for tx notes
- Added data-testids where necessary 
- Minor refactoring

Tests: Add tx notes tests

---

apps/web/cypress.config.js
apps/web/cypress/support/e2e.js
apps/web/cypress/support/utils/wallet.js
apps/web/src/markdown/terms/version.ts

- Add cookies versions dynamically from versions.ts 
- Remove extra step for cookies acceptance
- Add outreach acknowledgement to session storage
- Limit wallet connect attempts to 20 

Tests: Add test improvements

---

apps/web/src/components/tx-flow/flows/ConfirmTx/ConfirmProposedTx.tsx
apps/web/src/components/tx-flow/flows/ExecuteBatch/DecodedTxs.tsx
apps/web/src/features/speedup/components/SpeedUpModal.tsx
apps/web/src/features/speedup/hooks/useSafeTransaction.tsx
apps/web/src/services/tx/__tests__/extractTxInfo.test.ts
apps/web/src/services/tx/extractTxInfo.ts
apps/web/src/services/tx/tx-sender/__tests__/ts-sender.test.ts
apps/web/src/services/tx/tx-sender/create.ts
apps/web/src/services/tx/tx-sender/dispatch.ts
apps/web/src/utils/transactions.ts

`extractTxInfo` had some unnecessary branching for various types of txs instead of just getting values as is from TransactionData.
The changes affect only confirming existing transactions.
* Confirm and execute an ETH transfer
* Confirm and execute an ERC20 transfer
* Confirm and execute a Settings change (e.g. add owner)
* Confirm and execute a swap

Refactor(Tx flow): simplify extractTxInfo

---

apps/web/src/components/settings/FallbackHandler/index.tsx
apps/web/src/components/settings/TransactionGuards/styles.module.css

A small CSS fix. Make the fallback handler display in the same way as modules and guards.
Before:
After:

Fix(CSS): fallback handler component styles

---

apps/web/src/components/transactions/TxListItem/ExpandableTransactionItem.tsx
apps/web/src/features/myAccounts/components/AccountItems/MultiAccountItem.tsx
apps/web/src/features/myAccounts/components/AllSafes/index.tsx
apps/web/src/pages/_app.tsx

Resolves the pesky "button cannot be inside a button" warning from React.
Plus, rename WebCoreApp to SafeWalletApp.

Refactor(Web): fix "button in button" warning

---

apps/web/src/config/routes.ts
apps/web/src/features/myAccounts/components/AccountsHeader/index.tsx
apps/web/src/features/myAccounts/components/AccountsNavigation/index.tsx
apps/web/src/features/myAccounts/styles.module.css
apps/web/src/features/organizations/components/OrgsList/index.tsx
apps/web/src/features/organizations/components/OrgsList/styles.module.css
apps/web/src/features/organizations/components/OrgsSidebarNavigation/config.tsx
apps/web/src/hooks/useIsOrganizationRoute.ts
apps/web/src/hooks/useIsSidebarRoute.ts
apps/web/src/pages/welcome/organizations.tsx

Resolves #4937 
- Adds a navigation on the accounts page to switch between accounts and orgs
- Creates a new page `/welcome/organizations` with the same navigation
- Adds an empty `Create organization` button
Compare with the designs

[Orgs] Create Org toggle

---

apps/mobile/src/components/NetworkBadge/NetworkBadge.tsx
apps/mobile/src/components/NetworkBadge/theme.ts
apps/mobile/src/features/ImportReadOnly/components/AvailableNetworks.tsx

https://www.figma.com/design/sRo9PST52xElbawgukeagI/New-Mobile-App?node-id=4453-19762&m=dev
Network display was cut off and in addition to this didn't follow the latest design changes:
Now it looks like this:
Resolves #
fixes #4929

fix(mobile): network badge was not following design

---

apps/web/scripts/generate-routes.js
apps/web/src/config/routes.ts
apps/web/src/features/organizations/components/OrgsCard/index.tsx
apps/web/src/features/organizations/components/OrgsCard/styles.module.css
apps/web/src/features/organizations/components/OrgsList/index.tsx
apps/web/src/features/organizations/components/OrgsSidebarNavigation/config.tsx
apps/web/src/features/organizations/components/OrgsSidebarNavigation/index.tsx
apps/web/src/hooks/useIsOrganizationRoute.ts
apps/web/src/pages/organizations/[orgId]/members.tsx
apps/web/src/pages/organizations/[orgId]/safeAccounts.tsx
apps/web/src/pages/organizations/[orgId]/settings.tsx

Resolves #4955
- Creates pages for org members, org settings and org safe accounts
- Adjusts `generate-routes.js` to handle dynamic routes
- Adds links to the org cards to go to the org dashboard
2. Go to the welcome org page
3. Click on a card
4. Observe seeing the org dashboard
5. Navigate around through the sidebar
6. Observe seeing pages for each route

feat: Add empty org pages, adjust route generation

---

apps/web/src/components/icons/OrganizationIcon.tsx
apps/web/src/features/myAccounts/components/AccountItems/styles.module.css
apps/web/src/features/organizations/components/AccountsList/index.tsx
apps/web/src/features/organizations/components/Dashboard/index.tsx
apps/web/src/features/organizations/components/MembersList/index.tsx

Resolves #4906
Adds empty states for Members and accounts widgets on the orgs dashboard
Also adds the orgs list with Orgs populated (using owned safes for now)

feat(Orgs): empty members and accounts components for Orgs dashboard

---

apps/mobile/src/components/SafeBottomSheet/SafeBottomSheet.tsx

The default ScrollView component is not accomodating for the fact that it is rendered inside of a scrollView. Because of this when one had a lot of networks they were hiden at the end of screen. Using the exported ScrollView from bottomSheetModal fixes this. 
Resolves #4931
Magic
1. Try to import eth:0x55d93DF21332615D48EA0c0144c7b1D176F3e7cb (the safe exist on 16 networks)
2. go to the home page
3. try to switch network and select Base sepolia ( end of the list)

fix(mobile): cannot select last networks in multichain safes

---

.github/workflows/mobile-dev-release.yml
apps/mobile/app.config.js
apps/mobile/docs/release-procedure.md
apps/mobile/eas.json

This PR makes it possible to release a dev version of the app on new PRs that touch the files inside `apps/mobile` or `packages`
Resolves #
Makes it easier for QA to test changes/bug fixes
Note:
One problem with android is that the dev mobile app is in a draft status. As such we can't automatically publish the releases on the internal lane. The releases are pushed to app store, but then need to be manually distributed.

ci(mobile): Make mobile dev releases on a new PR

---

apps/mobile/src/app/import-signers/index.tsx
apps/mobile/src/features/ImportPrivateKey/ImportPrivateKey.container.tsx
apps/mobile/src/features/ImportPrivateKey/ImportPrivateKey.test.tsx
apps/mobile/src/features/ImportPrivateKey/components/ImportError/ImportError.tsx

The MVP supports only private key import. Removed seedphrase from the text.
Resolves #4959 
Removes the text
Go to Import a signer- > no seedphrase should be mentioned
Go to the next screen- > no seed phrase should be mentioned
Import incorrect signer -> no seedphrase should be mentioned

fix(mobile): wrong text for on import screens

---

apps/web/src/features/organizations/components/OrgsCard/index.tsx
apps/web/src/features/organizations/components/OrgsCard/styles.module.css
apps/web/src/features/organizations/components/OrgsList/index.tsx
apps/web/src/features/organizations/components/OrgsSidebar/index.tsx
apps/web/src/features/organizations/components/OrgsSidebarNavigation/config.tsx
apps/web/src/features/organizations/components/OrgsSidebarSelector/index.tsx
apps/web/src/features/organizations/components/OrgsSidebarSelector/styles.module.css
apps/web/src/pages/organizations/[orgId]/members.tsx

Resolves #4976
- adds the org selector to the orgs sidebar
- allows switching between orgs in the list.
- shows an overview of the currently selected org
- the dropdown contains buttons to create a new org and go to the orgs list.

feat(Orgs): Add org selector dropdown to orgs sidebar

---

apps/web/src/features/organizations/components/Members/index.tsx
apps/web/src/features/organizations/components/MembersList/EmptyMembers.tsx
apps/web/src/pages/organizations/[orgId]/members.tsx

Resolves #4956 
- Adds a new component `EmptyMembers` and `OrganizationMembers` and displays them on the member page
1. Open an organization and navigate to the members page
2. Observe the empty members view

Feat(Orgs): Add empty members view

---

apps/web/src/components/tx/security/tenderly/index.tsx

Resolves the issue: #4042. The title appeared smaller than the subtitle.
I have added the variants body1 to title and body2 subtitle. 
1) Go to a pending transaction
2) Click 'Confirm'
3) Click 'Simulate' in transaction checks block
4) See the alert on the right side
PS: The bold text in the subtitle was just for testing as i could not get to see the error message in the local host.

Fix(Simulation): change the error styling

---

apps/web/src/components/common/ProgressBar/styles.module.css
apps/web/src/components/tx-flow/common/TxStatusWidget/styles.module.css

Resolves the issue: #3876. The progress bar and the checklist icons color in the light mode are fixed.
I have added the conditional rendering of the variable color as per the theme. Earlier in both the themes the color name was but , the color values defined in the var.css were different. I added conditions in css so that the required color is used.
Go to a new transaction screen and see the status bar above the transaction card header and the transaction status on the right.
now both the things are renders with the required color.

Fix(Tx flow): progress bar color

---

apps/mobile/.env.development
apps/mobile/README.md

The PR to run the e2e tests on expo changed the way we deal with the firebase service file and this had to be reflected in the README
Resolves #
Makes it easier to run the app for the first time.
Explains better what is needed
- follow the guide on a clean repo clone

docs(mobile): update getting started steps

---

apps/web/src/features/organizations/components/OrgsList/index.tsx
apps/web/src/features/organizations/components/OrgsSidebarSelector/index.tsx

Resolves #5022
- Fetches all orgs for the orgs selector and displays them
1. Open an org
2. Observe the correct name showing in the selector
3. Click on the selector
4. Observe the rest of your orgs

Fix(Orgs): Fetch orgs and display them in the selector

---

.github/workflows/mobile-dev-release.yml
.github/workflows/mobile-e2e.yml

We were creating new releases on every PR - this was confusing as we were getting several builds served and it was not clear what features were available in the release. Now we only release when we merge into dev or if we set the “mobile-dev-release” label on a PR.
E2E tests are now going to run once daily or when we specify the mobile-e2e-label
Reduces the amount of builds and e2e tests we run on CI.
#4973

ci(mobile): restrict when we release and test

---

apps/web/src/features/organizations/components/Dashboard/DashboardInvite.tsx
apps/web/src/features/organizations/components/OrgsCard/index.tsx
apps/web/src/features/organizations/components/OrgsList/index.tsx

Resolves #5008
- adds the non functional component.
- accepting, declining, and linking to the detailed invite will come in a separate PR
- go to the orgs list.
- see that the org invite matches the designs

Feat(Orgs): add invite component to the orgs list

---

apps/web/src/features/organizations/components/Dashboard/DashboardInvite.tsx
apps/web/src/features/organizations/components/OrgsCard/index.tsx
apps/web/src/features/organizations/components/OrgsList/index.tsx

Resolves #5008
- adds the non functional component.
- accepting, declining, and linking to the detailed invite will come in a separate PR
- go to the orgs list.
- see that the org invite matches the designs

Feat(Orgs): add org invite component to orgs list

---

apps/mobile/package.json
apps/mobile/src/components/SafeTab/SafeTab.tsx
apps/mobile/src/components/SafeTab/SafeTabBar.tsx
apps/mobile/src/components/SafeTab/theme.ts
apps/mobile/src/features/AccountsSheet/MyAccounts/MyAccountsFooter.tsx
apps/mobile/src/features/Assets/components/AssetsHeader/AssetsHeader.tsx
apps/mobile/src/features/Assets/components/AssetsHeader/styles.ts
apps/mobile/src/features/Assets/components/Balance/Balance.tsx
apps/mobile/src/features/Assets/components/Navbar/Navbar.tsx
apps/mobile/src/features/Assets/components/Navbar/theme.ts
apps/mobile/src/theme/tamagui.config.ts
yarn.lock

Without this:
with this:
We had some transparent backgrouds. Now we apply a theme around those elements.

fix(mobile): navbar, tabs had transparent backgrounds

---

apps/mobile/src/components/Dropdown/sheetComponents.tsx

Enabling the BlurView on android with the experimentalBlurMethod={'dimezisBlurView'} params causes issues on android. I’ve reported the bug here. Until it is resolved or we find a workaround we can’t use BlurView on android: https://github.com/expo/expo/issues/34367
If we have any blurred view on android modal screens no longer work as expected. 
Android builds are now again usable
Resolves #
Play around with the android build

fix(mobile): android not able to open screen

---

apps/mobile/package.json
apps/mobile/src/components/SafeBottomSheet/SafeBottomSheet.tsx
apps/mobile/src/features/AccountsSheet/AccountsSheet.container.tsx
apps/mobile/src/features/AccountsSheet/MyAccounts/MyAccountsFooter.test.tsx
apps/mobile/src/features/AccountsSheet/MyAccounts/MyAccountsFooter.tsx
yarn.lock

When the list of safes was big one was not able to scroll inside of it.
Resolves #
fixes #4972
🪄 
There were a couple of gotchas. The Sheet doesn't automatically account for safe areas. So we had to apply an inset on the top, because previously we were behind the notch. We tried to go around this by using the snap point and setting the laste one at 90%, but this doesn't work with dynamic resizing. There is a bug in bottom-sheet in combination with react-native-animated. Bottom sheet is ignoring the max snap point. So, by setting the correct inset we can expand the sheet to 100% and the content will still be visible. Then we had to take the inset bottom in account. By relying on some random padding we were making the layout unpredictable. According to the docs of bottom shett it should …

fix(mobile): couldn’t properly scroll in sheet

---

apps/web/src/components/settings/NestedSafesList/index.tsx
apps/web/src/components/sidebar/NestedSafesButton/index.tsx
apps/web/src/components/sidebar/SafeListContextMenu/index.tsx
apps/web/src/hooks/useParentSafe.ts

Resolves https://github.com/safe-global/safe-client-gateway/issues/2323
This hides Nested Safes behind a targeted feature (`TARGETED_NESTED_SAFES`) but coniditonally rendering specific elements:
- `NestedSafesList` in setup settings
- `NestedSafesButton` in sidebar header
- `MenuItem` in `SafeListContextMenu` of drawer
Note: in all three of the above, the relevant Nested Safe data fetching has also been disabled to prevent the unnecessary request. `useParentSafe` has also been disabled in accordance with the flag in a similar fashion.
Open a targeted Safe and observe the feature present in the sidebar, drawer and settings. It should be possible to view, create and open Nested Safes with a breadcrumb visible in children. The feature should also be "unlocked" across non-targeted Safes. …

fix: hide Nested Safes behind targeted feature flag

---

apps/web/src/components/common/NestedSafeBreadcrumbs/index.tsx

Resolves #5038
Should the resolution be that of mobile, addresses present in the Nested Safe breadcrumbs are now truncated.
Open a Nested Safe on mobile and observe the addresses truncated. (The name from the address book takes precendence.)

fix: truncate breadcrumb addresses on mobile

---

apps/web/src/features/multichain/hooks/__tests__/useSafeCreationData.test.ts
apps/web/src/features/multichain/hooks/useSafeCreationData.ts
apps/web/src/features/safenet/config/constants.ts

Resolves https://github.com/safe-global/safenet/issues/399
In the sidebar, adding a new network for an existing Safenet-enabled account is now possible.
Adding a new chain for a Safenet-enabled accounts should now display the modal window with the networks dropdown instead of displaying an error.

Feat(Safenet): Add new networks for Safenet-enabled accounts

---

apps/web/next-env.d.ts
apps/web/src/features/organizations/components/AddMembersModal/index.tsx
apps/web/src/features/organizations/components/Members/InvitesList.tsx
apps/web/src/features/organizations/components/Members/index.tsx
apps/web/src/features/organizations/components/OrgsList/index.tsx
apps/web/src/features/organizations/components/OrgsSettings/index.tsx
apps/web/src/features/organizations/components/OrgsSidebarNavigation/index.tsx
apps/web/src/features/organizations/components/OrgsSidebarSelector/index.tsx
apps/web/src/features/organizations/hooks/useCurrentOrgId.ts
packages/store/scripts/api-schema/schema.json
packages/store/scripts/openapi-config.ts
packages/store/src/gateway/AUTO_GENERATED/organizations.ts
packages/store/src/gateway/AUTO_GENERATED/transactions.ts

Partially Resolves #4957
- Creates an invite for a user after submitting the invite users modal.
- Displays an orgs invited members on the members page.
- Shows a resend button and status chip for members who declined an invite.
- On the members page click the invite members button.
- Add an address in the form, choose a role, and submit the form.
- On the members page, see that there is a new row in the invited members list for each invited address
Note: We currently do not have access to the invited members address so a placeholder address is shown instead. The design for this section will likely need to be changed to show all connected addresses for the user.

Feat(Orgs): send invites and show invited members

---

apps/web/src/components/common/SafeIcon/index.tsx
apps/web/src/features/myAccounts/components/AccountItems/MultiAccountItem.tsx
apps/web/src/features/organizations/components/AccountsList/index.tsx
apps/web/src/features/organizations/components/AddAccounts/FilteredSafesList.tsx
apps/web/src/features/organizations/components/AddAccounts/SafesList.tsx
apps/web/src/features/organizations/components/AddAccounts/index.tsx
apps/web/src/features/organizations/components/AddAccounts/styles.module.css
apps/web/src/features/organizations/components/SafeAccountList/EmptySafeAccounts.tsx

Resolves #5005
- Creates a new component `AddAccounts`
- Creates a new component `SafesList`
- Creates a new component `FilteredSafesList`
1. Create an org
2. Press the Add accounts button on the dashboard
3. Observe all your owned Safes showing up with checkboxes
4. Check and uncheck safes and multichain safes
5. Observe the state updates correctly
6. Press Cancel
7. The form should close

Feat(Orgs): Add Safe accounts form

---

apps/web/next-env.d.ts
apps/web/src/components/common/AddressInput/index.tsx
apps/web/src/features/organizations/components/AddAccounts/AddManually.tsx
apps/web/src/features/organizations/components/AddAccounts/FilteredSafesList.tsx
apps/web/src/features/organizations/components/AddAccounts/SafesList.tsx
apps/web/src/features/organizations/components/AddAccounts/index.tsx
apps/web/src/features/organizations/components/AddAccounts/styles.module.css
apps/web/src/features/recovery/components/RecoverySettings/ChooseRecoveryMethodModal.tsx

Resolves #5048
- Adds a form to manually add a safe account in orgs
1. Open an org
2. Add safe accounts
3. Press Add manually
4. Type in a safe address and chain id
5. Submit the form
6. Observe the safe appears in the list of safes and is checked
7. Observe the number in the Submit button updating

Feat(Orgs): Add safes manually for orgs

---

apps/web/src/features/organizations/components/Dashboard/DashboardInvite.tsx
apps/web/src/features/organizations/components/OrgsList/index.tsx

Resolves #5008
- Replaces the hardcoded invite list with data from the backend.
- Implements the `accept` and `reject` button functionality.
- Filters out invites from the list of orgs you are a member of.
- Invite a wallet to your org from the members page.
- switch to the invited wallet and sign in. (You may need to delete the previous auth cookie)
- go to `/welcome/organizations` and see that the invite is listed.
- Click `Accept`. The invite should be replaced by an entry in the list of organizations below.
- Clicking reject should remove the invite from the page

Feat(Orgs): show list of pending invites on the orgs list screen 

---

apps/web/src/features/organizations/components/OrgsSidebarNavigation/index.tsx

Duplicate nav items in the orgs sidebar
Uses the nav label as the list key.
- Load a route with the orgs sidebar.
- observe no console errors.
- when running locally, hot reloads will not cause duplicate items to appear in the sidebar list.

Fix(Orgs): duplicate nav items in orgs sidebar 

---

apps/web/src/features/myAccounts/components/AccountItems/MultiAccountItem.tsx
apps/web/src/features/myAccounts/components/AccountItems/SingleAccountItem.tsx
apps/web/src/features/myAccounts/components/SafesList/index.tsx
apps/web/src/features/myAccounts/hooks/useAllSafesGrouped.ts
apps/web/src/features/organizations/components/SafeAccountList/EmptySafeAccounts.tsx
apps/web/src/features/organizations/components/SafeAccountList/index.tsx
apps/web/src/features/organizations/components/SafeAccounts/OrgSafeContextMenu.tsx
apps/web/src/features/organizations/components/SafeAccounts/index.tsx

Resolves #5065
- Creates a new component called `SafeAccountList`
- Adjusts `SafesList`, `SingleAccountItem` and `MultiAccountItem` to take a new prop called `isOrgSafe`
- Adjusts render logic depending on `isOrgSafe`
1. Open an org
2. Go to the safe accounts view
3. Observe a list of owned safes rendering
4. Compare with the Design

Feat(Orgs): Create orgs safe accounts list view

---

apps/web/src/features/organizations/components/Members/InvitesList.tsx

Partially Resolves #4957
- allows user to remove invited accounts from the pending invites list.
- go to the members page.
- Invite an address to join the org.
- when the invited user appears in the list, click the delete icon on the right.
- the invited user should be removed from the list.
- The invited user should no longer see the invite in their orgs list.

Feat(Orgs): allow deletion of invited users

---

apps/web/src/features/organizations/components/AddMembersModal/index.tsx

Resolves [4982](https://github.com/safe-global/safe-wallet-monorepo/issues/4982)
- adds name to the add member form
- restricts the form to adding one member at a time.
- uses the updated types from the CGW
See that the add members modal matches the designs

Feat(Orgs): add name field to add member modal

---

package.json
yarn.lock

Pin a higher elliptic curve version of the package

chore(web): force higher elliptic version

---

apps/web/src/features/organizations/components/Members/InvitesList.tsx
apps/web/src/features/organizations/components/Members/index.tsx
apps/web/src/features/organizations/components/MembersList/index.tsx
apps/web/src/features/organizations/hooks/useMembersSearch.ts

Resolves #5100
- implements search on the members list.
NOTE: since names are not implemented yet on the backend, it searches with the member ID for now.
exact implementation is tbd so for no it only searches added members and not pending.
- Open an org and go to the members page.
- type in the search bar. 
- The members list should be updated
- Type the id of one of the members in the list.
- That member should be shown, and all other members should be filtered out.

Feat(Orgs): add search to members list

---

apps/web/src/components/common/WalletInfo/index.tsx

Currently there is no way to go from the signed in state to the signed out state. We should allow the user to be able to sign out.
- Call the sign out endpoint when disconnecting the connected wallet.
- Set the redux state to logged out.
- go to the orgs list page in the signed in state. you should see the list of orgs.
- Disconnect your wallet.
- You should see the signed out state of the orgs list

Feat(Orgs): sign out on disconnect wallet

---

apps/web/src/components/tx-flow/SafeTxProvider.tsx
apps/web/src/components/tx-flow/flows/SafeAppsTx/ReviewSafeAppsTx.tsx
apps/web/src/components/tx/security/blockaid/useBlockaid.ts
apps/web/src/components/tx/security/shared/TxSecurityContext.tsx
apps/web/src/services/security/modules/BlockaidModule/index.ts

We were passing the wrong `metadata.domain` to Blockaid API:
* For txs made via Safe Wallet itself, it should be `non_dapp`
* For Safe Apps and apps connected via WalletConnect – their URL

Fix(Blockaid): pass dapp origin

---

apps/web/src/features/organizations/components/AddAccounts/index.tsx
apps/web/src/features/organizations/components/SafeAccountList/index.tsx

The payload type for the add accounts request from the CGW is wrong.
- Use the correct type and add a todo to update the type from the CGW when it is fixed.
- also adds back in the empty state for the accounts page when the org has no accounts.
- Go to the accounts page of an org. 
- If there are no accounts added yet you should see the empty accounts component.
- Click the add accounts button, select a safe, and submit. See that the form submits succesfully, and the safe now appears in the accounts page.

Fix(Orgs): use correct format for add accounts request

---

.github/workflows/web-deploy-production.yml

Uploads the arhive tar and checkum to github release for easier reference.

ci(web): upload release assets to github release

---

apps/web/src/features/organizations/components/Dashboard/DashboardInvite.tsx
apps/web/src/features/organizations/components/Dashboard/DashboardMembersList.tsx
apps/web/src/features/organizations/components/Dashboard/index.tsx
apps/web/src/features/organizations/components/Members/InvitesList.tsx
apps/web/src/features/organizations/components/Members/index.tsx
apps/web/src/features/organizations/components/MembersList/index.tsx
apps/web/src/features/organizations/components/OrgsCard/index.tsx
apps/web/src/features/organizations/components/OrgsCard/styles.module.css
apps/web/src/features/organizations/components/OrgsList/index.tsx
apps/web/src/features/organizations/components/OrgsSidebarSelector/index.tsx
apps/web/src/features/organizations/hooks/useOrgMembers.tsx

Resolves #5111
- Extracts members fetch and filtering into a hook.
- Displays limited list of members on the dashboard (5 max)
- Allows adding members from the dashboard.
- Go to the Dashboard page.
- Ensure the org is not in the initial state (have some safes added)
- Check that the members list on the dashboard matches the designs.
- Check that you can add an org from the dashboard using the button at the bottom of the members list.

Feat(Orgs): Add members list to the dashboard

---

.github/workflows/web-deploy-production.yml

This will generate an attestation over the archive file. One can then verify that this archive was generated on github by using the `gh attestation verify PATH/TO/YOUR/BUILD/ARTIFACT-BINARY -R ORGANIZATION_NAME/REPOSITORY_NAME` command. 
More info on attestation here:
https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds

chore(ci): generate artifact attestation

---

apps/web/src/features/organizations/components/AddMembersModal/index.tsx

There is a console error when opening the add members modal:
`React does not recognize the `gridArea` prop on a DOM element. `
- Wraps the svg in a box and sets gridArea on that instead.
- Open the add members modal
- Observe no console error.

Fix(Orgs): do not set gridArea directly on a DOM element

---

apps/web/src/components/welcome/WelcomeLogin/WalletLogin.tsx
apps/web/src/features/organizations/components/OrgsList/index.tsx
apps/web/src/features/organizations/components/SignInButton/index.tsx
apps/web/src/services/analytics/events/organizations.ts
apps/web/src/services/analytics/events/overview.ts

Resolves #[4965](https://github.com/safe-global/safe-wallet-monorepo/issues/4965)
- Re-uses the connect/continue button from the welcome page.
- Removes some unused styles from that component
- Prompts user to sign in once wallet is connected.
- Adds tracking for the button.
- Changes the text on the orgs list page for when there is a no connected wallet vs connected wallet but not signed in.
- Open the orgs list page with no wallet connected
- A connect wallet button should be shown.
- Connected a wallet.
- A sign in button should be shown with the icon and name of the connected wallet, and the connected address, similar to the welcome page.
No connected wallet:
With connected wallet:

Feat(Orgs): Implement sign in button

---

apps/web/src/features/organizations/components/Dashboard/DashboardMembersList.tsx
apps/web/src/features/organizations/components/Members/InvitesList.tsx
apps/web/src/features/organizations/components/Members/index.tsx
apps/web/src/features/organizations/components/MembersList/MemberName.tsx
apps/web/src/features/organizations/components/MembersList/index.tsx
apps/web/src/features/organizations/hooks/useMembersSearch.ts

Partially Resolves https://github.com/safe-global/safe-wallet-monorepo/issues/4957#issue-2846012995
- Includes invited members in the search according to the [updated designs](https://www.figma.com/design/PeChIDi5UKPjf58IOChtET/Organizations?node-id=4229-25673&t=7u4n6iz9lfB4hBc1-1)
- Only display the name (for now the id) in the invites list.
- Extracts member name + icon into its own component
- On the members page, type in the search bar.
- If the text matches anything, the match will show.
- If it matches a member in both the invites and members table, both tables will be shown in the results.

Feat(Orgs): Update members search to include invited members

---

apps/web/src/components/common/TxModalDialog/styles.module.css

Pushes the tx dialog further down to make room for the temporary banner
1. Create a transaction
2. Observe the close button is visible

fix: Push tx dialog further down on the screen

---

apps/web/src/components/tx-flow/flows/TokenTransfer/CreateTokenTransfer.tsx
apps/web/src/components/tx-flow/flows/TokenTransfer/SpendingLimitRow/index.tsx
apps/web/src/permissions/config.test.ts
apps/web/src/permissions/config.ts
apps/web/src/permissions/getRolePermissions.test.ts
apps/web/src/permissions/getRolePermissions.ts
apps/web/src/permissions/hooks/usePermission.test.ts
apps/web/src/permissions/hooks/usePermission.ts

Fixes a **permission check bug** when creating a **spending limit transaction**.  
The current permission function **does not verify whether the connected wallet matches the spending limit beneficiary address**. As a result, the permission check incorrectly returns `true` if a spending limit exists for the selected token—regardless of the beneficiary.  
1. Open a Safe that has **spending limits** for multiple signers for tokens **A** and **B**.  
2. Connect a signer with a spending limit for token **B** and without a spending limit for token **A**.  
3. Go to the **"Send token"** form and select token **A**.  
4. The **spending limit option is incorrectly available** (showing a limit of 0).  
To address this issue:  
* **Introduced `CommonProps`** – a shared structure that contains Safe …

fix(permissions): check spending limits for connected wallet

---

apps/web/src/components/tx-flow/SafeTxProvider.tsx
apps/web/src/hooks/__tests__/useSafeNotifications.test.ts
apps/web/src/hooks/useSafeNotifications.ts
apps/web/src/hooks/wallets/useSelectAvailableSigner.ts
apps/web/src/services/contracts/__tests__/safeContracts.test.ts
apps/web/src/services/contracts/safeContracts.ts

Removes the l2 migration
- Add a network to a e.g. 1.3.0 L1 Safe
- Observe a warning about an unsupported masterCopy without any migration
- Create a Tx
- Observe no migration gets prepended
see #5156

feat(web): remove l2 migration

---

apps/web/src/hooks/__tests__/useSafeAddressFromUrl.test.ts
apps/web/src/hooks/loadables/useLoadSafeInfo.ts
apps/web/src/hooks/useSafeAddress.ts
apps/web/src/hooks/useSafeAddressFromUrl.ts

`useSafeAddress` was used throughout the app to get the current Safe address. Some places use `safeAddress` from Safe Info instead.
This hook reads directly from the URL params which violates the single source of truth principle and also it doesn't validate that the Safe actually exists.

Fix(Web): use only validated safe address

---

apps/web/src/services/analytics/gtm.ts

Part of #5159
Adds back the console log on non-prod environments whenever an analytics event is sent
2. Open the console
3. Navigate around
4. Observe console logs for GA events

Fix(Analytics): Console log GA events

---

apps/web/src/components/common/PageLayout/index.tsx

The popup is breaking tests, so we're changing it to only appear in production but not in dev.

Fix(Web): show security banner and popup only on prod

---

.yarnrc.yml
package.json

Initially, I was thinking of using lavamoat for this, but then discovered that lavamoat by default actually sets enableScripts to false, so it seemed like kind of unnecessary to drag lavamoat into this. Having this option set to false means that postinstall scripts from 3rd party packages won't automatically run. Yarn is warning us about this:
I'm not sure what the scripts are doing and initially thought that nothing is going to work without them, but it turns out that at least on my machine everything I testesd seems to work:
- starting the app in dev mode
- building the web app
- building the mobile app
- running tests on both web and mobile
- linting

chore(yarn): prevent postinstall by default

---

apps/web/cypress/support/utils/gtag.js

Follow up on #5164 
Since #5164 events are pushed directly to GA. We still push them into the dataLayer but with a slightly different structure. This PR adjusts the util function to select the event payload correctly.

chore(e2e): Select events from new dataLayer structure

---

apps/web/src/components/common/NetworkSelector/index.tsx
apps/web/src/pages/apps/open.tsx

Resolves #4980
In File _apps/web/src/components/common/NetworkSelector/index.tsx_
```
export const getNetworkLink = (router: NextRouter, safeAddress: string, networkShortName: string) => {
const isSafeOpened = safeAddress !== ''
const query = (
isSafeOpened
? {
safe: `${networkShortName}:${safeAddress}`,
}
: { chain: networkShortName }
) as {
safe?: string
chain?: string
safeViewRedirectURL?: string
appUrl?: string // Added this to the query
}
const route = {
pathname: router.pathname,
query,
}
if (router.query?.safeViewRedirectURL) {
route.query.safeViewRedirectURL = router.query?.safeViewRedirectURL.toString()
}
if (router.query?.appUrl) {
route.query.appUrl = router.query.appUrl.toString()
} // if present then appUrl should be populated
return route
}
```
yarn workspace …

fix(web): appUrl query was getting lost while switching network in safeApp 

---

apps/web/src/components/balances/AssetsTable/FiatBalance.tsx
apps/web/src/components/balances/AssetsTable/index.tsx
apps/web/src/components/common/FiatValue/FiatValue.test.tsx
apps/web/src/components/common/FiatValue/index.tsx
apps/web/src/components/dashboard/Assets/index.tsx

Resolves #5126 
Ensures that when a fiat conversion rate is missing, the UI displays `--` instead of `0`, preventing confusion about the balance. 
This PR updates key components responsible for displaying fiat values and introduces proper handling of missing conversion rates. It also adds new test cases to validate the changes.  
**Key updates**  
- **Handled missing fiat conversion rate** in a new component `FiatBalance` and use it in:
-  `AssetsTable` (Assets view)
-  `AssetRow` (Dashboard)
- **Updated `FiatValue` component** to support `null` values and display `--`.  
- **Added test cases** to ensure correct behavior for missing fiat conversion rates.  
1. Open a Safe that holds a token **without a fiat conversion rate**.  
2. The fiat value should display `--` instead of `0` in:  
- …

feat(Assets): mask fiat balance when missing conversion

---

apps/web/src/components/common/AddressInput/index.tsx

Resolves #5067
`In apps/web/src/components/common/AddressInput/index.tsx
`
The code change adds a dependency on currentChain?.chainId in the useEffect hook for the AddressInput component. This ensures that the input validation is re-triggered when the chain changes, preventing potential stale validation states across different blockchain networks.
```
useEffect(() => {
trigger(address)
}, [currentChain?.chainId, trigger, address])
```
- Switch between different blockchain networks in the application
- Verify that address validation works correctly after network changes
https://github.com/user-attachments/assets/3543c8c9-533f-493b-9e5d-13675f482373

fix(web): Updated re-verifying of address in new-safe/load when chain is switched fixes (#5067)

---

.github/workflows/web-deploy-dev.yml
.github/workflows/web-deploy-production.yml
apps/web/package.json
apps/web/scripts/integrity-hashes.cjs
yarn.lock

Resolves #5154
- Adds a new script called `integrity-hashes.cjs`
- Adds a dev dependency for `cheerio` in order to parse HTML
- When run it iterates over each file in the `out` directory, generates a sha-256 hash for each internal script and inserts the hash with the integrity attribute to the script element
- Runs this script for each PR deployment
1. Open the PR deployment
2. Inspect the DOM
3. Observe no errors in the console
4. Observe integrity hashes are added to the script elements

chore: Add script to generate SRI hashes

---

apps/web/src/components/transactions/TxDetails/TxData/NestedTransaction/ExecTransaction/index.tsx
apps/web/src/components/tx-flow/flows/SignMessageOnChain/ReviewSignMessageOnChain.test.tsx
apps/web/src/components/tx/SignOrExecuteForm/ExecuteForm.tsx
apps/web/src/components/tx/SignOrExecuteForm/SignForm.tsx
apps/web/src/components/tx/SignOrExecuteForm/SignOrExecuteForm.tsx
apps/web/src/components/tx/SignOrExecuteForm/__tests__/SignOrExecute.test.tsx
apps/web/src/components/tx/SignOrExecuteForm/__tests__/__snapshots__/SignOrExecute.test.tsx.snap
apps/web/src/components/tx/SignOrExecuteForm/index.tsx
apps/web/src/components/tx/confirmation-views/useTxPreview.ts
apps/web/src/hooks/__tests__/useValidateTxPreview.test.ts
apps/web/src/hooks/useValidateTxPreview.ts

- validates the decodedData of the transaction preview against the raw transaction data
- If it does not match it shows an error and disabled the sign and execute button
- Create different transactions
- No error should appear

Feat(web): validate tx preview

---

apps/web/src/config/securityHeaders.ts

Follow up #5159
- Removes `unsafe-inline` from script-src since the GTM script that was inlined before has been removed
- Removes `https://www.google-analytics.com` and `https://ssl.google-analytics.com` from script-src because nothing is loaded from those domains
2. Observe no errors in the console regarding CSP
3. Observe that GA events are still tracked

fix: Remove unsafe-inline and GA domains from CSP

---

apps/mobile/src/features/ConfirmTx/ConfirmTx.container.tsx

It changes the condition for showing the "sign" button in the mobile app. According to @katspaugh, a tx can have more signatures than the threshold, so we need to adjust the display condition.

Fix(mobile): show confirmation button if a tx has more signatures than threshold

---

apps/web/cypress/e2e/pages/swaps.pages.js

- Some Twap tests failed due to flakiness in setting input value. The updated method aims to fix it.
- Run Twap tests and observe outcome

Tests: Update set value method

---

apps/web/src/features/organizations/components/OrgsList/index.tsx

Small fix when signing in on the orgs list page. Previously it would try to fetch user info without the cookie which resulted in an empty orgs list after signing in.
- Skip the user info fetch if the user is not signed in
1. Go to the orgs list page
2. Sign in
3. Observe your orgs showing up without having to reload

Fix(Orgs): Update orgs list when signing in

---

apps/web/src/components/sidebar/NestedSafesPopover/index.tsx

Resolves #5149
The maximum height of what was only set to the list is now on the `Popover` of the Nested Safe list.
Ensuring the current Safe owns many Nested Safes, open the Nested Safe list in the sidbar on a small resolution. Observe the "Add Nested Safe" button still present on screen.

fix: prevent "Add Nested Safe" button being off-screen

---

apps/web/src/features/organizations/hooks/useOrgSafes.tsx

Resolves [#5231](https://github.com/safe-global/safe-wallet-monorepo/issues/5231)
- Sends an empty array to `useAllSafesGrouped` instead of undefined so that the fallback (added safes) is not used.
- Go to the accounts page for an org
- Refresh the page
- See that the added safes are not shown briefly before the page has finished loading.

Fix(Orgs): added safes are shown on the org accounts list

---

apps/web/src/features/myAccounts/components/AccountItems/SingleAccountItem.tsx

Resolves #5236
- Adds the missing `elementRef` to the list item
1. Open an org
2. Add a safe account
3. Observe the balance is visible

Fix(Orgs): Show balances for org safe accounts

---

apps/web/cypress/e2e/pages/create_tx.pages.js
apps/web/cypress/e2e/pages/owners.pages.js
apps/web/cypress/e2e/regression/tx_history_2.cy.js
apps/web/src/components/tx/DecodedTx/index.test.tsx

- Add automation tests to cover new advanced details functionality
- Replace waiter in owner replace button with 'should.be.enabled' check
- Run Cypress and jest tests and observe outcome

Tests: Add advanced details tests

---

apps/web/src/features/organizations/components/OrgsList/index.tsx

[5234](https://github.com/safe-global/safe-wallet-monorepo/issues/5234)
Shows the empty orgs list if no user account is found for the signed in wallet address.
- go to /welcome/organizations using a wallet with no account
- click connect and then sign in.
- You should be shown the "no orgs" state.

Fix(Orgs): show empty orgs list state when user account is not found

---

apps/mobile/src/app/_layout.tsx
apps/mobile/src/app/transaction-parameters.tsx
apps/mobile/src/components/CopyButton/CopyButton.tsx
apps/mobile/src/config/constants.ts
apps/mobile/src/features/ConfirmTx/ConfirmTx.container.tsx
apps/mobile/src/features/ConfirmTx/components/ConfirmationView/ConfirmationView.tsx
apps/mobile/src/features/ConfirmTx/components/ListTable/ListTable.tsx
apps/mobile/src/features/ConfirmTx/components/ListTable/index.ts
apps/mobile/src/features/ConfirmTx/components/ParametersButton/ParametersButton.tsx
apps/mobile/src/features/ConfirmTx/components/ParametersButton/index.ts
apps/mobile/src/features/ConfirmTx/components/confirmation-views/AddSigner/AddSigner.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/AddSigner/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/Contract/Contract.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/Contract/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/GenericView/GenericView.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/GenericView/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/RemoveSigner/RemoveSigner.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/RemoveSigner/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/SwapOrder/utils.tsx
apps/mobile/src/features/TransactionParameters/TransactionParameters.container.tsx
apps/mobile/src/features/TransactionParameters/components/TxParametersList/TxParametersList.tsx
apps/mobile/src/features/TransactionParameters/components/TxParametersList/formatters/arrayValue.tsx
apps/mobile/src/features/TransactionParameters/components/TxParametersList/formatters/singleValue.tsx
apps/mobile/src/features/TransactionParameters/components/TxParametersList/index.ts
apps/mobile/src/features/TransactionParameters/components/TxParametersList/utils.tsx
apps/mobile/src/features/TransactionParameters/index.ts
apps/mobile/src/hooks/useCopyAndDispatchToast/index.ts
apps/mobile/src/utils/transaction-guards.ts

It allows user to see the transaction parameters by clicking in the "View Parameters" button, at the transaction details.

Feat(mobile): create transaction parameters page

---

apps/web/src/features/organizations/components/UserSettings/index.tsx
apps/web/src/features/organizations/components/UserSettings/styles.module.css
apps/web/src/pages/user-settings.tsx

Resolves #5012
- Adds a new route for user settings
- Lists all currently connected wallets.
- go to /user-settings
- see that it matches the designs

Feat(Orgs): Add user settings page

---

apps/web/src/components/settings/FallbackHandler/index.tsx
apps/web/src/components/tx/security/blockaid/ContractChangeWarning.tsx
apps/web/src/components/tx/security/blockaid/index.tsx
apps/web/src/components/tx/security/shared/TxSecurityContext.tsx
apps/web/src/services/security/modules/BlockaidModule/index.ts
apps/web/src/services/security/modules/BlockaidModule/types.ts

Blockaid returns a simulation which we don’t use for anything other than balance changes.
Show the simulation results for transactions that make contract changes:
- Delegate call to update the mastercopy
- Changing signers or threshold.
- Changing Safe modules
Note: if the blockaid scan already shows that the tx may be malicious then don't show these additional warnings (there are already warnings in place). Only show the simulation results as a fallback if the transactions is otherwise marked as benign.
- Create a tx which updates the mastercopy of a safe. See that a warning is shown near the sign button
- Create a tx that changes the signer setup or threshold of a safe. See that the warning is shown.

Feat: show blockaid simulation results on tx confirmation screen

---

apps/web/src/features/organizations/components/Dashboard/index.tsx
apps/web/src/features/organizations/components/Members/index.tsx
apps/web/src/features/organizations/components/OrgsSettings/index.tsx
apps/web/src/features/organizations/components/SafeAccounts/index.tsx
apps/web/src/features/organizations/components/SignedOutState/index.tsx
apps/web/src/features/organizations/hooks/useOrgMembers.tsx

Resolves #5252
- Extracts `SignedOutState` into its own file
- Uses that component on every view if user is not signed in
1. Open an org
2. Disconnect your wallet
3. Navigate through each page
4. Observe the sign in view

Fix(Orgs): Add signed out state to every orgs view

---

apps/web/src/features/organizations/components/Dashboard/DashboardMembersList.tsx
apps/web/src/features/organizations/components/Dashboard/index.tsx

Resolves [5254](https://github.com/safe-global/safe-wallet-monorepo/issues/5254)
Set a limit of 5 for the accounts list on the dashboard
- Open the dashboard page for an org with more than 5 safes.
- Check that only 5 safes are displayed.
- Check that the full number of safes is displayed in the title count.

Fix(Orgs): display a max of 5 safes on the dashboard page

---

apps/web/src/features/organizations/components/AddAccounts/index.tsx
apps/web/src/store/authSlice.ts

Resolves #5140 
Resolves #5253
- Filters out elements starting with `multichain_` in the selectedSafes object
- Resets form state and search query when cancelling the form
1. Open an org
2. Go to the safe accounts page
3. Add account
4. Select multichain accounts
5. Observe the correct number is displayed in the submit form
6. Cancel the form
7. Reopen it
8. Observe the form state is reset

Fix(Orgs): Display selected safes number, reset form state on cancel

---

apps/web/src/features/organizations/components/AddMembersModal/index.tsx
apps/web/src/features/organizations/components/Dashboard/MembersCard.tsx

Resolves #5265
- Clicking the add members button on the members dashboard card will open the add member modal.
- Redirect to the members page when a member has been successfully invited.
- Go to the dashboard of a newly created org
- Click `Add members`
- The add members modal should open. On submission, you should be redrected to the members page so you can see the invited user in the list.

Feat(Orgs): allow adding users from fresh org dashboard

---

packages/store/src/gateway/cgwClient.ts

Resolves #5226 
- Adds the `/v1/auth/logout` endpoint to the list of routes where credentials should be included
1. Open an org
2. Disconnect your wallet
3. Observe the `access_token` cookie is deleted

Fix(Orgs): Send credentials when logging out

---

apps/web/src/components/common/EthHashInfo/SrcEthHashInfo/index.tsx
apps/web/src/components/common/PaperViewToggle/index.tsx
apps/web/src/components/common/ToggleButtonGroup/index.tsx
apps/web/src/components/tx/ConfirmTxDetails/TxDetails.tsx
apps/web/src/components/tx/ConfirmTxDetails/index.tsx
apps/web/src/components/tx/SignOrExecuteForm/SignOrExecuteForm.tsx

* Show the full `to` address with a blockie avatar
* Show name and icon in a chip above
* Add "Show more" to the `data` field
* Make the receipt taller to fit the nonce field at the bottom
* Add operation type (call or delegate call)

Feat(Signing UX): show full to address

---

apps/web/src/components/tx-flow/flows/UpdateSafe/UpdateSafeReview.tsx
apps/web/src/components/tx-flow/flows/UpdateSafe/index.tsx
apps/web/src/components/tx/ConfirmTxDetails/TxDetails.tsx
apps/web/src/components/tx/ConfirmTxDetails/index.tsx
apps/web/src/components/tx/ReviewTransaction/ReviewTransactionContent.tsx

Add a receipt step to the Safe upgrade flow.

Feat(Signing UX): add receipt to the UpdateSafe flow

---

apps/web/src/features/organizations/components/AddMembersModal/index.tsx
apps/web/src/features/organizations/components/Dashboard/AcceptInviteDialog.tsx
apps/web/src/features/organizations/components/Dashboard/DashboardInvite.tsx
apps/web/src/features/organizations/components/MembersList/MemberName.tsx
apps/web/src/features/organizations/components/OrgsCard/index.tsx
apps/web/src/features/organizations/components/OrgsSidebarSelector/index.tsx
packages/store/scripts/api-schema/schema.json
packages/store/src/gateway/AUTO_GENERATED/balances.ts
packages/store/src/gateway/AUTO_GENERATED/organizations.ts
packages/store/src/gateway/AUTO_GENERATED/transactions.ts
packages/store/src/gateway/AUTO_GENERATED/users.ts

Resolves #5260
- Updates RTK Queries and types
- Adds `AcceptInviteDialog` when a user accepts an invite to an org to provide their user name
- Displays the member name on the members page
1. Open an org
2. Observe member names are visible
3. Invite a wallet to your org and assign a name
4. Switch to that wallet and sign in on the orgs list page
5. Observe a pending invite
6. Accept the invite
7. Observe a dialog with your name prefilled
8. Submit with or without a name change
9. Observe the name is reflected in the org

Feat(Orgs): Display member names

---

apps/web/src/features/organizations/components/AddAccounts/SafesList.tsx

Resolves #5267 
In `apps/web/src/features/organizations/components/AddAccounts/SafesList.tsx`
Marks showPrefix prop in `<EthHashInfo />` component to false if its a multichain safe
1. Open Organizations (Create an organization if not already present)
2. Add Accounts to organization

Feat(Orgs): Dont show chain prefix for multichain safes (#5267)

---

apps/mobile/src/features/Assets/components/NFTs/NFTs.container.tsx
apps/mobile/src/features/PendingTx/utils.tsx
apps/mobile/src/hooks/useInfiniteScroll/useInfiniteScroll.ts
apps/mobile/src/hooks/usePendingTxs/index.ts

The `useInfiniteScroll` hook is duplicating the `list` data every time the useEffect is triggered. The reason why it is happening is because we do not check if the consumer component is really going to the next page or just refetching the list data again.
Now we're comparing the previous url of the data with the previous url of the list, if both are the same, we just set whatever is in the data, otherwise we concatenate the data with the previous data, just like before.
- This issue is only reproducible within the Signer functionality, since before we were not invalidating the pending transactions data.

Fix(mobile): infinite scroll cache invalidation duplicates the list data

---

apps/mobile/src/features/Assets/components/NFTs/NFTs.container.tsx
apps/mobile/src/features/ChangeSignerSheet/ChangeSignerSheet.container.tsx
apps/mobile/src/features/ConfirmTx/components/SignTransaction/SignTransaction.tsx
apps/mobile/src/features/ConfirmTx/hooks/useTxSigner/useTxSigner.ts
apps/mobile/src/features/PendingTx/utils.tsx
apps/mobile/src/hooks/useInfiniteScroll/useInfiniteScroll.ts
apps/mobile/src/hooks/usePendingTxs/index.ts
apps/mobile/src/services/tx/tx-sender/create.ts
apps/mobile/src/services/tx/tx-sender/sign.ts
apps/mobile/src/store/signersBalance.ts

We were using api-kit for signing transactions, which stop working some weeks ago due to the server being down. After talking to @iamacook he mentioned that we actually should be using CGW for signing transactions, since that is the reason it was designed for.
It removes the lazy query we were using and uses the `addConfirmation` mutation instead.
- Add any wallet with a pending transaction
- go to your pending transactions
- click in the transaction that is pending
- click in the "Confirm" button
https://github.com/user-attachments/assets/27111040-055a-4eae-a2e8-b2a5ea4fe3ee

Fix(mobile): Use CGW for signing transactions

---

apps/web/src/features/organizations/components/MembersList/RemoveMemberModal.tsx
apps/web/src/features/organizations/components/MembersList/index.tsx
apps/web/src/features/organizations/hooks/useIsAdmin.ts

Resolves [5294](https://github.com/safe-global/safe-wallet-monorepo/issues/5294)
- Adds a confirmation dialogue when deleting members of an org
- Hides the member list action buttons when the current member is not an admin.
- Disables the delete button for the last admin in an org
- Open an org where you are an admin.
- You should see the option to delete other member of the org. If there are no other admins in the org, you should not be able to delete your own entry in the list.
- Click delete on one of the members. You should see a confirmation dialog.
- Clicking confirm should close the dialog and remove the chosen member from the members list.
- If you open the org as a non-admin, you should not be able to edit or delete the entries in the list.
Admin view:

Feat(Orgs): Allow deletion of members by Admins

---

apps/web/src/features/organizations/components/SafeAccounts/RemoveSafeDialog.tsx

Resolves #5279
- Updates the payload body for the delete safe request
1. Open an org with safe accounts
2. Delete a safe account
3. Observe the request not failing

Fix(Orgs): Update delete safe request payload type

---

apps/mobile/src/components/Identicon/Identicon.test.tsx
apps/mobile/src/components/Identicon/Identicon.tsx

Without this fix the identicons generated in iOS were different than the ones on web:
with this fix they are identical:
I’ve compared the generated data-uri on web and ios and they are 100% identical. So the problem can't be in the userd library: blockie. It must be something in expo-image that uses different kind of rendering for the data-uri. As a workaround I now generate the svg with bloSvg and use react-native-svg to render it directly. Seems to work fine.
The problem doesn't occur with every address. This one was different, but now should be the same:
eth:0xA77DE01e157f9f57C7c4A326eeE9C4874D0598b6
Open that safe both on mobile and in web and the blockies should match.

fix(mobile): blokie was not rendered correctly on iOS

---

apps/web/src/features/organizations/components/Dashboard/DashboardInvite.tsx

Resolves [5145](https://github.com/safe-global/safe-wallet-monorepo/issues/5145)
- Makes the org invite link to the org.
- go to the orgs list for a user who has been invited to an org. 
- Click on the org. It should link to the org dashboard.
- Clicking on invite or accept should complete the chosen action without triggering the link to the org dashboard.

Feat(Orgs): add link to org from invite card

---

apps/web/src/features/organizations/components/AddMembersModal/index.tsx
apps/web/src/features/organizations/components/MembersList/EditMemberDialog.tsx
apps/web/src/features/organizations/components/MembersList/index.tsx

Resolves #5312 
- Adds a new `EditMemberDialog` component
1. Open an org with members
2. Go to the members page
3. Edit one of them as an admin
4. Update their role and submit
5. Observe the role changing

Feat(Orgs): Edit member role

---

apps/web/src/features/organizations/components/Members/InvitesList.tsx
apps/web/src/features/organizations/components/Members/index.tsx
apps/web/src/features/organizations/components/SafeAccounts/index.tsx

partially Resolves [#5315](https://github.com/safe-global/safe-wallet-monorepo/issues/5315)
note: the admin page will be tackled separately once there are designs for it
For non admin users:
- Hides the add members button on the members page
- Hide the delete invited member button on the members page
- Hides the add accounts button on the accounts page
- open an org as a non admin user.
- Check that the buttons mentioned above are not visible
- Change to an admin user
- Check that the buttons are visible

Fix(Orgs): Hide buttons for non admins

---

apps/web/src/features/organizations/components/OrgsList/index.tsx
apps/web/src/features/organizations/components/OrgsSettings/index.tsx
apps/web/src/features/organizations/components/OrgsSidebarSelector/index.tsx
apps/web/src/features/organizations/hooks/useIsAdmin.ts
apps/web/src/features/organizations/hooks/useOrgMembers.tsx
apps/web/src/features/organizations/hooks/useOrgSafeCount.tsx
apps/web/src/features/organizations/hooks/useOrgSafes.tsx

Resolves #5319
- Uses `currentData` instead of `data` for all RTK Queries in Orgs
1. Open an org with safe accounts
2. Go to the safe accounts page
3. Disconnect your wallet
4. Connect and sign in with a different wallet thats not part of the org
5. Observe no safe accounts are visible

Fix(Orgs): Use currentData instead of data for fetching org data in RTK

---

apps/web/cypress/e2e/happypath_2/add_owner.cy.js
apps/web/cypress/e2e/happypath_2/proposers.cy.js
apps/web/cypress/e2e/happypath_2/swaps.cy.js
apps/web/src/services/private-key-module/index.ts

- Introduced a try-catch block to parse the typedData JSON string to allow catching of parsing errors.
- Added respective error messages
- Updated the method to use the parsed typedData for signing, ensuring that the correct structure is utilized when calling wallet.signTypedData.
- Re-enabled skipped tests in happy path that required signing

Tests: Enable data signing

---

apps/web/src/components/transactions/TxFilterForm/index.tsx
apps/web/src/utils/__tests__/tx-history-filter.test.ts
apps/web/src/utils/tx-history-filter.ts

Resolves #4942
For the incoming filter, the amount now must be specified in a decimal format (with zeroes) and not assume the default 18 decimals. This allows filtering by amounts for various tokens w/o specifying a token address.
* Open a Safe with incoming USDC transfers
* Filter by incoming with an amount with 6 trailing zeroes
* Filter for incoming ETH transfers with 18 zeroes

Fix(Tx history filter): incoming amount with decimals

---

apps/web/cypress/e2e/pages/create_tx.pages.js
apps/web/cypress/e2e/pages/sidebar.pages.js
apps/web/cypress/e2e/pages/swaps.pages.js
apps/web/cypress/e2e/prodhealthcheck/multichain_network.cy.js
apps/web/cypress/e2e/prodhealthcheck/tokens.cy.js
apps/web/cypress/e2e/regression/swaps.cy.js
apps/web/cypress/e2e/regression/swaps_2.cy.js
apps/web/cypress/e2e/regression/tokens.cy.js
apps/web/cypress/e2e/regression/twaps_history.cy.js

- Network selector is now can be accessed only with data-tested. Since it is not available on prod yet, some multi-chain tests are skipped.
- Updated steps in multi-chain tests to handle security modal.
- Removed domain condition in tests to always check ‘--’ in non-native tokens.
- Updated logic in swap/twap tests to handle confirm price impact modal.

Tests: Update cy tests 

---

apps/web/src/features/myAccounts/components/AccountItems/MultiAccountItem.tsx

Resolves #5257 
The tooltip component actually refs to its parent component the problem with the old code was that the tooltip was referring to this css component and was opening according to this component :
https://github.com/safe-global/safe-wallet-monorepo/blob/d793477e27d1cc60e31e99e564c8fd0370dfbad7/apps/web/src/features/myAccounts/components/AccountItems/MultiAccountItem.tsx#L265
Fix:
Now we are wrapping the Tooltip with the box component which was earlier inside the tooltip component so now it refers to `css.multiChains` which contains the network elements:
```
<Box className={css.multiChains}>
<Tooltip
title={
<Box data-testid="multichain-tooltip">
<Typography fontSize="14px">Multichain account on:</Typography>
{safes.map((safeItem) => (
<Box key={safeItem.chainId} sx={{ p: '4px …
```

Fix(Orgs/Web): network tooltip position issue fixed for multichain safes (#5257)

---

apps/web/src/config/securityHeaders.ts

Follow-up on #5201 
- Turns out GA still inserts an inline script to initialize the dataLayer with some configs which was being blocked
2. Observe no inline errors in the console
3. Click around
4. Events are sent to GA

fix: Add unsafe-inline to script-src CSP

---

apps/web/src/features/organizations/components/SafeAccounts/OrgSafeContextMenu.tsx

Resolves #5333
- Integrates the `EntryDialog` component into the orgs context menu
1. Open an org with safe accounts
2. Press the three-dot menu next to one
3. Choose Rename/Give name
4. Set a name and submit
5. Observe the name is visible

Fix(Orgs): Allow renaming safes in orgs

---

apps/web/src/features/organizations/components/Dashboard/DashboardInvite.tsx

Resolves #5337
- Adds the `invitedBy` value as an `EthHashInfo` to the pending invite card
1. Get invited to an org
2. Go to the orgs list page and sign in
3. Observe the address of the inviter is visible

fix: Show who invited you to their org

---

apps/web/src/features/organizations/components/SafeAccounts/index.tsx
apps/web/src/features/organizations/hooks/useMembersSearch.ts

Resolves: https://github.com/safe-global/safe-wallet-monorepo/issues/5255
Resolves: members search not working
- When no results are found from the search, display ` Found 0 results` instead of the no safes placeholder
- also fixes members search. Changes it so it searches by member name instead of member ID
1.
- go to the accounts page.
- type in the search bra untill there are no matching results
- see that there is a state for this case
2.
- Go to the members search.
- Type the name of one of the members in either of the two lists.
- Check that it filters the lists as expected.

Fix(Orgs): add not found state for accounts search

---

apps/web/src/features/organizations/components/Members/InvitesList.tsx
apps/web/src/features/organizations/components/MembersList/index.tsx

Resolves #5344 
- The table rawValue for the name column was still using the `member.user.id` instead of `member.name`
1. Open an org with a couple of members
2. Sort members by name
3. Members should be sorted alphabetically

Fix(Orgs): Update member name sort value

---

apps/web/src/components/common/NameInput/index.tsx

Resolves #5346
- Trims the input value in `NameInput` so that empty spaces are not allowed
1. Open an org
2. Add a member
3. Try adding empty spaces as the member name
4. Form should display an error and not let you submit

Fix(Orgs): Trim NameInput values

---

apps/mobile/src/app/_layout.tsx
apps/mobile/src/app/action-details.tsx
apps/mobile/src/app/transaction-actions.tsx
apps/mobile/src/components/EncodedData/EncodedData.tsx
apps/mobile/src/components/EncodedData/index.ts
apps/mobile/src/features/ActionDetails/ActionDetails.container.tsx
apps/mobile/src/features/ActionDetails/ActionsDetails.tsx
apps/mobile/src/features/ActionDetails/index.ts
apps/mobile/src/features/ActionDetails/utils.tsx
apps/mobile/src/features/ConfirmTx/components/ListTable/ListTable.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/Contract/Contract.tsx
apps/mobile/src/features/TransactionActions/TransactionActions.container.tsx
apps/mobile/src/features/TransactionActions/components/TxActionsList.tsx
apps/mobile/src/features/TransactionActions/index.ts
packages/store/src/gateway/types.ts

It create all the missing screens for the transaction actions.
- Go to any pending tx that has actions
- Click in the actions section
- You should be redirected to the actions list and inside of it, click in any of the item
- You should be redirected to the action details
https://github.com/user-attachments/assets/57bf4364-f2a1-406d-9d79-b071c094baeb

Feat(mobile): transaction actions flow

---

apps/web/src/features/organizations/components/OrgsSettings/index.tsx
apps/web/src/features/organizations/components/OrgsSidebarNavigation/config.tsx
apps/web/src/features/organizations/components/OrgsSidebarNavigation/index.tsx

Resolves #5315
- Disables all buttons on the settings page for non admins
- hides the settings page in the sidebar for non admins
- sign in to an org as a non member
- See that the settings page is not in the sidebar menu
- go to the settings page directly `/organizations/settings?orgId={orgId}`
- see that all the buttons are disabled

Fix(Orgs): Hide settings page for non admins

---

apps/web/src/features/organizations/components/MembersList/index.tsx

The chip was accidentally removed during a refactor in a previous PR
Adds the chip back in when a member in the invites list has declined the invite.
- Invite a user to an org
- decline the invite
- from the inviter wallet, view the pending invites list

Fix(Orgs): add declined chip back to invites list

---

apps/web/src/components/tx-flow/flows/NftTransfer/ReviewNftBatch.tsx
apps/web/src/components/tx-flow/flows/NftTransfer/index.tsx
apps/web/src/components/tx-flow/flows/RemoveGuard/ReviewRemoveGuard.tsx
apps/web/src/components/tx-flow/flows/RemoveGuard/index.tsx

Adds the new transaction receipt step to the following flows:
* NftTransferFlow
* RemoveGuardFlow
**Note**: I haven't been able to test it yet, because I'm missing a Safe that has the conditions for both flows (holds an NFT or has a guard defined).

feat(Signing UX): adds receipt step to NftTransferFlow + RemoveGuardFlow

---

apps/web/src/components/common/NetworkSelector/index.tsx
apps/web/src/pages/apps/open.tsx

Reverts #5081
Resolves #5350.
It broke the use case when you want to test an unlisted Safe App, e.g. running on localhost.

Revert "fix(web): appUrl query was getting lost while switching network in safeApp "

---

apps/web/src/features/organizations/components/AddAccounts/index.tsx

Resolves #5242
- Shows an error and keeps the dialog open
1. Open an org
2. Add a safe account
3. Try to add the same safe account again
4. Observe an error message

Fix(Orgs): Show error when trying to add same safe to org

---

apps/web/src/components/tx-flow/flows/AddOwner/index.tsx
apps/web/src/components/tx-flow/flows/CancelRecovery/index.tsx
apps/web/src/components/tx-flow/flows/ChangeThreshold/index.tsx
apps/web/src/components/tx-flow/flows/ConfirmBatch/index.tsx
apps/web/src/components/tx-flow/flows/ConfirmTx/index.tsx
apps/web/src/components/tx-flow/flows/NewSpendingLimit/index.tsx
apps/web/src/components/tx-flow/flows/NftTransfer/index.tsx
apps/web/src/components/tx-flow/flows/RecoverAccount/index.tsx
apps/web/src/components/tx-flow/flows/RejectTx/index.tsx
apps/web/src/components/tx-flow/flows/RemoveGuard/index.tsx
apps/web/src/components/tx-flow/flows/RemoveModule/index.tsx
apps/web/src/components/tx-flow/flows/RemoveOwner/index.tsx
apps/web/src/components/tx-flow/flows/RemoveRecovery/index.tsx
apps/web/src/components/tx-flow/flows/RemoveSpendingLimit/index.tsx
apps/web/src/components/tx-flow/flows/ReplaceOwner/index.tsx
apps/web/src/components/tx-flow/flows/SafeAppsTx/index.tsx
apps/web/src/components/tx-flow/flows/SignMessageOnChain/index.tsx
apps/web/src/components/tx-flow/flows/TokenTransfer/index.tsx
apps/web/src/components/tx-flow/flows/UpdateSafe/index.tsx
apps/web/src/components/tx-flow/flows/UpsertRecovery/index.tsx
apps/web/src/components/tx/ConfirmTxDetails/index.tsx
apps/web/src/services/analytics/events/modals.ts
apps/web/src/services/analytics/events/recovery.ts
apps/web/src/services/analytics/types.ts

Resolves #5283 
Add tracking for the following events:
* User checks the checkbox "I understand what I will sign ... "
* User clicks on external link to the article about how to perform basic transaction checks
* User navigates back or next on any transaction flow

feat(Signing UX): tracking

---

apps/web/src/features/organizations/components/AddAccounts/AddManually.tsx

Resolves https://github.com/safe-global/safe-wallet-monorepo/issues/5275#issuecomment-2724543297
- re triggers validation of the address input in the add account modal when the selected chain is changed.
- go to the add address modal. 
- Click add manually
- paste the address of a safe that exists on the currently selected chain. No validation error should be shown and the submit button enabled
- change the chain. A validation error should show and the submit should be disabled.

Fix(Orgs): re-trigger validation of safe address when chain id changes

---

apps/web/src/features/organizations/components/OrgsCreationModal/index.tsx

Resolves: Org creation button was changing size in it's loading state
- keeps the button size consistent when submitting the form.
- Also removes a console log and replaces it with an error message shown to the user.
- Open the org creation modal
- when the submit button is pressed, it should not jump or change size. The loading circle should show but the button size should be consistent.

Fix(Orgs): keep button size consistent when submitting

---

apps/web/src/features/organizations/components/AddAccounts/index.tsx
apps/web/src/features/organizations/components/Dashboard/MembersCard.tsx

Resolves [#5400](https://github.com/safe-global/safe-wallet-monorepo/issues/5400)
- diables the buttons for non admins
- adds tooltips to explain why
view the dashboard page as a non admin (normal member or invited member)
see that the add member and accounts buttons are disabled with a tootlip to explain why

Fix(Orgs): disable buttons on dashboard for non admins

---

apps/web/src/components/tx/confirmation-views/NestedSafeCreation/index.tsx

Resolves #5150
The identicon of the Nested Safe-to-be-created is now shown on the confirmation view of the transaction flow.
1. Open the flow to create a Nested Safe.
2. On the review screen, observe the identicon of the Nested Safe-to-be-created.

feat(Nested Safes): show identicon of Nested Safe-to-be-created

---

apps/web/src/components/tx-flow/flows/CreateNestedSafe/SetupNestedSafe.tsx

Resolves #5148
This add validation dependency of asset-to-fund amounts to the asset. When an asset is changed, the amount is revalidated.
1. Ensure a to-be-parent Safe has >1 asset of differing amounts: A and B.
2. Open the Nested Safe creation flow.
3. Select the token with smaller amount and enter an amount above that held, but below that of the other token
4. Change the token and observe the amount validation clearing.

fix(Nested Safes): trigger validation of Nested Safe asset on change

---

apps/web/cypress/e2e/smoke/nfts.cy.js

The preview NFT test is skipped , because the fetching metadata for the NFTs was turned off on the back-end, so the preview is not available for now
Resolves #
1. The test is skipped for now till we have more details 
1. run smoke nft tests
2. make sure that the text is skipped

Tests: skip NFT preview test

---

packages/store/src/gateway/cgwClient.test.ts
packages/store/src/gateway/cgwClient.ts

Resolves addition of `credentials` to every request
The `dynamicBaseQuery` of the store now only includes `credentials` for the following routes:
- `/v1/auth/*`
- `/v2/register/notifications`
- `/v2/chains/:chainId/notifications/devices/*`
Note: these will need to be adjusted should we require `credentials` on other routes, or if we restrict domains for the Client Gateway.
Interaction with the app should be as expected, and mobile registration for notifications should still work.

fix(CGW SDK): only include `credentials` for specific routes

---

apps/web/src/config/constants.ts
apps/web/src/hooks/useIsOfficialHost.ts

Display the Safe Wallet logo, as well as Terms and Privacy links in the footer for official IPFS deployments.
To detect such a deployment:
* We check the page host
* If it's one of the IPFS domains, get the version of the app
* Fetch the release notes for this version from our [IPFS repo](https://github.com/5afe/safe-wallet-ipfs/releases/tag/v1.53.0)
* If the current host matches the links in the release, it's an official deployment

Feat(web): detect official IPFS deployments

---

apps/web/src/features/spaces/components/MembersList/MemberName.tsx

Resolves #5433 
- Checks for the current member when rendering the member name and highlights them with `(you)`
1. Open an org
2. Go to the member list
3. Observe a `(you)` next to your member name

Fix(Orgs): Highlight current user in member list

---

apps/web/src/features/multichain/utils/utils.ts
apps/web/src/features/myAccounts/hooks/useAllSafesGrouped.ts
apps/web/src/features/spaces/components/AddAccounts/SafesList.tsx
apps/web/src/features/spaces/components/AddAccounts/index.tsx
apps/web/src/features/spaces/hooks/useSpaceSafes.tsx

Resolves #5425 
- Adds a new hook `useOwnedSafesGrouped` and uses that instead of `useAllSafesGrouped` within spaces
1. Create an undeployed safe
2. Observe it is listed under accounts
3. Add safe accounts
4. Observe the undeployed safe is not showing up in the list

Fix(Orgs): Only list owned accounts when adding to space

---

apps/web/src/features/spaces/components/Dashboard/DashboardMembersList.tsx

Resolves [#5400](https://github.com/safe-global/safe-wallet-monorepo/issues/5400)
- Hides the add members button in the members list if you are not an admin
- Go to the dashboard of a space where you are a non admin member
- If the members list is shown, it should not have a button for adding members.

Fix(Orgs): hide add members button on dashboard members list for non admins

---

apps/web/src/utils/wallets.ts

Ledger Live's WalletConnect peer name is `Ledger Wallet`, not just `Ledger`.

Fix(Signing UX v2): Ledger Live detection

---

apps/web/src/features/spaces/components/AddAccounts/index.tsx

Resolves https://github.com/safe-global/wallet-private-tasks/issues/7
- Checks the manual safe to be added against all safes instead of just the manually added ones
1. Open an org
2. Go to add safe accounts
3. Add safe manually thats already in the list
4. Observe no new entry and the existing entry is checked
5. Add a manual safe thats part of a multichain setup
6. Observe the correct multichain safe is checked and there is no duplicate

Fix(Orgs): Don't duplicate safes when adding manually

---

apps/web/src/components/transactions/HexEncodedData/styles.module.css
apps/web/src/components/tx-flow/common/TxLayout/styles.module.css
apps/web/src/components/tx/ConfirmTxDetails/index.tsx

Adjust some margins and the acknowledgment wording to fit in one line.

Fix(Signing UX): adjust CSS and wording

---

apps/web/src/features/spaces/components/SpaceSettings/DeleteSpaceDialog.tsx
apps/web/src/features/spaces/hooks/useSpaceSafes.tsx

Resolves https://github.com/safe-global/wallet-private-tasks/issues/8
- Uses the `space` parameter that is passed to the dialog instead of using the `useCurrentSpaceId` hook which doesn't work outside of a space e.g. on the space list view
1. Go to the space list view
2. Delete a space from there
3. Observe a success message

Fix(Orgs): Use correct space id when deleting space

---

apps/web/src/components/tx/ReviewTransaction/ReviewTransactionContent.tsx

Allow to continue to the transaction receipt step if connected wallet is not an owner of the Safe.

fix(Signing UX): allow non-owner execution in transaction review

---

apps/web/src/components/transactions/HexEncodedData/styles.module.css
apps/web/src/components/transactions/TxDetails/Summary/SafeTxHashDataRow/index.tsx
apps/web/src/components/tx-flow/common/TxLayout/styles.module.css
apps/web/src/components/tx/ConfirmTxDetails/TxDetails.tsx
apps/web/src/components/tx/ConfirmTxDetails/index.tsx
apps/web/src/components/tx/ReviewTransaction/__tests__/__snapshots__/index.test.tsx.snap
apps/web/src/components/tx/SignOrExecuteForm/__tests__/__snapshots__/SignOrExecute.test.tsx.snap

Resolves #5417
There is no common display of hashes (domain, message, Safe) in wallets and our receipt screen currently shows them depending on whether a hardware wallet is connect. We should instead always show them.
This adjusts the receipt screen to include a collapsable section, displaying the hashes when opened. It is opened by default if a hardware wallet is connected, however.
With the receipt screen open, observe the new section that can be opened/closed on click. If a hardware wallet is connected, it should be open by default.

feat(Signing UX): always show hashes on receipt

---

apps/mobile/package.json
apps/mobile/src/app/(import-accounts)/form.tsx
apps/mobile/src/components/Dropdown/DropdownLabel.tsx
apps/mobile/src/components/SafeInput/SafeInput.tsx
apps/mobile/src/components/SafeInput/styled.ts
apps/mobile/src/features/AccountsSheet/AccountItem/AccountItem.test.tsx
apps/mobile/src/features/AccountsSheet/AccountItem/AccountItem.tsx
apps/mobile/src/features/AccountsSheet/MyAccounts/MyAccounts.container.test.tsx
apps/mobile/src/features/Assets/components/Navbar/Navbar.tsx
apps/mobile/src/features/ImportReadOnly/AddSignersForm.container.tsx
apps/mobile/src/features/ImportReadOnly/ImportAccountForm.container.tsx
apps/mobile/src/features/ImportReadOnly/components/ImportAccountFormView.tsx
apps/mobile/src/features/ImportReadOnly/schema.ts
apps/mobile/src/features/ImportReadOnly/types.ts
apps/mobile/src/features/Settings/Settings.container.tsx
apps/mobile/src/features/Settings/Settings.tsx
apps/mobile/src/features/Settings/components/Navbar/SettingsMenu.tsx
apps/mobile/src/features/Share/components/ShareView.test.tsx
apps/mobile/src/features/Share/components/ShareView.tsx
apps/mobile/src/store/addressBookSlice.ts
apps/mobile/src/tests/test-utils.tsx
yarn.lock

With this PR safes added to the mobile app can have names.
Resolves  https://github.com/safe-global/safe-wallet-mobile/issues/62
During account import there is a field to enter the safe name. You can change that Safe name later in the Safe's settings. 
During the import the safe is created as a contact in the address book. We look for that contact everywhere where we need to display the safe name. (we could later optimise this and make it a hook)
Look at the added video
https://github.com/user-attachments/assets/95a97367-e0c8-4be6-9f50-2fd943e61216

feat(mobile): Safes can have a name now

---

apps/mobile/src/components/Fiat/Fiat.tsx
apps/mobile/src/components/transactions-list/Card/AccountCard/AccountCard.test.tsx
apps/mobile/src/components/transactions-list/Card/AccountCard/AccountCard.tsx
apps/mobile/src/features/AccountsSheet/AccountItem/AccountItem.test.tsx
apps/mobile/src/features/AccountsSheet/MyAccounts/MyAccounts.container.test.tsx
apps/mobile/src/features/Assets/components/Balance/Balance.tsx
apps/mobile/src/features/Assets/components/Tokens/Tokens.container.test.tsx
apps/mobile/src/features/Assets/components/Tokens/Tokens.container.tsx
apps/mobile/src/features/NetworksSheet/NetworksSheet.container.tsx
apps/mobile/src/utils/balance.test.ts
apps/mobile/src/utils/balance.ts

After adding the polyfill for the Intl.numberFormat class we didn't use the correct functions to display the fiat numbers across the app. 
Based on the available screen estate we either display a precise amount or a rounded value.

feat(mobile): unify fiat amount display

---

apps/mobile/src/components/Dropdown/DropdownLabel.tsx
apps/mobile/src/features/Assets/components/Balance/Balance.container.tsx
apps/mobile/src/features/Assets/components/Balance/Balance.tsx

Display the safe’s address next to the network selection dropdown. If the safe is not available on multiple networks we don’t display the arrow down icon.
https://www.figma.com/design/yVshG47sZRM7ztI66bDII4/New-Mobile-App?node-id=3521-19078&m=dev

feat(mobile): display safe address next to network

---

apps/web/src/features/myAccounts/hooks/useAllSafesGrouped.ts
apps/web/src/features/spaces/components/Dashboard/AggregatedBalances.tsx
apps/web/src/features/spaces/components/Dashboard/DashboardMembersList.tsx
apps/web/src/features/spaces/components/Dashboard/index.tsx
apps/web/src/features/spaces/components/Dashboard/styles.module.css

Resolves https://github.com/safe-global/wallet-private-tasks/issues/19
- Adds aggregated balances to the dashboard
1. Open a space with some safe accounts
2. Go to the dashboard
3. Observe aggregated balances showing

Feat(Orgs): Show aggregated balance on dashboard

---

apps/mobile/src/features/AccountsSheet/MyAccounts/hooks/useMyAccountsSortable.ts
apps/mobile/src/features/Assets/components/Balance/Balance.container.tsx
apps/mobile/src/features/Share/Share.container.tsx
apps/mobile/src/store/chains/index.ts
apps/mobile/src/store/safesSlice.ts

This PR fixes 2 bugs:
- When deleting safes from my accounts view - the safe was deleted, but it was still visible in the list 
- when deleting all the safes in the app, the final deleted safe caused the app to crash. This was due to improper assumptions about the store state. 
- add at least 2 safes
- try to drag and drop
- try to delete them

fix(mobile): crash when deleting safes

---

apps/web/src/utils/__tests__/safe-migrations.test.ts
apps/web/src/utils/safe-migrations.ts

Fixes safe-migrations.ts:
`hexData` can be `null` (even though not declared in type)
- Create a tx without tx data, e.g. a native transfer

fix: error in migration tx check

---

apps/web/src/features/spaces/components/AddAccounts/index.tsx
apps/web/src/features/spaces/components/AddMembersModal/index.tsx
apps/web/src/features/spaces/components/MembersList/EditMemberDialog.tsx
apps/web/src/features/spaces/components/MembersList/RemoveMemberDialog.tsx
apps/web/src/features/spaces/components/SafeAccounts/RemoveSafeDialog.tsx
apps/web/src/features/spaces/components/SpaceCreationModal/index.tsx
apps/web/src/features/spaces/components/SpaceSettings/DeleteSpaceDialog.tsx
apps/web/src/features/spaces/components/SpaceSettings/UpdateSpaceForm.tsx

Resolves #5397 
- Shows toast messages for `Add safe account`, `Delete safe account`, `Add member`, `Delete member/invite`, `Update member`, `Space creation`
1. Go through the above actions and observe toast messages show up

Fix(Orgs): Add more toast messages for space actions

---

apps/web/src/components/tx-flow/flows/CreateNestedSafe/ReviewNestedSafe.tsx
apps/web/src/components/tx-flow/flows/CreateNestedSafe/index.tsx
apps/web/src/components/tx-flow/flows/MigrateSafeL2/MigrateSafeL2Review.tsx
apps/web/src/components/tx-flow/flows/MigrateSafeL2/index.tsx

Resolves #5496 
Adds the transaction receipt screen to the **CreateNestedSafe** and **MigrateSafeL2** flows.

feat(Signing UX): receipt screen for CreateNestedSafe + MigrateSafeL2 flows

---

apps/web/src/components/settings/NestedSafesList/index.tsx
apps/web/src/components/sidebar/NestedSafesButton/index.tsx
apps/web/src/components/sidebar/NestedSafesPopover/index.tsx

Resolves #5075
Only deployed Safes can add nested Safes. This hides the creation buttons (in the sidebar and settings) if the current Safe is not deployed.
In a counterfactual Safe, observe no "Add nested Safe" button in the sidebar popover or settings.

fix(Nested Safes): only allow adding nested Safe for deployed Safes

---

apps/web/src/components/transactions/TxDetails/index.tsx
apps/web/src/hooks/loadables/useLoadBalances.ts
apps/web/src/store/index.ts

We're seeing a 3x increase in balances requests after migrating the Balances fetching to RTK Query.
@compojoom's hypothesis is that it's because the old `useIntervalCounter` polling was being suspended in a background tab and the query wasn't.
* Open the Console -> Network and filter by `balances`
* Observe that balances are polled every 15s
* Go to another tab, wait for 1 minute
* Come back to the Safe tab
* Observe that there's just one new request, not 4+

Fix(Balances): add skipPollingIfUnfocused to polled queries

---

apps/web/src/components/transactions/TxFilterForm/index.tsx
apps/web/src/utils/__tests__/tx-history-filter.test.ts
apps/web/src/utils/tx-history-filter.ts

Partially resolves https://github.com/safe-global/safe-client-gateway/issues/2340
We format/parse the `value` for incoming/outgoing filters because the Client Gateway requires "raw" values. When https://github.com/safe-global/safe-client-gateway/pull/2485 is merged, this value parsing will happen on the Client Gateway.
This removes the client-side format/parse accordingly.
Filter incoming/outgoing and observe the value "as is" in the request.

fix(History filters): don't parse/format filter values

---

.yarn/patches/next-npm-15.2.3-06a6671f62.patch
apps/web/docs/update-patch.md
apps/web/package.json
yarn.lock

Resolves https://github.com/safe-global/safe-wallet-monorepo/security/dependabot/107
- Updates next to v15.2.3
- Updates the integrity-hash patch
- Adds a document to explain the patch update process
- Deployment should work and the integrity hashes should still be generated

Chore(web): Update nextjs to v15.2.3 and integrity patch

---

apps/web/src/components/sidebar/SafeListContextMenu/index.tsx

Part of #5508 
- Only fetches the nested owned safes if the context menu is mounted. This reduces the number of requests on the accounts page significantly.
1. Open the accounts page
2. Connect a wallet that owns a few safes
3. Observe no requests to get safes for every safe that the wallet owns
4. Press the three-dot menu next to a safe item in the list
5. Observe the request happens then
6. Close the context menu and open it again
7. Observe no additional request (Redux cache kicking in)

Fix(Web): Only fetch owned nested safes if menu is opened

---

.vscode/settings.json
apps/web/src/components/tx/ReviewTransaction/ReviewTransactionContent.tsx
apps/web/src/features/policies/components/TxPolicies.tsx
apps/web/src/features/policies/config/constants.ts
apps/web/src/features/policies/hooks/useCheckTransaction.ts
apps/web/src/features/policies/hooks/useIsPoliciesEnabled.ts
apps/web/src/features/policies/utils/contracts.ts

This PR adds transaction policy verification to the user interface as part of the Safenet prototyping of on-chain Safe policies.
Note that it does not add the UI for re-configuring the policies to allow the transaction - I will leave that for a follow up, to keep the PRs small.

[Safenet Prototype] Add Transaction Policy Verification

---

apps/web/src/features/spaces/components/AuthState/index.tsx
apps/web/src/features/spaces/components/SpaceBreadcrumbs/index.tsx
apps/web/src/pages/welcome/spaces.tsx

Resolves #5230
- Redirects user from `/welcome/spaces` to `/welcome/accounts` if Spaces feature is turned off
- Redirects user from `/spaces/*` to `/welcome/accounts` if Spaces feature is turned off
- Only displays the spaces breadcrumbs if the feature is turned on
1. Turn off the feature flag
2. Navigate to the above mentioned pages
3. Observe being redirected to the accounts page
4. Open a safe and add a spaceId query param to the url
5. Observe no breadcrumbs are showing

Fix(Orgs): Redirect user to accounts page if spaces feature is turned off

---

apps/mobile/src/components/TokenAmount/TokenAmount.tsx
apps/mobile/src/components/TokenAmount/index.ts
apps/mobile/src/components/transactions-list/Card/TxTokenCard/TxTokenCard.tsx
apps/mobile/src/features/ConfirmTx/components/TransactionHeader/TransactionHeader.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/TokenTransfer/TokenTransfer.tsx
apps/mobile/src/features/PendingTx/components/PendingTxList/PendingTxList.container.tsx
apps/mobile/src/features/PendingTx/utils.tsx
apps/mobile/src/hooks/useTokenDetails/useTokenDetails.ts

The amounts displayed for sent/receive events were not properly formatted. In addition to that renamed the queue sectiosn to "next" and "in queue" as the old section titles were misleading.
Inspect transfer events in the queue and history. They should be properly formatted.

fix(mobile): display properly formatted amounts in queue and history

---

.github/workflows/package-utils-unit-tests.yml
.gitignore
apps/web/src/utils/gateway.ts
packages/utils/jest.config.js
packages/utils/package.json
packages/utils/src/features/swap/helpers/__tests__/utils.test.ts
packages/utils/src/utils/gateway.ts

This functions needs signTypeData from the web utils/web3 helper. Unfortunately if I move the helper to the utils package it drags with itself the typedData dependency from the safe-gateway-typescript-sdk. If I don’t move the function the mobile app can’t be build because the @safe-global/web package has a stream dependency from nodejs which cannot be resolved by the metro bundler. Until we ditch the safe-gateway-typescript-sdk this type will live in apps/web package.

refactor(utils): move signTxServiceMessage function back to web package

---

apps/mobile/app.config.js

Vision Camera is including location APIs, needed to properly tag an image, but since we don’t take images, we don’t need this.
Resolves #
This should put an end to "ITMS-90683: Missing purpose string in Info.plist" email that we get from apple.
Merge this, publish a release and wait for the mail...

fix(mobile): don’t use location APIs

---

apps/mobile/src/features/Assets/components/AssetsHeader/AssetsHeader.tsx
apps/mobile/src/features/Assets/components/ReadOnly/ReadOnly.container.test.tsx
apps/mobile/src/features/Assets/components/ReadOnly/ReadOnly.container.tsx
apps/mobile/src/features/Assets/components/ReadOnly/ReadOnly.tsx
apps/mobile/src/utils/signer.test.ts
apps/mobile/src/utils/signer.ts

Displays a "this is a read-only account" if there is no signer imported for the safe. 
You should see a "this is a read-only acocunt" in safe's where you haven't imported a signer.

feat(mobile): add „read-only“ account block

---

apps/web/src/features/spaces/components/SafeAccounts/SendTransactionButton.tsx
apps/web/src/features/spaces/components/SafeAccounts/styles.module.css

Resolves #5386
- Makes the buttons slightly larger
- Changes the background color and disabled color in light and dark mode according to Figma
1. Open a space with safe accounts
2. Compare the send token button design with Figma
3. Switch to a wallet thats not an owner of that safe
4. Compare the disabled button design with Figma
Light mode not disabled
Dark mode not disabled
Light mode disabled
Dark mode disabled

Fix(Orgs): Adjust send token buttons style within spaces

---

apps/web/src/components/common/NestedSafeBreadcrumbs/index.tsx
apps/web/src/features/myAccounts/components/AccountItems/SingleAccountItem.tsx
apps/web/src/features/myAccounts/hooks/useGetHref.ts
apps/web/src/features/spaces/components/SpaceBreadcrumbs/index.tsx
apps/web/src/services/analytics/events/overview.ts
apps/web/src/services/analytics/events/spaces.ts

Resolves https://github.com/safe-global/wallet-private-tasks/issues/58
- Fixes the parent safe link in the nested safe breadcrumbs by including the chain prefix in the pathname
- Includes all other query params in the parent safe link as well
- Adds two new analytics events to the space breadcrumbs when navigating to a space or to the space list
- Adds a link to the safe when clicking a safe item in spaces
1. Open a nested safe so that the breadcrumbs are visible
2. Add a spaceId parameter to the url
3. Observe the spaces breadcrumbs also appear
4. Press the parent safe button
5. Observe the spaceId stays in the url and the breadcrumbs are still visible
6. Press the space button and the space overview button
7. Observe analytics events for both

Fix(Orgs): Nested safe breadcrumbs, add breadcrumb analytics events

---

apps/web/src/features/myAccounts/components/AccountItems/MultiAccountItem.tsx
apps/web/src/features/myAccounts/components/AccountsNavigation/index.tsx
apps/web/src/features/spaces/components/SpaceCard/SpaceContextMenu.tsx
apps/web/src/features/spaces/components/SpaceSettings/DeleteSpaceDialog.tsx
apps/web/src/features/spaces/components/SpaceSettings/index.tsx
apps/web/src/services/analytics/events/spaces.ts

QA feedback for: https://github.com/safe-global/safe-wallet-monorepo/issues/5055
- do not send a tracking event when clicking the `Spaces` tab on the accounts page, if it has already been selected
- do not send an event for expanding a multi chain safe in the space accounts list.
- add missing events in the delete space flow.
- Minor name changes.
- go to the accounts page and click the spaces tab. See that the event is fired correctly. Clicking the tab again immediately should not fire the event a second time.
- go to the accounts list for a space. Expand a multichain safe item. See that no event is fired.
- Open the `delete space` dialog from the context menu in the spaces list. See that an event is fired.
- Click the confirm deletion from the `delete space` dialog. See that an event is …

Fix(Spaces): add missing tracking event and remove misfiring events

---

apps/web/src/features/spaces/components/UserSettings/index.tsx

Resolves #5010 
- Adds a signed out view and removes the redirect
- Adds a coming soon tooltip to the add wallet button
- Removes the delete wallet button for now
1. Open `/user-settings`
2. Observe a signed out state
3. Sign in with your wallet
4. Observe your wallet is listed but no actions are possible

Fix(Orgs): Update user-settings page

---

apps/web/src/features/spaces/components/Dashboard/AggregatedBalances.tsx
apps/web/src/features/spaces/components/Dashboard/styles.module.css

Follow-up on #5464 
- Adjusts the design of the aggregated balances to include chain logos
- Displays the chain indicator as a percentage of the total
1. Compare with [Figma](https://www.figma.com/design/PeChIDi5UKPjf58IOChtET/Spaces-(prev.-Organisations)?node-id=4641-48061&m=dev)

Fix(Orgs): Update aggregated balances design

---

apps/web/src/components/common/AddressInput/index.test.tsx
apps/web/src/components/common/AddressInput/index.tsx
apps/web/src/components/new-safe/load/steps/SetAddressStep/index.tsx
apps/web/src/features/spaces/components/AddAccounts/AddManually.tsx

Resolves https://github.com/safe-global/wallet-private-tasks/issues/77
- triggers the address transformation to remove the chain prefix anytime the chain is changed, not just when the address itself is changed. 
- This has the side effect of re-triggering validation, so the manual re-trigger of validation is removed.
- Open the `add address manually` dialog (or the add safe flow).
- Copy an address with the chain prefix included
- paste the address into the address input, but with the incorrect chain selected.
- It will show a validation error
- then select the correct chain. The chain prefix should be removed from the displayed value. You should be able to submit and add the safe to your space without issues.

Fix(Spaces): Re-trigger address transformation on chain change

---

apps/web/src/components/common/NamedAddressInfo/index.tsx
apps/web/src/components/transactions/TxDetails/TxData/Transfer/index.tsx

Resolves #5557.
Show "Unverified contact" for unknown contracts in tx details in history and queue.
* Go to some safe with lots of spam txs (e.g. [this one](https://unverified_contract--walletweb.review.5afe.dev/transactions/history?safe=eth:0x220866b1a2219f40e72f5c628b65d54268ca3a9d))
* Unhide suspicious txs
* Observe that the address is marked as "Unverified contract"

Feat(Tx details): show "Unverified contract" for unknown contracts

---

apps/web/src/components/sidebar/SidebarNavigation/index.tsx

Include all query params when navigating via the sidebar instead of always adding a `spaceId` param even if its empty
1. Open a safe
2. Navigate through the sidebar
3. Observe no spaceId param added to the url

Fix(Spaces): Adjust query param inclusion in sidebar navigation

---

apps/web/src/features/spaces/components/SignInButton/index.tsx

Only sets the sign in state if the sign in request succeeded
1. Open `/welcome/spaces`
2. Connect your wallet and press the sign in button
3. Cancel the sign in message in your wallet
4. Observe the sign in button is still visible

Fix(Spaces): Only sign in user if they submit the sign in request

---

apps/web/src/features/spaces/components/InviteBanner/index.tsx
apps/web/src/features/spaces/components/SpaceCard/index.tsx

The member count in the space summary is showing the wrong number. It is including the invited members in the count.
- only count active members for the space summary.
- Go to a space with pending invites.
- View the space summary:
- in the space switcher in the sidebar
- on the spaces list page
- on the invitation on top of the space list for an invited member
- see that the correct number of members is shown.

Fix(Spaces): only include active members in space member count

---

apps/web/src/features/spaces/components/SpacesList/index.tsx

The CTA for the logged out and disconnected states is in the center of the screen, but for the empty state, the CTA jumps to the top right.
- When there are no spaces in the list, do not show the CTA at the top right, add it to the empty spaces card instead.
- Also adds some padding above the CTA for this screen and the logged out and disconnected states
- Go to the spaces page and sign in with a EOA that is not part of any spaces yet.
- See that the CTA to create a space is in the middle of the screen

Fix(Spaces): Add a CTA to empty spaces card on the spaces list page

---

apps/web/src/components/common/SplitMenuButton/index.tsx

Resolves #5556
The submit button can have options now.
NB: no memory yet because I'm waiting for the sign-or-execute refactoring to be done first.

Feat(Signing UX): split menu button for Continue / Add to batch

---

apps/web/src/components/common/NamedAddressInfo/index.tsx
apps/web/src/components/tx/ConfirmTxDetails/TxDetails.tsx

Resolves #5557
Uses the existing `useAddressName` hook to show an unverified contract chip.

Feat(Signing UX): show unverified contracts

---

apps/web/src/features/myAccounts/hooks/useAllSafesGrouped.ts
apps/web/src/features/spaces/hooks/useSpaceSafes.tsx

Read only safes are missing the read only chip in the space accounts list
- checks if the space safes are owned by the currently connected wallet and sets the isReadOnly flag accordingly.
- go to the space accounts page and add a read only safe account to the space
- see that it has the read only flag in the list

Fix(Spaces): flag read only safe in the space accounts list

---

apps/web/src/features/myAccounts/hooks/useGetHref.ts
apps/web/src/features/spaces/components/AuthState/index.tsx
apps/web/src/features/spaces/components/Dashboard/AggregatedBalances.tsx
apps/web/src/features/spaces/components/Dashboard/styles.module.css
apps/web/src/features/spaces/components/SignInButton/index.tsx
apps/web/src/features/spaces/components/SpaceBreadcrumbs/index.tsx
apps/web/src/features/spaces/components/SpacesDashboardWidget/index.tsx
apps/web/src/features/spaces/hooks/useCurrentSpaceId.ts
apps/web/src/store/authSlice.ts

Instead of pushing the `spaceId` query parameter whenever the user "leaves" a space and use that as a source of truth we store it in local storage and update it whenever the `spaceId` changes.
- Removes the `spaceId` query parameter outside of spaces
- Stores it as part of the `authSlice`
- Checks that the currently opened safe is part of the space
2. Navigate to one of the safes
3. Observe no spaceId in the url
4. Open a safe that is not part of the space
5. Observe the breadcrumbs are not showing

Refactor(Spaces): Use current spaceId from local storage

---

apps/web/src/components/common/WalletInfo/index.tsx
apps/web/src/hooks/wallets/useOnboard.ts

There were a lot of requests and flickering happening whenever the user disconnected their wallet (even if not signed in). This is because we are resetting the logged in state whenever that happens which rerenders every component where we access the authenticated state.
This PR changes this to only update the state if the user is logged in.
Note: The app still flickers in case the user is signed in and disconnects. This will be optimized in a future PR.
- Check for `isAuthenticated` before calling `setUnauthenticated`
1. Open a Safe
2. Connect your wallet
3. Disconnect your wallet
4. Observe no flicker

Fix(Spaces): Only update auth slice if user was signed in

---

apps/web/src/store/authSlice.ts

Resolves https://github.com/safe-global/safe-wallet-monorepo/pull/5575#issuecomment-2772245429
- Instead of calling `resetApiState` on the api slice we only invalidate the `spaces` tags when a user disconnects. This effectively removes all previous spaces data from Redux
2. Sign in with your wallet
3. Go to a safe
4. Sign out with your wallet
5. Observe no flickering or excessive requests

fix: Only invalidate space related redux state

---

apps/web/src/components/common/WalletInfo/index.tsx
apps/web/src/hooks/wallets/useOnboard.ts

Reverts https://github.com/safe-global/safe-wallet-monorepo/pull/5575
After implementing the RTK slice fix in #5576 we can safely revert the previous fix that limited the scope only
1. Open a safe while signed in
2. Disconnect your wallet
3. Observe no excessive network requests or flicker

Fix(Spaces): Revert setUnauthenticated change

---

apps/mobile/src/features/AddressBook/components/List/AddressBookList.tsx

Wrong indeticons are displayed for the addresses in the addressbook
Addressbook: 0x is displayed twice for the addresses in the addressbook
https://github.com/safe-global/wallet-private-tasks/issues/101
https://github.com/safe-global/wallet-private-tasks/issues/93
We were not casting to string, but rather prepending 0x to the value
Go to the contacts - the identicon should match the one displayed on settings, no 0x0x in the address.

fix(mobile): identicon and address in contact book were wrong

---

apps/mobile/src/features/ConfirmTx/components/confirmation-views/AlreadySigned/__snapshots__/AlreadySigned.test.tsx.snap
apps/web/src/components/tx/ReviewTransaction/__tests__/ReviewTransactionContent.test.tsx
apps/web/src/components/tx/SignOrExecuteForm/__tests__/ExecuteForm.test.tsx
apps/web/src/components/tx/SignOrExecuteForm/__tests__/SignForm.test.tsx
apps/web/src/components/tx/SignOrExecuteForm/__tests__/SignFormV2.test.tsx
apps/web/src/components/tx/security/blockaid/ContractChangeWarning.tsx
apps/web/src/components/tx/security/blockaid/__tests__/useBlockaid.test.ts
apps/web/src/components/tx/security/blockaid/index.tsx
apps/web/src/components/tx/security/shared/TxSecurityContext.tsx
packages/utils/src/components/tx/security/blockaid/utils.ts
packages/utils/src/components/tx/security/shared/types.ts
packages/utils/src/components/tx/security/shared/utils.ts
packages/utils/src/config/constants.ts

Move blockaid utilities & types to @safe-global/utils. This allows us to share this functionality between web & mobile.

refactor: move blockaid utilities & types to @safe-global/utils

---

apps/web/src/config/routes.ts
apps/web/src/features/spaces/components/SpaceAddressBook/index.tsx
apps/web/src/features/spaces/components/SpaceSidebarNavigation/config.tsx
apps/web/src/hooks/useIsSpaceRoute.ts
apps/web/src/pages/spaces/address-book.tsx
apps/web/src/services/analytics/events/spaces.ts

Resolves: https://github.com/safe-global/wallet-private-tasks/issues/109#issue-2969278932
- Adds the address book route
- Updates `routes.ts`
- Adds the route to the list of spaces routes.
- renders an empty page with dummy button and search input.
- Open a space
- Click the address book link in the sidebar. The link should be enabled, and redirect to `/spaces/address-book`
- It should show an empty address book page with just the title, search bar, and add button.

Feat(Spaces): add address book route

---

apps/web/src/utils/wallets.ts

Resolves #4473
When navigating to the add Safe flow, WalletConnect disconnects because it is not deemed unlocked. This adds an early return, always flagging WalletConnect as unlocked.
Whilst connected via WalletConnect and with a Safe open, navigate to the flow to add a (specific) Safe. Observe WalletConnect not disconnecting. (An example video is in the issue.)

fix(WalletConnect): ensure WC remains connected when adding Safe

---

apps/web/src/components/common/NameInput/index.tsx
apps/web/src/features/spaces/components/AddMemberModal/index.tsx

Resolves https://github.com/safe-global/wallet-private-tasks/issues/115
- Changes the `NameInput` to be wrapped by a `Controller` to fix the shrink issue when setting a value
- Checks the address book whenever the address changed and sets the name value if there is a hit
- Uses the `AddressBookInput` for the address when adding a member
2. Add a member
3. Observe suggestions from the address book
4. Select one
5. Observe the name is filled automatically

Fix(Spaces): Check address book when adding a member

---

apps/web/src/features/myAccounts/components/AccountsNavigation/index.tsx
apps/web/src/features/myAccounts/styles.module.css

Resolves https://github.com/safe-global/wallet-private-tasks/issues/141
- Adjusts the condition for emitting the analytics event
- Adds a hover effect to the spaces and accounts tab
1. Go to `/welcome/accounts`
2. Hover the Spaces tab
3. Observe a visual feedback
4. Click the Spaces button
5. Observe an event is emitted in the console

Fix(Spaces): Add hover effect for space tab navigation

---

apps/web/src/components/tx-flow/common/TxFlowContent/index.tsx
apps/web/src/components/tx-flow/features/TxNote.tsx
apps/web/src/components/tx-flow/slots/SlotProvider.tsx
apps/web/src/features/tx-notes/TxNoteInput.tsx

Resolves #5625 
Moves the Note feature to the sidebar.
* Add a new `Sidebar` slot and update TxNote component to register for that slot.
* Update the TxNote UI to match the design.

feat(Signing UX): move Note to the sidebar

---

apps/web/src/components/common/TokenAmount/index.tsx
apps/web/src/components/common/TokenAmount/styles.module.css

This PR fixes a bug where long token names overlap with the date display in the Queue and History views.
Resolves #3438
- Introduces MAX_TOKEN_SYMBOL_LENGTH to the TokenAmount component.
- Truncates token names on all pages where TokenAmount is used, preventing layout overflow.
- Find (or create) any Safe transactions in {Wallet} (eg. gno:0x03F4156023e340779Feda280185C251B6aF00343)
- Use the browser console to add a long token name (e.g., REALTOKEN-S-13041-HAYES-ST-DETROIT-MI).
- Verify that the long token name is truncated and does not overlap with the date.

fix(web): truncate long name tokens

---

apps/web/src/components/tx/SponsoredBy/styles.module.css

This PR addresses visibility and spacing issues with the logo in the `ExecutionMethodSelector` component.
Resolves #5439
- Adds `margin-left` to the logo for proper spacing between the logo and text.
- Implements dark mode support to display the `logo` in white when dark mode is enabled.
- Create a transaction and go to the sponsorship modal
- Check the `spacing` (4px between logo and text) and color of logo

fix(web): add white safe logo and spaces on ExecutionMethodSelector

---

apps/web/scripts/github/s3_upload.sh

This fix prevents the build outages we faced on docs.safe.global after the build output became large enough (~500 pages). Predictably, fixing this file (that both the codebases have in common) solved this issue. Limiting threads was [already rightfully mentioned in previous discussions](https://github.com/safe-global/safe-wallet-monorepo/pull/4842), but not implemented in the end as we could not get it to work properly at the time.
Replace the `for` loop by a `while` and add a throttling function when the max limit is hit.
Check that the GitHub action used for deployment still succeeds, even with large build outputs. Already tested on the [docs repo](https://github.com/safe-global/safe-docs/pull/728).

Limit parallel threads in s3_upload.sh

---

apps/mobile/src/features/TxHistory/TxHistory.container.tsx
apps/mobile/src/features/TxHistory/components/TxHistoryList/TxHistoryList.tsx

Ads pull down to refresh on the history page
Resolves
https://github.com/safe-global/wallet-private-tasks/issues/128
Open safe, navigate to the history, pull down - you would see a spinner and the tx will load from the server. (you could try sending a tx to the safe and then pulling down to see the newest tx at the top.

feat(mobile): add pull down to refresh history

---

apps/mobile/src/hooks/useNotificationManager.test.ts
apps/mobile/src/hooks/useNotificationManager.ts
apps/mobile/src/services/notifications/NotificationService.ts

This PR implements fix on the UX of enabling Notifications. A bug leading users to click twice was also fixed.
Resolves https://github.com/safe-global/wallet-private-tasks/issues/145
**Notifications use cases.**
Implement handlers/references to handle different states.
Run each use case mentioned above.
https://github.com/user-attachments/assets/c102a3b6-b9a7-4b4f-8362-55350d8fdbe6
https://github.com/user-attachments/assets/12954308-d949-467a-97a6-8ab574b032d6
https://github.com/user-attachments/assets/67213057-54c3-4696-b1ee-332627672695

fix(mobile): subscribe to notifications in one click

---

apps/web/src/components/settings/SpendingLimits/index.tsx

This PR updates the Spending Limits table styling to match the Recovery table style.
Resolves #2923
- Removed the `mb: 2` from the Grid container styling 
- Added `mb: 2` to the "New spending limit" button for proper spacing
- Moved the `<SpendingLimitsTable> `component inside the `<Grid item xs>` and inside the same `<Box>` as the text
- Add spending limits
- Check the table view
- The table view should like the Figma [design](https://www.figma.com/design/pO43pjVwR34Uy1ihMsY3OM/Recovery-Hub?node-id=1-2&p=f&t=cHxWEvfBRneKnAqT-0)

fix(web): update spending limits table to match recovery table style

---

apps/web/src/components/transactions/HexEncodedData/index.tsx
apps/web/src/components/transactions/HexEncodedData/styles.module.css
apps/web/src/components/transactions/TxDetails/Summary/index.tsx

* Make the hex data monospaced 
* Remove the copy icon and just make the whole text click-to-copiable
* Memoize the Summary component to avoid re-renders on Safe polling

Fix(Signing UX): improvements for hex data

---

apps/mobile/src/components/Camera/QrCamera.tsx
apps/mobile/src/features/ImportReadOnly/ScanQrAccount.container.tsx
apps/mobile/src/features/ImportReadOnly/components/ScanQrAccountView.tsx

This PR implements fix the QRCode Scan flow while importing a Safe
Resolves #
From Notion
[x] - Update text in QR code scanner: You can find it in the web app’s sidebar on top.
[x] - Avoid camera to be prompt before user's interaction.
Add a button on CRScanner so the user trigger a camera permission request, instead of automatically on render.
Install a fresh version and try import a Safe.

fix(mobile): activate QR camera on user interaction

---

apps/mobile/src/features/Assets/components/Navbar/Navbar.tsx
apps/mobile/src/features/Settings/components/IdenticonWithBadge/IdenticonWithBadge.tsx

Resolves #
From Notion
[x] - Asset screen: badge threshold missing New Mobile App
Added badge with signers count on account selector
Open the app and on the Home, check if the account selector shows a badge.

chore(mobile): add account badge on selector

---

apps/mobile/src/features/ImportPrivateKey/components/ImportSuccess/ImportSuccess.tsx
apps/mobile/src/features/ImportReadOnly/components/AddSignersFormView.tsx
apps/mobile/src/features/Settings/Settings.tsx
apps/mobile/src/features/Signers/Signers.container.tsx
apps/mobile/src/features/Signers/components/SignersList/SignersList.tsx
apps/mobile/src/features/Signers/components/SignersList/SignersListItem.tsx
apps/mobile/src/features/Signers/components/SignersList/hooks/useSignersActions.ts
apps/mobile/src/features/Signers/constants.ts

This PR implements a condition to avoid show import on item menu if the item was imported already.
Resolves #
https://github.com/safe-global/wallet-private-tasks/issues/99
Adds state and conditionals to prevent showing unnecessary menu action to the user.
Import and account and click on the 3dots.

feat(mobile): import menu conditionally and UI fix

---

apps/mobile/src/app/_layout.tsx
apps/mobile/src/theme/provider/safeTheme.tsx

There are differences between the way android and ios handle content behind the statusbar. On android the Header from react-navigation ends up being behind the Statusbar which is unexpected. For now we are opting out of translucent statusbar and will tacle this at a later stage. It turns out to be a complicated issue with multiple bug reports, libraries to choose from (e.g. https://www.npmjs.com/package/react-native-edge-to-edge). Currently I'm not sure where the problem comes from. iOS seems to behave correctly where android does crazy stuff. 
Resolves #
before:
after:

fix(mobile): content on android was behing Statusbar

---

apps/mobile/src/theme/tokens.ts

Console was poluted by a huge No font size found $md error
That made looking at the logs very hard. 
That also fixes a problem where the wrong font was used for buttons.
Resolves
partially resolves https://github.com/orgs/safe-global/projects/1/views/16?pane=issue&itemId=105267036&issue=safe-global%7Cwallet-private-tasks%7C142
Launch the app, enable the JS debugger -> observe no warnings when you open a screen that has buttons.

fix(mobile): no size defined for $md & $sm warning

---

apps/mobile/src/app/biometrics-opt-in.tsx
apps/mobile/src/components/OptIn/OptIn.tsx
apps/mobile/src/navigation/hooks/useModalStyle.ts
apps/mobile/src/theme/tokens.ts

Display an info box on the biometrics screen explaining why we need it (Biometrics is required to import a signer). 
Resolves
https://github.com/safe-global/wallet-private-tasks/issues/96
Ads the missing banner component
Also properly aligns the design.
before:
after:

fix(mobile): display info on biometrics screen

---

apps/web/src/components/new-safe/create/logic/utils.ts
apps/web/src/components/new-safe/create/steps/ReviewStep/index.tsx
apps/web/src/hooks/useGasLimit.ts
apps/web/src/services/tx/tx-sender/dispatch.ts

Resolves #address calculation for Lens, which uses ZKsync
Adds Lens chains to the checks where we use ZKsync flows.
This is just a temporary solution to unlock QA, not an ideal solution as the chances of adding new ZKsync chains are higher over time. Already requested that a config parameter is added to the config service so we can check from ChainInfo if the chain uses ZKsync allowing dinamically to configure them in the future.

fix: add check for Lens to use ZKsync flows

---

apps/web/src/hooks/wallets/consts.ts
apps/web/src/services/private-key-module/index.ts
apps/web/src/services/siwe/useSiwe.tsx
apps/web/src/utils/wallets.ts

Resolves https://github.com/safe-global/wallet-private-tasks/issues/162
This now uses the same method as on mobile for the PK module that we use for testing.
- In case the connected wallet is the PK module we pass the signable message directly via `personal_sign` instead of using `signer.signMessage`
1. Open spaces
2. Connect a PK module wallet
3. Sign in
4. Observe it working
5. Connect with any other wallet
6. Sign in
7. Observe it still working

Fix(PK Module): Use `signMessageSync` for personal_sign with PK module

---

apps/mobile/src/components/SafeButton/SafeButton.tsx
apps/mobile/src/components/SafeInput/styled.ts
apps/mobile/src/features/AccountsSheet/MyAccounts/MyAccountsFooter.test.tsx
apps/mobile/src/features/AccountsSheet/MyAccounts/MyAccountsFooter.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/AlreadySigned/__snapshots__/AlreadySigned.test.tsx.snap
apps/mobile/src/features/GetStarted/GetStarted.tsx
apps/mobile/src/features/Settings/components/Navbar/SettingsMenu.tsx
apps/mobile/src/features/Share/components/ShareView.tsx

- center aligns button text and icon
- center aligns the text in input fields.
- fixes the places where we were using title case in buttons
Resolves
Makes annoyed users with laser eyes happy. 
If you open the app and you don't puke at the buttons and input text, then they are properly aligned 😄 
before
after
before
after

fix(mobile): fix different sizing issues

---

apps/mobile/src/features/Signers/components/SignersList/SignersListItem.tsx

The signers list items are not displaying the menu dropdown when clicking in the 3 dots
- Go to the signers list
- Click in any list item 3 dots icon
**Expected scenario**
- The menu dropdown should open
https://github.com/user-attachments/assets/bfbd827d-f481-4d55-bf4b-2ef3c823c2c3

Fix(mobile): Allow user to see the signer list item options

---

apps/mobile/src/hooks/useGTW.ts
apps/mobile/src/utils/uuid.test.ts
apps/mobile/src/utils/uuid.ts

When calling the register/notifications endpoint on android we were recieving a 422. It turned out that this is due to the format of the uuid that we send. The react-native-device-crypto getUniqueId method return uuid v4 on iOS, but only a 64-bix hex on android. Now, I’m converting the android id to a unique uuid. This way we are now able to subscribe on the gateway.
Resolves #
https://github.com/safe-global/wallet-private-tasks/issues/143
Converts the 64-bit hex string to a 128-bit UUID.
Try to subscribe to push notifications on android. You should not see a 422 error.

fix(mobile): unable to subscribe to push notifications on android

---

apps/mobile/src/theme/provider/font.tsx

Android was not loading the dmsans font. After a lot of time and refactoring of how we load the config I realised that the problem actually stems from the font name. We have a typo in it 🤦 
Resolves #
https://github.com/safe-global/wallet-private-tasks/issues/161
before:
after:

fix(android): dmsans font was not loaded on android

---

apps/web/src/services/analytics/useGtm.ts
apps/web/src/services/analytics/useMetaEvents.ts

Resolves https://github.com/safe-global/wallet-private-tasks/issues/160
- Checks `isSpaceRoute` before emitting meta events
1. Open a space with some safes added
2. Press the send token button next to a safe item
3. Observe only one GA event in the console
4. Close the send tokens flow
5. Observe no GA events in the console

Fix(Spaces): Don't track meta events in spaces

---

apps/web/cypress/e2e/regression/staking_history.cy.js

- Since decoding is back on staging, the tests are re-enabled again to perform required checks. 

Tests: Enable decoding tests

---

apps/web/src/components/common/SplitMenuButton/index.tsx
apps/web/src/components/tx-flow/TxFlow.tsx
apps/web/src/components/tx-flow/TxFlowProvider.tsx
apps/web/src/components/tx-flow/actions/Batching/index.tsx
apps/web/src/components/tx-flow/actions/ComboSubmit.tsx
apps/web/src/components/tx-flow/actions/Execute/ExecuteForm.tsx
apps/web/src/components/tx-flow/actions/Execute/__tests__/ExecuteForm.test.tsx
apps/web/src/components/tx-flow/actions/Execute/index.tsx
apps/web/src/components/tx-flow/actions/Sign/SignForm.tsx
apps/web/src/components/tx-flow/actions/Sign/__tests__/SignForm.test.tsx
apps/web/src/components/tx-flow/actions/Sign/index.tsx
apps/web/src/components/tx-flow/actions/index.ts
apps/web/src/components/tx-flow/common/TxFlowContent/index.tsx
apps/web/src/components/tx-flow/slots/Slot.tsx
apps/web/src/components/tx-flow/slots/SlotProvider.tsx
apps/web/src/components/tx-flow/slots/hooks/index.ts
apps/web/src/components/tx-flow/slots/hooks/useRegisterSlot.ts
apps/web/src/components/tx-flow/slots/hooks/useSlot.ts
apps/web/src/components/tx-flow/slots/hooks/useSlotIds.ts
apps/web/src/components/tx-flow/slots/index.ts
apps/web/src/components/tx-flow/slots/withSlot.tsx
apps/web/src/components/tx-flow/withCheckboxGuard.tsx
apps/web/src/components/tx/ConfirmTxReceipt/index.tsx
apps/web/src/components/tx/ReviewTransactionV2/ReviewTransactionContent.tsx
apps/web/src/components/tx/ReviewTransactionV2/__tests__/__snapshots__/index.test.tsx.snap
apps/web/src/components/tx/SignOrExecuteForm/SignOrExecuteForm.tsx
apps/web/src/components/tx/SignOrExecuteForm/SignOrExecuteFormV2.tsx

Resolves #5556
Introduces a combo button for signing, executing, or batching transactions, enhanced with memory to remember the user's last choice.
- Added new props:  
- `tooltip`: Displays contextual information on hover.  
- `onChange`: Handles selection changes.  
- `selected`: Controls the active option.  
- Updated `options` prop to support objects with `id` and `label` keys, enabling more descriptive and flexible menu options.
- Replaced `Popper` with `Popover` to improve accessibility and user experience.
- Render the new `SplitMenuButton` in Sign, Execute, and Batching components.
- **New `ComboSubmit` slot**: Introduced a dedicated slot to handle multi-action submission logic in one cohesive component.  
See [[1]](diffhunk://#diff-7726c8aaa4686f635e5e29a4ab8e4428f4ea36628368b6c31 …

feat(Signing UX): combo submit button

---

apps/mobile/package.json
apps/mobile/src/services/key-storage/key-storage.service.ts
yarn.lock

Without this fix the user was able to import a PK, but then trying to sign with it brought a 
> E  Signature/MAC verification failed (internal Keystore code: -30 message: system/security/keystore2/src/operation.rs:857: KeystoreOperation::finish
> Caused by:
>  0: system/security/keystore2/src/operation.rs:427: Finish failed.
>  1: Error::Km(r#VERIFICATION_FAILED))
Reimporting the key resolved this problem... 
It turned out that since we are using the same key for device crypto and react-native-keychain they were on the native side overriden. The keychain was overriding the device-crypto key and it was not possible to decrypt. 
Resolves #
Use different key ids 
You need a clean app. Import the PK and then try to sign. it should work.

fix(mobile): can't sign android

---

apps/mobile/src/features/AddressBook/AddressBookView.tsx
apps/mobile/src/features/AddressBook/components/List/AddressBookList.tsx
apps/mobile/src/features/AddressBook/components/List/NoContacts.tsx

Centers the No contacts illustartion on the address book view
2. Navigate to the address book with an empty address book
3. Observe the illustartion is vertically centered

Fix(Mobile): Center no contacts illustration

---

apps/web/src/services/safe-wallet-provider/index.test.ts
apps/web/src/services/safe-wallet-provider/index.ts

Propagates https://github.com/safe-global/safe-apps-sdk/pull/637 fix.
This updates our EIP-5792 implementation to align with [recent changes](https://github.com/ethereum/EIPs/pull/8826) to the `wallet_sendCalls` and `wallet_getCallsStatus` methods. The request and response objects changed meaning requests would fail.
Explicit types have been added for the respective methods and the logic for handling requests adjusted.
Using a DApp that supports the latest implementation of EIP-5792, send a batch call and then get the status of it sequentially throughout its lifecycle.

fix(WalletConnect): update EIP-5792 implementation

---

apps/mobile/src/components/Camera/QrCamera.tsx

On android we were directly sending the user to the OS settings for the app instead of bringing the camera permission prompt inside the app.
Now we bring the prompt. If the user denies we send him in the settings.
Resolves #
https://github.com/safe-global/wallet-private-tasks/issues/166
On android we by default get a denied permission, but that doesn't prevent us from asking.

fix(mobile): camera permission on android was wrong

---

apps/web/src/features/spaces/components/SafeAccounts/SpaceSafeContextMenu.tsx
apps/web/src/features/spaces/components/SafeAccounts/__tests__/SpaceSafeContextMenu.test.tsx

Due to some accidental changes that were supposed to be applied to the address book context menu, the safe context menu no longer works.
- Revert the changes
- Add tests for the SpaceSafeContextMenu component
- go to the safes list of a space
- Click on the context menu.
- Check that clicking the delete and edit options will open the conformation dialogs as expected

Fix(Spaces): revert accidental changes to space safe context menu

---

apps/web/src/features/spaces/components/AddAccounts/index.tsx
apps/web/src/features/spaces/components/Members/index.tsx
apps/web/src/features/spaces/components/SafeAccounts/index.tsx
apps/web/src/features/spaces/components/SearchInput/index.test.tsx
apps/web/src/features/spaces/components/SearchInput/index.tsx

Resolves https://github.com/safe-global/wallet-private-tasks/issues/127#issue-2971379246
- increases the size of the search input when you click into it.
- Makes the search input width 100% for smaller screens.
- Adds tests
- Go to the members or accounts page of a space.
- Click the search input. 
- See that the width increases.

Feat(Spaces): expand search input width when in focus

---

apps/web/src/components/tx-flow/TxFlow.tsx
apps/web/src/components/tx-flow/actions/Batching/index.tsx
apps/web/src/components/tx-flow/actions/Counterfactual.tsx
apps/web/src/components/tx-flow/actions/Execute/ExecuteForm.tsx
apps/web/src/components/tx-flow/actions/Execute/index.tsx
apps/web/src/components/tx-flow/actions/ExecuteThroughRole/index.tsx
apps/web/src/components/tx-flow/actions/Propose/index.tsx
apps/web/src/components/tx-flow/actions/Sign/SignForm.tsx
apps/web/src/components/tx-flow/actions/Sign/index.tsx
apps/web/src/components/tx-flow/slots/SlotProvider.tsx
apps/web/src/components/tx/ConfirmTxReceipt/index.tsx
apps/web/src/components/tx/ReviewTransactionV2/ReviewTransactionContent.tsx
apps/web/src/components/tx/ReviewTransactionV2/__tests__/ReviewTransactionContent.test.tsx
apps/web/src/components/tx/SignOrExecuteForm/SignOrExecuteForm.tsx
apps/web/src/components/tx/SignOrExecuteForm/SignOrExecuteFormV2.tsx

Show the combo button also on the receipt step and don't navigate to the previous step on sign/execute error.

feat(Signing UX): show combo button also on receipt step

---

apps/web/src/components/common/NetworkSelector/NetworkMultiSelectorInput.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/AddContact.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/EditContactDialog.tsx

https://github.com/safe-global/wallet-private-tasks/issues/184
- Adds a select all option to the network selector options
- Selects all networks by default when adding a contact.
- open the add contact dialog in a space
- see that all contacts are selected by default. You should still be able to select a subset of networks as before if desired.

Feat(Spaces): add select all option to the network multi selector

---

apps/web/src/components/common/EthHashInfo/SrcEthHashInfo/index.tsx
apps/web/src/components/tx/confirmation-views/BatchTransactions/__snapshots__/BatchTransactions.test.tsx.snap
apps/web/src/components/tx/confirmation-views/SettingsChange/__snapshots__/SettingsChange.test.tsx.snap
apps/web/src/features/myAccounts/components/AccountItems/MultiAccountItem.tsx
apps/web/src/features/myAccounts/components/AccountItems/SingleAccountItem.tsx
apps/web/src/features/myAccounts/components/AccountItems/styles.module.css
apps/web/src/features/spaces/components/SpaceCreationModal/index.tsx

Resolves https://github.com/safe-global/wallet-private-tasks/issues/169
Resolves https://github.com/safe-global/wallet-private-tasks/issues/170
- Uses `EthHashInfo` within `SingleAccountItem` and `MultiAccountItem`
- Adds a more useful error message when reaching the space creation limit
2. Add safes to that space
3. Hover over the address in the list
4. Observe a "Copy to clipboard" tooltip
5. Click the address
6. Observe the address is copied and the user is not navigated to that safe
7. Click anywhere else
8. The user is navigated to that safe
9. Accounts page and safe sidebar will also have this change
10. Add a safe address (multi-chain and single chain) to your address book
11. Observe the name shows up only once in the list

Fix(Spaces): Use EthHashInfo for SafeList items to support copy

---

apps/web/src/features/spaces/components/SpaceAddressBook/SpaceAddressBookTable.tsx

Resolves https://github.com/safe-global/wallet-private-tasks/issues/168
- Fixes the crash when trying to order address book entries by network
- Orders entries by the number of networks they have
2. Go to address book
3. Order by networks
4. Observe the ordering happens by number of networks

Fix(Spaces): Order networks by length in spaces address books

---

apps/web/src/components/settings/ProposersList/index.tsx
apps/web/src/components/settings/owner/OwnerList/index.tsx
apps/web/src/pages/settings/setup.tsx

This PR fixes misalignment between Signers and Proposers sections on the Settings page with smaller viewports.
Resolves #4554
- Introduces a shared `Grid` container for the entire Members section in `setup.tsx`
- Removes left `Grid` wrappers for signers and proposers.
- Add both OwnerList and ProposersList components inside a single `Box` to unify their structure and responsiveness.
- Go to the settings page
- Make the viewport smaller
- Observe the signers section and the proposers section aligned all time
https://github.com/user-attachments/assets/20823900-a27a-45b3-b638-2c8814f47ff6

fix(web): align signers and proposers sections

---

apps/web/src/features/spaces/components/SpaceAddressBook/index.tsx
apps/web/src/features/spaces/hooks/useAddressBookSearch.ts

Resolves https://github.com/safe-global/wallet-private-tasks/issues/111
- Adds a new hook `useAddressBookSearch`
- Use that hook inside the address book component
2. Go to address book
3. Search for name or address
4. Observe it working
5. Search for something that doesn't exist
6. Observe a 0 results found screen

Feat(Spaces): Add space address book search

---

apps/web/src/features/spaces/components/SpaceAddressBook/Import/ContactsList.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/Import/ImportAddressBookDialog.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/Import/__tests__/ImportAddressBookDialog.test.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/useContactSearch.ts

Resolves https://github.com/safe-global/wallet-private-tasks/issues/114#issuecomment-2808143091
- Removes the `Select all` button because the behaviour is not clear when encountering the same address multiple times
- Filters out address book entries on chains that are not active (e.g. old chains that have now been deactivated)
2. Go to the address book
3. Press import
4. Observe only entries on active chains are displayed
5. Observe no Select all button

Fix(Spaces): Filter address book entries by active chains

---

apps/web/src/components/tx-flow/flows/NewSpendingLimit/CreateSpendingLimit.tsx
packages/utils/src/components/tx/security/tenderly/utils.ts

Hi! I fixed two broken links referencing Safe contract implementations.
rename `GnosisSafeStorage.sol` - `SafeStorage.sol`
ref: https://github.com/safe-global/safe-smart-account/commits/main/contracts/libraries/SafeStorage.sol

chore: fixed broken links

---

apps/mobile/src/theme/hooks/useTheme.tsx

useColorSchema hook changes the current theme when app enters in background because the OS takes what is called a 'snapshot' on iOS, to facilitate the preview when you browse your open applications; a snapshot is required for both light & dark mode in case you change modes while on the open application screen, so the OS will report a brief moment in time both light & dark mode where the app should respond to these modes, or risk a flawed snapshot
It adds an event listener in the app using AppState instance and every time the nextAppState is `active` (when the app is resumed), it sets the theme to use the right theme. 
Follow the steps described in the issue: https://github.com/safe-global/wallet-private-tasks/issues/23

Fix(mobile): put the current theme in a local state to avoid side effects of useColorScheme hook

---

apps/web/src/components/tx-flow/actions/index.ts
apps/web/src/components/tx-flow/features/index.ts

No need to lazily import these components as the entire tx flows are already lazily imported.
It does make sense to lazily import individual features but it has to be done conditionally inside the feature hierarchy. E.g. if the user selects "add to batch" – lazy-load the batching feature.

Refactor(Signing UX): use static import for "features" and "actions"

---

apps/web/src/components/transactions/TxDetails/Summary/index.tsx
apps/web/src/components/transactions/TxDetails/TxData/DecodedData/index.tsx
apps/web/src/components/tx-flow/TxFlow.tsx
apps/web/src/components/tx/ReviewTransactionV2/ReviewTransactionContent.tsx
apps/web/src/components/tx/ReviewTransactionV2/__tests__/__snapshots__/ReviewTransactionContent.test.tsx.snap
apps/web/src/components/tx/ReviewTransactionV2/__tests__/__snapshots__/index.test.tsx.snap

Show the sign/execute/batch submit button on the Receipt step only and remove it from the transaction review step.
This is to avoid confusion in the signing process (see [this comment](https://github.com/safe-global/safe-wallet-monorepo/issues/5416#issuecomment-2819974099)).
1. Open update threshold transaction flow.
2. Continue to the transaction review step
3. Observe a "Continue" button instead of the combo button

fix(Signing UX): revert to show combo button only on final receipt step

---

apps/mobile/src/app/(tabs)/transactions/_layout.tsx

Resolves https://github.com/safe-global/wallet-private-tasks/issues/175
It adds a SafeAreaView into the transaction history list to avoid having the system icons being overlap by the screen title. Looks like all the screen on android are overlapping the system icons when user has not imported the wallet yet though.
- Remove the current app from your phone
- Install it again
- add a wallet
- go to transaction history tab
- The screen title should not be overlapping the system icons anymore.

Fix(mobile): transaction history title overlaping system icons

---

apps/mobile/src/components/SafeTab/SafeTabBar.tsx
apps/mobile/src/features/Assets/components/AssetsHeader/AssetsHeader.tsx
apps/mobile/src/features/Assets/components/ReadOnly/ReadOnly.container.tsx
apps/mobile/src/features/Assets/components/ReadOnly/ReadOnly.tsx

Resolves https://github.com/safe-global/safe-wallet-monorepo/issues/5717
It increases the measures for tab buttons and margins for the readonly alert. 
| **Before** | **After** |
|------------|-----------|
| <img width="400" alt="Screenshot 2025-04-23 at 13 06 59" src="https://github.com/user-attachments/assets/d8f3eebb-f6f1-4e54-9dab-2a96c1a3bb23" /> |  <img width="502" alt="Screenshot 2025-04-23 at 15 26 21" src="https://github.com/user-attachments/assets/26483b14-2a15-451d-8cbf-438eeca22db3" /> |

Fix(mobile): improve tab buttons accessibility

---

apps/web/src/components/tx-flow/flows/RecoveryAttempt/RecoveryAttemptReview.tsx
apps/web/src/features/recovery/services/recovery-sender.ts

Resolves inability to execute a recovery attempt with a Ledger device.
Similar to issues [creating recovery attempts](https://github.com/safe-global/safe-wallet-monorepo/pull/5738#issuecomment-2823012481), which was resolved by passing a gas estimation (882b672fe3b79a0d153186f8722ce57985b03813), this propagates the same changes to execution flow. Without an estimation, no gas is passed is present in the raw transaction.
If we see this issue again, we should consider adding gas estimation to the Ledger module (although it wasn't there previously).
It should be possible to successfully create and execute a recovery attempt with a (directly connected) Ledger device.

fix(web): estimate gas for recovery attempt execution

---

apps/web/src/services/onboard/ledger-module.ts

Resolves https://github.com/safe-global/wallet-private-tasks/issues/186
Instead of relying on the `lastValueFrom` of an action, we not explicitly subscribe to it and only `resolve`/`reject` if the status of it is complete or erroneous.
Each `signer` action returns an observable, of which there is an "action state" with [multiple states](https://github.com/LedgerHQ/device-sdk-ts/tree/develop/packages/signer/signer-eth#-observable-behavior). These encompass successful execution, errors and "intermediate" states (e.g. a locked device).
We were previously trusting the `lastValueFrom` of each observable but, after a device previously locked, the last "state" is not successful, but rather erroneous - not being able to make RPC requests.
This migrates from using `lastValueFrom` to explicitly …

fix(web): explicitly handle Ledger statuses

---

apps/web/src/features/bridge/components/BridgeWidget/index.test.tsx
apps/web/src/features/bridge/components/BridgeWidget/index.tsx

The bridge widget being able to determine the current chain.
In order to restrict config. within the bridge widget, it needs to know the current chain. This add a new `fromChain` query param. to the widget URL with the current chain ID.
Observe no option to select other chains.

feat(web): pass current chain to bridge widget

---

apps/web/src/features/walletconnect/components/WcProposalForm/CompatibilityWarning.tsx
apps/web/src/features/walletconnect/components/WcProposalForm/styles.module.css

This PR fixes the horizontal scrolling issue in the Compatibility Warning modal when using WalletConnect.
Resolves #4927
- Adds `.chainContainer` element 
- Updates styles for `.chain` and `.origin` elements to ensure proper wrapping and spacing.
- Attempt to connect to OpenSea using WalletConnect on Sepolia.
- Open the console and copy an element that contains a chain (e.g. from the modal).
- Paste and duplicate it in the console to simulate a long list of chains.

fix(web): fix horizontal scrolling on WC modal

---

apps/mobile/src/components/transactions-list/Card/TxOrderCard/SellOrder.tsx
apps/mobile/src/components/transactions-list/Card/TxOrderCard/TwapOrder.tsx
apps/mobile/src/components/transactions-list/Card/TxOrderCard/__snapshots__/TxOrderCard.test.tsx.snap

It solve the way how we're display the information about the swap / twap tokens.
Resolves https://github.com/safe-global/wallet-private-tasks/issues/135
After discussing to the PO, we decided to add a "~" which makes more sense then just removing the information of the amount exchanged by the token.
Follow the instructions on this issue:  https://github.com/safe-global/wallet-private-tasks/issues/135

fix(mobile): display info about swap and twap

---

apps/mobile/src/features/GetStarted/GetStarted.tsx

Resolves https://github.com/safe-global/wallet-private-tasks/issues/174
It removes the join account button from the code since it is not necessary now.
- Uninstall the app if you already have it and install it again
- Click in Get Started button
**Expected behavior**
Join account button should not appear anymore.

Fix(mobile): remove join account button

---

apps/mobile/app.config.js
apps/mobile/src/theme/provider/font.tsx

Expo splash screens has some inconsistencies as [this](https://github.com/expo/expo/issues/32515) on Android platform when using a full image as splash scree,
Resolves #
https://github.com/safe-global/wallet-private-tasks/issues/165
Implement a custom splash screen to be used on Android devices

fix(mobile): Implement custom splash screen solution for Android

---

apps/mobile/src/features/Assets/components/Navbar/Navbar.tsx
apps/mobile/src/features/Settings/components/Navbar/SettingsMenu.tsx

The bug was caused by introducing react-native-gesture-handler as suggested [here](https://github.com/expo/expo/issues/34683) and [here](https://github.com/react-navigation/react-navigation/issues/7052), as a side effect.
Resolves #
https://github.com/safe-global/wallet-private-tasks/issues/142
We reverted the usage of such library while replacing the onPress handler by onPressIn.

fix(mobile): Revert gesture-handler usage while add style inline with Figma

---

apps/mobile/src/app/(tabs)/transactions/_layout.tsx

After the fix on the title being displayed under the phone status bar, we introduced an issue of having the view with an unnecessary padding bottom.
It adds an `edge=['top']` prop, so the place affected will be only in the top of the view
- Go to tx history list and check if the list is being cut at the bottom
| Before | After |
|----------|----------|
| <img width="458" alt="Screenshot 2025-04-25 at 12 39 23" src="https://github.com/user-attachments/assets/5373c68e-7c5d-48cd-b1a0-10928dea44e7" /> | <img width="502" alt="Screenshot 2025-04-25 at 12 42 16" src="https://github.com/user-attachments/assets/e38b773c-3f34-4a49-a555-1a338cc9c04c" /> |

Fix(mobile): remove padding bottom on tx history

---

apps/web/src/features/spaces/components/AddAccounts/SafesList.tsx
apps/web/src/features/spaces/components/AddAccounts/index.tsx
apps/web/src/features/spaces/components/AddAccounts/styles.module.css
apps/web/src/features/spaces/components/AddMemberModal/MemberInfoForm.tsx
apps/web/src/features/spaces/components/AddMemberModal/index.tsx
apps/web/src/features/spaces/components/AddMemberModal/styles.module.css
apps/web/src/features/spaces/components/MembersList/MemberName.tsx
apps/web/src/features/spaces/components/SpaceSidebarNavigation/config.tsx
apps/web/src/features/spaces/components/SpaceSidebarSelector/index.tsx

Resolves https://www.notion.so/safe-global/MVP-Feedback-1c88180fe57380c498d4ec2e105f3037?pvs=4#1c88180fe573804494baf9b5f9edf56a
- Fixes the multichain item hover color when adding safe accounts
- Fixes the add safe accounts dialog layout when on smaller screens
- Adjusts the sidebar selector color in dark mode
- Adjusts the sidebar Soon color in dark mode
- Adjusts the hover color of member roles on hover
- Capitalizes the "you" in the member list
1. Open a space and compare elements with the feedback document screenshots

Fix(Spaces): Adjust Spaces UI elements

---

apps/mobile/src/features/ActionDetails/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/GenericView/GenericView.tsx

Resolves https://github.com/safe-global/wallet-private-tasks/issues/25
It takes the information from the `txData` contract call instead the `txInfo`.
Please follow the steps described in this ticket: https://github.com/safe-global/wallet-private-tasks/issues/25
ps: the logo is white because we're pointing to staging endpoint, which some urls returns "access denied".

Fix(mobile): Show correct info in the action details

---

apps/mobile/src/features/AccountsSheet/MyAccounts/MyAccountsFooter.test.tsx
apps/mobile/src/features/AccountsSheet/MyAccounts/MyAccountsFooter.tsx

Resolves https://github.com/orgs/safe-global/projects/1/views/10?pane=issue&itemId=106238218&issue=safe-global%7Cwallet-private-tasks%7C174
It removes the join account code from `account-sheet` view.
- Add a wallet in the app
- Go to your account dropdown
**Expected behavior**
Join account button should not appears anymore.

Fix(mobile): Remove "Join Account" button from account sheet

---

apps/web/src/components/transactions/TxDetails/TxData/NestedTransaction/OnChainConfirmation/index.tsx
apps/web/src/components/tx/security/tenderly/index.tsx

Resolves [this comment](https://github.com/safe-global/safe-wallet-monorepo/pull/5752#issuecomment-2833793865)
Updates the simulation params to use the correct values for nested transactions:
* **Safe info**: pass the nested Safe`s info 
* **executionOwner**: pass the parent Safe address which is signing the onchain confirmation

fix(Nested transactions): nested transaction simulation params

---

apps/web/src/components/common/EthHashInfo/SrcEthHashInfo/index.tsx
apps/web/src/components/common/EthHashInfo/index.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/AddContact.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/AddressBookContextMenu.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/EditContactDialog.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/Import/ContactsList.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/Import/ImportAddressBookDialog.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/Import/__tests__/ImportAddressBookDialog.test.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/SpaceAddressBookTable.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/__tests__/utils.test.ts
apps/web/src/features/spaces/components/SpaceAddressBook/utils.ts
apps/web/src/services/analytics/events/spaces.ts

Resolves https://github.com/safe-global/wallet-private-tasks/issues/192
- Adds the upsertion call to the Import, Add contacts and Edit contact dialog
- Shows a success message if it succeeds
- Adds tracking for edit and remove to the buttons
- Disables items during the import if they are already added
2. Go to address book
3. Press the import button and select one or more items
4. Submit the form
5. Observe a success message and the items show up in the list
6. Do the same with Add contact
7. Do the same with Edit contact
8. Make sure there are GA events when opening and submitting each action (import, add, edit)

Feat(Spaces): Implement address book upsertion

---

apps/web/src/features/spaces/components/SpaceAddressBook/DeleteContactDialog.tsx
packages/store/scripts/api-schema/schema.json
packages/store/src/gateway/AUTO_GENERATED/spaces.ts

Resolves https://github.com/safe-global/wallet-private-tasks/issues/193
- Integrates the DELETE endpoint in the delete dialog
1. Open a space with address book items
2. Delete one
3. Observe a success message
4. Observe that the item is gone from the list

Feat(Spaces): Implement deletion of address book items

---

apps/mobile/src/features/ActionDetails/utils.tsx

Resolves https://github.com/orgs/safe-global/projects/1/views/10?pane=issue&itemId=103102381&issue=safe-global%7Cwallet-private-tasks%7C25
It adds the `to` information of the action, in case the contractCall info is not present.
follow the steps described in the issue: https://github.com/orgs/safe-global/projects/1/views/10?pane=issue&itemId=103102381&issue=safe-global%7Cwallet-private-tasks%7C25 and the contract address with icon should appears in the enable module action.

Fix(mobile): show contract name in enable module action

---

apps/mobile/src/components/Badge/Badge.tsx
apps/mobile/src/components/Badge/theme.ts
apps/mobile/src/features/ConfirmTx/components/confirmation-views/AddSigner/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/Contract/Contract.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/Contract/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/GenericView/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/RemoveSigner/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/SendNFT/utils.tsx
apps/mobile/src/features/ConfirmTx/hooks/useOpenExplorer/useOpenExplorer.ts

Resolves https://github.com/orgs/safe-global/projects/1/views/10?pane=issue&itemId=103133072&issue=safe-global%7Cwallet-private-tasks%7C33
- Hides the parameters button in the header of multisend contract
- Adjust the border of the Logo component in light mode
- Adds explorer link functionality for all the confirmation views that are missing this implementation.
Follow the steps described here: https://github.com/orgs/safe-global/projects/1/views/10?pane=issue&itemId=103133072&issue=safe-global%7Cwallet-private-tasks%7C33

Fix(mobile): Adjust multiSend confirmation view to be according to figma

---

apps/mobile/src/features/Signer/Signer.container.tsx

We are hitting this bug: https://github.com/expo/expo/issues/36475. If the screen in question is neested in a navigator the useNavigation hook from expo-router doesn’t end up on the current screen and calling setOptions doesn’t update the options on the correct screen.
Resolves #
Can't set a signer name

fix(mobile): can’t edit signer

---

apps/mobile/src/features/ImportReadOnly/ImportAccountForm.container.tsx

Resolves https://github.com/safe-global/wallet-private-tasks/issues/86
It checks if the safe has any overview result, if it doesn't we show "Safe not found" error message bellow the input.
follow the steps described on this issue: https://github.com/safe-global/wallet-private-tasks/issues/86

fix(mobile): validate EOA in import safe flow

---

apps/web/src/components/tx-flow/TxFlow.tsx
apps/web/src/components/tx-flow/TxFlowProvider.tsx
apps/web/src/components/tx-flow/actions/Batching/index.tsx
apps/web/src/components/tx-flow/flows/CancelRecovery/CancelRecoveryFlowReview.tsx
apps/web/src/components/tx-flow/flows/CancelRecovery/CancelRecoveryOverview.tsx
apps/web/src/components/tx-flow/flows/CancelRecovery/index.tsx

Migrates the CancelRecoveryFlow to the new logic.
Also adds `isBatchable` flag to TxFlowContext.

refactor(CancelRecoveryFlow): migrate to new TxFlow logic

---

apps/web/src/components/tx-flow/SafeTxProvider.tsx

The recommended nonce is not used when creating a new transaction
Fixes the condition such that the `SafeTxProvider` uses the `recommendedNonce` when the form can be edited.
- Create a new transaction in a Safe that has queued transactions
- Observe that the nonce is chosen correctly to be at the end of the queue

fix(web): use recommended nonce when editing the nonce is allowed

---

apps/mobile/src/components/transactions-list/Card/TxContractInteractionCard/TxContractInteractionCard.tsx

Resolves https://github.com/safe-global/wallet-private-tasks/issues/105
It adds a flex: 1 property in the parent container of the icon to make it to have the full height of the its container, align it with flex properties and also changes the font-size of the icon in order to make it smaller.
Go to any safe tx history and look for a contract interaction transaction.

fix: contract icon size

---

apps/mobile/src/features/ActionDetails/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/AddSigner/AddSigner.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/AddSigner/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/Contract/Contract.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/Contract/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/GenericView/GenericView.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/GenericView/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/RemoveSigner/RemoveSigner.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/RemoveSigner/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/SendNFT/SendNFT.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/SendNFT/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/Stake/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/SwapOrder/utils.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/TokenTransfer/TokenTransfer.tsx
apps/mobile/src/features/ConfirmTx/hooks/useOpenExplorer/index.ts

Resolves https://github.com/safe-global/wallet-private-tasks/issues/26
It uses the useViewExplorer hook in the confirm token transaction view.
please follow the steps described here: https://github.com/safe-global/wallet-private-tasks/issues/26

Fix(mobile): Etherscan link for token transactions

---

apps/mobile/firebase.json
apps/mobile/src/app/_layout.tsx
apps/mobile/src/app/developer.tsx
apps/mobile/src/features/Developer/components/Developer.tsx
apps/mobile/src/features/GetStarted/GetStarted.tsx
apps/mobile/src/hooks/useScreenTracking.ts

Currently when we get a crash report uploaded to crashlytics we don't have any breadcrumbs and don't know which screens the user visited. 
We enabled analytics collection and are uploading the screen the user is to analytics. This gets combined with the crash data and we get a nice breadcrumb like this:
On the settings page, click 3 times on the safe version, navigate into the hidden Developer menu and hit the "crash app" button. This will generate a dummy crash report and send it to crashylitics once you start the app again. 
**Note**: analytics collection is only enabled during the onboarding when the user clicks on "get started" and creates a safe. This means that we won't be getting this data for users that have already imported a safe.

feat(mobile): track visited screens for crashlytics

---

apps/mobile/src/features/ConfirmTx/components/SignTransaction/SignError.tsx

We currently don't support execution, only signing so the text is misleading
Resolves https://github.com/safe-global/wallet-private-tasks/issues/217
Changes the text
Somehow trigger a signing error(disconnecting from network before hitting the sign button)

fix(mobile): change error text

---

apps/mobile/src/components/TxInfo/TxInfo.tsx
apps/mobile/src/components/transactions-list/Card/TxBatchCard/TxBatchCard.tsx
apps/mobile/src/components/transactions-list/Card/TxContractInteractionCard/TxContractInteractionCard.tsx

If the gateway returns a safeAppName for a contract interactioin we display it instead of the method name.
Resolves 
https://github.com/safe-global/wallet-private-tasks/issues/132
1. open sep:0x2a73e61bd15b25B6958b4DA3bfc759ca4db249b9
2. Tx 776 is a batch tx made with the tx builder.
before:
after:

fix(mobile): display safe app name if provided

---

apps/mobile/src/features/ConfirmTx/ConfirmTx.container.tsx
apps/mobile/src/features/ConfirmTx/components/CanNotSign/CanNotSign.test.tsx
apps/mobile/src/features/ConfirmTx/components/CanNotSign/CanNotSign.tsx
apps/mobile/src/features/ConfirmTx/components/CanNotSign/__snapshots__/CanNotSign.test.tsx.snap
apps/mobile/src/features/ConfirmTx/components/ConfirmTxForm/ConfirmTxForm.test.tsx
apps/mobile/src/features/ConfirmTx/components/ConfirmTxForm/ConfirmTxForm.tsx

The recent fix for the "ready to execute view" caused a crash when there is no active signer https://github.com/safe-global/safe-wallet-monorepo/pull/5828
We now accept the fact that the user might not have a signer imported and don't render the signer selector component that was causing the crash. 
1. Import a safe with pending txs
2. Make sure that you have no signers imported for it
3. Navigate to a pending tx
4. Observe no crash

fix(mobile): crash when there are no active signers

---

apps/mobile/src/features/Developer/components/Developer.tsx
apps/mobile/src/features/GetStarted/GetStarted.tsx
apps/mobile/src/hooks/useScreenTracking.ts
apps/mobile/src/services/notifications/FCMService.ts
apps/mobile/src/services/notifications/NotificationService.ts

https://rnfirebase.io/migrating-to-v22
We were already using version 22, but the code we were using the old syntax. Because of this our developer console was poluted by a mile long messages that we use the API incorrectly.
Changes to the Modular Web API syntax.
You should no longer see any react-native-firebase message logged in the developer console

refactor(mobile): migrate to v22

---

apps/web/src/features/spaces/components/Dashboard/AddAccountsCard.tsx
apps/web/src/features/spaces/components/Dashboard/ImportAddressBookCard.tsx
apps/web/src/features/spaces/components/Dashboard/MembersCard.tsx
apps/web/src/features/spaces/components/Dashboard/SpacesCTACard.tsx
apps/web/src/features/spaces/components/Dashboard/styles.module.css
apps/web/src/features/spaces/components/SpaceAddressBook/Import/ContactsList.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/Import/ImportAddressBookDialog.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/index.tsx
apps/web/src/features/spaces/hooks/useGetAddressBook.ts
apps/web/src/features/spaces/hooks/useGetSpaceAddressBook.ts
apps/web/src/services/analytics/events/spaces.ts

Part of https://github.com/safe-global/wallet-private-tasks/issues/114
- Adds the `ImportAddressBookDialog` to the dashboard when pressing the import button
- Adds an event when submitting the import
- Shows a Done state when there are entries in the space address book
- Extracts logic to get space address book into a custom hook `useGetAddressBook`
1. Create a new space
2. Observe an address book card on the dashboard
3. Press the import button
4. Observe the import dialog opens
5. Import contacts from your local address book
6. Observe a done state instead of the import button

Fix(Spaces): Add Done status to spaces dashboard if address book imported

---

apps/mobile/src/app/(import-accounts)/form.tsx
apps/mobile/src/components/SafeAccountInput/hooks/useImportSafe.ts
apps/mobile/src/components/SafeAccountInput/index.tsx
apps/mobile/src/features/ImportReadOnly/ImportAccountForm.container.tsx
apps/mobile/src/features/ImportReadOnly/components/ImportAccountFormView.tsx
apps/mobile/src/features/ImportReadOnly/types.ts

Resolves https://github.com/safe-global/wallet-private-tasks/issues/218 and https://github.com/safe-global/wallet-private-tasks/issues/86
It changes the way of how we're using react-hook-form on this screen to be according to its docs. Previously we were having conflicts with react-hook-form internal state due to validating/request the address outside the zod schema and the Controller component.
- Get an cleaned app
- Try to import a valid safe: button should be green and the chains should appear
- Try to import a EOA address: button should be disabled and the error message should appears
- Try to import a valid safe again: button should be green and the chains should appear again.

Fix(mobile): import safe refactor

---

apps/mobile/src/components/Badge/theme.ts

In light mode the status text of a swap was not visible.
Resolves https://github.com/safe-global/wallet-private-tasks/issues/137
Switches the text color to the value from the figma design.
Create a swap and view it in light mode
before:
after:

fix(mobile): wrong status theme in light mode

---

apps/mobile/src/features/Signers/components/SignersList/SignersListItem.tsx

Resolves https://github.com/safe-global/wallet-private-tasks/issues/130
Now we check in the item click, if the user is coming from the import safe flow or not. If the `import_safe` parameter is passed and the signer that we clicked is not a imported signer, we redirect him to the import signer flow.
Check https://github.com/safe-global/wallet-private-tasks/issues/130
https://github.com/user-attachments/assets/e3875d99-3068-410d-8e39-64881f945d5f

fix: redirect user to the import signer flow if he cames from import safe flow

---

apps/mobile/src/features/ConfirmTx/components/ConfirmTxForm/ConfirmTxForm.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/AlreadySigned/AlreadySigned.test.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/AlreadySigned/AlreadySigned.tsx

Resolves https://github.com/safe-global/wallet-private-tasks/issues/15
Now we show "Can be executed once the threshold is reached" when there isn't enough confirmations but all the imported signers in the app has already signed
follow the steps described by @liliya-soroka on this issue: https://github.com/safe-global/wallet-private-tasks/issues/15

fix(mobile): change the sign feedback message

---

apps/mobile/src/components/TokenAmount/TokenAmount.tsx
apps/mobile/src/components/TxInfo/TxInfo.tsx
apps/mobile/src/components/transactions-list/Card/StakingTxDepositCard/StakingTxDepositCard.stories.tsx
apps/mobile/src/components/transactions-list/Card/StakingTxDepositCard/StakingTxDepositCard.test.tsx
apps/mobile/src/components/transactions-list/Card/StakingTxDepositCard/StakingTxDepositCard.tsx
apps/mobile/src/components/transactions-list/Card/StakingTxDepositCard/__snapshots__/StakingTxDepositCard.test.tsx.snap
apps/mobile/src/components/transactions-list/Card/StakingTxDepositCard/index.tsx
apps/mobile/src/components/transactions-list/Card/StakingTxExitCard/StakingTxExitCard.stories.tsx
apps/mobile/src/components/transactions-list/Card/StakingTxExitCard/StakingTxExitCard.test.tsx
apps/mobile/src/components/transactions-list/Card/StakingTxExitCard/StakingTxExitCard.tsx
apps/mobile/src/components/transactions-list/Card/StakingTxExitCard/__snapshots__/StakingTxExitCard.test.tsx.snap
apps/mobile/src/components/transactions-list/Card/StakingTxExitCard/index.tsx
apps/mobile/src/components/transactions-list/Card/StakingTxWithdrawCard/StakingTxWithdrawCard.stories.tsx
apps/mobile/src/components/transactions-list/Card/StakingTxWithdrawCard/StakingTxWithdrawCard.test.tsx
apps/mobile/src/components/transactions-list/Card/StakingTxWithdrawCard/StakingTxWithdrawCard.tsx
apps/mobile/src/components/transactions-list/Card/StakingTxWithdrawCard/__snapshots__/StakingTxWithdrawCard.test.tsx.snap
apps/mobile/src/components/transactions-list/Card/StakingTxWithdrawCard/index.tsx
apps/mobile/src/utils/transaction-guards.ts
packages/store/src/gateway/types.ts

Staking txs were missing decoding in the history and as such were not shown at all
Resolves https://github.com/safe-global/wallet-private-tasks/issues/225
Ads decoding for
- staking deposit
- staking withdraw
- staking claim
Import eth:0xAD1Cf279D18f34a13c3Bf9b79F4D427D5CD9505B and check the history tab. You should see the staking tx in the history now.

feat(mobile): add missing staking tx cards in history

---

apps/mobile/src/features/GetStarted/GetStarted.tsx

The double nesting of Text seems to cause the problem as the tappable area ends up being too small. 
Resolves https://github.com/safe-global/safe-wallet-monorepo/issues/4952
We no longer nest text within text and this seems to make the tappable area bigger.
On the getting started screen tap on "user terms" and "privacy policy" - the buttons should be easy to tap and shouldn't require you hitting the text directly in the middle.

fix(mobile): user terms and privacy hard to click

---

apps/mobile/package.json
yarn.lock

The plugin broke when we updated to expo sdk53. 
https://github.com/matt-oakes/redux-devtools-expo-dev-plugin/pull/22
Updates the package to v2.
`yarn start` to start the metro server and then shift+m and select the redux-devtools. You should see the redux actions

chore(mobile): update redux-devtools-expo-dev-plugin

---

apps/web/package.json
yarn.lock

The latest deployment has support for hoodi which we need on staging.

web(chore): update safe-deployments to v1.37.22

---

apps/mobile/src/app/_layout.tsx
apps/mobile/src/store/index.ts
packages/store/package.json
packages/store/src/gateway/cgwClient.ts
packages/store/src/utils/persistTransformFilter.test.ts
packages/store/src/utils/persistTransformFilter.ts
packages/store/tsconfig.json
yarn.lock

Currenlty we had to wait for the app to fetch the chainConfig. It doesn’t change that often, so it makes sense that we persist it and use it directly when the app starts. Then we dispatch a new fetch and can update it if something has changed.
Launch the app, hit cmd + shift in the terminal and open redux dev tools. Add a safe, Reload the app and inspect the rehydrate action. You should see it having the query and config objects

feat(mobile): rehydrate chainConfig slice

---

apps/web/src/components/transactions/TxDetails/Summary/index.tsx
apps/web/src/components/transactions/TxDetails/TxData/DecodedData/Multisend/index.tsx
apps/web/src/components/tx-flow/flows/NftTransfer/ReviewNftBatch.tsx
apps/web/src/components/tx-flow/flows/NftTransfer/SendNftBatch.tsx
apps/web/src/components/tx/ReviewTransaction/__tests__/__snapshots__/index.test.tsx.snap
apps/web/src/components/tx/ReviewTransactionV2/__tests__/__snapshots__/ReviewTransactionContent.test.tsx.snap
apps/web/src/components/tx/ReviewTransactionV2/__tests__/__snapshots__/index.test.tsx.snap
apps/web/src/components/tx/SignOrExecuteForm/__tests__/__snapshots__/SignOrExecute.test.tsx.snap

Resolves https://www.notion.so/safe-global/Repeated-data-field-in-the-Send-NFT-tx-1f38180fe5738034871cef3bc475a073
I've removed the raw data fallback in the Multisend component because we display the same data in the advanced details.

Fix(Tx flow): don't show hex data as a fallback in multisend

---

apps/web/src/store/settingsSlice.ts

Copying the chain prefix is confusing to many users as most wallets and dapps still don't support this format.
This PR disables copying prefixes when copying addresses by default. It's still possible to enable it in user preferences.

Fix(web): don't copy chain prefix when copying addresses

---

apps/web/src/components/settings/ContractVersion/index.tsx
apps/web/src/components/sidebar/SidebarNavigation/index.tsx
apps/web/src/hooks/useSafeNotifications.ts
apps/web/src/services/tx/safeUpdateParams.ts
apps/web/src/utils/__tests__/chains.test.ts
packages/utils/src/utils/chains.ts

The Safe version upgrade from 1.3.0 to 1.4.1 isn't critical, so we shouldn't show a notification for it. This will allow us to enable 1.4.1 in the config service.
* Skip notifications for 1.3.0 Safes
* Use the latest Safe version specified in the config service for both Safe upgrades and new Safe creations (previously it was only used for upgrades).

Feat(web): don't notify about 1.4.1 upgrades

---

apps/web/src/components/transactions/TxDetails/Summary/index.tsx
apps/web/src/components/tx/ConfirmTxDetails/Receipt.tsx

Resolves #5777 
Adds the signatures back to the advanced transaction details. On the final receipt screen in the flow, they are not shown.

fix(Signing UX): show signatures in advanced transaction details

---

apps/web/src/components/common/PaperViewToggle/index.tsx
apps/web/src/components/tx/ConfirmTxDetails/JsonView.tsx
apps/web/src/components/tx/ConfirmTxDetails/Receipt.tsx
apps/web/src/components/tx/ReviewTransaction/__tests__/__snapshots__/index.test.tsx.snap
apps/web/src/components/tx/ReviewTransactionV2/__tests__/__snapshots__/ReviewTransactionContent.test.tsx.snap
apps/web/src/components/tx/ReviewTransactionV2/__tests__/__snapshots__/index.test.tsx.snap
apps/web/src/components/tx/SignOrExecuteForm/__tests__/__snapshots__/SignOrExecute.test.tsx.snap

* Restore a JSON tab in the Receipt component
* Add a copy button

Feat(Tx flow): restore JSON view + copy button

---

apps/web/src/components/address-book/AddressBookHeader/index.tsx
apps/web/src/components/common/AddressBookInput/index.tsx
apps/web/src/components/common/AddressInputReadOnly/index.tsx
apps/web/src/components/common/Breadcrumbs/BreadcrumbItem.tsx
apps/web/src/components/common/EthHashInfo/SrcEthHashInfo/index.tsx
apps/web/src/components/common/EthHashInfo/index.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/EditContactDialog.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/SpaceAddressBookTable.tsx
apps/web/src/hooks/__tests__/useAllAddressBooks.test.ts
apps/web/src/hooks/useAllAddressBooks.ts

Resolves https://github.com/safe-global/wallet-private-tasks/issues/195
- Creates a new hook `useAllMergedAddressBooks` that merges the space address book with the local address book (for the current network)
- Creates a new hook `useAddressBookItem` that returns a specific item from the above hook
- Uses the newly created hooks inside `AddressBookInput` and `EthHashInfo` among other places where names need to be shown
- If the user is not signed in or no space has been visited or the current safe doesn't belong to a space fall back to the local address book
1. Open a space with an address book and safe accounts attached to it
2. Sign in and navigate to one of the safes
3. Observe the names shown either come from the local address book or space address book
4. Observe a different icon …

Feat(Spaces): Plug space address book into existing UI

---

apps/web/src/components/dashboard/index.tsx
apps/web/src/components/dashboard/styles.module.css
apps/web/src/features/spaces/components/SpacesDashboardWidget/index.tsx
apps/web/src/features/spaces/components/SpacesDashboardWidget/styles.module.css

Resolves https://github.com/safe-global/wallet-private-tasks/issues/235
- Updates the spaces dashboard banner layout
- Removed the info modal from there
1. Open a safe
2. Go the the dashboard
3. Observe the new banner design
4. It should still be possible to hide it and click on Try now

Fix(Spaces): Update spaces dashboard banner layout

---

apps/web/src/components/tx-flow/TxFlow.tsx
apps/web/src/components/tx/confirmation-views/index.tsx
apps/web/src/tests/builders/safeTx.ts
apps/web/src/utils/__tests__/transaction-guards.test.ts
apps/web/src/utils/transaction-guards.ts

https://www.notion.so/safe-global/Messages-sign-onchain-message-Signing-UX-v2-1f28180fe57380cdb1fbf68f905f19b8
- Hides the Transaction Details for SignMsgLib calls inside the ConfirmationView
- Sign a message on-chain (e.g. by enforcing on-chain sigs in `Settings / Safe Apps`

Fix(web): on chain signing confirmation view

---

apps/web/src/components/sidebar/NestedSafesPopover/index.tsx

https://www.notion.so/safe-global/Create-nested-safe-button-is-not-disabled-for-non-owners-add-as-a-task-to-monorepo-1f38180fe57380fcbdd3f6c709c0b554
- Wraps button in `<CheckWallet>` component
- Open the Nested Safes popover without being an owner of that Safe

fix(web): disable nested safe creation for non-owners

---

apps/web/src/hooks/useIsSidebarRoute.ts

Fixes a hydration error that occurs when loading a global settings page, such as `/settings/appearance`.
The issue is caused by different values of the `hasSafe` variable inside useIsSidebarRoute hook on client and server. This happens because `router.isReady` is always false on the server, while in the client it's true.
Moving the `router.isReady` check into an useEffect fixes it and is also recommended in the Next.js docs ([ref](https://nextjs.org/docs/pages/api-reference/functions/use-router#router-object)).

fix(useIsSidebarRoute): move `router.isReady` into useEffect to fix hydration error

---

apps/web/src/components/transactions/TxDetails/Summary/index.tsx
apps/web/src/components/transactions/TxDetails/TxData/index.tsx
apps/web/src/components/transactions/TxDetails/index.tsx
apps/web/src/components/tx/ReviewTransaction/__tests__/__snapshots__/index.test.tsx.snap
apps/web/src/components/tx/ReviewTransactionV2/__tests__/__snapshots__/ReviewTransactionContent.test.tsx.snap
apps/web/src/components/tx/ReviewTransactionV2/__tests__/__snapshots__/index.test.tsx.snap
apps/web/src/components/tx/SignOrExecuteForm/__tests__/__snapshots__/SignOrExecute.test.tsx.snap
apps/web/src/components/tx/confirmation-views/SettingsChange/index.tsx
apps/web/src/components/tx/confirmation-views/index.tsx

Resolves #5780 
Hide the contract interaction info in the transaction details accordion if it is already being rendered above. 
1. Create a transaction that has no custom decoding (e.g. a multiSend transaction)
2. In the confirmation view observe that the transaction details accordion does not show the contract interaction info as it is already being rendered above
3. Same should be the case for a transaction in the queue/history
4. The contract interaction info should still be visible for transactions that have a custom decoding (such as a token transfer)

fix(Signing UX): duplicate contract interaction info

---

apps/web/src/components/tx-flow/TxFlowStep.tsx
apps/web/src/components/tx-flow/flows/UpsertRecovery/UpsertRecoveryFlowIntro.tsx
apps/web/src/components/tx-flow/flows/UpsertRecovery/UpsertRecoveryFlowSettings.tsx

https://www.notion.so/safe-global/Safe-recovery-Signing-UX-v2-1f28180fe573806b9a4bff880e8f8016
- Passes the data correctly between steps
- Setup recovery on an account without recovery
- Change the recovery setup on an account with existing recoverers

fix(Recovery): pass data to second step of recovery flow

---

apps/web/package.json
apps/web/src/features/earn/components/VaultDepositConfirmation/index.tsx
apps/web/src/features/earn/components/VaultRedeemConfirmation/index.tsx

Only accesses tokenInfo of extra rewards if they exist

Hotfix(Earn): Only access extra rewards if they exist

---

apps/web/src/components/tx/ConfirmTxDetails/NameChip.test.tsx
apps/web/src/components/tx/ConfirmTxDetails/NameChip.tsx

https://www.notion.so/safe-global/Why-is-the-name-of-an-address-book-item-red-during-transaction-review-Signing-UX-v2-issue-1f38180fe57380c49d55eb1776b1f85e
- Does not mark addresses as unverified / untrusted when they are in the address book.
- Adds unit test to component

fix(web): do not mark address book addresses as untrusted in NameChip

---

apps/web/src/components/transactions/TxDetails/TxData/NestedTransaction/ExecTransaction/index.tsx

Resolves #5901
There are several issues with how nested transaction details are displayed for `execTransaction` calls:
1. The receipt shows a nonce of -1 for the nested transaction.
2. The Hashes tab only displays the Domain hash. Both the Message hash and safeTxHash are missing.
3. Switching to the JSON tab in the receipt causes the content to disappear, showing the error message: "Error parsing data".
For an execTransaction call we don't have all the data required to display the full nested transaction with the advanced tx details. 
Update the nestedTransaction data display for execTransaction calls to use the `TxData` component instead of `Summary`.
See the steps listed in #5901

fix(ExecTransaction): replace Summary component with TxData

---

apps/web/cypress/e2e/pages/create_tx.pages.js
apps/web/cypress/e2e/regression/tx_history_4.cy.js
apps/web/cypress/fixtures/txhistory_data_data.json

fixes for the regression tx_history_4 e2e suite
Resolves #
1. Removed the time check from the tests as it depends on the timezone.
2. Updated the check for the "Etherscan" link, since the copy button was removed from the transaction details.
3. Added a wait for the address book page body to load.
---

fix(tests): regression test tx_history_4

---

apps/web/src/components/common/Table/DataRow.tsx
apps/web/src/components/tx/confirmation-views/BatchTransactions/__snapshots__/BatchTransactions.test.tsx.snap
apps/web/src/features/earn/components/VaultDepositConfirmation/index.tsx
apps/web/src/features/earn/components/VaultRedeemConfirmation/index.tsx

Follow up for https://github.com/safe-global/wallet-private-tasks/issues/212
- Removes the link to the vault since its not available on prod
- Aligns the icon and name of the vault visually
1. Open a Safe on Base/Mainnet with deposit/withdraw transactions in the history
2. Go to the history and make sure icon and name of the vault are aligned
3. Do the same for the confirmation view
---

Fix(Earn): Align vault name with icon

---

apps/web/src/components/tx-flow/flows/NewSpendingLimit/ReviewSpendingLimit.tsx
apps/web/src/components/tx/ReviewTransaction/__tests__/__snapshots__/index.test.tsx.snap
apps/web/src/components/tx/ReviewTransactionV2/ReviewTransactionContent.tsx
apps/web/src/components/tx/confirmation-views/index.tsx

Reolves [this comment](https://github.com/safe-global/safe-wallet-monorepo/pull/5917#issuecomment-2904466322)
- Updated ReviewTransactionContent and ConfirmationView to accept a new optional prop `withDecodedData` to control the display of decoded transaction data.
- Modified ReviewSpendingLimit to pass `withDecodedData={false}` to ReviewTransaction, ensuring decoded data is not shown in this context.
Fix for e2e tests:
- Added Box component with `data-testid="beneficiary-address"` around beneficiary address to make sure the data-testid is in the DOM
1. Create a new transaction that modifies an existing spending limit
2. In the confirmation screen observe that there is no duplicate spending limit info anymore
---
With the submission of this Pull Request, I confirm that I have read and …

fix(Signing UX): remove duplicate info on spending limits confirmation view

---

apps/mobile/src/features/ConfirmTx/components/ConfirmationView/ConfirmationView.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/Contract/Contract.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/SendNFT/SendNFT.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/TokenTransfer/TokenTransfer.tsx

Resolves https://github.com/safe-global/wallet-private-tasks/issues/33
We add the parameters button back. Also added in the missing screens.
Propose different transactions and check if the parameters are displaying as expected. 
Some of the screens:
---

fix: add parameters button in the missing views

---

apps/web/src/components/tx-flow/flows/NftTransfer/ReviewNftBatch.tsx
apps/web/src/components/tx/confirmation-views/SettingsChange/SettingsChange.test.tsx
apps/web/src/components/tx/confirmation-views/SettingsChange/__snapshots__/SettingsChange.test.tsx.snap

Resolves [this comment](https://github.com/safe-global/safe-wallet-monorepo/pull/5917#issuecomment-2909304894)
Disable decoded data display in ReviewNftBatch component
1. Create a new NFT transfer transaction
2. In the confirmation screen observe that there is no duplicate NFT transfer info anymore
---

fix(Signing UX): remove duplicate NFT transfer info

---

apps/web/src/components/common/AddressInput/index.tsx
apps/web/src/components/new-safe/OwnerRow/index.tsx

Reset the signer name when the address field is being cleared.
* Introduce `onReset` callback in `AddressInput` component.
* Implement onReset in `OwnerRow` to clear the name field when the reset action occurs.
1. Open "Manage signers" flow from settings page
2. Add a signer row
3. Select an address from the address book
4. Observe the name field being populated with the name from the address book
5. Click the address field to clear the value
6. Observe the name field being cleared as well
https://github.com/user-attachments/assets/041921e2-03aa-44a7-b2fc-ce57aa3e145d
---

fix(Signing UX): reset signer name when address is cleared

---

apps/web/package.json
package.json
yarn.lock

We were resolving to different versions of ethers across the project and this was causing type mismatch.
Now `yarn lint` and `yarn build` work again.
---

fix(web): yarn lint was failing

---

apps/web/src/hooks/usePreventNavigation.ts

Resolves [EN-118](https://linear.app/safe-global/issue/EN-118/tenderly-report-is-opened-in-the-same-tab-as-the-safe-ui)
Allow to open external links in the Tx flow.
Don't use "prevent navigation" logic when clicking on links with target="_blank".
1. Start a Tx flow, e.g. transfer token
2. Proceed until the confirm step
3. Click on any external link (Safe utils, Tx decoder, Tenderly)
5. Observe that the link opens in a new tab
---

fix(Tx flow): allow navigation for links that open in a new tab

---

apps/mobile/src/features/ImportReadOnly/hooks/useScan/useScan.test.tsx

The test was failing because we wanted to mock a single function, but the other functions in the navigation object were wiped out by the mock. 
---

fix(mobile): useScan test was failing

---

packages/utils/package.json
packages/utils/src/components/tx/security/tenderly/__tests__/utils.test.ts
packages/utils/src/components/tx/security/tenderly/utils.ts
yarn.lock

Resolves https://github.com/safe-global/wallet-private-tasks/issues/226
When a guard is present, we overwrite the guard slot with the zero address it when simulating transactions.
- Setup a Safe with a Guard that blocks some transaction
- Queue a transaction that meets the blocking criteria
- Observe a successful simulation despite the guard
---

feat(utils): overwrite guard with zero address when simulating

---

apps/mobile/app.config.js
package.json

We need to bump the version number as apple won't accept new versions with the same version number, because 1.0.0 was approved. 
---

chore(mobile): bump mobile version number

---

apps/web/src/components/common/NamedAddressInfo/index.test.tsx
apps/web/src/components/common/NamedAddressInfo/index.tsx

Resolves [WAL-5951](https://linear.app/safe-global/issue/WAL-5951/verified-on-etherscan-contracts-are-displayed-as-unverified-on-ui)
Show "This Safe Account" when address matches Safe address.
Fixes the issue where the name was shown as "Unverified contract" when the address matched the Safe address.
Move the address comparison with the current Safe address to the useAddressName hook to ensure that the name is always displayed correctly.
1. Create a transaction that is sent to the Safe itself (e.g. a change threshold transaction)
2. Proceed to the Confirm transaction step and expand the transaction details accordion
3. Observe that the "To" value in the receipt has a "This Safe Account" name tag
4. Continue to the Review step and observe the same in the receipt there
5. Sign or execute …

fix(Signing UX): show name for address of Safe itself correctly

---

apps/web/src/features/spaces/components/MembersList/index.tsx
apps/web/src/features/spaces/components/SpaceSettings/LeaveSpaceDialog.tsx
apps/web/src/features/spaces/components/SpaceSettings/index.tsx
apps/web/src/features/spaces/components/SpaceSidebarNavigation/config.tsx
apps/web/src/features/spaces/components/SpaceSidebarNavigation/index.tsx
apps/web/src/features/spaces/hooks/useIsLastActiveAdmin.ts
apps/web/src/features/spaces/hooks/useSpaceMembers.tsx
apps/web/src/services/analytics/events/spaces.ts
packages/store/scripts/api-schema/schema.json
packages/store/src/gateway/AUTO_GENERATED/spaces.ts

Resolves [#116](https://github.com/safe-global/wallet-private-tasks/issues/116) - Allow active members to leave a space voluntarily
https://linear.app/safe-global/issue/EN-29/spaces-allow-members-to-leave-a-space
This PR enables users who are active members of a space to remove themselves from that space. Safeguards are included to prevent the last active admin from leaving.
> 🔗 **Note:** This change works in conjunction with related CGW updates [#2600](https://github.com/safe-global/safe-client-gateway/pull/2600).
- Added a “Leave space” button to the `SpaceSettings` view.
- Display a tooltip explaining why the button is disabled for the last active admin.
- Introduced `LeaveSpaceDialog` to confirm the action before proceeding.
- Display the Settings page in the sidebar navigation for …

feat(Spaces): leave a space

---

apps/web/cypress/e2e/pages/create_tx.pages.js
apps/web/cypress/e2e/regression/spending_limits.cy.js

The test counts the amount of external links. The system wasn't finding them
Makes the system search in the signers list
Run Spending_limit test. The scenario "Verify explorer links contain Sepolia link" should pass
---

fix(test): fix counting external links 

---

apps/web/src/components/balances/AssetsTable/FiatChange.tsx
apps/web/src/components/balances/AssetsTable/SendButton.tsx
apps/web/src/components/dashboard/Assets/index.tsx
apps/web/src/components/dashboard/PendingTxs/styles.module.css
apps/web/src/components/dashboard/styled.tsx
apps/web/src/components/theme/safeTheme.ts
apps/web/src/features/earn/components/EarnButton/index.tsx
apps/web/src/features/stake/components/StakeButton/index.tsx
apps/web/src/features/swap/components/SwapButton/index.tsx
packages/utils/src/utils/__tests__/formatNumber.test.ts
packages/utils/src/utils/formatNumber.ts

Resolves [EN-134](https://linear.app/safe-global/issue/EN-134/dashboard-update-top-assets-section)
- Updates the layout of the dashboard assets table according to Figma
- Adds buttons on hover
- Shows a percentage of total fiat value next to each item
- The percentage is hidden on mobile view
1. Open a Safe dashboard
2. Observe the new design for the assets overview
---

Fix(Dashboard): Update dashboard assets layout

---

apps/web/cypress/e2e/pages/create_tx.pages.js
apps/web/cypress/e2e/regression/create_tx_2.cy.js

Adds a test that was not being done. Checks that the values edited in adv params are correctly saved after submiting the form
Adds the scenario Verify advance parameters are saved after editing
Creates a new function to set the values and submit and one to get the values once they are set
Run the test create_tx_2.ts and all test should pass
---

feat(test): add adv params verification after editing

---

apps/web/src/features/proposers/components/UpsertProposer.tsx

Resolves [EN-91](https://linear.app/safe-global/issue/EN-97/dont-allow-to-add-an-owner-as-a-delegate)
Extended address validation in "Add proposer" to prevent adding a Safe owner as proposer.
1. Go to Safe settings and click "Add proposer"
2. Enter the address of an existing Safe owner
3. Observe a validation error:
> Cannot add Safe Owner as proposer
---

feat(Proposer): prevent adding owners as proposer

---

apps/mobile/src/features/Settings/components/Currency/CurrencyItem/CurrencyItem.tsx
apps/mobile/src/utils/currency.ts

I was too quick to merge the other PR. This ads just a small change to the display so that we don't display the currency synmbol when it is the same as the currency abbreviation.
---

fix(mobile): improve currency view

---

apps/web/cypress/e2e/regression/bulk_execution.cy.js

Fixes the verification of the actions listed in a bulk execution
Just changes the wordind of the action it was needed to find
Run regression/bulk execution and it should work fine
---

fix(web:e2e): fix action verfification in bulk tx

---

apps/mobile/src/features/ConfirmTx/components/confirmation-views/TokenTransfer/TokenTransfer.tsx

It fixes the buttons overlap problem in the sign tx screen
Open any token transaction in the pending transactions screen.
---

fix: copy button being overlaped in sign tx screen

---

yarn.config.cjs

Adding some @safe-global dependencies to the consistency check. This makes sure we won't forget to update them across all packages.  
---

chore: add more packages to the dependency check

---

apps/web/src/components/transactions/QueuedTxSimulation/index.tsx

The simulation in the queue is not respecting the simulation feature flag
Evaluates the feature flag when rendering the simulation in queue.
- Open a Safe on a chain without simulation support
- Observe the simulation not being present in the queue
---

fix(web): add feature flag for simulation in queue

---

apps/web/package.json

This PR fixes the missing version bump for Release 1.63.0.
The original release PR was merged without updating the package.json version, which caused the GitHub release creation to fail. This PR adds the missing version bump to trigger the release workflow.
- Bump apps/web/package.json version from 1.62.1 to 1.63.0
- Original Release 1.63.0 PR was merged but forgot version bump
- GitHub release workflow only triggers on PR merges, not direct commits
- This will create the missing v1.63.0 tag and GitHub release

Fix: Bump version to 1.63.0 for missed release

---

apps/mobile/src/features/GetStarted/GetStarted.tsx

The old android app doesn't have export account option therefore import account is not necessary for the new android app.
Resolves https://linear.app/safe-global/issue/MOB-70/disable-the-import-feature-on-android
Hides the button on android.
Launch the app on android --> you shouldn't see the "Import account" button.
Launch the app on iOS --> the button "Import account" should still be visible.
---

fix(mobile): don't show import account on android

---

apps/mobile/src/app/biometrics-opt-in.tsx
apps/mobile/src/hooks/useBiometrics.ts

On android there are devices that have both fingerprint and face id. Our detection does not detect which one of them is enabled but rather what is available. There could be a case where a user has enabled touch id but we show face id in the ui. That is why we go for the generic biometrics term.
Resolves https://linear.app/safe-global/issue/MOB-21/mobile-android-only-faceid-looks-strange-on-the-device-with-touch-id
Generic term "Biometrics" is used throughout the app.
Check settings they should say "Biometrics" in all scenarios.
---

fix(mobile): use generic biometrics term

---

apps/web/src/components/common/NetworkSelector/__tests__/ChainIndicatorWithFiatBalance.test.tsx
apps/web/src/components/common/NetworkSelector/index.tsx
apps/web/src/store/api/gateway/index.ts

Resolves #
UI value for fiat balance is not being updated in the Header for an active chain
For an active chain it is using the value from balances that is being dynamically updated (as in Total Asset Value and Side bar), and for the other ones in the list its lazy-loading the safe overviews
- Perform a send or receive action in the wallet
- Observe that balance got updated in in Total Asset Value, Side bar (left side) and header (top right bar)
- Observe that there was no calls to fetch other save overviews unless you opened the dropdown to switch the network
---

fix(web): update balance dynamically in Header top right bar) for active safe

---

apps/mobile/src/components/ProposalBadge/ProposalBadge.stories.tsx
apps/mobile/src/components/ProposalBadge/ProposalBadge.tsx
apps/mobile/src/components/ProposalBadge/index.tsx
apps/mobile/src/components/SafeListItem/SafeListItem.tsx

Resolves [MOB-32](https://linear.app/safe-global/issue/MOB-32/mobile-define-the-view-of-proposed-tx-without-the-signature-in-the)
- Adds a `ProposalBadge` component
1. Open a proposed transaction on mobile
2. Observe a badge saying "Proposal" instead of "0/x"
---

Fix(Mobile): Display Proposal badge in queue

---

apps/mobile/src/components/LoadableSwitch/LoadableSwitch.tsx
apps/mobile/src/hooks/useBiometrics.ts

Fixes biometrics hook state management issue where hasInteracted flag was unexpectedly resetting to true, causing unwanted biometric prompts when app returns from background.
- Convert hasInteracted from useState to useRef to prevent re-render cycles
- Remove dependencies from useEffect that were causing multiple re-runs
- Add deduplication for duplicate AppState events
- Fix dependency array issue that was the root cause of the state inconsistency
- Enable biometrics in app settings
- Put app in background, then return to foreground
- Verify biometrics prompt doesn't appear unexpectedly
- Toggle biometrics setting and verify it works correctly
N/A - Logic fix only
---
With the submission of this Pull Request, I confirm that I have read and agree to the terms of the [Contributor License …

fix(mobile): biometrics on settings

---

apps/mobile/src/features/DataImport/__tests__/useLegacyImport.test.ts
apps/mobile/src/features/DataImport/helpers/transforms.ts
apps/mobile/src/features/DataImport/hooks/useLegacyImport.ts
apps/mobile/src/utils/legacyData.test.ts
apps/mobile/src/utils/legacyData.ts

We were throughing the exception from the import decoding which could expose the data in the import in the logging. We now have more explicit error handling.
Resolves https://linear.app/safe-global/issue/MOB-98/private-keys-could-be-exposed-in-trace-and-logs
Ads more error classes and uses them and never just dumps the error object to the console
---

fix(mobile): sanitize error messages

---

apps/mobile/src/components/InfoSheet/InfoSheet.tsx
apps/mobile/src/features/TransactionChecks/components/TransactionChecksView.tsx
apps/mobile/src/features/TransactionChecks/components/blockaid/balance/BlockaidBalanceChanges.tsx

If a transaction was failing simulation with tenderly we were not showing a failure badge. 
Resolves https://linear.app/safe-global/issue/MOB-51/mobile-transaction-check-view
On a status different than true in the tx simulation we display a failure badge. 
Simulate a tx that would fail e.g. this one here: https://safe-wallet-web.dev.5afe.dev/transactions/tx?safe=eth:0xA77DE01e157f9f57C7c4A326eeE9C4874D0598b6&id=multisig_0xA77DE01e157f9f57C7c4A326eeE9C4874D0598b6_0x75c687359b7212953e3db1bfd56d0e193ee5c4b9cd365d186a1f041fe77acc75
---

fix(mobile): tenderly failure status was not shown

---

apps/mobile/src/features/ConfirmTx/components/SignTransaction/SignTransaction.tsx

When signing fails we send the user to an error page, but upon pressing retry he is able to sign again, but we stay at the error page and never navigate away. 
Resolves https://linear.app/safe-global/issue/MOB-17/mobile-there-is-no-signing-flow-on-ui-for-the-retry-failed-signing
We were not reseting the screen state.
Try to sign a tx and keep your face away from the camera. Once you get the face id "cancel" prompt you will land on the error page. Once on the error page hit "retry". You should land back in the loading state and will get prompted to sign again. Once this is done you should end up on the Success screen.
---

fix(mobile): incorrect loading state on retry signing

---

apps/mobile/package.json
apps/mobile/src/features/ConfirmTx/components/ConfirmationView/ConfirmationView.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/SwapOrder/SwapOrder.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/SwapOrder/SwapOrderHeader.test.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/SwapOrder/SwapOrderHeader.tsx
apps/web/package.json
apps/web/src/features/swap/components/SwapOrder/rows/SurplusFee.tsx
apps/web/src/features/swap/components/SwapOrderConfirmationView/OrderFeeConfirmationView.tsx
apps/web/src/features/swap/helpers/utils.ts
packages/utils/package.json
packages/utils/src/features/swap/helpers/fee.ts
packages/utils/src/features/swap/helpers/utils.ts
yarn.config.cjs
yarn.lock

- display actions on the swap order screen
- better display for buy orders
Resolves https://linear.app/safe-global/issue/MOB-11/
---

fix(mobile): miscellaneous swap order fixes

---

apps/mobile/src/app/_layout.tsx
apps/mobile/src/components/InfoSheet/InfoSheet.tsx
apps/mobile/src/features/AdvancedDetails/formatters/singleValue.tsx
apps/mobile/src/features/AdvancedDetails/utils/formatParameters.tsx
apps/mobile/src/features/DataImport/EnterPassword.container.tsx
apps/mobile/src/features/DataImport/HelpImport.container.tsx
apps/mobile/src/features/DataImport/ImportProgressScreen.container.tsx
apps/mobile/src/features/DataImport/ReviewData.container.tsx
apps/mobile/src/features/DataImport/components/EnterPasswordView.tsx
apps/mobile/src/features/DataImport/components/FileSelectionView.tsx
apps/mobile/src/features/DataImport/components/HelpImportView.tsx
apps/mobile/src/features/DataImport/components/ImportProgressScreenView.tsx
apps/mobile/src/features/DataImport/components/ReviewDataView.tsx
apps/mobile/src/theme/SafeStatusBar.tsx

Resolves [MOB-40](https://linear.app/safe-global/issue/MOB-40/display-more-data-in-modal)
Resolves [MOB-107](https://linear.app/safe-global/issue/MOB-107/mobile-light-mode-status-bar-is-white)
- Updates `InfoSheet` to accept children
- Adds `InfoSheet` to transaction data
- Extracts `StatusBar` into `SafeStatusBar` and handles theme changes
1. Open a transaction
2. Go to transaction details
3. Press on truncated data
4. Observe a sheet opening at the bottom of the screen that contains the full data
---

Fix(Mobile): Show truncated data in bottom sheet

---

apps/mobile/src/app/(tabs)/_layout.tsx
apps/mobile/src/features/DataImport/components/DataTransferView.tsx
apps/mobile/src/features/DataImport/components/EnterPasswordView.tsx
apps/mobile/src/features/DataImport/components/FileSelectionView.tsx
apps/mobile/src/features/DataImport/components/HelpImportView.tsx
apps/mobile/src/features/DataImport/components/ImportProgressScreenView.tsx
apps/mobile/src/features/DataImport/components/ReviewDataView.tsx
apps/mobile/src/features/Onboarding/components/OnboardingCarousel/OnboardingCarousel.tsx
apps/mobile/src/theme/SafeStatusBar.tsx
apps/mobile/src/theme/__tests__/SafeStatusBar.test.tsx

Resolves [MOB-107](https://linear.app/safe-global/issue/MOB-107/mobile-light-mode-status-bar-is-white)
- Removes all `StatusBar` except the one in _layout
- Adds `DARK_SCREENS` array
- Checks in `SafeStatusBar` if current screen should be dark or light
1. Open the app and go to the onboarding screen
2. Toggle with cmd+shift+a
3. Observe the Status bar doesn't change
4. Go into the app and select light/dark mode in settings
5. Toggle with cmd+shift+a
6. Observe the status bar not changing
---

Fix(Mobile): Centralize StatusBar and theme logic

---

apps/mobile/src/app/(tabs)/_layout.tsx

Resolves [MOB-110](https://linear.app/safe-global/issue/MOB-110/mobile-tab-navigation-ui)
- Shows tab labels
- Uses different icon for home
- Renames Settings to Account
2. Compare tab navigation with design
---

Fix(Mobile): Update bottom tab navigation style

---

apps/mobile/src/app/(tabs)/_layout.tsx

Resolves [MOB-110](https://linear.app/safe-global/issue/MOB-110/mobile-tab-navigation-ui)
- Uses `useTheme` for setting the colors in the tab navigation
2. Switch to light or dark mode
3. Observe that the tab navigation color is correct
---

Fix(Mobile): Tab color when switching theme

---

apps/mobile/src/components/Badge/theme.ts
apps/mobile/src/components/transactions-list/Card/AccountCard/AccountCard.tsx
apps/mobile/src/components/transactions-list/Card/AssetsCard/AssetsCard.tsx
apps/mobile/src/features/AddressBook/Contact/NetworkSelector/ChainItem.tsx
apps/mobile/src/features/AddressBook/Contact/components/ContactNetworkRow.tsx
apps/mobile/src/features/ConfirmTx/components/ConfirmationsInfo/ConfirmationsInfo.tsx
apps/mobile/src/features/ConfirmationsSheet/ConfirmationsSheet.container.tsx
apps/mobile/src/features/Settings/components/Navbar/SettingsMenu.tsx

Resolves Settings issue
- The settings button was overlapped by the settings container so I added a zIndex to it
- Replaced all `badge_warning_variant1` with `badge_warning` to fix color issues
- Removes the chain id / description from network items in address book
2. Go to account
3. Press the settings button
4. It should navigate
5. Go to a pending transaction
6. The confirmations badge should have the correct color
---

Fix(Mobile): Update badge color, fix settings button overlap

---

apps/web/src/components/common/AddressInput/index.tsx
apps/web/src/components/common/AddressInputReadOnly/index.tsx

Resolves [EN-140](https://linear.app/safe-global/issue/EN-140/owners-icons-look-smaller-if-they-dont-have-a-ab-name-set-for-them)
Set avatar size of readonly address input (when showing an address book entry) to 32px for consistency with regular address input.
---

fix(AddressInput): consistent avatar size for address book entries

---

apps/mobile/src/app/_layout.tsx
apps/mobile/src/app/pending-transactions.tsx
apps/mobile/src/app/transaction-parameters/_layout.tsx
apps/mobile/src/components/transactions-list/Card/TxBridgeCard/TxBridgeCard.tsx
apps/mobile/src/features/ConfirmTx/components/ConfirmationView/ConfirmationView.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/BridgeTransaction/BridgeTransaction.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/LifiSwapTransaction/LifiSwapTransaction.tsx
apps/mobile/src/features/ConfirmTx/components/confirmation-views/SwapOrder/SwapOrder.tsx
apps/mobile/src/features/PendingTx/components/PendingTxList/PendingTxList.container.tsx

- adds tx details button to swap txs
- adds tx details buttons to bridge txs
- move padding to inside the scrollview (this way the scrollview bars are attached to the edge of the screen and not 12px in the middle)
related to https://linear.app/safe-global/issue/MOB-11/
---

fix(mobile): add transaction details to confirmation details

---

apps/mobile/src/components/Logo/Logo.test.tsx
apps/mobile/src/components/Logo/Logo.tsx
apps/mobile/src/features/AdvancedDetails/components/Receiver/Receiver.tsx
apps/mobile/src/features/AdvancedDetails/components/Receiver/__tests__/Receiver.test.tsx

Resolves [MOB-94](https://linear.app/safe-global/issue/MOB-94/use-names-from-the-addressbook-on-the-tx-details)
This PR enhances the transaction details to display contact names from the address book when available.
The `Receiver` component now prioritizes contact names from the address book over transaction data. Falls back to transaction data names when no contact exists.
1. Create a transaction to an address that is also in the address book (e.g. to the Safe itself)
2. Navigate to the queued transaction
3. Open the transaction details
4. Observe the address book name above the address value in the `to` field
---

feat(mobile): integrate address book with Receiver component in transaction details

---

apps/web/src/components/tx-flow/flows/SignMessageOnChain/ReviewSignMessageOnChain.tsx

Resolves [COR-148](https://linear.app/safe-global/issue/COR-148/invalidaddresserror-on-safe-switch-with-walletconnect-signatures)
The **ReviewSignMessageOnChain** component was attempting to create transactions even when **signMessageAddress** was not yet defined, which sometimes lead to issues in the sign on-chain message flow.
Added a guard clause in the useEffect hook to ensure that transaction creation only occurs when signMessageAddress is available.
Ensure that the previously reported issue no longer occurs by following the steps below.
1. **Initiate the flow**: Trigger the `SignMessageOnchain` flow.
2. **Navigate to review**: Proceed to the review step.
3. **Check network requests**:
- Open your browser's developer tools and inspect the **Network** tab.
- Observe a failing request …

fix: Prevent transaction creation when `signMessageAddress` is undefined

---

package.json
yarn.lock

The builds are failing because the stylus dependency (that we don't directly use) was removed by npmjs. It seems that the report is bogus and it should get back to package repo. In the meantime I've implemented the workaround in the thread: https://github.com/stylus/stylus/issues/2938 
---

fix: stylus dep temp workaround

---

apps/mobile/package.json
apps/mobile/src/app/(tabs)/transactions.tsx
apps/mobile/src/components/OptIn/OptIn.tsx
apps/mobile/src/components/SafeBottomSheet/SafeBottomSheet.tsx
apps/mobile/src/features/AccountsSheet/MyAccounts/MyAccountsFooter.tsx
apps/mobile/src/features/GetStarted/GetStarted.tsx
apps/mobile/src/features/ImportReadOnly/components/AddSignersFormView.tsx
apps/mobile/src/features/PendingTx/components/PendingTxList/PendingTxList.container.tsx
apps/mobile/src/features/Settings/components/AppSettings/AppSettings.tsx
apps/mobile/src/features/Share/components/ShareView.tsx
apps/mobile/src/features/TxHistory/components/TxHistoryList/TxHistoryList.tsx
yarn.lock

Android now has 3 navigation modes
- Gesture navigation
- 2-button navigation
- 3-button navigation
when 2 and 3 button navigation is selected by the user some views were behind the navigation which created poor user experience. With this PR this problem should be fixed.
Resolves https://linear.app/safe-global/issue/COR-384/mobile-bottom-marginpadding-is-non-existent-in-android
It boils down to using safeAreaInsets even on screens that look fine on iOS. The bottom sheet was a bit tricky as it required some negative margins to hide content that "flies" behind it.
Best would be to run through all screens app with both iOS and andoird next to each other to confirm that everything looks ok on both platforms. 
---
With the submission of this Pull Request, I confirm that I have read and agree …

fix(mobile): android UI discrepancies

---

apps/mobile/src/components/TransactionSkeleton/TransactionSkeleton.tsx
apps/mobile/src/features/TxHistory/TxHistory.container.test.tsx
apps/mobile/src/features/TxHistory/components/TxHistoryList/TxHistoryList.tsx

[COR-378](https://linear.app/safe-global/issue/COR-378/mobile-android-history-dont-the-day-at-the-top-and-2-loading-icons-on)
Reverts to the native default spinner for the transaction history on both iOS and Android. 
The previously introduced custom spinner from #6145 has been removed. Although the custom spinner was visually distinct, it introduced a poor UX in fast-loading scenarios. It often appeared only for a brief moment (a few milliseconds), making it feel abrupt. The native spinner offers a smoother and more consistent experience across platforms.
1. Open the transaction history
2. Pull down from the top of the list to trigger a refresh
3. Expected: The platform's native loading spinner appears during the refresh process …

fix(mobile): revert custom pull-to-refresh spinner in transaction history

---

apps/mobile/app.config.js
apps/mobile/expo-plugins/ssl-pinning/README.md
apps/mobile/expo-plugins/ssl-pinning/withSSLPinning.js
apps/mobile/scripts/getCertificates.js

I’m adding an expo plugin that configures iOS and Android to use pinned certificates for our domains.
Resolves https://linear.app/safe-global/issue/COR-401/implement-ssl-pinning
The implementation is based on this callstack article
https://www.callstack.com/blog/ssl-pinning-in-react-native-apps
I just wrote the expo plugin to insert the native code in the correct places and small script to extract the hashes of the domains to pin. 
The app should continue to function as is. If you change the hashes to invalide one in the app.config.js, then do `expo prebuild` and run the app network request to CGW are going to fail. 
---

feat(mobile): ssl pinning

---

apps/mobile/src/app/confirm-transaction.tsx
apps/mobile/src/app/import-signers/private-key-success.tsx
apps/mobile/src/app/import-signers/private-key.tsx
apps/mobile/src/components/LinearGradient/LinearGradien.tsx
apps/mobile/src/components/LinearGradient/index.ts
apps/mobile/src/features/ConfirmTx/components/SignTransaction/SignError.tsx
apps/mobile/src/features/ConfirmTx/components/SignTransaction/SignSuccess.tsx

While using the app on my test device I found couple of screens that looked weird. I've set the navigation mode on Android to "gesture" and for some reason my android version has no bar at the bottom (basically 0 safearea). because of this buttons were glues to the corner of the screen. That's why I opted for using paddingBottom={Math.max(bottom, getTokenValue('$4'))}. This way we guarantee at least a minimum distance from the corner of the screen.
I also centralized the linearGradient usage to a single component - this way we don't have to make the same css modifications in multiple files
---

fix(mobile): couple of more UI glitches on Android

---

apps/web/src/components/tx/security/blockaid/__tests__/useBlockaid.test.ts
apps/web/src/components/tx/security/blockaid/useBlockaid.ts

Resolves a potential issue where the useBlockaid hook could attempt to log an undefined or null error message, leading to misleading logs or runtime noise.
This PR adds a conditional check in the `useBlockaid` hook to ensure the error message is only logged if it exists. This prevents unnecessary or confusing log entries when the error object does not include a message.
1.	Simulate a transaction.
2.	Confirm that:
- When there is an error, the error with a message is logged as expected.
- When the simulation is successful: No error is logged.
4.	Check console logs during testing to ensure no “undefined” or blank messages are logged.

fix(security): log error message only if it exists in useBlockaid hook

---

apps/mobile/src/components/ChainsDisplay/ChainsDisplay.tsx
apps/mobile/src/components/SafeBottomSheet/SafeBottomSheet.tsx
apps/mobile/src/components/StatusBanners/PendingTransactions/PendingTransactions.tsx
apps/mobile/src/features/AccountsSheet/AccountsSheet.container.tsx

When fixing an Android issue we unfortunately introduced a regression and broke the scrolling within the sheet. This PR fixes this. In addition, I'm reducing the size inside of the badge if the content text length is higher than 2 characters. The circle of the badge can't accomodate more than 3 items at font-size 12.
Resolves https://linear.app/safe-global/issue/COR-418/mobile-can-not-see-the-full-list-of-networks-for-multichain-safe
Test in a safe with a lot of networks. The networks should be scrollable.
https://github.com/user-attachments/assets/9a17ec32-d6fe-4617-be3f-ee01c755a1b0
---

fix(mobile): Scrolling within sheet was not possible

---

apps/mobile/app.config.js

Resolves [COR-427](https://linear.app/safe-global/issue/COR-427/mobile-android-remove-the-use-of-read-media-images-permission)
The `react-native-capture-protection` package with `fullMediaCapture` option was adding permission to read image files to support Android 13 and lower. Google now only allows this permission for apps that need "broad access to photos" which is not the case for the safe mobile app. The package also allows `restrictedCapture` to remove this permission and lose support for Android 13 and lower which is now activated.
- Try taking a screenshot on the signer screen with android 14+ and observe its still blocked
---

Fix(Mobile): Remove READ_MEDIA_IMAGES permission

---

apps/mobile/src/features/ConfirmTx/components/ReviewAndConfirm/tabs/JSONTab.tsx
apps/mobile/src/features/ConfirmTx/components/TransactionChecks/hooks/useTransactionSecurity.ts
apps/mobile/src/features/TransactionChecks/TransactionChecks.container.tsx
apps/mobile/src/hooks/useSafeTx.ts

Resolves [COR-158](https://linear.app/safe-global/issue/COR-158/mobile-updated-queue-summary-screen-a-la-signing-improvements-on-web)
- Displays the SafeTx JSON in the JSON tab to match the implementation on web
- Creates a new hook `useSafeTx` to get the safe tx through the txDetails
1. Open a safe on mobile
2. Go to a pending transaction and confirm
3. Observe the JSON tab matches web 
---

Fix(Mobile): Show safe tx data in JSON view when confirming txs

---

apps/mobile/assets/android/drawable/baseline_content_copy_24.xml
apps/mobile/src/features/Signers/components/SignersList/hooks/useSignersActions.ts

Resolves [COR-357](https://linear.app/safe-global/issue/COR-357/mobile-android-no-icon-and-black-icons-in-the-signer-menu)
- Adds the missing copy icon as an android vector
- Updates the color instead of hard-coding black
1. Open the signers page on android
2. Press the three-dot menu
3. Observe all icons are visible and look correct in dark/light mode
---

Fix(Mobile): Signer context menu icons on android

---

apps/web/cypress/e2e/pages/create_tx.pages.js
apps/web/src/components/transactions/TxShareLink/index.tsx

Fixes the `tx_share_block` e2e tests.
- Added a new data-testid for the share block header in the TxShareAccordion component.
- Updated the Cypress test to interact with the share block header instead of the whole share block itself.
---

fix(e2e): click on share block header to make sure it expands

---

apps/web/src/components/common/AddressInput/index.test.tsx
apps/web/src/components/common/EthHashInfo/index.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/SpaceAddressBookTable.tsx
apps/web/src/hooks/__tests__/useAllAddressBooks.test.ts
apps/web/src/hooks/useAllAddressBooks.ts

Resolves [COR-493](https://linear.app/safe-global/issue/COR-493/spaces-address-book-names-are-only-visible-if-wallet-is-on-the-correct)
- Allows overriding `EthHashInfo` address book name source
- Hides the chain prefix for addresses in a space address book
- Updates `useAllMergedAddressBooks` to use all local address books instead of only the current network one
1. Open a space with an address book that has entries on different chains
2. Observe that all names are shown at all times no matter if a wallet is connected or the connected wallets network
3. Observe that the cloud icon is shown at all times
4. Go to added safes on a space that have names in the local and space address book
5. Observe all names are visible and the correct icon is shown
---
With the submission of this Pull …

Fix(Spaces): Merge all address books independent of current chain

---

apps/web/src/components/common/EnhancedTable/index.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/SpaceAddressBookTable.tsx

Resolves [COR-490](https://linear.app/safe-global/issue/COR-490/spaces-sorting-by-name-doesnt-work-in-the-addressbook)
- Adds a new `disableSort` value to the EnhancedTable header cells
- Disables sorting for address book table
1. Open a space with an address book
2. Observe the table has no sortable headers
---

Fix(Spaces): Disable address book table sort

---

apps/web/src/features/myAccounts/components/AccountItems/MultiAccountItem.tsx
apps/web/src/features/myAccounts/components/AccountItems/SingleAccountItem.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/SpaceAddressBookTable.tsx
apps/web/src/features/spaces/hooks/useSpaceSafes.tsx
apps/web/src/features/spaces/utils.ts
apps/web/src/hooks/__tests__/useAllAddressBooks.test.ts
apps/web/src/hooks/useAllAddressBooks.ts

Resolves [COR-493](https://linear.app/safe-global/issue/COR-493/spaces-address-book-names-are-only-visible-if-wallet-is-on-the-correct#comment-9f575331)
We created a new hook `useAllMergedAddressBooks` that is supposed to combine local and cloud address books. Since the local address books have a different structure we need to map them into the new structure. Since there can also be duplicate entries there with different names we need a strategy to decide on the name we want to use. Previous to this fix we always defaulted with the first name we saw and kept that but this causes issues if the same safe on a different network is open it displays the name from the other network.
This PR fixes that by allowing to pass the chainId into the mapping logic and overwriting the name in case the …

Fix(Spaces): Respect current chainId when selecting address book item

---

apps/mobile/src/store/middleware/__tests__/notificationSync.test.ts
apps/web/src/hooks/__tests__/useGasPrice.test.ts
apps/web/src/tests/mocks/chains.ts
packages/utils/src/utils/__tests__/gateway.test.ts

This pull request updates the Etherscan URL used in test files to ensure they reference the correct and current endpoint.
---

fix(tests): update Etherscan API URLs in tests and mocks

---

apps/web/src/components/transactions/CsvTxExportButton/index.tsx
apps/web/src/components/transactions/CsvTxExportModal/index.tsx
apps/web/src/services/analytics/mixpanel-events.ts

Resolves # [COR-309](https://linear.app/safe-global/issue/COR-309/add-tracking-event-csv-export)
- tracking 2 events: `CSV Export` button clicked and CSV exported in Mixpanel
- on staging you should be able to see console logs about these events
---

chore(web): Mixpanel tracking for CSV export

---

apps/web/src/utils/__tests__/wallets.test.ts
apps/web/src/utils/wallets.ts

If an EOA has been upgraded to an EIP-7702 account, then this EOA was not able to sign off-chain signatures. Our checks were treating such account as a smart account and those have to submit on-chain signratures.
Resolves #
Our isSmartContract check returns true whenever getCode returns anything other than an empty data. For EIP-7702 accounts we do have data which is prefixed with 0xef0100. Those accounts are both smart accounts and EOAs. The user is still able to use them as EOAs. Now when we want to know if the wallet is an EOA we also check if the getCode returned is prefixed with 0xef0100
Use for example MM and upgrade an EOA to a smart acocunt. 
Now try to sign a tx - you should get a signrature prompt in MM instead of a on-chain tx request. 
---
With the submission of this Pull …

fix(web): EIP-7702 accounts are treated as smart accounts

---

apps/web/src/components/common/AddressBookInput/index.test.tsx
apps/web/src/components/common/AddressBookInput/index.tsx
apps/web/src/components/common/AddressBookSourceProvider/index.tsx
apps/web/src/components/common/EthHashInfo/SrcEthHashInfo/index.tsx
apps/web/src/components/common/EthHashInfo/index.tsx
apps/web/src/components/tx-flow/flows/NestedTxSuccessScreen/index.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/EditContactDialog.tsx
apps/web/src/features/spaces/components/SpaceAddressBook/SpaceAddressBookTable.tsx
apps/web/src/hooks/__tests__/useAllAddressBooks.test.ts
apps/web/src/hooks/useAddressBook.ts
apps/web/src/hooks/useAllAddressBooks.ts
apps/web/src/pages/_app.tsx
apps/web/src/pages/address-book.tsx
apps/web/src/pages/spaces/address-book.tsx
apps/web/src/pages/spaces/index.tsx
apps/web/src/pages/spaces/members.tsx
apps/web/src/pages/spaces/safe-accounts.tsx
apps/web/src/pages/spaces/settings.tsx

Resolves [COR-493](https://linear.app/safe-global/issue/COR-493/spaces-address-book-names-are-only-visible-if-wallet-is-on-the-correct)
- Updates `useAddressBook` to respect multiple address book sources
- Makes address book hooks context aware of spaces
- Within spaces any address name should only come from the space address book
- Within a safe any address name should either come from the space address book or from the local one in that order
---

Refactor(AB): Address book hooks to handle multiple sources

---

apps/web/src/components/sidebar/SidebarNavigation/config.tsx
apps/web/src/config/routes.ts
apps/web/src/pages/balances/index.tsx
apps/web/src/pages/balances/positions.tsx

Part of [GRO-33](https://linear.app/safe-global/issue/GRO-33/assets-page)
- Adds a new page for positions
- Moves the positions table from assets to the new page
1. Open assets
2. Observe a new tab Positions
3. Observe only wallet assets
4. Click on Positions
5. Observe the positions
---

feat(positions): Add positions page and move positions there

---

apps/web/src/components/common/AddressBookSourceProvider/index.tsx

Part of [COR-493](https://linear.app/safe-global/issue/COR-493/spaces-address-book-names-are-only-visible-if-wallet-is-on-the-correct)
When deciding on the source of address books we previously checked if the `safe` url query parameter was present and in that case used a **merged** approach and otherwise only accessed entries from the space. This doesn't work for non-safe and non-space routes such as safe creation. In those cases we still want to have a **merged** approach but since the safe query param doesn't exist there either we have to come up with a different strategy.
- Check for `spaceId` query parameter in order to decide `spaceOnly`
- Otherwise go with merged approach
This works because we don't keep the `spaceId` parameter when users navigate within a safe but instead access …

fix: Check spaceId query param for address book source

---

apps/web/cypress/support/localstorage_data.js
apps/web/src/components/batch/BatchSidebar/BatchTxItem.tsx
apps/web/src/components/batch/BatchSidebar/BatchTxList.tsx
apps/web/src/components/batch/BatchSidebar/styles.module.css
apps/web/src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx
apps/web/src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/styles.module.css
apps/web/src/components/tx-flow/actions/Batching/index.tsx
apps/web/src/components/tx-flow/flows/ConfirmBatch/index.tsx
apps/web/src/components/tx-flow/flows/SafeAppsTx/index.tsx
apps/web/src/components/tx/confirmation-views/BatchTransactions/BatchTransactions.stories.tsx
apps/web/src/components/tx/confirmation-views/BatchTransactions/BatchTransactions.test.tsx
apps/web/src/components/tx/confirmation-views/BatchTransactions/__snapshots__/BatchTransactions.test.tsx.snap
apps/web/src/components/tx/confirmation-views/BatchTransactions/mockData.ts
apps/web/src/config/constants.ts
apps/web/src/hooks/useDraftBatch.ts
apps/web/src/services/ls-migration/batch.ts
apps/web/src/services/ls-migration/tests.test.ts
apps/web/src/store/batchSlice.ts
apps/web/src/store/index.ts

Resolves COR-29
- Changes BatchTx datastructure to just contain `{ to, data, value, operation}`
- Allows batching multiSend delegateCalls coming from the Transaction Builder by decoding the multiSends and adding its individual transactions to the batch
- Create a Batch
- Add a Multisend from the Transaction Builder to the batch
https://github.com/user-attachments/assets/5130168c-3058-4b7c-a110-5a0ce923b68c
---

feat(web): allow batching of batch txs

---

apps/web/src/components/new-safe/create/logic/index.test.ts
apps/web/src/components/new-safe/create/logic/index.ts
apps/web/src/components/new-safe/create/logic/utils.ts
apps/web/src/components/new-safe/create/steps/ReviewStep/index.tsx
packages/utils/src/services/contracts/__tests__/deployments.test.ts
packages/utils/src/services/contracts/deployments.ts

[COR-509](https://linear.app/safe-global/issue/COR-509/prefer-canonical-contract-addresses-for-multichain-safe-creation-on)
Prefer the canonical addresses for core contracts when creating a new Safe. This is necessary to ensure the multichain Safe creation works when deploying on zkSync/Lens and an EVM-based chain.
Introduced `getCanonicalOrFirstAddress` util in packages/utils, refactored web Safe creation to use it for all contracts, and added unit tests.
1. Create multichain Safe on Lens/zkSync
2. Then add Sepolia
3. Expected: No errors due to chain-specific addresses.
1. Create multichain Safe on Lens/zkSync + Sepolia
2. Expected: No errors due to chain-specific addresses.
---
With the submission of this Pull Request, I confirm that I have read and agree to the terms of the …

fix: Prefer canonical contract addresses for Safe creation

---

apps/web/src/components/transactions/CsvTxExportButton/__tests__/index.test.tsx
apps/web/src/components/transactions/CsvTxExportButton/index.tsx
apps/web/src/components/transactions/CsvTxExportModal/CsvTxExportModal.test.tsx
apps/web/src/components/transactions/CsvTxExportModal/index.tsx
apps/web/src/services/analytics/events/txList.ts
apps/web/src/services/analytics/ga-mixpanel-mapping.ts
apps/web/src/services/analytics/mixpanel-events.ts

The CSV Export events were only tracked in Mixpanel, while we want to track analytics in Google Analytics and Mixpanel.
- **CSV Export Tracking**: Add GA events and mapping for dual GA/MixPanel tracking of CSV
export interactions
- **Parameter Rename**: `PERIOD` → `DATE_RANGE` for better clarity
---

feat(analytics): CSV export dual tracking and parameter improvements

---

apps/web/src/pages/balances/positions.tsx

Removes these buttons from the Positions View, as they are not needed there:
---

Feat(Positions): Hide Currency and Token Select at Position Balance

---

apps/web/src/components/dashboard/Assets/index.tsx
apps/web/src/components/dashboard/PendingTxs/PendingTxsList.tsx

Resolves #
https://github.com/safe-global/safe-wallet-monorepo/pull/6218#issuecomment-3223953546
---

fix(web): dont show empty state for assets/pending tx before loaded

---

apps/web/src/pages/balances/index.tsx

The total balance at assets was not reduced by hiding tokens.
Now the total balance at assets is reduced by hiding tokens.
1. Go to assets.
2. Observe the total balance.
3. Hide a token.
4. Observe that the total balance got decreased.
---

Feat(Positions): Use visible balance for total asset balance.

---

apps/web/src/components/balances/AssetsTable/index.tsx
apps/web/src/features/positions/components/PositionsHeader/index.tsx
apps/web/src/features/positions/index.tsx

Part of [GRO-44](https://linear.app/safe-global/issue/GRO-44/qa-final-round-for-positions)
- Computes weights based on fiat total
- Shows tooltip to explain this
1. Open a safe with positions and assets
2. Go to balances
3. Hover the weight column header
4. Observe a tooltip
5. Do the same for positions
---

fix(positions): Compute weight based on fiat total, add tooltips

---

apps/web/src/hooks/useFiatTotal.ts

We had a double-accounting issue when calculation the total portfolio value by summing up assets and positions. Some positions are represented with tokens, and would such affect the total calculation twice. 
Removes positions from the total value calculation.
Observe the total value and make sure the positions don't count into it.
---

feat(positions): remove positions from total value

---

apps/web/src/components/dashboard/Assets/index.tsx
apps/web/src/components/dashboard/Overview/Overview.tsx
apps/web/src/components/dashboard/Overview/OverviewSkeleton.tsx
apps/web/src/components/dashboard/PendingTxs/PendingTxsList.tsx

Resolves # [COR-394](https://linear.app/safe-global/issue/COR-394/loading-state-new-dashboard)
- changed the loading state to be user-friendly 
- load the Wallet Dashboard with the throttle network setting so it loads slow and observe the loading state for Total Assets Value, Top Assets and Pending Transactions
---

fix(web): update Dashboard loading state

---

apps/web/src/components/transactions/QueuedTxSimulation/index.tsx
apps/web/src/components/tx-flow/TxInfoProvider.tsx
apps/web/src/components/tx/security/tenderly/__tests__/useSimulation.test.ts
apps/web/src/components/tx/security/tenderly/index.tsx
apps/web/src/components/tx/security/tenderly/useSimulation.ts
packages/utils/src/components/tx/security/tenderly/__tests__/utils.test.ts
packages/utils/src/components/tx/security/tenderly/useSimulation.ts
packages/utils/src/components/tx/security/tenderly/utils.ts
yarn.lock

Resolves https://linear.app/safe-global/issue/COR-46/internal-reverts-on-tenderly
Resolves issues with Tenderly transaction simulation warnings for partial reverts - scenarios where a Safe transaction succeeds overall but contains internal call trace errors (e.g., a multicall where some sub-calls revert). This was causing complaints from users and is technically inaccurate as transactions can still execute.
- isCallTrace edited to show when simulations succeed but also have internal errors.
- Refactored getSimulationStatus() to clearly extract nested simulation data and detect partial revert scenarios
- Fixed confusing double nesting in simulation response handling (simulation.simulation.simulation → cleaner access pattern)
-Added tests for the new partial revert detection logic
-Included …

Fix(web): tenderly partial revert warnings

---

apps/web/package.json
apps/web/src/components/settings/FallbackHandler/__tests__/index.test.tsx
apps/web/src/features/walletconnect/components/WcProposalForm/__tests__/useCompatibilityWarning.test.ts
apps/web/src/services/safe-wallet-provider/useSafeWalletProvider.test.tsx
apps/web/src/tests/pages/apps.test.tsx
apps/web/src/tests/test-utils.tsx

Test cases where failing locally, so a 100% passing test suite was never reachable.
* Makes regex tests be aware if this is the officially hosted wallet, or a local fork
* Add US locale to local test pipeline to avoid locale errors
Run `yarn test` and observe passing tests.
---

Tests: fix/adapt unit tests

---

apps/web/src/components/balances/AssetsTable/index.tsx
apps/web/src/components/common/EnhancedTable/index.tsx

The assets table was scrolling horizontally due to an added column (DeFi positions).
* Reduce the width of columns to add up to 100%
* Add `overflowX: hidden`

fix(assets): fix horizontal scroll in assets table

---

apps/web/src/components/common/NamedAddressInfo/index.test.tsx
apps/web/src/components/common/NamedAddressInfo/index.tsx

- Doesn't show `Unverified Contract` for those that were not indexed by Decoder service
Resolves # [COR-480](https://linear.app/safe-global/issue/COR-480/tx-flow-and-history-remove-unverified-wording-if-the-contract-is-not)
- only show `Unverified Contract` for the contracts that don't have ABI in the Decoder Service response
- do not show it for the contracts that were not found (not indexed)
- remove the check of  the on-chain bytecode and rely solemnly on Decoder response
Check for Name tag in transaction queue/history. `Unverified Contract` should only be shown for those that do not have ABI
---

fix(web): dont show inverified for non-indexed contracts

---

apps/web/src/components/dashboard/Overview/Overview.tsx
apps/web/src/components/dashboard/index.tsx
apps/web/src/components/safe-apps/AppFrame/__tests__/AppFrame.test.tsx
apps/web/src/hooks/useBalances.ts
apps/web/src/hooks/useSafeInfo.ts
apps/web/src/hooks/useVisibleBalances.ts
apps/web/src/store/common.ts

There was an inconsistent initial state when loading the dashboard. Balances aren't in a _loading_ state initially (`loading: false`) , yet there was initial placeholder data with `items: []`.
I've added a new piece of state for all "loadable" slices like Balances and Safe Info to indicate whether the data has been loaded or not. The lifecycle of loadable slices is now like this:
1. Initial state:
```
{
data: { ... }, // placeholder data,
loaded: false,
loading: false, // hasn't started loading yet
error: undefined,
}
```
2. Loading state:
```
{
data: { ... }, // placeholder data,
loaded: false,
loading: true,
error: undefined,
}
```
3. Finished loading:
```
{
data: { ... }, // actual data
loaded: true,
loading: false,
error: undefined,
}
```
3. Error state:
```
{
data: { ... }, // …
```

fix(dashboard): don't show 0 balance before balances are loaded

---

apps/web/src/components/common/NamedAddressInfo/index.test.tsx
apps/web/src/components/common/NamedAddressInfo/index.tsx
apps/web/src/components/transactions/TxDetails/TxData/Transfer/index.test.tsx
apps/web/src/hooks/useAddressResolver.ts
apps/web/src/services/analytics/useMixpanel.ts

A small follow up on #6281 – reuse an existing useAddressResolver hook in NamedAddressInfo.
Plus, a small fix for Mixpanel on dev.

Refactor(web): call useAddressResolver in NamedAddressInfo

---

apps/web/next.config.mjs
apps/web/src/components/common/Footer/index.tsx
apps/web/src/config/constants.ts

- expose commit hash to the web app and show it next to the version
It's convenient to see what was the last commit that was deployed to the dev/staging site. E.g. you pushed a new feature and want to make sure it's already deployed.

feat(web): show commit hash in footer

---

apps/mobile/src/features/AdvancedDetails/utils/formatTxDetails.test.tsx
apps/mobile/src/features/AdvancedDetails/utils/formatTxDetails.tsx
apps/mobile/src/features/HistoryTransactionDetails/components/HistoryTransactionView/HistoryTransactionView.tsx
apps/mobile/src/features/HistoryTransactionDetails/components/history-views/HistoryTokenTransfer.tsx

Some transactions such as “sent” events due to a swap don’t have txData. For those on web we don’t display any advanced details. Now we do the same. I also added a check to formatTxDetails for txData so that it won’t crash again if we stumble on a tx without any txData.
Resolves https://linear.app/safe-global/issue/COR-517/sent-screen
check this tx: https://safe-wallet-web.dev.5afe.dev/transactions/tx?safe=eth:0x8675B754342754A30A2AeF474D114d8460bca19b&id=transfer_0x8675B754342754A30A2AeF474D114d8460bca19b_eeb34c7a34951dc29cb5eea90a4820810502b5bb21c48b69f162a71cca500745d320
There should be no "transaction details" button anymore. 
---

fix(mobile): advanced details crashes when no txData

---

apps/web/src/features/walletconnect/WalletConnectContext.tsx
apps/web/src/features/walletconnect/__tests__/WalletConnectContext.test.tsx
apps/web/src/services/safe-wallet-provider/index.test.ts
apps/web/src/services/safe-wallet-provider/index.ts

[COR-404](https://linear.app/safe-global/issue/COR-404/add-support-for-atomic-capability-in-eip-5792-v2)
Implements support for the `atomic` capability in accordance with the [EIP-5792 v2 specification](https://eips.ethereum.org/EIPS/eip-5792), enabling better compatibility with dApps using the latest version.  
The existing `atomicBatch` field is preserved to ensure backward compatibility with v1 clients.
Changes to comply with the points outlined in the [migration guide](https://www.eip5792.xyz/reference/migrating-to-v2):
- Adds the `atomic` field to the response of `wallet_getCapabilities` as required by EIP-5792 v2  
- Updates the version field in `wallet_getCallsStatus` results to align with the v2 format  
- Introduces the `atomicRequired` flag to the `SendCallsParams` type for v2 …

feat: migrate to EIP-5792 v2 spec with new atomic field

---

apps/web/src/features/walletconnect/__tests__/WalletConnectContext.test.tsx

[COR-404](https://linear.app/safe-global/issue/COR-404/add-support-for-atomic-capability-in-eip-5792-v2)
Fixes TS errors that were accidently introduced with #6176 due to long time between last commit and merge.
https://github.com/safe-global/safe-wallet-monorepo/actions/runs/17614934370/job/50045523019
---

fix(tests): TS errors in WalletConnectContext tests

---

apps/mobile/src/features/ExecuteTx/components/ExecuteProcessing.tsx
apps/mobile/src/features/ExecuteTx/components/ExecuteTransaction.tsx
apps/mobile/src/features/TxHistory/TxHistory.container.tsx
apps/mobile/src/hooks/useSafeInfo.ts

Resolves [MOB-117](https://linear.app/safe-global/issue/MOB-117/mobile-update-safe-info-and-queuehistory-fetch-logic)
- Adds a `polling_interval` to fetching the safe info
- Adds the `txHistoryTag` as a dependency to the history query
- Adds a `router.dismissAll` when executing a transaction
2. Execute a transaction
3. Execute another one
4. Observe no error message regarding the nonce
5. Observe the history updates after a transaction has been executed
---

fix(Mobile): Poll safe info and update history

---

packages/store/README.md

Gerate looks like was intended to be Generate

docs: fix minor typo in readme

---

apps/mobile/src/features/Signer/Signer.container.tsx
apps/mobile/src/features/Signer/components/SignerView.tsx

Ads a "delete connection" button for ledger signers. This way a user can "Disassociate" a created ledger connection. 
partially resolves https://linear.app/safe-global/issue/COR-538/mobile-implement-ledger-support#comment-da4b6584
Import a ledger signer. Then On the signers list click on that ledger signer and you should see a delete button. I also added the ledger icon for such signers.
---

feat(mobile): add a delete ledger connection option

---

apps/mobile/src/features/Ledger/LedgerAddresses.container.tsx
apps/mobile/src/features/Ledger/hooks/useImportLedgerAddress.test.ts
apps/mobile/src/features/Ledger/hooks/useImportLedgerAddress.ts
apps/mobile/src/store/__tests__/signersSlice.test.ts
apps/mobile/src/store/signersSlice.ts

Currently the imported ledger address would end up being "Singer-{last 4 digits of address}". With this PR the imported address would be stored as "{LEDGER device name} + {last 4 digits of address}"
Resolves https://linear.app/safe-global/issue/COR-538/mobile-implement-ledger-support#comment-34c3abb8
I had to refactor the addSignerWithEffects hook to accept the passed name instead of always setting one itself.  
Add a ledger signer and observe that the signer has a name that contains the Ledger device name. (note: if you've already imported this signer the name won't change as the contact exists in the address book)
---

feat(mobile): automatically set the name of imported ledger address

---

apps/mobile/app.config.js

Our testflight build was failng with:
> 0683: Missing purpose string in Info.plist. Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “DevSafeMobile.app” bundle should contain a NSPhotoLibraryUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required.
Resolves https://linear.app/safe-global/issue/COR-635/fix-failing-ios-build
I think that this is a false positive as I'm not aware of us using the photo library anywhere. I thought that it is a …

fix(mobile): failing build in testflight
